<?
$this->addCssFile("style.css");

$this->addPageTitle($this->_('úprava miniatury'));
$this->addPageHeadline($this->_('úprava miniatury'));

$this->addJsPlugin(new JsPlugin_JCrop());
?>
<?$this->includeTpl("buttonback.phtml", true, array('link'=>$this->link()->route('editimages')));?>
<div id="editPhotoForm">
   <table class="formTable">
      <tr>
         <td>
            <p><?=$this->_('Aktuální miniatura')?></p>
            <?=vve_tpl_image_tag($this->category()->getModule()->getDataDir().$this->subdir.Photogalery_Controller::DIR_SMALL
                    .DIRECTORY_SEPARATOR.$this->image->{PhotoGalery_Model_Images::COLUMN_FILE},
                    $this->image->{PhotoGalery_Model_Images::COLUMN_FILE}, Photogalery_Controller::MEDIUM_WIDTH)?>
         </td>
      </tr>
   </table>

   <form action="<?=$this->form->getAction()?>" method="post">
      <table class="formTable">
         <tr>
            <td id="cropImage">
               <p><?=$this->_('Myší vyberte oblast ze které se má vytvořit miniatura')?></p>
               <?=vve_tpl_image_tag($this->category()->getModule()->getDataDir().$this->subdir.Photogalery_Controller::DIR_MEDIUM
                       .DIRECTORY_SEPARATOR.$this->image->{PhotoGalery_Model_Images::COLUMN_FILE},
                       $this->image->{PhotoGalery_Model_Images::COLUMN_FILE}, Photogalery_Controller::MEDIUM_WIDTH)?>
            </td>
         </tr>
         <tr>
            <td>
               <h2><?=$this->_('Náhled')?></h2>
               <p id="preview" style="overflow:hidden; width:<?=Photogalery_Controller::SMALL_WIDTH?>px;
                  height:<?=Photogalery_Controller::SMALL_WIDTH?>px;">
                  <img src="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir.Photogalery_Controller::DIR_MEDIUM
                               .URL_SEPARATOR.$this->image->{PhotoGalery_Model_Images::COLUMN_FILE}?>"
                       alt="<?=$this->image->{PhotoGalery_Model_Images::COLUMN_FILE}?>" />
               </p>
            </td>
         </tr>
      </table>
      <table class="formTable">
         <tr class="hidden">
            <th class="formLabels"></th>
            <td class="formControlls">
               <?
               $this->form->start_x->setValues(0);
               print($this->form->start_x->controll());
               ?>
            </td>
         </tr>
         <tr class="hidden">
            <th class="formLabels"></th>
            <td class="formControlls">
               <?
               $this->form->start_y->setValues(0);
               print($this->form->start_y->controll())
                       ?>
            </td>
         </tr>
         <tr class="hidden">
            <th class="formLabels"></th>
            <td class="formControlls">
               <?
               $this->form->width->setValues(Photogalery_Controller::SMALL_WIDTH);
               print($this->form->width->controll())
                       ?>
            </td>
         </tr>
         <tr class="hidden">
            <th class="formLabels"></th>
            <td class="formControlls">
               <?
               $this->form->height->setValues(Photogalery_Controller::SMALL_HEIGHT);
               print($this->form->height->controll())
                       ?>
            </td>
         </tr>
         <tr>
            <th class="formLabels"></th>
            <td class="formControlls">
               <?=$this->form->save->controll()?>
            </td>
         </tr>
         <tr>
            <td class="formLabels">
               <?=$this->form->goBack->label()."<br />";?>
            </td>
            <td class="formControlls">
               <?=$this->form->goBack->controll();?>
            </td>
         </tr>
         </tbody>
      </table>
   </form>
   <script type="text/javascript">
      /* <![CDATA[ */
      function showPreview(coords){
         var rx = <?=Photogalery_Controller::SMALL_WIDTH;?>;
         var ry = <?=Photogalery_Controller::SMALL_HEIGHT;?>;
         if (parseInt(coords.w) > 0){
            var rx = rx/coords.w;
            var ry = ry/coords.h;

            $('#preview img').css({
               width: Math.round(rx * $("#cropImage img").attr('width')) + 'px',
               height: Math.round(ry * $("#cropImage img").attr('height')) + 'px',
               marginLeft: '-' + Math.round(rx * coords.x) + 'px',
               marginTop: '-' + Math.round(ry * coords.y) + 'px'
            });
         }
         $('#image_start_x').val(coords.x);
         $('#image_start_y').val(coords.y);
         $('#image_width').val(coords.w);
         $('#image_height').val(coords.h);
      };

      jQuery(document).ready(function() {
         $(function(){
            $('#cropImage img').Jcrop({
               onChange: showPreview,
               onSelect: showPreview,
               minSize: [ <?=Photogalery_Controller::SMALL_WIDTH;?>, <?=Photogalery_Controller::SMALL_HEIGHT;?> ],
               setSelect: [ 0, 0, <?=Photogalery_Controller::SMALL_WIDTH;?>, <?=Photogalery_Controller::SMALL_HEIGHT;?> ],
               aspectRatio: 1
            });
         });

      });
      /* ]]> */
   </script>
</div>
<?$this->includeTpl("buttonback.phtml", true, array('link'=>$this->link()->route('editphotos')));?>