<?
$h = $this->tr('Vytvořit newsletter');
$this->addPageTitle($h);
?>
<h1><?=$h?></h1>
<?=$this->includeTpl('navigation.phtml');?>
<div class="main-content-detail" id="sendMailForm">
<? 
$this->form->send->cancel->html()->addClass('cancel');
$this->form->send->cancel->html()->setAttrib('onclick', 'return confirm(\''.$this->tr('Opravdu zrušit změny?').'\')');
echo $this->form;
?>
</div>
<? 
$jq = new JsPlugin_JQuery();
$jq->addUIDatepicker();
$this->addJsPlugin($jq);
?>
<script type="text/javascript">
   $(document).ready(function(){
      $('.newsletter_compose_senddate_class').datepicker({});
   });
</script>
