<?php 
$items = array(
   $this->tr('Vytvořit newsletter') => array('link' => (string)$this->link()->route(), 'icon' => 'plus'),
   $this->tr('Seznam newsletterů') => array('link' => (string)$this->link()->route('list'), 'icon' => 'list'),
//    $this->tr('Fronta odesílání') => array('link' => (string)$this->link()->route('queue'), 'icon' => 'email_go.png'),
   $this->tr('Šablony') => array('link' => (string)$this->link()->route('tpls'), 'icon' => 'file-text-o'),
   );
$this->includeTpl('module_navigation.phtml', true, array('items' => $items));