<?php 
$this->items = array(
   $this->tr('Vytvořit newsletter') => array('link' => (string)$this->link()->route(), 'icon' => 'email_edit.png'),
   $this->tr('Seznam newsletterů') => array('link' => (string)$this->link()->route('list'), 'icon' => 'application_view_list.png'),
//    $this->tr('Fronta odesílání') => array('link' => (string)$this->link()->route('queue'), 'icon' => 'email_go.png'),
   $this->tr('Šablony') => array('link' => (string)$this->link()->route('tpls'), 'icon' => 'page_lightning.png'),
   );
$this->includeTpl('module_navigation.phtml', true);
?>