<?
$h = $this->tr('Seznam newsleterů');
$this->addPageTitle($h);
$jQuery = new JsPlugin_JQuery();
$this->addJsPlugin($jQuery);
$this->addCssFile('style.css');
?>
<h1><?=$h?></h1>
<?=$this->includeTpl('navigation.phtml');?>
<div class="main-content-list module-newsleters-list">
   <?if(!empty ($this->newsleters)) {?>
   <table class="templates-list full-width">
      <thead>
         <tr class="ui-widget-header">
            <th class="template-tb-name"><?=$this->tr('Název')?></th>
            <th class="template-tb-actions"></th>
         </tr>
      </thead>
   <?
      foreach ($this->templates as $template) {?>
      <tr class="ui-widget-content">
         <td class="template-tb-name"><?=$template->{MailsNewsletters_Model_Templates::COLUMN_NAME}?></td>
         <td class="template-tb-actions">
            <?
            $toolbox = clone $this->toolboxItem;
            $toolbox->editForm->setAction(
                  $this->link()->route('tplEdit', array('id' => $template->{MailsNewsletters_Model_Templates::COLUMN_ID}))->param('ajax', true)
                );
            $toolbox->previewTpl->setAction( $this->link()->route('tplPreview', array('id' => $template->{MailsNewsletters_Model_Templates::COLUMN_ID})) );
            $toolbox->form_delete_->getForm()->id->setValues( $template->{MailsNewsletters_Model_Templates::COLUMN_ID} );
            $toolbox->setTemplate(Template_Toolbox2::TEMPLATE_INLINE);
            echo $toolbox;
            ?>
         </td>
      </tr>
     <?}?>
   </table>
   <?} else {?>
      <div class="admin-info-text"><? ps($this->tr('Není uložen žádný newsletter')); ?> </div>
   <?}?>
</div>
<div id="test-prw"></div>
<? 
$this->addJsPlugin(new JsPlugin_PrettyPhoto());
?>
<a rel="prettyPhoto"></a>
<script type="text/javascript">
   /* <![CDATA[ */
   $(document).ready(function(){
      // init prettyphoto
      $("a[rel^='prettyPhoto']").prettyPhoto({ social_tools: '' }); 
      
      $('form[name="previewTpl"]').submit(function(){
         var url = $(this).attr('action')+"&iframe=true&width=1000&height=500";
         //$('#test-prw').load(url);
         $.prettyPhoto.open(url,$(this).parents('tr.ui-widget-content').find('td.template-tb-name').text());
         return false;
      });
   });
   /* ]]> */
</script>
