<!DOCTYPE html>
<html>
<head>
   <title><?ps($this->title)?></title>
   <link rel="stylesheet" type="text/css" href="<?=Url_Request::getBaseWebDir(true)?>/stylesheets/normalize.css" />
   <style type="text/css">
      body { text-align: center;}
      #newsletter { width: 1000px; margin: 10px auto; text-align: left;}
   </style>
</head>
<body>
   <div id="newsletter">
      <?echo $this->cnt?>
   </div>
</body>
</html>