<?
$h = $this->template == null ? $this->tr('Vytvořit šablonu') : sprintf($this->tr('Úprava šablony %s'), $this->template->{MailsNewsletters_Model_Templates::COLUMN_NAME}) ;
$this->addPageTitle($h);
$this->addCssFile('style.css');
?>
<h1><?ps($h)?></h1>
<?=$this->includeTpl('navigation.phtml');?>
<div class="main-content-form-edit" id="mails-send-mail-form">
   <?
   echo $this->form;
    ?>
</div>



