<?php 
$h = $this->tr('Seznam šablon');
$this->addPageTitle($h);
$jQuery = new JsPlugin_JQuery();
$jQuery->addUIAccordion();
$this->addJsPlugin($jQuery);
$this->addFile('css://style.less');
?>
<h1><?php echo $h?></h1>
<?php echo $this->includeTpl('navigation.phtml');?>
<div class="main-content-list module-templates-list">
   <?php 
   $this->moduleButtons = array(
         array(
               'link' => $this->link()->route('tplAdd'),
               'title' => $this->tr('Vytvořit novou šablonu'),
               'icon' => 'plus',
               'name' => $this->tr('Vytvořit šablonu'),
         ),
         array(
               'link' => $this->link()->route('tplUpload'),
               'title' => $this->tr('Nahrát novou šablonu'),
               'icon' => 'upload',
               'name' => $this->tr('Nahrát šablonu'),
         ),
   );
   $this->includeTpl('modules/buttons.phtml', true);
   ?>
   <?php if(!empty ($this->templates)) {?>
   <table class="templates-list full-width table table-bordered table-hover">
      <thead>
         <tr class="">
            <th class="template-tb-name"><?php echo $this->tr('Název')?></th>
            <th class="template-tb-actions"></th>
         </tr>
      </thead>
   <?php 
      foreach ($this->templates as $template) {?>
      <tr class="">
         <td class="template-tb-name"><?php echo $template->{MailsNewsletters_Model_Templates::COLUMN_NAME}?></td>
         <td class="template-tb-actions">
            <?php 
            $toolbox = clone $this->toolboxItem;
            $toolbox->editForm->setAction(
                  $this->link()->route('tplEdit', array('id' => $template->{MailsNewsletters_Model_Templates::COLUMN_ID}))->param('ajax', true)
                );
            $toolbox->previewTpl->setAction( $this->link()->route('tplPreview', array('id' => $template->{MailsNewsletters_Model_Templates::COLUMN_ID})) );
            $toolbox->form_delete_->getForm()->id->setValues( $template->{MailsNewsletters_Model_Templates::COLUMN_ID} );
            $toolbox->setTemplate(Template_Toolbox2::TEMPLATE_INLINE);
            echo $toolbox;
            ?>
         </td>
      </tr>
     <?php }?>
   </table>
   <?php } else {?>
      <div class="admin-info-text"><?php  ps($this->tr('Není vložena žádná šablona')); ?> </div>
   <?php }?>
</div>
<div id="test-prw"></div>
<?php  
$this->includeTpl('components/modal.phtml', true, array(
    'large' => true,
    'id' => 'tpl-preview-modal',
    'close' => true,
    'header' => $this->tr('Náhled šablony <span class="tpl-name"></span>'),
    'content' => '<iframe frameborder="0" class="tpl-iframe-content"></iframe>',
));
?>
<a rel="prettyPhoto"></a>
<script type="text/javascript">
   /* <![CDATA[ */
   $(document).ready(function(){
      $('a.toolbox-button-previewTpl').on('click', function (e) {
         e.preventDefault();
         $('#tpl-preview-modal .tpl-iframe-content').prop('src', 'about:blank');
         $('#tpl-preview-modal').show();
         $('#tpl-preview-modal .tpl-name').text($(this).closest('tr').find('.template-tb-name').text());
         $('#tpl-preview-modal .tpl-iframe-content').prop('src', $(this).attr('href')+"?iframe=true");
         return false;
      });
   });
   /* ]]> */
</script>
