<?php 
$h = $this->tr('Seznam šablon');
$this->addPageTitle($h);
$jQuery = new JsPlugin_JQuery();
$jQuery->addUIAccordion();
$this->addJsPlugin($jQuery);
$this->addFile('css://style.less');
?>
<h1><?php echo $h?></h1>
<?php echo $this->includeTpl('navigation.phtml');?>
<div class="main-content-list module-templates-list">
   <?php 
   $this->moduleButtons = array(
         array(
               'link' => $this->link()->route('tplAdd'),
               'title' => $this->tr('Vytvořit novou šablonu'),
               'icon' => 'add.png',
               'name' => $this->tr('Vytvořit šablonu'),
         ),
         array(
               'link' => $this->link()->route('tplUpload'),
               'title' => $this->tr('Nahrát novou šablonu'),
               'icon' => 'go-up.png',
               'name' => $this->tr('Nahrát šablonu'),
         ),
   );
   $this->includeTpl('modules/buttons.phtml', true);
   ?>
   <?php if(!empty ($this->templates)) {?>
   <table class="templates-list full-width">
      <thead>
         <tr class="ui-widget-header">
            <th class="template-tb-name"><?php echo $this->tr('Název')?></th>
            <th class="template-tb-actions"></th>
         </tr>
      </thead>
   <?php 
      foreach ($this->templates as $template) {?>
      <tr class="ui-widget-content">
         <td class="template-tb-name"><?php echo $template->{MailsNewsletters_Model_Templates::COLUMN_NAME}?></td>
         <td class="template-tb-actions">
            <?php 
            $toolbox = clone $this->toolboxItem;
            $toolbox->editForm->setAction(
                  $this->link()->route('tplEdit', array('id' => $template->{MailsNewsletters_Model_Templates::COLUMN_ID}))->param('ajax', true)
                );
            $toolbox->previewTpl->setAction( $this->link()->route('tplPreview', array('id' => $template->{MailsNewsletters_Model_Templates::COLUMN_ID})) );
            $toolbox->form_delete_->getForm()->id->setValues( $template->{MailsNewsletters_Model_Templates::COLUMN_ID} );
            $toolbox->setTemplate(Template_Toolbox2::TEMPLATE_INLINE);
            echo $toolbox;
            ?>
         </td>
      </tr>
     <?php }?>
   </table>
   <?php } else {?>
      <div class="admin-info-text"><?php  ps($this->tr('Není vložena žádná šablona')); ?> </div>
   <?php }?>
</div>
<div id="test-prw"></div>
<?php  
$this->addJsPlugin(new JsPlugin_PrettyPhoto());
?>
<a rel="prettyPhoto"></a>
<script type="text/javascript">
   /* <![CDATA[ */
   $(document).ready(function(){
      // init prettyphoto
      $("a[rel^='prettyPhoto']").prettyPhoto({ social_tools: '' }); 
      
      $('a.toolbox-button-previewTpl').click(function(){
         var url = $(this).attr('href')+"&iframe=true&width=1000&height=500";
         //$('#test-prw').load(url);
         $.prettyPhoto.open(url,$(this).parents('tr.ui-widget-content').find('td.template-tb-name').text());
         return false;
      });
   });
   /* ]]> */
</script>
