CREATE TABLE IF NOT EXISTS `{PREFIX}actions` (
  `id_action` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `id_category` smallint(5) unsigned NOT NULL,
  `id_user` smallint(5) unsigned NOT NULL,
  `name_cs` varchar(50) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `subname_cs` varchar(200) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL,
  `text_cs` text CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `text_clear_cs` text CHARACTER SET utf8 COLLATE utf8_czech_ci,
  `urlkey_cs` varchar(200) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL,
  `note_cs` varchar(500) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL,
  `name_sk` varchar(50) CHARACTER SET utf8 COLLATE utf8_slovak_ci NOT NULL,
  `subname_sk` varchar(200) CHARACTER SET utf8 COLLATE utf8_slovak_ci DEFAULT NULL,
  `text_sk` text CHARACTER SET utf8 COLLATE utf8_slovak_ci NOT NULL,
  `text_clear_sk` text CHARACTER SET utf8 COLLATE utf8_slovak_ci,
  `urlkey_sk` varchar(200) CHARACTER SET utf8 COLLATE utf8_slovak_ci DEFAULT NULL,
  `note_sk` varchar(500) CHARACTER SET utf8 COLLATE utf8_slovak_ci DEFAULT NULL,
  `name_en` varchar(50) DEFAULT NULL,
  `subname_en` varchar(200) DEFAULT NULL,
  `text_en` text,
  `text_clear_en` text,
  `urlkey_en` varchar(200) DEFAULT NULL,
  `note_en` varchar(500) DEFAULT NULL,
  `name_de` varchar(50) DEFAULT NULL,
  `subname_de` varchar(200) DEFAULT NULL,
  `text_de` text,
  `text_clear_de` text,
  `urlkey_de` varchar(200) DEFAULT NULL,
  `note_de` varchar(500) DEFAULT NULL,
  `author` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `start_date` date NOT NULL,
  `stop_date` date DEFAULT NULL,
  `image` varchar(200) DEFAULT NULL,
  `time` time DEFAULT NULL,
  `price` int(11) DEFAULT NULL,
  `preprice` smallint(6) DEFAULT NULL,
  `place` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `public` tinyint(1) NOT NULL DEFAULT '1',
  `time_add` datetime NOT NULL,
  `changed` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_action`),
  UNIQUE KEY `urlkey_cs` (`urlkey_cs`),
  UNIQUE KEY `urlkey_de` (`urlkey_de`),
  KEY `id_user` (`id_user`),
  FULLTEXT KEY `label_cs` (`name_cs`),
  FULLTEXT KEY `label_en` (`name_en`),
  FULLTEXT KEY `label_de` (`name_de`),
  FULLTEXT KEY `text_clear_cs` (`text_clear_cs`),
  FULLTEXT KEY `text_clear_en` (`text_clear_en`),
  FULLTEXT KEY `text_clear_de` (`text_clear_de`),
  FULLTEXT KEY `place` (`place`),
  FULLTEXT KEY `subname_en` (`subname_en`),
  FULLTEXT KEY `subname_cs` (`subname_cs`),
  FULLTEXT KEY `subname_de` (`subname_de`),
  FULLTEXT KEY `author` (`author`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;