CREATE TABLE IF NOT EXISTS `{PREFIX}actions` (
  `id_action` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `id_category` smallint(5) unsigned NOT NULL,
  `id_user` smallint(5) unsigned NOT NULL,
  `action_name_cs` varchar(50) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL,
  `action_subname_cs` varchar(200) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL,
  `action_text_cs` text CHARACTER SET utf8 COLLATE utf8_czech_ci,
  `action_text_clear_cs` text CHARACTER SET utf8 COLLATE utf8_czech_ci,
  `action_urlkey_cs` varchar(200) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL,
  `action_note_cs` varchar(500) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL,
  `action_name_sk` varchar(50) CHARACTER SET utf8 COLLATE utf8_slovak_ci DEFAULT NULL,
  `action_subname_sk` varchar(200) CHARACTER SET utf8 COLLATE utf8_slovak_ci DEFAULT NULL,
  `action_text_sk` text CHARACTER SET utf8 COLLATE utf8_slovak_ci,
  `action_text_clear_sk` text CHARACTER SET utf8 COLLATE utf8_slovak_ci,
  `action_urlkey_sk` varchar(200) CHARACTER SET utf8 COLLATE utf8_slovak_ci DEFAULT NULL,
  `action_note_sk` varchar(500) CHARACTER SET utf8 COLLATE utf8_slovak_ci DEFAULT NULL,
  `action_name_en` varchar(50) DEFAULT NULL,
  `action_subname_en` varchar(200) DEFAULT NULL,
  `action_text_en` text,
  `action_text_clear_en` text,
  `action_urlkey_en` varchar(200) DEFAULT NULL,
  `action_note_en` varchar(500) DEFAULT NULL,
  `action_name_de` varchar(50) DEFAULT NULL,
  `action_subname_de` varchar(200) DEFAULT NULL,
  `action_text_de` text,
  `action_text_clear_de` text,
  `action_urlkey_de` varchar(200) DEFAULT NULL,
  `action_note_de` varchar(500) DEFAULT NULL,
  `action_author` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `action_start_date` date NOT NULL,
  `action_stop_date` date DEFAULT NULL,
  `action_image` varchar(200) DEFAULT NULL,
  `action_time` time DEFAULT NULL,
  `action_price` int(11) DEFAULT NULL,
  `action_preprice` smallint(6) DEFAULT NULL,
  `action_place` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `action_public` tinyint(1) NOT NULL DEFAULT '1',
  `action_time_add` datetime NOT NULL,
  `action_changed` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `action_id_form` int(11) DEFAULT NULL,
  `action_form_show_to_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id_action`),
  KEY `id_user` (`id_user`),
  KEY `urlkey_de` (`action_urlkey_de`),
  KEY `urlkey_cs` (`action_urlkey_cs`),
  FULLTEXT KEY `label_cs` (`action_name_cs`),
  FULLTEXT KEY `label_en` (`action_name_en`),
  FULLTEXT KEY `label_de` (`action_name_de`),
  FULLTEXT KEY `text_clear_cs` (`action_text_clear_cs`),
  FULLTEXT KEY `text_clear_en` (`action_text_clear_en`),
  FULLTEXT KEY `text_clear_de` (`action_text_clear_de`),
  FULLTEXT KEY `place` (`action_place`),
  FULLTEXT KEY `subname_en` (`action_subname_en`),
  FULLTEXT KEY `subname_cs` (`action_subname_cs`),
  FULLTEXT KEY `subname_de` (`action_subname_de`),
  FULLTEXT KEY `author` (`action_author`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
