ALTER TABLE `{PREFIX}actions`
CHANGE COLUMN `name_cs` `name_cs` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL  ,
CHANGE COLUMN `note_cs` `note_cs` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL  ,
CHANGE COLUMN `name_sk` `name_sk` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_slovak_ci' NULL DEFAULT NULL  ,
CHANGE COLUMN `name_en` `name_en` VARCHAR(200) NULL DEFAULT NULL  ,
CHANGE COLUMN `name_de` `name_de` VARCHAR(200) NULL DEFAULT NULL  ,
CHANGE COLUMN `text_cs` `text_cs` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_czech_ci' NULL DEFAULT NULL ,
CHANGE COLUMN `text_sk` `text_sk` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_slovak_ci' NULL DEFAULT NULL ;

