<?php  // načtení detailu
$this->addPageTitle($this->_('Archiv'));
$this->addPageHeadline($this->_('Archiv'));

$jQuery = new JsPlugin_JQuery();
$jQuery->addUIAccordion();
$this->addJsPlugin($jQuery);
?>
<div>
   <div id="articlesArchiveList">
      <?php 
      foreach ($this->articles as $year => $rows) {?>
      <h2 class="archiveYearLabel year<?php echo $year?>"><a href="#"><?php echo $year?></a></h2>
      <div class="">
         <ul>
         <?php foreach ($rows as $row){?>
            <li>
               <a href="<?php echo $this->link()->route('detail', array('urlkey' => $row->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
                  title="<?php echo $row->{Articles_Model_Detail::COLUMN_NAME}?>"><?php echo $row->{Articles_Model_Detail::COLUMN_NAME}?></a>
            </li>
         <?php }?>
         </ul>
      </div>
      <?php }?>
   </div>
   <hr class="reseter" />
   <script type="text/javascript">

      $(function() {
         $("#articlesArchiveList").accordion({
            collapsible: true
         });
      });
   </script>
</div>
<?php $this->includeTpl("buttonback.phtml", true);?>
