<div class="articlesList">
   <?php if(!empty ($this->articles)) {
      foreach ($this->articles as $article) {
         $showClass = $public = null;
         if($article->{Articles_Model_Detail::COLUMN_PUBLIC} == 0) {
            $showClass = 'noPublicArticle';
            $public = $this->_('Nezveřejněn');
         }
         $editTime = new DateTime($article->{Articles_Model_Detail::COLUMN_ADD_TIME});
         ?>
   <div class="<?php echo $showClass?>">
      <h2><a href="<?php echo $this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
             title="<?php echo htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>"><?php echo htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>&nbsp;
            <span class="smallFont">
                     <?php echo strftime("%x %X", $editTime->format("U"))?> - <?php echo $article->{Model_Users::COLUMN_USERNAME}?></span>
         </a><?php echo '<span class="smallFont">'.$public.'</span>'?>
      </h2>
            <?php  // nalezneme v textu první obrázek, pokud ano vykreslíme jej
            $out = array();
            preg_match('/< *[img][^>]*[src] *= *[\"\']{0,1}([^"\'\ >]*)/i', $article->{Articles_Model_Detail::COLUMN_TEXT}, $out);
            if(!empty ($out) AND $out[1] != '0') {?>
      <div class="imageBox">
                  <?php echo vve_tpl_image_tag($out[1], "article title image", 80, 80);?>
      </div>
               <?php }?>

            <?php //print (vve_tpl_xhtml_cut(strip_tags('img', $article->{Articles_Model_Detail::COLUMN_TEXT}), 650));?>
            <?php echo $article->{Articles_Model_Detail::COLUMN_TEXT};?>
      <hr class="reseter" />
      <br />
   </div>
         <?php }
   } else {
      print ($this->_('Není vložen žádný článek'));
   }?>
</div>
