<?
// načtení detailu
Template_Core::addToPageTitle($this->course->{Courses_Model_Courses::COLUMN_NAME});
Template_Core::setPageKeywords($this->course->{Courses_Model_Courses::COLUMN_KEYWORDS});
Template_Core::setPageDescription($this->course->{Courses_Model_Courses::COLUMN_DESCRIPTION});

$dateStart = new DateTime($this->course->{Courses_Model_Courses::COLUMN_DATE_START});
if ($this->course->{Courses_Model_Courses::COLUMN_DATE_STOP} != null) {
   $dateStop = new DateTime($this->course->{Courses_Model_Courses::COLUMN_DATE_STOP});
}
// který typ
switch ($this->course->{Courses_Model_Courses::COLUMN_TYPE}) {
   case Courses_Controller::TYPE_CONFERENTION:
      $type = 'konference';
      break;
   case Courses_Controller::TYPE_SEMINARE:
      $type = 'semináře';
      break;
   default:
      $type = 'kurzu';
      break;
}

?>
<style type="text/css">
   .module-courses-detail-params .course-param, .course-lecturer-name {
      font-weight: bold;
      margin-right: 1em;
   }
   .module-courses-detail-params li {
      list-style-type: circle;
      margin-left: 2em;
   }
</style>
<h1><?=$this->course->{Courses_Model_Courses::COLUMN_NAME}?></h1>
<div class="main-content-detail module-courses-detail">
   <?
   echo $this->course->{Courses_Model_Courses::COLUMN_TEXT_SHORT}.'<br />';
   if($this->courseImage != null){?>
      <img style="float: right; width: 150px;" src="<?=$this->courseImage?>" alt="obrázek kurzu <?=$this->course->{Courses_Model_Courses::COLUMN_NAME}?>" />
   <?
   }
   ?>
   <ul class="module-courses-detail-params">
      <li>
         <?
         echo '<span class="course-param">'.$this->_('Termín ').$type . ":</span>";
         echo vve_date("%x", new DateTime($this->course->{Courses_Model_Courses::COLUMN_DATE_START}));
         if ($this->course->{Courses_Model_Courses::COLUMN_DATE_STOP} != null) {
            echo ' - ' . vve_date("%x", new DateTime($this->course->{Courses_Model_Courses::COLUMN_DATE_STOP}));
         }
         ?>
      </li>
      <?if($this->course->{Courses_Model_Courses::COLUMN_TIME_START} != null){?>
      <li><? echo '<span class="course-param">'.$this->_('Předpokládaný čas začátku') . ":</span>" . $this->course->{Courses_Model_Courses::COLUMN_TIME_START}; ?></li>
      <?}?>
      <li><?echo '<span class="course-param">'.$this->_('Místo konání') . ":</span>" . $this->course->{Courses_Model_Courses::COLUMN_PLACE};?></li>
      <?if ($this->course->{Courses_Model_Courses::COLUMN_HOURS_LEN} != 0) {
            echo '<li>'
            . '<span class="course-param">'. $this->_('Délka ').$type . ":</span>"
            . $this->course->{Courses_Model_Courses::COLUMN_HOURS_LEN} . '&nbsp;' . $this->_('hodin')
            . '</li>';
      }
      if ($this->course->{Courses_Model_Courses::COLUMN_PRICE} != 0) {
            echo '<li>'
            . '<span class="course-param">'. $this->_('Cena ').$type . ":</span>"
            . number_format($this->course->{Courses_Model_Courses::COLUMN_PRICE},0,',',' ') . '&nbsp;' . $this->_('Kč')
            . '</li>';
      }
      if($this->course->{Courses_Model_Courses::COLUMN_SEATS} != 0){?>
      <li><?echo '<span class="course-param">'.$this->_('Kapacita') . ":</span>" . $this->course->{Courses_Model_Courses::COLUMN_SEATS} . '&nbsp;' . $this->_('míst');?></li>
      <li><?echo '<span class="course-param">'.$this->_('Volných') . ":</span>" . $this->freeSeats . '&nbsp;' . $this->_('míst');?></li>
      <?}
      // akreditace
      if($this->course->{Courses_Model_Courses::COLUMN_AKREDIT_MPSV} != null){?>
      <li><? echo '<span class="course-param">'.$this->_('Akreditace MPSV') . ":</span>" . $this->course->{Courses_Model_Courses::COLUMN_AKREDIT_MPSV}; ?></li>
      <?}
      if($this->course->{Courses_Model_Courses::COLUMN_AKREDIT_MSMT} != null){?>
      <li><? echo '<span class="course-param">'.$this->_('Akreditace MŠMT') . ":</span>" . $this->course->{Courses_Model_Courses::COLUMN_AKREDIT_MSMT}; ?></li>
      <?}
      if($this->course->{Courses_Model_Courses::COLUMN_TAGRT_GROUPS} != null){?>
      <li><? echo '<span class="course-param">'.$this->_('Cílové skupiny') . ":</span>" . $this->course->{Courses_Model_Courses::COLUMN_TAGRT_GROUPS}; ?></li>
      <?}

      ?>
      </ul>
      <br />
      <div class="main-content-text">
         <?=$this->course->{Courses_Model_Courses::COLUMN_TEXT} ?>
      </div>
      <hr class="reseter" />
      <br />

      <?if($this->isPrivate === true AND $this->course->{Courses_Model_Courses::COLUMN_TEXT_PRIVATE} != null){?>
      <h2><?=$this->_('Neveřejná data');?></h2>
      <div class="main-content-text">
         <?=$this->course->{Courses_Model_Courses::COLUMN_TEXT_PRIVATE} ?>
      </div>
      <hr class="reseter" />
      <br />
      <?}?>

      <h2><?=$this->_('Lektoři ').$type?></h2>
      <?
      $this->includeTpl('onlylist.phtml', false, array('lecturers' => $this->lecturers,'hE' => 'span', 'hEClass' => 'course-lecturer-name'), 'lecturers');
         /*foreach ($this->lecturers as $lecturer) {
            if($lecturer->{Lecturers_Model::COLUMN_IMAGE} != null){
            ?>
         <p style="float: left">
            <img src="<?=Url_Request::getBaseWebDir().VVE_DATA_DIR.URL_SEPARATOR
            .  Lecturers_Controller::DATA_DIR.URL_SEPARATOR.$lecturer->{Lecturers_Model::COLUMN_IMAGE}?>" alt="" />
         </p>
         <?}?>
         <span class="course-lecturer-name">
         <?
         if($lecturer->{Lecturers_Model::COLUMN_DEGREE} != null)
            echo $lecturer->{Lecturers_Model::COLUMN_DEGREE}.' &nbsp;';
         echo $lecturer->{Lecturers_Model::COLUMN_NAME}.'&nbsp;';
         echo $lecturer->{Lecturers_Model::COLUMN_SURNAME};
         ?>
            </span><br />
            <?=$lecturer->{Lecturers_Model::COLUMN_TEXT};?>
         <hr class="reseter" />
         <br />
         <?
         }*/
         ?>
   <?
         $this->includeTpl("buttonback.phtml", true, array('link' => $this->link()->clear()->route(), 'text' => $this->_('Zpět na seznam kurzů')));
         echo '<br />';
         echo $this->toolbox;
      if($this->formReg != null){$this->includeTpl("registration.phtml");}
   ?>
</div>

