<?
$this->addCssFile("style.css");
// do titulku
if($this->edit) {
   $h = $this->_('Úprava položky');
   $this->addPageTitle($h);
} else {
   $h = $this->_('Přidání položky');
   $this->addPageTitle($h);
}
// donastavení formuláře
$this->form->textShort->html()->setAttrib('cols', 70)->setAttrib('rows', 10);
$this->form->text->html()->setAttrib('cols', 70)->setAttrib('rows', 30);
$this->form->textPrivate->html()->setAttrib('cols', 70)->setAttrib('rows', 30);
$this->form->name->html()->setAttrib('size', 60);
$this->form->place->html()->setAttrib('size', 60);
$this->form->targetGroups->html()->setAttrib('size', 60);
$this->form->akredMPSV->html()->setAttrib('size', 60);
$this->form->akredMSMT->html()->setAttrib('size', 60);
$this->form->urlkey->html()->setAttrib('size', 60);
$this->form->metaKeywords->html()->setAttrib('size', 60);
$this->form->metaDesc->html()->setAttrib('cols', 63)->setAttrib('rows', 3);

$jQuery = new JsPlugin_JQuery();
$jQuery->addUIDatepicker();
$jQuery->addUIAutoComplete();

$this->addJsPlugin($jQuery);

// doplnění obrázku
if($this->courseImage != null){
   $this->form->deleteImg->setSubLabel($this->_('Uloženo').':<br /><img src="'.$this->courseImage.'" height="50" />');
}
?>
<h1><?=$h?></h1>
<div id="editArticleForm">
   <?print($this->form);?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         $.datepicker.setDefaults(['<?=Locales::getLang()?>'] ) ;
         $("input[name=course_dateStart]").datepicker();
         $("input[name=course_dateStop]").datepicker();

         $("#course_place").autocomplete({
            source: "<?=$this->link()->route('placesList')?>",
            minLength: 2
         });

      });
      /* ]]> */
   </script>
</div>
