<?php 
$this->addCssFile('style.css');
if($this->isAllList == true){
   $this->addPageTitle($this->_('Seznam všech kurzů'));
   $h1 = $this->_('Seznam všech kurzů');
} else {
   $h1 = $this->_('Seznam aktuálních kurzů');
}
?>
<style type="text/css">
   .table td {
      border: 1px solid silver;
   }
   .table td {
      padding: 4px;
   }
</style>
<h1><?php echo $h1?></h1>
<div class="main-content-list module-courses-list">
   <?php if(!empty ($this->courses)) {?>
   <table class="table">
      <thead>
         <tr>
            <th width="300"><?php echo $this->_('název')?></th>
            <th width="100"><?php echo $this->_('termín')?></th>
            <th><?php echo $this->_('délka')?></th>
            <th><?php echo $this->_('cena')?></th>
         </tr>
      </thead>
      <tbody>
      <?php 
      foreach ($this->courses as $course) {?>
         <tr class="<?php if($course->{Courses_Model_Courses::COLUMN_IN_LIST} == false) echo 'course-not-in-list-row'?>">
            <td>
               <?php 
               if($course->{Courses_Model_Courses::COLUMN_IS_NEW} == true){?>
               <img src="images/icons/new-16x16.png" alt="new" width="16"/>
               <?php 
               }
               if($course->{Courses_Model_Courses::COLUMN_TEXT_SHORT} != null
                  OR $course->{Courses_Model_Courses::COLUMN_TEXT_SHORT} != ''){
                  $title = trim(strip_tags($course->{Courses_Model_Courses::COLUMN_TEXT_SHORT}));
               } else {
                  $title = $course->{Courses_Model_Courses::COLUMN_NAME};
               }
               ?>
               <a href="<?php echo $this->link()->route('detailCourse', array('urlkey' => $course->{Courses_Model_Courses::COLUMN_URLKEY}))?>"
                  title="<?php echo htmlspecialchars($title)?>"
                  ><?php echo $course->{Courses_Model_Courses::COLUMN_NAME}?></a><?php 
                  if($course->{Courses_Model_Courses::COLUMN_TYPE} == Courses_Controller::TYPE_CONFERENTION) echo ' (konference)';
                  else if($course->{Courses_Model_Courses::COLUMN_TYPE} == Courses_Controller::TYPE_SEMINARE) echo ' (seminář)';
                  ?>
            </td>
            <td align="center">
               <?php 
               echo vve_date("%x", new DateTime($course->{Courses_Model_Courses::COLUMN_DATE_START}));
               if($course->{Courses_Model_Courses::COLUMN_DATE_STOP} != null){
                  echo '<br /> - <br />'.vve_date("%x", new DateTime($course->{Courses_Model_Courses::COLUMN_DATE_STOP}));
               }
               ?>
            </td>
            <td align="center">
               <?php if($course->{Courses_Model_Courses::COLUMN_HOURS_LEN} != null){
                  echo $course->{Courses_Model_Courses::COLUMN_HOURS_LEN}.' '.$this->_('hodin');
               }?>
            </td>
            <td align="right">
               <?php if($course->{Courses_Model_Courses::COLUMN_PRICE} != null){
                  echo number_format($course->{Courses_Model_Courses::COLUMN_PRICE}, 0, ',', ' ').' '.$this->_('Kč');
               }?>
            </td>
         </tr>
     <?php }?>
      </tbody>
   </table>
   <br />
   <?php 
   } else {
      print ($this->_('Není vložen žádný kurz'));
   }?>
   <?php if($this->isAllList == true){?>
   <a href="<?php echo $this->link()->route(null);?>" title="<?php echo $this->_('Seznam aktuálních kurzů');?>"
      ><?php echo $this->_('Seznam aktuálních kurzů');?></a>
   <?php 
   } else {?>
   <a href="<?php echo $this->link()->route('listAllCourses');?>" title="<?php echo $this->_('Seznam všech kurzů');?>"
      ><?php echo $this->_('Seznam všech kurzů');?></a>
   <?php }
   echo $this->toolbox;
   ?>
</div>
