<?
$this->addCssFile('style.css');
if($this->isAllList == true){
   $this->addPageTitle($this->_('Seznam všech kurzů'));
   $h1 = $this->_('Seznam všech kurzů');
} else {
   $h1 = $this->_('Seznam aktuálních kurzů');
}
?>
<style type="text/css">
   .table td {
      border: 1px solid silver;
   }
   .table td {
      padding: 4px;
   }
</style>
<h1><?=$h1?></h1>
<div class="main-content-list module-courses-list">
   <?if(!empty ($this->courses)) {?>
   <table class="table">
      <thead>
         <tr>
            <th width="300"><?=$this->_('název')?></th>
            <th width="100"><?=$this->_('termín')?></th>
            <th><?=$this->_('délka')?></th>
            <th><?=$this->_('cena')?></th>
         </tr>
      </thead>
      <tbody>
      <?
      foreach ($this->courses as $course) {?>
         <tr class="<?if($course->{Courses_Model_Courses::COLUMN_IN_LIST} == false) echo 'course-not-in-list-row'?>">
            <td>
               <?
               if($course->{Courses_Model_Courses::COLUMN_IS_NEW} == true){?>
               <img src="images/icons/new-16x16.png" alt="new" width="16"/>
               <?
               }
               if($course->{Courses_Model_Courses::COLUMN_TEXT_SHORT} != null
                  OR $course->{Courses_Model_Courses::COLUMN_TEXT_SHORT} != ''){
                  $title = trim(strip_tags($course->{Courses_Model_Courses::COLUMN_TEXT_SHORT}));
               } else {
                  $title = $course->{Courses_Model_Courses::COLUMN_NAME};
               }
               ?>
               <a href="<?=$this->link()->route('detailCourse', array('urlkey' => $course->{Courses_Model_Courses::COLUMN_URLKEY}))?>"
                  title="<?=htmlspecialchars($title)?>"
                  ><?=$course->{Courses_Model_Courses::COLUMN_NAME}?></a><?
                  if($course->{Courses_Model_Courses::COLUMN_TYPE} == Courses_Controller::TYPE_CONFERENTION) echo ' (konference)';
                  else if($course->{Courses_Model_Courses::COLUMN_TYPE} == Courses_Controller::TYPE_SEMINARE) echo ' (seminář)';
                  ?>
            </td>
            <td align="center">
               <?
               echo vve_date("%x", new DateTime($course->{Courses_Model_Courses::COLUMN_DATE_START}));
               if($course->{Courses_Model_Courses::COLUMN_DATE_STOP} != null){
                  echo '<br /> - <br />'.vve_date("%x", new DateTime($course->{Courses_Model_Courses::COLUMN_DATE_STOP}));
               }
               ?>
            </td>
            <td align="center">
               <?if($course->{Courses_Model_Courses::COLUMN_HOURS_LEN} != null){
                  echo $course->{Courses_Model_Courses::COLUMN_HOURS_LEN}.' '.$this->_('hodin');
               }?>
            </td>
            <td align="right">
               <?if($course->{Courses_Model_Courses::COLUMN_PRICE} != null){
                  echo number_format($course->{Courses_Model_Courses::COLUMN_PRICE}, 0, ',', ' ').' '.$this->_('Kč');
               }?>
            </td>
         </tr>
     <?}?>
      </tbody>
   </table>
   <br />
   <?
   } else {
      print ($this->_('Není vložen žádný kurz'));
   }?>
   <?if($this->isAllList == true){?>
   <a href="<?=$this->link()->route(null);?>" title="<?=$this->_('Seznam aktuálních kurzů');?>"
      ><?=$this->_('Seznam aktuálních kurzů');?></a>
   <?
   } else {?>
   <a href="<?=$this->link()->route('listAllCourses');?>" title="<?=$this->_('Seznam všech kurzů');?>"
      ><?=$this->_('Seznam všech kurzů');?></a>
   <?}
   echo $this->toolbox;
   ?>
</div>
