<?
$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
?>
<p class="panelLabel"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->panelObj()->getName())?>"><?=$this->panelObj()->getName()?></a></p>
<div style="<?=$backImg?>">
   <?foreach ($this->courses as $course) {?>
   <a href="<?=$this->link()->route('detail', array('urlkey' => $course->{Courses_Model_Courses::COLUMN_URLKEY}))?>"
      title="<?=htmlspecialchars($course->{Courses_Model_Courses::COLUMN_NAME})?>"><?=vve_tpl_truncate($course->{Courses_Model_Courses::COLUMN_NAME},25)?></a><br />
      <p><?=$course->{Courses_Model_Courses::COLUMN_TEXT_SHORT}?></p>
   <?}?>
</div>
<p class="panelLinkMore">
   <a href="<?=$this->link()?>"
      title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->_('Více')?></a>
</p>