<?
$jQuery = new JsPlugin_JQuery();
$this->addJsPlugin($jQuery);
?>
<style type="text/css">
   .course-regform-item {
      padding: 5px;
      clear: left;
      position: relative;
   }

   .course-regform-item-label {
      float: left;
      width: 200px;
   }

   .course-regform-item-help {
      display: none;
      position: absolute;
      top: 0;
      left: 400px;
      padding: 5px;
      margin-top: 5px;
      border: 1px solid #c77405;
      background-color: #F3D673;
      width: 150px;
      z-index: 10;
   }
   .course-regform-item-help span {
      background-image: url('images/icons/resultset_previous.png');
      position: absolute;
      top: 0px;
      left: -12px;
      width: 19px;
      height: 16px;
      display: block;
   }

</style>

<div class="module-courses-registration">
   <h2><?=$this->_('Závazná registrace')?></h2>
   <?// <form>
   echo $this->formReg->renderStart();?>

   <fieldset>
      <legend><?=$this->_('Základní informace')?></legend>
      <div class="course-regform-item">
         <?
         $this->formReg->name->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->name->label();
         echo $this->formReg->name->Controll();
         ?>
      </div>
      <div class="course-regform-item">
         <?
         $this->formReg->surname->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->surname->label();
         echo $this->formReg->surname->Controll();
         ?>
      </div>
      <div class="course-regform-item">
         <?
         $this->formReg->degree->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->degree->label();
         echo $this->formReg->degree->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('Váš titul (např. Mgr., DiS., Bc.)')?>
         </p>
      </div>
      <div class="course-regform-item">
         <?
         $this->formReg->grade->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->grade->label();
         echo $this->formReg->grade->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('např. sociální pracovník, pedagog, student')?>
         </p>
      </div>
      <div class="course-regform-item">
         <?
         $this->formReg->practiceLength->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->practiceLength->label();
         echo $this->formReg->practiceLength->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('jak dlouhou máte praxi v souvislosti s Vaším pracovním zařazením (např. 5 let, 7 měsíců...)')?>
         </p>
      </div>
      <div class="course-regform-item">
         <?
         $this->formReg->phone->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->phone->label();
         echo $this->formReg->phone->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('kontaktní telefon na Vás (pro případ sdělení náhlých změn těsně před kurzem, nefunkční email apod.)')?>
         </p>
      </div>
      <div class="course-regform-item">
         <?
         $this->formReg->mail->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->mail->label();
         echo $this->formReg->mail->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('Vaše emailová adresa, na kterou Vám potvrdíme přijetí přihlášky a budou zaslány bližší informace před konáním kurzu')?>
         </p>
      </div>
      <div class="course-regform-item">
         <?
         $this->formReg->regNewsletter->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->regNewsletter->label();
         echo $this->formReg->regNewsletter->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('(pokud chcete na uvedený e-mail získávat novinky o připravovaných kurzech, mimořádných slevách apod., zaškrtněte toto tlačítko)')?>
         </p>
      </div>
      <div class="course-regform-item">
         <?
         $this->formReg->note->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->note->label();
         $this->formReg->note->html()->setAttrib('rows', 5)->setAttrib('cols', 60);
         echo $this->formReg->note->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('Vaše poznámky či požadavky vztahující se ke kurzu (např. jako student bych chtěl požádat o studentskou slevu, uvedená praxe se vztahuje k době mého studia, nyní jsem nastoupila nově do zaměstnání, kde pracuji jako terénní pracovnice, fakturu prosím zašlete na tuto adresu: Jarní 5, která je odlišná od fakturační, předem děkuji)')?>
         </p>
      </div>
   </fieldset>

   <fieldset>
      <legend><?=$this->_('Fakturační údaje')?></legend>
      <div class="course-regform-item">
         <?
         $this->formReg->payType->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->payType->label();
         echo $this->formReg->payType->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('pokud Vás na kurz vysílá Vaše organizace a bude jej za Vás hradit, ponechte zatrženou možnost. V případě, že se kurzu účastníte jako soukromá osoba, zaškrtněte prosím tlačítko Soukromě')?>
         </p>
      </div>
      <div class="course-regform-item course-regform-pay-org">
         <?
         $this->formReg->orgName->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->orgName->label();
         $this->formReg->orgName->html()->setAttrib('size', 57);
         echo $this->formReg->orgName->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('název Vaší organizace s uvedením její právní formy (a.s., o.s., ...)')?>
         </p>
      </div>
      <div class="course-regform-item course-regform-pay-org">
         <?
         $this->formReg->orgAddress->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->orgAddress->label();
         $this->formReg->orgAddress->html()->setAttrib('rows', 5)->setAttrib('cols', 60);
         echo $this->formReg->orgAddress->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('adresa sídla Vaší organizace, na kterou bude vystavena a zaslána faktura ke kurzu')?>
         </p>
      </div>
      <div class="course-regform-item course-regform-pay-org">
         <?
         $this->formReg->orgICO->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->orgICO->label();
         echo $this->formReg->orgICO->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('IČ Vaší organizace')?>
         </p>
      </div>
      <div class="course-regform-item course-regform-pay-org">
         <?
         $this->formReg->orgPhone->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->orgPhone->label();
         echo $this->formReg->orgPhone->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('kontaktní telefon do Vaší organizace pro případ řešení nesrovnalostí na faktuře apod.')?>
         </p>
      </div>
      <div class="course-regform-item course-regform-pay-private">
         <?
         $this->formReg->privateAddress->htmlLabel()->addClass('course-regform-item-label');
         echo $this->formReg->privateAddress->label();
         $this->formReg->privateAddress->html()->setAttrib('rows', 5)->setAttrib('cols', 60);
         echo $this->formReg->privateAddress->Controll();
         ?>
         <p class="course-regform-item-help">
            <?=$this->_('Vaše adresa, na kterou bude vystavena a zaslána faktura ke kurzu')?>
         </p>
      </div>
      <div class="course-regform-item">
         <?
         echo $this->formReg->send->Controll();
         ?>
      </div>
   </fieldset>
   <?// </form>
   echo $this->formReg->renderEnd();
//   echo $this->formReg;
   ?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         $('.course-regform-item-help').append('<span></span>');

         function regFormChangePay($obj){
//            var selPay = $('input[name=course_reg_payType]:checked').val();
            var selPay = $obj.val();
            switch (selPay) {
               case 'organisation':
                  $('div.course-regform-pay-org').show();
                  $('div.course-regform-pay-private').hide();
                  break;
               default:
                  $('div.course-regform-pay-private').show();
                  $('div.course-regform-pay-org').hide();
         	}
         }
         regFormChangePay($('input[name=course_reg_payType]:checked'));

         $('input[name=course_reg_payType]').click(function(){
            regFormChangePay($(this));
            $(this).focus();
         });

         $('input[type=checkbox]').click(function(){$(this).focus()});

         $('.course-regform-item input, .course-regform-item textarea').focus(function(){
            var $help = $(this).parent().children('p.course-regform-item-help');
//            alert($(this).attr('type'));
            if($(this).attr('type') == 'radio'){
               $help.css('left', 400);
            } else {
               $help.css('left', $(this).width()+230);
            }
            $help.show();
         });

         $('.course-regform-item input, .course-regform-item textarea').blur(function(){
            var $help = $(this).parent().children('p.course-regform-item-help').hide();
         });
      });
      /* ]]> */
   </script>
</div>