<?
//$this->addCssFile("style.css");
// do titulku
if($this->edit) {
   $this->addPageTitle(sprintf($this->_('úprava skupiny %s'),$this->band->{Bands_Model::COLUMN_NAME}));
   $this->addPageHeadline(sprintf($this->_('úprava skupiny %s'),$this->band->{Bands_Model::COLUMN_NAME}));

   // přidáme obrázek do popisku
//   $img = new Html_Element('img');
//   $img->setAttrib('src', $this->category()->getModule()->getDataDir(true).$this->band->{Bands_Model::COLUMN_IMAGE})
//   ->setAttrib('alt' , $this->band->{Bands_Model::COLUMN_IMAGE})->setAttrib('height', 40);



} else {
   $this->addPageTitle($this->_('přidání skupiny'));
   $this->addPageHeadline($this->_('přidání skupiny'));
}
// donastavení formuláře
$this->form->text->html()->setAttrib('cols', 80)->setAttrib('rows', 30)->addClass("mceEditor");

$tinymce = new JsPlugin_TinyMce();
$tinymce->setCfgParam(JsPlugin_TinyMce::PARAM_THEME, JsPlugin_TinyMce::TINY_THEME_ADVANCED);
$this->addJsPlugin($tinymce);

?>

<div id="editArticleForm">
   <?print($this->form);?>
   <?if($this->edit === true){
      $this->includeTpl("buttonback.phtml", true, array('link' => $this->link()->route('detail')));
   } else {
      $this->includeTpl("buttonback.phtml", true, array('link' => $this->link()->clear()));
   }?>
</div>
