<?php 
//$this->addCssFile("style.css");
?>
<div class="bandsList">
   <?php if(!empty ($this->bands)) {
      foreach ($this->bands as $band) {
         $showClass = null;
         if($band->{Bands_Model::COLUMN_PUBLIC} == 0) {
            $showClass = 'article-list-no-public';
         }
         ?>
   <div class="article-list bands-list <?php echo $showClass?>">
      <h2><a href="<?php echo $this->link()->route('detail', array('urlkey' => $band->{Bands_Model::COLUMN_URLKEY}))?>"
             title="<?php echo htmlspecialchars($band->{Bands_Model::COLUMN_NAME})?>"><?php echo htmlspecialchars($band->{Bands_Model::COLUMN_NAME})?>&nbsp;
         </a>
      </h2>
      <div class="article-list-box-image bands-list-box-image">
                  <?php echo vve_tpl_image_tag($this->category()->getModule()->getDataDir(true)
                          .$band->{Bands_Model::COLUMN_IMAGE}, $band->{Bands_Model::COLUMN_IMAGE}, 200, 150);?>
      </div>

            <?php print vve_tpl_truncate(strip_tags($band->{Bands_Model::COLUMN_TEXT}), 640);?>
      <hr class="reseter" />
      <p style="float:left;"><?php echo $this->_('Zobrazeno')?>:&nbsp;<?php echo $band->{Bands_Model::COLUMN_SHOWED}?>&times;</p>
      <p style="text-align:right;">
         <a href="<?php echo $this->link()->route('detail', array('urlkey' => $band->{Bands_Model::COLUMN_URLKEY}))?>"
            title="<?php echo $band->{Bands_Model::COLUMN_NAME}?>">[&nbsp;<?php echo $this->_("více")?>&nbsp;]</a>
      </p>
      <br />
   </div>
         <?php }
      echo $this->scrollComp;
   } else {
      echo ($this->_('Není vložena žádná kapela'));
   }?>
   <?php echo $this->toolbox;// TOOLBOXY?>
</div>
