<?
$icon = null;
if($this->panelObj()->getIcon() != null) {
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null) {
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
?>

<p class="panel-box-label"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->panelObj()->getName())?>"><?=$this->panelObj()->getName()?></a></p>
<div class="panel-box-content" style="<?=$backImg?>">
   <?
   $width = 170; // ZDE MĚNIT VELIKOST !!!
   $height = ceil($width/4*3);
   ?>
   <a href="<?=$this->link()->route('detail', array('urlkey' => $this->band->{Bands_Model::COLUMN_URLKEY}))?>"
      title="<?=htmlspecialchars($this->band->{Bands_Model::COLUMN_NAME})?>"><?=$this->band->{Bands_Model::COLUMN_NAME}?></a>
   <!--[if !IE]> -->
   <object id="flash" type="application/x-shockwave-flash"  height="<?=$height?>" width="<?=$width?>"
           data="<?=$this->band->{Bands_Model::COLUMN_CLIPS}?>&hl=cs_CZ&fs=1&rel=0">
      <!-- <![endif]-->

      <!--[if IE]>
      <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
        codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0"
        width="<?=$width?>" height="<?=$height?>">
      <!--><!--dgx-->
      <param name="movie" value="<?=$this->band->{Bands_Model::COLUMN_CLIPS}?>&hl=cs_CZ&fs=1&rel=0" />
      <param name="allowFullScreen" value="true" />
      <param name="allowscriptaccess" value="always" />
      <param name="menu" value="false" />
      <p>Prosím nainstalijte si Adobe Flash Player</p>
   </object>
   <!-- <![endif]-->

</div>
<p class="panel-box-link-more">
   <a href="<?=$this->link()->route('detail', array('urlkey' => $this->band->{Bands_Model::COLUMN_URLKEY}))?>"
      title="<?=htmlspecialchars($this->band->{Bands_Model::COLUMN_NAME})?>"><?=$this->_('Více')?></a>
</p>