<div class="form-edit contact-form-edit">
   <?
   // donastavení formuláře
   $this->formEdit->text->html()->setAttrib('cols', 80)->setAttrib('rows', 30)->addClass("mceEditor");
   $this->formEdit->textPanel->html()->setAttrib('cols', 80)->setAttrib('rows', 10)->addClass("mceEditorSimple");

   $tinymce = new JsPlugin_TinyMce();
   $tinymce->setCfgParam(JsPlugin_TinyMce::PARAM_THEME, JsPlugin_TinyMce::TINY_THEME_ADVANCED);
   $tinymce->setCfgParam('editor_selector', 'mceEditor');
   $this->addJsPlugin($tinymce);

   $tinySimple = new JsPlugin_TinyMce();
   $tinySimple->setCfgParam('editor_selector', 'mceEditorSimple');
   $tinySimple->setCfgParam(JsPlugin_TinyMce::PARAM_THEME, JsPlugin_TinyMce::TINY_THEME_ADVANCED_SIMPLE);
   $this->addJsPlugin($tinySimple);

   echo $this->formEdit;
   ?>
</div>
<? $this->includeTpl("buttonback.phtml", true, array('link' => $this->link()->clear())); ?>
