<h1><?echo $this->category()->getName();?></h1>
<div class="main-content-detail">
<? if ($this->text != null) { ?>
   <div class="main-content-text"><? echo $this->text; ?></div>
<?}
if ($this->category()->getParam(Contact_Controller::PARAM_MAP, true) == true) {
   switch ($this->category()->getParam(Contact_Controller::PARAM_MAP_TYPE, Contact_Controller::PARAM_MAP_TYPE_IMAGE)) {
      case Contact_Controller::PARAM_MAP_TYPE_IFRAME:
         $this->includeTpl("map_iframe.phtml");
         break;
      case Contact_Controller::PARAM_MAP_TYPE_IMAGE:
      default:
         $this->includeTpl("map.phtml");
         break;
   }
   echo "<br />";
}
if ($this->category()->getParam(Contact_Controller::PARAM_FORM, true) == true) {
   $this->includeTpl("form.phtml");
   echo "<br />";
}
echo $this->toolbox;
?>
</div>
