<?if($this->urlParams != null){?>
<h2 id="contact-map-headline"><?=$this->_('Mapa jak se knám dostanete')?></h2>
<div class="contact-map">
<iframe width="500" height="400" frameborder="0" scrolling="no"
        marginheight="0" marginwidth="0"
        src="http://maps.google.com/maps?q=<?echo $this->urlParams?>"></iframe><br />
<small><a href="http://maps.google.com/maps?q=<?echo $this->urlParams?>"
          style="color:#0000FF;text-align:left">Zvětšit mapu</a></small>
</div>
<?}?>