<?
$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
$this->text = vve_remove_empty_tags($this->text);
if($this->text != null){
?>
<div class="panel-box-label"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->panelObj()->getName())?>"><?=$this->panelObj()->getName()?></a></div>
<div class="panel-box-content" style="<?=$backImg?>">
   <div class="panel-box-text"><address><?echo vve_remove_empty_tags($this->text);?></address></div>
</div>
<div class="panel-box-link-more"><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->tr('Více')?></a></div>
<?}?>