<?
$this->addPageTitle($this->_('Skupiny'));
//$this->addCssFile('style.css');
$jsJqGrid = new Component_JqGrid_JsPlugin();
$this->addJsPlugin($jsJqGrid);
$jQuery = new JsPlugin_JQuery();
$this->addJsPlugin($jQuery);
?>
<h1><?=$this->_('Skupiny');?></h1>
<?$this->includeTpl('navigation.phtml');?>

<div class="main-content-detail">
   <table id="table-groups"></table>
   <div id="table-groups-pager"></div>
   <hr class="reseter" />
   <br />
</div>
<?
?>
<script type="text/javascript" charset="utf-8">
      /* <![CDATA[ */
      var selectedGroupId = 0;
      $(document).ready(function() {
         var addressGrid = $("#table-groups").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url: '<?=$this->link()->route('groupsList');?>',
            datatype: "json",
            colNames:['ID', '<?=$this->_('Název')?>', '<?=$this->_('Popis')?>'],
            colModel:[
               {name:'<?=Model_Groups::COLUMN_ID?>',index:'<?=Model_Groups::COLUMN_ID?>',
                  width:33,editable:false},
               {name:'<?=Model_Groups::COLUMN_NAME?>',index:'<?=Model_Groups::COLUMN_NAME?>', width:100,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:2, label: "<?=$this->_('Název')?>",elmprefix:"(*)"}},
               {name:'<?=Model_Groups::COLUMN_LABEL?>',index:'<?=Model_Groups::COLUMN_LABEL?>', width:300,editable: true,edittype:"textarea", editoptions:{rows:"2",cols:"20"},
                  formoptions:{ rowpos:7, label: "<?=$this->_('Popis')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
            ],
            rowNum:20,
            rowList:[10,20,40,100],
            pager: '#table-groups-pager',
            sortname: '<?=Model_Groups::COLUMN_ID?>',
            caption:"Skupiny v systému",
            height: 350,
            width : 650,
            editurl:"<?=$this->link()->route('editGroup')?>"
         });
         addressGrid.jqGrid('navGrid','#table-groups-toolbar',{edit:false,add:false,del:false});
         // úpravy
         jQuery("#table-groups").jqGrid('navGrid','#table-groups-pager',
            {view:false}, //options
            {height:250,reloadAfterSubmit:true, jqModal:true, closeOnEscape:true,viewPagerButtons:false, // edit options
               bottominfo:"<?=$this->_('Položky označené (*) jsou povinné')?>",closeAfterEdit:true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
//                     return [false, 'users.phtml ok']
               }
            },
            {height:200,reloadAfterSubmit:true,jqModal:true, closeOnEscape:true, // add options
               bottominfo:"<?=$this->_('Položky označené (*) jsou povinné')?>", closeAfterAdd: true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },  // del options
            {reloadAfterSubmit:true,jqModal:true, closeOnEscape:true,
               afterSubmit : function(respond, postdata){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            {closeAfterSearch: true,closeOnEscape:true,sopt : ['eq','ne','cn','nc']}, // search options
            {height:120,jqModal:true,closeOnEscape:true} // view options
         );
      });
      /* ]]> */
      </script>