<?
$this->addPageTitle($this->tr('Skupiny'));
//$this->addCssFile('style.css');
$jsJqGrid = new Component_JqGrid_JsPlugin();
$this->addJsPlugin($jsJqGrid);
$jQuery = new JsPlugin_JQuery();
$this->addJsPlugin($jQuery);
?>
<h1><?=$this->tr('Skupiny');?></h1>
<?$this->includeTpl('navigation.phtml');?>

<div class="main-content-detail">
   <table id="table-groups"></table>
   <div id="table-groups-pager"></div>
   <hr class="reseter" />
   <br />
</div>
<?
?>
<script type="text/javascript" charset="utf-8">
      /* <![CDATA[ */
      var selectedGroupId = 0;
      $(document).ready(function() {
         var groupsGrid = $("#table-groups").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url: '<?=$this->link()->route('groupsList');?>',
            datatype: "json",
            colNames:['ID', '<?=$this->tr('Název')?>', '<?=$this->tr('Popis')?>', '<?=$this->tr('Admin')?>', '<?=$this->tr('Omezení na domény')?>'],
            colModel:[
               {name:'<?=Model_Groups::COLUMN_ID?>',index:'<?=Model_Groups::COLUMN_ID?>',
                  width:33,editable:false},
               {name:'<?=Model_Groups::COLUMN_NAME?>',index:'<?=Model_Groups::COLUMN_NAME?>', width:130,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:2, label: "<?=$this->tr('Název')?>",elmprefix:"(*)"}},
               {name:'<?=Model_Groups::COLUMN_LABEL?>',index:'<?=Model_Groups::COLUMN_LABEL?>', width:250,editable: true,edittype:"textarea", editoptions:{rows:"2",cols:"18"},
                  formoptions:{ rowpos:3, label: "<?=$this->tr('Popis')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               {name:'<?=Model_Groups::COLUMN_IS_ADMIN?>',index:'<?=Model_Groups::COLUMN_IS_ADMIN?>', formatter: 'checkbox',
//                   formatoptions:{disabled: false, 'class' : 'blockUser'},
                  width:60,editable:true,edittype:'checkbox', editoptions:{size:20, value:"true:false"
//                   ,dataEvents: [ {  type: 'change',fn: function(e) {if($(this).is(':checked')){$('#subsites').removeAttr('disabled');} else {$('#subsites').attr('disabled', true);}} } ]
                  },
                  formoptions:{ rowpos:4, label: "<?=$this->tr('Admin')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               {name:'sites',index:'sites', width:170, editable: true, edittype:"select", editoptions: {
                     value: <?=json_encode($this->sites)?>,
                     multiple: true, size: 3
                  },
                  formoptions:{ rowpos:5, label: "<?=$this->_('Uživatel<br />pouze pro<br />domény')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
            ],
            rowNum:20,
            rowList:[10,20,40,100],
            pager: '#table-groups-pager',
            sortname: '<?=Model_Groups::COLUMN_ID?>',
            caption:"Skupiny v systému",
            height: 350,
            width : 650,
            editurl:"<?=$this->link()->route('editGroup')?>"
         });
         groupsGrid.jqGrid('navGrid','#table-groups-toolbar',{edit:false,add:false,del:false});
         // úpravy
         jQuery("#table-groups").jqGrid('navGrid','#table-groups-pager',
            {view:false}, //options
            {height:350,reloadAfterSubmit:true, jqModal:true, closeOnEscape:true,viewPagerButtons:false, // edit options
               bottominfo:"<?=$this->tr('Položky označené (*) jsou povinné')?>",closeAfterEdit:true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               },
               afterShowForm : function(formid){
                  var data = groupsGrid.getCell(groupsGrid.jqGrid('getGridParam','selrow'), 'sites');
                  if(data != false || data != null){
                     data = data.split(';');
                     data.pop();
                     $('#sites option').each(function(){
                        if($.inArray($(this).text(),data) != -1){
                           $(this).attr('selected', 'selected');
                        } else {
                           $(this).removeAttr('selected');
                        }
                     });
                  }
               },
            },
            {height:300,reloadAfterSubmit:true,jqModal:true, closeOnEscape:true, // add options
               bottominfo:"<?=$this->tr('Položky označené (*) jsou povinné')?>", closeAfterAdd: true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },  // del options
            {reloadAfterSubmit:true,jqModal:true, closeOnEscape:true,
               afterSubmit : function(respond, postdata){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            {closeAfterSearch: true,closeOnEscape:true,sopt : ['eq','ne','cn','nc']}, // search options
            {height:120,jqModal:true,closeOnEscape:true} // view options
         );
      });
      /* ]]> */
      </script>