<?
$model = new Model_Users();
$users = $model->getUsersList();
// ajax
$linkAjax = new Url_Link_ModuleRequest();

$this->addJsPlugin(new JsPlugin_JQuery());
?>
<div>
   <h2><?=$this->_('Uživatelé')?></h2>
   <table style="width: 90%">
      <tr>
         <th width="20"><?=$this->_('id')?></th>
         <th width="80"><?=$this->_('jméno')?></th>
         <th width="80"><?=$this->_('přijmení')?></th>
         <th width="80"><?=$this->_('uživ. jméno')?></th>
         <th><?=$this->_('e-mail')?></th>
         <th width="60"><?=$this->_('skupina')?></th>
         <th width="60"><?=$this->_('status')?></th>
         <th width="60"><?=$this->_('pperace')?></th>
      </tr>
      <? while ($row = $users->fetchObject()) {?>
      <tr>
         <td><?=$row->{Model_Users::COLUMN_ID}?></td>
         <td><?=$row->{Model_Users::COLUMN_NAME}?></td>
         <td><?=$row->{Model_Users::COLUMN_SURNAME}?></td>
         <td><?=$row->{Model_Users::COLUMN_USERNAME}?></td>
         <td><?=$row->{Model_Users::COLUMN_MAIL}?></td>
         <td><?=$row->{Model_Users::COLUMN_GROUP_NAME}?></td>
         <td><?
         if($row->{Model_Users::COLUMN_BLOCKED} == true){?>
            <form method="post" action="<?=$this->link()?>" style="display:inline;">
               <input type="hidden" value="<?=$row->{Model_Users::COLUMN_ID}?>" name="userstatus_id" />
               <input type="hidden" value="enable" name="userstatus_status" />
               <input type="image" src="<?=vve_get_tpl_file('icons/disable.png', VVE_TPL_FILE_IMAGE)?>"
                      value="edit" name="userstatus_change" title="<?=$this->_('Aktivovat uživatele')?>" />
            </form>
         <?} else {?>
            <form method="post" action="<?=$this->link()?>" style="display:inline;">
               <input type="hidden" value="<?=$row->{Model_Users::COLUMN_ID}?>" name="userstatus_id" />
               <input type="hidden" value="disable" name="userstatus_status" />
               <input type="image" src="<?=vve_get_tpl_file('icons/enable.png', VVE_TPL_FILE_IMAGE)?>"
                      value="edit" name="userstatus_change" title="<?=$this->_('Deaktivovat uživatele')?>" />
            </form>
         <?}?>
         </td>
         <td>
            <?if($this->category()->getRights()->isControll()){?>
            <form method="post" action="<?=$this->link()->route('edituser',array('id' => $row->{Model_Users::COLUMN_ID}))?>" style="display:inline;">
               <input type="image" src="<?=vve_get_tpl_file('icons/user_edit.png', VVE_TPL_FILE_IMAGE)?>"
                      value="edit" name="user_edit" title="<?=$this->_('Upravit')?>" />
            </form>
            <form method="post" action="<?=$this->link()?>" style="display:inline;" onsubmit="return confirm('<?=$this->_('Opravdu smazat uživatele: ').$row->{Model_Users::COLUMN_USERNAME};?>')">
               <input type="hidden" value="<?=$row->{Model_Users::COLUMN_ID}?>" name="user_id" />
               <input type="image" src="<?=vve_get_tpl_file('icons/user_delete.png', VVE_TPL_FILE_IMAGE)?>"
                      value="remove" name="user_remove" title="<?=$this->_('Smazat')?>" />
            </form>
            <?}?>
         </td>
      </tr>

      <?}?>

   </table>
<script type="text/javascript">
   /* <![CDATA[ */
   function disableUser(id){
      $.post("<?=$linkAjax->action('disable', 'php')?>", { id: id } );
   }
   /* ]]> */
</script>
   <br />
   <br />
   <?
   $grList = $model->getGroups();
   ?>
   <h2><?=$this->_('Skupiny')?></h2>
   <table style="width: 90%;">
      <tr>
         <th width="20"><?=$this->_('id')?></th>
         <th width="80"><?=$this->_('jméno')?></th>
         <th><?=$this->_('popis')?></th>
         <th width="60"><?=$this->_('výchozí práva')?></th>
         <th width="60"><?=$this->_('operace')?></th>
      </tr>
      <? while ($row = $grList->fetchObject()) {?>
      <tr>
         <td><?=$row->{Model_Users::COLUMN_ID_GROUP}?></td>
         <td><?=$row->{Model_Users::COLUMN_GROUP_NAME}?></td>
         <td><?=$row->{Model_Users::COLUMN_GROUP_LABEL}?></td>
         <td><?=$row->{Model_Users::COLUMN_GROUP_DEF_RIGHT}?></td>
         <td>
            <?if($this->category()->getRights()->isControll()){?>
            <form method="post" action="<?=$this->link()->route('editgroup',array('id' => $row->{Model_Users::COLUMN_ID_GROUP}))?>" style="display:inline;">
               <input type="image" src="<?=vve_get_tpl_file('icons/group_edit.png', VVE_TPL_FILE_IMAGE)?>"
                      value="edit" name="group_edit" title="<?=$this->_('Upravit')?>" />
            </form>
            <form method="post" action="<?=$this->link()?>" style="display:inline;" onsubmit="return confirm('<?=$this->_('Opravdu smazat skupinu: ').$row->{Model_Users::COLUMN_GROUP_LABEL};?>')">
               <input type="hidden" value="<?=$row->{Model_Users::COLUMN_ID_GROUP}?>" name="group_id" />
               <input type="image" src="<?=vve_get_tpl_file('icons/group_delete.png', VVE_TPL_FILE_IMAGE)?>"
                      value="remove" name="group_remove" title="<?=$this->_('Smazat')?>" />
            </form>
            <?}?>
         </td>
      </tr>
      <?}?>
   </table>
   <?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('add_user', $this->_("Přidat uživatele"),
          $this->link()->route('adduser'),
          $this->_("Přidat nového uživatele"), "user_add.png");
      $toolbox->addTool('add_group', $this->_("Přidat skupinu"),
          $this->link()->route('addgroup'),
          $this->_("Přidat novou skupinu"), "group_add.png");
      $this->includeTplObj($toolbox);
   }
   ?>
</div>