<?
$this->addPageTitle($this->_('Uživatelé'));
//$this->addCssFile('style.css');
$jsJqGrid = new Component_JqGrid_JsPlugin();
$this->addJsPlugin($jsJqGrid);
$jQuery = new JsPlugin_JQuery();
$this->addJsPlugin($jQuery);

$grpsArr = array();
?>
<h1><?=$this->_('Uživatelé');?></h1>
<?$this->includeTpl('navigation.phtml');?>

<div class="main-content-detail">
   <table id="table-users"></table>
   <div id="table-users-toolbar">
      <label for="select-group-id"><?=$this->_('Skupina')?>:</label>
      <select id="select-group-id" name="sel_group">
         <?foreach ($this->groups as $grp) {
            $grpsArr[(int)$grp[Model_Groups::COLUMN_ID]] = $grp[Model_Groups::COLUMN_NAME];
            ?><option value="<?=$grp[Model_Groups::COLUMN_ID]?>" title="<?=$grp[Model_Groups::COLUMN_NAME]?>"><?=$grp[Model_Groups::COLUMN_NAME].' - '.$grp[Model_Groups::COLUMN_LABEL]?></option><?
         }
         ?>
      </select>
   </div>
   <div id="table-users-pager"></div>
   <hr class="reseter" />
   <br />
</div>
<?
?>
<script type="text/javascript" charset="utf-8">
      /* <![CDATA[ */
      var selectedGroupId = 0;
      $(document).ready(function() {
         var addressGrid = $("#table-users").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url: '<?=$this->link()->route('usersList');?>?idgrp='+$('#select-group-id').val().toString(),
            datatype: "json",
            colNames:['ID', '<?=$this->_('Jméno')?>', '<?=$this->_('Přijmení')?>', '<?=$this->_('Už.jméno')?>',
               '<?=$this->_('heslo')?>', '<?=$this->_('E-mail')?>', '<?=$this->_('Blokace')?>', '<?=$this->_('Poznámka')?>', '<?=$this->_('Skupina')?>'],
            colModel:[
               {name:'<?=Model_Users::COLUMN_ID?>',index:'<?=Model_Users::COLUMN_ID?>',
                  width:33,editable:false},
               {name:'<?=Model_Users::COLUMN_NAME?>',index:'<?=Model_Users::COLUMN_NAME?>', width:100,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:2, label: "<?=$this->_('Jméno')?>",elmprefix:"(*)"}},
               {name:'<?=Model_Users::COLUMN_SURNAME?>',index:'<?=Model_Users::COLUMN_SURNAME?>', width:100,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:3, label: "<?=$this->_('Přijmení')?>",elmprefix:"(*)"}},
               {name:'<?=Model_Users::COLUMN_USERNAME?>',index:'<?=Model_Users::COLUMN_USERNAME?>', width:100,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:4, label: "<?=$this->_('Uživ. jméno')?>",elmprefix:"(*)"}},
               {name:'<?=Model_Users::COLUMN_PASSWORD?>',index:'<?=Model_Users::COLUMN_PASSWORD?>',width:1,editable:true,edittype:'password',editoptions:{size:20},
                  formoptions:{ rowpos:5, label: "<?=$this->_('Heslo')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               {name:'<?=Model_Users::COLUMN_MAIL?>',index:'<?=Model_Users::COLUMN_MAIL?>', width:260,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:6, label: "<?=$this->_('E-mail')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               {name:'<?=Model_Users::COLUMN_BLOCKED?>',index:'<?=Model_Users::COLUMN_BLOCKED?>', formatter: 'checkbox', 
                  formatoptions:{disabled: false, 'class' : 'blockUser'}, width:70,editable:true,edittype:'checkbox', editoptions:{size:20, value:"true:false"},
                  formoptions:{ rowpos:7, label: "<?=$this->_('Blokace')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               {name:'<?=Model_Users::COLUMN_NOTE?>',index:'<?=Model_Users::COLUMN_NOTE?>', width:300,editable: true,edittype:"textarea", editoptions:{rows:"2",cols:"20"},
                  formoptions:{ rowpos:8, label: "<?=$this->_('Poznámka')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               {name:'<?=Model_Users::COLUMN_GROUP_ID?>',index:'<?=Model_Users::COLUMN_GROUP_ID?>', width:50,editable: true,edittype:"select",
                  editoptions:{value: <?=json_encode($grpsArr)?>},formoptions:{ rowpos:9, label: "<?=$this->_('Skupina')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}}
            ],
            rowNum:20,
            rowList:[10,20,40,100],
            pager: '#table-users-pager',
            sortname: '<?=Model_Users::COLUMN_ID?>',
            caption:"Uživatelé v systému",
            height: 450,
            width : 650,
            editurl:"<?=$this->link()->route('editUser')?>",
            toolbar: [true,"top"]
         });
         addressGrid.jqGrid('navGrid','#table-users-toolbar',{edit:false,add:false,del:false});
         $("#t_table-users").append($('#table-users-toolbar'));
         /* změna skupiny */
         $("#select-group-id").change(function(){
            baseId = this.value;
            addressGrid.jqGrid('setGridParam', { url: '<?=$this->link()->route('usersList');?>?idgrp='+this.value});
            addressGrid.trigger("reloadGrid");
         });
         /* změna statusu usera */
         $('#table-users input[type=checkbox]').live('change',function(){
            var newStatus = false;
            var idUser = $(this).parent('td').parent('tr').attr('id');
            if($(this).is(':checked')){newStatus = true;}
            $.ajax({
               url: "<?=$this->link()->route('blockUser')?>", type: "POST",
               data: ({id : idUser, blocked : newStatus})
            });
         });

         // úpravy
         jQuery("#table-users").jqGrid('navGrid','#table-users-pager',
            {view:false}, //options
            {height:280,reloadAfterSubmit:true, jqModal:true, closeOnEscape:true,viewPagerButtons:false, // edit options
               bottominfo:"<?=$this->_('Položky označené (*) jsou povinné')?>",closeAfterEdit:true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            {height:260,reloadAfterSubmit:true,jqModal:true, closeOnEscape:true, // add options
               bottominfo:"<?=$this->_('Položky označené (*) jsou povinné')?>", closeAfterAdd: true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               },
               afterShowForm : function(){
                  $('#gname').val($('#select-group-id').val());
               }
            },  // del options
            {reloadAfterSubmit:true,jqModal:true, closeOnEscape:true,
               afterSubmit : function(respond, postdata){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            {closeAfterSearch: true,closeOnEscape:true,sopt : ['eq','ne','cn','nc']}, // search options
            {height:120,jqModal:true,closeOnEscape:true} // view options
         );
      });
      /* ]]> */
      </script>