<?php 
$this->addPageTitle($this->tr('Uživatelé'));
//$this->addCssFile('style.css');
$jsJqGrid = new Component_JqGrid_JsPlugin();
$this->addJsPlugin($jsJqGrid);
$jQuery = new JsPlugin_JQuery();
$this->addJsPlugin($jQuery);

$grpsArr = array();
?>
<h1><?php echo $this->tr('Uživatelé');?></h1>
<?php $this->includeTpl('navigation.phtml');?>

<div class="main-content-detail">
   <table id="table-users"></table>
   <div id="table-users-toolbar">
      <label for="select-group-id"><?php echo $this->tr('Skupina')?>:</label>
      <select id="select-group-id" name="sel_group">
         <?php foreach ($this->groups as $grp) {
            $grpsArr[(int)$grp[Model_Groups::COLUMN_ID]] = $grp[Model_Groups::COLUMN_NAME];
            ?><option value="<?php echo $grp->{Model_Groups::COLUMN_ID}?>" title="<?php echo $grp->{Model_Groups::COLUMN_NAME}?>"><?php echo $grp->{Model_Groups::COLUMN_NAME}.' - '.$grp->{Model_Groups::COLUMN_LABEL}?></option><?php 
         }
         ?>
      </select>
   </div>
   <div id="table-users-pager"></div>
   <hr class="reseter" />
   <br />
</div>
<?php 
?>
<script type="text/javascript" charset="utf-8">
      /* <![CDATA[ */
      var selectedGroupId = 0;
      $(document).ready(function() {
         var usersGrid = $("#table-users").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url: '<?php echo $this->link()->route('usersList');?>?idgrp='+$('#select-group-id').val().toString(),
            datatype: "json",
            colNames:['ID', '<?php echo $this->tr('Už.jméno')?>', '<?php echo $this->tr('Jméno')?>', '<?php echo $this->tr('Přijmení')?>',
               '<?php echo $this->tr('Heslo')?>', '<?php echo $this->tr('E-mail')?>', '<?php echo $this->tr('Tel.')?>', '<?php echo $this->tr('Adresa')?>', 
               '<?php echo $this->tr('Blokace')?>', '<?php echo $this->tr('Poznámka')?>', '<?php echo $this->tr('Skupina')?>'],
            colModel:[
               {name:'<?php echo Model_Users::COLUMN_ID?>',index:'<?php echo Model_Users::COLUMN_ID?>',
                  width:33,fixed: true,editable:false},
               {name:'<?php echo Model_Users::COLUMN_USERNAME?>',index:'<?php echo Model_Users::COLUMN_USERNAME?>', 
                  width:150,fixed: true,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:2, label: "<?php echo $this->tr('Uživ. jméno')?>",elmprefix:"<span class=\"required\"></span>"}},
               {name:'<?php echo Model_Users::COLUMN_NAME?>',index:'<?php echo Model_Users::COLUMN_NAME?>', 
                  width:80,fixed: true,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:3, label: "<?php echo $this->tr('Jméno')?>",elmprefix:"<span class=\"required\"></span>"}},
               {name:'<?php echo Model_Users::COLUMN_SURNAME?>',index:'<?php echo Model_Users::COLUMN_SURNAME?>', 
                  width:80,fixed: true,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:4, label: "<?php echo $this->tr('Přijmení')?>",elmprefix:"<span class=\"required\"></span>"}},
               {name:'<?php echo Model_Users::COLUMN_PASSWORD?>',index:'<?php echo Model_Users::COLUMN_PASSWORD?>',
                  width:1,fixed:true,hidedlg:false, hidden:true, editable:true,edittype:'password',editoptions:{size:20},
                  formoptions:{ rowpos:5, label: "<?php echo $this->tr('Heslo')?>",elmprefix:""}},
               {name:'<?php echo Model_Users::COLUMN_MAIL?>',index:'<?php echo Model_Users::COLUMN_MAIL?>', 
                  width:150,fixed: true,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:6, label: "<?php echo $this->tr('E-mail')?>",elmprefix:""}},
               
               {name:'<?php echo Model_Users::COLUMN_PHONE?>',index:'<?php echo Model_Users::COLUMN_PHONE?>', 
                  width:100, fixed : true, editable: true,editoptions:{size:20},
                  formoptions:{ rowpos:7, label: "<?php echo $this->tr('Tel.')?>",elmprefix:""}},
                  
               {name:'<?php echo Model_Users::COLUMN_ADDRESS?>',index:'<?php echo Model_Users::COLUMN_ADDRESS?>', 
                  width:1,fixed:true,hidedlg:false, hidden:true, editable:true, edittype:"textarea", editoptions:{rows:"2",cols:"20"},
                  formoptions:{ rowpos:8, label: "<?php echo $this->tr('Adresa')?>",elmprefix:""}},
               
               {name:'<?php echo Model_Users::COLUMN_BLOCKED?>',index:'<?php echo Model_Users::COLUMN_BLOCKED?>', formatter: 'checkbox', 
                  formatoptions:{disabled: false, 'class' : 'blockUser'}, 
                  width:50,fixed: true,editable:true,edittype:'checkbox', editoptions:{size:20, value:"true:false"},
                  formoptions:{ rowpos:9, label: "<?php echo $this->tr('Blokace')?>",elmprefix:""}},
               {name:'<?php echo Model_Users::COLUMN_NOTE?>',index:'<?php echo Model_Users::COLUMN_NOTE?>', 
                  editable: true,edittype:"textarea", editoptions:{rows:"2",cols:"20"},
                  formoptions:{ rowpos:10, label: "<?php echo $this->tr('Poznámka')?>",elmprefix:""}},
               {name:'<?php echo Model_Users::COLUMN_GROUP_ID?>',index:'<?php echo Model_Users::COLUMN_GROUP_ID?>', 
                  width:90,fixed: true, editable: true,edittype:"select",
                  editoptions:{value: <?php echo json_encode($grpsArr)?>},formoptions:{ rowpos:11, 
                     label: "<?php echo $this->tr('Skupina')?>",elmprefix:""}}
            ],
            rowNum:20,
            rowList:[10,20,40,100],
            pager: '#table-users-pager',
            sortname: '<?php echo Model_Users::COLUMN_ID?>',
            caption:"<?php echo $this->tr('Uživatelé v systému')?>",
            autowidth : true,
            height: '100%',
            editurl:"<?php echo $this->link()->route('editUser')?>",
            toolbar: [true,"top"]
         });
         $("#t_table-users").append($('#table-users-toolbar'));
         /* změna skupiny */
         $("#select-group-id").change(function(){
            baseId = this.value;
            usersGrid.jqGrid('setGridParam', { url: '<?php echo $this->link()->route('usersList');?>?idgrp='+this.value});
            usersGrid.trigger("reloadGrid");
         });
         /* změna statusu usera */
         $('#table-users input[type=checkbox]').live('change',function(){
            var newStatus = false;
            var idUser = $(this).parent('td').parent('tr').attr('id');
            if($(this).is(':checked')){newStatus = true;}
            $.ajax({
               url: "<?php echo $this->link()->route('blockUser')?>", type: "POST",
               data: ({id : idUser, blocked : newStatus})
            });
         });

         usersGrid.jqGrid('navGrid','#table-users-pager',
            {edit:true,add:true,del:true},
            // edit options
            {reloadAfterSubmit:true, jqModal:true, closeOnEscape:true,viewPagerButtons:false,
               width:400,
               bottominfo:"<?php echo $this->tr('Položky označené (*) jsou povinné')?>",closeAfterEdit:true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               },
               beforeShowForm: function(form) { $("tr#tr_password",form[0]).show();$("tr#tr_user_address",form[0]).show(); }
            },
            // add options
            {reloadAfterSubmit:true,jqModal:true, closeOnEscape:true, 
               width:400,
               bottominfo:"<?php echo $this->tr('Položky označené (*) jsou povinné')?>", closeAfterAdd: true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               },
               afterShowForm : function(){
                  $('#id_group').val($('#select-group-id').val());
               },
               beforeShowForm: function(form) { $("tr#tr_password",form[0]).show();$("tr#tr_user_address",form[0]).show(); }
            },  
            // del options
            {reloadAfterSubmit:true,jqModal:true, closeOnEscape:true,
               afterSubmit : function(respond, postdata){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            {multipleSearch:false, closeAfterSearch: true,closeOnEscape:true,sopt : ['eq','ne','cn','nc']},
            {closeOnEscape:true}
         );
      });
      /* ]]> */
      </script>