<h1><?php echo $this->tr('Nástroje pro príci s e-maily')?></h1>
<?php echo $this->includeTpl('navigation.phtml');?>
<div class="form-edit">
   <div id="mails-tools" style="">
	<ul>
		<li><a href="<?php echo $this->link()?>#mails-export">Export</a></li>
		<li><a href="<?php echo $this->link()?>#mails-import">Import</a></li>
		<li><a href="<?php echo $this->link()?>#mails-utilities">Nástroje</a></li>
	</ul>
	<div id="mails-export">
      <?php 
      echo $this->formExport;
      echo $this->tr('Podporován je momentálně export do souboru typu xls, csv a txt. V txt exportu jsou pouze e-mailové adresy.');
      ?>
	</div>
	<div id="mails-import">
      <?php 
//      $this->formImport->separator->html()->setAttrib('size', 1);
      echo $this->formImport;
      ?>
      <p class="note"><?php echo $this->tr('Podporován je momentálně soubor pouze s e-mailovými adresami.')?></p>
      <br />
      <?php 
//      $this->formImport->separator->html()->setAttrib('size', 1);
      echo $this->formImportUsers;
      ?>
	</div>
	<div id="mails-utilities">
      <?php 
//      $this->formImport->separator->html()->setAttrib('size', 1);
      echo '<h3>'.$this->tr('Odstranění duplicitních emailů z adresáře.').'</h3>';
      echo $this->formRemoveDuplicity;
      echo $this->tr('Odstraněny budou všechny duplicitní e-mailové adresy.');
      echo "<br />";
      echo '<h3>'.$this->tr('Oprava uložených emailů').'</h3>';
      echo $this->formRepair;
      echo $this->tr('Opraví se duplicitní položky a odstraní špatné zanyk v emailu.');
      ?>
      <hr class="reseter" />
	</div>
   <?php 
   $jQuery = new JsPlugin_JQuery();
   $jQuery->addPluginCookie();
   $jQuery->addUITabs();
   $this->addJsPlugin($jQuery);   
   ?>
   <script type="text/javascript">
      $(document).ready(function(){
         $('#mails-tools').tabs({
            cookie : { expires : 10, path: "/"}
         });
      });
   </script>
   </div>
</div>
