<?php 
// do titulku
if($this->edit) {
   $h = sprintf($this->tr('úprava osoby "%s"'),$this->person->{Teams_Model_Persons::COLUMN_NAME}.' '.$this->person->{Teams_Model_Persons::COLUMN_SURNAME});
} else {
   $h = $this->tr('přidání osoby');
}
$this->addPageTitle($h);
// donastavení formuláře
$this->form->text->html()->setAttrib('cols', 80)->setAttrib('rows', 30);
$this->form->degree->html()->setAttrib('size', 5);
?>
<h1><?php ps($h)?></h1>
<div class="main-content-form-edit">
   <?php 
   echo($this->form);
   ?>
</div>