<?php 
/* VARS:
 * $this->teams = array('name' => 'group name' , 'persons' => 'array of MODEL_ORM_RECORD with person obj')
 * 
 */

$this->addFile('css://style.css');
?>
<h1><?php ps($this->category()->getName())?></h1>
<div class="list" id="people-list">
   <div id="teams-list" class="item">
      <?php foreach ($this->teams as $team) {
         if(empty ($team['persons']) ){
            continue;
         }
         ?>
      <h2><?php ps($team['name']);?></h2>
      <ul class="team">
         <?php foreach ($team['persons'] as $person){
            $name = null;
            if($person->{Teams_Model_Persons::COLUMN_DEGREE} != null){
               $name .= $person->{Teams_Model_Persons::COLUMN_DEGREE}.' ';
            }
            $name .= $person->{Teams_Model_Persons::COLUMN_NAME}." ".$person->{Teams_Model_Persons::COLUMN_SURNAME}." ".$person->{Teams_Model_Persons::COLUMN_DEGREE_AFTER};
            
            ?>
         <li class="person">
            <img src="<?php echo $this->category()->getModule()->getDataDir(true).$person->{Teams_Model_Persons::COLUMN_IMAGE}?>" 
                 alt="<?php ps($person->{Teams_Model_Persons::COLUMN_NAME}." ".$person->{Teams_Model_Persons::COLUMN_SURNAME})?>" class="person-image"/>
            <h3 id="team-person-<?php echo $person->{Teams_Model_Persons::COLUMN_ID}?>"><?php 
               if($person->{Teams_Model_Persons::COLUMN_LINK} != null){
                  echo '<a href="'.$person->{Teams_Model_Persons::COLUMN_LINK}.'" title="'.$person->{Teams_Model_Persons::COLUMN_NAME}.'" class="link-external">';
               }
               ps($name);
               if($person->{Teams_Model_Persons::COLUMN_LINK} != null){
                  echo '</a>';
               }
               ?></h3>
            <div class="text">
               <?php if($person->{Teams_Model_Persons::COLUMN_WORK} != null){?>
                  <h4><?php ps($person->{Teams_Model_Persons::COLUMN_WORK})?></h4>
               <?php }?>
               <?php echo $person->{Teams_Model_Persons::COLUMN_TEXT}?>
            </div>
            
            <?php if($this->toolboxEdit != null){
               $this->toolboxEdit->person_edit->setAction($this->link()->route('edit', array('id' => $person->{Teams_Model_Persons::COLUMN_ID})));
               $this->toolboxEdit->person_edit_photo->setAction($this->link()->route('editPhoto', array('id' => $person->{Teams_Model_Persons::COLUMN_ID})));
               $this->toolboxEdit->person_del_->getForm()->id->setValues($person->{Teams_Model_Persons::COLUMN_ID});
               echo $this->toolboxEdit;
            }?>
            <hr class="reseter" />
         </li>   
         <?php 
         } ?>
      </ul>
      <hr class="reseter" />
      <?php }?>
            
         <?php /*   // create name
            $name = null;
            if($person->{Teams_Model_Persons::COLUMN_DEGREE} != null){
               $name .= $person->{Teams_Model_Persons::COLUMN_DEGREE}.' ';
            }
            
            $name .= $person->{Teams_Model_Persons::COLUMN_NAME}." ".$person->{Teams_Model_Persons::COLUMN_SURNAME}." ".$person->{Teams_Model_Persons::COLUMN_DEGREE_AFTER};
            
            // start block
            if($curGroup != $person->{Teams_Model_Persons::COLUMN_GROUP_NAME}){
               $curGroup = $person->{Teams_Model_Persons::COLUMN_GROUP_NAME};
            ?>
            <div class="group">
               <h2 class="" title="<?php ps($person->{Teams_Model_Persons::COLUMN_GROUP_NAME})?>"
                   ><?php ps( $person->{Teams_Model_Persons::COLUMN_GROUP_NAME} != null ? $person->{Teams_Model_Persons::COLUMN_GROUP_NAME} : $this->tr('Nezařazeno'))?></h2>
               <div class="persons-list">
            <?php }?>
                  <div class="person">
                     <img src="<?php echo $this->category()->getModule()->getDataDir(true).$person->{Teams_Model_Persons::COLUMN_IMAGE}?>" 
                          alt="<?php ps($person->{Teams_Model_Persons::COLUMN_NAME}." ".$person->{Teams_Model_Persons::COLUMN_SURNAME})?>"
                          class="person-image"/>
                     <h3 id="person-<?php echo $person->{Teams_Model_Persons::COLUMN_ID}?>"><?php ps($name." order: ".(string)$person->{Teams_Model_Persons::COLUMN_ORDER});?></h3>
                     <div class="text">
                        <?php echo $person->{Teams_Model_Persons::COLUMN_TEXT}?>
                     </div>
                     <hr class="reseter" />
                     <?php 
                     if($this->toolboxEdit != null){
//                        $this->toolboxEdit->person_edit->setAction($this->link()->route('edit', array('id' => $person->{Teams_Model_Persons::COLUMN_ID})));
//                        $this->toolboxEdit->person_del_->getForm()->id->setValues($person->{Teams_Model_Persons::COLUMN_ID});
//                        echo $this->toolboxEdit;
                     }
                     ?>
                  </div>
            <?php  // end of block
            if(!isset ($this->people[$index+1]) || $this->people[$index+1]->{Teams_Model_Persons::COLUMN_GROUP_NAME} != $curGroup){?>
               </div>
               <hr class="reseter" />
            </div>
            <?php }?>
         <?php }*/?>
   </div>
</div>
<?php 
   echo $this->toolbox;// TOOLBOXY
?>
