<?php 
$modelImages = new PhotoGalery_Model_Images();
?>
<div class="galeriesList">
   <?php if(!empty ($this->articles)) {
      foreach ($this->articles as $article) {
         $noPClass = $noPubllic = null;
         if($article->{Articles_Model::COLUMN_CONCEPT} == 1){
            $noPClass = 'noPublicGalery';
            $noPubllic = '<span class="smallFont">'.$this->_('Nezveřejněno').'</span>';
         }
         $addDate = new DateTime($article->{Articles_Model::COLUMN_ADD_TIME});
         ?>
   <div class="<?php echo $noPClass?>">
      <h2><a href="<?php echo $this->link()->route('detail', array('urlkey' => $article->{Articles_Model::COLUMN_URLKEY}))?>"
             title="<?php echo htmlspecialchars($article->{Articles_Model::COLUMN_NAME})?>"><?php echo htmlspecialchars($article->{Articles_Model::COLUMN_NAME})?>&nbsp;
            <span class="smallFont"><?php echo strftime("%x %X", $addDate->format("U"))?> - <?php echo $article->{Model_Users::COLUMN_USERNAME}?></span>
         </a><?php echo $noPubllic?>
      </h2>
      <?php 
      $images = $modelImages->getImages($this->category()->getId(), 
              $article->{Articles_Model::COLUMN_ID},
              $this->category()->getParam('imagesinlist', Photogalerymed_Controller::DEFAULT_IMAGES_IN_LIST));
      while ($row = $images->fetch()) {?>
      <img alt="<?php echo $row->{PhotoGalery_Model_Images::COLUMN_NAME}?>" 
           src="<?php echo $this->category()->getModule()->getDataDir(true).
              $article[Articles_Model::COLUMN_URLKEY][Locales::getDefaultLang()]
              .URL_SEPARATOR.Photogalery_Controller::DIR_SMALL
              .URL_SEPARATOR.$row->{PhotoGalery_Model_Images::COLUMN_FILE}?>" />
      <?php }?>

            <?php echo $article->{Articles_Model::COLUMN_TEXT}?>
      <hr class="reseter" />
      <br />
   </div>
     <?php }
   } else {
      print ($this->_('Není vložena žádná galerie'));
   }?>
</div>
