<?php 
$this->addPageTitle($this->article->{Articles_Model::COLUMN_NAME});
$h1 = $this->article->{Articles_Model::COLUMN_NAME};
echo $this->toolbox;
?>
<h1><?php echo $h1?></h1>
<div class="main-content-detail">
   <div class="main-content-text"><?php 
   if((string)$this->article->{Articles_Model::COLUMN_TEXT} != null) {
      echo $this->article->{Articles_Model::COLUMN_TEXT};
   } else if($this->category()->getRights()->isWritable()) {
      ?><div class="admin-info-text"><?php echo $this->tr('Źádný text galerie nebyl vyplněn.');?></div><?php 
   }
   ?></div>
   <?php 
   $this->includeTpl('privateText.phtml', false,null, 'articles');//private text
   
   // images gallery
   $this->imagesBaseDir = $this->category()->getModule()->getDataDir(true).$this->websubdir;
   $this->includeFile('tpl://engine:photogalery.phtml');
   // link back
   $this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->link()->route()));
   // share tools
   $this->includeTpl('articletools.phtml', true, array(
           'lastEditTime' => $this->article->{Articles_Model::COLUMN_EDIT_TIME},
           'lastEditUser' => $this->article->{Model_Users::COLUMN_USERNAME},
           'linkToPdf' => $this->link()->route('detailExport',array('output' => 'pdf')),
           'shares' => array('url' => $this->link(), 'title' => $this->article->{Articles_Model::COLUMN_NAME})));
   ?>
</div>
<?php echo $this->comments;?>
