<?
$this->addCssFile("style.css");

$this->addPageTitle($this->article->{Articles_Model_Detail::COLUMN_NAME});
$this->addPageHeadline($this->article->{Articles_Model_Detail::COLUMN_NAME});
// jquery galerka
$this->addJsPlugin(new JsPlugin_PiroBox());
$addDate = new DateTime($this->article->{Articles_Model_Detail::COLUMN_ADD_TIME});
$editDate = new DateTime($this->article->{Articles_Model_Detail::COLUMN_EDIT_TIME});
?>
<div>
   <p>
      <?=$this->_('Přidáno')." ".strftime("%x %X", $addDate->format("U"))
              ."&nbsp;".$this->_('uživatelem')."&nbsp;".$this->article->{Model_Users::COLUMN_USERNAME}?>.&nbsp;
      <?=$this->_('Zobrazeno')?>:&nbsp;<?=$this->article->{Articles_Model_Detail::COLUMN_SHOWED}?>&times;
   </p>
   <?if($this->article->{Articles_Model_Detail::COLUMN_TEXT} != null) {?>
   <div class="photogaleryMedText">
         <?=$this->article->{Articles_Model_Detail::COLUMN_TEXT}?>
   </div>
   <br />
      <?}?>

   <!-- Start Advanced Gallery Html Containers -->
   <div class="photogaleryMedImages">
      <?while ($image = $this->images->fetch()) {
         ?>
      <a class="pirobox_gall" href="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir
                    .Photogalery_Controller::DIR_MEDIUM.URL_SEPARATOR.$image[PhotoGalery_Model_Images::COLUMN_FILE]?>"
         title="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>">
         <img src="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                         .$image[PhotoGalery_Model_Images::COLUMN_FILE]?>" alt="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>" />
      </a>
         <?}?>
   </div>
   <!-- End Gallery Html Containers -->
   <hr class="reseter" />
   <?$this->includeTpl('articletools.phtml', true, array(
           'lastEditTime' => $this->article->{Articles_Model_Detail::COLUMN_EDIT_TIME},
           'lastEditUser' => $this->article->{Model_Users::COLUMN_USERNAME},
           'linkToPdf' => $this->link()->route('detailpdf'),
           'shares' => $this->shares));?>

   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         $().piroBox({
            my_speed: 300, //animation speed
            bg_alpha: 0.8, //background opacity
            radius: 4, //caption rounded corner
            scrollImage : false, // true == image follows the page _|_ false == image remains in the same open position
            // in some cases of very large images or long description could be useful.
            slideShow : 'slideshow', // true == slideshow on, false == slideshow off
            slideSpeed : 3, //slideshow
            pirobox_next : 'piro_next', // Nav buttons -> piro_next == inside piroBox , piro_next_out == outside piroBox
            pirobox_prev : 'piro_prev', // Nav buttons -> piro_prev == inside piroBox , piro_prev_out == outside piroBox
            close_all : '.piro_close' // add class .piro_overlay(with comma)if you want overlay click close piroBox
         });
      });

      /* ]]> */
   </script>
   <?
   echo $this->toolbox;
   ?>
</div>
<?$this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->l()->route('normal')));?>
