<?
$this->addCssFile("style.css");

$this->addPageTitle($this->article->{Articles_Model_Detail::COLUMN_NAME});
$h1 = $this->article->{Articles_Model_Detail::COLUMN_NAME};
// jquery galerka
$this->addJsPlugin(new JsPlugin_PiroBox());
?>
<h1><?=$h1?></h1>
<div class="main-content-detail">
   <div class="main-content-text"><?
   if($this->article->{Articles_Model_Detail::COLUMN_TEXT} != null) {
      echo $this->article->{Articles_Model_Detail::COLUMN_TEXT};
   }
   echo $this->toolboxMain;
   ?></div>
   <!-- Start Advanced Gallery Html Containers -->
   <div class="main-content-images"><?
      $images = $this->images->fetchAll();
      if(count($images) == 1) {$class = 'pirobox';}
      else {$class = 'pirobox_gall';}
      foreach ($images as $image) {
         ?><a class="<?=$class?>" href="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir
                    .Photogalery_Controller::DIR_MEDIUM.URL_SEPARATOR.$image[PhotoGalery_Model_Images::COLUMN_FILE]?>"
         title="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>"
         ><img src="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                         .$image[PhotoGalery_Model_Images::COLUMN_FILE]?>" alt="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>"
                         /></a><?
         }
         echo $this->toolboxImages;
         ?></div>
   <!-- End Gallery Html Containers -->
   <hr class="reseter" />
   <?$this->includeTpl('articletools.phtml', true, array(
           'lastEditTime' => $this->article->{Articles_Model_Detail::COLUMN_EDIT_TIME},
           'lastEditUser' => $this->article->{Model_Users::COLUMN_USERNAME},
           'linkToPdf' => $this->link()->route('detailExport',array('output' => 'pdf')),
           'shares' => $this->shares));?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         $().piroBox({
            slideShow : true, // true == slideshow on, false == slideshow off
            slideSpeed : 3, //slideshow
         });
      });
      /* ]]> */
   </script>
</div>
<?$this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->l()->route('normal')));?>
