<?
$this->addCssFile("style.css");

$this->addPageTitle($this->_('úprava obrázků'));
$this->addPageHeadline($this->_('úprava obrázků'));

$this->addJsPlugin(new JsPlugin_Uploadify());
?>
photogalerymed
<div id="editImagesForm">
   <h2><?=$this->_('Přidání obrázku');?></h2>

   <span id="loader" style="display:none"><img src="images/progress.gif" alt="Loading..." width="16" /></span>
   <div id="sidebar">
      <!-- form to be replaced by uploadify -->
      <form id="mainftp" method="post" action="<?=$this->link()?>" enctype="multipart/form-data">
         <? print ($this->addForm->image->label());
         print ($this->addForm->image->labelValidations());
         print ("<p>".$this->addForm->image->controll()."</p>");
         print ("<p>".$this->addForm->send->controll()."</p>"); ?>
      </form>
   </div>

   <br />
   <?$this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->l()->route('detail', array('urlkey' => $this->urlKey))));?>
   <h2><?=$this->_('Úpravy obrázků');?></h2>
   <div id="allfiles">
      <form method="post" action="<?=$this->link()?>">
         <table style="width:90%;">
            <tr>
               <td colspan="3" align="right">
                  <a href="#" title="<?=$this->_('Označit vše pro smazání')?>" onclick="return deleteAll()"><?=$this->_('Označit vše pro smazání')?></a>
                  <?=$this->editForm->save->controll()?>
               </td>
            </tr>
            <?$step = 0;
            while ($image = $this->images->fetch()) {$step++;
               ?>
            <tr>
               <td width="100">
                  <img src="<?=$this->category()->getModule()->getDataDir(true).Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                              .$image->{PhotoGalery_Model_Images::COLUMN_FILE}?>" alt="<?=$image->{PhotoGalery_Model_Images::COLUMN_FILE}?>" />
               </td>
               <td valign="top" style="padding-right:10px;">
                     <?
                     $this->editForm->name->setDimensional($image->{PhotoGalery_Model_Images::COLUMN_ID});
                     $this->editForm->name->setValues(array($image->{PhotoGalery_Model_Images::COLUMN_ID} =>
                         $image->{PhotoGalery_Model_Images::COLUMN_NAME}));
                     print ($this->editForm->name->label()."<br />");
                     print ($this->editForm->name->labelLangs());
                     print ($this->editForm->name->controll());
                     print ($this->editForm->name->scripts());
                     ?><br />
                     <?
                     $this->editForm->ord->setDimensional($image->{PhotoGalery_Model_Images::COLUMN_ID});
                     $this->editForm->ord->setValues($image->{PhotoGalery_Model_Images::COLUMN_ORDER});
                     print ($this->editForm->ord->label());
                     $this->editForm->ord->html()->setAttrib('size', 5);
                     print ($this->editForm->ord->controll());
                     print ($this->editForm->ord->scripts());
                     ?>
                     <?
                     $this->editForm->delete->setDimensional($image->{PhotoGalery_Model_Images::COLUMN_ID});
                     $this->editForm->delete->setValues(false);
                     print ($this->editForm->delete->label());
                     print ($this->editForm->delete->controll()->setAttrib('onclick', "if(this.checked == true)return confirm('Smazat?')"));
                     print ($this->editForm->delete->scripts());
                     ?><br />

               </td>
               <td valign="top">
                     <?
                     $this->editForm->desc->setDimensional($image->{PhotoGalery_Model_Images::COLUMN_ID});
                     $this->editForm->desc->setValues(array($image->{PhotoGalery_Model_Images::COLUMN_ID} =>
                         $image->{PhotoGalery_Model_Images::COLUMN_DESC}));
                     print ($this->editForm->desc->label()."<br />");
                     print ($this->editForm->desc->labelLangs());
                     print ($this->editForm->desc->controll());
                     print ($this->editForm->desc->scripts());
                     ?>
                     <?
                     $this->editForm->id->setDimensional($image->{PhotoGalery_Model_Images::COLUMN_ID});
                     $this->editForm->id->setValues($image->{PhotoGalery_Model_Images::COLUMN_ID});
                     print ($this->editForm->id->controll());
                     ?>
               </td>
            </tr>
            <tr>
               <td colspan="3" style="border-bottom: 1px solid gray">
                  <a href="<?=$this->link()->route('editphoto', array('id' => $image->{PhotoGalery_Model_Images::COLUMN_ID}))?>"
                     title="<?=$this->_('Upravit miniaturu')?>"><?=$this->_('Upravit miniaturu')?></a>
               </td>
            </tr>

            <?
            if($step%5 == 0){?>
            <tr>
               <td colspan="3" align="right">
                  <?=$this->editForm->save->controll()?>
               </td>
            </tr>
            <?}
            }           
            if($step%5 != 0){?>
            <tr>
               <td colspan="3" align="right">
                  <?=$this->editForm->save->controll()?>
               </td>
            </tr>
            <?}?>
         </table>
         <?=$this->editForm->scripts()?>
      </form>
   </div>

   <?$uploadLink = new Url_Link_ModuleRequest();?>
   <script type="text/javascript">
      /* <![CDATA[ */
      /*jQuery(document).ready(function() {
         var elem = $('#mainftp');
         var elem2 = $('#mainftp').parent();
         $('#mainftp').uploadify({
            'uploader'	: 'jscripts/jqueryuploadify/uploadify.swf',
            'script'    : '<?=$uploadLink->action('uploadFile', 'php');?>',
            'checkScript' : '<?=$uploadLink->action('checkFile', 'php');?>',
            'multi'			: true,
            'auto'			: true,
            'height'		:	'32', //height of your browse button file
            'width'			:	'105', //width of your browse button file
            'sizeLimit'	:	'5120000',  //remove this to set no limit on upload size
            //'simUploadLimit' : '2', //remove this to set no limit on simultaneous uploads
            //'buttonImg' : 'images/browse_<?=Locale::getLang()?>.png',
            'buttonText': '<?=$this->_('Prochazet')?>',
            'cancelImg' : 'images/cancel.png',
            'fileDesc'  : 'images',
            'fileExt'   : '*.jpg;*. jpeg;*.png;*. gif',
            'fileDataName' : 'addimage_image',
            'scriptData' : {'sessionid': '<?=session_id();?>', 'addimage_send' : 'send'},
            onProgress: function() {
               $('#loader').show();
               $('#mainftpQueue').show();
            },
            onAllComplete: function() {
               $('#loader').hide();
               $('#mainftpQueue').hide();
               $('#allfiles').load(location.href+" #allfiles>*","",function(){
                  //alert(location.href+" #allfiles>*");
                  formShowOnlyLang('<?=Locale::getLang()?>');
               });
               
               //location.reload(); //uncomment this line if youw ant to refresh the whole page instead of just the #allfiles div
            },
            onError : function(){
               alert ('Upload error');
            }
         });
      });*/

      function deleteAll(){
         if(confirm('<?=$this->_('Smazat všechny obrázky?')?>')){
            $('#allfiles input[type=checkbox]').each(function(){
               $(this).attr('checked', 'checked');
            });
         }
         return false;
      }
      /* ]]> */
   </script>


   <?$this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->l()->route('detail', array('urlkey' => $this->urlKey))));?>
</div>
