<?
$this->addCssFile("style.css");
$modelImages = new PhotoGalery_Model_Images();
?>
<div class="galeriesList">
   <?if(!empty ($this->articles)) {
      foreach ($this->articles as $article) {
         $noPClass = $noPubllic = null;
         if($article->{Articles_Model_Detail::COLUMN_PUBLIC} == 0){
            $noPClass = 'noPublicGalery';
            $noPubllic = '<span class="smallFont">'.$this->_('Nezveřejněno').'</span>';
         }
         $addDate = new DateTime($article->{Articles_Model_Detail::COLUMN_ADD_TIME});
         ?>
   <div class="<?=$noPClass?>">
      <h2><a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
             title="<?=htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>"><?=htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>&nbsp;
            <span class="smallFont"><?=strftime("%x %X", $addDate->format("U"))?> - <?=$article->{Model_Users::COLUMN_USERNAME}?></span>
         </a><?=$noPubllic?>
      </h2>
      <?
      $images = $modelImages->getImages($this->category()->getId(), 
              $article->{Articles_Model_Detail::COLUMN_ID},
              $this->category()->getParam('imagesinlist', Photogalerymed_Controller::DEFAULT_IMAGES_IN_LIST));
      while ($row = $images->fetch()) {?>
      <img alt="<?=$row->{PhotoGalery_Model_Images::COLUMN_NAME}?>" 
           src="<?=$this->category()->getModule()->getDataDir(true).
              $article[Articles_Model_Detail::COLUMN_URLKEY][Locales::getDefaultLang()]
              .URL_SEPARATOR.Photogalery_Controller::DIR_SMALL
              .URL_SEPARATOR.$row->{PhotoGalery_Model_Images::COLUMN_FILE}?>" />
      <?}?>

            <?//print vve_tpl_truncate(strip_tags($article->{Articles_Model_Detail::COLUMN_TEXT}), 640);?>
      <hr class="reseter" />
      <p style="float:left;"><?=$this->_('Zobrazeno')?>:&nbsp;<?=$article->{Articles_Model_Detail::COLUMN_SHOWED}?>&times;</p>
      <p style="text-align:right;">
         <a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
            title="<?=$article->{Articles_Model_Detail::COLUMN_NAME}?>">[&nbsp;<?=$this->_("více")?>&nbsp;]</a>
      </p>
      <br />
   </div>
     <?}
      print $this->scrollComp;
      print $this->feedsComp;
   } else {
      print ($this->_('Není vložena žádná galerie'));
   }?>

   <?
   echo $this->toolbox;
   ?>
</div>
