<?
$this->addCssFile("style.css");

//$model = new Text_Model_Detail();
//$text = $model->getText(Category::getSelectedCategory()->getId());
//$modelImages = new PhotoGalery_Model_Images();
//$images = $modelImages->getImages($this->category()->getId());

// jquery galerka

?>
<div class="imagesList">
   
   <?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('add_galery', $this->_("Přidat galerii"),
          $this->link()->route('add'),
          $this->_("Přidat galerii"), "image_add.png");
      $this->includeTplObj($toolbox);
   }?>
</div>
