<?
$this->includeTpl('sortLabel.phtml',false,null,'articles');
$h1 = $this->category()->getName().$this->sortText;
$modelImages = new PhotoGalery_Model_Images();
echo $this->toolbox;
?>
<h1><?ps($h1);?></h1>
<div class="posts-list">
   <?=$this->includeTpl('sort.phtml',false,null,'articles')?>
   <?if(!empty ($this->articles)) {
      foreach ($this->articles as $article) {
         $showClass  = null;
         if($article->{Articles_Model::COLUMN_CONCEPT} == 1){
            $showClass = 'concept';
         }
         $addDate = new DateTime($article->{Articles_Model::COLUMN_ADD_TIME});
         
         $text = null;
         // načtení obrázků
         if((string)$article->{Articles_Model::COLUMN_ANNOTATION} != null OR (string)$article->{Articles_Model::COLUMN_TEXT} != null ){
            $text = (string)$article->{Articles_Model::COLUMN_ANNOTATION} != null ? 
               (string)$article->{Articles_Model::COLUMN_ANNOTATION} : vve_tpl_truncate(strip_tags((string)$article->{Articles_Model::COLUMN_TEXT}), 300);
            
         }
         $images = $modelImages->where(PhotoGalery_Model_Images::COLUMN_ID_ART .' = :ida AND '.PhotoGalery_Model_Images::COLUMN_ID_CAT.' = :idc', 
               array('ida' => $article->{Articles_Model::COLUMN_ID}, 'idc' => $this->category()->getId()))
//                 ->limit(0, $this->category()->getParam('imagesinlist', 1))
                 ->order(array(PhotoGalery_Model_Images::COLUMN_ORDER => Model_ORM::ORDER_ASC ))->records();
               
         // title image
         $titleImageFile = $titleImageAlt = null;
         if($article->{Articles_Model::COLUMN_TITLE_IMAGE} != null){
            $titleImageFile = vve_tpl_art_title_image($article->{Articles_Model::COLUMN_TITLE_IMAGE});
            $titleImageAlt = $article->{PhotoGalery_Model_Images::COLUMN_NAME};
         } else if(isset ($images[0])){
            $titleImageFile = $this->category()->getModule()->getDataDir(true).$article[Articles_Model::COLUMN_URLKEY][Locales::getDefaultLang()]
              .URL_SEPARATOR.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR.$images[0]->{PhotoGalery_Model_Images::COLUMN_FILE};
            $titleImageAlt = $images[0]->{PhotoGalery_Model_Images::COLUMN_NAME};
         }
               
         ?>
   <div class="post <?=$showClass?>">
      <h2><a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model::COLUMN_URLKEY}))?>"
             title="<?=htmlspecialchars($article->{Articles_Model::COLUMN_NAME})?>"><?=htmlspecialchars($article->{Articles_Model::COLUMN_NAME})?></a>
         <?if($article->{Articles_Model::COLUMN_CONCEPT} == true){?><span class="font-small"><?=$this->tr('Koncept')?></span><?}?>
      </h2>
      <div class="dateadd">
         <? 
         echo vve_date("%x %H:%i", new DateTime($article->{Articles_Model_Detail::COLUMN_ADD_TIME}));
         printf(' '.$this->tr("(%s fotek)"), count($images));
         ?>
      </div>
      <?
      if($text != null){?>
         <?if($titleImageFile != null){ ?>
         <div class="title-image">
            <img src="<?=$titleImageFile?>" alt="<?ps($titleImageAlt)?>" />
         </div>
         <?}?>
         <div class="annotation">
         <?if((string)$article->{Articles_Model_Detail::COLUMN_ANNOTATION} != null){
            echo strip_tags($article->{Articles_Model_Detail::COLUMN_ANNOTATION}, '<p><a><span><br>');
         } else {
            echo vve_tpl_truncate(strip_tags($article->{Articles_Model_Detail::COLUMN_TEXT}), 640);
         }?>
      </div>
      <?
      } else {
         $numImages = $this->category()->getParam('imagesinlist', 5);
         $i = 1;
         foreach ($images as $img) { ?>
         <div class="title-image image-left <?if($i == $numImages) echo "last";?>">
            <img src="<?=$this->category()->getModule()->getDataDir(true).$article[Articles_Model::COLUMN_URLKEY][Locales::getDefaultLang()]
              .URL_SEPARATOR.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR.$img->{PhotoGalery_Model_Images::COLUMN_FILE}?>" 
              alt="<?=$img->{PhotoGalery_Model_Images::COLUMN_NAME}?>" />
         </div>
         <?
         if($i == $numImages){ break; }
         $i++;
         }
      }
      ?>
      <hr class="reseter" />
      <div class="link-more">
         <a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
            title="<?=$this->tr("více o").' '.$article->{Articles_Model_Detail::COLUMN_NAME}?>">[&nbsp;<?=$this->tr("Více")?>&nbsp;]</a>
      </div>
      </div>
     <?}?>
     <?
      echo $this->scrollComp;
   } else {
      echo ($this->tr('Není vložena žádná galerie'));
   }
   // rss ikony
   $feeds = new Component_Feed();
   $feeds->setConfig('feedLink', $this->link()->clear());
   echo $feeds;
   ?>
</div>
