<h2>Správa obrázků</h2>
<p>Ná této stránce je soustředěna celková správa obrázků dané galerie. Obrázky lez pidávat, mazat či upravovat.</p>
<h3>Nahrávání</h3>
<p>Obrázky se nahrávají pomocí dialogu, který se Vám zobrazí po kliknutím na tlačítko "Vybrat obrázky". V dialogu lze vybrat také více obrázků najednou.
   Po potvrzení výběru jsou obrázky automaticky nahrávány. Po úspěšném nahrání se zobrazí všechny obrázky ve tabulce s obrázky.</p>
<p>Při nahrávání se u velkých obrázků mění velikost již v prohlížeči. Proto nahrání může trvat i delší dobu.</p>

<h3>Úprava textů</h3>
<p>U každého obrázku jsou zobrazeny dvě textová pole. Pole název určuje samotný název obrázku a používá se také jako alternativní text.
   Pole popis rozvíjí informace o obrázku.</p>
<p>U obrázků lze také použít jednoduché nástroje pro jejich úpravu a to otočení a vytvoření miniatury.</p>
<p>
   <strong>POZOR!</strong> Po jekékoliv změně (otočení, dopsání popisků, názvů či pořadí) je nutné seznam obrázků uložit
   pomocí tlačítek napravo na začátku resp. konci seznamu, jinak budou změny ztraceny!
</p>

<p class="note">Delší popisek je zobrazen pouze pokud jej šablona stránek podporuje.</p>

<h3>Mazání obrázku</h3>
<p>U každého obrázku je checkbox pro označení smazání obrázku. Pokud bude obrázek označen, bude při uložení seznamu smazán.</p>
<p>Mazat obrázky lze přímo také pomocí ikonky křížku v pravém horním rohu řádku s obrázkem.</p>

