<h2>Řazení obrázků</h2>
<p>Ná této stránce jsou seřazeny všechny obrázky galerie v řádcích jejich nastaveném pořadí.</p>
<h3>Řazení</h3>
<p>Obrázky stačí přesunovat myší na nové polohy.</p>
<h3>Uložení pořadí</h3>
<p>Po dokončení řazení je nutné pozice uložit <strong>tlačítky</strong> na konci seznamu.</p>

<h3>Mazání obrázku</h3>
<p>U každého obrázku je v pravém horním rohu tlačítko pro mazání obrázku. Po kliknutí a potvrzení je obrázek smazán z aplikace.</p>

