<?
$this->addJsPlugin(new JsPlugin_JQuery());
echo $this->toolbox;
?>
<h1><?=$this->category()->getName();?></h1>
<div class="main-content-detail">
<a href="#" title="<?=$this->tr('Přidat příspěvek')?>" id="toggleForm"><?=$this->tr('Přidat příspěvek')?></a>
<div id="guestbookNewItemForm">
   <?
   $this->form->text->html()->setAttrib('cols', 60)->setAttrib('rows', 7);
   echo ($this->form);
   ?>
</div>
<script type="text/javascript">
   /* <![CDATA[ */
   $('#guestbookNewItemForm').hide();
   $('#toggleForm').click(function(){
      $('#guestbookNewItemForm').show();
      $(this).hide();
      return false;
   });
   <?if($this->showFrom === true){?>
   $('#toggleForm').click();
   <?}?>
   /* ]]> */
</script>
</div>
<hr class="reseter" />
<br />
<?=$this->includeFile('tpl://list.phtml');?>

