<?php 
$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
?>
<div class="panel-box-label"><?php echo $icon?><a href="<?php echo $this->link()?>" title="<?php echo htmlspecialchars($this->panelObj()->getName())?>"><?php echo $this->panelObj()->getName()?></a></div>
   <?php if($this->lastPosts != null){?>
      <div class="panel-box-content-label"><?php echo $this->tr('Poslední příspěvek:', count($this->lastPosts));?></div>
      <?php foreach ($this->lastPosts as $message) {?>
         <div class="panel-box-content">
         <strong><?php echo $message->{GuestBook_Model::COLUMN_NICK}?></strong><br />
         <?php echo $this->filter(vve_tpl_xhtml_cut(strip_tags($message->{GuestBook_Model::COLUMN_TEXT},VVE_SHORT_TEXT_TAGS),150), array('emoticons'))?>
         </div>
      <?php }?>
   <?php }?>
   <?php 
   if($this->leaveMsg){?>
   <div class="panel-box-content">
      <a href="<?php echo $this->link()->param('s', true)?>" title="<?php echo htmlspecialchars($this->category()->getLabel().' - '.$this->tr('Zanechte nám vzkaz'))?>"><?php echo $this->tr('Zanechte nám vzkaz')?></a>
   </div>
   <?php }?>
<div class="panel-box-link-more"><a href="<?php echo $this->link()?>" title="<?php echo htmlspecialchars($this->category()->getLabel())?>"><?php echo $this->tr('Více')?></a></div>