<?php 
$this->addFile('css://style.css');
// do titulku
$h = sprintf( $this->tr('Úprava parametru "%s"'), $this->paramName );
$this->addPageTitle($h);

function renderCatsList($childs, $form, $link, $param) 
{
   foreach ($childs as $child) {
      
      $obj = $child->getCatObj()->getDataObj();
      $form->param->setDimensional($obj->{Model_Category::COLUMN_ID});
      $value = $obj->{$param};
      $form->param->setValues($value);
   ?>
      <li class="cubecms-list-row">
         <div class="name cubecms-header">
            <?php ps($obj->{Model_Category::COLUMN_NAME}); ?> 
            <a href="<?php echo $link->category($obj->{Model_Category::COLUMN_URLKEY})?>"
               title="<?php ps($obj->{Model_Category::COLUMN_ALT})?>"
               class="link-external"><em>(URL: <?php ps($obj->{Model_Category::COLUMN_URLKEY})?>)</em></a>
         </div>
         <div class="form-group">
            <div class="form-controls">
               <?php  
   //             echo $form->param->label();
               echo $form->param->labelLangs();
               $form->param->html()->addClass('form-control');
               echo $form->param->controllAll();
               ?>
            </div>
         </div>
         <?php  if(!$child->isEmpty()){?>
         <ul>
            <?php renderCatsList($child, $form, $link, $param) ?>
         </ul>      
         <?php }?>
      </li>   
   <?php 
   }
}
?>
<h1><?php ps($h) ?></h1>
<div class="content-admin">
   <?php echo $this->form->renderStart();?>
   <ul id="categories-list" class="cubecms-widget cubecms-list">
      <?php  
      renderCatsList($this->struct, $this->form, $this->link()->clear(), $this->param);
      ?>
      <li><?php echo $this->form->save->controllAll();?></li>
   </ul>
   <?php echo $this->form->renderEnd();?>
   <?php  
   ?>
   <script type="text/javascript">
      /* <![CDATA[ */
      /* ]]> */
   </script>
</div>
