<?php  
$this->addJsPlugin(new JsPlugin_JQueryCSS());

?>
<h1><?php echo $this->tr('Záloha')?></h1>
<?php $this->includeTpl('navigation.phtml');?>
<div class="post content">
   <h2><?php echo $this->tr('Vytvoření zálohy')?></h2>
   <?php  
   echo $this->form->renderStart();
   echo $this->form->type->label();
   echo $this->form->type->control();
   echo $this->form->backup->control();
   echo $this->form->renderEnd();
   ?>
   <br />
   <h2><?php echo $this->tr('Provedené zálohy')?></h2>
   <table class="full-width ui-widget">
   	<thead class="ui-widget-header">
      	<tr>
      		<th><?php echo $this->tr('Název')?></th>
   	   	<th><?php echo $this->tr('Velikost')?></th>
   	   	<th></th>
      	</tr>
   	</thead>
      <tbody>
   	   <?php foreach ($this->backupFiles as $file) {
   	      $filename = pathinfo($file, PATHINFO_BASENAME);
   	      ?>
      	<tr class="ui-widget-content <?php if(filemtime($file) <= (time()-60*60*24*31) ) echo "ui-state-disabled" ?>">
      		<td><?php echo $filename?></td>
   	   	<td><?php 
   	   	   $s = filesize($file);
   	   	   if($s > 1024*1024){
   	   	      echo round($s/1024/1024, 2)." MB";
   	   	   } else if($s > 1024) {
   	   	      echo round($s/1024, 2 )." KB";
   	   	   } else {
   	   	      echo $s." B";
   	   	   }
   	   	?></td>
   	   	<td style="text-align: right;">
   	   	   <a href="<?php echo $this->link()->route('fileAction')->param('a', 'dw')
   	   	      ->param('file', $filename)?>"
   	   	      ><img src="/images/icons/download.png" /></a>
   	   	</td>
   	   </tr>
   	   <?php }?>
      </tbody>
      <tfoot class="ui-widget-header">
         <tr>
            <td colspan="3">
            <?php  
            $this->formClean->html()->setAttrib('onsubmit', 'return confirm(\''.$this->tr('Smazat zálohy?').'\');');
            echo $this->formClean->renderStart();
            echo $this->formClean->oldest->label();
            echo $this->formClean->oldest->controll();
            $this->formClean->clean->html()->addClass('cancel');
            echo $this->formClean->clean->controll();
            echo $this->formClean->renderEnd();
            ?>
            </td>
         </tr>
      </tfoot>	
   </table>
</div>
