<?
$this->addPageTitle($this->tr('Databáze'));
//$this->addCssFile('style.css');
$jsJqGrid = new Component_JqGrid_JsPlugin();
$this->addJsPlugin($jsJqGrid);
$jQuery = new JsPlugin_JQuery();
$this->addJsPlugin($jQuery);
?>
<h1><?=$this->tr('Databáze');?></h1>
<?$this->includeTpl('navigation.phtml');?>

<div class="main-content-detail">
   <table id="table-tables"></table>
   <div id="table-tables-pager"></div>
   <hr class="reseter" />
   <br />
   <table>
   	<tr>
   		<td><? 
            echo $this->formOptimizeDbTables->renderStart();
            echo $this->formOptimizeDbTables->optimise->controll();
            echo $this->formOptimizeDbTables->renderEnd();
   		?></td>
   		<td><? 
            echo $this->formRepairDbTables->renderStart();
            echo $this->formRepairDbTables->repair->controll();
            echo $this->formRepairDbTables->renderEnd();
   		?></td>
   	</tr>
   </table>
</div>
<script type="text/javascript" charset="utf-8">
      /* <![CDATA[ */
      var selectedGroupId = 0;
      $(document).ready(function() {
         var addressGrid = $("#table-tables").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url: '<?=$this->link()->route('tablesList');?>',
            datatype: "json",
            colNames:['<?=$this->tr('Název')?>', '<?=$this->tr('Řádků')?>', '<?=$this->tr('Velikost (B)')?>', '<?=$this->tr('Kolace')?>', '<?=$this->tr('Engine')?>', '<?=$this->tr('Kontrola')?>'],
            colModel:[
               {name:'<?=Model_Tables::COL_TABLE_NAME?>',index:'<?=Model_Tables::COL_TABLE_NAME?>', editable:false},
               {name:'<?=Model_Tables::COL_TABLE_ROWS?>',index:'<?=Model_Tables::COL_TABLE_ROWS?>', width:60, fixed: true,editable:false},
               {name:'<?=Model_Tables::COL_DATA_LENGTH?>',index:'<?=Model_Tables::COL_DATA_LENGTH?>', width:90,fixed: true,editable:false},
               {name:'<?=Model_Tables::COL_TABLE_COLLATION?>',index:'<?=Model_Tables::COL_TABLE_COLLATION?>', width:100,fixed: true,editable:false},
               {name:'<?=Model_Tables::COL_ENGINE?>',index:'<?=Model_Tables::COL_ENGINE?>', width:70,fixed: true,editable:false},
               {name:'check',index:'check', width:100,sortable:false, editable:false},
            ],
            rowNum:20,
            rowList:[10,20,40,100],
            pager: '#table-tables-pager',
            sortname: '<?=Model_Tables::COL_TABLE_NAME?>',
            caption:"<?=$this->tr('Tabulky v databázi')?>",
            autowidth : true,
            height: '100%'
         });
         addressGrid.jqGrid('navGrid','#table-tables-toolbar',{edit:false,add:false,del:false});
//         // úpravy
         jQuery("#table-tables").jqGrid('navGrid','#table-tables-pager',
            {view:false, edit:false, add:false, del:false},
            {closeAfterSearch: true,closeOnEscape:true,sopt : ['eq','ne','cn','nc']}, // search options
            {height:120,jqModal:true,closeOnEscape:true} // view options
         );
      });
      /* ]]> */
      </script>