<? 
$this->addJsPlugin(new JsPlugin_JQueryCSS());

define('ADMINER_PATH', AppCore::getAppLibDir()."modules".DIRECTORY_SEPARATOR."services".DIRECTORY_SEPARATOR."adminer".DIRECTORY_SEPARATOR);

?>
<h1><?=$this->tr('Administrace databáze')?></h1>
<?$this->includeTpl('navigation.phtml');?>
<div class="post content">
   <? 
//    include ADMINER_PATH."init.php" ;
   ?>
   <iframe src="<?=Url_Request::getBaseWebDir(true).'modules/services/adminer/init.php?'
      .'server='.VVE_DB_SERVER.'&amp;username='.VVE_DB_USER.'&amp;database='.VVE_DB_NAME?>" 
      style="width: 100%; height: 800px;">
   </iframe>
</div>
