<?php 
$jq = new JsPlugin_JQuery();
$jq->addUIButton();
$this->addJsPlugin($jq);

define('ADMINER_PATH', AppCore::getAppLibDir()."modules".DIRECTORY_SEPARATOR."services".DIRECTORY_SEPARATOR."adminer".DIRECTORY_SEPARATOR);

?>
<h1><?php echo $this->tr('Administrace databáze')?></h1>
<?php $this->includeTpl('navigation.phtml');?>
<div class="post content">
   <?php  
//    include ADMINER_PATH."init.php" ;
   ?>
   <div id="iframe-buttons" style="margin-bottom: 10px">
      <a id="button-enable-fullscreen"><?php ps($this->tr('Na celou obrazovku'))?></a>
   </div>
   <iframe id="adminer-iframe" src="<?php echo Url_Request::getBaseWebDir(true).'modules/services/adminer/init.php?'
      .'server='.VVE_DB_SERVER.'&amp;username='.VVE_DB_USER.'&amp;database='.VVE_DB_NAME?>" 
      style="width: 100%; height: 800px; margin:0; padding: 0;">
   </iframe>
   <a id="button-disable-fullscreen" href="<?php echo $this->link()?>#fullscreen"><img src="images/icons/cross.png" alt="close" /></a>
   <script type="text/javascript">
      $(document).ready(function(){
         $( "#button-enable-fullscreen" ).button({
            icons: {
               primary: "ui-icon-zoomin"
            }
         });
         $('#button-enable-fullscreen').click(function(){
            $('#adminer-iframe').css({
               position : "fixed",
               top : 30, left : 0,
               height : "95%"
            });
            $(this).hide();
            $('#button-disable-fullscreen').css({
               position : "fixed",
               top : 30, right : 0
            }).show();
            return false;
         });

         $('#button-disable-fullscreen').hide().click(function(){
            $(this).hide();
            $('#adminer-iframe').css({
               position : "relative",
               top : "auto", left : "auto",
               height : "800px"
            });
            $('#button-enable-fullscreen').show();
         });

      });
   </script>
</div>
