<?php 
$this->addPageTitle($this->tr('Diskový prostor'));
?>
<h1><?php echo  $this->tr('Diskový prostor'); ?></h1>
<?php  $this->includeTpl('navigation.phtml'); ?>
<div class="main-content-detail">
   <h2>Cache</h2>
   <div>
      Vyčištění odkládacího prostoru pro soubory.<br />
      Aktuální velikost:
      <span style="font-weight:bold;<?php  if ($this->isBigSize === true) { echo ("color:red;");}?>">
         <?php if ($this->cacheSize > 1024 * 1024) {
            echo (round($this->cacheSize / (1024 * 1024), 2) . "&nbsp;MB");
         } else if ($this->cacheSize > 1024) {
            echo (round($this->cacheSize / (1024), 2) . "&nbsp;KB");
         } else {
            echo (round($this->cacheSize, 2) . "&nbsp;B");
         }?>
      </span>
      <form action="<?php echo  $this->link() ?>" method="post">
         <?php echo $this->formClearCache->clear->controll() ?>
      </form>
   </div>
   <br />
   <h2>Data</h2>
   <div>
      Aktuální velikost:
      <span><?php if ($this->dataSize > 1024 * 1024) {
            echo (round($this->dataSize / (1024 * 1024), 2) . "&nbsp;MB");
         } else if ($this->dataSize > 1024) {
            echo (round($this->dataSize / (1024), 2) . "&nbsp;KB");
         } else {
            echo (round($this->dataSize, 2) . "&nbsp;B");
         }?></span>
   </div>
</div>
