<?
$this->addPageTitle($this->_('Pamět'));
?>
<h1><?= $this->_('Pamět'); ?></h1>
<? $this->includeTpl('navigation.phtml'); ?>
<div class="main-content-detail">
   <h2>Cache</h2>
   <div>
      Vyčištění odkládacího prostoru pro soubory.<br />
      Aktuální velikost:
      <span style="font-weight:bold;<? if ($this->isBigSize === true) { echo ("color:red;");}?>">
         <?if ($this->cacheSize > 1024 * 1024) {
            echo (round($this->cacheSize / (1024 * 1024), 2) . "&nbsp;MB");
         } else if ($this->cacheSize > 1024) {
            echo (round($this->cacheSize / (1024), 2) . "&nbsp;KB");
         } else {
            echo (round($this->cacheSize, 2) . "&nbsp;B");
         }?>
      </span>
      <form action="<?= $this->link() ?>" method="post">
         <?=$this->formClearCache->clear->controll() ?>
      </form>
   </div>
   <br />
   <h2>Data</h2>
   <div>
      Aktuální velikost:
      <span><?if ($this->dataSize > 1024 * 1024) {
            echo (round($this->dataSize / (1024 * 1024), 2) . "&nbsp;MB");
         } else if ($this->dataSize > 1024) {
            echo (round($this->dataSize / (1024), 2) . "&nbsp;KB");
         } else {
            echo (round($this->dataSize, 2) . "&nbsp;B");
         }?></span>
   </div>
</div>
