<?
$this->items = array(
   'Diskový prostor' => array('link' => (string)$this->link()->route(), 'icon' => 'disk.png'),
   'Databáze' => array('link' => (string)$this->link()->route('database'), 'icon' => 'database.png'),
   'Správa databáze' => array('link' => (string)$this->link()->route('dbadmin'), 'icon' => 'database_edit.png'),
   'Záloha' => array('link' => (string)$this->link()->route('backup'), 'icon' => 'database_save.png')
   );
$this->includeTpl('module_navigation.phtml', true);?>