<?
// načtení detailu
$h1 = $this->category()->getName().' - '.$this->tr('Archiv');
Template_Core::setPageTitle($h1);

$jQuery = new JsPlugin_JQuery();
$jQuery->addUIAccordion();
$this->addJsPlugin($jQuery);
?>
<h1><?$this->includeFile('tpl://engine:headline/icon.phtml'); echo $h1; ?></h1>
<div class="main-content-tools">
   <a href="<?=$this->link()->route();?>" title="<?$this->tr('Přejít na seznam článků')?>"><?=$this->tr('Seznam')?></a>
</div>
<div class="main-content-archive">
   <? foreach ($this->articles as $year => $rows) {?>
      <h2 class="main-content-archive-year year<?= $year ?>"><a href="#"><?= $year ?></a></h2>
      <div class="main-content-archive-year-content">
         <ul>
         <?foreach ($rows as $row) {
            $title = $row->{Articles_Model::COLUMN_NAME};
            if ((string) $row->{Articles_Model::COLUMN_ANNOTATION} != null) {
               $title = strip_tags($row->{Articles_Model::COLUMN_ANNOTATION});
            }
            $date = new DateTime($row->{Articles_Model::COLUMN_ADD_TIME});
            ?>
            <li class="main-content-archive-item">
               <a href="<?= $this->link()->route('detail', array('urlkey' => $row->{Articles_Model::COLUMN_URLKEY})) ?>"
                  title="<?= htmlspecialchars($title)?>"><?=htmlspecialchars($row->{Articles_Model::COLUMN_NAME});?></a>&nbsp;&nbsp;<span class="main-content-archive-dateadd">(<?=vve_date("%x", $date);?>)</span>
            </li>
            <? } ?>
      </ul>
   </div>
   <? } ?>
   </div>
   <hr class="reseter" />
   <script type="text/javascript">

      $(function() {
         $(".main-content-archive").accordion({
            collapsible: true
         });
      });
   </script>
