<? // detail článku pouze jako html 
$addDate = new DateTime($this->article->{Articles_Model_Detail::COLUMN_ADD_TIME});
$editDate = new DateTime($this->article->{Articles_Model_Detail::COLUMN_EDIT_TIME});
?>
<h1><?=htmlspecialchars($this->article->{Articles_Model_Detail::COLUMN_NAME})?></h1>
<div class="print-detail">
   <div class="font-small"><?=$this->_('Přidáno')." ".strftime("%x %X", $addDate->format("U"))
          ."&nbsp;".$this->_('uživatelem')."&nbsp;".$this->article->{Model_Users::COLUMN_USERNAME}?>.&nbsp;
      <?=$this->_('Zobrazeno')?>:&nbsp;<?=$this->article->{Articles_Model_Detail::COLUMN_SHOWED}?>&times;
   </div>
   <!--</h2>-->
   <?=$this->article->{Articles_Model_Detail::COLUMN_TEXT}?>
   <hr class="reseter" />
   <?if($this->allowPrivate === true){?>
      <?=$this->article->{Articles_Model_Detail::COLUMN_TEXT_PRIVATE}?>
      <hr class="reseter" />
   <?}?>
   <?$this->includeTpl('articletools.phtml', true, array(
      'lastEditTime' => $this->article->{Articles_Model_Detail::COLUMN_EDIT_TIME},
              'lastEditUser' => $this->article->{Model_Users::COLUMN_USERNAME},
              'linkToPdf' => $this->link()->route('detailExport', array('output' => 'pdf')),
              'linkToHtml' => $this->link()->route('detailExport', array('output' => 'html')),
              'shares' => $this->shares));?>
   
</div>
