<div class="main-content-list">
   <?php if(!empty ($this->articles)) {
      foreach ($this->articles as $article) {
         $showClass = $public = null;
         if($article->{Articles_Model::COLUMN_CONCEPT} == 1) {
            $showClass = 'main-content-concept';
            $public = $this->tr('Koncept');
         }
         $editTime = new DateTime($article->{Articles_Model::COLUMN_ADD_TIME});
         ?>
   <div class="main-content-list-record <?php echo $showClass?>">
      <h2><a href="<?php echo $this->link()->route('detail', array('urlkey' => $article->{Articles_Model::COLUMN_URLKEY}))?>"
             title="<?php echo htmlspecialchars($article->{Articles_Model::COLUMN_NAME})?>"><?php echo htmlspecialchars($article->{Articles_Model::COLUMN_NAME})?>&nbsp;
            <span class="font-small">
                     <?php echo strftime("%x %X", $editTime->format("U"))?> - <?php echo $article->{Model_Users::COLUMN_USERNAME}?></span>
         </a><?php echo '<span class="font-small">'.$public.'</span>'?>
      </h2>
            <?php  // nalezneme v textu první obrázek, pokud ano vykreslíme jej
            $out = array();
            preg_match('/< *[img][^>]*[src] *= *[\"\']{0,1}([^"\'\ >]*)/i', $article->{Articles_Model::COLUMN_TEXT}, $out);
            if(!empty ($out) AND $out[1] != '0') {?>
      <div class="main-content-image"><?php echo vve_tpl_image_tag($out[1], "article title image", 130, 100);?></div>
               <?php }?>
      <div class="main-content-text"><?php echo $article->{Articles_Model::COLUMN_TEXT};?></div>
      <hr class="reseter" />
   </div>
         <?php }
   } else {
      print ($this->tr('Není vložen žádný článek'));
   }?>
</div>
