<? // načtení detailu
$this->addPageTitle($this->article->{Articles_Model::COLUMN_NAME});
$h1 = $this->article->{Articles_Model::COLUMN_NAME};
$piroBox = new JsPlugin_PiroBox();
$this->addJsPlugin($piroBox);
echo $this->toolbox;

$image = null;
if ($this->article->{Articles_Model::COLUMN_TITLE_IMAGE} != null) {
   $image = vve_tpl_image_tag(
      vve_tpl_art_title_image($this->article->{Articles_Model::COLUMN_TITLE_IMAGE}), $this->article->{Articles_Model::COLUMN_NAME}, 100, 100, array('title-image'));
}

$editTime = new DateTime($this->article->{Articles_Model::COLUMN_ADD_TIME});
?>

<h1><?$this->includeFile('tpl://engine:headline/icon.phtml'); echo htmlspecialchars($h1); if($this->article->{Articles_Model::COLUMN_CONCEPT} == true)echo $this->tr(' - koncept');?></h1>

<div class="post">
   <span class="date"><?=strftime("%x %X", $editTime->format("U"))?> - <?=$this->article->{Model_Users::COLUMN_USERNAME}?></span>
   <?if((string)$this->article->{Articles_Model::COLUMN_ANNOTATION} != null){?>
   <div class="annotation"><?
      echo $image;$image = null;
      echo $this->filter((string)$this->article->{Articles_Model::COLUMN_ANNOTATION}, array('emoticons', 'filesicons'));
      ?>
   <hr class="reseter" />
   </div>
   <?}?>
   <div class="text"><?
      echo $image;
      echo $this->filter((string)$this->article->{Articles_Model::COLUMN_TEXT}, array('emoticons', 'filesicons'));
    ?></div>
   <hr class="reseter" />
   <?$this->includeTpl('privateText.phtml', false,null,'articles');?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){$().piroBox({slideShow : true, slideSpeed : 3});});
      /* ]]> */
   </script>
   <hr class="reseter" />
   <?if($this->articles != null){?>
   <form name="gotoart" action="<?=$this->link();?>" method="get" onsubmit="document.gotoart.action = document.getElementById('gotoArtLinkSel').value">
      <p>
         <label><?=$this->tr('Přejít na')?></label>
         <select id="gotoArtLinkSel">
            <?foreach ($this->articles as $article) {?>
            <option value="<?=$this->link()->route('detail', array('urlkey' => (string)$article->{Articles_Model::COLUMN_URLKEY}));?>">
            <?=vve_tpl_truncate((string)$article->{Articles_Model::COLUMN_NAME}, 100)?>
            </option>
            <?}?>
         </select>
         <input type="submit" value="<?=$this->tr('Přejít')?>" />
      </p>
   </form>
   <?} else {
      $this->includeTpl("buttonback.phtml", true);
   }
   if($this->category()->getParam('shareTools', true) == true){
   $this->includeTpl('articletools.phtml', true, array(
      'lastEditTime' => $this->article->{Articles_Model::COLUMN_EDIT_TIME},
              'lastEditUser' => $this->article->{Model_Users::COLUMN_USERNAME},
              'createdByUser' => $this->article->usernameCreated,
              'linkToPdf' => $this->link()->route('detailExport', array('output' => 'pdf')),
              'linkToHtml' => $this->link()->route('detailExport', array('output' => 'html')),
              'shares' => array('url' => $this->link(), 'title' => $this->article->{Articles_Model::COLUMN_NAME})));
   }
//   echo $this->toolbox;
   ?>
   <?
   if($this->article != null AND ( 
      strpos((string)$this->article->{Articles_Model_Detail::COLUMN_TEXT}, 'pirobox') !== false
      OR strpos((string)$this->article->{Articles_Model::COLUMN_TEXT_PRIVATE}, 'pirobox') !== false)){
   
      $this->addJsPlugin(new JsPlugin_PiroBox());
   ?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){$().piroBox({slideShow : true,slideSpeed : 3});});
      /* ]]> */
   </script>
<?}?>
</div>
<?echo $this->comments;?>


