<?
$this->addCssFile("style.css");
// do titulku
if($this->edit) {
   $h = $this->_('úprava článku').' '.$this->catName;
} else {
   $h = $this->_('přidání článku');
}
$this->addPageTitle($h);
// donastavení formuláře
$this->form->name->html()->setAttrib('size', 72);
$this->form->urlkey->html()->setAttrib('size', 72);
$this->form->metaKeywords->html()->setAttrib('size', 72);
$this->form->annotation->html()->setAttrib('cols', 70)->setAttrib('rows', 5)->addClass("mceEditorSimple");
$this->form->metaDesc->html()->setAttrib('cols', 70)->setAttrib('rows', 3);
$this->form->text->html()->setAttrib('cols', 70)->setAttrib('rows', 30)->addClass("mceEditor");
if($this->form->haveElement('textPrivate')){
   $this->form->textPrivate->html()->setAttrib('cols', 70)->setAttrib('rows', 30)->addClass("mceEditor");
}

$tinySimple = new JsPlugin_TinyMce();
$tinySimple->setCfgParam(JsPlugin_TinyMce::PARAM_THEME, JsPlugin_TinyMce::TINY_THEME_ADVANCED_SIMPLE);
$tinySimple->setCfgParam('editor_selector', 'mceEditorSimple');
$this->addJsPlugin($tinySimple);

$tinymce = new JsPlugin_TinyMce();
$tinymce->setCfgParam(JsPlugin_TinyMce::PARAM_THEME, JsPlugin_TinyMce::TINY_THEME_ADVANCED);
$tinymce->setCfgParam('editor_selector', 'mceEditor');
$this->addJsPlugin($tinymce);
?>
<h1><?=$h;?></h1>
<div class="main-content-form-edit" id="article-edit-form">
   <?print($this->form);?>
</div>
<?if($this->edit === true){
   $this->includeTpl("buttonback.phtml", true, array('link' => $this->link()->route('detail')));
} else {
   $this->includeTpl("buttonback.phtml", true, array('link' => $this->link()->clear()));
}?>
