<div id="editArticleForm">
   <ul class="langMenu">
      <? foreach ($this->pVar("appLangsNames") as $key => $lang) {?>
      <li>
         <a href="#articleLang<?=$key?>" class="selectedd">
            <img src="images/lang/<?$key?>.png" title="<?=$lang?>" />
            <?=$lang?>
         </a>
      </li>
      <?}?>
   </ul>

   <div class="tabsContent">
      <form method="post" action="<?=$this->l();?>">
         <? foreach ($this->pVar("appLangsNames") as $key => $lang) {?>
         <p id="articleLang<?=$key?>" class="tabcontent">
            <?=$this->_m("Název článku");?>:<br />
            <input type="text" size="40" maxlength="50" name="article_label[<?=$key?>]"
            value="<?=$this->post("article_label[$key]", $this->article['label'][$key]);?>" /><br />
            <?=$this->_m("Text");?>*:<br />
            <textarea class="textarea_tinymce textarea" rows="25" cols="70"
            name="article_text[<?=$key;?>]"><?=$this->post("article_text[$key]", $this->article['text'][$key]);?></textarea>
         </p>

         <?}?>
         <br />
         <input name="article_reset" type="reset" value="<?=$this->_m("Obnovit")?>" />
         <input name="article_send" type="submit" value="<?=$this->_m("Odeslat")?>" />
         <?$this->includeTpl("help.phtml", true, array('file' => 'edit', 'module' => 'articles'));?>
         <?if($this->edit){?>
            <input name="article_id" type="hidden" value="" />
         <?}?>

      </form>
      
   </div>
   <?$this->includeTpl("buttonback.phtml", true, array('link' => $this->l()->action()));?>
   <script>
      $(document).ready(function(){
         $("#editArticleForm").tabs();
      });
   </script>
      <? $this->includeTplObj($this->EPLfiles); ?>

</div>
