<?
$this->addFile("css://articles:style.css?original");
$jq = new JsPlugin_JQuery();
$jq->addUIDatepicker();
$this->addJsPlugin($jq);
// do titulku
if($this->edit) {
   $h = $this->tr('úprava položky').' '.$this->artName;
} else {
   $h = $this->tr('přidání položky');
}
$this->addPageTitle($h);
// donastavení formuláře
$this->form->name->html()->setAttrib('size', 60)->addClass('form-element-long');
$this->form->urlkey->html()->setAttrib('size', 60)->addClass('form-element-long');
$this->form->metaKeywords->html()->setAttrib('size', 60)->addClass('form-element-long');
$this->form->annotation->html()->setAttrib('cols', 58)->setAttrib('rows', 5);
$this->form->metaDesc->html()->setAttrib('cols', 58)->setAttrib('rows', 3);
$this->form->text->html()->setAttrib('cols', 58)->setAttrib('rows', 30);
if($this->form->haveElement('textPrivate')){
   $this->form->textPrivate->html()->setAttrib('cols', 70)->setAttrib('rows', 30);
}

// datepickery
$this->form->created_date->html()->addClass('datepicker');
?>
<h1><?=$h;?></h1>
<div class="main-content-form-edit" id="article-edit-form">
   <?
   echo($this->form);
   $this->includeFile('tpl://engine:parts/seltitleimage.phtml');
   ?>
</div>
<script type="text/javascript">
   /* <![CDATA[ */
   $(document).ready(function(){
      $.datepicker.setDefaults(['<?= Locales::getLang() ?>'] ) ;
      $("input.datepicker").datepicker();
   });
   /* ]]> */
</script>
