<?
// načtení článků
$artModel = new Articles_Model_List();
$articles = $artModel->getList($this->category()->getId());

?>

<div class="articlesList">
   <?if(!empty ($articles)) {
      foreach ($articles as $article) {?>
   <div>
      <h2><a href="<?=$this->link()?>"
             title="<?=$article->{Articles_Model_Detail::COLUMN_NAME}?>"><?=$article->{Articles_Model_Detail::COLUMN_NAME}?>&nbsp;
            <span class="smallFont"><?//=strftime("%x %X", $article['add_time'])?> - <?//=$article['username']?></span>
         </a>
      </h2>
      <div class="imageBox">
               <?
               //         var_dump($article);exit;
//               if(isset($article['title_image'])) {
//                  print imageTag($article['title_image'], "article title image", 80, 80);
//               } else {
                  ?>
                  <img src="images/icons/article_icon.png" alt="article title image" height="80" />
               <?

               //}
            ?>
      </div>
            <?//print (xhtml_cut(remove_tag('img', $article['text']), 650));?>
            <?//print truncate(strip_tags($article['text']), 640);?>
      <p style="text-align:right;">
         <a href="<?=$this->link()?>"
            title="<?//=$article['label']?>">[&nbsp;<?=$this->_("více")?>&nbsp;]</a>
      </p>
      <hr class="reseter" />
   </div>
      <?}
   } else {
      print ($this->_('Není vložen žádný článek'));
   }?>
   
   <?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('add_article', $this->_("Přidat článek"),
          $this->link()->route('add'),
          $this->_("Přidat nový článek"), "text_add.png");
      $this->includeTplObj($toolbox);
   }
   ?>
</div>
<?
//$this->includeTplObj($this->EPLscroll);
?>