<?
$this->addCssFile("style.css");

if($this->top === true) {
   $this->addPageTitle($this->_('nejčtenější články'));
   $this->addPageHeadline($this->_('nejčtenější články'));
}
?>
<div class="articlesList">
<p style="text-align:right">
<?if($this->top === true) {?>
   <a href="<?=$this->link()->route()->rmParam()?>" title="<?=$this->_('Nejnovější články')?>"><?=$this->_('Nejnovější články')?></a>
   <?} else {?>
   <a href="<?=$this->link()->route('top')->rmParam()?>" title="<?=$this->_('Nejčtenější články')?>"><?=$this->_('Nejčtenější články')?></a>
   <?}?>
   <a href="<?=$this->link()->route('archive')->rmParam()?>" title="<?=$this->_('Archiv')?>"><?=$this->_('Archiv')?></a>
</p>
   <?if(!empty ($this->articles)) {
      foreach ($this->articles as $article) {
         $showClass = $public = null;
         if($article->{Articles_Model_Detail::COLUMN_PUBLIC} == 0){
            $showClass = 'noPublicArticle';
            $public = $this->_('Nezveřejněn');
         }
         ?>
   <div class="<?=$showClass?>">
      <h2><a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
             title="<?=htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>"><?=htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>&nbsp;
            <span class="smallFont">
             <?=strftime("%x %X", $article->{Articles_Model_Detail::COLUMN_ADD_TIME})?> - <?=$article->{Model_Users::COLUMN_USERNAME}?></span>
         </a><?='<span class="smallFont">'.$public.'</span>'?>
      </h2>
            <? // nalezneme v textu první obrázek, pokud ano vykreslíme jej
            $out = array();
            preg_match('/< *[img][^>]*[src] *= *[\"\']{0,1}([^"\'\ >]*)/i', $article->{Articles_Model_Detail::COLUMN_TEXT}, $out);
            if(!empty ($out) AND $out[1] != '0') {?>
      <div class="imageBox">
                  <?=vve_tpl_image_tag($out[1], "article title image", 80, 80);?>
      </div>
            <?}?>

            <?//print (vve_tpl_xhtml_cut(strip_tags('img', $article->{Articles_Model_Detail::COLUMN_TEXT}), 650));?>
            <?print vve_tpl_truncate(strip_tags($article->{Articles_Model_Detail::COLUMN_TEXT}), 640);?>
      <hr class="reseter" />
      <p style="float:left;"><?=$this->_('Zobrazeno')?>:&nbsp;<?=$article->{Articles_Model_Detail::COLUMN_SHOWED}?>&times;</p>
      <p style="text-align:right;">
         <a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
            title="<?//=$article['label']?>">[&nbsp;<?=$this->_("více")?>&nbsp;]</a>
      </p>
      <br />
   </div>
     <?}
      print($this->scrollComp);
   } else {
      print ($this->_('Není vložen žádný článek'));
   }?>

   <?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('add_article', $this->_("Přidat článek"),
          $this->link()->route('add'),
          $this->_("Přidat nový článek"), "page_add.png");
      $this->includeTplObj($toolbox);
   }
   ?>
</div>
