<?
$h1 = $this->category()->getName()
?>
<h1><?$this->includeFile('tpl://engine:headline/icon.phtml'); echo $h1;?></h1>
<div data-role="content" class="list">
   <?if(!empty ($this->articles)) {
      foreach ($this->articles as $article) {
         $showClass = $public = null;
         if($article->{Articles_Model::COLUMN_CONCEPT} == true){
            $showClass = 'main-content-concept';
            $public = $this->tr('Koncept').'&nbsp;';
         }
         $editTime = new DateTime($article->{Articles_Model::COLUMN_ADD_TIME});
         // find image
         $image = null;
         if($article->{Articles_Model::COLUMN_TITLE_IMAGE} != null){
            $image = vve_tpl_image_tag(
               vve_tpl_art_title_image($article->{Articles_Model::COLUMN_TITLE_IMAGE}),$article->{Articles_Model::COLUMN_NAME}, 100, 100);
         } else {
            $doc = new DOMDocument();
            @$doc->loadHTML($article->{Articles_Model::COLUMN_TEXT});
            $xml = simplexml_import_dom($doc); // just to make xpath more simple
            $images = $xml->xpath('//img');
            if(!empty ($images) && isset ($images[0])){
               $image = vve_tpl_image_tag($images[0]['src'], $images[0]['alt'] != null ? $images[0]['alt'] : "article title image", 100, 100);
            }
         }
         ?>
      <div class="item <?=$showClass?>">
         <h2><a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model::COLUMN_URLKEY}))?>"
               title="<?=htmlspecialchars($article->{Articles_Model::COLUMN_NAME})?>"><?=htmlspecialchars($article->{Articles_Model::COLUMN_NAME})?></a>
         </h2>
         <p class="date"><?=strftime("%x %X", $editTime->format("U"))?> - <?=$article->{Model_Users::COLUMN_USERNAME}?></p>
         
         <?echo vve_tpl_truncate(strip_tags((string)$article->{Articles_Model::COLUMN_ANNOTATION} != null ? 
            $article->{Articles_Model::COLUMN_ANNOTATION} : $article->{Articles_Model::COLUMN_TEXT}), 200);?>
         <hr class="reseter" />
         <div class="showed"><?=$this->tr('Zobrazeno')?>:&nbsp;<?=$article->{Articles_Model::COLUMN_SHOWED}?>&times;</div>
         <hr class="reseter" />
      </div>
      <?}?>
   <?
      echo $this->scrollComp;
   } else {
      echo ($this->tr('Není vložen žádný článek'));
   }
   ?>
</div>