<?php 
$this->addFile("css://articles:style.css?original");
// do titulku
$h = sprintf( $this->tr('přesun položky "%s"'), $this->article->{Articles_Model::COLUMN_NAME});

$this->addPageTitle($this->article->{Articles_Model::COLUMN_NAME});
$this->addPageTitle($this->tr('přesun položky'));
?>
<h1><?php echo $h;?></h1>
<div class="main-content-form-edit" id="article-move-form">
   <p class="admin-info-text">
   <?php echo $this->tr('Položka se přesune do níže vybrané kategorie včetně všech přiřazených obrázků.') ?>
   </p>
   <?php 
   echo($this->form);
   ?>
</div>
<script type="text/javascript">
   /* <![CDATA[ */
   /* ]]> */
</script>
