<?
$icon = null;
if($this->panel->{Model_Panel::COLUMN_ICON} != null){
   $icon = '<img src="'.Panel::getIconDir().$this->panel->{Model_Panel::COLUMN_ICON}.'" alt="'.$this->panel->{Model_Panel::COLUMN_ICON}.'" />';
}
$backImg = null;
if($this->panel->{Model_Panel::COLUMN_BACK_IMAGE} != null){
   $backImg = 'background-image: url(\''.Panel::getBackImgDir().$this->panel->{Model_Panel::COLUMN_BACK_IMAGE}.'\');';
}

if($this->rssLink != null){?>
<a style="float: right" href="<?=$this->rssLink?>" title="rss"><img src="<?=vve_get_tpl_file('icons/rss-icon.png', VVE_TPL_FILE_IMAGE)?>" alt="rss" /></a>
<?}?>
<p class="panelLabel"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->category()->getLabel()?></a></p>
<div style="<?=$backImg?>">
   <?foreach ($this->newArticles as $article) {?>
   <a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
      title="<?=htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>"><?=vve_tpl_truncate($article->{Articles_Model_Detail::COLUMN_NAME},25)?></a><br />
   <?}?>
</div>
<p class="panelLinkMore">
   <a href="<?=$this->link()?>"
      title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->_('Více')?></a>
</p>