<?
$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
if($this->rssLink != null){?>
<a style="float: right" href="<?=$this->rssLink?>" title="rss"><img src="<?=vve_get_tpl_file('icons/rss-icon.png', VVE_TPL_FILE_IMAGE)?>" alt="rss" /></a>
<?}?>
<div class="name"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->panelObj()->getName())?>"><?=$this->panelObj()->getName()?></a></div>
   <?foreach ($this->articles as $article) {?>
   <div class="content article">
   <div class="name"><a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model::COLUMN_URLKEY}))?>"
                                            title="<?=htmlspecialchars($article->{Articles_Model::COLUMN_NAME})?>"
                                            ><?=vve_tpl_truncate($article->{Articles_Model::COLUMN_NAME},25)?></a></div>
   <?=  vve_tpl_xhtml_cut(strip_tags($article->{Articles_Model::COLUMN_TEXT},VVE_SHORT_TEXT_TAGS),150)?>
   <div class="link-more"><a href="<?=$this->link()->route('detail', array('urlkey'=> $article->{Articles_Model::COLUMN_URLKEY}));?>"
      title="<?=htmlspecialchars($article->{Articles_Model::COLUMN_NAME})?>"><?=$this->tr('Více')?></a>
   </div>
   </div>
   <?}?>
<p class="link-more">
   <a href="<?=$this->link()?>"
      title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->tr('Více')?></a>
</p>