<form method="post" action="<?=$this->l();?>" onsubmit="return checkValues();" name="orderForm">
   <fieldset>
      <legend><?=$this->_("Ostatní údaje")?></legend>
      <div id="tabs">
         <ul class = "tabsMenu">
            <li><a href="#services"><?=$this->_('Služby');?></a></li>
            <li><a href="#pobocky"><?=$this->_('Pobočka');?></a></li>
            <li><a href="#contact"><?=$this->_('Osobní údaje');?></a></li>
         </ul>
         <div id="services" class="tabsContent productsList">
            <?foreach ($this->services as $service) {
               if($this->buyDetails[(string)$service->inputname]) {?>
            <input type="checkbox" checked name="orderform_<?=$service->inputname?>" /><?=$service->name?><br/>
               <?} else {?>
            <input type="checkbox" name="orderform_<?=$service->inputname?>" /><?=$service->name?><br/>
               <?}}?>
         </div>
         <div id="pobocky" class="tabsContent productsList">
            <?$first = true;
               foreach ($this->mesta as $mesto) {
               if(($this->buyDetails['office'] == false AND $first) OR $mesto['name'] == $this->buyDetails['office']) {?>
            <input type="radio" name="orderform_office" value="<?=$mesto["name"]?>" checked />
               <?} else {?>
            <input type="radio" name="orderform_office" value="<?=$mesto["name"]?>" />
               <?$first = false;}?>
               <?=$mesto["name"]?><br/>
            <?}?>
         </div>

         <div id="contact" class="tabsContent productsList">
            <h2><?=$this->_('Osobní údaje');?></h2>
            <table>
               <tr>
                  <td width="150px"><label for="orderform_name"><?=$this->_('Jméno');?>:*</label></td>
                  <td>
                     <input name="orderform_name" type="text" value="<?=$this->buyDetails['name']?>" id="orderform_name" />
                  </td>
               </tr>
               <tr>
                  <td width="150px"><label for="orderform_surname"><?=$this->_('Příjmení');?>:*</label></td>
                  <td>
                     <input name="orderform_surname" type="text" value="<?=$this->buyDetails['surname']?>" id="orderform_surname" />
                  </td>
               </tr>
               <tr>
                  <td width="150px"><label for="orderform_company"><?=$this->_('Firma (nepovinné)');?>:</label></td>
                  <td>
                     <input name="orderform_company" type="text" value="<?=$this->buyDetails['company']?>" id="orderform_company" />
                  </td>
               </tr>
               <tr>
                  <td width="150px"><label for="orderform_phone"><?=$this->_('Telefon');?>:*</label></td>
                  <td>
                     <input name="orderform_phone" type="text" value="<?=$this->buyDetails['phone']?>" id="orderform_phone" />
                  </td>
               </tr>
               <tr>
                  <td width="150px"><label for="orderform_email"><?=$this->_m('E-mail');?>:*</label></td>
                  <td>
                     <input name="orderform_email" type="text" value="<?=$this->buyDetails['email']?>" id="orderform_email"/>
                  </td>
               </tr>
            </table>
         </div>
      </div>
      <div class="productSizesBottomLine"></div>
   </fieldset>
   <br />
   <input name="orderform_send" type="submit" value="<?=$this->_("Pokračovat")?>&nbsp;&raquo;" />
</form>
<script type="text/javascript">
   <!--
//   $(document).ready(function(){
      var tabs = $("#tabs").tabs();
//   });
   // kontrola zadání hodnot
   function checkValues(){
      var allOk = true;
      var msg = null;

      if(numItems == 0){
         alert("<?=$this->_("Košík je prázdný")?>");
         return false;
      }

      $("form[name=orderForm]").find("input").removeClass("missing");
      if($("input[name=orderform_name]").val() == ""){
         tabs.tabs('select', 2);
         $("input[name=orderform_name]").addClass("missing");
         document.forms.orderForm.orderform_name.focus();
         alert("<?=$this->_("Nebylo vyplněno jméno")?>");
         return false;
      }
      if($("input[name=orderform_surname]").val() == ""){
         tabs.tabs('select', 2);
         $("input[name=orderform_surname]").addClass("missing");
         document.forms.orderForm.orderform_surname.focus();
         alert("<?=$this->_("Nebylo vyplněno přijmení")?>");
         return false;
      }
      if($("input[name=orderform_phone]").val() == "" || 
         $("input[name=orderform_phone]").val().search(/^(\+420)? ?[0-9]{3} ?[0-9]{3} ?[0-9]{3}$/)){
         tabs.tabs('select', 2);
         $("input[name=orderform_phone]").addClass("missing");
         document.forms.orderForm.orderform_phone.focus();
         alert("<?=$this->_("Nebylo vyplněn telefon")?>");
         return false;
      }
      if($("input[name=orderform_email]").val() == "" ||
         $("input[name=orderform_email]").val().search(/[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}/)){
         tabs.tabs('select', 2);
         $("input[name=orderform_email]").addClass("missing");
         document.forms.orderForm.orderform_email.focus();
         alert("<?=$this->_("Nebylo vyplněn správný e-mail")?>");
         return false;
      }

//      return false;
//      if(allOk){
//         return true;
//      } else {
//         alert("<?=$this->_("Nebyly vyplněny všechny údaje")?>");
//         return false;
//      }
   }

   
   -->
</script>

