<?php 
$items = array();
$items[$this->tr('Základní')] = (string) $this->link()->route();
$items[$this->tr('Měna a daně')] = (string) $this->link()->route('currencyAndTaxes');
$items[$this->tr('Platby a dopravy')] = (string) $this->link()->route('shipAndPay');
$items[$this->tr('Objednávky')] = (string) $this->link()->route('orders');
$items[$this->tr('Stavy objednávek')] = (string) $this->link()->route('orderStates');

$this->includeFile('tpl://engine:modules/navigation.phtml', array('items' => $items));