<? 
$this->addFile('css://style.css');
$jsJqGrid = new Component_JqGrid_JsPlugin();
$this->addJsPlugin($jsJqGrid);
?>
<h1><?= $this->tr('Měny a daně') ?></h1>
<?
$this->includeFile('tpl://nav.phtml');
?>
<div class="main-content-form-edit">
   <? echo $this->form; ?>
   <h2><?=$this->tr('Platby')?></h2>
   <table id="table-payments"></table>
   <div id="table-payments-pager"></div>
   <hr class="reseter" />
   <h2><?=$this->tr('Dopravy')?></h2>
   <table id="table-shippings"></table>
   <div id="table-shippings-pager"></div>
   <hr class="reseter" />
</div>

<script type="text/javascript" charset="utf-8">
   /* <![CDATA[ */
   var selectedGroupId = 0;
      $(document).ready(function() {
         var paymentsGrid = $("#table-payments").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url: '<?=$this->link()->route('paymentsList');?>',
            datatype: "json",
            colNames:['ID','<?=$this->tr('Název')?>', '<?=$this->tr('Cena')?>', '<?=$this->tr('Doplňující text pro uživatele')?>'],
            colModel:[
               {name:'<?=Shop_Model_Payments::COLUMN_ID?>',index:'<?=Shop_Model_Payments::COLUMN_ID?>', 
                  width:33, fixed : true, editable:false},
               
               {name:'<?=Shop_Model_Payments::COLUMN_NAME?>',index:'<?=Shop_Model_Payments::COLUMN_NAME?>',
                  formatter: langFmatter, unformat: langUnFmatter,
                  width:160, fixed : true, editable:true, edittype:"textarea", 
                  editoptions:{rows:"5",cols:"18",
                     defaultValue : "<?foreach (Locales::getAppLangs() as $l){echo "[$l][/$l]\\n";}?>"
                  },
                  formoptions:{ rowpos:2, label: "<?=$this->tr('Název')?>",elmprefix:"(*)"}},
               
               {name:'<?=Shop_Model_Payments::COLUMN_PRICE_ADD?>',index:'<?=Shop_Model_Payments::COLUMN_PRICE_ADD?>', 
                  width:50, fixed : true, editable: true,editoptions:{size:20},
                  formoptions:{ rowpos:3, label: "<?=$this->tr('Cena')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               
               {name:'<?=Shop_Model_Payments::COLUMN_TEXT?>',index:'<?=Shop_Model_Payments::COLUMN_TEXT?>', 
                  formatter: langFmatter, unformat: langUnFmatter,
                  editable:true,edittype:"textarea", editoptions:{rows:"12",cols:"18",
                     defaultValue : "<?foreach (Locales::getAppLangs() as $l){echo "[$l][/$l]\\n";}?>"
                  },
                  formoptions:{ rowpos:4, label: "<?=$this->tr('Text pro uživatele')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}}
            ],
            rowNum:5,
            rowList:[5,10,20,50],
            pager: '#table-payments-pager',
            sortname: '<?=Shop_Model_Tax::COLUMN_NAME?>',
            caption:"Seznam plateb",
            jsonReader: {
               repeatitems : false, root:"rows"
            },
            height: '100%',
            autowidth : true,
            editurl:"<?=$this->link()->route('editPayment')?>"
         });
         paymentsGrid.jqGrid('navGrid','#table-payments-pager',
            {edit:true,add:true,del:true,search:false},
            // edit options
            {reloadAfterSubmit:true, jqModal:true, closeOnEscape:true,viewPagerButtons:false, 
               bottominfo:"<?=$this->tr('Položky označené (*) jsou povinné').'<br />'.$this->tr('Jazykové verze se zadávají mezi značky [cs][/cs] (Anglicky [en][/en]).')?>",closeAfterEdit:true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            // add options
            {reloadAfterSubmit:true,jqModal:true, closeOnEscape:true, 
               bottominfo:"<?=$this->tr('Položky označené (*) jsou povinné')?>", closeAfterAdd: true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },  
            // del options
            {reloadAfterSubmit:true, jqModal:true, closeOnEscape:true, width: 300,
               afterSubmit : function(respond, postdata){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            }
         );
      
      var shippingsGrid = $("#table-shippings").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url: '<?=$this->link()->route('shippingsList');?>',
            datatype: "json",
            colNames:['ID', '<?=$this->tr('Název')?>', '<?=$this->tr('Hodnota v %')?>', 
               '<?=$this->tr('Doplňující text pro uživatele')?>', '<?=$this->tr('ID zakázaných plateb')?>'],
            colModel:[
               {name:'<?=Shop_Model_Shippings::COLUMN_ID?>',index:'<?=Shop_Model_Shippings::COLUMN_ID?>', 
                  width:33, fixed : true, editable:false},
               
               {name:'<?=Shop_Model_Shippings::COLUMN_NAME?>',index:'<?=Shop_Model_Shippings::COLUMN_NAME?>',
                  formatter: langFmatter, unformat: langUnFmatter,
                  width:160, fixed : true, editable:true, edittype:"textarea", 
                  editoptions:{rows:"5",cols:"18",
                     defaultValue : "<?foreach (Locales::getAppLangs() as $l){echo "[$l][/$l]\\n";}?>"
                  },
                  formoptions:{ rowpos:2, label: "<?=$this->tr('Název')?>",elmprefix:"(*)"}},
               
               {name:'<?=Shop_Model_Shippings::COLUMN_VALUE?>',index:'<?=Shop_Model_Shippings::COLUMN_VALUE?>', 
                  width:50, fixed : true, editable: true,editoptions:{size:20},
                  formoptions:{ rowpos:3, label: "<?=$this->tr('Cena')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               
               {name:'<?=Shop_Model_Shippings::COLUMN_TEXT?>',index:'<?=Shop_Model_Shippings::COLUMN_TEXT?>',
                  formatter: langFmatter, unformat: langUnFmatter,
                  editable:true, edittype:"textarea", 
                  editoptions:{rows:"12",cols:"18",
                     defaultValue : "<?foreach (Locales::getAppLangs() as $l){echo "[$l][/$l]\\n";}?>"
                  },
                  formoptions:{ rowpos:4, label: "<?=$this->tr('Text pro uživatele')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               
               {name:'<?=Shop_Model_Shippings::COLUMN_DISALLOWED_PAYMENTS?>',index:'<?=Shop_Model_Shippings::COLUMN_DISALLOWED_PAYMENTS?>', 
                  width:130, fixed : true, editable: true,editoptions:{size:20},
                  formoptions:{ rowpos:5, label: "<?=$this->tr('ID zakázaných plateb <br />oddělených středníky')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}}
            ],
            rowNum:5,
            rowList:[5,10,20,50],
            pager: '#table-shippings-pager',
            sortname: '<?=Shop_Model_Shippings::COLUMN_NAME?>',
            caption:"Seznam doprav",
            jsonReader: {
               repeatitems : false, root:"rows"
            },
            height: '100%',
            autowidth : true,
            editurl:"<?=$this->link()->route('editShipping')?>"
         });
         shippingsGrid.jqGrid('navGrid','#table-shippings-pager',
            {edit:true,add:true,del:true,search:false},
            // edit options
            {reloadAfterSubmit:true, jqModal:true, closeOnEscape:true,viewPagerButtons:false, 
               bottominfo:"<?=$this->tr('Položky označené (*) jsou povinné')?>",closeAfterEdit:true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            // add options
            {reloadAfterSubmit:true,jqModal:true, closeOnEscape:true, 
               bottominfo:"<?=$this->tr('Položky označené (*) jsou povinné')?>", closeAfterAdd: true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },  
            // del options
            {reloadAfterSubmit:true, jqModal:true, closeOnEscape:true, width: 300,
               afterSubmit : function(respond, postdata){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            }
         );
         
         function langFmatter (cellvalue, options, rowObject)
         {
            return cellvalue.replace(/(\[\/?[a-z]{2}\])/gi, "<span class=\"lang-cell\">$1</span>");
//            return cellvalue.replace(/(\[\/?[a-z]{2}\])/gi, "");
         }
         function langUnFmatter (cellvalue, options)
         {
            return cellvalue;
         }
      });
   /* ]]> */
</script>
