<?php
$this->addJsPlugin(new JsPlugin_JQuery());
?>
<h1><?php echo $this->tr('Stavy objednávek') ?></h1>
<?php
$this->includeFile('tpl://nav.phtml');
?>
<div class="content-admin">
   <div class="alert alert-info">
      <?php 
      $linkTemplates = Url_Link::getCategoryAdminLink(32792);
      printf($this->tr('Šablony emailů se přidávají v administračním menu v položce Obsah a šablony > <a class="link-external" href="%s">šablony</a>'), $linkTemplates) ?>
   </div>
   <?php
   $this->moduleButtons = array(
       array(
           'link' => $this->link()->route('addOrderState'),
           'title' => $this->tr('Přidat nový stav'),
           'icon' => Template_Toolbox2::ICON_ADD,
           'name' => $this->tr('Přidat nový stav'),
       ),
   );
   $this->includeTpl('modules/buttons.phtml', true);
   ?>
   <table class="panels-list cubecms-widget cubecms-table">
      <thead class="cubecms-header">
         <tr class="">
            <th scope="col" class="orderstate-tb-category"><?php echo $this->tr('Název') ?></th>
            <th scope="col" class="orderstate-tb-tpl"><?php echo $this->tr('Šablona mailu') ?></th>
            <th scope="col" class="orderstate-tb-color"><?php echo $this->tr('Barva') ?></th>
            <th scope="col" class="orderstate-tb-complete"><?php echo $this->tr('Dokončena') ?></th>
            <th scope="col" class="orderstate-tb-actions"><?php echo $this->tr('Akce') ?></th>
         </tr>
      </thead>
      <tbody>
         <?php
         if (!empty($this->orderStates)) {
            foreach ($this->orderStates as $key => $state) {
               ?>
               <tr class="cubecms-row ">
                  <td>
                     <?php
                     ps($state->{Shop_Model_OrdersStates::COLUMN_NAME});
                     ?>
                  </td>
                  <td>
                     <?php
                     if($state->{Shop_Model_OrdersStates::COLUMN_ID_TEMPLATE} != 0){
                        ps($state->{Templates_Model::COLUMN_NAME}. ' (ID: '.$state->{Shop_Model_OrdersStates::COLUMN_ID_TEMPLATE}.' )');
                     } else {
                        echo '<em>'.$this->tr('není nastavena').'</em>';
                     }
                     ?>
                  </td>
                  <td style="<?php echo $state->{Shop_Model_OrdersStates::COLUMN_COLOR} ? 'background-color:'.$state->{Shop_Model_OrdersStates::COLUMN_COLOR} : ''?>">
                     <?php
                     if($state->{Shop_Model_OrdersStates::COLUMN_COLOR}){
                        echo $state->{Shop_Model_OrdersStates::COLUMN_COLOR};
                     }
                     ?>
                  </td>
                  <td>
                     <?php
                     ps ($state->{Shop_Model_OrdersStates::COLUMN_COMPLETE} ? $this->tr('Ano') : $this->tr('Ne'));
                     ?>
                  </td>
                  <td class="text-right">
                     <?php
                     if($state->getPK() != CUBE_CMS_SHOP_ORDER_DEFAULT_STATUS){
                        echo $state->toolbox;
                     } else {
                        echo '<em>'.$this->tr('výhozí').'</em>';
                     }
                     ?>
                  </td>
               </tr>
               <?php
            }
         } else {
            ?>
            <tr class="cubecms-row">
               <td colspan="4"><?php echo $this->tr('Není uložen žádný stav'); ?></td>
            </tr>
         <?php } ?>
      </tbody>
   </table>
   <h2><?php ps($this->tr('Přehled proměnných pro šablony e-mailů')) ?></h2>
   <ul class="styled">
      <li><em>{WEBSITE_NAME}</em> - <?php ps($this->tr('název obchodu')) ?></li>
      <li><em>{STORE_ADDRESS}</em> - <?php ps($this->tr('adresa obchodu')) ?></li>
      <li><em>{CURRENT_DATE}</em> - <?php ps($this->tr('aktuální datum')) ?></li>
      <li><em>{ORDER_NUMBER}</em> - <?php ps($this->tr('číslo objednávky')) ?></li>
      <li><em>{ORDER_NOTE}</em> - <?php ps($this->tr('poznámka k objednávce')) ?></li>
      <li><em>{ORDER_TOTAL}</em> - <?php ps($this->tr('celková cena objednávky')) ?></li>
      <li><em>{ORDER_DATE}</em> - <?php ps($this->tr('datum objednávky')) ?></li>
      <li><em>{ADDRESS_DELIVERY}</em> - <?php ps($this->tr('doručovací adresa')) ?></li>
      <li><em>{ADDRESS_BILLING}</em> - <?php ps($this->tr('fakturační adresa')) ?></li>
      <li><em>{PAYMENT_NAME}</em> - <?php ps($this->tr('název platební metody')) ?></li>
      <li><em>{PAYMENT_PRICE}</em> - <?php ps($this->tr('cena platební metody')) ?></li>
      <li><em>{SHIPPING_NAME}</em> - <?php ps($this->tr('název doručovací metody')) ?></li>
      <li><em>{SHIPPING_PRICE}</em> - <?php ps($this->tr('cena doručovací metody')) ?></li>
      <li><em>{PRODUCTS}</em> - <?php ps($this->tr('přehled produktů v tabulce se souhrnem')) ?></li>
      <li><em>{STATE}</em> - <?php ps($this->tr('stav objednávky')) ?></li>
      <li><em>{STATE_NOTE}</em> - <?php ps($this->tr('poznámka ke stavu objednávky')) ?></li>
   </ul>
   <div class="alert alert-warning">
      <?php ps($this->tr('Ne všechny proměnné jsou vždy k dispozici. Například infomace o objednávce jsou k dispozici pouze u e-mailů týkajících se objednávky.')) ?>
   </div>
</div>

<script type="text/javascript" charset="utf-8">
   /* <![CDATA[ */

   /* ]]> */
</script>
