<?php 
$this->addPageTitle($this->tr('Úprava vzhledu'));
$this->addFile('css://style.less');
$jQuery = new JsPlugin_JQuery();
$this->addJsPlugin($jQuery);

$grpsArr = array();
?>
<h1><?php echo $this->tr('Úprava zdrojových kódu vzhledu');?></h1>
<div class="content-admin">
   vaberte soubor. Pokud je k dispozici soubor s příponou "less" použijte ten. Css soubor je generován automaticky z LESS
   
   <div id="faceedit-files" class="">
      <h2>Soubory</h2>
      <div class="file-selector clearfix">
         <form action="<?php echo $this->link()->route('editFile')?>">
            <div class="label">
               <lable>Šablony</lable>:
            </div>
            <div class="control">
               <select name="file" id="">
                  <?php foreach ($this->filesPHTML as $file) {?>
                  <option value="<?php echo $file?>"><?php ps($file)?></option>
                  <?php }?>
               </select>
               <button type="submit">Upravit</button>
            </div>
         </form>
      </div>
      <div class="file-selector clearfix">
         <form action="<?php echo $this->link()->route('editFile')?>">
            <div class="label">
               <lable>Soubory stylů</lable>:
            </div>
            <div class="control">
               <select name="file" id="">
                  <?php foreach ($this->filesCSS as $file) {?>
                  <option value="<?php echo $file?>"><?php ps($file)?></option>
                  <?php }?>
               </select>
               <button type="submit">Upravit</button>
            </div>
         </form>
      </div>
      <div class="file-selector clearfix">
         <form action="<?php echo $this->link()->route('editFile')?>">
            <div class="label">
               <lable>PHP Soubory</lable>:
            </div>
            <div class="control">
               <select name="file" id="">
                  <?php foreach ($this->filesPHP as $file) {?>
                  <option value="<?php echo $file?>"><?php ps($file)?></option>
                  <?php }?>
               </select>
               <button type="submit">Upravit</button>
            </div>
         </form>
      </div>
      </form>
   </div>
   
</div>
<script type="text/javascript" charset="utf-8">
   /* <![CDATA[ */
   /* ]]> */
</script>