<?php 
$jQuery = new JsPlugin_JQuery();
$jQuery->addUICore();
//$jQuery->addUIDialog();
$jQuery->addUISortable();
$this->addJsPlugin($jQuery);
$this->addFile('css://style.less');
$this->addFile('js://shop-variants.js');
$buttonCancelEdit = '<button name="cancel" class="button-cancel" onclick="clearForm(this); return false;" >'
   .$this->tr('Vyčistit').'</button> ';
?>
<h1><?php echo  $this->category()->getName() ?></h1>
<div class="main-content-admin-form">
   <div class="row">
      <div class="col-md-6">
         <div id="variants-groups" class="cubecms-widget cubecms-widget-sorting">
            <div class="cubecms-header"><?php echo $this->tr('Skupiny')?></div>
            <div class="cubecms-content">
               <ul id="variants-groups-list" class="cubecms-widget cubecms-list"></ul>
               <div id="groups-control" class="cubecms-footer">
                  <button onclick="ShopVariants.addGroup()" class="btn btn-success"><span class="icon icon-plus"></span> <?php ps($this->tr('Přidat'))?></button>
                  <button onclick="ShopVariants.loadGroups()" class="btn btn-primary"><span class="icon icon-refresh"></span> <?php ps($this->tr('Obnovit'))?></button>
               </div>
            </div>
            <?php
            $this->includeFile('tpl://engine:components/modal.phtml', array('content' => (string)$this->formEditGroup, 'id' => 'dialog-variant-group-edit',
                'header' => $this->tr('Přidání skupiny atributů'),
                'close' => true,
                'large' => true,
                'footer' => '<button class="btn btn-default close-modal">Zavřít</button>'));
            ?>
         </div>
      </div>
      <div class="col-md-6">
         <div id="variants-values" class="cubecms-widget cubecms-widget-sorting">
            <div class="cubecms-header"><?php ps($this->tr('Atributy'));?> <span id="group-name"></span></div>
            <div class="cubecms-content">
               <ul id="variants-values-list" class="cubecms-widget cubecms-list"></ul>
               <div id="values-control" class="cubecms-footer">
                  <button id="button-add-variant"  class="btn btn-success" onclick="ShopVariants.addVariant()"
                          ><span class="icon icon-plus"></span> <?php ps($this->tr('Přidat'))?></button>
               </div>
            </div>
            <?php
            $this->includeFile('tpl://engine:components/modal.phtml', array('content' => (string)$this->formEditVariant, 'id' => 'dialog-variant-edit',
                'header' => $this->tr('Přidání parametru'),
                'close' => true,
                'large' => true,
                'footer' => '<button class="btn btn-default close-modal">Zavřít</button>'));
            ?>
         </div>
      </div>
   </div>

   <script type="text/javascript" charset="utf-8">
      /* <![CDATA[ */
      function clearForm(button){
         var $this = $(button);
         $this.parents('form').find('input[type="text"],input[type="hidden"]').val("");
      }
      $(document).ready(function() {
          $('.button-delete-group,.button-delete-value').click(function(){
             return confirm('<?php echo $this->tr('Opravdu zmazat tuto skupinu/hodnotu?')?>');
          });

         ShopVariants.init({
            urlGroups : '<?php echo $this->link()->clear()->route('groupsList')?>',
            urlEditGroup : '<?php echo $this->link()->clear()->route('editGroup')?>',
            urlVariants : '<?php echo $this->link()->clear()->route('variantsList')?>',
            urlEditVariant : '<?php echo $this->link()->clear()->route('editVariant')?>',
            strings : {
               dlgEditGroupTitle : '<?php echo $this->tr('Úprava skupiny')?>',
               dlgAddGroupTitle : '<?php echo $this->tr('Přidání skupiny')?>',
               dlgEditAttrTitle : '<?php echo $this->tr('Úprava parametru')?>',
               dlgAddAttrTitle : '<?php echo $this->tr('Přidání parametru')?>',
               infoSetName : 'Musí být zadán název',
               confirmDeleteVariant : 'Smazat tento atribut?',
               confirmDeleteGroup : 'Smazat tuto skupinu?',
               emptyValues : 'Žádná hodnota není vytvořena',
               saved : 'uloženo'
            }
         }, {
            $dialogGroup : $('#dialog-variant-group-edit'),
            $dialogVariant : $('#dialog-variant-edit'),
            $listGroups : $('#variants-groups-list'),
            $listVariants : $('#variants-values-list'),
            $formEditGroup : $("#dialog-variant-group-edit form"),
            $formEditVariant : $("#dialog-variant-edit form"),
            $groupNameBox : $('#group-name'),
            $buttonAddVariant : $('#button-add-variant')
         });

      });
      /* ]]> */
   </script>
</div>