<div>
	<a href="{$VARS.LINK_TO_ADD_SECTION}" title="{$VARS.LINK_TO_ADD_SECTION_NAME}">{$VARS.LINK_TO_ADD_SECTION_NAME}</a>
	<a href="{$VARS.LINK_TO_ADD_BLOG}" title="{$VARS.LINK_TO_ADD_BLOG_NAME}">{$VARS.LINK_TO_ADD_BLOG_NAME}</a>
</div>