<?
$this->addPageHeadline($this->_('Adresář'));
$this->addPageTitle($this->_('Adresář'));

$jsJqGrid = new Component_JqGrid_JsPlugin();
$this->addJsPlugin($jsJqGrid);
?>
<?=$this->includeTpl('navigation.phtml');?>
<div>
   <table id="table-addressbook"></table>
   <div id="table-addressbook-toolbar">
   </div>
   <div id="table-addressbook-pager"></div>
   <hr class="reseter" />
   <br />
   <h2><?=$this->_('Import adres'); ?></h2>
<?
   echo $this->formImport->renderStart();
   echo $this->formImport->file->label();
   echo $this->formImport->file->controll();
   echo $this->formImport->separator->label();
   $this->formImport->separator->html()->setAttrib('size', 1);
   echo $this->formImport->separator->controll();
   echo $this->formImport->import->controll();
   echo $this->formImport->renderEnd();
?>
   <br />
   <h2>Export adres</h2>
   <script type="text/javascript" charset="utf-8">
      /* <![CDATA[ */
      $(document).ready(function() {
         // seznam emailů
         var addressGrid = $("#table-addressbook").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url:'<?=$this->link()->route('addressList');?>',
            datatype: "json",
            colNames:['E-mail', 'Jméno', 'Přijmení','Poznámka'],
            colModel:[
               {name:'mail',index:'<?=Mails_Model_Addressbook::COLUMN_MAIL?>',
                  width:200,editable:true,editoptions:{size:25},
                  formoptions:{ rowpos:1, label: "<?=$this->_('E-mail')?>", elmprefix:"(*)"},
                  editrules:{required:true}},
               {name:'name',index:'<?=Mails_Model_Addressbook::COLUMN_NAME?>',
                  width:120,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:2, label: "<?=$this->_('Jméno')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               {name:'surname',index:'surname', width:120,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:3, label: "<?=$this->_('Přijmení')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               {name:'note',index:'note', width:100,editable: true,edittype:"textarea", editoptions:{rows:"2",cols:"20"}},
            ],
            rowNum:<?=Mails_Controller::NUM_ROWS_IN_TABLE;?>,
            rowList:[<?=Mails_Controller::NUM_ROWS_IN_TABLE;?>,<?=Mails_Controller::NUM_ROWS_IN_TABLE*2;?>,<?=Mails_Controller::NUM_ROWS_IN_TABLE*4;?>,<?=Mails_Controller::NUM_ROWS_IN_TABLE*10;?>],
            pager: '#table-addressbook-pager',
            sortname: 'mail',
//            multiselect: true,
            caption:"e-maily",
            height: 350,
//            toolbar: [true,"top"],
            editurl:"<?=$this->link()->route('editMail')?>"
         });
         // úpravy
         jQuery("#table-addressbook").jqGrid('navGrid','#table-addressbook-pager',
            {view:false}, //options
            {height:200,reloadAfterSubmit:true, jqModal:true, closeOnEscape:true,viewPagerButtons:false, // edit options
               bottominfo:"<?=$this->_('Položky označené (*) jsou povinné')?>",
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            }, 
            {height:150,reloadAfterSubmit:true,jqModal:true, closeOnEscape:true, // add options
               bottominfo:"<?=$this->_('Položky označené (*) jsou povinné')?>", closeAfterAdd: true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },  // del options
            {reloadAfterSubmit:false,jqModal:true, closeOnEscape:true,
               afterSubmit : function(respond, postdata){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            {closeOnEscape:true}, // search options
            {height:120,jqModal:true,closeOnEscape:true} // view options
         ).navSeparatorAdd("#table-addressbook-pager")
            .navButtonAdd('#table-addressbook-pager',{
            caption:"",
            buttonicon:"ui-icon-mail-closed",
            onClickButton: function(){
               // serializace mailů do url adresy
               var composeLink = '<?=$this->link()->clear()?>?mail='+escape(addressGrid.getRowData(addressGrid.getGridParam('selrow')).mail);
               window.location.href = composeLink;
            },
            title: "<?=$this->_('Poslat e-mail označenému')?>",
            position:"last"
         });
      })
         ;
      /* ]]> */
      </script>
   </div>
<?$this->includeTpl("buttonback.phtml", true, array('text' => $this->_('Zpět na tvorbu e-mailu')));?>