<?
$this->addPageTitle($this->tr('Adresář'));
$this->addCssFile('style.css');
$jsJqGrid = new Component_JqGrid_JsPlugin();
$this->addJsPlugin($jsJqGrid);
$jQuery = new JsPlugin_JQuery();
$this->addJsPlugin($jQuery);
?>
<h1><?=$this->category()->getName().' - '.$this->tr('adresář')?></h1>
<?=$this->includeTpl('navigation.phtml');?>
<div class="main-content-detail">
   <table id="table-addressbook-groups"></table>
   <div id="table-addressbook-groups-toolbar"></div>
   <div id="table-addressbook-groups-pager"></div>
   <hr class="reseter" />
   <br />
   <table id="table-addressbook"></table>
   <div id="table-addressbook-toolbar"></div>
   <div id="table-addressbook-pager"></div>
   <hr class="reseter" />
   <br />
   <?$this->includeTpl("buttonback.phtml", true, array('text' => $this->tr('Zpět na tvorbu e-mailu')));?>
</div>
   <script type="text/javascript" charset="utf-8">
      /* <![CDATA[ */
      var selectedGroupId = 0;
      $(document).ready(function() {
         var groupsGrid = $("#table-addressbook-groups").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url:'<?=$this->link()->route('groupsList');?>',
            datatype: "json",
            colNames:['Název', 'Poznámka'],
            colModel:[
               {name:'name',index:'<?=  Mails_Model_Groups::COLUMN_NAME?>',
                  width:200,editable:true,editoptions:{size:25},
                  formoptions:{ rowpos:1, label: "<?=$this->tr('Název')?>", elmprefix:"(*)"},
                  editrules:{required:true}},
               {name:'note',index:'<?=  Mails_Model_Groups::COLUMN_NOTE?>', width:100,editable: true,edittype:"textarea", editoptions:{rows:"2",cols:"20"}},
            ],
            rowNum:<?=Mails_Controller::NUM_ROWS_IN_GRPTABLE;?>,
            rowList:[<?=Mails_Controller::NUM_ROWS_IN_GRPTABLE;?>,<?=Mails_Controller::NUM_ROWS_IN_GRPTABLE*2;?>,<?=Mails_Controller::NUM_ROWS_IN_GRPTABLE*4;?>,<?=Mails_Controller::NUM_ROWS_IN_GRPTABLE*10;?>],
            pager: '#table-addressbook-groups-pager',
            sortname: '<?=Mails_Model_Groups::COLUMN_NAME?>',
            caption:"Skupiny",
            height: 120,
            width : $('.main-content-detail').width(),
            editurl:"<?=$this->link()->route('editGroup')?>",
            loadComplete : function(){
               $("#table-addressbook-groups").setSelection($("#table-addressbook-groups").getDataIDs()[0],true);
            },
            onSelectRow: function(ids) {
               if(ids != null) {
                  jQuery("#table-addressbook").jqGrid('setGridParam',{url:"<?=$this->link()->clear()->route('addressList');?>?idgrp="+ids,page:1});
                  jQuery("#table-addressbook").jqGrid('setCaption',"E-maily skupiny: "
                     +jQuery("#table-addressbook-groups").jqGrid('getRowData',ids).name).trigger('reloadGrid');
               }
            }
         });
         // úpravy
         groupsGrid.jqGrid('navGrid','#table-addressbook-groups-pager',
            {view:false}, //options
            {height:200, width:350, reloadAfterSubmit:true, jqModal:true, closeOnEscape:true,viewPagerButtons:false, // edit options
               bottominfo:"<?=$this->tr('Položky označené (*) jsou povinné')?>",
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            {height:200, width:350, reloadAfterSubmit:true,jqModal:true, closeOnEscape:true, // add options
               bottominfo:"<?=$this->tr('Položky označené (*) jsou povinné')?>", closeAfterAdd: true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },  // del options
            {reloadAfterSubmit:true,jqModal:true, closeOnEscape:true,
               msg: "<?=$this->tr('Opravdu smazat skupinu? <br/>Smazání smaže také e-maily uložení v ní.')?>",
               afterSubmit : function(respond, postdata){
                  jQuery("#table-addressbook").jqGrid('clearGridData',true);
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            {closeOnEscape:true, sopt : ['eq','ne','cn','nc']}, // search options
            {height:120,jqModal:true,closeOnEscape:true} // view options
         );
         
         // seznam emailů
         var addressGrid = $("#table-addressbook").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url:'<?=$this->link()->route('addressList');?>?idgrp=<?=$this->idSelGrp?>',
            datatype: "json",
            colNames:['E-mail', 'Jméno', 'Přijmení','Poznámka'],
            colModel:[
               {name:'mail',index:'<?=Mails_Model_Addressbook::COLUMN_MAIL?>',
                  width:200,editable:true,editoptions:{size:25},
                  formoptions:{ rowpos:1, label: "<?=$this->tr('E-mail')?>", elmprefix:"(*)"},
                  editrules:{required:true}},
               {name:'name',index:'<?=Mails_Model_Addressbook::COLUMN_NAME?>',
                  width:120,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:2, label: "<?=$this->tr('Jméno')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               {name:'surname',index:'surname', width:120,editable:true,editoptions:{size:20},
                  formoptions:{ rowpos:3, label: "<?=$this->tr('Přijmení')?>",elmprefix:"&nbsp;&nbsp;&nbsp;&nbsp;"}},
               {name:'note',index:'note', width:100,editable: true,edittype:"textarea", editoptions:{rows:"2",cols:"20"}},
            ],
            rowNum:<?=Mails_Controller::NUM_ROWS_IN_TABLE;?>,
            rowList:[<?=Mails_Controller::NUM_ROWS_IN_TABLE;?>,<?=Mails_Controller::NUM_ROWS_IN_TABLE*2;?>,<?=Mails_Controller::NUM_ROWS_IN_TABLE*4;?>,<?=Mails_Controller::NUM_ROWS_IN_TABLE*10;?>],
            pager: '#table-addressbook-pager',
            sortname: '<?=Mails_Model_Addressbook::COLUMN_MAIL?>',
            caption:"E-maily skupiny",
            height: 350,
            width : $('.main-content-detail').width(),
            editurl:"<?=$this->link()->route('editMail')?>"
         });
         // úpravy
         jQuery("#table-addressbook").jqGrid('navGrid','#table-addressbook-pager',
            {view:false}, //options
            {height:250, width:350,reloadAfterSubmit:true, jqModal:true, closeOnEscape:true,viewPagerButtons:false, // edit options
               bottominfo:"<?=$this->tr('Položky označené (*) jsou povinné')?>",closeAfterEdit:true,
               beforeSubmit : function(postdata, formid){
                  postdata.idg = $("#table-addressbook-groups").getGridParam('selrow');
                  return [true]
               },
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            {height:250, width:350,reloadAfterSubmit:true,jqModal:true, closeOnEscape:true, // add options
               bottominfo:"<?=$this->tr('Položky označené (*) jsou povinné')?>", closeAfterAdd: true,
               beforeSubmit : function(postdata, formid){
                  if($("#table-addressbook-groups").getGridParam('selrow') == null){
                     return[false,'<?=$this->tr('Nelze přidávat pokud není vybrána skupina')?>'];
                  }
                  postdata.idg = $("#table-addressbook-groups").getGridParam('selrow');
                  return [true]
               },
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },  // del options
            {reloadAfterSubmit:false,jqModal:true, closeOnEscape:true,
               afterSubmit : function(respond, postdata){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            {closeAfterSearch: true,closeOnEscape:true,sopt : ['eq','ne','cn','nc']}, // search options
            {height:120,jqModal:true,closeOnEscape:true} // view options
         ).navSeparatorAdd("#table-addressbook-pager")
            .navButtonAdd('#table-addressbook-pager',{
            caption:"",
            buttonicon:"ui-icon-mail-closed",
            onClickButton: function(){
               // serializace mailů do url adresy
               var composeLink = '<?=$this->link()->clear()?>?mail='+escape(addressGrid.getRowData(addressGrid.getGridParam('selrow')).mail);
               window.location.href = composeLink;
            },
            title: "<?=$this->tr('Poslat e-mail označenému')?>",
            position:"last"
         });
      });
      /* ]]> */
      </script>
