<?
$this->addPageTitle($this->_('odeslání e-mailu'));
$this->addPageHeadline($this->_('odeslání e-mailu'));
?>
<div id="sendMailForm">
   <?
   $tinymce = new JsPlugin_TinyMce();
   $tinymce->setCfgParam(JsPlugin_TinyMce::PARAM_THEME, JsPlugin_TinyMce::TINY_THEME_ADVANCED);
   $tinymce->setCfgParam('editor_selector', 'mceEditorSimple');
   $tinymce->setCfgParam(JsPlugin_TinyMce::PARAM_TPL_TYPE, Templates_Model::TEMPLATE_TYPE_MAIL);
   $this->addJsPlugin($tinymce);
   ?>
<?echo $this->form->renderStart();?>
   <table>
      <tr>
         <td>
         <?echo $this->form->recipients->label()?><br />
         <? $this->form->recipients->html()->setAttrib('cols', 60);
         echo $this->form->recipients->controll();?>
         <?echo $this->form->recipients->sublabel()?>
         <br />
         </td>
      </tr>
      <tr>
         <td>
         <?echo $this->form->subject->label()?><br />
         <?$this->form->subject->html()->setAttrib('size', 60);
         echo $this->form->subject->controll();?><br />
         <br />
         </td>
      </tr>
      <tr>
         <td>
         <?echo $this->form->text->label()?><br />
         <?
         $this->form->text->html()->setAttrib('cols', 60)->setAttrib('rows', 40)->addClass('mceEditorSimple');
         echo $this->form->text->controll();?>
         <br />
         <strong><?=$this->_('Edotir')?>:&nbsp;</strong>
         <a href="<?=$this->link()?>#disableEditor" 
            onclick="toggleEditor('sendmail_text');"
            title="<?=$this->_('vypnout/zapnout editor')?>"><?=$this->_('OFF/ON')?></a>
         <br />
         <br />
         </td>
      </tr>
      <tr>
         <td>
         <?
         echo $this->form->file->label();
         echo $this->form->file->controll();
         ?>
         <br />
         </td>
      </tr>
      <tr>
         <td align="right">
            <?echo $this->form->send->controll()?>
         </td>
      </tr>
   </table>
<?echo $this->form->renderEnd();?>
</div>
<script type="text/javascript">
   function toggleEditor(id) {
      if (!tinyMCE.get(id)) tinyMCE.execCommand('mceAddControl', false, id);
      else tinyMCE.execCommand('mceRemoveControl', false, id);
      return false;
}
</script>
<br />
<?$this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->link()->route('list')));?>