<?php 
$this->addPageTitle($this->tr('seznam odeslaných emailů'));
$jQuery = new JsPlugin_JQuery();
$jQuery->addUIAccordion();
$this->addJsPlugin($jQuery);
$this->addCssFile('style.less');
?>
<h1><?php echo $this->category()->getName().' - '.$this->tr('odeslané e-maily')?></h1>
<?php echo $this->includeTpl('navigation.phtml');?>
<div id="module-mail-list" class="module-mails-list-mails">
   <?php foreach ($this->mails as $mail) {?>
   <h2><a href="#" title="<?php echo $this->tr('Dateil mailu')?>"
          ><?php echo $mail->{Mails_Model_SendMails::COLUMN_SUBJECT}.'&nbsp;-&nbsp;'
          .vve_date('%x %X', new DateTime($mail->{Mails_Model_SendMails::COLUMN_DATE}))?></a></h2>
   <div class="mail-detail">
      <div class="mail-tools"><a href="<?php echo $this->link()->route('composeMail')->param('sendmail',
                 $mail->{Mails_Model_SendMails::COLUMN_ID})?>"
            ><img src="<?php echo vve_get_tpl_file('icons/email_resend.png', VVE_TPL_FILE_IMAGE)?>"
                alt="icon send mail" />&nbsp;<?php echo $this->tr('Poslat znovu')?></a>
      </div>
      <h3><?php echo $this->tr('Příjemci')?></h3>
      <div class="mail-recipients">
         <?php 
         $recs = explode(Mails_Model_SendMails::RECORD_SEPARATOR, $mail->{Mails_Model_SendMails::COLUMN_RECIPIENTS});
         foreach ($recs as $rec) {?>
            <a href="<?php echo $this->link()->clear()->param('mail', $rec)?>"
               title="<?php echo $this->tr('Odeslat e-mail na adresu').' '.htmlspecialchars($rec);?>"><?php echo htmlspecialchars($rec)?></a>,
         <?php }
         ?>
      </div><br />
      <h3><?php echo $this->tr('Obsah')?></h3>
      <div class="mail-content">
         <?php echo $mail->{Mails_Model_SendMails::COLUMN_CONTENT}?>
      </div>
      <?php if($mail->{Mails_Model_SendMails::COLUMN_ATTACHMENTS} != null){?>
      <br />
      <h3><?php echo $this->tr('Přílohy')?></h3>
      <div class="mail-attachments">
         <?php echo $mail->{Mails_Model_SendMails::COLUMN_ATTACHMENTS}?>
      </div>
      <?php }?>
      <br />
      <div class="mail-tools"><a href="<?php echo $this->link()->route('composeMail')->param('sendmail',
                 $mail->{Mails_Model_SendMails::COLUMN_ID})?>"
            ><img src="<?php echo vve_get_tpl_file('icons/email_resend.png', VVE_TPL_FILE_IMAGE)?>"
                alt="icon send mail" />&nbsp;<?php echo $this->tr('Poslat znovu')?></a>
      </div>
   </div>
   <?php 
}
?>
</div>
<script type="text/javascript">
   /* <![CDATA[ */
   $(function() {
      $(".module-mails-list-mails").accordion({
         active : false,
         autoHeight: false
      });
   });
   /* ]]> */
</script>
<?php 
echo $this->scrollComp;
?>