<?
$this->addPageHeadline($this->_('Správa e-mailových adres'));
$this->addPageTitle($this->_('Správa e-mailových adres'));
$this->addCssFile('style.css');

$jsDataTables = new JsPlugin_DataTables();
$jsDataTables->addHiddenNodesPlugin();
$this->addJsPlugin($jsDataTables);
?>
<div>
   <h2><?=$this->_('Addresář');
?></h2>
   <p class="module-mails-tools">
      <a href="<?=$this->link()->route('addMail')
?>" title="<?=$this->_('Přidt nový e-mail do adresáře')
?>"
         ><img src="<?=Template::getFileDir('icons/email_add.png', Template::IMAGES_DIR, false, true)
?>"
            alt="add mail icon"/>&nbsp;<?=$this->_('Nový e-mail')
?></a>
   </p>
   <br />
   <h2><?=$this->_('Uložené e-mailové adresy'); ?></h2>
   <?
            $this->formSelMails->html()->setAttrib('name', 'selmail_form');
            echo $this->formSelMails->renderStart();
   ?>
            <table id="tableMails" style="width: 100%;">
               <thead>
                  <tr>
                     <th style="width: 140px"></th>
                     <th>E-mail</th>
                     <th>Jméno</th>
                     <th>Přijmení</th>
                     <th>Skupina</th>
                     <th>Akce</th>
                  </tr>
               </thead>
               <tbody>
<? foreach ($this->mails as $key => $mail) { ?>
               <tr class="mails-table-row mails-row-group-<?=$mail['group']?>">
                  <td align="center">
                     <input type="checkbox" name="selmail_select[<?=$key; ?>]" value="<?=$mail['id']; ?>" />
                  </td>
                  <td><a href="<?=$this->link()->route('composeMail')->param('mail', $mail['mail']); ?>"
                         title="<?=$this->_('Poslat email') ?>"
                         ><?=$mail['mail'] ?></a></td>
                  <td><?=$mail['name'] ?></td>
                  <td><?=$mail['surname'] ?></td>
                  <td>
                        <?=$mail['group'] ?>
               <input type="hidden"
                      name="selmail_type[<?=$key; ?>]" value="<?=$mail['type']; ?>" />
            </td>
            <td>
               <? if ($mail['type'] == Mails_Controller::MAIL_TYPE_ADDRESSBOOK
                       OR $mail['type'] == Mails_Controller::MAIL_TYPE_NEWSLETTER) { ?>
                  <input type="image" src="images/icons/email_delete.png"
                         name="selmail_delete" value="<?=$this->_('Smazat'); ?>" title="<?=$this->_('Smazat e-mail'); ?>" />
                      <?
                   }
                   if ($mail['type'] == Mails_Controller::MAIL_TYPE_ADDRESSBOOK) {
                      ?>
               <a href="<?=$this->link()->route('editMail', array('id' => $mail['id']))
                      ?>"
                  title="<?=$this->_('Upravit e-mail');
                      ?>"
                      ><img src="<?=Template::getFileDir('icons/email_edit.png', Template::IMAGES_DIR, false, true)
                      ?>"
                         alt="edit mail icon"/></a>
<? } ?>
                <input type="hidden" name="selmail_mail[<?=$key; ?>]" value="<?=$mail['mail']; ?>" />
                <input type="hidden" name="selmail_name[<?=$key; ?>]" value="<?=$mail['name']; ?>" />
               <input type="hidden" name="selmail_surname[<?=$key; ?>]" value="<?=$mail['surname']; ?>" />
            </td>
         </tr>
   <? } ?>
         </tbody>
      </table>
      <input type="hidden" name="selmail_action" value="<?=Mails_Controller::ACTION_COMPOSE ?>" />
<? echo $this->formSelMails->renderEnd(); ?>
   <hr class="reseter" />
   <div>
      <strong><?=$this->_('Označit') ?>:</strong>&nbsp;
      <button type="submit" name="select_all" title="<?=$this->_('Vše') ?>"
              value="<?=$this->_('Vše') ?>"><?=$this->_('Vše') ?></button>&nbsp;
      <button type="submit" name="select_none" title="<?=$this->_('Nic') ?>"
              value="<?=$this->_('Nic') ?>"><?=$this->_('Nic') ?></button>&nbsp;
      <select name="select_group">
<? foreach ($this->groups as $name => $group) { ?>
            <option value="<?=$group ?>"><?=$name ?></option>
<? } ?>
      </select>
      <button type="submit" name="select_group_button" title="<?=$this->_('Označit') ?>"
              value="<?=$this->_('Označit') ?>"><?=$this->_('Označit') ?></button>&nbsp;
      <strong><?=$this->_('Označené') ?>:</strong>&nbsp;
      <button type="submit" name="delete_items" title="<?=$this->_('Smazat označené') ?>"
              value="<?=$this->_('Smazat') ?>"><?=$this->_('Smazat') ?></button>&nbsp;
      <button type="submit" name="composemail_button" title="<?=$this->_('Poslat e-mail označeným') ?>"
              value="compose_mail"><?=$this->_('Poslat e-mail') ?></button>&nbsp;
      <select name="export_type">
         <option value="<?=Mails_Controller::EXPORT_CSV ?>">CSV</option>
         <option value="<?=Mails_Controller::EXPORT_TXT ?>">txt</option>
         <option value="<?=Mails_Controller::EXPORT_VCARD ?>">vCard</option>
      </select>
      <button type="submit" name="export_mails_button" value="export_mails"><?=$this->_('Export') ?></button>
      <br />
      <p class="content-note">
         <span class="content-note-label"><?=$this->_('Poznámka:') ?></span><br />
<? echo $this->_('Emailové adresy uživatelů registrovaných v systému zde nelze smazat.') ?>
      </p>
   </div>
   <br />
   <h2><?=$this->_('Import adres');?></h2>
   <?
      echo $this->formImport->renderStart();
      echo $this->formImport->file->label();
      echo $this->formImport->file->controll();
      echo $this->formImport->target->label();
      echo $this->formImport->target->controll();
      echo $this->formImport->separator->label();
      $this->formImport->separator->html()->setAttrib('size',1);
      echo $this->formImport->separator->controll();
      echo $this->formImport->import->controll();
      echo $this->formImport->renderEnd();
   ?>
   <br />

   <script type="text/javascript" charset="utf-8">
      var $table;
      $(document).ready(function() {
         $table = $('#tableMails').dataTable( {
            "oLanguage": {
               "sLengthMenu": "<?=$this->_('Zobrazit _MENU_ záznamů na stránku') ?>",
               "sZeroRecords": "<?=$this->_('Nic nenalezeno') ?>",
               "sInfo": "<?=$this->_('Zobrazeno od _START_ do _END_ z _TOTAL_ záznamů') ?>",
               "sInfoEmtpy": "<?=$this->_('Zobrazeno 0 z 0 záznamů') ?>",
               "sInfoFiltered": "(<?=$this->_('filtrováno z _MAX_ celkových záznamů') ?>)"
            },
            "aaSorting": [[ 1, "asc" ]],
            "aoColumns": [{ "bSortable": false },
               null, null, null, null, { "bSortable": false }
            ]
         });

         // přepnutí označení při kliknutí na řádek
//         $('#tableMails tr').click(function(){
//            var $checkbox = $(this).find('input[type=checkbox]');
//            if($checkbox.attr('checked') == true) {
//               $checkbox.attr('checked', false);
//            } else {
//               $checkbox.attr('checked', true);
//            }
//         });

         // označení všech
         $('button[name=select_all]').click(function(){
            $('input[type=checkbox]',$table.fnGetNodes()).attr('checked', true);
            return false;
         });
         // zrušení označení
         $('button[name=select_none]').click(function(){
            $('input[type=checkbox]',$table.fnGetNodes()).attr('checked', false);
            return false;
         });
         // označení skupiny
         $('button[name=select_group_button]').click(function(){
            $('button[name=select_none]').click();
            var selectedGroup = $('select[name=select_group]').val();
            $('#tableMails tr.mails-row-group-'+selectedGroup+' input[type=checkbox]').attr('checked', true);
            return false;
         });
         $('select[name=select_group]').change(function(){
            $('button[name=select_group_button]').click();
         });

         // smazánní jednoho mailu
         $('input[name=selmail_delete]').click(function(){
            if(!confirm('<?=$this->_('Smazat e-mail?') ?>')){return false;}
            $('#tableMails tr td input[type=checkbox]').attr('checked', false);
            $(this).parent().parent().find('input[type=checkbox]').attr('checked', true);
            var $form = $('form[name=selmail_form]');
            $('input[name=selmail_action]', $form).val('<?=Mails_Controller::ACTION_DELETE ?>');
            $form.submit();
            return false;
         });

         $('button[name=delete_items]').click(function(){
            if(!confirm('<?=$this->_('Smazat označené?') ?>')){return false;}
            var $form = $('form[name=selmail_form]');
            $('input[name=selmail_action]', $form).val('<?=Mails_Controller::ACTION_DELETE ?>');
            $form.submit();
            return false;
         });

         // submit formu a přidání zkrytých prvků
         $('form[name=selmail_form]').submit( function() {
            var $hiddenNodes = $table.fnGetHiddenNodes();
            var $form = $(this).clone();
            // $(this).hide().append($hiddenNodes);
            $form.append($hiddenNodes).submit();
            return false;
         });


         // přechod na tvorbu emailu
         $('button[name=composemail_button]').click(function(){
            if(isSomeSelected() == false) return false;
            var $form = $('form[name=selmail_form]');
            $form.attr('action', $(this).attr('action'));
            $('input[name=selmail_action]', $form).val('<?=Mails_Controller::ACTION_COMPOSE ?>');
            $form.submit();
            return false;
         });

         // export
         $('button[name=export_mails_button]').click(function(){
            if(isSomeSelected() == false) return false;
            var exportType = $('select[name=export_type]').val();
            var $form = $('form[name=selmail_form]');
            $('input[name=selmail_action]', $form).val('<?=Mails_Controller::ACTION_EXPORT ?>');
            $form.attr('action', '<?=$this->link() ?>'+'?export='+exportType).submit();
            return false;
         });


      });
      // funkce vytáhne všechyn vybrané maily
      function getMails(){
         //         return $('tr.mails-table-row:has(input[type=checkbox]:checked)', $table.fnGetNodes());
         return $table.fnGetNodes();
      }

      function isSomeSelected(){
         var $items = $('input[type=checkbox]:checked' ,$table.fnGetNodes());
         if($items.length == 0){
            errMsg('<?=$this->_('Nebyla vybrána žádná položka') ?>');
            return false;
         }
         return true;
      }
   </script>
   <br />
</div>
<? $this->includeTpl("buttonback.phtml", true, array('link' => (string) $this->link()->route(null))); ?>
