<?
$this->addPageTitle($this->tr('Vytvořit e-mail'));
$this->addCssFile('style.css');
?>
<h1><?=$this->category()->getName().' - '.$this->tr('vytvořit e-mail')?></h1>
<?=$this->includeTpl('navigation.phtml');?>
<div class="main-content-form-edit" id="mails-send-mail-form">
   <?
   $jQ = new JsPlugin_JQuery();
   $jQ->addUITabs();
   $jQ->addUIAutoComplete();
   $this->addJsPlugin($jQ);
   ?>
   <?
   $this->form->html()->setAttrib('id', 'mail-send-form');
   echo $this->form->renderStart(); ?>
      <fieldset>
      <table class="form-table">
      <tr>
         <th class="form-labels">
            <? echo $this->form->recipients->label() ?>
         </th>
         <td class="form-controlls">
            <? 
            $this->form->recipients->html()->setAttrib('cols', 80)->setAttrib('rows', 5)->addClass('full-width');
            echo $this->form->recipients->controll();
            echo $this->form->recipients->sublabel() ?>
         </td>
      </tr>
      <tr>
         <th class="form-labels">
            <?=$this->tr('Uložené Maily') ?>:
         </th>
         <td>
            <div id="address-tabs">
               <ul>
                  <li><a href="#tabs-mails-addressbook"><?=$this->tr('Adresář') ?></a></li>
                  <li><a href="#tabs-mails-users"><?=$this->tr('Uživatelé systému') ?></a></li>
                  <?if($this->mailsNewsLetter !== null AND !empty ($this->mailsNewsLetter)){?>
                     <li><a href="#tabs-mails-newsletter"><?=$this->tr('NewsLetter') ?></a></li>
                  <?}?>
                  <?if($this->mailsGuestbook !== null AND !empty ($this->mailsGuestbook)){?>
                     <li><a href="#tabs-mails-guestbook"><?=$this->tr('Kniha návštěv') ?></a></li>
                  <?}?>
               </ul>
               <div id="tabs-mails-addressbook">
                  <label for="mails-addressbook"><?=$this->tr('Všechny adresy v adresáři')?>:</label><br />
                  <select name="mails-addressbook" class="mail-selected" id="mails-addressbook"
                          size="6" multiple="multiple">
                     <? foreach ($this->mailsAddressBook as $mail) {
                        $str = null;
                        if ($mail->{Mails_Model_Addressbook::COLUMN_SURNAME} != null) {
                           $str .= '"'.$mail->{Mails_Model_Addressbook::COLUMN_NAME}
                           ." ".$mail->{Mails_Model_Addressbook::COLUMN_SURNAME}.'" ';
                        }
                        $str .= '<'.$mail->{Mails_Model_Addressbook::COLUMN_MAIL}.'>';
                        $str = htmlspecialchars($str);
                        ?><option value="<?=$str?>"><?=$str?></option><?
                     }?>
                  </select><br />
                  <input type="button" value="<?=$this->tr('Přidat')?>" class="button-add" data-select="mails-addressbook" />
                  <input type="button" value="<?=$this->tr('Přidat všechny')?>" class="button-add-all" data-select="mails-addressbook" /><br />
                  <br />
                  <label for="mails-addressbook-groups"><?=$this->tr('Adresy ze skupiny')?>:</label><br />
                  <select name="mails-addressbook-groups" id="mails-addressbook-groups">
                     <?foreach ($this->mailsGroups as $grp) {
                        ?><option value="<?=$grp->{Mails_Model_Groups::COLUMN_ID}?>"><?=$grp->{Mails_Model_Groups::COLUMN_NAME}?></option><?
                     }?>
                  </select>
                  <input type="button" value="<?=$this->tr('Přidat')?>" name="button-add-group" /><br />
               </div>
               <div id="tabs-mails-users">
                  <table style="width: 100%;">
                  <?foreach ($this->mailsUsers as $gname => $grp) {
                     $gnameAscii = md5($gname);
                     ?>
                     <tr>
                        <td colspan="2"><label for="mails-users-grp-<?=$gnameAscii?>"><?=$this->tr('Skupina').':&nbsp;'.$gname?></label></td>
                     </tr>
                     <tr>
                        <td style="width: 60%;">
                           <select name="mails-users" class="mail-selected" id="mails-users-grp-<?=$gnameAscii?>">
                     <?foreach ($grp as $mail) {
                        if($mail->{Model_Users::COLUMN_MAIL} == null) continue;
                        $m = explode(';', $mail->{Model_Users::COLUMN_MAIL});
                        $str = null;
                        if ($mail->{Model_Users::COLUMN_SURNAME} != null) {
                           $str .= '"'.$mail->{Model_Users::COLUMN_NAME}
                           ." ".$mail->{Model_Users::COLUMN_SURNAME}.'" ';
                        } 
                        $str .= '<'.$m[0].'>';
                        $str = htmlspecialchars($str);
                        ?><option value="<?=$str;?>"><?=$str;?></option><?
                     }?>
                           </select>
                        </td>
                        <td>
                           <input type="button" value="<?=$this->tr('Přidat')?>" class="button-add" data-select="mails-users-grp-<?=$gnameAscii?>" />
                           <input type="button" value="<?=$this->tr('Přidat všechny')?>" class="button-add-all" data-select="mails-users-grp-<?=$gnameAscii?>"  />
                        </td>
                     </tr>
                  <?}?>
                  </table>
               </div>
                  <?if($this->mailsNewsLetter !== null AND !empty ($this->mailsNewsLetter)){?>
               <div id="tabs-mails-newsletter">
                  <select name="mails-newsletters" class="mail-selected" id="mails-newsletters"
                          size="6" multiple="multiple">
                     <?foreach ($this->mailsNewsLetter as $mail) {
                        $str = htmlspecialchars('<'.$mail->{NewsLetter_Model_Mails::COLUMN_MAIL}.'>');
                        ?><option value="<?=$str?>"><?=$str;?></option><?
                     }?>
                  </select><br />
                  <input type="button" value="<?=$this->tr('Přidat')?>" class="button-add" data-select="mails-newsletters" />
                  <input type="button" value="<?=$this->tr('Přidat všechny')?>" class="button-add-all" data-select="mails-newsletters" />
               </div>
                  <?}?>
                  <?if($this->mailsGuestbook !== null AND !empty ($this->mailsGuestbook)){?>
               <div id="tabs-mails-guestbook">
                  <select name="mails-guestbook" class="mail-selected" id="mails-guestbook"
                          size="6" multiple="multiple">
                     <?foreach ($this->mailsGuestbook as $mail) {
                        $str = htmlspecialchars('"'.$mail->{GuestBook_Model_Detail::COL_NICK}.'" '
                        .'<'.$mail->{GuestBook_Model_Detail::COL_EMAIL}.'>');
                        ?><option value="<?=$str;?>"><?=$str;?></option>
                     <?}?>
                  </select><br />
                  <input type="button" value="<?=$this->tr('Přidat')?>" class="button-add" data-select="mails-guestbook" />
                  <input type="button" value="<?=$this->tr('Přidat všechny')?>" class="button-add-all" data-select="mails-guestbook" />
               </div>
                  <?}?>
            </div>
            <br />
         </td>
      </tr>
      <tr>
         <th class="form-labels">
            <? echo $this->form->subject->label() ?>
         </th>
         <td class="form-controlls">
            <? 
            $this->form->subject->html()->setAttrib('size', 60);
            echo $this->form->subject->controll(); 
            ?><br />
         </td>
      </tr>
      <tr>
         <th class="form-labels"><? echo $this->form->text->label() ?></th>
         <td class="form-controlls">
            <?=$this->tr('editor') ?>:&nbsp;<a href="<?=$this->link() ?>#disableEditor"
                      onclick="toggleEditor('sendmail_text_1');"
                      title="<?=$this->tr('vypnout/zapnout editor') ?>"><?=$this->tr('OFF/ON') ?></a>
            <br />
            <?
            $this->form->text->html()
               ->setAttrib('cols', 90)->setAttrib('rows', 40)->addClass('full-width');
            echo $this->form->text->controll(); ?>
            <br />
         </td>
      </tr>
      <tr>
         <th class="form-labels"></th>
         <td class="form-controlls">
            <? 
            echo $this->form->send->controll();
            ?>
         </td>
      </tr>
      <tr>
         <th class="form-labels"></th>
         <td class="form-controlls">
            <?
            echo $this->form->sendQueue->label();
            echo $this->form->sendQueue->controll();
            echo $this->form->sendQueue->subLabel();
            ?>
            <br />
         </td>
      </tr>
      <tr>
         <th class="form-labels"></th>
         <td class="form-controlls">
            <?
            echo $this->form->file->label();
            echo $this->form->file->controll();
            ?>
            <br />
         </td>
      </tr>
      <tr>
         <th class="form-labels"></th>
         <td class="form-controlls">
            <? 
            echo $this->form->sendBatch->label();
            echo $this->form->sendBatch->controll();
            ?>
         </td>
      </tr>
   </table>
   </fieldset>
   <? echo $this->form->renderEnd(); ?>
</div>
<script type="text/javascript">
   /* <![CDATA[ */
   function toggleEditor(id) {
      if (!tinyMCE.get(id)) tinyMCE.execCommand('mceAddControl', false, id);
      else tinyMCE.execCommand('mceRemoveControl', false, id);
      return false;
   }
   var $recBox = null;
   function addMail(mailstr){
      var curStr = $recBox.val();
      if(mailstr != '' && mailstr != null && curStr.search(mailstr) == -1){
         $recBox.val(curStr+mailstr.replace('&lt;', '<').replace('&gt;', '>')+', ');
      }
   }
   // find last string
   function getLastStr(str){
      var lastSpace = str.lastIndexOf(' ');
      var lastDot = str.lastIndexOf(',');
      if(lastSpace != -1 || lastDot != -1){
         if(lastSpace > lastDot){
            str = str.slice(lastSpace+1);
         } else {
            str = str.slice(lastDot+1);
         }
      }
      return str;
   }

   $(function() {
      $recBox = $('textarea[name=sendmail_recipients]'); // init of box
      // tabs
      $("#address-tabs").tabs({collapsible: true,selected: -1});
      // buttons
      $('input.button-add-all').click(function(){
         $('#'+$(this).data('select')).children('option').each(function() {addMail($(this).val());});
      });
      $('input.button-add').click(function(){
         $('#'+$(this).data('select')).children('option:selected').each(function(){addMail($(this).val());});
      });
      // double click on select
      $('select.mail-selected option').dblclick(function(){
         addMail($(this).val());
      });
      // add grp
      $('input[name=button-add-group]').click(function(){
         $.ajax({
            type: "POST",
            cache : false,
            url:'<?=$this->link()->route('addressList');?>',
            data : ({idgrp : $('select[name=mails-addressbook-groups]').val(), rows:10000}),
            success: function(data){
               $.each(data.rows, function(index, value) {
                  var str = '';
                  if(value.addressbook_name != null && value.addressbook_surname != ''){
                     str += '"'+value.addressbook_name+' '+value.addressbook_surname+'" ';
                  }
                  str += '<'+value.addressbook_mail+'>';
                  addMail(str);
               });
            }
         });
      });
      // autocomplete
      var sterm = '';
      $recBox.autocomplete({
			minLength: 1,
			source: function(request, response) {
            sterm = getLastStr(request.term);
				$.getJSON("<?=$this->link()->route('searchMail')?>", {q:sterm},
            function(data){
               var list = new Array();
               $.each(data.mails, function(){
                  var str = '';
                  if( this.<?=MailsAddressBook_Model_Addressbook::COLUMN_NAME?> != null && this.<?=MailsAddressBook_Model_Addressbook::COLUMN_NAME?> != '' ){
                     str += '"'+this.<?=MailsAddressBook_Model_Addressbook::COLUMN_NAME?>+' '+this.<?=MailsAddressBook_Model_Addressbook::COLUMN_SURNAME?>+'" ';
                  }
                  str += '<'+this.<?=MailsAddressBook_Model_Addressbook::COLUMN_MAIL?>+'>';
                  list.push(str)
               });
               response(list);
            }
            );
			},
         search: function(event, ui) {
            if(getLastStr($recBox.val()).replace(/\s/g,"") == ""){
               return false;
            }
         },
			focus: function() {return false;},
			select: function(event, ui) {
            var reg = new RegExp(sterm+'$');
            $recBox.val($recBox.val().replace(reg,''));
            addMail(ui.item.value);
				return false;
			}
		});
   });
   /* ]]> */
</script>



