<?
$this->items = array(
   $this->tr('Vytvořit e-mail') => array('link' => (string)$this->link()->route(), 'icon' => 'email_edit.png'),
   $this->tr('Fronta odesílání') => array('link' => (string)$this->link()->route('sendMailsQueue'), 'icon' => 'cog.png'),
   $this->tr('Odesláné e-maily') => array('link' => (string)$this->link()->route('sendMailsList'), 'icon' => 'email_go.png'),
   );
$this->includeTpl('module_navigation.phtml', true);
?>