<h2>Základní parametry</h2>
<h3>Úprava parametru "název kategorie"</h3>
<p>U nových názvů kategorií se automaticky generuje i URL klíče k těmto kategoriím.</p>

<h3>Úprava parametru "URL klíč"</h3>
<p>Při úpravě klíču se prázdné hodnoty generují automaticky podle názvu kategorie a zařazení kategorie ve struktuře.</p>

<h3>Mapa stránek</h3>
<h2>Úprava parametru "Priorita"</h2>
<p>Parametr určuje důležitost zadané kategorie. Nejdůležitější kategorie by měla mí prioritu "1". Každá stránka by měla mít odlišnou prioritu.</p>