<h2>Hromadná úprava</h2>
<p>Hromadná úprava parametrů slouží pro zjednodušení editace všech kategorií a samotné struktury stránek. 
Upravovat lze několik základních parametrů a parametrů pro SEO</p>
<h3>Parametry:</h3>
<ul>
   <li>
      Základní
      <ul>
         <li>Název</li>
         <li>Alternativní název</li>
         <li>URL klíč</li>
         <li>Priorita</li>
         <li>Viditelnost</li>
         <li>Individuální panely</li>
         <li>Výchoí práva</li>
         <li>RSS export</li>
      </ul>
   </li>
   <li>
      Metadata
      <ul>
         <li>Popisek</li>
         <li>Klíčová slova</li>
      </ul>
   </li>
   <li>
      Mapa stránek
      <ul>
         <li>Frekvence změn</li>
         <li>Priorita</li>
      </ul>
   </li>
</ul>