<?
$grid = new Component_JqGrid_JsPlugin();
$this->addJsPlugin($grid);
$this->addFile('css://style.css');

if(isset($_GET['back']) && $_GET['back'] == "detail"){
   $link = $this->link()->route('dirList')->param('back');
} else {
   $link = $this->link()->route();
}
?>

<h1><?ps(sprintf($this->tr('Přístupy ke složce "%s"'), $this->directory->{ShareDocs_Model_Dirs::COLUMN_NAME} ))?></h1>

<div class="main-content-form-edit">
   <div id="sharedocs-edit-buttons" class="module-tool-buttons">
      <form action="<?=$link?>" method="get">
         <input type="submit" value="<?=$this->tr('Zavřít úpravu')?>" class="button-cancel" />
      </form>
   </div>
   <div><?=$this->formPublicAcc;?></div>
   
   <h2><?=$this->tr("Oprávnění skupin");?></h2>
   <table id="table-groups"></table>
   <div id="table-groups-pager"></div>
   <hr class="reseter" />
   <br />
   <h2><?=$this->tr("Oprávnění uživatelů");?></h2>
   <table id="table-users"></table>
   <div id="table-users-pager"></div>
   <hr class="reseter" />
   <br />
   
</div>
<script type="text/javascript">
         /* <![CDATA[ */
      var groupsList = <?=json_encode($this->groups)?>;
      var usersList = <?=json_encode($this->users)?>;
      
      $(document).ready(function() {
         var groupsGrid = $("#table-groups").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url: '<?=$this->link()->route('groupsList');?>',
            datatype: "json",
            colNames:['<?=$this->tr('Název')?>', '<?=$this->tr('Pouze čtení')?>'],
            colModel:[
               {name:'group',index:'group', editable:true, edittype : 'select', editoptions:{ value : groupsList },
                  formoptions:{ rowpos:2, label: "<?=$this->tr('Název')?>"}},
               
               {name:'<?=ShareDocs_Model_GroupsAcc::COLUMN_READ_ONLY?>',index:'<?=ShareDocs_Model_GroupsAcc::COLUMN_READ_ONLY?>', 
                  formatter: 'checkbox', formatoptions: {disabled : false, 'class' : 'groupChangeRead'},
                  width:80,fixed:true, editable:true, edittype:'checkbox', editoptions: {value: "true:false" },
                  formoptions:{ rowpos:4, label: "<?=$this->tr('Pouze čtení')?>"}}
            ],
            rowNum:10, rowList:[10,20,40,100], 
            pager: '#table-groups-pager',
            caption:"<?=$this->tr('Skupiny s oprávněními')?>",
            autowidth : true, height: '100%',
            editurl : "<?=$this->link()->route("editGroupAcc")?>",
            jsonReader: { repeatitems : false, root:"rows" }
         });

         groupsGrid.jqGrid('navGrid','#table-groups-pager',
            {edit:false,add:true,del:true, search:false},{},// edit options
            // add options
            {reloadAfterSubmit:true,jqModal:true, closeOnEscape:true, closeAfterAdd: true, width: 500,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },  
            // del options
            {reloadAfterSubmit:true, jqModal:true, closeOnEscape:true, width: 300,
               afterSubmit : function(respond, postdata){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            {}, {closeOnEscape:true}
         );
         
         /* USERS */
      
         var usersGrid = $("#table-users").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url: '<?=$this->link()->route('usersList');?>',
            datatype: "json",
            colNames:['<?=$this->tr('Jméno')?>', '<?=$this->tr('Pouze čtení')?>'],
            colModel:[
               {name:'user',index:'user', editable:true, edittype : 'select', editoptions:{ value : usersList },
                  formoptions:{ rowpos:2, label: "<?=$this->tr('Název')?>"}},
               
               {name:'<?=  ShareDocs_Model_UsersAcc::COLUMN_READ_ONLY?>',index:'<?=ShareDocs_Model_UsersAcc::COLUMN_READ_ONLY?>', 
                  formatter: 'checkbox', formatoptions: {disabled : false, 'class' : 'userChangeRead'},
                  width:80,fixed:true, editable:true, edittype:'checkbox', editoptions: {value: "true:false" },
                  formoptions:{ rowpos:4, label: "<?=$this->tr('Pouze čtení')?>"}}
            ],
            rowNum:10, rowList:[10,20,40,100], 
            pager: '#table-users-pager',
            caption:"<?=$this->tr('Uživatelé s oprávněními')?>",
            autowidth : true, height: '100%',
            editurl : "<?=$this->link()->route("editUserAcc")?>",
            jsonReader: { repeatitems : false, root:"rows" }
         });
         
         usersGrid.jqGrid('navGrid','#table-users-pager',
            {edit:false,add:true,del:true, search:false},{},// edit options
            // add options
            {reloadAfterSubmit:true,jqModal:true, closeOnEscape:true, closeAfterAdd: true, width: 500,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },  
            // del options
            {reloadAfterSubmit:true, jqModal:true, closeOnEscape:true, width: 300,
               afterSubmit : function(respond, postdata){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            {}, {closeOnEscape:true}
         );
         
         /* změna read/write */
         $('input[type="checkbox"]', groupsGrid).live('change', function(){
            var $obj = $(this); var rowId = $obj.parents('tr').attr('id');
            var val = false;
            if($obj.is(':checked')){ val = true; }
            $.ajax({
               url: "<?=$this->link()->route("setReadOnly")?>", cache : false,
               type: "POST", data: {id : rowId, type : 'group', status : val},
               success : function(data){
                  if( (typeof data.result == "undefined") || data.result == false){
                     alert('<?=$this->tr("Chyba při změně oprávnění. Kontaktujte administrátora.")?>');
                  }
               }
            });
         });
         $('input[type="checkbox"]', usersGrid).live('change', function(){
            var $obj = $(this); var rowId = $obj.parents('tr').attr('id');
            var val = false;
            if($obj.is(':checked')){ val = true; }
            $.ajax({
               url: "<?=$this->link()->route("setReadOnly")?>", cache : false,
               type: "POST", data: {id : rowId, type : 'user', status : val},
               success : function(data){
                  if( (typeof data.result == "undefined") || data.result == false){
                     alert('<?=$this->tr("Chyba při změně oprávnění. Kontaktujte administrátora.")?>');
                  }
               }
            });
         });
      
      
      });
      /* ]]> */
</script>   
