<?
$jQuery = new JsPlugin_JQuery();
$jQuery->addUISortable();
$this->addJsPlugin($jQuery);
$this->addCssFile('style.css');
?>
<div>
   <?=$this->form->renderStart();?>
   <fieldset>
      <ul id="boxsSortable">
      <?$step = 0;
      $this->form->api->html()->addClass('boxApiSelect');
      $this->form->sel->html()->addClass('buttonSelSource');
      $this->form->sel_article->html()->addClass('boxArtSelect');
      foreach ($this->curBoxes as $key => $box) {
         $this->form->api->setValues((string)$box);
         $this->form->api->setDimensional($step);
         $this->form->sel->setValues((string)$box['type']);
         $this->form->sel->setDimensional($step);
         $this->form->sel_article->setOptions($this->websApis[(string)$box]['options']);
         $this->form->sel_article->setDimensional($step);
         $this->form->sel_article->setValues($box['url']);
         ?>
      <li>
      <table class="formTableGroup tblBoxSetting" width="400">
         <tr><th class="movableRow" colspan="2">Box <?=$step?></th></tr>
         <tr>
            <th class="formLabels">
                  <?=$this->form->api->label();?>
            </th>
            <td class="formControlls">
                  <?=$this->form->api->controllAll();?>
               <span></span>
            </td>
         </tr>
         <tr>
            <th class="formLabels">
                  <?=$this->form->sel->label();?>
            </th>
            <td class="formControlls">
                  <?=$this->form->sel->controllAll();?>
               <span></span>
            </td>
         </tr>
         <tr>
            <th class="formLabels">
                  <?=$this->form->sel_article->label();?>
            </th>
            <td class="formControlls">
                  <?=$this->form->sel_article->controllAll();?>
               <span></span>
            </td>
         </tr>
         <tr>
            <td colspan="2" align="right">
                  <?//=$this->form->actualurl->controllAll();?>
               <a href="#" class="buttonRemoveBox" title="Odstranit">Odstranit</a>
            </td>
         </tr>
      </table>
      </li>
         <?
         $step++;
      }?>
      </ul>
      <table id="boxTableRemove" class="formTableGroup" width="400">
         <tr>
            <td colspan="2" align="right"><a href="#" class="buttonAddBox" title="Přidat box">Přidat box</a></td>
         </tr>
         <tr>
            <th class="formLabels">
            </th>
            <td class="formControlls">
               <?=$this->form->save->controllAll();?>
               <span></span>
            </td>
         </tr>
      </table>
   </fieldset>
   <?=$this->form->renderEnd();
   $this->form->api->setDimensional('replace');
   $this->form->sel->setDimensional('replace');
   $this->form->sel_article->setDimensional('replace');
   ?>
   <table class="boxTemplate formTableGroup tblBoxSetting" width="400" style="display: none;">
      <tr><th class="movableRow" colspan="2">Box replace</th></tr>
      <tr>
         <th class="formLabels">
            <?=$this->form->api->label();?>
         </th>
         <td class="formControlls">
            <?=$this->form->api->controllAll();?>
            <span></span>
         </td>
      </tr>
      <tr>
         <th class="formLabels">
            <?=$this->form->sel->label();?>
         </th>
         <td class="formControlls">
            <?=$this->form->sel->controllAll();?>
            <span></span>
         </td>
      </tr>
      <tr>
         <th class="formLabels">
            <?=$this->form->sel_article->label();?>
         </th>
         <td class="formControlls">
            <?
            $this->form->sel_article->html()->setAttrib('disabled', 'disabled');
            print($this->form->sel_article->controllAll());
            ?>
            <span></span>
         </td>
      </tr>
      <tr>
         <td colspan="2" align="right">
            <?//=$this->form->actualurl->controllAll();?>
            <a href="#" class="buttonRemoveBox" title="Odstranit">Odstranit</a>
         </td>
      </tr>
   </table>

   <script type="text/javascript">
      var lastId = <?=$step?>;
      /* <![CDATA[ */
      function evRemoveBox(event){
         if($('.tblBoxSetting').length > 1){
            var obj = $(this).parents('table');
            obj.remove();
         }
         return false;
      }

      function evChangeApi(ev){
         loadArticles($(this).parents('table'));
      }

      function evChangeSource(ev){
         if($(this).val() == 'selected'){
            $(this).parents('table').find('select.boxArtSelect').removeAttr('disabled');
         } else {
            $(this).parents('table').find('select.boxArtSelect').attr('disabled', 'disabled');
         }
      }

      $('.buttonAddBox').click(function(){
         var jTbl = $('.boxTemplate').clone(true);
         var idNew = lastId;
         var str = jTbl.html();
         str = str.replace('replace', idNew.toString(),'g');
         var newTbl = $('<li></li>').html('<table class="formTableGroup tblBoxSetting">'+str+'</table>');
         newTbl.find('a.buttonRemoveBox').bind('click', null, evRemoveBox);
         newTbl.find('input.buttonSelSource').bind('click', null, evChangeSource);
         newTbl.find('select.boxApiSelect').bind('change', null, evChangeApi);
         loadArticles(newTbl);
         $('ul#boxsSortable').append(newTbl);
         $("#boxsSortable").sortable('refresh');
         lastId++;
         return false;
      });

      function loadArticles(jqtable){
         jqtable.find(".boxArtSelect").html('')
         .load('<?=$this->link()->route('loadArticles')?>?type='+jqtable.find('select.boxApiSelect').val());
      }


      $(document).ready(function(){
         $(".buttonRemoveBox").bind('click', null, evRemoveBox);
         $(".buttonSelSource").bind('click', null, evChangeSource);
         $(".boxApiSelect").bind('change', null, evChangeApi);
         $("#boxsSortable").sortable({
            placeholder: 'ui-state-highlight'
         });
         $("#boxsSortable").disableSelection();
         $("select.boxArtSelect").each(function(){
            var val = $(this).parents('table').find('input.buttonSelSource:checked').val();
            if(val == 'selected'){
               $(this).removeAttr('disabled');
            } else {
               $(this).attr('disabled', 'disabled');
            }
         });

      });



      /* ]]> */
   </script>
</div>
<?=$this->includeTpl('buttonback.phtml', true, array('link' => $this->link()->clear()))?>
