<?
$this->addCssFile("style.css");

$this->addPageTitle($this->article->{Articles_Model_Detail::COLUMN_NAME});
// jquery galerka
$this->addJsPlugin(new JsPlugin_PiroBox());
$images = $this->images;
echo $this->toolbox;

$image = null;
if ($this->article->{Articles_Model::COLUMN_TITLE_IMAGE} != null) {
   $image = vve_tpl_image_tag(
      vve_tpl_art_title_image($this->article->{Articles_Model::COLUMN_TITLE_IMAGE}), $this->article->{Articles_Model::COLUMN_NAME}, 100, 100, array('image-left'));
} else if(!empty ($images) AND $images != false){
   $randImage = reset($images);
   $image = (vve_tpl_image_tag($this->category()->getModule()->getDataDir(true)
      . $this->websubdir . Photogalery_Controller::DIR_SMALL . URL_SEPARATOR
      . $randImage->{PhotoGalery_Model_Images::COLUMN_FILE}, $randImage->{PhotoGalery_Model_Images::COLUMN_NAME}, 130, 100));
}

?>
<h1><?=$this->article->{Articles_Model_Detail::COLUMN_NAME};?></h1>
<div class="main-content-detail">
   <?if((string)$this->article->{Articles_Model_Detail::COLUMN_ANNOTATION} != null){?>
         <div class="main-content-annotation"><?
         if($image != null) {?><div class="main-content-image"><?=$image?></div><? $image = null;}
         echo $this->article->{Articles_Model_Detail::COLUMN_ANNOTATION};?>
      <hr class="reseter" />
   </div>
   <?}?>
   <div class="main-content-text">
      <?
      echo $this->article->{Articles_Model_Detail::COLUMN_TEXT};
      ?>
      <hr class="reseter" />
   </div>
   <?$this->includeTpl('privateText.phtml', false,null, 'articles');//private text?>
   <!-- Start Advanced Gallery Html Containers -->
   <div class="main-content-images">
      <?
      if(count($images) == 0) echo $this->tr('Galerie neobsahuje žádný obrázek.');
      if(count($images) == 1) {$class = 'pirobox';}
      else {$class = 'pirobox_gall';}
      foreach ($images as $image) {
         ?>
      <a class="<?=$class?>" href="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir
                    .Photogalery_Controller::DIR_MEDIUM.URL_SEPARATOR.$image[PhotoGalery_Model_Images::COLUMN_FILE]?>"
         title="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>">
         <img src="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                         .$image[PhotoGalery_Model_Images::COLUMN_FILE]?>" alt="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>" />
      </a>
         <?}
      echo $this->toolboxImages;?>
   </div>
   <!-- End Gallery Html Containers -->
   <hr class="reseter" />
   <?
   if($this->category()->getParam('shareTools', true) == true){
      $this->includeTpl('articletools.phtml', true, array(
           'lastEditTime' => $this->article->{Articles_Model_Detail::COLUMN_EDIT_TIME},
           'lastEditUser' => $this->article->{Model_Users::COLUMN_USERNAME},
           'linkToPdf' => $this->link()->route('detailExport',array('output' => 'pdf')),
           'linkToHtml' => $this->link()->route('detailExport',array('output' => 'html')),
           'shares' => array('url' => $this->link(), 'title' => $this->article->{Articles_Model::COLUMN_NAME})));
   }
   ?>

   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         $().piroBox({slideShow : true,slideSpeed : 3});
      });
      /* ]]> */
   </script>
</div>
<?$this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->l()->route('normal')));?>
