<?
$this->addCssFile("style.css");

$this->addPageTitle($this->article->{Articles_Model_Detail::COLUMN_NAME});
// jquery galerka
$this->addJsPlugin(new JsPlugin_PiroBox());
$addDate = new DateTime($this->article->{Articles_Model_Detail::COLUMN_ADD_TIME});
$editDate = new DateTime($this->article->{Articles_Model_Detail::COLUMN_EDIT_TIME});
$images = $this->images->fetchAll();
?>
<h1><?=$this->article->{Articles_Model_Detail::COLUMN_NAME};?></h1>
<div class="main-content-detail">
   <?if((string)$this->article->{Articles_Model_Detail::COLUMN_ANNOTATION} != null){?>
   <div class="main-content-annotation"><?=$this->article->{Articles_Model_Detail::COLUMN_ANNOTATION};?></div>
   <?}?>
   <? // nalezneme v textu první obrázek, pokud ano vykreslíme jej
   if(!empty ($images) AND $images != false) {?>
   <div class="main-content-image">
         <?
         $randImage = reset($images);
         print (vve_tpl_image_tag($this->category()->getModule()->getDataDir(true)
                 .$this->subdir.Photogalery_Controller::DIR_MEDIUM.URL_SEPARATOR
                 .$randImage->{PhotoGalery_Model_Images::COLUMN_FILE},
                 $randImage->{PhotoGalery_Model_Images::COLUMN_NAME}, 130, 100));
         ?>
   </div>
   <?}?>
   <?if((string)$this->article->{Articles_Model_Detail::COLUMN_TEXT} != null){?>
      <div class="main-content-text">
         <?=$this->article->{Articles_Model_Detail::COLUMN_TEXT}?>
      </div>
      <hr class="reseter" />
   <?}?>
   <?if($this->allowPrivate === true){?>
      <div class="main-content-text">
         <?=$this->article->{Articles_Model_Detail::COLUMN_TEXT_PRIVATE}?>
      </div>
      <hr class="reseter" />
   <?}?>

   <!-- Start Advanced Gallery Html Containers -->
   <div class="main-content-images">
      <?
      if(count($images) == 1) {$class = 'pirobox';}
      else {$class = 'pirobox_gall';}
      foreach ($images as $image) {
         ?>
      <a class="<?=$class?>" href="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir
                    .Photogalery_Controller::DIR_MEDIUM.URL_SEPARATOR.$image[PhotoGalery_Model_Images::COLUMN_FILE]?>"
         title="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>">
         <img src="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                         .$image[PhotoGalery_Model_Images::COLUMN_FILE]?>" alt="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>" />
      </a>
         <?}?>
   </div>
   <!-- End Gallery Html Containers -->
   <hr class="reseter" />
   <?$this->includeTpl('articletools.phtml', true, array(
           'lastEditTime' => $this->article->{Articles_Model_Detail::COLUMN_EDIT_TIME},
           'lastEditUser' => $this->article->{Model_Users::COLUMN_USERNAME},
           'linkToPdf' => $this->link()->route('detailExport',array('output' => 'pdf')),
           'linkToHtml' => $this->link()->route('detailExport',array('output' => 'html')),
           'shares' => $this->shares));?>

   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         $().piroBox({slideShow : true,slideSpeed : 3});
      });

      /* ]]> */
   </script>
   <?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('edit_galery', $this->_("Upravit článek"),
              $this->link()->route('edit', array('urlkey' => $this->article->{Articles_Model_Detail::COLUMN_URLKEY})),
              $this->_("Upravit galerii"), "page_edit.png");
      $toolbox->addTool('edit_images', $this->_("Upravit fotky"),
              $this->link()->route('editphotos', array('urlkey' => $this->article->{Articles_Model_Detail::COLUMN_URLKEY})),
              $this->_("Upravit fotky galerie"), "image_edit.png");
      $toolbox->addTool('article_delete', $this->_("Smazat"),
              $this->link(), $this->_("Smazat zobrazený článek"), "page_delete.png",
              'article_id', (int)$this->article->{Articles_Model_Detail::COLUMN_ID},
              $this->_('Opravdu smazat článek?'));
      $this->includeTplObj($toolbox);
   }?>
</div>
<?$this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->l()->route('normal')));?>
