<?
$this->addCssFile("style.css");

$this->addPageTitle($this->article->{Articles_Model_Detail::COLUMN_NAME});
$this->addPageHeadline($this->article->{Articles_Model_Detail::COLUMN_NAME});
// jquery galerka
$this->addJsPlugin(new JsPlugin_PiroBox());
$addDate = new DateTime($this->article->{Articles_Model_Detail::COLUMN_ADD_TIME});
$editDate = new DateTime($this->article->{Articles_Model_Detail::COLUMN_EDIT_TIME});
$images = $this->images->fetchAll();
?>
<div>
   <div>
      <?=$this->_('Přidáno')." ".strftime("%x %X", $addDate->format("U"))
              ."&nbsp;".$this->_('uživatelem')."&nbsp;".$this->article->{Model_Users::COLUMN_USERNAME}?>.&nbsp;
      <?=$this->_('Zobrazeno')?>:&nbsp;<?=$this->article->{Articles_Model_Detail::COLUMN_SHOWED}?>&times;
   </div>
   <? // nalezneme v textu první obrázek, pokud ano vykreslíme jej
   if(!empty ($images) AND $images != false) {?>
   <div class="imageBox">
         <?
         $randImage = reset($images);
         print (vve_tpl_image_tag($this->category()->getModule()->getDataDir(true)
                 .$this->subdir.Photogalery_Controller::DIR_MEDIUM.URL_SEPARATOR
                 .$randImage->{PhotoGalery_Model_Images::COLUMN_FILE},
                 $randImage->{PhotoGalery_Model_Images::COLUMN_NAME}, 235,null, 'articleImage'));
         ?>
   </div>
      <?}?>
   <div class="photogaleryMedText">
      <?=$this->article->{Articles_Model_Detail::COLUMN_TEXT}?>
   </div>
   <br />

   <!-- Start Advanced Gallery Html Containers -->
   <div class="photogaleryMedImages">
      <?foreach ($images as $image) {
         ?>
      <a class="pirobox_gall" href="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir
                    .Photogalery_Controller::DIR_MEDIUM.URL_SEPARATOR.$image[PhotoGalery_Model_Images::COLUMN_FILE]?>"
         title="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>">
         <img src="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                         .$image[PhotoGalery_Model_Images::COLUMN_FILE]?>" alt="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>" />
      </a>
         <?}?>
   </div>
   <!-- End Gallery Html Containers -->
   <hr class="reseter" />
   <?$this->includeTpl('articletools.phtml', true, array(
           'lastEditTime' => $this->article->{Articles_Model_Detail::COLUMN_EDIT_TIME},
           'lastEditUser' => $this->article->{Model_Users::COLUMN_USERNAME},
           'linkToPdf' => $this->link()->route('detailExport',array('output' => 'pdf')),
           'shares' => $this->shares));?>

   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         $().piroBox({
            my_speed: 300, //animation speed
            bg_alpha: 0.8, //background opacity
            radius: 4, //caption rounded corner
            scrollImage : false, // true == image follows the page _|_ false == image remains in the same open position
            // in some cases of very large images or long description could be useful.
            slideShow : 'slideshow', // true == slideshow on, false == slideshow off
            slideSpeed : 3, //slideshow
            pirobox_next : 'piro_next', // Nav buttons -> piro_next == inside piroBox , piro_next_out == outside piroBox
            pirobox_prev : 'piro_prev', // Nav buttons -> piro_prev == inside piroBox , piro_prev_out == outside piroBox
            close_all : '.piro_close' // add class .piro_overlay(with comma)if you want overlay click close piroBox
         });
      });

      /* ]]> */
   </script>
   <?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('edit_galery', $this->_("Upravit článek"),
              $this->link()->route('edit', array('urlkey' => $this->article->{Articles_Model_Detail::COLUMN_URLKEY})),
              $this->_("Upravit galerii"), "page_edit.png");
      $toolbox->addTool('edit_images', $this->_("Upravit fotky"),
              $this->link()->route('editphotos', array('urlkey' => $this->article->{Articles_Model_Detail::COLUMN_URLKEY})),
              $this->_("Upravit fotky galerie"), "image_edit.png");
      $toolbox->addTool('article_delete', $this->_("Smazat"),
              $this->link(), $this->_("Smazat zobrazený článek"), "page_delete.png",
              'article_id', (int)$this->article->{Articles_Model_Detail::COLUMN_ID},
              $this->_('Opravdu smazat článek?'));
      $this->includeTplObj($toolbox);
   }?>
</div>
<?$this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->l()->route('normal')));?>
