<?
$this->addCssFile("style.css");
$this->includeTpl('sortLabel.phtml',false,null,'articles');
$h1 = $this->category()->getName().$this->sortText;
$imagesM = new PhotoGalery_Model_Images();
echo $this->toolbox;
?>
<h1><?=$h1;?></h1>
<div class="main-content-list">
   <?=$this->includeTpl('sort.phtml',false,null,'articles')?>
   <div class="main-content-list-records">
   <?if(!empty ($this->articles)) {
      foreach ($this->articles as $article) {
         $showClass = $public = null;
         if($article->{Articles_Model_Detail::COLUMN_PUBLIC} == 0){
            $showClass = 'main-content-no-public';
            $public = $this->_('Nezveřejněno');
         }
         $editTime = new DateTime($article->{Articles_Model_Detail::COLUMN_ADD_TIME});
         // hlavní obrázek
         $mainImage = $imagesM->getImages($this->category()->getId(), $article->{Articles_Model_Detail::COLUMN_ID},1)->fetch();

         ?>
   <div class="main-content-list-record <?=$showClass?>">
      <h2><a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
             title="<?=htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>"><?=htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>&nbsp;
            <span class="font-small">
             <?=strftime("%x %X", $editTime->format("U"))?> - <?=$article->{Model_Users::COLUMN_USERNAME}?></span>
         </a><?='<span class="font-small">'.$public.'</span>'?>
      </h2>
            <? // nalezneme v textu první obrázek, pokud ano vykreslíme jej
            if($mainImage != false) {
               ?>
      <div class="main-content-list-record-image"><?
         echo vve_tpl_image_tag($this->category()->getModule()->getDataDir(true)
                          .$article[Articles_Model_Detail::COLUMN_URLKEY][Locales::getDefaultLang()]
                          .URL_SEPARATOR.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                          .$mainImage->{PhotoGalery_Model_Images::COLUMN_FILE},
                          $mainImage->{PhotoGalery_Model_Images::COLUMN_NAME}, 140, 100);
         ?></div><?
         }?>
      <?if((string)$article->{Articles_Model_Detail::COLUMN_ANNOTATION} != null){?>
         <div class="main-content-list-record-annotation"><?echo $article->{Articles_Model_Detail::COLUMN_ANNOTATION};?></div>
      <?} else if((string)$article->{Articles_Model_Detail::COLUMN_TEXT} != null) {?>
         <div class="main-content-list-record-text"><?echo vve_tpl_truncate(strip_tags($article->{Articles_Model_Detail::COLUMN_TEXT}), 640);?></div>
      <?}?>
      <hr class="reseter" />
      <div class="main-content-showed"><?=$this->_('Zobrazeno')?>:&nbsp;<?=$article->{Articles_Model_Detail::COLUMN_SHOWED}?>&times;</div>
      <div class="main-content-link-more">
         <a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
            title="<?=$this->_("více o").' '.$article->{Articles_Model_Detail::COLUMN_NAME}?>">[&nbsp;<?=$this->_("více")?>&nbsp;]</a>
      </div>
      <hr class="reseter" />
   </div>
     <?}
      echo $this->scrollComp;
   } else {
      echo ($this->_('Není vložen žádný článek'));
   }
   ?>
   </div>
   <?
   // rss ikony
   $feeds = new Component_Feed();
   $feeds->setConfig('feedLink', $this->link()->clear());
   $feeds->mainView();
   echo $feeds;
   ?>
</div>
