<?php 
$this->addCssFile("style.css");
$this->includeFile('tpl://articles:sortLabel.phtml');
$h1 = $this->category()->getName().$this->sortText;
echo $this->toolbox;
?>
<h1><?php echo $h1;?></h1>
<div class="main-content-list">
   <?php echo $this->includeFile('tpl://articles:sort.phtml')?>
   <div class="main-content-list-records">
   <?php if(!empty ($this->articles)) {
      foreach ($this->articles as $article) {
         $showClass = $public = null;
         if($article->{Articles_Model_Detail::COLUMN_CONCEPT} == 1){
            $showClass = 'main-content-concept';
            $public = $this->tr('Koncept');
         }
         $editTime = new DateTime($article->{Articles_Model_Detail::COLUMN_ADD_TIME});
         // hlavní obrázek
         $mainImage = false;
         if($article->{Articles_Model::COLUMN_TITLE_IMAGE} != null){
            $mainImage = vve_tpl_image_tag(
               vve_tpl_art_title_image($article->{Articles_Model::COLUMN_TITLE_IMAGE}),$article->{Articles_Model::COLUMN_NAME}, 100, 100);
         } else {
            $img = PhotoGalery_Model_Images::getImages($this->category()->getId(), $article->{Articles_Model_Detail::COLUMN_ID},1);
            if($img != false){
               $mainImage = vve_tpl_image_tag($this->category()->getModule()->getDataDir(true)
                  .$article[Articles_Model_Detail::COLUMN_URLKEY][Locales::getDefaultLang()]
                  .URL_SEPARATOR.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                  .$img->{PhotoGalery_Model_Images::COLUMN_FILE}, $img->{PhotoGalery_Model_Images::COLUMN_NAME}, 100, 100);
            }
         }
         ?>
   <div class="main-content-list-record <?php echo $showClass?>">
      <h2><a href="<?php echo $this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
             title="<?php echo htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>"><?php echo htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>&nbsp;
            <span class="font-small">
             <?php echo strftime("%x %X", $editTime->format("U"))?> - <?php echo $article->{Model_Users::COLUMN_USERNAME}?></span>
         </a><?php echo '<span class="font-small">'.$public.'</span>'?>
      </h2>
      <?php if($mainImage != false) {?><div class="main-content-list-record-image"><?php echo $mainImage;?></div><?php }?>
      <?php if((string)$article->{Articles_Model_Detail::COLUMN_ANNOTATION} != null){?>
         <div class="main-content-list-record-annotation"><?php echo $article->{Articles_Model_Detail::COLUMN_ANNOTATION};?></div>
      <?php } else if((string)$article->{Articles_Model_Detail::COLUMN_TEXT} != null) {?>
         <div class="main-content-list-record-text"><?php echo vve_tpl_truncate(strip_tags($article->{Articles_Model_Detail::COLUMN_TEXT}), 640);?></div>
      <?php }?>
      <hr class="reseter" />
      <div class="main-content-showed"><?php echo $this->tr('Zobrazeno')?>:&nbsp;<?php echo $article->{Articles_Model_Detail::COLUMN_SHOWED}?>&times;</div>
      <div class="main-content-link-more">
         <a href="<?php echo $this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
            title="<?php echo $this->tr("více o").' '.$article->{Articles_Model_Detail::COLUMN_NAME}?>">[&nbsp;<?php echo $this->tr("více")?>&nbsp;]</a>
      </div>
      <hr class="reseter" />
   </div>
     <?php }
      echo $this->scrollComp;
   } else {
      echo ($this->tr('Není vložen žádný článek'));
   }
   ?>
   </div>
   <?php 
   // rss ikony
   $feeds = new Component_Feed();
   $feeds->setConfig('feedLink', $this->link()->clear());
   echo $feeds;
   ?>
</div>
