<h1><?=$this->_("Správa fotek k referenci");?></h1>

<script type="text/javascript">

</script>
<!--<noscript>
<div id="addPhoto">
      <form method="post" action="<?=$this->l();?>" enctype="multipart/form-data">
<?=$this->_m("Obrázek (vkládejte obrázky typu \"jpg/jpech/png/gif\")");?>*:<br />
         <input type="file" size="20" name="reference_photo_file" value="" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <input name="reference_photo_send" type="submit" value="<?=$this->_m("Odeslat")?>" />
      </form>
</div>
</noscript>-->
<div id="uploadForm">
   <form action="<?=$this->ajaxLink->action("addPhoto")->param('idArticle', $this->sys()->article()->getArticle());?>" method="post" enctype="multipart/form-data" target="upload_target" onsubmit="startUpload();" >
      <p id="upload_process"><?=$this->_("Nahrávám")?><img src="images/progress.gif" alt="loading" width="16"/></p>
      <?=$this->_m("Obrázek (vkládejte obrázky typu \"jpg/jpech/png/gif\")");?>*:<br />
      <input name="reference_photo_file" type="file" />
      <input type="submit" name="reference_photo_send" value="<?=$this->_("Nahrát")?>" />
      <span id="result"></span>
   </form>
   <iframe id="upload_target" name="upload_target" src="#" style="width:0;height:0;border:0px solid #fff;"></iframe>

</div>

<?// výpis obrázků?>
<div id="referenceImages">
   <?foreach ($this->images as $image) {
      $this->imageTpl->image = $image;
      $this->includeTplObj($this->imageTpl);
   }?>
</div>

<script language="javascript" type="text/javascript">
   $(document).ready(function(){
      $(".refPhotoEdit").tabs();
   });

   function startUpload(){
      $("#upload_process").show("normal");
      return true;
   }

   function stopUpload(successMessage, insertHtml){
      $("#result").text(successMessage);
      $("#upload_process").hide("normal");
      var newObj = $(insertHtml);
      $("#referenceImages").prepend(newObj);
      newObj.slideDown("normal");
      $('.refPhotoEdit').tabs();
      setLightBox();
      return true;
   }

   function deletePhoto(idPhoto){
      $.ajax({
         type: "POST",
         url: "<?=$this->ajaxLink->action('deletePhoto')?>",
         data: {
            reference_photo_id : idPhoto},
         success: function(msg){
            if(msg == true){
               $("#refPhoto"+idPhoto).slideUp("normal",
               function callback() {
                  $(this).remove(); // dom element
                  setLightBox();
               });
            } else {
               alert(msg+"<?=$this->_("Fotku se nepodařilo smazat")?>");
            }
         }
      });
      return false;
   }

   function setLightBox(){
      $('a[rel*=lightbox]').lightBox();
   }

   // uložení textu fotky přes AJAX
   function savePhotoLabel(formObj, id){
      $(".refFormImgProgress"+id).css('display', 'inline');
//      $("#upload_process").show("normal");

      //načtení da z formuláře
      var labels = new Object();
      $(':input',formObj).each(function(){
         labels[this.name] = $(this).val();
      });
      // odeslání dat na server
      $.ajax({
         type: "POST",
         url: "<?=$this->ajaxLink->action('savePhotoLabel')?>",
         data: labels,
         success: function(msg){
            $(".refFormImgProgress"+id).css('display', 'none');
            $(".refFormImgOk"+id).css('display', 'inline');
            setTimeout('$(".refFormImgOk'+id+'").css("display", "none");',1000)
         },
         error: function(msg){
            alert("<?=$this->_("Chyba při ukládání:")?> "+msg);
         }
      });
      return false;
   }

   $(document).ready(function() { setLightBox() });
</script>

<?$this->includeTpl("buttonback.phtml", true, array('link' => $this->l()->action()));?>

