<div class="referencesList">
   <?if(!empty ($this->referencesArray)) {
      foreach ($this->referencesArray as $reference) {?>
   <div>
      <h2><a href="<?=$this->l()->article($reference['name'], $reference['id_reference'])?>"
             title="<?=$reference['name']?>"><?=$reference['name']?></a>
      </h2>
      <?if($reference['file'] != null){?>
      <div class="imageBox">
         <?=imageTag($this->sys()->module()->getDir()->getDataDir().References_Controller::IMAGES_SMALL_DIR
            .'/'.$reference['file'], "reference image", 100, 100);?>
      </div>
      <?}?>
      <?print truncate(strip_tags($reference['text']), 640);?>
      <p style="text-align:right;">
         <a href="<?=$this->l()->article($reference['name'], $reference['id_reference'])?>"
            title="<?=$reference['name']?>">[&nbsp;<?=$this->_("více")?>&nbsp;]</a></p>
      <hr class="reseter" />
   </div>
      <?}}?>
   <br />
   <?if($this->sys()->rights()->isWritable()) {
      $this->includeTplObj($this->toolbox);
   }?>
</div>
<?
$this->includeTplObj($this->EPLscroll);
?>