<?php 
$this->addCssFile('style.css');
echo $this->toolbox;
?>
<h1><?php $this->includeFile('tpl://engine:headline/icon.phtml'); echo $this->category()->getName();?></h1>
<div class="main-content-detail">
   <div class="row">
      <div class="col-md-12">
         <div class="search-box">
            <form method="get" action="<?php echo $this->link()?>" class="form-inline" role="form">
               <div class="form-group">

               <label for="search_string"><?php echo $this->tr('Hledat')?>:&nbsp;</label>
               <input class="form-control" id="search_string" type="text" size="35" name="q" value="<?php echo $this->searchString?>" />
               <button class="btn btn-primary" type="submit" value="1"><?php echo $this->tr('Hledat')?></button>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
<?php 
if($this->search === true) {
   $this->includeFile('tpl://results.phtml');
}
