<?php
$this->addFile('css://style.less');
$jQuery = new JsPlugin_JQuery();
$jQuery->addUIDraggable();
$this->addJsPlugin($jQuery);
$this->addJsPlugin(new JsPlugin_PrettyPhoto());
?>
<h1><?php
   echo $this->category()->getName();
   ?></h1>
<div class="content content-admin">
   <div id="product-category-select">
      <form method="get" id="form-filter-cat" action="<?php echo $this->link() ?>" class="ui-widget ui-state-default ui-cube-widget ui-widget-toolbox ui-corner-all">
         <label for="select-category"><?php ps($this->tr('Kategorie')) ?>:</label>
         <select id="select-category" name="idc"  onchange="this.form.submit();">
            <option value=""><?php ps($this->tr('Všechny')) ?></option>
            <?php foreach ($this->catsList as $c) { ?>
               <option
               <?php
               if (isset($_GET['idc']) && $_GET['idc'] == $c->getPK()) {
                  echo 'selected="selected"';
               }
               ?>
                  value="<?php echo $c->getPK() ?>"><?php ps($c->{Model_Category::COLUMN_NAME}) ?> - (<?php
                     ps($this->tr(array('%s produkt', '%s produkty', '%s produktů'), $c->products));
//               ps(sprintf(
//                  $this->tr('%s produktů'), $c->products));
                     ?>)</option>
            <?php } ?>
         </select>
      </form>
      <?php
      $this->moduleButtons = array(
          array(
              'link' => $this->link()->route('add'),
              'title' => $this->tr('Vytvořit nové zboží'),
              'icon' => 'add.png',
              'name' => $this->tr('Nové zboží'),
          ),
      );
      $this->includeTpl('modules/buttons.phtml', true);
      ?>
   </div>
   <form method="post" action="<?php echo $this->link() ?>" id="form-products-list">
      <table id="products-list" class="full-width cubecms-widget cubecms-table">
         <thead class="cubecms-header">
            <tr class="ui-widget-header">
               <th><input type="checkbox" id="select-all" /></th>
               <th style="width: 30px;">ID</th>
               <th colspan="2"><?php ps($this->tr('Zboží')) ?></th>
               <th style="width: 40px;"><?php ps($this->tr('Stav')) ?></th>
               <th><?php ps($this->tr('Množství')) ?></th>
               <th><?php ps($this->tr('Cena')) ?></th>
               <th style="width: 120px;"></th>
            </tr>
         </thead>
         <tbody class="cubecms-content">
            <?php
            if (!empty($this->products)) {
               foreach ($this->products as $p) {
                  $src = null;
                  $titleImg = $p->getTitleImage();
                  if ($titleImg) {
                     $src = Utils_Image::cache($titleImg->getUrl(), 100, round(100 / 4 * 3), true);
                     $srcBig = $titleImg->getUrl();
                  }
                  ?>
                  <tr class="cubecms-row product-row">
                     <td><input type="checkbox" name="product[<?php ps($p->getPK()) ?>]" class="product-mark" /></td>
                     <td class="text-center"><?php echo $p->getPK() ?></td>
                     <td class="text-center">
                        <?php if ($src) { ?>
                           <a href="<?php echo $srcBig ?>" rel="prettyPhoto" title="<?php ps($p->{Shop_Model_Product::COLUMN_NAME}) ?>"><img src="<?php echo $src ?>" alt="<?php ps($p->{Shop_Model_Product::COLUMN_NAME}) ?>" /></a>
                        <?php } ?>
                     </td>
                     <td>
                        <div>
                           <a href="<?php echo $this->link()->route('edit', array('urlkey' => $p->getUrlKey())) ?>">
                              <?php ps($p->{Shop_Model_Product::COLUMN_NAME}) ?>
                           </a>
                        </div>
                        <?php if ($p->{Shop_Model_Product::COLUMN_CODE}) { ?>
                           <div>
                              <strong><?php ps($this->tr('Kód produktu')) ?>: <?php ps($p->{Shop_Model_Product::COLUMN_CODE}) ?></strong>
                           </div>
                        <?php } ?>
                        <?php if ($p->{Model_Category::COLUMN_NAME}) { ?>
                           <div class="category-name">(
                              <?php $l = clone $this->link() ?>
                              <a href="<?php echo $l->clear()->category($p->{Model_Category::COLUMN_URLKEY}) ?>">
                                 <?php ps($p->{Model_Category::COLUMN_NAME}) ?>
                              </a>
                              )</div>
                        <?php } ?>
                        <?php if ($p->{Shop_Model_Product::COLUMN_MANUFACTURER}) { ?>
                           <div class="manufacturer-name">
                              <em><?php ps($p->{Shop_Model_Product::COLUMN_MANUFACTURER}) ?></em>
                           </div>
                        <?php } ?>
                     </td>
                     <td class="text-center">
                        <a href="<?php echo $this->link()->param('idp', $p->getPK())->param('action', 'changeState') ?>" title="<?php ps($this->tr('Změnit stav')) ?>">
                           <span class="icon icon-<?php echo $p->{Shop_Model_Product::COLUMN_ACTIVE} ? 'check-square' : 'square-o' ?>"></span></a>
                        <?php
                        $curDate = new DateTime();
                        $newEdnDate = new DateTime($p->{Shop_Model_Product::COLUMN_IS_NEW_TO_DATE});
                        $newEdnDate->setTime(23, 59, 59);
                        if ($newEdnDate > $curDate) {
                           echo '<span class="icon icon-star text-gold" title="' . $this->tr('Novinka!') . '"></span>';
                        }
                        ?>
                     </td>
                     <td class="text-right">
                        <?php
                        if ($p->{Shop_Model_Product::COLUMN_STOCK}) {
                           ps((float) $p->quantity . ' ' . $p->{Shop_Model_Product::COLUMN_UNIT});
                        } else {
                           ps('---');
                        }
                        ?>
                     </td>
                     <td class="price text-right">
                        <?php
                        if ($p->priceMax == null) {
                           echo Shop_Tools::getPriceOfProduct($p);
                        } else {
                           echo Shop_Tools::getFormatedPrice($p->priceMin, $p->{Shop_Model_Tax::COLUMN_VALUE})
                           . ' - ' . Shop_Tools::getFormatedPrice($p->priceMax, $p->{Shop_Model_Tax::COLUMN_VALUE});
                        }
                        ?>
                     </td>
                     <td class="actions">
                        <?php
                        $p->toolbox->setTemplate(Template_Toolbox2::TEMPLATE_INLINE);
                        echo $p->toolbox;
                        ?>    
                     </td>
                  </tr>
                  <?php
               }
            } else {
               ?>
               <tr class="cubecms-row cubecms-state-disable">
                  <td colspan="8"><?php ps($this->tr('Zboží nebylo nalezeno')) ?></td>
               </tr>
            <?php } ?>
         </tbody>
         <tfoot class="cubecms-widget-footer">
            <tr class="cubecms-row">
               <td colspan="8">
                  <?php echo $this->scrollComp ?>
               </td>
            </tr>
            <tr class="cubecms-row">
               <td colspan="8">
                  <?php ps($this->tr('Zaškrtnuté')) ?>:
                  <select name="list-action">
                     <option><?php ps($this->tr('Označené:')) ?></option>
                     <option value="activate"><?php ps($this->tr('Aktivovat')) ?></option>
                     <option value="deactivate"><?php ps($this->tr('Deaktivovat')) ?></option>
                     <optgroup label="<?php ps($this->tr('Přesunot do kateogrie')) ?>">
                        <?php foreach ($this->catsList as $c) { ?>
                           <option value="move_to_<?php echo $c->getPK() ?>"><?php ps($c->{Model_Category::COLUMN_NAME}) ?>
                              - (<?php ps($this->tr(array('%s produkt', '%s produkty', '%s produktů'), $c->products)); ?>)</option>
                        <?php } ?>
                     </optgroup>
                     <option value="delete"><?php ps($this->tr('Smazat')) ?></option>
                  </select>
               </td>
            </tr>
         </tfoot>
      </table>
   </form>
</div>
<script type="text/javascript">
   $(document).ready(function () {
      $("a[rel^='prettyPhoto']").prettyPhoto();

      $('.product-row').hover(function () {
         $(this).addClass('ui-state-hover');
      }, function () {
         $(this).removeClass('ui-state-hover');
      });

      $('.product-mark').change(function () {
         $(this).is(':checked') ? $(this).closest('tr').addClass('ui-state-highlight') : $(this).closest('tr').removeClass('ui-state-highlight');
      });

      $('select[name="list-action"]').change(function () {
         $(this).closest('form').submit();
      });

      $('form#form-products-list').submit(function () {
         // kontrola výběru
         if ($('input.product-mark:checked').length == 0) {
            alert('<?php ps($this->tr('Není vybráno žádné zboží!')) ?>');
            $(this).val($("option:first", $(this)).val());
            return false;
         }

         // delete má potvrzení
         if ($('select[name="list-action"]').val() == "delete") {
            return confirm('<?php ps($this->tr('Opravdu smazat označené produkty?')) ?>')
         }
      });

      $('#select-all').change(function () {
         if ($(this).is(':checked')) {
            $('form#form-products-list tbody input[type="checkbox"]').attr('checked', true);
         } else {
            $('form#form-products-list tbody input[type="checkbox"]').attr('checked', false);
         }
      });
   });
</script>