<?
if(empty($this->products)){
   return;
}
$this->includeFile('tpl://shopproductgeneral:panel.phtml');
return;

$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}?>
<div class="name"><?=$icon?><?ps($this->panelObj()->getName())?></div>
<?foreach ($this->products as $product) {
   $link = (string)$this->link()
      ->category($product->curlkey)
      ->route('detail', array('urlkey' => $product->{Shop_Model_Product::COLUMN_URLKEY}));

   $src = vve_image_cacher(Shop_Product_Controller::getImagesDir(true).$product->{Shop_Model_Product::COLUMN_IMAGE}, 100);
   ?>
<div class="content article">
   <div class="name">
      <a href="<?=$link?>" title="<?ps($product->{Shop_Model_Product::COLUMN_NAME})?>"
              ><?ps($product->{Shop_Model_Product::COLUMN_NAME})?></a>
   </div>
   <div>
      <a href="<?=$link?>" title="<?ps($product->{Shop_Model_Product::COLUMN_NAME})?>">
         <img src="<?=$src?>" alt="<?ps($product->{Shop_Model_Product::COLUMN_NAME})?>" />
      </a>
   </div>
   <div>
      <?ps($this->tr('Cena:')." ".Shop_Tools::getPriceOfProduct($product, $product->{Shop_Model_ProductCombinations::COLUMN_PRICE}, true))?>
   </div>
   <div class="link-more">
      <a href="<?=$link?>" title="<?ps($product->{Shop_Model_Product::COLUMN_NAME})?>"><?ps($this->tr('Více'))?></a>
   </div>
</div>
<?}?>
