<div class="action">
<h2><?=$this->action[Actions_Model_Detail::COLUMN_ACTION_LABEL]?></h2>
<p class="subLabel"><?=$this->action[Actions_Model_Detail::COLUMN_ACTION_TEXT_SHORT]?></p>
   <?if($this->sys()->rights()->isWritable()){?>
   <?=$this->_("Zveřejněno:")."&nbsp;".$this->_("od")." "
      .strftime("%x", $this->action['start_date'])."&nbsp;".$this->_("do")."&nbsp;"
      .strftime("%x", $this->action['stop_date'])?></span>
   <br />
   <?}?>
   <?if($this->action[Actions_Model_Detail::COLUMN_ACTION_IMAGE]){?>
   <img src="<?=$this->module()->getDir()->getDataDir().$this->action[Actions_Model_Detail::COLUMN_ACTION_IMAGE]?>"
        alt="image for action <?=$this->action[Actions_Model_Detail::COLUMN_ACTION_LABEL]?>"/>
   <?}?>
   <?=$this->action[Actions_Model_Detail::COLUMN_ACTION_TEXT]?>
<hr class="reseter" />
<?$this->includeTpl("buttonback.phtml", true, array('link' => $this->l()->article()));?>
<?if($this->sys()->rights()->isWritable()){
      $this->includeTplObj($this->toolbox);
   }?>
</div>