<?
$this->addPageTitle($this->_('Archiv'));
$this->addPageHeadline($this->_('Archiv'));

$jQuery = new JsPlugin_JQuery();
$jQuery->addWidgentAccordion();
$this->addJsPlugin($jQuery);

$model = new Actions_Model_List();
$actions = $model->getAllActions($this->category()->getId(), !$this->category()->getRights()->isWritable());

?>
<div>
   <p style="text-align: right">
      <a href="<?=$this->link()->route()?>" title="<?=$this->_('Seznam')?>"><?=$this->_('Seznam')?></a>
   </p>
   <div id="actionsArchiveList">
      <? $prevYear = null;
      while ($row = $actions->fetch()) {
         $year = date("Y", $row->{Actions_Model_Detail::COLUMN_DATE_START});
         if($year == $prevYear) continue;
         $prevYear = $year;?>
      <h2 class="actionYearLabel year<?=$year?>"><a href="#"><?=$year?></a></h2>
      <div>
         <table cellpadding="0" cellspacing="0">
               <?$curAct = $model->getActions($this->category()->getId(),
                       mktime(0, 0, 0, 1, 1, $year), mktime(23, 59, 59, 12, 31, $year),
                       !$this->category()->getRights()->isWritable());
               $prevMounth = null;
               while ($rowY = $curAct->fetch()) {
                  $class = null;
                  if(!$rowY->{Actions_Model_Detail::COLUMN_PUBLIC}) {
                     $class = 'nonPublicAction';
                  }
                  $startDate = strftime("%x", $rowY->{Actions_Model_Detail::COLUMN_DATE_START});
                  $stopDate = strftime("%x", $rowY->{Actions_Model_Detail::COLUMN_DATE_STOP});
                  $mounth = strftime("%B", $rowY->{Actions_Model_Detail::COLUMN_DATE_STOP});
                  $mounthNum = strftime("%Y_%m", $rowY->{Actions_Model_Detail::COLUMN_DATE_STOP});
                  if($mounth != $prevMounth) {
                     $prevMounth = $mounth;?>
            <tr>
               <td colspan="3"><a href="#" onclick="return showMonth(this,'.mounth_<?=$mounthNum?>');"
                                  title="<?=$this->_('zobraz')." ".$mounth?>">
                     <img src="<?=vve_get_tpl_file('buttons/expand2.gif',VVE_TPL_FILE_IMAGE)?>"
                          alt="expand" />&nbsp;<?=$mounth?></a></td>
            </tr>
                     <?}?>
            <tr class="mounth_<?=$mounthNum?>" style="display: none;">
               <td><span style="padding-left: 1em;"><?=$startDate?></span></td>
               <td>
                        <?if($startDate != $stopDate) {
                           print ("&nbsp;&mdash;&nbsp;");
                           print ($stopDate);
                        }?>
               </td>
               <td>
                  &nbsp;&nbsp;
                  <a href="<?=$this->link()->route('detail',
                                   array('urlkey' => $rowY->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
                     title="<?=$rowY->{Articles_Model_Detail::COLUMN_NAME}?>"
                     ><?print ($rowY->{Articles_Model_Detail::COLUMN_NAME});?></a>
               </td>
            </tr>
                  <?}?>
         </table>
      </div>
         <?}?>
   </div>
   <hr class="reseter" />
</div>
<script type="text/javascript">

   $(function() {
      $("#actionsArchiveList").accordion({
         collapsible: true,
         autoHeight: false,
         active: '.year<?=date('Y')?>'
      });
   });

   function showMonth(aObj, cls){
      //$(cls).toggle();
      $(cls).toggle(0,
      function(){
         if($(this).is(":hidden")){
            $(aObj).children("img").attr('src', 'images/buttons/expand2.gif');
         } else {
            $(aObj).children("img").attr('src', 'images/buttons/collapse2.gif');
         }
      }
   );
      return false;
   }
</script>
