<?php  // načtení detailu
$this->addPageTitle($this->action->{Actions_Model::COLUMN_NAME});
$image = null;
if ($this->action->{Actions_Model::COLUMN_IMAGE} != null) {
   $imgSrc = vve_image_cacher(vve_tpl_art_title_image($this->action->{Actions_Model::COLUMN_IMAGE}), 300, 225);
   $imgAlt = htmlspecialchars($this->action->{Actions_Model::COLUMN_NAME});
   $image = "<img src=\"$imgSrc\" alt=\"$imgAlt\" class=\"title-image image-left\" />";
}

?>
<h1><?php $this->includeFile('tpl://engine:headline/icon.phtml'); ps_lang($this->action->{Actions_Model::COLUMN_NAME})?></h1>
<div class="post">
   <?php if($this->action->{Actions_Model::COLUMN_SUBANME} != null) {?>
   <div class="text subname"><?php p_lang($this->action->{Actions_Model::COLUMN_SUBANME})?></div>
   <?php }?>
   <?php if($this->action->{Actions_Model::COLUMN_AUTHOR} != null) {?>
   <div class="text author"><?php p_lang($this->action->{Actions_Model::COLUMN_AUTHOR})?></div>
      <?php }?>
   <div class="text info">
      <?php 
      $startDate = vve_date("%x", new DateTime($this->action->{Actions_Model::COLUMN_DATE_START}));
      $stopDate = vve_date("%x", new DateTime($this->action->{Actions_Model::COLUMN_DATE_STOP}));
      print ($startDate);
      if($startDate != $stopDate AND $this->action->{Actions_Model::COLUMN_DATE_STOP} != null) {
         echo ("&nbsp;&mdash;&nbsp;");
         echo ($stopDate);
      }
      if($this->action->{Actions_Model::COLUMN_TIME} != '00:00:00'|null) {
         $time = new DateTime($this->action->{Actions_Model::COLUMN_TIME});
         echo (",&nbsp;".$time->format("G:i"));
      }
      if($this->action->{Actions_Model::COLUMN_PLACE} != null) {
         echo ',&nbsp;'.$this->action->{Actions_Model::COLUMN_PLACE};
      }
      if((int)$this->action->{Actions_Model::COLUMN_PRICE} != null|0) {
         printf(',&nbsp;'.strtolower($this->tr('Vstupné: %d Kč')),$this->action->{Actions_Model::COLUMN_PRICE});
      }
      if((int)$this->action->{Actions_Model::COLUMN_PREPRICE} != null|0) {
         printf(',&nbsp;'.strtolower($this->tr('V předprodeji: %d Kč')),$this->action->{Actions_Model::COLUMN_PREPRICE});
      }
      ?>
   </div>
   <?php if($this->action->{Actions_Model::COLUMN_NOTE} != null) {?>
   <div class="text note"><?php p_lang($this->action->{Actions_Model::COLUMN_NOTE})?></div>
      <?php }?>
   <?php if($image != null) {?><div class="title-image"><?php echo $image;?></div><?php }?>
   <div class="text">
   <?php p_lang($this->action->{Actions_Model::COLUMN_TEXT})?>
   </div>
   <hr class="reseter" />
   <?php 
   echo $this->dForm;
   
   if(!$this->category()->getParam(Actions_Controller::PARAM_SHOW_EVENT_DIRECTLY, false) && $this->isPreview == null){
      $this->includeTpl("buttonback.phtml", true, array('text' => $this->tr('Zpět na seznam')));
   }
   ?>
   <?php 
   $this->includeTpl('articletools.phtml', true, array(
           'lastEditTime' => $this->action->{Actions_Model::COLUMN_CHANGED},
           'lastEditUser' => $this->action->{Model_Users::COLUMN_USERNAME},
           'linkToPdf' => $this->link()->route('detailExport',array('output' => 'pdf')),
           'shares' => array('url' => $this->link(), 'title' => $this->action->{Actions_Model::COLUMN_NAME})));?>

   <?php 
   echo $this->toolbox;
   ?>
</div>
