<?
$this->addCssFile("style.css");
// do titulku
if($this->edit) {
   $this->addPageTitle($this->_('úprava akce'));
   $this->addPageTitle($this->catName);
   $h1 = $this->_('úprava akce').' '.$this->catName;
} else {
   $this->addPageTitle($this->_('přidání akce'));
   $h1 = $this->_('přidání akce');
}
// donastavení formuláře
$this->form->text->html()->setAttrib('cols', 80)->setAttrib('rows', 30)->addClass("mceEditor");

$tinymce = new JsPlugin_TinyMce();
$tinymce->setCfgParam('theme', 'full');
$this->addJsPlugin($tinymce);

$jQuery = new JsPlugin_JQuery();
$jQuery->addUIDatepicker();
$this->addJsPlugin($jQuery);

?>
<h1><?=$h1?></h1>
<div class="main-content-form-edit" id="editArticleForm">
   <?print($this->form);?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         $.datepicker.setDefaults(['<?=Locales::getLang()?>'] ) ;
         $("input[name=action_date_start]").datepicker();
         $("input[name=action_date_stop]").datepicker();
      });
      /* ]]> */
   </script>
</div>
<?$this->includeTpl('buttonback.phtml', true);?>
