<?php 
$this->addCssFile("style.css");
// do titulku
if($this->edit) {
   $this->addPageTitle($this->tr('úprava události'));
   $this->addPageTitle($this->action->{Actions_Model::COLUMN_NAME});
   $h1 = sprintf( $this->tr('úprava události "%s"'), $this->action->{Actions_Model::COLUMN_NAME});
} else {
   $this->addPageTitle($this->tr('přidání události'));
   $h1 = $this->tr('přidání události');
}
// donastavení formuláře
$this->form->send->cancel->html()->addClass('cancel')->setAttrib('onclick', 'return confirm(\''.$this->tr('Opravdu zrušit změny?').'\')');
$this->form->send->preview->html()->addClass('exclusive');
$this->form->name->html()->setAttrib('size', 60);
$this->form->subname->html()->setAttrib('size', 60);
$this->form->author->html()->setAttrib('size', 60);
$this->form->place->html()->setAttrib('size', 60);
$this->form->note->html()->setAttrib('size', 60);
$this->form->urlkey->html()->setAttrib('size', 60);
$this->form->text->html()->setAttrib('cols', 80)->setAttrib('rows', 30);

$jQuery = new JsPlugin_JQuery();
$jQuery->addUIDatepicker();
$jQuery->addUITimepicker();
$this->addJsPlugin($jQuery);

?>
<h1><?php echo $h1?></h1>
<div class="main-content-form-edit" id="editArticleForm">
   <?php if($this->previewLink){?>
   <div class="message message-info message-warning"><?php 
      printf($this->tr('Máte již vytvořenu starší verzi dokumentu. Chcete ji <a href="%s"><strong>otevřít</strong></a> nebo <a href="%s"><strong>zrušit</strong></a>?'),
         $this->previewLink, $this->previewLinkCancel);
      ?></div>
   <?php }
   echo($this->form);
   $this->includeFile('tpl://engine:parts/seltitleimage.phtml');
   ?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         $.datepicker.setDefaults( $.datepicker.regional[ "<?php echo Locales::getLang()?>" ] );
         var dates = $('input#action_date_start_1, input#action_date_stop_1').datepicker({
            showButtonPanel: true, showOtherMonths: true, selectOtherMonths: true,
            onSelect: function( selectedDate ) {
               var option = this.id == "action_date_start_1" ? "minDate" : "maxDate",
               instance = $( this ).data( "datepicker" ),
               date = $.datepicker.parseDate(
               instance.settings.dateFormat ||
               $.datepicker._defaults.dateFormat,
                  selectedDate, instance.settings );
               dates.not( this ).datepicker( "option", option, date );
            }
         });
         $('input#action_formShowToDate_1').datepicker({
            showButtonPanel: true, showOtherMonths: true, selectOtherMonths: true
         });
         $('input#action_time_1').timepicker({ stepMinute: 5 });
      });
      /* ]]> */
   </script>
</div>
