<?php 
$this->addPageTitle(vve_date("%x", $this->dateFrom).' - '.vve_date("%x", $this->dateTo));
echo $this->toolbox; // tolbox pro přidání
?>
<h1><?php $this->includeFile('tpl://engine:headline/icon.phtml'); echo $this->category->getName().' - '.vve_date("%x", $this->dateFrom).' - '.vve_date("%x", $this->dateTo)?></h1>
<div class="main-content-list">
   <?php 
   if($this->text != false) {?>
   <div class="text">
         <?php 
         echo $this->text->{Text_Model_Detail::COLUMN_TEXT};
         echo $this->toolboxText; // toolbox pro úpravu úvodního textu
         ?>
   </div>
      <?php }?>

   <div class="tools">
      <a href="<?php echo $this->link()->route('archive')?>" title="<?php echo $this->tr('Archiv')?>"><?php echo $this->tr('Archiv')?></a>
   </div>
   <?php if(!empty ($this->actions)){?>
   <div class="post-list events-list">
   <?php 
   foreach ($this->actions as $row) {
      if($row->{Actions_Model::COLUMN_PUBLIC}) $class = "";
      else $class = 'main-content-no-public';
      $subLabel = $row->{Actions_Model::COLUMN_NAME};
      if($row->{Actions_Model::COLUMN_SUBANME} != null) {
         $subLabel = '<span class="">'.$row->{Actions_Model::COLUMN_SUBANME}.'</span><br />'.$subLabel;
      }
      
      $image = null;
      if ($row->{Actions_Model::COLUMN_IMAGE} != null) {
         $imgSrc = vve_image_cacher(vve_tpl_art_title_image($row->{Actions_Model::COLUMN_IMAGE}), 300, 225);
         $imgAlt = htmlspecialchars($row->{Actions_Model::COLUMN_NAME});
         $image = "<img src=\"$imgSrc\" alt=\"$imgAlt\" class=\"title-image image-left\" />";
      }

      ?><div class="post event <?php echo $class?>">
      <h2><a href="<?php echo $this->link()->route('detail', array('urlkey' => $row->{Actions_Model::COLUMN_URLKEY}))?>"
             title="<?php echo $row->{Actions_Model::COLUMN_NAME}?>"
             ><?php echo $subLabel?></a><?php 
            if($this->category()->getRights()->isControll()){
               echo '&nbsp;'.langsImages($row->{Actions_Model::COLUMN_URLKEY});
            }
            ?></h2>
            <?php if($row->{Actions_Model::COLUMN_AUTHOR} != null) {?>
      <div class="text author">
               <?php echo $row->{Actions_Model::COLUMN_AUTHOR}?>
      </div>
            <?php }?>
      <div class="text info">
            <?php 
            $startDate = vve_date("%x", new DateTime($row->{Actions_Model::COLUMN_DATE_START}));
            $stopDate = vve_date("%x", new DateTime($row->{Actions_Model::COLUMN_DATE_STOP}));
            echo ($startDate);
            if($startDate != $stopDate AND $row->{Actions_Model::COLUMN_DATE_STOP} != null) {
               echo ("&nbsp;&mdash;&nbsp;");
               echo ($stopDate);
            }
            if($row->{Actions_Model::COLUMN_TIME} != null) {
               $time = new DateTime($row->{Actions_Model::COLUMN_TIME});
               echo (",&nbsp;".$time->format("G:i"));
            }
            if($row->{Actions_Model::COLUMN_PLACE} != null) {
               echo ',&nbsp;'.$row->{Actions_Model::COLUMN_PLACE};
            }
            if((int)$row->{Actions_Model::COLUMN_PRICE} != null|0) {
               printf(',&nbsp;'.strtolower($this->tr('Vstupné: %d Kč')),$row->{Actions_Model::COLUMN_PRICE});
            }
            if((int)$row->{Actions_Model::COLUMN_PREPRICE} != null|0) {
               printf(',&nbsp;'.strtolower($this->tr('V předprodeji: %d Kč')),$row->{Actions_Model::COLUMN_PREPRICE});
            }
            ?>
      </div>
         <?php if($row->{Actions_Model::COLUMN_NOTE} != null) {?>
      <div class="text note">
          <?php echo $row->{Actions_Model::COLUMN_NOTE}?>
      </div>
            <?php }?>
      <?php if($image != null) {?><div class="title-image"><?php echo $image?></div><?php }?>
      <div class="text">
            <?php echo vve_tpl_xhtml_cut(strip_tags($row->{Actions_Model::COLUMN_TEXT},VVE_SHORT_TEXT_TAGS), 600);?>
      </div>
      <p class="mlink-more">
         <a href="<?php echo $this->link()->route('detail', array('urlkey' => $row->{Actions_Model::COLUMN_URLKEY}))?>"
            title="<?php echo $this->tr('Více')?>"><?php echo $this->tr('Více')?></a>
      </p>
      <hr class="reseter"/>
      </div>
      <?php }
      ?>
   </div>
   <?php 
   } else if($this->category()->getParam(Actions_Controller::PARAM_SHOW_EVENT_DIRECTLY, false)) {?>
      <div class="text"><?php echo $this->tr('Není žádná aktuální nebo nadcházející událost')?></div> 
   <?php } 
   
   if(!$this->category()->getParam(Actions_Controller::PARAM_SHOW_EVENT_DIRECTLY, false)){?>
     &laquo;&nbsp;<a href="<?php echo $this->linkBack?>" title="<?php echo $this->linkBackLabel?>"
      ><?php echo $this->linkBackLabel?></a>&nbsp;&brvbar;&nbsp;<a
      href="<?php echo $this->linkNext?>" title="<?php echo $this->linkNextLabel?>"><?php echo $this->linkNextLabel?></a>&nbsp;&raquo;
   <?php }
   // rss ikony
//    $feeds = new Component_Feed();
//    $feeds->setConfig('feedLink', $this->link()->clear());
//    echo $feeds;
   ?>
</div>