<?
$this->addPageTitle(vve_date("%x", $this->dateFrom).' - '.vve_date("%x", $this->dateTo));
echo $this->toolbox; // tolbox pro přidání
?>
<h1><?$this->includeFile('tpl://engine:headline/icon.phtml'); echo $this->category->getName().' - '.vve_date("%x", $this->dateFrom).' - '.vve_date("%x", $this->dateTo)?></h1>
<div class="main-content-list">
   <?
   if($this->text != false) {?>
   <div class="main-content-text">
         <?
         echo $this->text->{Text_Model_Detail::COLUMN_TEXT};
         echo $this->toolboxText; // toolbox pro úpravu úvodního textu
         ?>
   </div>
      <?}?>

   <div class="main-content-tools">
      <a href="<?=$this->link()->route('archive')?>" title="<?=$this->tr('Archiv')?>"><?=$this->tr('Archiv')?></a>
   </div>

   <div class="main-content-list-records">
   <?while ($row = $this->actions->fetch()) {
      if($row->{Actions_Model_Detail::COLUMN_PUBLIC}) $class = "";
      else $class = 'main-content-no-public';
      $subLabel = $row->{Actions_Model_Detail::COLUMN_NAME};
      if($row->{Actions_Model_Detail::COLUMN_SUBANME} != null) {
         $subLabel = '<span class="">'.$row->{Actions_Model_Detail::COLUMN_SUBANME}.'</span><br />'.$subLabel;
      }

      ?><div class="main-content-list-record <?=$class?>">
      <h2><a href="<?=$this->link()->route('detail', array('urlkey' => $row->{Actions_Model_Detail::COLUMN_URLKEY}))?>"
             title="<?=$row->{Actions_Model_Detail::COLUMN_NAME}?>"
             ><?=$subLabel?></a><?
            if($this->category()->getRights()->isControll()){
               echo '&nbsp;'.langsImages($row->{Actions_Model_Detail::COLUMN_URLKEY});
            }
            ?></h2>
            <?if($row->{Actions_Model_Detail::COLUMN_AUTHOR} != null) {?>
      <div class="main-content-text">
               <?=$row->{Actions_Model_Detail::COLUMN_AUTHOR}?>
      </div>
            <?}?>
      <div class="main-content-text">
            <?
            $startDate = vve_date("%x", new DateTime($row->{Actions_Model_Detail::COLUMN_DATE_START}));
            $stopDate = vve_date("%x", new DateTime($row->{Actions_Model_Detail::COLUMN_DATE_STOP}));
            echo ($startDate);
            if($startDate != $stopDate AND $row->{Actions_Model_Detail::COLUMN_DATE_STOP} != null) {
               echo ("&nbsp;&mdash;&nbsp;");
               echo ($stopDate);
            }
            if($row->{Actions_Model_Detail::COLUMN_TIME} != null) {
               $time = new DateTime($row->{Actions_Model_Detail::COLUMN_TIME});
               echo (",&nbsp;".$time->format("G:i"));
            }
            if($row->{Actions_Model_Detail::COLUMN_PLACE} != null) {
               echo ',&nbsp;'.$row->{Actions_Model_Detail::COLUMN_PLACE};
            }
            if((int)$row->{Actions_Model_Detail::COLUMN_PRICE} != null|0) {
               printf(',&nbsp;'.strtolower($this->tr('Vstupné: %d Kč')),$row->{Actions_Model_Detail::COLUMN_PRICE});
            }
            if((int)$row->{Actions_Model_Detail::COLUMN_PREPRICE} != null|0) {
               printf(',&nbsp;'.strtolower($this->tr('V předprodeji: %d Kč')),$row->{Actions_Model_Detail::COLUMN_PREPRICE});
            }
            ?>
      </div>
         <?if($row->{Actions_Model_Detail::COLUMN_NOTE} != null) {?>
      <div class="main-content-text">
          <?=$row->{Actions_Model_Detail::COLUMN_NOTE}?>
      </div>
            <?}?>
      <?if($row->{Actions_Model_Detail::COLUMN_IMAGE} != null) {?>
         <div class="main-content-image">
            <img src="<?=vve_tpl_art_title_image($row->{Actions_Model_Detail::COLUMN_IMAGE})?>" alt="<?ps($row->{Actions_Model_Detail::COLUMN_NAME})?>" />
         </div>
      <?}?>
      <div class="main-content-text">
            <?=vve_tpl_xhtml_cut(strip_tags($row->{Actions_Model_Detail::COLUMN_TEXT},VVE_SHORT_TEXT_TAGS), 600);?>
      </div>
      <p class="main-content-link-more">
         <a href="<?=$this->link()->route('detail', array('urlkey' => $row->{Actions_Model_Detail::COLUMN_URLKEY}))?>"
            title="<?=$this->tr('Více')?>"><?=$this->tr('Více')?></a>
      </p>
      <hr class="reseter"/>
      </div>
      <?}
      ?>
   </div>
   &laquo;&nbsp;<a href="<?=$this->linkBack?>" title="<?=$this->linkBackLabel?>"
     ><?=$this->linkBackLabel?></a>&nbsp;&brvbar;&nbsp;<a
     href="<?=$this->linkNext?>" title="<?=$this->linkNextLabel?>"><?=$this->linkNextLabel?></a>&nbsp;&raquo;
   <br/>
   <br/>
   <?
   // rss ikony
   $feeds = new Component_Feed();
   $feeds->setConfig('feedLink', $this->link()->clear());
   echo $feeds;
   ?>
</div>