<?//<desc>Panel s aktuální akci</desc>
if($this->action != null) {
$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
if($this->rssLink != null){?>
<a style="float: right" href="<?=$this->rssLink?>" title="rss"><img src="<?=vve_get_tpl_file('icons/rss-icon.png', VVE_TPL_FILE_IMAGE)?>" alt="rss" /></a>
<?}?>
<p class="panelLabel"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->panelObj()->getName())?>"><?=$this->panelObj()->getName()?></a></p>
<div class="panelActions" style="<?=$backImg?>">
      <?// podnadpis
      if($this->action->{Actions_Model_Detail::COLUMN_SUBANME} != null){
         print(new Html_Element('p', $this->action->{Actions_Model_Detail::COLUMN_SUBANME}));
      }?>
      <p><a href="<?=$this->link()->route('detail', array('urlkey' => $this->action->{Actions_Model_Detail::COLUMN_URLKEY}))?>"
      title="<?=$this->action->{Actions_Model_Detail::COLUMN_NAME}?>"
      ><?=$this->action->{Actions_Model_Detail::COLUMN_NAME}?></a></p>
      <?// autor
      if($this->action->{Actions_Model_Detail::COLUMN_AUTHOR} != null){
         print(new Html_Element('p', $this->action->{Actions_Model_Detail::COLUMN_AUTHOR}));
      }
      // čas a datum
      $startDate = vve_date("%x", new DateTime($this->action->{Actions_Model_Detail::COLUMN_DATE_START}));
      $stopDate = vve_date("%x", new DateTime($this->action->{Actions_Model_Detail::COLUMN_DATE_STOP}));
      $timeStr = $startDate;
      if($startDate != $stopDate AND $this->action->{Actions_Model_Detail::COLUMN_DATE_STOP} != null) {
         $timeStr .= " - ".$stopDate;
      }
      if($this->action->{Actions_Model_Detail::COLUMN_TIME} != NULL) {
         $timeStr .= ', '.preg_replace("/:[0-9]+$/", null, $this->action->{Actions_Model_Detail::COLUMN_TIME});
      }
      print(new Html_Element('p', $timeStr));
      if($this->action->{Actions_Model_Detail::COLUMN_IMAGE} != null){
      ?>
      <p class="image" style="width: 100%; overflow: hidden;">
         <img style="width: 100%;"
            src="<?=$this->datadir.$this->action->{Actions_Model_Detail::COLUMN_IMAGE}?>"
              alt="<?=$this->tr('titulní obrázek akce').' '
                 .htmlspecialchars($this->action->{Actions_Model_Detail::COLUMN_NAME})?>"/>
      </p>
      <?}
      $linkNext = '... <a href="'.$this->link()->route('detail', 
              array('urlkey' => $this->action->{Actions_Model_Detail::COLUMN_URLKEY}))
              .'" title="'.$this->action->{Actions_Model_Detail::COLUMN_NAME}.'">(dále)</a>';
      print('<p>'.vve_tpl_truncate($this->action->{Actions_Model_Detail::COLUMN_TEXT_CLEAR},140,$linkNext).'</p>');

      if ($this->action->{Actions_Model_Detail::COLUMN_PRICE} != null
         AND $this->action->{Actions_Model_Detail::COLUMN_PREPRICE} != null) {
         printf('<p>'.$this->tr('cena: <span title="Na místě">%s</span>&nbsp;/&nbsp;<span title="V předprodeji">%s</span> Kč').'</p>', 
                 $this->action->{Actions_Model_Detail::COLUMN_PRICE},
                         $this->action->{Actions_Model_Detail::COLUMN_PREPRICE});
      } else if($this->action->{Actions_Model_Detail::COLUMN_PREPRICE} != null) {
         printf('<p>'.$this->tr('cena: <span title="V předporodeji">%s</span> Kč').'</p>', 
                 $this->action->{Actions_Model_Detail::COLUMN_PREPRICE});
      } else if($this->action->{Actions_Model_Detail::COLUMN_PRICE} != null) {
         printf('<p>'.$this->tr('cena: <span title="Na místě">%s</span> Kč').'</p>', 
                 $this->action->{Actions_Model_Detail::COLUMN_PRICE});
      }
      ?>

</div>
<p class="panelLinkMore">
   <a href="<?=$this->link()?>"
      title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->tr('Více')?></a>
</p>
<?}?>