<?php  // načtení detailu
$this->addFile("css://style.less");
$this->addFile("js://custommenu.js");
$jq = new JsPlugin_JQuery();
$jq->addUISortable();
$jq->addUIDialog();
$this->addJsPlugin($jq);

?>
<h1><?php ps($this->category()->getName());?></h1>
<div class="content-admin clearfix" id="custom-menu-list">
   <?php 
   if(!empty($this->boxes)){
      foreach ($this->boxes as $key => $box) {?>
      <div class="menu-box">
         <h2><?php ps($box['name'])?></h2>
         <table class="full-width ui-cube ui-cube-widget ui-table-widget">
            <thead>
               <tr class="ui-widget-header">
                  <td></td>
                  <th><?php ps($this->tr('Název'))?></th>
                  <th><?php ps($this->tr('Odkaz'))?></th>
                  <td></td>
               </tr>
            </thead>
            <tfoot>
               <tr class="ui-widget-content">
                  <td colspan="4">
                     <button onclick="CustomMenu.addCustomMenuItem('<?php echo $key?>');"><?php ps($this->tr('Přidat'))?></button>
                  </td>
               </tr>
            </tfoot>
            <tbody>
               <?php 
               if(!empty($box['items'])){
                  foreach ($box['items'] as $item) {?>
                  <tr id="custom-menu-item-<?php echo $item->getPK()?>" class="custom-menu-item ui-widget-content"
                      data-id="<?php echo $item->getPK()?>"
                      data-name='<?php echo htmlentities(json_encode($item->{CustomMenu_Model_Items::COLUMN_NAME}->getArray()))?>'
                      data-box='<?php echo $item->{CustomMenu_Model_Items::COLUMN_BOX}?>'
                      data-active="<?php echo $item->{CustomMenu_Model_Items::COLUMN_ACTIVE} ? "true" : "false" ?>"
                      data-link="<?php echo $item->{CustomMenu_Model_Items::COLUMN_LINK}?>"
                      data-idcat="<?php echo $item->{CustomMenu_Model_Items::COLUMN_ID_CATEGORY}?>"
                      data-newwin="<?php echo $item->{CustomMenu_Model_Items::COLUMN_NEW_WINDOW} ? "true" : "false" ?>"
                          >
                     <td class="move"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span></td>
                     <td class="name"><?php ps($item->{CustomMenu_Model_Items::COLUMN_NAME})?></td>
                     <td class="link">
                        <?php 
                        $href = $item->{CustomMenu_Model_Items::COLUMN_LINK} != null ? $item->{CustomMenu_Model_Items::COLUMN_LINK} : $item->catLink;
                        ?>
                        <a href="<?php echo $href?>" title="<?php ps($href);?>"><?php echo(vve_tpl_xhtml_cut($href, 30))?></a>
                     </td>
                     <td class="actions">
                        <?php $icon = $item->{CustomMenu_Model_Items::COLUMN_ACTIVE} ? 'eye' : "eye-slash";?>
                        <a href="<?php echo $this->link()->route('edit')->param('action', 'changeState')->param('id', $item->getPK())?>"><span class="icon icon-<?php echo $icon?>"></span></a>
                        <a href="<?php echo $this->link()->param('action', 'edit')->param('id', $item->getPK())?>"
                           onclick="CustomMenu.editCustomMenuItem(<?php echo $item->getPK()?>); return false;"
                           class="button-edit-param"><span class="icon icon-pencil"></span></a>
                        <a href="<?php echo $this->link()->route('edit')->param('action', 'delete')->param('id', $item->getPK())?>"
                           onclick="CustomMenu.deleteCustomMenuItem(<?php echo $item->getPK()?>);"
                           class="button-delete-param"><span class="icon icon-times"></span></a>
                     </td>
                  </tr>
                  <?php 
                  }
               } else {?>
                  <tr class="ui-widget-content"><td colspan="4"><?php ps($this->tr('Žádná položka není přidána'))?></td></tr>
               <?php }?>
            </tbody>
         </table>
      </div>
      <?php }
   } else {?>
      <div class="message message-warning">
         <?php ps($this->tr('Pro tuto šablonu není definováno žádné menu'))?>
      </div>
   <?php }?>
   <div id="form-edit-menu-item">
      <?php echo $this->form;?>
   </div>
   <script type="text/javascript">
      $(document).ready(function(){
         CustomMenu.init({
            editUrl : '<?php echo $this->link()->route('edit')?>',
            dialogTitle : {  add : '<?php ps($this->tr('Přidání položky'))?>', edit: '<?php ps($this->tr('Úprava položky'))?>'}
         });
      });
   </script>
</div>

