<h1><?php ps($this->tr('Výběr nového bloku')); ?></h1>
<div class="row">
   <div class="col-lg-12 custom-blocks-select ">
      <div class="custom-block cubecms-widget cubecms-list-blocks">
<?php foreach ($this->blocks as $block) { 
   ?>
      <div class="custom-block cubecms-list-block">
         <div class="header">
            <h2><a href="<?php echo $block['url']?>"><?php ps($block['name']); ?></a></h2>
         </div>
         <?php if($block['img']){?>
         <div class="content">
            <a href="<?php echo $block['url']?>"><img src="<?php echo Utils_Image::cache($block['img'], 1280);?>" class="img-responsive" /></a>
         </div>
         <?php }?>
         <div class="footer clearfix">
            <a href="<?php echo $block['url']?>" class="btn btn-success right-box"><?php ps($this->tr('Vybrat')); ?> <span class="icon icon-chevron-right"></span></a>
         </div>
      </div>
<?php } ?>
      </div>
      <a href="<?php echo $this->link()->route()?>" class="btn btn-danger"><span class="icon icon-chevron-left"></span> <?php ps($this->tr('Zpět')); ?></a>
   </div>
</div>