<?php 
echo $this->toolbox;
$h1 = $this->tr('Přidání události');

if($this->event != null){
   $h1 = sprintf($this->tr('Úprava události "%s"'), (string)$this->event->{Events_Model::COL_NAME} );
}
Template_Core::setPageTitle($h1);

$jq = new JsPlugin_JQuery();
$jq->addUIDatepicker();
$jq->addUITimepicker();
$this->addJsPlugin($jq);
?>
<h1><?php ps($h1)?></h1>
<div class="form-edit">
   <?php 
   echo $this->form;
   ?>
   <script type="text/javascript">
   $(document).ready(function(){
      $('input[name="editevent_timefrom"]').timepicker({ stepMinute: 5, hour: 15 });
      $('input[name="editevent_timeto"]').timepicker({ stepMinute: 5, hour: 15 });
      $('input[name="editevent_datefrom"]').datepicker({  });
      $('input[name="editevent_dateto"]').datepicker({ });
   });
   </script>
</div>