<?php 
echo $this->toolbox;
$h1 = $this->tr('Přidání kategorie událostí');

if($this->eventCat != null){
   $h1 = sprintf($this->tr('Úprava kategorie %s'), $this->eventCat->{Events_Model_Categories::COL_NAME} );
}
Template_Core::setPageTitle($h1);
?>
<h1><?php ps($h1)?></h1>
<div class="form-edit">
   <?php 
   echo $this->form;
   ?>
   <?php 
   $this->addJsPlugin(new JsPlugin_JQueryDropDown());
   ?>
   <script type="text/javascript">
      $(document).ready(function(){
         $('select[name="editcat_imageSelect"] option').each(function(){
            $(this).attr('title', '<?php echo $this->category()->getModule()->getDataDir(true)?>cats/'+$(this).attr('value'));
         });
         $('select[name="editcat_imageSelect"]').msDropDown({
            visibleRows:5,rowHeight:23
         });
      });
   </script>
   <style type="text/css">
      .dd .ddTitle span.ddTitleText img, .dd .ddChild a img { height:16px; }
   </style>
</div>