<?php
echo $this->toolbox;
$this->addFile('css://style.css');
$h1 = $this->tr('Seznam událostí');
Template_Core::addPageTitle($h1);

$this->addJsPlugin(new JsPlugin_JQueryCSS());
$jq = new JsPlugin_JQuery();
$jq->addUIDatepicker();
$this->addJsPlugin($jq);

function getParam($name, $cmp, $print)
{
   if (isset($_GET[$name])) {
      
   }
}

$showFFrom = false;
if (isset($_GET['dateFrom']) || isset($_GET['dateTo']) || isset($_GET['cat']) || isset($_GET['contain']) || isset($_GET['onlyPublicAdd'])) {
   $showFFrom = true;
}
?>
<h1><?php ps($h1) ?></h1>
<div class="form-edit">

   <?php
   $this->moduleButtons = array(
       array(
           'link' => $this->link()->route('addEvent'),
           'title' => $this->tr('Přidat novou událost'),
           'icon' => Template_Toolbox2::ICON_ADD,
           'name' => $this->tr('Přidat novou událost'),
       ),
       array(
           'id' => 'buttonShowFilter',
           'link' => $this->link() . '#filter',
           'title' => $this->tr('Zobrazit filtraci'),
           'icon' => 'search',
           'name' => $this->tr('Filtrace') . ($showFFrom ? ' (zapnuta)' : ' (vypnuta)'),
       ),
   );
   $this->includeTpl('modules/buttons.phtml', true);
   ?>
   <form id="formFilter" action="<?php echo $this->link() ?>" method="get" class="form-horizontal" style="<?php if (!$showFFrom) echo 'display: none;'; ?>">
      <div class="form-group">
         <label for="dateFrom" class="col-sm-2 control-label"><?php echo $this->tr('Od') ?>:</label>
         <div class="col-sm-10">
            <input name="dateFrom" value="<?php echo vve_date("%x", $this->dateFrom) ?>" type="text" id="dateFrom" class="form-control"  />
         </div>
      </div>
      <div class="form-group">
         <label for="dateTo" class="col-sm-2 control-label"><?php echo $this->tr('Do') ?>:</label>
         <div class="col-sm-10">
            <input name="dateTo" value="<?php echo vve_date("%x", $this->dateTo) ?>" type="text" id="dateTo" class="form-control" />
         </div>
      </div>
      <div class="form-group">
         <label for="contain"  class="col-sm-2 control-label"><?php echo $this->tr('Název') ?>:</label>
         <div class="col-sm-10">
            <input name="contain" value="<?php if (isset($_GET['contain'])) echo $_GET['contain'] ?>" type="text" id="contain" class="form-control" />
         </div>
      </div>
      <?php if ($this->isControll) { ?>
         <div class="form-group">
            <label for="catSelect" class="col-sm-2 control-label"><?php echo $this->tr('Kategorie') ?>:</label>
            <div class="col-sm-10">
               <select name="cat" id="catSelect" class="form-control">
                  <option value=""><?php echo $this->tr('vše') ?></option>
                  <?php foreach ($this->cats as $cat) { ?>
                     <option <?php
                     if (isset($_GET['cat']) && $_GET['cat'] == $cat->{Events_Model_Categories::COL_ID}) {
                        echo 'selected="selected"';
                     }
                     ?> 
                        value="<?php echo $cat->{Events_Model_Categories::COL_ID} ?>"><?php ps($cat->{Events_Model_Categories::COL_NAME}) ?></option>      
                     <?php } ?>
               </select>
            </div>
         </div>
         <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
               <div class="checkbox">
                  <label >
                     <input name="onlyPublicAdd" type="checkbox" id="onlyPublicAdd" <?php if (isset($_GET['onlyPublicAdd']) && $_GET['onlyPublicAdd'] == "on") echo 'checked="checked"' ?> />
                     <?php echo $this->tr('Pouze veřejně přidané') ?></label>
               </div>
            </div>
         </div>
      <?php } ?>

      <div class="form-group">
         <div class="col-sm-offset-2 col-sm-10">
            <input value="<?php echo $this->tr('Filtrovat') ?>" type="submit" />
            <input value="<?php echo $this->tr('Zrušit filtraci') ?>" type="button" id="buttonHideFilter" 
                   onclick="window.location = '<?php echo $this->link()->rmParam(array('dateFrom', 'dateTo', 'contain', 'cat', 'onlyPublicAdd')) ?>';"/>
         </div>
      </div>
      <?php if (isset($_GET['token'])) { ?><input type="hidden" name="token" value="<?php echo $_GET['token'] ?>" /><?php } ?>
   </form>
   <script type="text/javascript">
      $(document).ready(function () {
         var dates = $('input#dateFrom, input#dateTo').datepicker({
            showButtonPanel: true,
            showOtherMonths: true,
            selectOtherMonths: true,
            onSelect: function (selectedDate) {
               var option = this.id == "dateFrom" ? "minDate" : "maxDate",
                       instance = $(this).data("datepicker"),
                       date = $.datepicker.parseDate(
                               instance.settings.dateFormat ||
                               $.datepicker._defaults.dateFormat,
                               selectedDate, instance.settings);
               dates.not(this).datepicker("option", option, date);
            }
         });
         $('#buttonShowFilter').click(function () {
            console.log($('#formFilter').is(':hidden'));
            if ($('#formFilter').is(':hidden')) {
               $('#formFilter').slideDown('fast');
            } else {
               $('#formFilter').slideUp('fast');
            }
            return false;
         });
      });
   </script>
   <?php if (!empty($this->events)) { ?>
      <?php foreach ($this->events as $cat) { ?>

         <div class="events-list-in-cat">
            <h3><?php echo $cat['cat']->{Events_Model_Categories::COL_NAME} ?></h3>
            <?php
            foreach ($cat['events'] as $event) {
               $state = $event->{Events_Model::COL_PUBLIC} != true ? "ui-state-disabled" : null;
               ?>
               <table class="cubecms-widget cubecms-table full-width event-event-item <?php if ($event->{Events_Model::COL_PUBLIC_ADD} == true) { ?>event-public-add<?php } ?>">
                  <tr class="cubecms-header">
                     <th class="event-name" colspan="2">
                        <input type="checkbox" name="event_selected" value="<?php echo $event->{Events_Model::COL_ID} ?>" />
                        <?php if ($event->{Events_Model::COL_IS_RECOMMENDED} == true) { ?>
                           <img src="images/icons/star.png" alt="recomend" title="<?php echo $this->tr('Položka je doporučována') ?>" />
                        <?php } ?>
                        <?php if ($event->{Events_Model::COL_PUBLIC_ADD} == true && $this->isControll) { ?>
                           <img src="images/icons/group.png" alt="new" title="<?php echo $this->tr('Veřejně přidaná položka') ?>" />
                        <?php } ?>
                        <span class="<?php echo $state ?>">
                           <?php
                           ps($event->{Events_Model::COL_NAME} . " ");
                           ?>
                        </span>
                        <em>

                           <?php
                           // datum a čas
                           $dateStr = null;
                           if ($event->{Events_Model::COL_DATE_FROM} != null) {
                              $dateStr = vve_date("%x", new DateTime($event->{Events_Model::COL_DATE_FROM}));
                           }
                           if ($event->{Events_Model::COL_DATE_TO} != null) {
                              $dateStr .= " - " . vve_date("%x", new DateTime($event->{Events_Model::COL_DATE_TO}));
                           }

                           $timeStr = null;
                           if ($event->{Events_Model::COL_TIME_FROM} != null) {
                              $timeStr = ", " . vve_date("%G:%i", new DateTime($event->{Events_Model::COL_TIME_FROM}));
                           }
                           if ($event->{Events_Model::COL_TIME_TO} != null) {
                              $timeStr .= " - " . vve_date("%G:%i", new DateTime($event->{Events_Model::COL_TIME_TO}));
                           }
                           ?>
                        </em>
                        <?php
                        $this->toolboxItem->editEvent->setAction($this->link()->route('editEvent', array('idevent' => $event->{Events_Model::COL_ID})));
                        $this->toolboxItem->cloneEvent->setAction($this->link()->route('addEvent')->param('source', $event->{Events_Model::COL_ID}));
                        $this->toolboxItem->ev_delete->getForm()->id->setValues($event->{Events_Model::COL_ID});

                        if ($this->isControll) {
                           $this->toolboxItem->ev_change_recomended_->getForm()->id->setValues($event->{Events_Model::COL_ID});
                           $this->toolboxItem->ev_change_recomended_->setIcon(
                                   $event->{Events_Model::COL_IS_RECOMMENDED} == true ? 'star-o' : 'star');
                        } else {
                           unset($this->toolboxItem->ev_change_recomended_);
                        }

                        $this->toolboxItem->ev_change_visible->getForm()->id->setValues($event->{Events_Model::COL_ID});
                        $this->toolboxItem->ev_change_visible->setIcon(
                                $event->{Events_Model::COL_PUBLIC} == true ? 'eye-slash' : 'eye');

                        $this->toolboxItem->setTemplate(Template_Toolbox2::TEMPLATE_INLINE);
                        echo $this->toolboxItem;
                        ?>
                     </th>
                  </tr>
                  <tr class="cubecms-row <?php echo $state ?>">
                     <th scope="row" class="param-name"><?php echo $this->tr('Datum a čas') ?></th>
                     <td><?php echo $dateStr . $timeStr ?></td>
                  </tr>

                  <?php if ($event->{Events_Model::COL_PLACE} != null) { ?>
                     <tr class="cubecms-row <?php echo $state ?>">
                        <th scope="row" class="param-name"><?php echo $this->tr('Místo konání') ?></th>
                        <td><?php echo $event->{Events_Model::COL_PLACE} ?></td>
                     </tr>
                  <?php } ?>

                  <?php if ($event->{Events_Model::COL_PRICE} != null) { ?>
                     <tr class="cubecms-row <?php echo $state ?>">
                        <th scope="row" class="param-name"><?php echo $this->tr('Cena') ?></th>
                        <td><?php echo $event->{Events_Model::COL_PRICE} ?> Kč</td>
                     </tr>
                  <?php } ?>

                  <?php if ($event->{Events_Model::COL_CONTACT} != null) { ?>
                     <tr class="cubecms-row <?php echo $state ?>">
                        <th scope="row" class="param-name"><?php echo $this->tr('Kontakt') ?></th>
                        <td><?php echo $event->{Events_Model::COL_CONTACT} ?></td>
                     </tr>
                  <?php } ?>

                  <?php if ($event->{Events_Model::COL_NOTE} != null) { ?>
                     <tr class="cubecms-row <?php echo $state ?>">
                        <th scope="row" class="param-name"><?php echo $this->tr('Poznámka') ?></th>
                        <td><?php echo $event->{Events_Model::COL_NOTE} ?></td>
                     </tr>
                  <?php } ?>
               </table>
            <?php } ?>
         </div>
      <?php } ?>
      <div>
         <form action="<?php echo $this->link() ?>" method="post" id="formEventAction">
            <label><?php echo $this->tr('Vybrat') ?>:</label>
            <a href="<?php echo $this->link() ?>#select-all" onclick="selectEvents('all');" title="<?php echo $this->tr('Vybrat všechny položky') ?>"><?php echo $this->tr('vše') ?></a>
            | <a href="<?php echo $this->link() ?>#select-none" onclick="selectEvents(null);" title="<?php echo $this->tr('Zrušit vybrání') ?>"><?php echo $this->tr('nic') ?></a>
            <?php if ($this->isControll) { ?>| <a href="<?php echo $this->link() ?>#select-new"  onclick="selectEvents('new');" 
                    title="<?php echo $this->tr('Vybrat pouze veřejně přidané položky') ?>"><?php echo $this->tr('veřejně přidané') ?></a><?php } ?>
            &nbsp;<label><?php echo $this->tr('Označené') ?>:</label>
            <input type="hidden" value="" name="events_items_ids" />
            <select name="events_action" id="formEventSelector">
               <option selected="selected" value=""><?php echo $this->tr('Vyberte akci...') ?></option>
               <?php if ($this->isControll) { ?>
                  <option value="notnew"><?php echo $this->tr('Zrušit atribut nové') ?></option>
                  <option value="recommended"><?php echo $this->tr('Nastavit doporučení') ?></option>
                  <option value="delrecommended"><?php echo $this->tr('Zrušit doporučení') ?></option>
               <?php } ?>
               <option value="visible" ><?php echo $this->tr('Nastavit viditelné') ?></option>
               <option value="nonvisible" ><?php echo $this->tr('Nastavit neviditelné') ?></option>
               <option value="delete" data-message="<?php echo $this->tr('Smazat vybrané?') ?>"><?php echo $this->tr('Smazat') ?></option>
            </select>   
         </form>
         <script type="text/javascript">
            function selectEvents(type) {
               if (type == "all") {
                  $('input[name="event_selected"]').prop("checked", true).change();
               } else if (type == null) {
                  $('input[name="event_selected"]').prop("checked", false).change();
               } else if (type == "new") {
                  $('input[name="event_selected"]').each(function () {
                     if ($(this).parents(".event-event-item").hasClass('event-public-add')) {
                        $(this).prop("checked", true).change();
                     } else {
                        $(this).prop("checked", false).change();
                     }
                  });
               }
               return false;
            }
            $(document).ready(function () {
               // select all or none
               $('input[name="event_selected"]').prop("checked", false);
               $('#formEventAction').submit(function () {
                  var $items = $('input[name="event_selected"]:checked');
                  if ($items.length == 0) {
                     alert('<?php echo $this->tr('Musíte vybrat alespoň jednu položku') ?>');
                     return false;
                  }

                  var $option = $("option:selected", this);
                  if ($option.data('message') != null && !confirm($option.data('message'))) {
                     return false;
                  }
                  // pasování pro přenos
                  var ids = new Array();
                  $items.each(function () {
                     ids.push($(this).val());
                  });
                  $('input[name="events_items_ids"]', this).val(ids.join(';'));
               });
               $('input[name="event_selected"]').change(function () {
                  if ($(this).is(':checked')) {
                     $(this).parents('tr').addClass('ui-state-highlight');
                  } else {
                     $(this).parents('tr').removeClass('ui-state-highlight');
                  }
               });

               $('.event-name').click(function (e) {
                  if (e.target === this) {
                     var $input = $(this).find('input[name="event_selected"]');
                     if ($input.is(':checked')) {
                        $input.prop("checked", false);
                     } else {
                        $input.prop("checked", true);
                     }
                     $input.change();
                  }
               });

               $("#formEventSelector").val($("#formEventSelector option:first").val());
               $('#formEventSelector').change(function () {
                  if ($(this).val() != "") {
                     $('#formEventAction').submit();
                  }
                  $("#formEventSelector").val($("#formEventSelector option:first").val());
                  return false;
               });
            });
         </script>
      </div>
   <?php } else { ?>
      <p><?php echo $this->tr('Zadanému filtru nevyhovuje žádná položka') ?></p>   
   <?php } ?>
   <br />
</div>
