<?php 
echo $this->toolbox;
$this->addFile('css://style.css');
$h1 = $this->tr('Seznam kategorií');

$this->addJsPlugin(new JsPlugin_JQueryCSS());
Template_Core::addPageTitle($this->tr('kategorie událostí'));

$catImgDir = $this->category()->getModule()->getDataDir(true).Events_Controller::DIR_CAT_IMAGES."/";
?>
<h1><?php echo $this->category()->getName()?></h1>
<div class="form-edit">
   <div>
      <a href="<?php echo $this->link()->route('addCat')?>" title="<?php echo $this->tr('Přidat novou kategorii')?>"
         ><img src="images/icons/add.png" alt="add" /> <?php echo $this->tr('Přidat kategorii')?></a>
   </div>
   <?php 
   if(!empty($this->categories)){
   foreach ($this->categories as $cat) {?>
   <table class="ui-widget full-width event-cat-item">
      <tr class="ui-widget-header <?php if($cat->{Events_Model_Categories::COL_IS_PUBLIC}){?>ui-state-hover<?php }?>">
         <td class="event-name" colspan="2">
            <?php 
            if($cat->{Events_Model_Categories::COL_IMAGE} != null){?>
            <img src="<?php echo $catImgDir.$cat->{Events_Model_Categories::COL_IMAGE}?>" width="16" />
            <?php }
            echo $cat->{Events_Model_Categories::COL_NAME};
            
            $toolbox = clone $this->toolboxItem;
            
            $toolbox->cat_is_public_->getForm()->id->setValues($cat->{Events_Model_Categories::COL_ID});
            $toolbox->editCat->setAction($this->link()->route('editCat', array('idcat' => $cat->{Events_Model_Categories::COL_ID})));
            $toolbox->cat_delete_->getForm()->id->setValues($cat->{Events_Model_Categories::COL_ID});
            $toolbox->cat_token_->getForm()->id->setValues($cat->{Events_Model_Categories::COL_ID});
            $toolbox->setTemplate(Template_Toolbox2::TEMPLATE_INLINE);
            
            if($cat->{Events_Model_Categories::COL_IS_PUBLIC} == true){
               echo ' <em>('.$this->tr('veřejná').')</em>';
               $toolbox->cat_is_public_->setIcon("eye_delete.png");
               unset($toolbox->cat_token_);
            }
            echo $toolbox;
            ?>
         </td>
      </tr>
      <?php if($cat->{Events_Model_Categories::COL_CONTACT} != null){?>
      <tr class="ui-widget-content">
         <th scope="row" class="param-name"><?php echo $this->tr('Kontakt')?>:</th>
         <td><?php echo $cat->{Events_Model_Categories::COL_CONTACT}?></td>
      </tr>
      <?php }?>
      <?php if($cat->{Events_Model_Categories::COL_WWW} != null){?>
      <tr class="ui-widget-content">
         <th scope="row" class="param-name"><?php echo $this->tr('WWW')?>:</th>
         <td><a href="<?php echo $cat->{Events_Model_Categories::COL_WWW}?>" class="link-external" title="<?php echo $this->tr('Otevřít v novém okně')?>"
                ><?php ps($cat->{Events_Model_Categories::COL_WWW});?></a></td>
      </tr>
      <?php }?>
      <?php if($cat->{Events_Model_Categories::COL_NOTE} != null){?>
      <tr class="ui-widget-content">
         <th scope="row" class="param-name"><?php echo $this->tr('Poznámka')?>:</th>
         <td><?php echo $cat->{Events_Model_Categories::COL_NOTE}?></td>
      </tr>
      <?php }?>
      <?php if($cat->{Events_Model_Categories::COL_IS_PUBLIC} == false){?>
      <tr class="ui-widget-content">
         <th scope="row" class="param-name"><?php echo $this->tr('Přistupový odkaz')?>:</th>
         <td class="event-cat-token"><?php 
         if($cat->{Events_Model_Categories::COL_ACCESS_TOKEN} != null){
            $link = $this->link()->route('listEvents')->param('token', $cat->{Events_Model_Categories::COL_ACCESS_TOKEN});
            ?>
            <a href="<?php echo $link?>" title="<?php echo $this->tr('Odkaz pro přístup z venku')?>"><?php echo $link;?></a> 
         <?php } else {
            echo '<em>'.$this->tr('Není vytvořen. Klikněte na ikonku klíče v nastrojích položky.').'</em>';
         }?>
         </td>
      </tr>
      <?php }?>
   </table>
   <?php }
   }?>
</div>