<?
echo $this->toolbox;
$this->addFile('css://style.css');
$h1 = $this->tr('Seznam událostí');
Template_Core::addPageTitle($h1);

$this->addJsPlugin(new JsPlugin_JQueryCSS());
$jq = new JsPlugin_JQuery();
$jq->addUIDatepicker();
$this->addJsPlugin($jq);

function getParam($name, $cmp, $print){
   if(isset($_GET[$name])){
      
   }
}
$showFFrom = false;
if(isset($_GET['dateFrom']) || isset($_GET['dateTo']) || isset($_GET['cat']) || isset($_GET['contain']) || isset($_GET['onlyPublicAdd'])){
   $showFFrom = true;
}
?>
<h1><?ps($h1)?></h1>
<div class="form-edit">
   <div>
      <a href="<?=$this->link()->route('addEvent')?>" title="<?=$this->tr('Přidat novou událost')?>"
         ><img src="images/icons/add.png" alt="add" /> <?=$this->tr('Přidat událost')?></a>
      <a id="buttonShowFilter" href="<?=$this->link()?>#filter" title="<?=$this->tr('Zobrazit filtraci')?>"
         style="<?if($showFFrom) echo 'display: none;';?>"
         ><img src="images/icons/magnifier.png" alt="filter" /> <?=$this->tr('Filtrace')?></a>
   </div>
   <form id="formFilter" action="<?=$this->link()?>" method="get" style="<?if(!$showFFrom) echo 'display: none;';?>">
      <fieldset>
         <legend><?=$this->tr('Filtrace')?></legend>
      <table class="form-table">
         <tr>
            <th class="form-labels"><label for="dateFrom"><?=$this->tr('Od')?>:</label></th>
            <td class="form-controlls"><input name="dateFrom" value="<?=vve_date("%x", $this->dateFrom)?>" type="text" id="dateFrom" /></td>
         </tr>
         <tr>
            <th class="form-labels"><label for="dateTo"><?=$this->tr('Do')?>:</label></th>
            <td class="form-controlls"><input name="dateTo" value="<?=vve_date("%x", $this->dateTo)?>" type="text" id="dateTo" /></td>
         </tr>
         <tr>
            <th class="form-labels"><label for="contain"><?=$this->tr('Název')?>:</label></th>
            <td class="form-controlls"><input name="contain" value="<?if(isset($_GET['contain']))echo $_GET['contain']?>" type="text" id="contain" /></td>
         </tr>
         <?if($this->isControll){?>
         <tr>
            <th class="form-labels"><label for="catSelect"><?=$this->tr('Kategorie')?>:</label></th>
            <td class="form-controlls">
               <select name="cat" id="catSelect">
            <option value=""><?=$this->tr('vše')?></option>
            <?foreach ($this->cats as $cat) {?>
            <option <?if(isset($_GET['cat']) && $_GET['cat'] == $cat->{Events_Model_Categories::COL_ID} ){ echo 'selected="selected"';}?> 
               value="<?=$cat->{Events_Model_Categories::COL_ID}?>"><?ps($cat->{Events_Model_Categories::COL_NAME})?></option>      
            <?}?>
               </select>
            </td>
         </tr>
         <tr>
            <th class="form-labels"></th>
            <td class="form-controlls"><input name="onlyPublicAdd" type="checkbox" id="onlyPublicAdd" <?if(isset($_GET['onlyPublicAdd']) && $_GET['onlyPublicAdd'] == "on")echo 'checked="checked"'?> /> <label for="onlyPublicAdd"><?=$this->tr('Pouze veřejně přidané')?></label></td>
         </tr>
         <?}?>
         <tr>
            <td></td>
            <td class="form-controlls">
               <input value="<?=$this->tr('Filtrovat')?>" type="submit" />
               <input value="<?=$this->tr('Zrušit filtraci')?>" type="button" id="buttonHideFilter" 
                      onclick="window.location = '<?=$this->link()->rmParam(array('dateFrom', 'dateTo', 'contain', 'cat', 'onlyPublicAdd'))?>';"/>
            </td>
         </tr>
      </table>
      <?if(isset($_GET['token'])){ ?><input type="hidden" name="token" value="<?=$_GET['token']?>" /><?}?>
      </fieldset>
   </form>
   <script type="text/javascript">
      $(document).ready(function(){
         $('input#dateFrom').datepicker({ });
         $('input#dateTo').datepicker({ });
      <?if($showFFrom){?>
         $('#buttonShowFilter').hide();
      <?}?>
         $('#buttonShowFilter').click(function(){
            $('#formFilter').slideDown('fast');
            $(this).hide();
         });
      });
   </script>
   <?
   if(!empty($this->events)){?>
   <?foreach ($this->events as $cat) {?>
   
   <div class="events-list-in-cat">
      <h3><?=$cat['cat']->{Events_Model_Categories::COL_NAME}?></h3>
      <?foreach ($cat['events'] as $event) {
         $state = $event->{Events_Model::COL_PUBLIC} != true ? "ui-state-disabled" : null ;
         ?>
         <table class="ui-widget full-width event-event-item <?if($event->{Events_Model::COL_PUBLIC_ADD} == true){?>event-public-add<?}?>">
         <tr class="ui-widget-header">
            <td class="event-name" colspan="2">
               <input type="checkbox" name="event_selected" value="<?=$event->{Events_Model::COL_ID}?>" />
               <?if($event->{Events_Model::COL_IS_RECOMMENDED} == true){?>
               <img src="images/icons/star.png" alt="recomend" title="<?=$this->tr('Položka je doporučována')?>" />
               <?}?>
               <?if($event->{Events_Model::COL_PUBLIC_ADD} == true && $this->isControll){?>
               <img src="images/icons/group.png" alt="new" title="<?=$this->tr('Veřejně přidaná položka')?>" />
               <?}?>
               <span class="<?=$state?>">
               <?
               ps($event->{Events_Model::COL_NAME}." ");
               ?>
               </span>
               <em>
                  
               <?
               // datum a čas
               $dateStr = null;
               if($event->{Events_Model::COL_DATE_FROM} != null){
                  $dateStr = vve_date("%x", new DateTime($event->{Events_Model::COL_DATE_FROM}));
               }
               if($event->{Events_Model::COL_DATE_TO} != null){
                  $dateStr .= " - ".vve_date("%x", new DateTime($event->{Events_Model::COL_DATE_TO}));
               }
//               echo $dateStr;
               
               $timeStr = null;
               if($event->{Events_Model::COL_TIME_FROM} != null){
                  $timeStr = ", ".vve_date("%G:%i", new DateTime($event->{Events_Model::COL_TIME_FROM}));
               }
               if($event->{Events_Model::COL_TIME_TO} != null){
                  $timeStr .= " - ".vve_date("%G:%i", new DateTime($event->{Events_Model::COL_TIME_TO}));
               }
//               echo $timeStr;
               ?>
               </em>
               <?
               $this->toolboxItem->editEvent->setAction($this->link()->route('editEvent', array('idevent' => $event->{Events_Model::COL_ID})));
               $this->toolboxItem->ev_delete->getForm()->id->setValues($event->{Events_Model::COL_ID});
               
               if($this->isControll){
                  $this->toolboxItem->ev_change_recomended_->getForm()->id->setValues($event->{Events_Model::COL_ID});
                  $this->toolboxItem->ev_change_recomended_->setIcon(
                     $event->{Events_Model::COL_IS_RECOMMENDED} == true ? 'star_delete.png' : 'star_add.png');
               } else {
                  unset($this->toolboxItem->ev_change_recomended_);
               }
               
               $this->toolboxItem->ev_change_visible->getForm()->id->setValues($event->{Events_Model::COL_ID});
               $this->toolboxItem->ev_change_visible->setIcon(
                  $event->{Events_Model::COL_PUBLIC} == true ? 'eye_delete.png' : 'eye.png');
               
               $this->toolboxItem->setTemplate(Template_Toolbox2::TEMPLATE_INLINE);
               echo $this->toolboxItem;
               ?>
            </td>
         </tr>
         <tr class="ui-widget-content <?=$state?>">
            <th scope="row" class="param-name"><?=$this->tr('Datum a čas')?></th>
            <td><?=$dateStr.$timeStr ?></td>
         </tr>
         
         <?if($event->{Events_Model::COL_PLACE} != null){?>
         <tr class="ui-widget-content <?=$state?>">
            <th scope="row" class="param-name"><?=$this->tr('Místo konání')?></th>
            <td><?=$event->{Events_Model::COL_PLACE} ?></td>
         </tr>
         <?}?>
         
         <?if($event->{Events_Model::COL_PRICE} != null){?>
         <tr class="ui-widget-content <?=$state?>">
            <th scope="row" class="param-name"><?=$this->tr('Cena')?></th>
            <td><?=$event->{Events_Model::COL_PRICE}?> Kč</td>
         </tr>
         <?}?>
         
         <?if($event->{Events_Model::COL_CONTACT} != null){?>
         <tr class="ui-widget-content <?=$state?>">
            <th scope="row" class="param-name"><?=$this->tr('Kontakt')?></th>
            <td><?=$event->{Events_Model::COL_CONTACT} ?></td>
         </tr>
         <?}?>
         
         <?if($event->{Events_Model::COL_NOTE} != null){?>
         <tr class="ui-widget-content <?=$state?>">
            <th scope="row" class="param-name"><?=$this->tr('Poznámka')?></th>
            <td><?=$event->{Events_Model::COL_NOTE} ?></td>
         </tr>
         <?}?>
         </table>
      <?}?>
   </div>
   <?}?>
   <div>
      <form action="<?=$this->link()?>" method="post" id="formEventAction">
         <label><?=$this->tr('Vybrat')?>:</label>
         <a href="<?=$this->link()?>#select-all" onclick="selectEvents('all');" title="<?=$this->tr('Vybrat všechny položky')?>"><?=$this->tr('vše')?></a>
         | <a href="<?=$this->link()?>#select-none" onclick="selectEvents(null);" title="<?=$this->tr('Zrušit vybrání')?>"><?=$this->tr('nic')?></a>
         <?if($this->isControll){?>| <a href="<?=$this->link()?>#select-new"  onclick="selectEvents('new');" 
              title="<?=$this->tr('Vybrat pouze veřejně přidané položky')?>"><?=$this->tr('veřejně přidané')?></a><?}?>
         &nbsp;<label><?=$this->tr('Označené')?>:</label>
         <input type="hidden" value="" name="events_items_ids" />
         <select name="events_action" id="formEventSelector">
            <option selected="selected" value=""><?=$this->tr('Vyberte akci...')?></option>
            <?if($this->isControll){?>
            <option value="notnew"><?=$this->tr('Zrušit atribut nové')?></option>
            <option value="recommended"><?=$this->tr('Nastavit doporučení')?></option>
            <option value="delrecommended"><?=$this->tr('Zrušit doporučení')?></option>
            <?}?>
            <option value="visible" ><?=$this->tr('Nastavit viditelné')?></option>
            <option value="nonvisible" ><?=$this->tr('Nastavit neviditelné')?></option>
            <option value="delete" data-message="<?=$this->tr('Smazat vybrané?')?>"><?=$this->tr('Smazat')?></option>
         </select>   
      </form>
      <script type="text/javascript">
         function selectEvents(type){
            if(type == "all"){
               $('input[name="event_selected"]').prop("checked", true).change();
            } else if(type == null){
               $('input[name="event_selected"]').prop("checked", false).change();
            } else if(type == "new"){
               $('input[name="event_selected"]').each(function(){
                  if($(this).parents(".event-event-item").hasClass('event-public-add')){
                      $(this).prop("checked", true).change();
                  } else {
                      $(this).prop("checked", false).change();
                  }
               });
            }
            return false;
         }
         $(document).ready(function(){
            // select all or none
            $('input[name="event_selected"]').prop("checked", false);
            $('#formEventAction').submit(function(){
               var $items = $('input[name="event_selected"]:checked');
               if($items.length == 0){
                  alert('<?=$this->tr('Musíte vybrat alespoň jednu položku')?>');
                  return false;
               }
               
               var $option = $("option:selected", this);
               if($option.data('message') != null && !confirm($option.data('message'))){
                  return false;
               }
               // pasování pro přenos
               var ids = new Array();
               $items.each(function(){
                  ids.push($(this).val());
               });
               $('input[name="events_items_ids"]', this).val(ids.join(';'));
            });
            $('input[name="event_selected"]').change(function(){
               if($(this).is(':checked')){
                  $(this).parents('tr').addClass('ui-state-highlight');
               } else {
                  $(this).parents('tr').removeClass('ui-state-highlight');
               }
            });
            
            $('.event-name').click(function(e){
               if (e.target === this) {
                  var $input = $(this).find('input[name="event_selected"]');
                  if($input.is(':checked')){
                     $input.prop("checked", false);
                  } else {
                     $input.prop("checked", true);
                  }
                  $input.change();
               }
            });
            
            $("#formEventSelector").val($("#formEventSelector option:first").val());
            $('#formEventSelector').change(function(){
               if($(this).val() != ""){
                  $('#formEventAction').submit();
               }
               $("#formEventSelector").val($("#formEventSelector option:first").val());
               return false;
            });
         });
      </script>
   </div>
   <?} else {?>
   <p><?=$this->tr('Zadanému filtru nevyhovuje žádná položka')?></p>   
   <?}?>
   <br />
</div>
