<?php 
echo $this->toolbox;
$this->addFile('css://style.css');

$showFFrom = false;
if(isset($_GET['dateFrom']) || isset($_GET['dateTo']) || isset($_GET['cat']) || isset($_GET['contain']) || isset($_GET['onlyPublicAdd'])){
   $showFFrom = true;
}
?>
<h1><?php echo $this->category()->getName()?></h1>
<div>
   <p id="eventFilterButtons">
   Zobrazit: 
   <a href="<?php echo $this->link()->route()->param('range');?>" title="<?php echo $this->tr('na dnešek')?>"
      ><?php echo $this->tr('na dnešek')?></a>
   | <a href="<?php echo $this->link()->route()->param('range', 'week')?>" title="<?php echo $this->tr('na tento týden')?>"
      ><?php echo $this->tr('na tento týden')?></a>
   | <a href="<?php echo $this->link()->route()->param('range', 'month')?>" title="<?php echo $this->tr('na tento měsíc')?>"
      ><?php echo $this->tr('na tento měsíc')?></a>
   | <a id="buttonShowFilter" href="<?php echo $this->link()->param('range')?>#formFilter" title="<?php echo $this->tr('vlasní rozsah')?>"
      ><?php echo $this->tr('vlasní rozsah')?></a>
   </p>
   
   <form id="formFilter" action="<?php echo $this->link()?>" method="get" style="<?php if(!$showFFrom) echo 'display: none;';?>">
      <fieldset>
         <legend><?php echo $this->tr('Filtrace')?></legend>
      <table class="form-table">
         <tr>
            <th class="form-labels"><label for="dateFrom"><?php echo $this->tr('Od')?>:</label></th>
            <td class="form-controlls"><input name="dateFrom" value="<?php echo vve_date("%x", $this->dateFrom)?>" type="text" id="dateFrom" /></td>
         </tr>
         <tr>
            <th class="form-labels"><label for="dateTo"><?php echo $this->tr('Do')?>:</label></th>
            <td class="form-controlls"><input name="dateTo" value="<?php echo vve_date("%x", $this->dateTo)?>" type="text" id="dateTo" /></td>
         </tr>
         <tr>
            <th class="form-labels"><label for="catSelect"><?php echo $this->tr('Kategorie')?>:</label></th>
            <td class="form-controlls">
               <select name="cat" id="catSelect">
            <option value=""><?php echo $this->tr('vše')?></option>
            <?php foreach ($this->cats as $cat) {?>
            <option <?php if(isset($_GET['cat']) && $_GET['cat'] == $cat->{Events_Model_Categories::COL_ID} ){ echo 'selected="selected"';}?> 
               value="<?php echo $cat->{Events_Model_Categories::COL_ID}?>"><?php ps($cat->{Events_Model_Categories::COL_NAME})?></option>      
            <?php }?>
               </select>
            </td>
         </tr>
         <tr>
            <td></td>
            <td class="form-controlls">
               <input value="<?php echo $this->tr('Filtrovat')?>" type="submit" />
               <input value="<?php echo $this->tr('Zrušit filtraci')?>" type="button" id="buttonHideFilter" 
                      onclick="window.location = '<?php echo $this->link()->rmParam(array('dateFrom', 'dateTo', 'cat'))?>';"/>
            </td>
         </tr>
      </table>
      <?php if(isset($_GET['token'])){ ?><input type="hidden" name="token" value="<?php echo $_GET['token']?>" /><?php }?>
      </fieldset>
   </form>
   <?php 
   $jq = new JsPlugin_JQuery();
   $jq->addUIDatepicker();
   $this->addJsPlugin($jq);
   ?>
   <script type="text/javascript">
      $(document).ready(function(){
         var dates = $('input#dateFrom, input#dateTo').datepicker({
            showButtonPanel: true,
            showOtherMonths: true,
            selectOtherMonths: true,
            onSelect: function( selectedDate ) {
               var option = this.id == "dateFrom" ? "minDate" : "maxDate",
               instance = $( this ).data( "datepicker" ),
               date = $.datepicker.parseDate(
               instance.settings.dateFormat ||
               $.datepicker._defaults.dateFormat,
                  selectedDate, instance.settings );
               dates.not( this ).datepicker( "option", option, date );
            }
         });
      <?php if($showFFrom){?>
         $('#eventFilterButtons').hide();
      <?php }?>
         $('#buttonShowFilter').click(function(){
            $('#formFilter').slideDown('fast');
            $('#eventFilterButtons').hide();
            return false;
         });
      });
   </script>
   
</div>
<div class="post">
   <?php 
   if(!empty($this->events)){?>
   <?php foreach ($this->events as $cat) {?>
   <h2><?php echo $cat['cat']->{Events_Model_Categories::COL_NAME}?></h2>
   <?php if($cat['cat']->{Events_Model_Categories::COL_CONTACT} != null){?>
   <p class="font-small"><?php 
      ps($cat['cat']->{Events_Model_Categories::COL_CONTACT});
   ?></p>   
   <?php }?>
   <p>
   <table class="events-list full-width">
      <thead>
         <tr>
            <th><?php echo $this->tr('Název')?></th>
            <th><?php echo $this->tr('Datum')?></th>
            <th><?php echo $this->tr('Čas')?></th>
            <th><?php echo $this->tr('Místo konání')?></th>
            <th><?php echo $this->tr('Cena')?></th>
         </tr>
      </thead>
      <tbody>
      <?php foreach ($cat['events'] as $event) {?>
         <tr  class="row-begin">
            <td class="event-name" >
               <?php 
               ps($event->{Events_Model::COL_NAME}." ");
               if($event->{Events_Model::COL_IS_RECOMMENDED} == true){
                  ?><img src="images/icons/star.png" alt="recomend" title="<?php echo $this->tr('Doporučujeme !')?>" /><?php 
               }
               ?>
            </td>
            <td class="event-date" >
               <?php 
               // datum a čas
               $dateStr = null;
               if($event->{Events_Model::COL_DATE_FROM} != null){
                  $dateStr = vve_date("%x", new DateTime($event->{Events_Model::COL_DATE_FROM}));
               }
               if($event->{Events_Model::COL_DATE_TO} != null){
                  $dateStr .= " - ".vve_date("%x", new DateTime($event->{Events_Model::COL_DATE_TO}));
               }
               echo $dateStr;
               ?>
            </td>
            <td class="event-time">
               <?php 
               $timeStr = null;
               if($event->{Events_Model::COL_TIME_FROM} != null){
                  $timeStr = /*", ".*/vve_date("%G:%i", new DateTime($event->{Events_Model::COL_TIME_FROM}));
               }
               if($event->{Events_Model::COL_TIME_TO} != null){
                  $timeStr .= " - ".vve_date("%G:%i", new DateTime($event->{Events_Model::COL_TIME_TO}));
               }
               echo $timeStr;
               ?>
            </td>
            <td class="event-place">
            <?php if($event->{Events_Model::COL_PLACE} != null){?>
               <?php echo $event->{Events_Model::COL_PLACE} ?>
            <?php }?>
            </td>
            <td class="event-price">
            <?php if($event->{Events_Model::COL_PRICE} != null){?>
               <?php echo $event->{Events_Model::COL_PRICE}?> Kč
            <?php }?>
            </td>
         </tr>
         <tr class="row-end">
            <td></td>
            <td class="event-note" colspan="4">
            <?php if($event->{Events_Model::COL_NOTE} != null){
               ps ($event->{Events_Model::COL_NOTE});
            }?>
            </td>
         </tr>
      <?php }?>
      </tbody>
   </table>
   </p>
 <?php }?>
 <?php }?>
   <div>
      <a href="<?php echo $this->link()->route('addEvent')?>" title="<?php echo $this->tr('Přidat novou událost')?>"
         ><img src="images/icons/add.png" alt="add" /> <?php echo $this->tr('Přidat událost')?></a>
   </div>
</div>
