<?//<desc>Panel seznam nadcházejících akcí</desc>
if(!empty ($this->events)) {
   $icon = null;
   if($this->panelObj()->getIcon() != null) {
      $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
   }
   $backImg = null;
   if($this->panelObj()->getBackImage() != null) {
      $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
   }
   /*if($this->rssLink != null) {?>
<a style="float: right" href="<?=$this->rssLink?>" title="rss"><img src="<?=vve_get_tpl_file('icons/rss-icon.png', VVE_TPL_FILE_IMAGE)?>" alt="rss" /></a>
         <?}*/
         ?>
<div class="label"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->panelObj()->getName())?>"><?=$this->panelObj()->getName()?></a></div>
<div class="content" style="<?=$backImg?>">
   <?
   foreach ($this->events AS $cat){
      ?>
      <div class="name name-section"><?=$cat['cat']->{Events_Model_Categories::COL_NAME}?></div>
      <div class="item-section">
      <?
      foreach ($cat['events'] AS $event){
         // datum a čas
         $dateStr = null;
         if ($event->{Events_Model::COL_DATE_FROM} != null) {
            $dateStr = vve_date("%x", new DateTime($event->{Events_Model::COL_DATE_FROM}));
         }
         if ($event->{Events_Model::COL_DATE_TO} != null) {
            $dateStr .= " - " . vve_date("%x", new DateTime($event->{Events_Model::COL_DATE_TO}));
         }  

         $timeStr = null;
         if ($event->{Events_Model::COL_TIME_FROM} != null) {
            $timeStr = ", " . vve_date("%G:%i", new DateTime($event->{Events_Model::COL_TIME_FROM}));
         }
         if ($event->{Events_Model::COL_TIME_TO} != null) {
            $timeStr .= " - " . vve_date("%G:%i", new DateTime($event->{Events_Model::COL_TIME_TO}));
         }
      
      ?>
      <div class="item post">
         <div class="name"><?=$event->{Events_Model::COL_NAME}?></div>
         <div class="text">
            <span class="date"><?=$dateStr?></span><span class="time"><?=$timeStr?></span>
            <?if($event->{Events_Model::COL_PLACE} != null){?>
               <br/><span class="place"><?ps($event->{Events_Model::COL_PLACE})?></span>
            <?}?>
            <?if($event->{Events_Model::COL_NOTE} != null){?>
               <br/><span class="note"><?ps($event->{Events_Model::COL_NOTE})?></span>
            <?}?>
         </div>
      </div>
      <?}?>
      </div>
   <?}?>
   <div class="link-more">
      <a href="<?=$this->link()?>"
         title="<?=$this->tr('Více akcí z ').htmlspecialchars($this->category()->getLabel())?>"><?=$this->tr('Více událostí')?></a>
   </div>
</div>
   <?}?>