<?php //<desc>Panel seznam nadcházejících akcí</desc>
if(!empty ($this->events)) {
   $icon = null;
   if($this->panelObj()->getIcon() != null) {
      $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
   }
   $backImg = null;
   if($this->panelObj()->getBackImage() != null) {
      $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
   }
   /*if($this->rssLink != null) {?>
<a style="float: right" href="<?php echo $this->rssLink?>" title="rss"><img src="<?php echo vve_get_tpl_file('icons/rss-icon.png', VVE_TPL_FILE_IMAGE)?>" alt="rss" /></a>
         <?php }*/
         ?>
<div class="label"><?php echo $icon?><a href="<?php echo $this->link()?>" title="<?php echo htmlspecialchars($this->panelObj()->getName())?>"><?php echo $this->panelObj()->getName()?></a></div>
<div class="content" style="<?php echo $backImg?>">
   <?php 
   foreach ($this->events AS $cat){
      ?>
      <div class="name name-section"><?php echo $cat['cat']->{Events_Model_Categories::COL_NAME}?></div>
      <div class="item-section">
      <?php 
      foreach ($cat['events'] AS $event){
         // datum a čas
         $dateStr = null;
         if ($event->{Events_Model::COL_DATE_FROM} != null) {
            $dateStr = vve_date("%x", new DateTime($event->{Events_Model::COL_DATE_FROM}));
         }
         if ($event->{Events_Model::COL_DATE_TO} != null) {
            $dateStr .= " - " . vve_date("%x", new DateTime($event->{Events_Model::COL_DATE_TO}));
         }  

         $timeStr = null;
         if ($event->{Events_Model::COL_TIME_FROM} != null) {
            $timeStr = ", " . vve_date("%G:%i", new DateTime($event->{Events_Model::COL_TIME_FROM}));
         }
         if ($event->{Events_Model::COL_TIME_TO} != null) {
            $timeStr .= " - " . vve_date("%G:%i", new DateTime($event->{Events_Model::COL_TIME_TO}));
         }
      
      ?>
      <div class="item post">
         <div class="name"><?php echo $event->{Events_Model::COL_NAME}?></div>
         <div class="text">
            <span class="date"><?php echo $dateStr?></span><span class="time"><?php echo $timeStr?></span>
            <?php if($event->{Events_Model::COL_PLACE} != null){?>
               <br/><span class="place"><?php ps($event->{Events_Model::COL_PLACE})?></span>
            <?php }?>
            <?php if($event->{Events_Model::COL_NOTE} != null){?>
               <br/><span class="note"><?php ps($event->{Events_Model::COL_NOTE})?></span>
            <?php }?>
         </div>
      </div>
      <?php }?>
      </div>
   <?php }?>
   <div class="link-more">
      <a href="<?php echo $this->link()?>"
         title="<?php echo $this->tr('Více akcí z ').htmlspecialchars($this->category()->getLabel())?>"><?php echo $this->tr('Více událostí')?></a>
   </div>
</div>
   <?php }?>