<?php 
$h1 = $this->category()->getName();
$dwLink = new Url_DownloadLink($this->category()->getModule()->getDataDir());
echo $this->toolbox;
$this->addFile("css://style.css");
?>
<h1><?php $this->includeFile('tpl://engine:headline/icon.phtml'); echo $h1;?></h1>
<div class="posts-list">
   <?php if($this->reports != false && !empty ($this->reports)){?>
      <ul class="press-messages-list">
      <?php foreach ($this->reports as $report) {?>
         <li class="press-message" id="press-message-<?php echo $report->{PressReports_Model::COLUMN_ID}?>">
            <div>
               <span class="date"><?php echo vve_date("%x", new DateTime($report->{PressReports_Model::COLUMN_TIME_ADD}))?></span> /
               <a href="<?php echo $this->dataDir.$report->{PressReports_Model::COLUMN_FILE}?>" title="<?php echo $this->tr('Zobrazit')?>">
               <?php ps($report->{PressReports_Model::COLUMN_NAME})?>
               </a>
               <?php if($report->{PressReports_Model::COLUMN_AUTHOR} != null){?>
               <span class="author">(<?php ps($report->{PressReports_Model::COLUMN_AUTHOR})?>)</span>   
               <?php }?>
               <?php  echo $report->toolbox?>
            </div>
         </li>
      <?php }?>
      </ul>
   <?php } else if($this->category()->getRights()->isWritable()) {?>
      <div class="admin-info-text"><?php  echo $this->tr('Žádná tisková zpráva nebyla vložena. Zprávu nahrajete pomocí nástrojů.'); ?></div>
   <?php } else {?>
      <div class="post text">
         <?php echo $this->tr('Žádná tisková zpráva nebyla vložena.'); ?>
      </div>
   <?php }?>
</div>

