<?php 
$h1 = $this->category()->getName();
echo $this->toolbox;
?>
<h1><?php $this->includeFile('tpl://engine:headline/icon.phtml'); echo $h1;?></h1>
<div class="main-content-list">
   <?php if($this->text != false && (string)$this->text->{Text_Model::COLUMN_TEXT} != null){?>
   <div class="main-content-text">
      <?php echo $this->filter((string)$this->text->{Text_Model::COLUMN_TEXT}, array('anchors','emoticons'))?>
      <hr class="reseter" />
   </div>   
   <?php } else if($this->category()->getRights()->isWritable()) {?>
      <p class="admin-info-text"><?php echo $this->tr('Úvodní text projektů není definován.');?></p>
   <?php }?>
   <?php if(!empty ($this->projects)) {?>
      <div class="main-content-list-records">
      <ul>
      <?php foreach ($this->projects as $project) {
         $imageFile = null;
         if($project->{Projects_Model_Projects::COLUMN_THUMB} != null){
            $imageFile = $this->dataDir.$project->{Projects_Model_Projects::COLUMN_URLKEY}.'/'.$project->{Projects_Model_Projects::COLUMN_THUMB};
         } else if($project->{Projects_Model_Projects::COLUMN_IMAGE} != null){
            $imageFile = $this->dataDir.$project->{Projects_Model_Projects::COLUMN_URLKEY}.'/'.$project->{Projects_Model_Projects::COLUMN_IMAGE};
         }
         ?>
         <li>
            <a href="<?php echo $this->link()->route('project', array('prkey' => $project->{Projects_Model_Projects::COLUMN_URLKEY}))?>"
               title="<?php echo htmlspecialchars($project->{Projects_Model_Projects::COLUMN_NAME})?>"><?php 
               if($imageFile != null){?><img src="<?php echo $imageFile?>" alt="<?php echo $project->{Projects_Model_Projects::COLUMN_NAME}?>" width="50" /><?php }?>
               
               <?php echo htmlspecialchars($project->{Projects_Model_Projects::COLUMN_NAME})?>
            </a>
         </li>
      <?php }?>
      </ul>
      </div>
   <?php 
   } else {?>
      <p class="admin-info-text"><?php echo $this->tr('Není vložen žádný projekt');?></p>
   <?php }?>
</div>
