<?
$h1 = $this->category()->getName();
echo $this->toolbox;
?>
<h1><?$this->includeFile('tpl://engine:headline/icon.phtml'); echo $h1;?></h1>
<div class="main-content-list">
   <?if($this->text != false && (string)$this->text->{Text_Model::COLUMN_TEXT} != null){?>
   <div class="main-content-text">
      <?=$this->filter((string)$this->text->{Text_Model::COLUMN_TEXT}, array('anchors','emoticons'))?>
      <hr class="reseter" />
   </div>   
   <?} else if($this->category()->getRights()->isWritable()) {?>
      <p class="admin-info-text"><?=$this->tr('Úvodní text projektů není definován.');?></p>
   <?}?>
   <?if(!empty ($this->projects)) {?>
      <div class="main-content-list-records">
      <ul>
      <?foreach ($this->projects as $project) {
         $imageFile = null;
         if($project->{Projects_Model_Projects::COLUMN_THUMB} != null){
            $imageFile = $this->dataDir.$project->{Projects_Model_Projects::COLUMN_URLKEY}.'/'.$project->{Projects_Model_Projects::COLUMN_THUMB};
         } else if($project->{Projects_Model_Projects::COLUMN_IMAGE} != null){
            $imageFile = $this->dataDir.$project->{Projects_Model_Projects::COLUMN_URLKEY}.'/'.$project->{Projects_Model_Projects::COLUMN_IMAGE};
         }
         ?>
         <li>
            <a href="<?=$this->link()->route('project', array('prkey' => $project->{Projects_Model_Projects::COLUMN_URLKEY}))?>"
               title="<?=htmlspecialchars($project->{Projects_Model_Projects::COLUMN_NAME})?>"><?
               if($imageFile != null){?><img src="<?=$imageFile?>" alt="<?=$project->{Projects_Model_Projects::COLUMN_NAME}?>" width="50" /><?}?>
               
               <?=htmlspecialchars($project->{Projects_Model_Projects::COLUMN_NAME})?>
            </a>
         </li>
      <?}?>
      </ul>
      </div>
   <?
   } else {?>
      <p class="admin-info-text"><?=$this->tr('Není vložen žádný projekt');?></p>
   <?}?>
</div>
