<li class="open" id="rootDir" rel="root"><a href="#"><ins>&nbsp;</ins>data</a>
   <ul>
      <?
      function printDirs($dirList, $root = true) {
         foreach ($dirList as $key => $dir) {
            print ('<li rel="child-edit"><a href="#"><ins>&nbsp;</ins>'.$key.'</a>');
            if(!empty ($dir['childs'])) {
               print ('<ul>');
               printDirs($dir['childs']);
               print ('</ul>');
            }
            print('</li>');
         }
      }
      printDirs($this->dirs);
      ?>
   </ul>
</li>
