<?php
if (!$this->structure) {
   return;
}

if (!defined('M_NAVIGATION_PANEL_GOTO')) {

   define('M_NAVIGATION_PANEL_GOTO', $this->tr('Přejít na'));

   function navPanelRenderStructure($structure, $level = 1)
   {
      if (empty($structure))
         return null;
      $retStr = null;
      $retStr .= '<div class="module-navigation-container module-navigation-level-' . $level . '">';
      foreach ($structure as $item) {
         $retStr .= '<div>'
            . '<a class="products-panel" href="' . $item['link'] . '" title="' . M_NAVIGATION_PANEL_GOTO . ' ' . htmlspecialchars($item['name']) . '">'
            . '<img class="panel-img" src="' . $item['category']->getImage() . '" height="60" /> '
            . htmlspecialchars($item['name']) . '</a>';
         if (!empty($item['childs'])) {
            $retStr .= navPanelRenderStructure($item['childs'], $level + 1);
         }
         $retStr .= '</div>';
      }
      $retStr .= '</div>';
      return $retStr;
   }

}
$icon = null;
if ($this->panelObj()->getIcon() != null) {
   $icon = '<img src="' . Panel_Obj::getIconDir() . $this->panelObj()->getIcon() . '" alt="' . $this->panelObj()->getIcon() . '" />';
}
$backImg = null;
if ($this->panelObj()->getBackImage() != null) {
   $backImg = 'background-image: url(\'' . Panel_Obj::getBackImgDir() . $this->panelObj()->getBackImage() . '\');';
}
$form = Auth::getAuthenticator('internal')->getLoginForm();
?>
<h2 class="h1">
   <?php echo $icon ?><a href="<?php echo $this->l(); ?>" title="<?php psa($this->panelObj()->getName()) ?>"
      ><?php ps($this->panelObj()->getName()) ?></a>
</h2>
<div class="content" style="<?php echo $backImg ?>">
   <?php
   echo navPanelRenderStructure($this->structure);
   ?>
</div>