<?
$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
?>
<p class="panelLabel"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->panelObj()->getName())?>"><?=$this->panelObj()->getName()?></a></p>
<div class="panelText" style="<?=$backImg?>">
   <?=$this->text->{Text_Model_Detail::COLUMN_TEXT}?><br />
</div>
<p class="panelLinkMore">
   <a href="<?=$this->link()?>"
      title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->tr('Více')?></a>
</p>