<?
$icon = null;
if($this->panel->{Model_Panel::COLUMN_ICON} != null){
   $icon = '<img src="'.Panel::getIconDir().$this->panel->{Model_Panel::COLUMN_ICON}.'" alt="'.$this->panel->{Model_Panel::COLUMN_ICON}.'" />';
}
$backImg = null;
if($this->panel->{Model_Panel::COLUMN_BACK_IMAGE} != null){
   $backImg = 'background-image: url(\''.Panel::getBackImgDir().$this->panel->{Model_Panel::COLUMN_BACK_IMAGE}.'\');';
}
?>
<p class="panelLabel"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->category()->getLabel()?></a></p>
<div class="panelText" style="<?=$backImg?>">
   <?=$this->shortText->{Text_Model_Detail::COLUMN_TEXT_PANEL}?><br />
</div>
<p class="panelLinkMore">
   <a href="<?=$this->link()?>"
      title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->_('Více')?></a>
</p>