<?php 
$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
?>
<p class="panelLabel"><?php echo $icon?><a href="<?php echo $this->link()?>" title="<?php echo htmlspecialchars($this->panelObj()->getName())?>"><?php echo $this->panelObj()->getName()?></a></p>
<div class="panelText" style="<?php echo $backImg?>">
   <?php echo $this->text->{Text_Model_Detail::COLUMN_TEXT}?><br />
</div>
<p class="panelLinkMore">
   <a href="<?php echo $this->link()?>"
      title="<?php echo htmlspecialchars($this->category()->getLabel())?>"><?php echo $this->tr('Více')?></a>
</p>