<?
if($this->text != false AND (string)$this->text->{Text_Model_Detail::COLUMN_LABEL} != null) {
   $this->addPageTitle($this->text->{Text_Model_Detail::COLUMN_LABEL});
   $h1 = $this->text->{Text_Model_Detail::COLUMN_LABEL};
} else {
   $h1 = $this->category()->getName();
}
?>
<h1><?=$h1;?></h1>
<div class="main-content-detail">
<div class="main-content-text">
   <?
   if($this->text != false AND (string)$this->text->{Text_Model_Detail::COLUMN_TEXT} != null) {
      echo ($this->text->{Text_Model_Detail::COLUMN_TEXT});
   } else {
      echo ($this->_("Text nebyl definován, vytvoříte jej v administraci"));
   }
   ?>
</div>
</div>
<?
if($this->text != null AND strpos((string)$this->text->{Text_Model_Detail::COLUMN_TEXT}, 'pirobox') !== false){
$this->addJsPlugin(new JsPlugin_PiroBox())?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         $().piroBox({
            my_speed: 300, //animation speed
            bg_alpha: 0.8, //background opacity
            radius: 4, //caption rounded corner
            scrollImage : false, // true == image follows the page _|_ false == image remains in the same open position
            // in some cases of very large images or long description could be useful.
            slideShow : 'slideshow', // true == slideshow on, false == slideshow off
            slideSpeed : 3, //slideshow
            pirobox_next : 'piro_next', // Nav buttons -> piro_next == inside piroBox , piro_next_out == outside piroBox
            pirobox_prev : 'piro_prev', // Nav buttons -> piro_prev == inside piroBox , piro_prev_out == outside piroBox
            close_all : '.piro_close' // add class .piro_overlay(with comma)if you want overlay click close piroBox
         });
      });
      /* ]]> */
</script>
<?}

if($this->toolbox != null) $this->includeTplObj($this->toolbox);
?>
