<?
if($this->text != false AND (string)$this->text->{Text_Model_Detail::COLUMN_LABEL} != null) {
   $this->addPageTitle($this->text->{Text_Model_Detail::COLUMN_LABEL});
   $h1 = $this->text->{Text_Model_Detail::COLUMN_LABEL};
} else {
   $h1 = $this->category()->getName();
}
?>
<h1><?=$h1;?></h1>
<div class="main-content-detail">
<div class="main-content-text">
   <?
   if($this->text != false AND (string)$this->text->{Text_Model_Detail::COLUMN_TEXT} != null) {
      echo ($this->text->{Text_Model_Detail::COLUMN_TEXT});
   } else {
      echo ($this->_("Text nebyl definován, vytvoříte jej v administraci"));
   }
   ?>
</div>
</div>
<?
if($this->text != null AND strpos((string)$this->text->{Text_Model_Detail::COLUMN_TEXT}, 'pirobox') !== false){
$this->addJsPlugin(new JsPlugin_PiroBox())?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         $().piroBox({
            slideShow : true, // true == slideshow on, false == slideshow off
            slideSpeed : 3 //slideshow
         });
      });
      /* ]]> */
</script>
<?}

if($this->toolbox != null) $this->includeTplObj($this->toolbox);
?>
