<h1><?php ps($this->h1)?></h1>
<div class="main-content-form-edit" id="text-edit-form">
   <?php if($this->previewLink){?>
      <div class="message message-info message-warning"><?php  
         printf($this->tr('Máte již vytvořenu starší verzi dokumentu. Chcete ji <a href="%s"><strong>otevřít</strong></a> nebo <a href="%s"><strong>zrušit</strong></a>?'),
                $this->previewLink, $this->previewLinkCancel); 
      ?></div>   
   <?php }
   
   $this->form->text->html()->setAttrib('cols', 60)->setAttrib('rows', 40);
   $this->form->send->cancel->html()->addClass('cancel');
   $this->form->send->cancel->html()->setAttrib('onclick', 'return confirm(\''.$this->tr('Opravdu zrušit změny?').'\')');
   $this->form->send->preview->html()->addClass('exclusive');
   echo ($this->form);
   ?>
</div>