<?php 
// načtení detailu
//$this->addCssFile("style.css");
$this->addPageTitle($this->band->{Bands_Model::COLUMN_NAME});
$this->addPageHeadline($this->band->{Bands_Model::COLUMN_NAME});




$showClass = null;
if ($this->band->{Bands_Model::COLUMN_PUBLIC} == 0) {
   $showClass = 'article-detail-no-public';
}
?>

<div class="article-detail band-detail <?php echo $showClass
?>">
   <div class="article-detail-box-image bands-detail-box-image">
      <?php echo vve_tpl_image_tag($this->category()->getModule()->getDataDir(true)
        . $this->band->{Bands_Model::COLUMN_IMAGE}, $this->band->{Bands_Model::COLUMN_IMAGE}, 200, 150); ?>
      </div>
      <?php echo $this->band->{Bands_Model::COLUMN_TEXT}
?>
      <hr class="reseter" />

</div>
   <?php 
   // pokud je v textu třída pirobox načteme plugin
   if (strpos($this->band->{Bands_Model::COLUMN_TEXT}, 'pirobox')) {
      $piroBox = new JsPlugin_PiroBox();
      $this->addJsPlugin($piroBox);
   ?>

         <script type="text/javascript">
            /* <![CDATA[ */
            $(document).ready(function(){
               $().piroBox({
                  my_speed: 300, //animation speed
                  bg_alpha: 0.8, //background opacity
                  radius: 4, //caption rounded corner
                  scrollImage : false, // true == image follows the page _|_ false == image remains in the same open position
                  // in some cases of very large images or long description could be useful.
                  slideShow : 'slideshow', // true == slideshow on, false == slideshow off
                  slideSpeed : 3, //slideshow
                  pirobox_next : 'piro_next', // Nav buttons -> piro_next == inside piroBox , piro_next_out == outside piroBox
                  pirobox_prev : 'piro_prev', // Nav buttons -> piro_prev == inside piroBox , piro_prev_out == outside piroBox
                  close_all : '.piro_close' // add class .piro_overlay(with comma)if you want overlay click close piroBox
               });
            });

            /* ]]> */
         </script>
   <?php 
}

$this->includeTpl('articletools.phtml', true, array(
    'lastEditTime' => $this->band->{Bands_Model::COLUMN_EDIT_TIME},
    'lastEditUser' => $this->band->{Model_Users::COLUMN_USERNAME},
    'showed' => $this->band->{Bands_Model::COLUMN_SHOWED},
    'linkToPdf' => $this->link()->route('detailExport', array('output' => 'pdf'))->rmparam(),
    'linkToHtml' => $this->link()->route('detailExport', array('output' => 'html'))->rmparam(),
    'shares' => $this->shares));
   ?>

<?php  echo $this->toolbox; // TOOLBOX ?>
<?php  $this->includeTpl("buttonback.phtml", true); ?>
