<?php  
$jsJqGrid = new Component_JqGrid_JsPlugin();
$this->addJsPlugin($jsJqGrid);
?>
<h1><?php echo  $this->tr('Měny a daně') ?></h1>
<?php 
$this->includeFile('tpl://nav.phtml');
?>
<div class="main-content-form-edit">
   <?php  echo $this->form; ?>
   <h2><?php echo $this->tr('Daně')?></h2>
   <table id="table-taxes"></table>
   <div id="table-taxes-pager"></div>
   <hr class="reseter" />
</div>

<script type="text/javascript" charset="utf-8">
   /* <![CDATA[ */
   var selectedGroupId = 0;
      $(document).ready(function() {
         var taxesGrid = $("#table-taxes").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url: '<?php echo $this->link()->route('taxesList');?>',
            datatype: "json",
            colNames:['<?php echo $this->tr('Název')?>', '<?php echo $this->tr('Hodnota v %')?>'],
            colModel:[
               {name:'<?php echo Shop_Model_Tax::COLUMN_NAME?>',
                index:'<?php echo Shop_Model_Tax::COLUMN_NAME?>', width:130, editable:true, editoptions:{size:20},
                formoptions:{ rowpos:1, label: "<?php echo $this->tr('Název')?>",elmprefix:"(*)"}},
               {name:'<?php echo Shop_Model_Tax::COLUMN_VALUE?>',
                index:'<?php echo Shop_Model_Tax::COLUMN_VALUE?>', width:130,editable:true,editoptions:{size:20},
                formoptions:{ rowpos:2, label: "<?php echo $this->tr('Hodnota')?>",elmprefix:"(*)"}},
            ],
            rowNum:5,
            rowList:[5,10,20,50],
            pager: '#table-taxes-pager',
            sortname: '<?php echo Shop_Model_Tax::COLUMN_NAME?>',
            caption:"Seznam daní",
            jsonReader: {
               repeatitems : false, root:"rows"
            },
            height: 'auto',
            autowidth : true,
            editurl:"<?php echo $this->link()->route('editTax')?>"
         });
         taxesGrid.jqGrid('navGrid','#table-taxes-pager',
            {edit:true,add:true,del:true,search:false},
            // edit options
            {reloadAfterSubmit:true, jqModal:true, closeOnEscape:true,viewPagerButtons:false, 
               bottominfo:"<?php echo $this->tr('Položky označené (*) jsou povinné')?>",closeAfterEdit:true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },
            // add options
            {reloadAfterSubmit:true,jqModal:true, closeOnEscape:true, 
               bottominfo:"<?php echo $this->tr('Položky označené (*) jsou povinné')?>", closeAfterAdd: true,
               afterSubmit : function(respond){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            },  
            // del options
            {reloadAfterSubmit:true, jqModal:true, closeOnEscape:true, width: 300,
               afterSubmit : function(respond, postdata){
                  var res = eval("("+respond.responseText+")");
                  var msg = res.errmsg.toString();
                  if(res.infomsg.length > 0){
                     msg = res.infomsg.toString();
                  }
                  return [res.allOk,msg];
               }
            }
         );
      });
   /* ]]> */
</script>
