<?php 
if(!empty($this->groups)){
   foreach( $this->groups as $group ) {?>
   <li id="attrgroup-<?php echo $group->getPK()?>"
       class="ui-state-default clearfix"
       data-id="<?php echo $group->getPK()?>"
       data-name="<?php echo $group->{Shop_Model_AttributesGroups::COLUMN_NAME}?>"
       >

      <span class="move ui-icon ui-icon-arrowthick-2-n-s"></span>
      <a href="<?php echo $this->link()->clear()->route('variantsList', array('idg' => $group->getPK()))?>"
         onclick="ShopVariants.selectGroup(this); return false;"
         class="name"><?php ps_lang($group->{Shop_Model_AttributesGroups::COLUMN_NAME})?></a>
            <span class="controls">
               <a href="<?php echo $this->link()->param('g', $group->{Shop_Model_AttributesGroups::COLUMN_ID})
                  ->param('editg', $group->{Shop_Model_AttributesGroups::COLUMN_ID})?>"
                  onclick="ShopVariants.editGroup(<?php echo $group->getPK()?>); return false;"
                  class="button-edit-group"><img src="/images/icons/pencil.png" /></a>
               <a href="<?php echo $this->link()->param('deleteg', $group->{Shop_Model_AttributesGroups::COLUMN_ID})?>"
                  onclick="ShopVariants.deleteGroup(<?php echo $group->getPK()?>); return false;"
                  class="button-delete-group"><img src="/images/icons/delete.png" /></a>
            </span>
   </li>
   <?php }
} else {?>
   <li><?php ps($this->tr('Není vytvořen žádný parametr'))?></li>
<?php }?>