<?php if($this->sys()->rights()->isWritable()) {
      $this->includeTplObj($this->toolbox);
}?>

<?php foreach ($this->contacts as $contact) {?>
<div class="contact">
   <h2><?php echo $contact["name"]?></h2>
   <a href="<?php echo $this->module()->getDir()->getDataDir().$contact[Contacts_Model_Detail::COLUMN_CONTACT_FILE]?>"
      title="<?php echo $this->_("Budova kontaktu")?> <?php echo $contact["name"]?>" rel="lightbox">
      <img src="<?php echo $this->module()->getDir()->getDataDir()."small/".$contact[Contacts_Model_Detail::COLUMN_CONTACT_FILE]?>"
        alt="image<?php echo $contact[Contacts_Model_Detail::COLUMN_CONTACT_FILE]?> " />
   </a>
   <b><?php echo $contact["name_type"]?></b>
   <?php echo $contact[Contacts_Model_Detail::COLUMN_CONTACT_TEXT];?>
   <?php if($this->sys()->rights()->isWritable()){?>
   <br />Priorita:<?php echo $contact['priority']?><br />
   <?php $this->includeTplObj($contact['toolbox'])?>
   <?php }?>
   <hr class="reseter" />
</div>
<?php }?>

<script type="text/javascript">
   $(function() {
      $('.contact>a').lightBox();
   });
</script>
