<div class="ui-widget ui-widget-upload">
   <h2 class="ui-widget-header"><?=$this->tr('Přidání obrázků')?></h2>
   <div class="swfupload-control ui-widget-content">
      <form action="<?=$this->link()?>" method="post">
         <p><strong><?=$this->tr('Obrázky')?>:</strong>
            <span id="spanButtonPlaceholder"></span>
            <button name="upload-button"><?=$this->tr('Vybrat obrázky')?></button>
            &nbsp;&nbsp;Optimalizovat nahrání:<input id="optimalise-upload" type="checkbox" value="true" checked="checked" /><br /></p>
         <p class="note"><?= $this->tr('Pro bezproblémové nahrání obrázků by měl být instalován Flash Player verze 10. Velikost obrázků je měněna přímo v prohížeči, proto nahrání
         může trvat déle. Pokud je obrázek typu "png" a má velké rozlišení, jeho změna velikosti bude trvat také dlouho.<br/>
         Pokud se při nahrávání vyskytnou chyby, zkuste obnovit stránku a nahrát soubory znovu.)'); ?></p>
      </form>
      <p><span id="queuestatus" ><?=$this->tr('Vybráno souborů')?>: 0 / <?=$this->tr('Zařazeno souborů')?>: 0</span></p>
      <ol id="upload-files-log"></ol>
   </div>
</div>
<br/>
<script type="text/javascript">
   /* <![CDATA[ */
   $(document).ready(function() {
      $('.swfupload-control').swfupload({
         // Backend Settings
         upload_url: "<?= $this->link()->route('uploadFile'); ?>",    // Relative to the SWF file (or you can use absolute paths)
         file_post_name: "addimage_image",
         post_params: {'sessionid': '<?= session_id(); ?>', 'addimage_send' : 'send', 'addimage_idArt' : <?= $this->addForm->idArt->getUnfilteredValues() ?>},
         file_size_limit : "10048", // 100MB
         file_types : "*.jpg;*.jpeg;*.png;*.JPG;*.JPEG;*.PNG",
         file_types_description : "<?=$this->tr('Obrázky');?>",
         file_upload_limit : 150,
         file_queue_limit : 0,
         button_placeholder_id : "spanButtonPlaceholder",
         button_width: 90,
         button_height: 22,
         button_window_mode: SWFUpload.WINDOW_MODE.TRANSPARENT,
         button_cursor: SWFUpload.CURSOR.HAND,
         debug: <?if(VVE_DEBUG_LEVEL > 1){echo "true";}else{echo "false";};?>,
         // Flash Settings
         flash_url : "<?=Url_Request::getBaseWebDir()?>/jscripts/swfupload/swfupload.swf",
         flash9_url : "<?=Url_Request::getBaseWebDir()?>/jscripts/swfupload/swfupload_fp9.swf",
         custom_settings : { // added setting for JQuery SWFUpload plugin
            r_width: <?=$this->category()->getParam('medium_width',Photogalery_Controller::MEDIUM_WIDTH)?>,
            r_height: <?=$this->category()->getParam('medium_height',Photogalery_Controller::MEDIUM_HEIGHT)?>,
            r_quality: 100
         }
      });

      // assign our event handlers
      $('.swfupload-control')
      .bind('fileQueued', function(event, file){
         var listitem='<li id="'+file.id+'" >'+
         '<em>'+file.name+'</em> ('+Math.round(file.size/1024)+' KB) <span class="progressvalue" >'
         +'</span><span class="status" > <?=$this->tr('Čekám')?></span>'
         +'<p class="progressbar" ><span class="progress" ></span></p><span class="cancel" >&nbsp;</span>'+'</li>';
         $('#upload-files-log').append(listitem);
         $('li#'+file.id+' .cancel').bind('click', function(){ //Remove from queue on cancel click
            var swfu = $.swfupload.getInstance('.swfupload-control');
            swfu.cancelUpload(file.id);
            $('li#'+file.id).slideUp('fast');
         });
         // start the upload once a file is queued
         if($('input#optimalise-upload').is(":checked")){
            $(this).swfupload('startResizedUpload');
         } else {
            $(this).swfupload('startUpload');
         }
      })
      .bind('uploadComplete', function(event, file){
         if($('input#optimalise-upload').is(":checked")){
            $(this).swfupload('startResizedUpload');
         } else {
            $(this).swfupload('startUpload');
         }
      })
      .bind('fileQueueError', function(event, file, errorCode, message){alert('<?=$this->tr('Velikost souboru')?> '+file.name+' <?=$this->tr('je větší než povolený limit')?>');})
      .bind('fileDialogComplete', function(event, numFilesSelected, numFilesQueued){
         $('#queuestatus').text('<?=$this->tr('Vybráno souborů')?>: '+numFilesSelected+' / <?=$this->tr('Zařazeno souborů')?>: '+numFilesQueued);
      })
      .bind('uploadResizeStart', function(event, file){
         $('#upload-files-log li#'+file.id).find('span.status').text(' <?=$this->tr('Měním velikost')?>');
         $('#upload-files-log li#'+file.id).find('span.cancel').hide();
      })
      .bind('uploadStart', function(event, file){ // kvůli flash9
         $('#upload-files-log li#'+file.id).find('span.status').text(' <?=$this->tr('Odesílám')?>...');
         $('#upload-files-log li#'+file.id).find('span.progressvalue').text('0%');
         $('#upload-files-log li#'+file.id).find('span.cancel').hide();
      })
      .bind('uploadProgress', function(event, file, bytesLoaded){//Show Progress
         var percentage=Math.round((bytesLoaded/file.size)*100);
         $('#upload-files-log li#'+file.id).find('span.progress').css('width', percentage+'%');
         $('#upload-files-log li#'+file.id).find('span.progressvalue').text(percentage+'% ');
      })
      .bind('uploadSuccess', function(event, file, serverData){
         $('#upload-files-log li#'+file.id).animate({opacity:0}, 300, function(){$(this).remove()});
         // null queue reload cnt
         var stat = $.swfupload.getInstance('.swfupload-control').getStats();
         if(stat.files_queued == 0){
            $('#edit-photos-list').load(location.href+" #edit-photos-list>*","",function(){
               $('#edit-photos-list p.form-link-lang-container a:first-child').trigger('click', false);
               $().piroBox({slideShow : true,slideSpeed : 3});
               infoMsg('<?=$this->tr('Obrázky byly nahrány')?>');
            });
         }
      });
      // označení všech obrázků
      $('#button-check-all-images').live('click',function(){
         $('input.button-check-delete-image').each(function(){$(this).click();checkCheckbox(this);});
         return false;
      });
      /* zešednutí  */
      $('input.button-check-delete-image').live('click', function(){checkCheckbox(this);});
      $('input.button-check-delete-image').each(function(){checkCheckbox(this);});
      // pirobox
      $().piroBox({slideShow : true,slideSpeed : 3});
   });

   function checkCheckbox(obj){
      if($(obj).is(':checked')){
         $(obj).parents('tr').find('td').not(':first-child').css({opacity : 0.3});
      } else {
         $(obj).parents('tr').find('td').css({opacity : 1});
      }
   }
   /* ]]> */
</script>
