<?
$jq = new JsPlugin_JQuery();
$jq->addUISortable();
$jq->addUIDialog();
$this->addJsPlugin($jq);
$this->addJsPlugin(new JsPlugin_PrettyPhoto());
$this->addFile("css://photogalery:style.less");
$this->addFile("js://photogalery:editphotos.js");
?>
<h1><?
   printf($this->tr('Úprava obrázků přiřazených ke "%s"'), $this->name == null ? $this->category()->getName() : $this->name);
?></h1>
<div>
   <h2><?=$this->tr('Nahrání obrázků')?></h2>
   <div id="image-uplaod-component" class="drop-area clearfix">
      <?
      $this->uploadForm->html()
          ->setAttrib('id', 'images-upload-form')
//          ->setAttrib('target', 'upload-target')
          ;
      echo $this->uploadForm->renderStart();
      ?>
      <div class="form-group">
         <div class="coll-input">
            <div class="form-controls">
            <?
            echo $this->uploadForm->image->control();
            ?>
            <div class="drop-area-label"><?  ps($this->tr('Nebo zde přetáhněte obrázky'))?></div>
            </div>
         </div>
         <div class="coll-buttons">
            <div class="form-controls">
               <?
               echo $this->uploadForm->idItem->control();
               echo $this->uploadForm->send->control();
               ?>
               <a class="btn btn-danger" href="<?=$this->linkBack?>">Zavřít</a>
            </div>
         </div>
      </div>
      <? 
      echo $this->uploadForm->renderEnd();
      ?>
      <iframe src="<?=$this->link()->route('imageUploadIframe')?>" id="upload-target" frameborder="0" width="0" height="0"></iframe>
      <ul id="upload-queue" class="unstyled">
         
      </ul>
      <ul id="upload-queue-tpl" class="hidden">
         <li class="clearfix">
            <span class="col-left">
               <span class="thumbnail"><img src="" /></span>
            </span>
            <span class="col-right">
               <span class="name"></span>
               <span class="progress">
                  <span class="progress-bar" role="progressbar" style="width: 0%;">0%</span>
               </span>
            </span>
            <a class="button-cancel-upload" href="<?=$this->link()?>#cancel"><span class="icon icon-times"></span></a>
         </li>
      </ul>
   </div>
   
   <h2><?=$this->tr('Seznam uložených obrázků')?></h2>
   <ul id="images-list" class="unstyled drop-area clearfix">
      <?
      foreach ($this->images as $image) {
         $src = $this->category()->module()->getDataDir(true).$this->imagesPath.Photogalery_Controller::DIR_ORIGINAL."/".$image->{PhotoGalery_Model_Images::COLUMN_FILE};
         $srcThumb = Utils_Image::cache($src, Photogalery_Controller::EDIT_THUMB_WIDTH, Photogalery_Controller::EDIT_THUMB_HEIGHT);
         ?>
      <li 
         id="image-<?=$image->getPK()?>"
         data-id="<?=$image->getPK()?>"
         data-name='<?=json_encode($image->{PhotoGalery_Model_Images::COLUMN_NAME}->toArray())?>'
         data-desc='<?=json_encode($image->{PhotoGalery_Model_Images::COLUMN_DESC}->toArray())?>'
         data-src="<?=$src?>"
         class="image-box"
         >
         <span class="image-title" title="<?  ps($image->{PhotoGalery_Model_Images::COLUMN_NAME})?>"><?  ps($image->{PhotoGalery_Model_Images::COLUMN_NAME})?></span>
         <input type="checkbox" name="imagesSelect" class="image-checkbox" />
         <span class="image-thumb">
            <img src="<?=$srcThumb?>" alt="" />
         </span>
         <span class="image-tools clearfix">
            <?
            /* @var $this->imageToolbox Template_Toolbox2 */
            $this->imageToolbox->setTemplate(Template_Toolbox2::TEMPLATE_INLINE);
            echo $this->imageToolbox;
            ?>
         </span>
      </li>
      <?}?>
   </ul>
   <ul class="hidden" id="image-tpl">
      <li data-id="" data-name="" data-desc="" data-src="" class="image-box" >
         <span class="image-title" title=""></span>
         <input type="checkbox" name="imagesSelect" class="image-checkbox" />
         <span class="image-thumb">
            <img src="" alt="" />
         </span>
         <span class="image-tools clearfix">
            <?
            /* @var $this->imageToolbox Template_Toolbox2 */
            $this->imageToolbox->setTemplate(Template_Toolbox2::TEMPLATE_INLINE);
            echo $this->imageToolbox;
            ?>
         </span>
      </li>
   </ul>
   <?/*
   <div class="form-group">
      <div class="form-controls">
         <div class="input-group">
            <label for="images-oprtation"><?php ps($this->tr('Označené')); ?></label>
            <select name="images-oprtation" class="form-control" id="select-images-oprtation">
               <option value="delte"><?ps($this->tr('Smazat'))?></option>
            </select>
            <button type="button" class="input-group-btn"><span class="icon icon-check"></span></button>
         </div>
      </div>
   </div>
    */?>
   <div id="dialog-image-labels">
      <?
      $this->editLabelsForm->text->html()->setAttrib('rows', 7);
      echo $this->editLabelsForm;
      ?>
   </div>
 <?/*  
<div class="modal fade">
   <div class="modal-dialog">
      <div class="modal-content">
         <?=$this->editLabelsForm->renderStart();?>
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Modal title</h4>
         </div>
         <div class="modal-body">
            <div class="form-group">
               <div class="form-labels">
                  <?=$this->editLabelsForm->name->label()?>
               </div>
               <div class="form-controls">
                  <?=$this->editLabelsForm->name->controlAll()?>
               </div>
            </div>
            <div class="form-group">
               <div class="form-labels">
                  <?=$this->editLabelsForm->text->label()?>
               </div>
               <div class="form-controls">
                  <?=$this->editLabelsForm->text->controlAll()?>
               </div>
            </div>
         </div>
         <div class="modal-footer">
            <?=$this->editLabelsForm->id->controlAll()?>
            <?=$this->editLabelsForm->buttons->controlAll()?>
         </div>
         <?=$this->editLabelsForm->renderEnd();?>
      </div><!-- /.modal-content -->
   </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
   */?>
   <script type="text/javascript">
      $(document).ready(function(){
         CubeImagesEditor.init({
            uploadImageUrl : '<?=$this->link()->route('imageUploadAjax')?>',
            imageDeleteUrl : '<?=$this->link()->route('imageDelete')?>',
            imageMoveUrl : '<?=$this->link()->route('imageMove')?>',
            imageRotateUrl : '<?=$this->link()->route('imageRotate')?>',
            editLabelsUrl : '<?=$this->link()->route('imageEditLabels')?>',
            
            getImagesUrl : '<?=$this->link()->route('getImages')?>'
         });
      });
   </script>
</div>