<?
$this->addPageTitle($this->_('úprava obrázků'));
$this->addPageHeadline($this->_('úprava obrázků'));

?>
<div id="editImagesForm">
   <h2><?=$this->_('Přidání obrázku');?></h2>
   <form method="post" action="<?=$this->link()?>" enctype="multipart/form-data">
      <? print ($this->addForm->image->label());
      print ($this->addForm->image->labelValidations());
      print ($this->addForm->image->controll());
      print ($this->addForm->send->controll()); ?>
   </form>
   <br />
   <?$this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->l()->route(null)));?>
   <h2><?=$this->_('Úpravy obrázků');?></h2>
   <form method="post" action="<?=$this->link()?>">
      <p align="right">
         <?=$this->editForm->save->controll()?>
      </p>
      <table>
         <?while ($image = $this->images->fetch()) {
            ?>
         <tr>
            <td width="100" style="border-bottom: 1px solid gray">
               <img src="<?=$this->category()->getModule()->getDataDir(true).Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                           .$image->{PhotoGalery_Model_Images::COLUMN_FILE}?>" />
            </td>
            <td valign="top" style="padding-right:10px; border-bottom: 1px solid gray">
                  <?
                  $this->editForm->name->setDimensional($image->{PhotoGalery_Model_Images::COLUMN_ID});
                  $this->editForm->name->setValues(array($image->{PhotoGalery_Model_Images::COLUMN_ID} =>
                      $image->{PhotoGalery_Model_Images::COLUMN_NAME}));
                  print ($this->editForm->name->label()."<br />");
                  print ($this->editForm->name->labelLangs());
                  print ($this->editForm->name->controll());
                  print ($this->editForm->name->scripts());
                  ?><br />
                  <?
                  $this->editForm->ord->setDimensional($image->{PhotoGalery_Model_Images::COLUMN_ID});
                  $this->editForm->ord->setValues($image->{PhotoGalery_Model_Images::COLUMN_ORDER});
                  print ($this->editForm->ord->label());
                  print ($this->editForm->ord->controll()->setAttrib('size', 5));
                  print ($this->editForm->ord->scripts());
                  ?>
                  <?
                  $this->editForm->delete->setDimensional($image->{PhotoGalery_Model_Images::COLUMN_ID});
                  $this->editForm->delete->setValues(false);
                  print ($this->editForm->delete->label());
                  print ($this->editForm->delete->controll()->setAttrib('onclick', "if(this.checked == true)return confirm('Smazat?')"));
                  print ($this->editForm->delete->scripts());
                  ?><br />

            </td>
            <td valign="top" style="border-bottom: 1px solid gray">
                  <?
                  $this->editForm->desc->setDimensional($image->{PhotoGalery_Model_Images::COLUMN_ID});
                  $this->editForm->desc->setValues(array($image->{PhotoGalery_Model_Images::COLUMN_ID} =>
                      $image->{PhotoGalery_Model_Images::COLUMN_DESC}));
                  print ($this->editForm->desc->label()."<br />");
                  print ($this->editForm->desc->labelLangs());
                  print ($this->editForm->desc->controll());
                  print ($this->editForm->desc->scripts());
                  ?>
                  <?
                  $this->editForm->id->setDimensional($image->{PhotoGalery_Model_Images::COLUMN_ID});
                  $this->editForm->id->setValues($image->{PhotoGalery_Model_Images::COLUMN_ID});
                  print ($this->editForm->id->controll());
                  ?>
                  <?
                  $this->editForm->file->setDimensional($image->{PhotoGalery_Model_Images::COLUMN_ID});
                  $this->editForm->file->setValues($image->{PhotoGalery_Model_Images::COLUMN_FILE});
                  print ($this->editForm->file->controll());
                  ?>
            </td>
         </tr>

         <?}?>
      </table>
      <p align="right">
         <?=$this->editForm->save->controll()?>
      </p>
   </form>
   <?$this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->l()->route(null)));?>
</div>
