<?
$this->addCssFile("style.css");
// jquery galerka
$this->addJsPlugin(new JsPlugin_PiroBox());
?>
<h1><?echo $this->category()->getName();?></h1>
<div class="main-content-detail">
      <div class="main-content-text"><?
   if($this->text != null AND (string)$this->text->{Text_Model_Detail::COLUMN_TEXT} != null) {
      echo $this->text->{Text_Model_Detail::COLUMN_TEXT};
   } else if($this->category()->getRights()->isWritable()) {
      echo '<p class="admin-info-text">'.$this->tr('Text nebyl definován. (Tento text vidí pouze uživatelé s oprávněním zápisu)').'</p>';
   }
   //echo $this->toolboxText;
   ?></div>
   <?
   $images = $this->images;
   if(count($images) != 0){
   ?>
   <div class="main-content-images">
      <?
      $images = $this->images;
      if(count($images) == 1) {$class = 'pirobox';}
      else {$class = 'pirobox_gall';}
      foreach ($images as $image) {
         ?><a class="<?echo $class;?>" href="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir
                .Photogalery_Controller::DIR_MEDIUM.URL_SEPARATOR.$image[PhotoGalery_Model_Images::COLUMN_FILE]?>"
         title="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>"
         ><img src="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                     .$image[PhotoGalery_Model_Images::COLUMN_FILE]?>" alt="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>"
                     /></a><?
        }
        echo $this->toolboxImages;
        ?>
   </div>
    <?
   } else if($this->toolboxImages != null){?>
   <div class="admin-info-text">
      <?
      echo $this->tr('Galerie neobsahuje žádný obrázek.');
      echo $this->toolboxImages;
      ?>
   </div>
   <?}?>
   <hr class="reseter" />
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){$().piroBox({slideShow : true,slideSpeed : 3});});
      /* ]]> */
   </script>
   <?
   echo $this->toolbox;
   ?>
</div>
