<?php 
$jq = new JsPlugin_JQuery();
$jq->addUISortable();
$this->addJsPlugin($jq);
$this->addFile("css://photogalery:style.less");
?>
<h1><?php echo  $this->tr('Úprava pořadí obrázků z').' '.$this->category()->getName();?></h1>
<div class="main-content-form-edit ui-widget ui-widget-imageslist">
   <div id="images-sorter" class="ui-widget-content">
   <?php echo $this->form->renderStart();?>
   
   <ul>
      <?php foreach($this->images as $image){?>
      <li class="ui-state-default">
         <img src="<?php echo $this->category()->getModule()->getDataDir(true)
              .$this->websubdir.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
              .$image->{PhotoGalery_Model_Images::COLUMN_FILE}.'?time='.time()?>" 
              alt="<?php echo $image->{PhotoGalery_Model_Images::COLUMN_FILE}?>" width="70" />
         <?php 
         $this->form->id->setValues($image->{PhotoGalery_Model_Images::COLUMN_ID});
         echo $this->form->id->controll();
         ?>
         <a class="button-delete-image" href="#"
            title="<?php echo $this->tr('Smazat')?>"><img src="/images/icons/delete.png" /></a>
      </li>
      <?php }?>
   </ul>
      <hr class="reseter" />
      <div class="form-controlls ui-widget ui-widget-header">
         <?php  echo $this->form->save->controll(); ?>
      </div>
      <?php 
   echo $this->form->renderEnd();
   ?>

   </div>
   <script>
      $(function() {
		$( "#images-sorter ul" ).sortable({
			placeholder: "ui-state-highlight"
		});
		$( "#images-sorter ul" ).disableSelection();

      // delete image
      $('.button-delete-image').click(function(e){
         e.preventDefault();
         if(confirm('<?php echo $this->tr('Smazat obrázek?')?>')){
            // get id
            var id = $(this).parent('li').find('input.sort_image_id_class').val();
            var $item = $(this).parent('li');
            $item.fadeOut(500, function(){
               // ajax request
               $.ajax({
                  type: "POST",
                  url: "<?php echo $this->link()->route('deletephoto')?>",
                  data: {id : id},
                  success: function(msg){
                     $item.remove();
                  }
               });
            });
         }
      });
   });
   </script>
</div>