<?php 
if($this->text != false AND (string)$this->text->{Text_Model::COLUMN_LABEL} != null) {
   $this->addPageTitle($this->text->{Text_Model::COLUMN_LABEL});
   $h1 = $this->text->{Text_Model::COLUMN_LABEL};
} else {
   $h1 = $this->category()->getName();
}
if($this->toolboxPrivate == null){
   echo $this->toolbox;
   $this->toolbox = null;
}
?>
<h1><?php $this->includeFile('tpl://engine:headline/icon.phtml'); echo $h1;?> <?php echo vve_tpl_show_text_langs($this->text->{Text_Model::COLUMN_TEXT});?></h1>
<div class="main-content-detail">
   <div class="main-content-text"><?php echo ($this->filter($this->text->{Text_Model::COLUMN_TEXT},'emoticons')).$this->toolbox;?></div>
   <?php if($this->textPrivate != false AND (string)$this->textPrivate->{Text_Model::COLUMN_TEXT} != null){
      ?><div class="main-content-text"><?php echo ($this->filter($this->textPrivate->{Text_Model::COLUMN_TEXT},'emoticons')).$this->toolboxPrivate;?></div><?php 
   }
   
   // images gallery
   $this->imagesBaseDir = $this->category()->getModule()->getDataDir(true).$this->websubdir;
   $this->includeFile('tpl://engine:photogalery.phtml');
   ?>
   <hr class="reseter" />
   <?php 
   if($this->text != false){
         $this->includeTpl('articletools.phtml', true, array(
//            'lastEditTime' => $this->text->{Text_Model::COLUMN_CHANGED_TIME},
//              'lastEditUser' => $this->article->{Model_Users::COLUMN_USERNAME},
              'linkToPdf' => $this->link()->route('detailExport', array('output' => 'pdf')),
              'linkToHtml' => $this->link()->route('detailExport', array('output' => 'html')),
              'shares' => array('url' => $this->link(), 'title' => $this->category()->getName())));
      echo '<hr class="reseter" />';
   }
   ?>
</div>
<?php 
if(($this->text != null AND strpos((string)$this->text->{Text_Model::COLUMN_TEXT}, 'pirobox') !== false)
   OR ($this->textPrivate != null AND strpos((string)$this->textPrivate->{Text_Model::COLUMN_TEXT}, 'pirobox') !== false)){
   $this->addJsPlugin(new JsPlugin_PiroBox());
   ?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){$().piroBox({slideShow : true,slideSpeed : 3});});
      /* ]]> */
   </script>
<?php }?>