<?php 
$this->addFile("css://style.less");

$jq = new JsPlugin_JQuery();
$jq->addUITabs();
$jq->addUISortable();
$jq->addJQPlugin('cookie');
$this->addJsPlugin($jq);
$this->addJsPlugin(new JsPlugin_JQueryCSS());

?>
<h1><?php echo $this->category()->getName();?></h1>
<div class="content-admin">
   <div id="form-upload">
      <?php 
      echo $this->formUpload;
      ?>
   </div>
   <h2><?php ps($this->tr('Nahrané obrázky'))?></h2>
   <?php if(!empty($this->images)){?>
      <ul id="images-list" class="ui-widget ui-cube-widget">
         <?php foreach ($this->images as $img) {?>
         <li class="ui-widget-content ui-state-default slide-image-row" id="image-<?php echo $img->getPK()?>" data-id="<?php echo $img->getPK()?>">
            <ul class="tabs-links clearfix">
               <li><a class="tab-link" href="<?php echo $this->link()?>#preview-<?php echo $img->getPK()?>"><?php ps($this->tr('Náhled'))?></a></li>
               <li><a class="tab-link" href="<?php echo $this->link()?>#edit-<?php echo $img->getPK()?>"><?php ps($this->tr('Úprava'))?></a></li>
            </ul>
            <div class="tab tab-preview" id="preview-<?php echo $img->getPK()?>">
               <img class="image-slide" src="<?php echo $this->imagesUrl.$img->{HPSlideShow_Model::COLUMN_FILE}?>" />
               <?if((string)$img->{HPSlideShow_Model::COLUMN_LABEL} != null){?>
                  <div class="image-label"><?echo vve_get_lang_string($img->{HPSlideShow_Model::COLUMN_LABEL})?></div>
               <?}?>
               <div class="link-info">
               <?php if((string)$img->{HPSlideShow_Model::COLUMN_LINK} != null){?>
                  <?php ps($this->tr('Odkaz na'))?>:
                   <a href="<?php echo $img->{HPSlideShow_Model::COLUMN_LINK}?>" class="link-external"><?php ps($img->{HPSlideShow_Model::COLUMN_LINK})?></a>
               <?php } else if($img->{HPSlideShow_Model::COLUMN_ID_CAT} != 0){?>
                   <?php ps($this->tr('Odkaz na kategorie'))?>:
                  <a href="<?php echo $this->link()->clear()->category($img->{Model_Category::COLUMN_URLKEY})?>" class="link-external">
                     <?php ps($img->{Model_Category::COLUMN_NAME});?>
                  </a>
               <?php } else {?>
                  <?php ps($this->tr('Nemá proklik'))?>.
               <?php }?>
               </div>
            </div>
            <div class="tab" id="edit-<?php echo $img->getPK()?>">
               <?php 
               $this->formEdit->setAction($this->link()->anchor('image-'.$img->getPK()));
               $this->formEdit->html()->addClass('form-edit-image');
               $this->formEdit->id->setValues($img->{HPSlideShow_Model::COLUMN_ID});
               $this->formEdit->catId->setValues($img->{HPSlideShow_Model::COLUMN_ID_CAT});
               $this->formEdit->link->setValues($img->{HPSlideShow_Model::COLUMN_LINK});
               $this->formEdit->label->setValues($img->{HPSlideShow_Model::COLUMN_LABEL});
               echo $this->formEdit;
               ?>
            </div>
            <div class="slide-buttons">
               <span class="button-move"><img src="images/icons/arrow_up_down.png" /></span>
               <a class="button-changestate" data-id="<?php echo $img->getPK()?>" href="<?php echo $this->link()?>#changestate-<?php echo $img->getPK()?>"><img
                       src="images/icons/<?php echo $img->{HPSlideShow_Model::COLUMN_ACTIVE} ? 'enable.png' : 'disable.png'?>" /></a>
               <a class="button-delete" data-id="<?php echo $img->getPK()?>" href="<?php echo $this->link()?>#delete-<?php echo $img->getPK()?>"><img src="images/icons/cancel.png" /></a>
            </div>
         </li>
         <?php }?>
      </ul>
      <script type="text/javascript">
         $(document).ready(function(){
            $( "#images-list>li" ).each(function(){
               var id = $(this).prop('id');
               $(this).tabs({
                  active   : $.cookie('hpslideshowactivetab'+id),
                  activate : function( event, ui ){
                      $.cookie( 'hpslideshowactivetab'+id, ui.newTab.index(),{expires : 10});
                  }
               });
            });
            $( "#images-list" ).sortable({
               placeholder: "ui-state-highlight",
               axis: "y",
               forceHelperSize: true,
               forcePlaceholderSize: true,
               handle : ".button-move",
               update : function( event, ui ){
                  $.ajax({
                     type : 'POST', url : "<?php echo $this->link()->route('editImage')?>",
                     data : {action : 'changepos', id : ui.item.data('id'), pos : ui.item.index()+1},
                     success : function(data){
                        if(data.errmsg.length != 0){
                           alert('Chyba při přesunu: '+data.errmsg.join(";"));
                        }
                     }
                  });
               }
            });

            $('.button-delete').click( function (){
               if(!confirm('<?php ps($this->tr('Opravdu smazat obrázek?'))?>')){
                   return false;
               }
               var $li = $(this).closest('li.slide-image-row');
               var id = $(this).data("id");
               $.ajax({
                  type: "POST",
                  url: "<?php echo $this->link()->route('editImage')?>",
                  data: {action : "delete", id : id},
                  success : function(data){
                     $li.fadeOut(300, function(){
                        $(this).remove();
                     });
                  }
               });
               return false;
            });

            $('.button-changestate').click( function (){
               var id = $(this).data("id");
               var $this = $(this);
               $.ajax({
                  type: "POST",
                  url: "<?php echo $this->link()->route('editImage')?>",
                  data: {action : "changestate", id : id},
                  success : function(data){
                     var $img = $('img', $this);
                     if($img.attr('src').indexOf('enable') === -1){
                        $img.attr('src', $img.attr('src').replace('disable', 'enable'))
                     } else {
                        $img.attr('src', $img.attr('src').replace('enable', 'disable'))
                     }

                  }
               });
               return false;
            });

            $('input[name="img_edit_save"]').after($('<img src="images/progress_small.gif" />').addClass('loader').hide());
         });
      </script>
   <?php } else { ?>
      <div class="admin-info-text">
         <?php ps($this->tr('Naní nahrán žádný obrázek'))?>
      </div>
   <?php }?>
</div>
