<?
// do titulku
if($this->edit) {
   $this->addPageTitle($this->_('úprava šablony'));
   $this->addPageHeadline($this->_('úprava šablony'));
} else {
   $this->addPageTitle($this->_('přidání šablony'));
   $this->addPageHeadline($this->_('přidání šablony'));
}
// donastavení formuláře
$this->form->content->html()->setAttrib('cols', 80)->setAttrib('rows', 30)->addClass("mceEditor");

$linkDisableEdit = '<a href="javascript:toggleEditor(\'template_content\');" id="template-disable-editor-button">'.$this->_('Vvpnout / zapnout editor').'</a>';
$this->form->content->setSubLabel($linkDisableEdit);


$tinymce = new JsPlugin_TinyMce();
$tinymce->setCfgParam('theme', 'full');
$this->addJsPlugin($tinymce);

?>

<div id="editArticleForm">
   <?
   print($this->form);
   $this->includeTpl("buttonback.phtml", true, array('link' => $this->link()->clear()));
   ?>
</div>
<script type="text/javascript">
function toggleEditor(id) {
   /* <![CDATA[ */
   if (!tinyMCE.get(id)){
      tinyMCE.execCommand('mceAddControl', false, id);
   } else {
      tinyMCE.execCommand('mceRemoveControl', false, id);
   }
}
/* ]]> */
</script>
