<?php 
// do titulku
if($this->edit) {
   $h = $this->tr('úprava šablony');
} else {
   $h = $this->tr('přidání šablony');
}
$this->addPageTitle($h);
// donastavení formuláře
$this->form->content->html()->setAttrib('cols', 80)->setAttrib('rows', 30);

$linkDisableEdit = '<a href="javascript:toggleEditor(\'template_content_1\');" id="template-disable-editor-button">'.$this->tr('Vvpnout / zapnout editor').'</a>';
$this->form->content->setSubLabel($linkDisableEdit);

?>
<h1><?php echo $h?></h1>
<div class="main-content-form-edit">
   <?php 
   print($this->form);
   ?>
</div>
<script type="text/javascript">
   /* <![CDATA[ */
   function toggleEditor(id) {
      if (!tinyMCE.get(id)){tinyMCE.execCommand('mceAddControl', false, id);}
      else {tinyMCE.execCommand('mceRemoveControl', false, id);}
   }
/* ]]> */
</script>
