<?
$this->addCssFile('style.css');
$this->addJsPlugin(new JsPlugin_JQueryCSS());
?>
<h1><?=$this->category()->getName();?></h1>
<div class="main-content-list module-templates-list">
   <?php
   $this->moduleButtons = array(
      array(
         'link' => $this->link()->route('add'),
         'title' => $this->tr('Vytvořit novou šablonu'),
         'faicon' => Template_Toolbox2::ICON_ADD,
         'name' => $this->tr('Vytvořit šablonu'),
      ),
   );
   $this->includeTpl('modules/buttons.phtml', true);
   ?>
   <?if(!empty ($this->templates)) {?>
   <table class="templates-list">
      <thead>
         <tr class="ui-widget-header">
            <th class="template-tb-name"><?=$this->_('Název')?></th>
            <th class="template-tb-cnt"><?=$this->_('Obsah')?></th>
            <th class="template-tb-type"><?=$this->_('Typ')?></th>
            <th class="template-tb-actions"></th>
         </tr>
      </thead>
   <?
      foreach ($this->templates as $template) {?>
      <tr class="ui-widget-content ui-state-default">
         <td><?=$template->{Templates_Model::COLUMN_NAME}?></td>
         <td><span class="templates-tpl-short-cnt" title="<?=htmlspecialchars($template->{Templates_Model::COLUMN_CONTENT})?>"
                ><?=vve_tpl_truncate(htmlspecialchars($template->{Templates_Model::COLUMN_CONTENT}), 100)?></span></td>
         <td><?=$template->{Templates_Model::COLUMN_TYPE}?></td>
         <td>
            <?/*<a href="<?=$this->link()?>#preview" title="<?=$this->_('Náhled v novém okně')?>"
               ><img src="<?=Template::getFileDir('icons/page_preview.png', Template::IMAGES_DIR, false,true)?>" alt="preview" /></a>*/?>
            <form action="<?=$this->link()->route('preview', array('id' => $template->{Templates_Model::COLUMN_ID}))?>" method="post" onsubmit="window.open(this.action); return false; //openWindow(this.action)">
               <input type="image" name="tpl_preview_go" value="" title="<?=$this->_('náhled')?>"
                      src="<?=Template::getFileDir('icons/page_preview.png', Template::IMAGES_DIR, false,true)?>" />
            </form>
            <form action="<?=$this->link()->route('edit', array('id' => $template->{Templates_Model::COLUMN_ID}))?>" method="post">
               <input type="image" name="tpl_edit_go" value="" title="<?=$this->_('upravit')?>"
                      src="<?=Template::getFileDir('icons/page_edit.png', Template::IMAGES_DIR, false,true)?>" />
            </form>
            <form action="<?=$this->link()->route()?>" method="post" onsubmit="return confirm('<?=$this->_('Oprvadu smazat šablonu &quot;'.$template->{Templates_Model::COLUMN_NAME}.'&quot; ?')?>');">
               <input type="hidden" name="tpl_del_id" value="<?=$template->{Templates_Model::COLUMN_ID}?>" />
               <input type="image" name="tpl_del_save" value="" title="<?=$this->_('smazat')?>"
                      src="<?=Template::getFileDir('icons/page_delete.png', Template::IMAGES_DIR, false,true)?>" />
            </form>
         </td>
      </tr>
     <?}?>
   </table>
   <?
   } else {
      print ($this->_('Není vložena žádná šablona'));
   }
   ?>
</div>
