<?
$h = $this->_('Náhled šablony').' '.$this->tpl->{Templates_Model::COLUMN_NAME};
$this->addPageTitle($h);
?>
<h1><?=$h;?></h1>
<div class="main-content-detail">
   <a href="<?=$this->link()->param('time', time())?>" title="<?echo $this->_('Obnovit náhled')?>"
      ><img src="<?=Template::getFileDir('icons/page_refresh.png', Template::IMAGES_DIR, false,true)?>"
        alt="icon reload" />&nbsp;<?echo $this->_('Obnovit náhled')?></a>
</div>
<?
switch ($this->previewType) {
   case 'normal':
   default:
      $this->includeTpl('preview_normal.phtml');
      break;
}
?>
<hr class="reseter" />
<?
$this->linkBack = $this->link()->clear();
$this->includeTpl("buttonback.phtml", true);?>
