<?php 
$h = $this->_('Náhled šablony').' '.$this->tpl->{Templates_Model::COLUMN_NAME};
$this->addPageTitle($h);
?>
<h1><?php echo $h;?></h1>
<div class="main-content-detail">
   <a href="<?php echo $this->link()->param('time', time())?>" title="<?php echo $this->_('Obnovit náhled')?>"
      ><img src="<?php echo Template::getFileDir('icons/page_refresh.png', Template::IMAGES_DIR, false,true)?>"
        alt="icon reload" />&nbsp;<?php echo $this->_('Obnovit náhled')?></a>
</div>
<?php 
switch ($this->previewType) {
   case 'normal':
   default:
      $this->includeTpl('preview_normal.phtml');
      break;
}
?>
<hr class="reseter" />
<?php 
$this->linkBack = $this->link()->clear();
$this->includeTpl("buttonback.phtml", true);?>
