<?php 
echo $this->toolbox;// TOOLBOXY
?>
<h1 class="hidden"><?php echo $this->category()->getName()?></h1>
<div class="main-content-list-records">
   <?php if(count($this->years) > 1){?>
   <form action="<?php echo $this->link()?>" method="get">
      <p>
         <label for="select-year"><?php echo $this->tr('Výběr ročníku')?>:</label>
         <select id="select-year" style="font-size: 80%;" onchange="this.form.action = this.value; this.form.submit()">
            <?php foreach ($this->years as $year => $numJournals) {?>
            <option value="<?php echo $this->link()->route('showYear', array('year' => $year))?>" <?php if($this->yearCurrent == $year){echo 'selected="selected"';}?> 
                    ><?php echo $this->tr("Ročník ").$year." &#8211; ".$this->tr(array('%s číslo', '%s čísla', '%s čísel'), $numJournals) ?></option>      
            <?php }?>
         </select>
<!--         <input type="submit" value="<?php echo $this->tr('Zobrazit')?>" />-->
      </p>
   </form>
   <?php 
   }
   
   if(empty ($this->journals)){?>
   <div class="main-content-text">Žádné číslo nebylo nahráno</div>
   <?php } else {
   foreach ($this->journals as $journal) {?>
   <div class="main-content-list-record journal">
   <div class="main-content-list-record-image journal-image">
      <img src="<?php echo $this->category()->getModule()->getDataDir(true).$journal->{Journals_Model::COLUMN_FILE}?>.jpg" alt="<?php echo $this->tr('Titulní strana')?>"/><br />
   </div>
   <h2>
      <a href="<?php echo $this->link()->route('show', array('year' => $journal->{Journals_Model::COLUMN_YEAR},
         'number' => $journal->{Journals_Model::COLUMN_NUMBER} ))?>" title="<?php   printf($this->tr('Otevřít číslo %s'), $journal->{Journals_Model::COLUMN_NUMBER})?>">
         <?php printf($this->tr('Ročník %s / číslo %s'), $journal->{Journals_Model::COLUMN_YEAR}, $journal->{Journals_Model::COLUMN_NUMBER})?>
      </a>
   </h2>
      <div class="main-content-list-record-text">
         <?php echo vve_tpl_truncate( strip_tags($journal->labels),130 );?>
         <div class="journal-actions font-small">
            <a class="file-icon file-pdf" href="<?php echo $this->dir.$journal->{Journals_Model::COLUMN_FILE}?>" title="stáhnout pdf">stáhnout pdf</a>
            <?php if($this->category()->getRights()->isWritable()){?>
            <span><?php printf($this->tr('Zobrazeno: %sx'), $journal->{Journals_Model::COLUMN_VIEWED})?></span>   
            <?php }?>
         </div>
      </div>
      
   <hr class="reseter" />
   </div>
   <?php }}?>
</div>

