<?
if($this->post instanceof Model_ORM_Record){
   $h = sprintf($this->tr('Úprava příspěvku %s'), $this->post->{Forum_Model_Posts::COLUMN_NAME});
} else {
   $h = sprintf($this->tr('Přidání příspěvku'));
}
$this->addPageTitle($h);
?>
<h1><?=$h?></h1>
<div class="main-content-detail">
   <div class="main-content-form-edit">
   <?
   $this->form->text->html()->setAttrib('rows', 15);
   echo $this->form;
   ?>
   </div>
</div>

