<?
if($this->topic instanceof Model_ORM_Record){
   $h = sprintf($this->tr('Úprava témata %s'), $this->topic->{Forum_Model_Topics::COLUMN_NAME});
} else {
   $h = sprintf($this->tr('Přidání témata'));
}
$this->addPageTitle($h);
?>
<h1><?=$h?></h1>
<div class="main-content-detail">
   <div class="main-content-form-edit">
   <?
   $this->form->text->html()->setAttrib('rows', 10);
   echo $this->form;
   ?>
   </div>
</div>

