<?
if($this->topic instanceof Model_ORM_Record){
   $h = sprintf($this->tr('Úprava témata %s'), $this->topic->{Forum_Model_Topics::COLUMN_NAME});
} else {
   $h = sprintf($this->tr('Přidání témata'));
}
$this->addPageTitle($h);
$this->addJsPlugin(new JsPlugin_JQuery());
?>
<h1><?=$h?></h1>
<div class="main-content-detail">
   <div class="main-content-form-edit">
   <?
   $this->form->text->html()->setAttrib('rows', 10);
   if(isset($this->form->notificationEMails)){
      $this->form->email->setSubLabel('<a id="buttonAddToNotify" href="#add-mail-notify" title="'.$this->tr('Zasílat nové příspěvky na e-mail').'">'.$this->tr('Přidat').'</a> '.$this->tr(' do upozornění na nové příspěvky'));
      if(isset($this->form->attachments)){
         $this->form->attachments->setSubLabel('<a id="buttonAddAttachment" href="#add-attachment" title="'.$this->tr('Přida další přílohu').'">'.$this->tr('Přida další přílohu').'</a>');
      }
   }
   echo $this->form;
   ?>
   </div>
   <script type="text/javascript">
      $('#buttonAddToNotify').click(function(e){
         e.preventDefault();
         var mail = $('#topic_email_1').val();
         if($('#topic_notificationEMails_1').val().search(mail) == -1){
            $('#topic_notificationEMails_1').val(mail+";"+$('#topic_notificationEMails_1').val() );
         }
      });
      <?if(isset($this->form->attachments)){?>
      $('#buttonAddAttachment').click(function(e){
         e.preventDefault();
         var $rowOrig = $(this).parents('tr:last');
         var $tbl = $rowOrig.parents('table');
         var lastId = $tbl.find('tr').length+1; 
         var $row = $rowOrig.clone(true);
         $rowOrig.find('a').remove();
         // replace id
         var newID = $('label', $row).attr('for').replace(/[0-9]+/, lastId);
         $('label', $row).attr('for', newID);
         $('input', $row).attr('id', newID).val(null);
         $tbl.append($row);
      });
      <?}?>
   </script>
</div>

