<?
if($this->message instanceof Model_ORM_Record){
   $h = sprintf($this->tr('Úprava příspěvku %s'), $this->message->{Forum_Model_Messages::COLUMN_NAME});
} else {
   $h = sprintf($this->tr('Přidání příspěvku'));
}
$this->addPageTitle($h);
$this->addFile('css://style.css');
?>
<h1><?=$h?></h1>
<div class="main-content-detail forum-message-edit">
   <?if($this->parentMessage){?>
   <?if($this->parentMessage->{Forum_Model_Messages::COLUMN_NAME} != null){?>
   <h2><?=$this->tr('Reakce na')?>: <?ps($this->parentMessage->{Forum_Model_Messages::COLUMN_NAME})?></h2>
   <?}?>
   <div class="author"><?=$this->tr('Autor')?>: <?ps($this->parentMessage->{Forum_Model_Messages::COLUMN_CREATED_BY})?></div>   
   <div class="text"><?=$this->parentMessage->{Forum_Model_Messages::COLUMN_TEXT}?></div>   
   <?}?>
   <div class="main-content-form-edit">
   <?
   $this->form->text->html()->setAttrib('rows', 15);
   echo $this->form;
   ?>
   </div>
</div>

