<?
if($this->message instanceof Model_ORM_Record){
   $h = sprintf($this->tr('Úprava příspěvku %s'), $this->message->{Forum_Model_Messages::COLUMN_NAME});
} else {
   $h = sprintf($this->tr('Přidání příspěvku'));
}
$this->addPageTitle($h);
$this->addFile('css://style.css');
?>
<h1><?=$h?></h1>
<div class="main-content-detail forum-message-edit">
   <?if($this->parentMessage){?>
   <?if($this->parentMessage->{Forum_Model_Messages::COLUMN_NAME} != null){?>
   <h2><?=$this->tr('Reakce na')?>: <?ps($this->parentMessage->{Forum_Model_Messages::COLUMN_NAME})?></h2>
   <?}?>
   <div class="author"><?=$this->tr('Autor')?>: <?ps($this->parentMessage->{Forum_Model_Messages::COLUMN_CREATED_BY})?></div>   
   <div class="text"><?=$this->parentMessage->{Forum_Model_Messages::COLUMN_TEXT}?></div>   
   <?}?>
   <div class="main-content-form-edit">
   <?
   $this->form->text->html()->setAttrib('rows', 15);
   if(isset($this->form->attachments)){
      $this->form->attachments->setSubLabel('<a id="buttonAddAttachment" href="#add-attachment" title="'.$this->tr('Přida další přílohu').'">'.$this->tr('Přida další přílohu').'</a>');
   }
   echo $this->form;
   ?>
   </div>
   <? 
   if(isset($this->form->attachments)){
      $this->addJsPlugin(new JsPlugin_JQuery());
   ?>
   <script type="text/javascript">
      $('#buttonAddAttachment').click(function(e){
         e.preventDefault();
         var $rowOrig = $(this).parents('tr:last');
         var $tbl = $rowOrig.parents('table');
         var lastId = $tbl.find('tr').length+1; 
         var $row = $rowOrig.clone(true);
         $rowOrig.find('a').remove();
         // replace id
         var newID = $('label', $row).attr('for').replace(/[0-9]+/, lastId);
         $('label', $row).attr('for', newID);
         $('input', $row).attr('id', newID).val(null);
         $tbl.append($row);
      });
   </script>
   <?}?>
</div>

