<?
$this->addJsPlugin(new JsPlugin_JQuery());
$this->addFile('css://style.css');
$h = $this->topic->{Forum_Model_Topics::COLUMN_NAME};
if($this->topic->{Forum_Model_Topics::COLUMN_SOLVED}){
   $h .= ' - '.$this->tr('vyřešeno');
}
?>
<h1><?=$h?></h1>
<div class="guestbook-items main-content-list">
   <table class="forum-topics full-width">
      <thead class="header">
         <tr>
            <th class="forum-topic-author forum-post-author"><?=$this->tr('Autor');?></th>
            <th class="forum-topic-views"><?=$this->tr('Zpráva');?></th>
         </tr>
      </thead>
      <tbody>
         <?if($this->scrollComp->getCurPageNumber() == 1){?>
         <tr class="forum-post-item row">
            <td class="forum-post-author">
               <?=ps($this->topic->{Forum_Model_Topics::COLUMN_CREATED_BY})?>
               <div class="font-small forum-post-info">
                  <?printf($this->tr('Přidáno: %s'), vve_date('%d.%m.%Y %G:%i', new DateTime($this->topic->{Forum_Model_Topics::COLUMN_DATE_ADD})));?>
               </div>
            </td>
            <td class="forum-post-message">
               <?echo $this->toolboxTopic;?>
               <div class="main-content-text">
                  <?echo $this->topic->{Forum_Model_Topics::COLUMN_TEXT};?>
               </div>
            </td>
         </tr>
         <?}?>
      <?if(!empty ($this->posts)){ ?>
      <?foreach ($this->posts as $post) {?>
         <tr class="forum-post-item row <?if($post->{Forum_Model_Posts::COLUMN_CENSORED})echo "censored";?>">
            <td class="forum-post-author">
                  <?echo ps($post->{Forum_Model_Posts::COLUMN_CREATED_BY}).'<br/>';?>
                  <div class="font-small forum-post-info">
                  <?if($post->{Forum_Model_Posts::COLUMN_CREATED_BY_MODERATOR} == true){
                     echo $this->tr('Moderátor').'<br/>';
                  } else if($post->{Forum_Model_Posts::COLUMN_ID_USER} == 0){
                     echo $this->tr('Anonymní').'<br/>';
                  }
                  printf($this->tr('Přidáno: %s'), vve_date('%d.%m.%Y %G:%i', new DateTime($post->{Forum_Model_Posts::COLUMN_DATE_ADD})));
                  if($post->{Forum_Model_Posts::COLUMN_CENSORED}){
                     echo '<p class="font-small">'.$this->tr('Příspěvek byl cenzurován').'</p>';
                  }
                  ?>
                  </div>
            </td>
            <td class="forum-post-message">
               <?
               if($this->toolboxPost instanceof Template_Toolbox2 && ($this->category()->getRights()->isControll()
                  || $post->{Forum_Model_Posts::COLUMN_ID_USER} == Auth::getUserId() )){
                  $this->toolboxPost->edit_post->setAction($this->link()->route('editPost', array('idp' => $post->{Forum_Model_Posts::COLUMN_ID})));
                  if(isset($this->toolboxPost->post_delete)){
                     $this->toolboxPost->post_censore->getForm()->id->setValues($post->{Forum_Model_Posts::COLUMN_ID});
                     $this->toolboxPost->post_delete->getForm()->id->setValues($post->{Forum_Model_Posts::COLUMN_ID});
                  }
                  echo $this->toolboxPost;
               }
               ?>
               <div class="main-content-text">
               <?
               if($this->category()->getRights()->isControll() || $post->{Forum_Model_Posts::COLUMN_CENSORED} == false){
                  if($post->{Forum_Model_Posts::COLUMN_NAME} != null){
                     echo '<h2>'.$post->{Forum_Model_Posts::COLUMN_NAME}.'</h2>';
                  }
                  echo $post->{Forum_Model_Posts::COLUMN_TEXT};
               } else {
                  echo '<p>'.$this->tr('Příspěvek byl cenzurován.').'<p>';
               }
               ?>
               </div>
            </td>
         </tr>
      <?}
      } else {}?>
      </tbody>
      <tfoot>
      <?if($this->category()->getRights()->isWritable() && $this->topic->{Forum_Model_Topics::COLUMN_CLOSED} == false){?>
         <tr class="forum-post-item row">
            <td colspan="2">
               <img src="/images/icons/comment_add.png" alt="add" />
               <a href="<?=$this->link()->route('addPost', array('id' => $this->topic->{Forum_Model_Topics::COLUMN_ID}))?>" 
                  title="<?=$this->tr('Přidat nový příspěvek')?>" ><?=$this->tr('Přidat příspěvek')?></a>
            </td>
         </tr>   
      <?}?>
         <tr class="forum-post-item row">
            <td colspan="2"><?
               $this->includeTpl('articletools.phtml', true, array(
              'shares' => array('url' => $this->link(), 'title' => $this->link())));
            ?></td>
         </tr>   
      </tfoot>
   </table>
   <?
//   $this->scrollComp->setConfig('text_prev', 'Startší');
//   $this->scrollComp->setConfig('text_next', 'Novejší');
   echo ($this->scrollComp);
   ?>
   <br />
   <div class="link-back"><a href="<?=$this->link()->route()?>" title="<?=$this->tr('Zpět na seznam témat');?>">&Lt; <?=$this->tr('Zpět na seznam témat');?></a></div>
</div>