<?
$this->addJsPlugin(new JsPlugin_JQuery());
$this->addFile('css://style.less');
$h = $this->topic->{Forum_Model_Topics::COLUMN_NAME};
if($this->topic->{Forum_Model_Topics::COLUMN_SOLVED}){
   $h .= ' - '.$this->tr('vyřešeno');
}
$jqcss = new JsPlugin_JQueryCSS();
$this->addJsPlugin($jqcss);
$expire = new DateTime();
$expire->modify('+1 year');
?>
<h1><?=$h?></h1>
<div class="forum-items main-content-list">
   <ul class="forum-topic-messages">
      <li class="topic-header ui-widget-header item">
         <table class="full-width">
            <tr class="">
            <th class="message-author"><?=$this->tr('Autor');?></th>
            <th class="message-text"><?=$this->tr('Zpráva');?></th>
         </tr>
         </table>
      </li>
      <li class="topic ui-widget-content item">
         <table class="full-width">
            <tr>
               <td class="message-author">
                  <?=ps($this->topic->{Forum_Model_Topics::COLUMN_CREATED_BY})?>
                  <div class="message-params">
                     <?printf($this->tr('Přidáno: %s'), vve_date('%d.%m.%Y %G:%i', new DateTime($this->topic->{Forum_Model_Topics::COLUMN_DATE_ADD})));?>
                  </div>
               </td>
               <td class="message-text">
                  <?echo $this->toolboxTopic;?>
                  <div class="text">
                     <?echo $this->topic->{Forum_Model_Topics::COLUMN_TEXT};?>
                  </div>
                  <?if(isset($this->attachments[0]) && !empty($this->attachments[0])){ 
                     $str = null;
                     foreach ($this->attachments[0] as $file) {
                        $imgTag = new Html_Element('a', htmlspecialchars($file->{Forum_Model_Attachments::COLUMN_FILENAME}));
                        $imgTag->setAttrib('href', $this->attachmentsPath.$file->{Forum_Model_Attachments::COLUMN_FILENAME});
                        $imgTag->setAttrib('title', $file->{Forum_Model_Attachments::COLUMN_FILENAME});
                        if(in_array( strtolower( pathinfo($file->{Forum_Model_Attachments::COLUMN_FILENAME}, PATHINFO_EXTENSION) ), array('jpg', 'jpeg', 'png', 'gif'))){
                           $imgTag->setAttrib('rel', 'prettyPhoto');
                        }
                        $str .= '<li>'.$imgTag.'</li>';
                     }?>
                  <div class="attachments">
                     <strong><?=$this->tr('Přílohy')?></strong>
                     <ul><?=$this->filter($str, 'filesicons');?></ul>
                  </div>
                  <?} ?>
               </td>
            </tr>
            <tr>
               <td>
               </td>
               <td class="message-tools">
                  <?
                  $linkToAdd = $this->link()
                     ->route('addMessage', array('id' => $this->topic->{Forum_Model_Topics::COLUMN_ID})); 
                  ?>
                  <?if($this->category()->getRights()->isWritable() && $this->topic->{Forum_Model_Topics::COLUMN_CLOSED} == false){?>
                  <a href="<?=$linkToAdd ?>" 
                     title="<?=$this->tr('Reagovat na tento příspěvek')?>" 
                     ><img src="/images/icons/comment_add.png" alt="add" /> <?=$this->tr('Reagovat')?></a>
                  <?}?>
               </td>
            </tr>
         </table>
      </li>
      <?if(!empty ($this->messages)){ ?>
      <?foreach ($this->messages as $message) {?>
      <li id="message-<?=$message->{Forum_Model_Messages::COLUMN_ID}?>"
          style="margin-left: <?=(int)($message->{Forum_Model_Messages::COLUMN_DEPTH}*20+10)?>px"
          class="item ui-widget-content <?if($message->{Forum_Model_Messages::COLUMN_CENSORED})echo "ui-state-disabled";?>">
            <table class="full-width">
               <tr>
                  <td class="message-author">
                     <?echo ps($message->{Forum_Model_Messages::COLUMN_CREATED_BY}).'<br/>';?>
                     <div class="message-params">
                     <?if($message->{Forum_Model_Messages::COLUMN_CREATED_BY_MODERATOR} == true){
                        echo $this->tr('Moderátor').'<br/>';
                     } else if($message->{Forum_Model_Messages::COLUMN_ID_USER} == 0){
                        echo $this->tr('Anonymní').'<br/>';
                     }
                     printf($this->tr('Přidáno: %s'), vve_date('%d.%m.%Y %G:%i', new DateTime($message->{Forum_Model_Messages::COLUMN_DATE_ADD})));
                     if($message->{Forum_Model_Messages::COLUMN_CENSORED}){
                        echo '<p class="font-small">'.$this->tr('Příspěvek byl cenzurován').'</p>';
                     }
                     ?>
                     </div>
                  </td>
                  <td class="message-text" rowspan="2">
                     <?
                     if($this->toolboxMessage instanceof Template_Toolbox2 && ($this->category()->getRights()->isControll()
                        || $message->{Forum_Model_Messages::COLUMN_ID_USER} == Auth::getUserId() )){
                        $this->toolboxMessage->edit_message->setAction($this->link()->route('editMessage', array('idm' => $message->{Forum_Model_Messages::COLUMN_ID})));
                        if(isset($this->toolboxMessage->message_delete)){
                           $this->toolboxMessage->message_censore->getForm()->id->setValues($message->{Forum_Model_Messages::COLUMN_ID});
                           $this->toolboxMessage->message_delete->getForm()->id->setValues($message->{Forum_Model_Messages::COLUMN_ID});
                        }
                        echo $this->toolboxMessage;
                     }
                     ?>
                     <div class="text">
                     <?
                     if($this->category()->getRights()->isControll() || $message->{Forum_Model_Messages::COLUMN_CENSORED} == false){
                        if($message->{Forum_Model_Messages::COLUMN_NAME} != null){
                           echo '<h2>'.$message->{Forum_Model_Messages::COLUMN_NAME}.'</h2>';
                        }
                        echo $message->{Forum_Model_Messages::COLUMN_TEXT};
                     } else {
                        echo '<p>'.$this->tr('Příspěvek byl cenzurován.').'<p>';
                     }?>
                     </div>
                     <?if(isset($this->attachments[$message->{Forum_Model_Messages::COLUMN_ID}]) && !empty($this->attachments[$message->{Forum_Model_Messages::COLUMN_ID}])){ 
                        $str = null;
                        foreach ($this->attachments[$message->{Forum_Model_Messages::COLUMN_ID}] as $file) {
                           $imgTag = new Html_Element('a', htmlspecialchars($file->{Forum_Model_Attachments::COLUMN_FILENAME}));
                           $imgTag->setAttrib('href', $this->attachmentsPath.$file->{Forum_Model_Attachments::COLUMN_FILENAME});
                           $imgTag->setAttrib('title', $file->{Forum_Model_Attachments::COLUMN_FILENAME});
                           if(in_array( strtolower( pathinfo($file->{Forum_Model_Attachments::COLUMN_FILENAME}, PATHINFO_EXTENSION) ), array('jpg', 'jpeg', 'png', 'gif'))){
                              $imgTag->setAttrib('rel', 'prettyPhoto');
                           }
                           $str .= '<li>'.$imgTag.'</li>';
                        }?>
                     <div class="attachments">
                        <strong><?=$this->tr('Přílohy')?></strong>
                        <ul><?=$this->filter($str, 'filesicons');?></ul>
                     </div>
                     <?} ?>
               </td>
            </tr>
            <tr>
               <td class="message-vote">
<!--                  <strong>--><?//ps($this->tr('Hodnocení'))?><!--</strong><br />-->
               </td>
            </tr>
            <?if($this->category()->getRights()->isControll() && $message->{Forum_Model_Messages::COLUMN_VOTE_SPAM} > 10){?>
            <tr>
               <td colspan="2">
                  <div class="message message-warning">
                     <strong><?ps(sprintf($this->tr('%s krát označen jako "nevhodné/SPAM"'), $message->{Forum_Model_Messages::COLUMN_VOTE_SPAM}))?></strong>
                  </div>
               </td>
            </tr>
            <?}?>
            <tr>
               <td>
                  <div class="message-vote clearfix">
                     <?if($message->voteEnabled){?>
                     <a class="vote-button vote-button-up" href="<?=$this->link()->route('voteMessage')->param('id', $message->getPK())->param('action', 'voteUp')?>"
                        title="<?ps($this->tr('Hotnotit: výborně'))?>" ><img src="images/icons/go-up.png"/></a>
                     <?}?>
                     <span class="vote-counter">
                        <?if(!$message->voteEnabled){ ps($this->tr('Hlasů').": ");}?>
                        <?ps($message->{Forum_Model_Messages::COLUMN_VOTE})?>
                     </span>
                     <?if($message->voteEnabled){?>
                     <a class="vote-button vote-button-down" href="<?=$this->link()->route('voteMessage')->param('id', $message->getPK())->param('action', 'voteDown')?>"
                        title="<?ps($this->tr('Hotnotit: zbytečný'))?>" ><img src="images/icons/go-down.png"/></a>
                     <a class="vote-button vote-button-spam" href="<?=$this->link()->route('voteMessage')->param('id', $message->getPK())->param('action', 'voteSpam')?>"
                        title="<?ps($this->tr('Nahlásit nevhodné / SPAM'))?>" ><img src="images/icons/decline.png"/></a><br />
                     <?}?>
                  </div>
               </td>
               <td class="message-tools">
                  <div class="message-vote-label clearfix"></div>
                  <?
                  $linkToAdd = $this->link()
                     ->route('addMessage', array('id' => $this->topic->{Forum_Model_Topics::COLUMN_ID}))
                     ->param('msg', $message->{Forum_Model_Messages::COLUMN_ID}); 
                  ?>
                  <?if($this->category()->getRights()->isWritable() && $this->topic->{Forum_Model_Topics::COLUMN_CLOSED} == false){?>
                  <a href="<?=$linkToAdd ?>" 
                     title="<?=$this->tr('Reagovat na tento příspěvek')?>" 
                     ><img src="/images/icons/comment_add.png" alt="add" /> <?=$this->tr('Reagovat')?></a>
                  <?}?>
               </td>
            </tr>
         </table>
      </li>
      <?}
   }?>
      <li class="topic-footer ui-widget-content item message-tools">
         <a href="<?=$this->link()->route('rssTopic', array('id' => $this->topic->{Forum_Model_Topics::COLUMN_ID}))?>" 
            title="<?=$this->tr('Sledovat diskusi pomocí rss')?>" 
            ><img src="/images/icons/rss.png" alt="add" /> <?=$this->tr('Sledovat')?></a>
         <?if($this->category()->getRights()->isWritable() && $this->topic->{Forum_Model_Topics::COLUMN_CLOSED} == false){?>
         <a href="<?=$this->link()->route('addMessage', array('id' => $this->topic->{Forum_Model_Topics::COLUMN_ID}))?>" 
            title="<?=$this->tr('Přidat nový příspěvek')?>" 
            ><img src="/images/icons/comment_add.png" alt="add" /> <?=$this->tr('Přidat příspěvek')?></a>
         <?}?>
      </li>
   </ul>
   <div class="link-back"><a href="<?=$this->link()->route()?>" title="<?=$this->tr('Zpět na seznam témat');?>">&Lt; <?=$this->tr('Zpět na seznam témat');?></a></div>
</div>
<? 
$this->addJsPlugin(new JsPlugin_PrettyPhoto());
?>
<script type="text/javascript">
   function getCookie(name) {
      var regexp = new RegExp("(?:^" + name + "|;\\s*"+ name + ")=(.*?)(?:;|$)", "g");
      var result = regexp.exec(document.cookie);
      return (result === null) ? null : result[1];
   }
   $(document).ready(function(){
	   $("a[rel^='prettyPhoto']").prettyPhoto({social_tools: ''});

      $('.vote-button').hover(function(){
         $(this).closest('table').find('.message-vote-label').text($(this).prop('title'));
         $(this).data('title', $(this).prop('title'));
         $(this).prop('title', "");
      }, function(){
         $(this).prop('title', $(this).data('title'));
         $(this).closest('table').find('.message-vote-label').text("");
      });
      $('.vote-button').click(function(){
         var $link = $(this);
         $.ajax({
            url : $link.prop('href'),
            cache : false,
            success : function(respond){
               if(respond.infomsg && respond.errmsg.length == 0){
                  var $msg = $('#message-'+respond.idMessage);
                  var idsStrored = getCookie('<?=Forum_Controller::COOKIE_NAME?>');
                  var ids = idsStrored == null ? new Array() : idsStrored.split('|');
                  if($.inArray(respond.idMessage, ids) == -1){
                     ids.push(respond.idMessage);
                  }
                  document.cookie ='<?=Forum_Controller::COOKIE_NAME?>='+ids.join('|')+'; expires=<?=$expire->format(DATE_COOKIE)?>; path=/'
                  $('.vote-counter', $msg).text('<?ps($this->tr('Hlasů'))?>: '+respond.votes);
                  <?if(!$this->category()->getRights()->isControll()){?>
                  // disable buttons
                  $('.vote-button,.message-vote-label', $msg).remove();
                  <?}?>
               }
            }
         });
         return false;
      });


	});
</script>