tinyMCE.addI18n('cs.cubephotogalery_dlg',{
tab_general:"Z\u00E1kladn\u00ED",
//tab_appearance:"Appearance",
tab_advanced:"Pokro\u010Dil\u00E9",
tab_html:"HTML",
dialog_title:"Vlo\u017Een\u00ED fotogalerie", 

general:"Z\u00E1kladn\u00ED",
uploadstatus:"Nahr\u00E1v\u00E1n\u00ED",

images:"Obr\u00E1zky",
select_images:"Vybrat obr\u00E1zky",
selected_images:"Vybr\u00E1not obr\u00E1zk\u016F",
directory:"Adres\u00E1\u0159",
galery_name:"N\u00E1zev galerie",
dir_name:"N\u00E1zev adres\u00E1\u0159e",

statusuploading : "Nahr\u00E1v\u00E1m",
statusready : "P\u0159ipraveno",
statusnotready : "Nen\u00ED vybr\u00E1n",
uploaded : "Nahr\u00E1no",
images_loaded : "Nahran\u00e9 a  p\u0159ipraven\u00e9 obr\u00e1zky",
insert_with_error_upload : "Nekter\u00e9 obr\u00e1zky se nepoda\u0159ilo nahr\u00e1t. Chcete opravdu vlo\u017eit nekompletn\u00ed galerii?",

classes : "T\u0159\u00eddy",
label : "Popisek",
label_add : "P\u0159idat popisek",
style : "Styly",
html_settings : "Nastaven\u00ed HTML",
image_settings : "Nastaven\u00ed obr\u00e1zk\u016f",
link_settings : "Nastaven\u00ed odkaz\u016f",
preview_in : "N\u00e1hled v",
wrapper:"Element obalu",

/* msgs */
error_unknown : 'Nezn\u00E1m\u00E1 chyba',
error_file_queue_size_limit : 'Obr\u00E1zek "{0}" je p\u0159\u00EDli\u0161 velk\u00FD',
error_file_queue_indorrect_file : 'Neplatn\u00FD typ obr\u00E1zku. Soubor "{0}".',
error_file_queue_zero_file : 'Obr\u00E1zek "{0}" m\u00E1 nulovou velikost',
error_no_galery : '\u017D\u00E1dn\u00FD obr\u00E1zek nebyl vybr\u00E1n. Chcete pokra\u010Dovat?',

//constrain_proportions:"Constrain proportions",
//langdir:"Language direction",
//langcode:"Language code",
//long_desc:"Long description link",
//style:"Style",
//classes:"Classes",
//ltr:"Left to right",
//rtl:"Right to left",
//id:"Id",
//map:"Image map",
//swap_image:"Swap image",
//alt_image:"Alternative image",
//mouseover:"for mouse over",
//mouseout:"for mouse out",
//misc:"Miscellaneous",
//example_img:"Appearance preview image",
//missing_alt:"Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.",
//dialog_title:"Insert/edit image",
//src:"Image URL",
//alt:"Image description",
//list:"Image list",
//border:"Border",
//dimensions:"Dimensions",
//width:"Width",
//height:"Height",
//vspace:"Vertical space",
//hspace:"Horizontal space",
//align:"Alignment",
//align_baseline:"Baseline",
//align_top:"Top",
//align_middle:"Middle",
//align_bottom:"Bottom",
//align_texttop:"Text top",
//align_textbottom:"Text bottom",
//align_left:"Left",
//align_right:"Right",
image_list:"Image list"
});