<div class="<?php if($this->box == 'left'){echo 'panel ';}?>custom-menu custom-menu-<?php echo $this->box?> clearfix hidden-print">
   <?php 
   if($this->box == 'left'){?>
      <div class="name"><?php ps($this->tr('Kam dále?'))?></div>
   <?php }?>
   <ul class="nav">
   <?php foreach ($this->items as $item) {
      ?>
      <li>
         <a href="<?php echo $item->{AdminCustomMenu_Model_Items::COLUMN_LINK}?>"
            class="<?php  if($item->{AdminCustomMenu_Model_Items::COLUMN_NEW_WINDOW}){ echo "link-external";}?>"
            title="<?php ps($item->{AdminCustomMenu_Model_Items::COLUMN_NAME})?>"
                 ><?php ps($item->{AdminCustomMenu_Model_Items::COLUMN_NAME})?></a>
      </li>
   <?php }?>
   </ul>
</div>