<h1><?php echo $this->tr('CHYBA 401: Přístup zamítnut')?></h1>
<div class="post">
   <div class="text page-err403">
      <?php echo $this->tr('K požadované stránce nemáte přístup. Pravděpodobně jste byl/a odhlášen/a. Pro přístup se prosím znovu');?>
      <a href="<?php echo $this->pVar("MAIN_WEB_DIR")?>/ucet/" title="<?php echo $this->tr('přihlášení');?>"><?php echo $this->tr('přihlašte');?></a>.
   </div>
</div>
