<h1><?php echo $this->tr('Chyba - Stránka nenalezena')?></h1>
<div class="main-content-detail">
   <div class="main-content-text page-err404">
      <?php echo $this->tr('Chyba 404 - Stránka nebyla nalezena. Zkontrolujte prosím zadanou adresu nebo přejděte na');?>
      <a href="<?php echo $this->pVar("MAIN_WEB_DIR")?>" title="<?php echo $this->tr('hlavní stránku');?>"><?php echo $this->tr('hlavní stránku');?></a>
   </div>
</div>
