<div class="message" id="coreErrMessage" style="background-image: url('<?=vve_get_tpl_file('icons/exclamation.png', VVE_TPL_FILE_IMAGE)?>')">
      <?
      $errors = CoreErrors::getErrors();
      foreach ($errors as $error) {?>
   <p>
            <?=$error["name"]?>: (<i><?=$error["code"]?></i>) <b><?=$error["message"]?></b>
            <?=$this->tr("soubor")?>: <?=$error["file"]?>, <?=$this->tr("řádek")?>: <?=$error["line"]?><br />
            <? if(VVE_DEBUG_LEVEL > 1) {
               foreach ($error["trace"] as $err) {?>
                  <?=$err["class"].$err["type"].$err["function"]."&nbsp;&nbsp;";
                  echo $this->tr("soubor").": <i>".$err["file"] ."</i>&nbsp;&nbsp;&nbsp;".$this->tr("řádek").": ".$err["line"];?>
      <br />
               <?}
            }?>
   </p>
      <?}?>
</div>
