<?php
ob_start();
?>
<a class="modal-image-selector-image <?php echo $this->selected == "" ? "active" : "" ?>" href="<?php echo $this->link() ?>#" data-value=""
   ><img src="<?php echo Utils_Image::cache(Utils_Url::pathToSystemUrl(AppCore::getAppLibDir()) . Template::IMAGES_DIR . "/no_image.png", 80, 80) ?>" alt="" /></a>
   <?php foreach ($this->images as $img) {
      ?>
   <a class="modal-image-selector-image <?php echo $this->selected == $img ? "active" : "" ?>" href="<?php echo $this->link() ?>#" data-value="<?php echo $img ?>"
      ><img src="<?php echo Utils_Image::cache($this->imgurl . $img, 80, 80) ?>" alt="" /></a>
   <?php } ?>
<?php
$cnt = ob_get_clean();

$this->includeFile('tpl://engine:components/modal.phtml', array(
    'content' => $cnt,
    'id' => 'modal-image-selector-' . $this->elementName . '_' . $this->rKey,
    'header' => $this->tr('Výběr titulního obrázku'),
    'close' => true,
    'large' => false,
    'class' => 'cubecms-modal-images',
    'footer' => '<button class="btn btn-default close-modal">' . $this->tr('Zavřít') . '</button>'));


