<div>
<?
// do titulku
if($this->editGlobalOption == true){
   $h = $this->tr('úprava globální volby').' '.$this->option->{Model_Config::COLUMN_KEY};
} else {
   $h = $this->tr('úprava lokální volby').' '.$this->option->{Model_Config::COLUMN_KEY};
}
$this->addPageTitle($h);
?>
<h1><?=$h?></h1>
<div class="main-content-form-edit">
   <?=$this->form?>
</div>


<script type="text/javascript">
   /* <![CDATA[ */
   /* ]]> */
</script>
</div>