<?
$model = new Model_Config();
$list = $model->getList();

?>
<div>
   <?//sekce?>
   <h2><?=$this->_("Struktura stránek")?></h2>
   <div id="sections">
      <table class="valuesTable">
         <tr>
            <th width="220" style=""><?=$this->_('Klíč')?></th>
            <th width="300"><?=$this->_('Popis')?></th>
            <th width="100"><?=$this->_('Hodnota')?></th>
            <th width="50"><?=$this->_('Operace')?></th>
         </tr>
         <?while ($row = $list->fetch()) {?>
         <tr>
            <td><p style="width: 200px; overflow: auto;"><?=$row->{Model_Config::COLUMN_KEY}?></p></td>
            <td><?=$row->{Model_Config::COLUMN_LABEL}?></td>
            <td><?=$row->{Model_Config::COLUMN_VALUE}?></td>
            <td>
               <form method="post" action="<?=$this->link()->route('edit', array('id' => $row->{Model_Config::COLUMN_ID}))?>" style="display:inline;">
                  <input type="image" src="<?=vve_get_tpl_file('icons/plugin_edit.png', VVE_TPL_FILE_IMAGE)?>"
                         value="edit" name="category_edit" title="<?=$this->_('Upravit')?>" />
               </form>
            </td>
         </tr>
         <?}?>
      </table>
   </div>
   <br />
   <br />
   <script type="text/javascript">
      function submitRemoveCfgValue(msg){
         return confirm('<?=$this->_('Opravdu smazat kategorii: ')?>'+msg+'?');
      }
   </script>

   <?
   // disabled -- není potřeba
   //   if($this->category()->getRights()->isWritable()) {
   //      $toolbox = new Template_Toolbox();
   //      $toolbox->addTool('add_config', $this->_("Přidat volbu"),
   //          $this->link()->route('add'),
   //          $this->_("Přidat novou konfigurační volbu"), "text_add.png");
   //      $this->includeTplObj($toolbox);
   //   }
   ?>
</div>

