<div class="content">
   <!--[if !IE]> -->
   <object type="application/x-shockwave-flash"
           data="<?=$this->sys()->module()->getDir()->getDataDir()?>virtualnidum.swf" width="610" height="600">
      <!-- <![endif]-->
      <!--[if IE]>
      <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
        codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0"
        width="100" height="130">
        <param name="movie" value="<?=$this->sys()->module()->getDir()->getDataDir()?>virtualnidum.swf" />
      <!--><!--dgx-->
      <param name="loop" value="true" />
      <param name="menu" value="false" />
      <param name="wmode" value="transparent" />
      <span><?=_("Prosím nainstalijte si Adobe Flash Player")?></span>
   </object>
   <!-- <![endif]-->
</div>