<?
$this->addFile("css://style.css");
$this->addJsPlugin(New JsPlugin_JQuery());
$this->addJsPlugin(New JsPlugin_JQueryCSS());
?>
<h1><? echo $this->module != null ? sprintf($this->tr('Překladač statických textů modulu "%s"'), $this->module) : $this->tr('Překladač statických textů jádra');?></h1>
<div class="ui-widget ">
<?
$this->formTr->html()->setAttrib('id', 'form_translation');
echo $this->formTr->renderStart();
?>
<fieldset>
   <legend><?=$this->tr('Jednotná čísla');?></legend>
   <table style="width: 100%;" cellpadding="0" cellspacing="0">
   <?
   $rowTrS = 1;
   foreach ($this->singulars as $strHash => $translation) {?>
      <tr class="ui-widget-content ui-state-default <?if($translation[0] == $translation[1]){echo "ui-state-highlight";}?>"><td>
         <table id="tr_si_<?echo $rowTrS++?>" class="tr_row full-width">
      <tr><th><?echo $this->tr('Originál');?>:</th></tr>
      <tr><td class="tr_str"><?echo $translation[0];?></td></tr>
      <tr><th><?echo $this->formTr->trsingular->label();?></th></tr>
      <tr>
         <td class=""><?
      $this->formTr->trsingular->html()->setAttrib('rows', 1)->setAttrib('cols', 60)->addClass('tr_str_res');
      $this->formTr->trsingular->setDimensional($strHash);
      $this->formTr->trsingular->setValues($translation[1]);
      echo $this->formTr->trsingular->controll();
      ?></td>
      </tr>
   </table>
   </td></tr>
   <?}?>
   </table>
</fieldset>

<fieldset id="text-plurals">
   <legend><?=$this->tr('Množná čísla');?></legend>
   <table cellpadding="0" cellspacing="0" class="full-width">
   <?
   $rowTrP = 1;
   foreach ($this->plurals as $strHash => $translation) {?>
   <tr class="ui-widget-content ui-state-default <?if($translation[0][0] == $translation[1][0]){echo "ui-state-highlight";}?>"><td>
         <table id="tr_pl_<?echo $rowTrP++?>" class="tr_pl_row full-width">
         <tr><th colspan="3"><?echo $this->tr('Originál');?>:</th></tr>
         <tr>
            <td class="tr_pl_str_1" style="width: 33%;"><em><?echo htmlspecialchars($translation[0][0]);?></em></td>
            <td class="tr_pl_str_2" style="width: 33%;"><em><?echo htmlspecialchars($translation[0][1]);?></em></td>
            <td class="tr_pl_str_3" style="width: 33%;"><em><?if(isset($translation[0][2])){echo htmlspecialchars($translation[0][2]);}?></em></td>
         </tr>
         <!-- translations -->
         <tr>
            <th><?echo $this->formTr->trplural1->label();?></th>
            <th><?echo $this->formTr->trplural2->label();?></th>
            <th><?echo $this->formTr->trplural3->label();?></th>
         </tr>
         <tr>
            <td><?
            $this->formTr->trplural1->html()->setAttrib('rows', 1)->setAttrib('cols', 20)->addClass('tr_pl_str_1_res');
            $this->formTr->trplural1->setDimensional($strHash);
            $this->formTr->trplural1->setValues(null);
            if(isset ($translation[1][0])) {
               $this->formTr->trplural1->setValues($translation[1][0]);
            }
            echo $this->formTr->trplural1->controll();
            ?></td>
            <td><?
            $this->formTr->trplural2->html()->setAttrib('rows', 1)->setAttrib('cols', 20)->addClass('tr_pl_str_2_res');
            $this->formTr->trplural2->setDimensional($strHash);
            $this->formTr->trplural2->setValues(null);
            if(isset ($translation[1][1])) {
               $this->formTr->trplural2->setValues($translation[1][1]);
            }
            echo $this->formTr->trplural2->controll();
            ?></td>
            <td><?
            if(isset($translation[1][2])){
               $this->formTr->trplural3->html()->setAttrib('rows', 1)->setAttrib('cols', 20)->addClass('tr_pl_str_3_res');
               $this->formTr->trplural3->setDimensional($strHash);
               $this->formTr->trplural3->setValues(null);
               if(isset ($translation[1][2])) {
                  $this->formTr->trplural3->setValues($translation[1][2]);
               }
               echo $this->formTr->trplural3->controll();
            }
            ?></td>
         </tr>
      </table>
   </td></tr>
   <?}?>
   </table>
</fieldset>
<fieldset>
   <?
      echo $this->formTr->save;
   ?>
</fieldset>


<?echo $this->formTr->renderEnd();?>
</div>
<script type="text/javascript">
   $(document).ready(function(){});
</script>