CREATE TABLE IF NOT EXISTS `{PREFIX}map_locations` (
`id_location` SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`id_category` SMALLINT NOT NULL ,
`name` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL ,
`text` TEXT CHARACTER SET utf8 COLLATE utf8_czech_ci NULL DEFAULT NULL ,
`text_clear` TEXT CHARACTER SET utf8 COLLATE utf8_czech_ci NULL DEFAULT NULL ,
`coordinate_x` FLOAT NULL DEFAULT NULL ,
`coordinate_y` FLOAT NULL DEFAULT NULL ,
`image` VARCHAR( 50 ) NULL DEFAULT NULL ,
`marker` VARCHAR( 30 ) NULL DEFAULT NULL ,
INDEX (  `id_category` )
) ENGINE = MYISAM ;