<a class="toolbox-button" href="" title="Otevřít nástroje"><img src="<?=$this->iconsDir.$this->toolboxIcon?>" alt="icon <?=$this->toolboxIcon?>" /></a>
<div class="toolbox">
   <? foreach ($this->getTools() as $tool) {?>
      <div class="toolbox-tool">
      <?
         $formOnSubmit = null;
         if($tool->getConfirmMessage() != null){
            $formOnSubmit .= 'return confirm(\''.$tool->getConfirmMessage().'\');';
         }
         $class = get_class($tool);
         switch ($class) {
            case 'Template_Toolbox2_Tool_PostRedirect':
               ?>
         <form action="<?=$tool->getAction() ?>" method="post" onsubmit="<?=$formOnSubmit?>">
            <div><img src="<?=$this->iconsDir . $tool->getIcon() ?>" alt="icon <?=$tool->getIcon() ?>"
                  /><input class="toolbox-tool-button" type="submit" name="<?=$tool->getName() ?>_button"
                     value="<?=$tool->getLabel() ?>" title="<?=$tool->getTitle() ?>" />
                  <?
                  $addVal = $tool->getSubmitValues();
                  foreach ($addVal as $key => $value) {
                     echo "<input type=\"hidden\" name=\"$key\" value=\"" . (string) $value . "\" />";
                  }?>
                  </div>
               </form>
               <?
               break;
            case 'Template_Toolbox2_Tool_Form':
               ?>
               <form action="<?=$tool->getForm()->getAction();?>" method="<?=$tool->getForm()->getSendMethod();?>" onsubmit="<?=$formOnSubmit?>">
                  <div><img src="<?=$this->iconsDir . $tool->getIcon() ?>" alt="icon <?=$tool->getIcon() ?>"/><?
               
               foreach ($tool->getForm() as $element) {
                  if($element instanceof Form_Element_Submit OR $element instanceof Form_Element_SubmitImage){
                     ?><input class="toolbox-tool-button" type="submit" name="<?=$element->getName()?>"
                         value="<?=$element->getLabel()?>" title="<?=$element->getLabel() ?>" /><?
                  } else if($element instanceof Form_Element_Hidden) {
                     ?><input type="hidden" name="<?=$element->getName();?>" value="<?=$element->getValues() ?>" /><?
                  }
               }
                  ?><input type="hidden" name="<?=$tool->getForm()->getFormChecker()->getName();?>" value="<?=$tool->getForm()->getFormChecker()->getValues() ?>" /><?
               ?></div></form><?
               break;
            default:
               echo "nepodporovaný nástroj";
               break;
         }
      ?>
      </div>
   <? } ?>
</div>
