<div class="toolbox-inline" id="toolbox-<?=rand(1, time());?>-box">
   <? foreach ($this->getTools() as $name => $tool) {
      $class = get_class($tool);
      if($class == "Template_Toolbox2_Tool_LangLoader" AND !Locales::isMultilang()) continue;
      ?>
      <div class="toolbox-tool-inline">
      <?
         $formOnSubmit = null;
         if($tool->getConfirmMessage() != null){
            $formOnSubmit .= 'return confirm(\''.$tool->getConfirmMessage().'\');';
         }
         $image = $this->iconsDir . Template_Toolbox2::ICON_WRENCH;
         if($tool->getIcon() != null){
           $image = $this->iconsDir . $tool->getIcon();
         }

         switch ($class) {
            case 'Template_Toolbox2_Tool_PostRedirect':
               ?>
         <form action="<?=$tool->getAction() ?>" method="post" onsubmit="<?=$formOnSubmit?>" name="<?=$name?>">
            <div>
               <button class="toolbox-tool-inline-button" type="submit" 
                       title="<?=$tool->getTitle() ?>" name="<?=$tool->getName() ?>_button" value="<?=$tool->getLabel() ?>"
                       ><span class="icon icon-<?=$tool->getIcon()?>"></span></button>
                  <?php
                  $addVal = $tool->getSubmitValues();
                  foreach ($addVal as $key => $value) {
                     echo "<input type=\"hidden\" name=\"$key\" value=\"" . (string) $value . "\" />";
                  }?>
                  </div>
               </form>
               <?
               break;
            case 'Template_Toolbox2_Tool_Redirect':
               // tohle má být odkaz
               $addVal = $tool->getSubmitValues();
               $link = $tool->getAction();
               foreach ($addVal as $key => $value) {
                  $link->param($key, $value);
               }
               ?><a href="<?=$link ?>" title="<?ps($tool->getTitle())?>"
                  id="toolbox-button-<?=substr(md5($link), 0,8)?>" onclick="<?=$formOnSubmit?>" 
                  class="toolbox-tool-inline-button toolbox-button-<?=$name?>"
                  ><span class="icon icon-<?=$tool->getIcon()?>"></span></a>
               <?
               break;
            case 'Template_Toolbox2_Tool_Form':
               ?>
               <form action="<?=$tool->getForm()->getAction();?>" method="<?=$tool->getForm()->getSendMethod();?>" onsubmit="<?=$formOnSubmit?>" name="<?=$name?>">
                  <div><?foreach ($tool->getForm() as $element) {
                  if($element instanceof Form_Element_Submit OR $element instanceof Form_Element_SubmitImage){
                     ?>
                     <button class="toolbox-tool-inline-button" type="submit" 
                       title="<?=$element->getLabel() ?>" name="<?=$element->getName() ?>_button" value="<?=$element->getLabel() ?>"
                       ><span class="icon icon-<?=$tool->getIcon()?>"></span></button>
                     <?
                  } else if($element instanceof Form_Element_Hidden) {
                     ?><input type="hidden" name="<?=$element->getName();?>" value="<?=$element->getValues() ?>" /><?
                  }
               }
                  ?><input type="hidden" name="<?=$tool->getForm()->getFormChecker()->getName();?>" value="<?=$tool->getForm()->getFormChecker()->getValues() ?>" /><?
               ?></div></form><?
               break;
            case 'Template_Toolbox2_Tool_LangLoader':
               ?>
               <div style="font-size: small;"><?=$image?>
               <?
               echo $this->tr('Ukaž');
               $link = new Url_Link();
                  foreach($tool->getLangs() as $key => $lang){?>
                     <a class="toolbox-changelang-button" href="<?if(Locales::getLang() != $key){ echo $link->param('l', $key); } else {echo $link->param('l');}?>" 
                        title="<?=$lang?>"><img src="images/langs/small/<?=$key?>.png" /></a>
                  <?}?>
               </div>
               <?
               break;
            case 'Template_Toolbox2_Tool_Button':
               ?>
               <button class="toolbox-button toolbox-button-<?ps($name)?>" title="<?ps($tool->getTitle())?>"
                       onclick="<?=$formOnSubmit?>"><span class="icon icon-<?=$tool->getIcon()?>"></span></button>
               <?
               break;
            default:
               echo $this->tr("nepodporovaný nástroj");
               break;
         }
      ?>
      </div>
   <? } ?>
</div>
