<?
$this->addJsPlugin(new JsPlugin_JQuery());
$this->addJsPlugin(new JsPlugin_JQueryCSS());
?>
<a class="toolbox-button ui-button ui-state-default ui-corner-all" href=""
   title="Otevřít nástroje"><span class="ui-icon ui-icon-pencil"></span></a>
<div class="toolbox ui-widget">
   <?
   $step =1;
   $countTools = count($this->getTools());
   foreach ($this->getTools() as $tool) {?>
      <div class="toolbox-tool">
      <?
         $formOnSubmit = null;
         if($tool->getConfirmMessage() != null){
            $formOnSubmit .= 'return confirm(\''.$tool->getConfirmMessage().'\');';
         }
         $class = get_class($tool);
         switch ($class) {
            case 'Template_Toolbox2_Tool_PostRedirect':
               ?>
         <form action="<?=$tool->getAction() ?>" method="post" onsubmit="<?=$formOnSubmit?>">
            <div class="ui-state-default<?if($step == 1){echo ' ui-corner-top';} if($step == $countTools){echo ' ui-corner-bottom';}?>"><span class="ui-icon ui-icon-pencil"></span>
            <?/*<img src="<?=$this->iconsDir . $tool->getIcon() ?>" alt="icon <?=$tool->getIcon() ?>" />*/?>
                  <input class="ui-helper-reset ui-button ui-state-default" type="submit" name="<?=$tool->getName() ?>_button"
                     value="<?=$tool->getLabel()?>" title="<?=$tool->getTitle() ?>" />
                  <?
                  $addVal = $tool->getSubmitValues();
                  foreach ($addVal as $key => $value) {
                     echo "<input type=\"hidden\" name=\"$key\" value=\"" . (string) $value . "\" />";
                  }?>
                  </div>
               </form>
               <?
               break;
            case 'Template_Toolbox2_Tool_Form':
               ?>
               <form action="<?=$tool->getForm()->getAction();?>" method="<?=$tool->getForm()->getSendMethod();?>" onsubmit="<?=$formOnSubmit?>">
                  <div class="ui-state-default<?if($step == 1){echo ' ui-corner-top';} if($step == $countTools){echo ' ui-corner-bottom';}?>"><span class="ui-icon ui-icon-closethick"></span>
                  <?/*<img src="<?=$this->iconsDir . $tool->getIcon() ?>" alt="icon <?=$tool->getIcon() ?>"/><?*/
               
               foreach ($tool->getForm() as $element) {
                  if($element instanceof Form_Element_Submit OR $element instanceof Form_Element_SubmitImage){
                     ?><input class="ui-helper-reset ui-button ui-state-default" type="submit" name="<?=$element->getName()?>"
                         value="<?=$element->getLabel()?>" title="<?=$element->getLabel() ?>" /><?
                  } else if($element instanceof Form_Element_Hidden) {
                     ?><input class="ui-helper-hidden" type="hidden" name="<?=$element->getName();?>" value="<?=$element->getValues() ?>" /><?
                  }
               }
               ?><input class="ui-helper-hidden" type="hidden" name="<?=$tool->getForm()->getFormChecker()->getName();?>" value="<?=$tool->getForm()->getFormChecker()->getValues() ?>" /><?
               ?></div></form><?
               break;
            default:
               echo "nepodporovaný nástroj";
               break;
         }
         $step++;
      ?>
      </div>
   <? } ?>
</div>
