<?
$this->addJsPlugin(new JsPlugin_JQuery());
$this->addJsPlugin(new JsPlugin_JQueryCSS());
$rTime = rand(1, time());
?>
<a class="toolbox-button ui-state-default ui-corner-all" id="toolbox-<?=$rTime?>-button"
   href="" title="<?$this->tr('Otevřít nástroje')?>"><img src="<?=$this->iconsDir.$this->toolboxIcon?>" alt="icon <?=$this->toolboxIcon?>" height="16" /></a>
<div class="toolbox" id="toolbox-<?=$rTime?>-box">
   <? foreach ($this->getTools() as $name => $tool) {
      $class = get_class($tool);
      if($class == "Template_Toolbox2_Tool_LangLoader" AND !Locales::isMultilang()) continue;
      ?>
      <div class="toolbox-tool ui-state-default">
      <?
         $formOnSubmit = null;
         if($tool->getConfirmMessage() != null){
            $formOnSubmit .= 'return confirm(\''.$tool->getConfirmMessage().'\');';
         }
         $image = null;
         if($tool->getIcon() != null){
           $image = '<img src="'.$this->iconsDir . $tool->getIcon().'" alt="icon '.$tool->getIcon().'" />';
         }

         switch ($class) {
            case 'Template_Toolbox2_Tool_PostRedirect':
               ?>
         <form action="<?=$tool->getAction() ?>" method="post" onsubmit="<?=$formOnSubmit?>" name="<?=$name?>">
            <div><?=$image;?><input class="toolbox-tool-button ui-state-default" type="submit" name="<?=$tool->getName() ?>_button"
                     value="<?=$tool->getLabel() ?>" title="<?=$tool->getTitle() ?>" />
                  <?
                  $addVal = $tool->getSubmitValues();
                  foreach ($addVal as $key => $value) {
                     echo "<input type=\"hidden\" name=\"$key\" value=\"" . (string) $value . "\" />";
                  }?>
                  </div>
               </form>
               <?
               break;
            case 'Template_Toolbox2_Tool_Redirect':
               ?>
         <form action="<?=$tool->getAction()?>" method="get" onsubmit="<?=$formOnSubmit?>" name="<?=$name?>">
            <div><?=$image;?><input class="toolbox-tool-button ui-state-default" type="submit"
                     value="<?=$tool->getLabel() ?>" title="<?=$tool->getTitle() ?>" />
                  <?
                  $addVal = $tool->getSubmitValues();
                  foreach ($addVal as $key => $value) {
                     echo "<input type=\"hidden\" name=\"$key\" value=\"" . (string) $value . "\" />";
                  }?>
                  </div>
               </form>
               <?
               break;
            case 'Template_Toolbox2_Tool_Form':
               ?>
               <form action="<?=$tool->getForm()->getAction();?>" method="<?=$tool->getForm()->getSendMethod();?>" name="<?=$name?>" onsubmit="<?=$formOnSubmit?>">
                  <div><?=$image;?><?

               foreach ($tool->getForm() as $element) {
                  if($element instanceof Form_Element_Submit OR $element instanceof Form_Element_SubmitImage){
                     ?><input class="toolbox-tool-button ui-state-default" type="submit" name="<?=$element->getName()?>"
                         value="<?=$element->getLabel()?>" title="<?=$element->getLabel() ?>" /><?
                  } else if($element instanceof Form_Element_Hidden) {
                     ?><input type="hidden" name="<?=$element->getName();?>" value="<?=$element->getValues() ?>" /><?
                  }
               }
                  ?><input type="hidden" name="<?=$tool->getForm()->getFormChecker()->getName();?>" value="<?=$tool->getForm()->getFormChecker()->getValues() ?>" /><?
               ?></div></form><?
               break;
            case 'Template_Toolbox2_Tool_LangLoader':
               ?>
               <div style="font-size: small;"><?=$image?>
               <?
               echo $this->tr('Ukaž');
               $link = new Url_Link();
                  foreach($tool->getLangs() as $key => $lang){?>
                     <a class="toolbox-changelang-button" href="<?if(Locales::getLang() != $key){ echo $link->param('l', $key); } else {echo $link->param('l');}?>" 
                        title="<?=$lang?>"><img src="images/langs/small/<?=$key?>.png" /></a>
                  <?}?>
               </div>
               <?
               break;
            default:
               echo $this->tr("nepodporovaný nástroj");
               break;
         }
      ?>
      </div>
   <? } ?>
</div>
