<?php 
$this->addFile('css://engine:admin/admin.less');// need for buttons style
?>
<div class="toolbox-inline" id="toolbox-<?php echo rand(1, time());?>-box">
   <?php  foreach ($this->getTools() as $name => $tool) {
      $class = get_class($tool);
      if($class == "Template_Toolbox2_Tool_LangLoader" AND !Locales::isMultilang()) continue;

      $toolClasses = array();
      $tool->getImportant() ? $toolClasses[] = 'important' : '';
      $class == "Template_Toolbox2_Tool_LangLoader" ? $toolClasses[] = 'multitool' : '';
      ?>
      <div class="toolbox-tool-inline <?php echo implode(' ', $toolClasses)?>">
      <?php 
         $formOnSubmit = null;
         if($tool->getConfirmMessage() != null){
            $formOnSubmit .= 'return confirm(\''.$tool->getConfirmMessage().'\');';
         }
         $image = $this->iconsDir . Template_Toolbox2::ICON_WRENCH;
         if($tool->getIcon() != null){
           $image = $this->iconsDir . $tool->getIcon();
         }

         switch ($class) {
            case 'Template_Toolbox2_Tool_PostRedirect':
               ?>
         <form action="<?php echo $tool->getAction() ?>" method="post" onsubmit="<?php echo $formOnSubmit?>" name="<?php echo $name?>">
            <div>
               <button class="toolbox-tool-inline-button" type="submit" 
                       title="<?php echo $tool->getTitle() ?>" name="<?php echo $tool->getName() ?>_button" value="<?php echo $tool->getLabel() ?>"
                       ><span class="icon icon-<?php echo $tool->getIcon()?> icon-fw"></span></button>
                  <?php
                  $addVal = $tool->getSubmitValues();
                  foreach ($addVal as $key => $value) {
                     echo "<input type=\"hidden\" name=\"$key\" value=\"" . (string) $value . "\" />";
                  }?>
                  </div>
               </form>
               <?php 
               break;
            case 'Template_Toolbox2_Tool_Redirect':
               // tohle má být odkaz
               $addVal = $tool->getSubmitValues();
               $link = $tool->getAction();
               foreach ($addVal as $key => $value) {
                  $link->param($key, $value);
               }
               ?><a href="<?php echo $link ?>" title="<?php ps($tool->getTitle())?>"
                  id="toolbox-button-<?php echo substr(md5($link), 0,8)?>" onclick="<?php echo $formOnSubmit?>" 
                  class="toolbox-tool-inline-button toolbox-button-<?php echo $name?>"
                  ><span class="icon icon-<?php echo $tool->getIcon()?> icon-fw"></span></a>
               <?php 
               break;
            case 'Template_Toolbox2_Tool_Form':
               ?>
               <form action="<?php echo $tool->getForm()->getAction();?>" method="<?php echo $tool->getForm()->getSendMethod();?>" onsubmit="<?php echo $formOnSubmit?>" name="<?php echo $name?>">
                  <div><?php foreach ($tool->getForm() as $element) {
                  if($element instanceof Form_Element_Submit OR $element instanceof Form_Element_SubmitImage){
                     ?>
                     <button class="toolbox-tool-inline-button" type="submit" 
                       title="<?php echo $element->getLabel() ?>" name="<?php echo $element->getName() ?>_button" value="<?php echo $element->getLabel() ?>"
                       ><span class="icon icon-<?php echo $tool->getIcon()?> icon-fw"></span></button>
                     <?php 
                  } else if($element instanceof Form_Element_Hidden) {
                     ?><input type="hidden" name="<?php echo $element->getName();?>" value="<?php echo $element->getValues() ?>" /><?php 
                  }
               }
                  ?><input type="hidden" name="<?php echo $tool->getForm()->getFormChecker()->getName();?>" value="<?php echo $tool->getForm()->getFormChecker()->getValues() ?>" /><?php 
               ?></div></form><?php 
               break;
            case 'Template_Toolbox2_Tool_LangLoader':
               ?>
               <div style="font-size: small;"><?php echo $image?>
               <?php 
               echo $this->tr('Ukaž');
               $link = new Url_Link();
                  foreach($tool->getLangs() as $key => $lang){?>
                     <a class="toolbox-changelang-button" href="<?php if(Locales::getLang() != $key){ echo $link->param('l', $key); } else {echo $link->param('l');}?>" 
                        title="<?php echo $lang?>"><img src="images/langs/small/<?php echo $key?>.png" /></a>
                  <?php }?>
               </div>
               <?php 
               break;
            case 'Template_Toolbox2_Tool_Button':
               ?>
               <button class="toolbox-button toolbox-button-<?php ps($name)?>" title="<?php ps($tool->getTitle())?>"
                       onclick="<?php echo $formOnSubmit?>"><span class="icon icon-<?php echo $tool->getIcon()?> icon-fw"></span></button>
               <?php 
               break;
            default:
               echo $this->tr("nepodporovaný nástroj");
               break;
         }
      ?>
      </div>
   <?php  } ?>
</div>
