<?php 
   // funkce pro render menu
   function bootstrapMenuRenderFunc($menuArr, $link) {
      foreach ($menuArr as $key => $item) {
         if(!$item->isEmpty()){
            echo '<li class="dropdown">';
//            echo '<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">'
//                .$item->getCatObj()->getLabel().' <span class="caret"></span></a>'."";
            echo '<a href="'.$link->clear()->category($item->getCatObj()->getUrlKey()).'" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">'
                .$item->getCatObj()->getLabel().' <span class="caret"></span></a>'."";
            echo '<ul  class="dropdown-menu" role="menu">'."\n";
            bootstrapMenuRenderFunc($item, $link);
            echo '</ul>'."\n";
         } else {
            echo '<li>';
            echo '<a href="'.$link->clear()->category($item->getCatObj()->getUrlKey()).'">'
                .$item->getCatObj()->getLabel().'</a>'."";
         }
         echo '</li>'."\n";
      }
   }
?>
<div class="collapse navbar-collapse" id="main-nav">
   <ul class="nav navbar-nav">
      <?php echo bootstrapMenuRenderFunc($this->menu, $this->link())?>
   </ul>
</div>