<div class="alert alert-info" id="infoMessages" role="alert" <?php if(empty ($this->messages)){ echo 'style="display:none;"';}?>>
     <?php // Vypis hlasek
     if(!empty ($this->messages)) {
        foreach ($this->messages as $message) {
           echo '<p>'.$message . '</p>';
        }
     }?>
</div>
<!--{*-CORE_ERRORS-*}-->
<?php  // chyby modulu?>
<div class="alert alert-danger" id="errMessages" role="alert" <?php if(empty ($this->moduleErrors) AND Template::pVar('IE_WARN') == false) { echo 'style="display:none;"';}?>>
   <?php 
   if(Template::pVar('IE_WARN') == true){ $this->includeTpl('ie6browser.phtml',true); }
   if(!empty ($this->moduleErrors)) {
      echo("<strong>".$this->tr("Chyba:")."</strong>");
      foreach ($this->moduleErrors as $error) {
         echo '<p>'.$error . '</p>';
      }
   }?>
</div>