<?
$this->addPageHeadline($this->_('Seznam registrovaných e-mailových adres'));
$this->addPageTitle($this->_('Seznam registrovaných e-mailových adres'));

$this->addJsPlugin(new JsPlugin_DataTables());
?>
<div>
   <h2><?=$this->_('Seznam registrovaných e-mailů')?></h2>
   <table id="tableMails" style="width: 100%;">
      <thead>
		<tr>
         <th>E-mail</th>
			<th style="width: 140px"><?=$this->_('Přidáno')?></th>
         <th style="width: 140px">
            <?=$this->_('Označit')?>&nbsp;
            (<a href="#" id="selectAll" title="<?=$this->_('vše')?>" ><?=$this->_('vše')?></a>,&nbsp;
            <a href="#" id="selectNon" title="<?=$this->_('nic')?>" ><?=$this->_('nic')?></a>)
         </th>
		</tr>
	</thead>
   <tbody>
      <?foreach ($this->mails as $mail) {?>
      <tr>
         <td><a href="mailto:<?=$mail->{NewsLetter_Model_Mails::COLUMN_MAIL}?>"
                title="<?=$this->_('Poslat email')?>"
                ><?=$mail->{NewsLetter_Model_Mails::COLUMN_MAIL}?></a></td>
         <td><?=vve_date("%x", new DateTime($mail->{NewsLetter_Model_Mails::COLUMN_DATE_ADD}))?></td>
         <td align="center">
            <input type="checkbox" name="select_item[<?=$mail->{NewsLetter_Model_Mails::COLUMN_ID}?>]" />
         </td>
      </tr>
      <?}?>
   </tbody>
   </table>
   <hr class="reseter" />
   <div>
      <strong><?=$this->_('Označené')?>:</strong>&nbsp;
      <button type="submit" name="delete_items" title="<?=$this->_('Smazat označené')?>"
              value="<?=$this->_('Smazat')?>"><?=$this->_('Smazat')?></button>&nbsp;
      <form id="sendmail_form" action="<?=$this->link()->route('sendMail')?>" method="post" style="display: inline">
      <input type="hidden" name="sendmail_items" value="" />
      <input type="submit" name="sendmail_getform" title="<?=$this->_('Poslat e-mail označeným')?>"
              value="<?=$this->_('Poslat e-mail')?>" />&nbsp;
   </form>
   </div>
      <script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				var $table = $('#tableMails').dataTable( {
					"oLanguage": {
						"sLengthMenu": "<?=$this->_('Zobrazit _MENU_ záznamů na stránku')?>",
						"sZeroRecords": "<?=$this->_('Nic nenalezeno')?>",
						"sInfo": "<?=$this->_('Zobrazeno od _START_ do _END_ z _TOTAL_ záznamů')?>",
						"sInfoEmtpy": "<?=$this->_('Zobrazeno 0 z 0 záznamů')?>",
						"sInfoFiltered": "(<?=$this->_('filtrováno z _MAX_ celkových záznamů')?>)"
					}
				});

            $('button[name=delete_items]').click(function(){
               var $items = getTableItems();
               if($items.length == 0){
                  errMsg('<?=$this->_('Nebyla vybrána žádná položka')?>');
                  return false;
               }
               if(!confirm('<?=$this->_('Smazat označené?')?>')){return false;}

               $.ajax({url: '<?=$this->link()->route('deleteMails')?>',
                  data : $items.serialize(),
                  success: function(data) {
                     if(data.status == true){//delete items
                        var $items = getSelectedItems();
                        $items.each(function(index){
                           if($(this).is(':checked')){
                              $table.fnDeleteRow(index);
                           }
                        });
                     }
                     vveShowMessages(data);
                  }
               });

            });
            // serializace označených emailů
            $('form#sendmail_form').submit(function(){
               var $items = getTableItems();
               if($items.length == 0){
                  errMsg('<?=$this->_('Nebyla vybrána žádná položka')?>');
                  return false;
               }

               $items.each(function(){
                  if($(this).is(':checked')){
                     var item = $(this).clone().hide();
                     $('form#sendmail_form').append(item);
                  }
               });
            });

            $('a#selectAll').click(function(){
               getTableItems().attr('checked', true);
               return false;
            });
            $('a#selectNon').click(function(){
               getTableItems().attr('checked', false);
               return false;
            });

         function getTableItems(){
//            return $('#tableMails input[type=checkbox]:checked');
            return $('input[type=checkbox]', $table.fnGetNodes());
//            return $('input[type=checkbox]', $table.fnGetNodes());
         }
			});
		</script>
   <br />
   <h2><?=$this->_('Export adres')?></h2>
   <a href="<?=$this->link()->route('export',array('output' => 'txt'))?>">txt</a>
   <a href="<?=$this->link()->route('export',array('output' => 'csv'))?>">csv</a>
   <br />
   <br />
<?$this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->link()->route(null)));?>
</div>
