<?php 
$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
$this->form->html()->addClass('regMailFormPanel');
?>
<div class="name"><?php echo $icon?><a href="<?php echo $this->link()?>" title="<?php echo htmlspecialchars($this->panelObj()->getName())?>"><?php echo $this->panelObj()->getName()?></a></div>
<div class="content" style="<?php echo $backImg?>">
   <div class="text">
      <?php echo $this->tr('Registrace k odběru novinek e-mailem')?>
   </div>
   <div class="text">
   <?php echo $this->form->renderStart();?>
      <?php 
      $this->form->mail->html()->setAttrib('size', '15');
      echo $this->form->mail->label().'<br />';
      echo $this->form->mail->controll().'<br />';?>
      <p>
      <?php echo $this->form->send->controll()?><br />
      </p>
      <?php echo $this->form->renderEnd();?>
   </div>
</div>
<div class="link-more">
   <a href="<?php echo $this->link()?>"
      title="<?php echo htmlspecialchars($this->category()->getLabel())?>"><?php echo $this->tr('Více')?></a>
</div>
<?php if(!defined('VVE_REGMAIL_RENDER')){
define('VVE_REGMAIL_RENDER', true);
   ?>
<script type="text/javascript">
   /* <![CDATA[ */
   $('form.regMailFormPanel').live('submit',function(){
      var jform = $(this);
      showLoadBox(jform);
      $.ajax({
         type: "POST",
         cache: false,
         url: '<?php echo $this->link()->clear()->route();?>',
         data: jform.serialize(),
         dataType: "json",
         success: function(data) {
            vveShowMessages(data);
            hideLoadBox();
         },
         error : function(){
            hideLoadBox();
         }
      });
      return false;
   });
   /* ]]> */
</script>
<?php }?>
