<?
if($this->text != false AND (string)$this->text->{Text_Model_Detail::COLUMN_LABEL} != null){
   $this->addPageHeadline($this->text->{Text_Model_Detail::COLUMN_LABEL});
}
$this->addJsPlugin(new JsPlugin_JQuery());
?>
<div>
   <?if($this->text != false AND (string)$this->text->{Text_Model_Detail::COLUMN_TEXT} != null){?>
   <div class=""><?=$this->text->{Text_Model_Detail::COLUMN_TEXT}?></div>
   <?}?>
   <br />
   <strong><?=$this->_('Registrace e-mailu')?></strong><br />
   <?
   $this->newMailForm->html()->setAttrib('id', 'registerNewMail');
   print($this->newMailForm->renderStart());
   print($this->newMailForm->mail->controll());
   print($this->newMailForm->send->controll());
   print($this->newMailForm->renderEnd());

   if($this->toolbox != null) $this->includeTplObj($this->toolbox);
   ?>
      <br />
      <a href="<?=$this->link()->route('unregistration');?>"
         title="<?=$this->_('Zrušit registraci e-mailu')?>"
         ><?=$this->_('Zrušit registraci e-mailu')?></a>
</div>
<script type="text/javascript">
   /* <![CDATA[ */
   $('form#registerNewMail').submit(function(){
      $.ajax({type: "POST",
         url: "<?=$this->link()->route('normal')?>",
         data: $(this).serialize(),
         success: function(data){
            vveShowMessages(data);
         }
      });
      return false;
   });
   /* ]]> */
</script>