<?php 
$h = $this->category()->getName();
if($this->text != false AND (string)$this->text->{Text_Model_Detail::COLUMN_LABEL} != null){
   $h = ($this->text->{Text_Model_Detail::COLUMN_LABEL});
   Template_Core::setPageTitle($h);
}
$this->addJsPlugin(new JsPlugin_JQuery());

echo $this->toolbox;
?>
<h1><?php ps($h)?></h1>
<div class="content">
   <?php if($this->text != false AND (string)$this->text->{Text_Model_Detail::COLUMN_TEXT} != null){?>
   <div class=""><?php echo $this->text->{Text_Model_Detail::COLUMN_TEXT}?></div>
   <?php }?>
   <?php 
   $this->newMailForm->html()->setAttrib('id', 'registerNewMail');
   echo $this->newMailForm;
   ?>
      <br />
      <a href="<?php echo $this->link()->route('unregistration');?>"
         title="<?php echo $this->tr('Zrušit registraci e-mailu')?>"
         ><?php echo $this->tr('Zrušit registraci e-mailu')?></a>
</div>
<script type="text/javascript">
   /* <![CDATA[ */
   $('form#registerNewMail').submit(function(){
      $.ajax({type: "POST",
         url: "<?php echo $this->link()?>",
         data: $(this).serialize(),
         success: function(data){ vveShowMessages(data); }
      });
      return false;
   });
   /* ]]> */
</script>