<?
$this->addPageTitle($this->_('odeslání e-mailu'));
$this->addPageHeadline($this->_('odeslání e-mailu'));
?>
<div id="sendMailForm">
   <?
   $tinymce = new JsPlugin_TinyMce();
   $tinymce->setCfgParam('theme', 'advancedsimple');
   $tinymce->setCfgParam('editor_selector', 'mceEditorSimple');
   $this->addJsPlugin($tinymce);
   ?>
<?echo $this->form->renderStart();?>
   <table>
      <tr>
         <td>
         <?echo $this->form->recipients->label()?><br />
         <? $this->form->recipients->html()->setAttrib('cols', 60);
         echo $this->form->recipients->controll();?>
         <?echo $this->form->recipients->sublabel()?>
         <br />
         </td>
      </tr>
      <tr>
         <td>
         <?echo $this->form->subject->label()?><br />
         <?$this->form->subject->html()->setAttrib('size', 60);
         echo $this->form->subject->controll();?><br />
         <br />
         </td>
      </tr>
      <tr>
         <td>
         <?echo $this->form->text->label()?><br />
         <?
         $this->form->text->html()->setAttrib('cols', 60)->setAttrib('rows', 15)->addClass('mceEditorSimple');
         echo $this->form->text->controll();?>
         <br />
         </td>
      </tr>
      <tr>
         <td>
            <?echo $this->form->send->controll()?>
         </td>
      </tr>
   </table>
<?echo $this->form->renderEnd();?>
</div>
<br />
<?$this->includeTpl("buttonback.phtml", true, array('link'=>(string)$this->link()->route('list')));?>