<?php 
$h = $this->tr('Zrušení registrace e-mailu');
Template_Core::addPageTitle($h);
$this->addJsPlugin(new JsPlugin_JQuery());
?>
<h1><?php ps($h)?></h1>
<div class="content content-form-edit">
   <?php 
   $this->unregMailForm->html()->setAttrib('id', 'unregisterMail');
   echo $this->unregMailForm;
   ?>
</div>
<script type="text/javascript">
   /* <![CDATA[ */
   $('form#unregisterMail').submit(function(){
      $.ajax({type: "POST",
         url: "<?php echo $this->link()?>",
         data: $(this).serialize(),
         success: function(data){
            vveShowMessages(data);
         }
      });
      return false;
   });
   $('input[name="unregmail_send_cancel"]').click(function(e){
      e.preventDefault();
      window.location.href = '<?php echo $this->link()->route()?>';
   });
   /* ]]> */
</script>