<?php 
function tplCatTrRights(Translator $translator, $right)
{
   $out = null;
   if($right[0] == 'r'){
      $out .= $translator->tr('čtení').', ';
   }
   if($right[1] == 'w'){
      $out .= $translator->tr('zápis').', ';
   }
   if($right[2] == 'c'){
      $out .= $translator->tr('plný přístup').', ';
   }
   if($out == null){
      $out .= $translator->tr('Nemá přidělena žádná práva').' ';
   }
   
   return $out.'('.$right.')';
}

$disabled = array();
foreach ($this->catInfo->{Model_Category::COLUMN_DISABLE} as $lang => $dis) {
   if((bool)$dis){
      $disabled[] = $lang;
   }
}

?>
<input type="hidden" name="id_cat" value="<?php echo $this->catInfo->{Model_Category::COLUMN_CAT_ID};?>" />
<table class="cubecms-widget cubecms-table">
   <tr>
      <th colspan="3" class="cubecms-header"><?php echo $this->tr('Názvy (s jazyky)');?>:</th>
   </tr>
   <?php foreach ($this->catInfo[Model_Category::COLUMN_NAME] as $lang => $name) {
      if($name != null){?>
      <tr class="cubecms-row">
         <td colspan="2"><?php echo   htmlspecialchars($name);?></td><td class="cell-lang"><?php echo vve_tpl_lang_image($lang)?></td>
      </tr><?php }
   }?>
   <tr><th class="cubecms-header" colspan="3"><?php echo $this->tr('Adresy URL (s jazyky)');?>:</th></tr>
   <?php 
   $link = new Url_Link(true);
   foreach ($this->catInfo[Model_Category::COLUMN_URLKEY] as $lang => $key) {
      if($key != null){?>
      <tr class="cubecms-row">
         <td class="editable" colspan="2" >
            <a href="<?php echo $link->lang($lang)->category($key);?>" title="<?php echo $this->tr('Otevřít v novém okně')?>"
               class="link-external"><?php echo $key?></a>
         </td>
         <td class="cell-lang"><?php echo '&nbsp;'.vve_tpl_lang_image($lang)?></td>
      </tr><?php }
   }
   if(!empty($disabled)){?>
   <tr class="cubecms-row">
      <th>Vypnuté jazyky</th>
      <td colspan="2"><?php 
         foreach ($disabled as $lang) {
            echo vve_tpl_lang_image($lang).'&nbsp;';
         }
      ?></td>
   </tr>
   <?php }?>
</table>
<table class="cubecms-widget cubecms-table">
   <tr class="cubecms-row">
      <th class=""><?php echo $this->tr('Modul');?></th>
      <td class=""><?php echo $this->catInfo->{Model_Category::COLUMN_MODULE};?></td>
   </tr>
   <tr class="single-row cubecms-row">
      <th class=""><?php echo $this->tr('ID');?></th>
      <td class=""><?php echo $this->catInfo->{Model_Category::COLUMN_CAT_ID};?></td>
   </tr>
   <tr class="cubecms-row">
      <th class=""><?php echo $this->tr('Viditelné');?></th>
      <td class="">
         <select name="cat_visibility">
            <?php foreach ($this->visTypes as $type => $label) {?>
            <option value="<?php echo $type?>" <?php if($this->catInfo->{Model_Category::COLUMN_VISIBILITY} == $type) echo 'selected="selected"'?>><?php echo $label?></option>
            <?php }?>
         </select>
     </td>
   </tr>
   <tr class="cubecms-row">
      <th class=""><?php echo $this->tr('Individuální rozložení panelů');?></th>
      <td class=""><input type="checkbox" name="cat_ind_panels"
      <?php if($this->catInfo->{Model_Category::COLUMN_INDIVIDUAL_PANELS} == true) echo 'checked="checked"';?> /></td>
   </tr>
   <tr class="cubecms-row">
      <th class=""><?php echo $this->tr('Výchozí práva');?></th>
      <td class=""><?php echo tplCatTrRights($this->translator(), $this->catInfo->{Model_Category::COLUMN_DEF_RIGHT});?></td>
   </tr>
   <tr class="cubecms-row">
      <th class=""><?php echo $this->tr('Vlastník');?></th>
      <td class=""><?php 
      if($this->owner->{Model_Users::COLUMN_NAME} != null){
         echo $this->owner->{Model_Users::COLUMN_SURNAME}.' '.$this->owner->{Model_Users::COLUMN_NAME}." (".$this->owner->{Model_Users::COLUMN_USERNAME}.")";
      } else {
         echo $this->owner->{Model_Users::COLUMN_USERNAME};
      }?></td>
   </tr>
   <tr class="cubecms-row">
      <th class=""><?php echo $this->tr('Priorita');?></th>
      <td class=""><?php echo $this->catInfo->{Model_Category::COLUMN_PRIORITY};?></td>
   </tr>
</table>
<table class="cubecms-widget cubecms-table">
   <tr class="cubecms-row"><th class="" colspan="2"><?php echo $this->tr('Datový adresář');?>:</th></tr>
   <tr class="cubecms-row"><td colspan="2"><?php echo VVE_DATA_DIR.'/'.$this->catInfo->{Model_Category::COLUMN_DATADIR}.'/'?></td></tr>
   <tr><th class="" colspan="2"><?php echo $this->tr('Popis');?>:</th></tr>
   <tr class="cubecms-row"><td colspan="2"><?php 
      echo (string)$this->catInfo->{Model_Category::COLUMN_ALT} == null ? $this->tr('Není') : $this->catInfo->{Model_Category::COLUMN_ALT};
   ?></td></tr>
<!--   Vyhledávač -->
   <tr class="cubecms-row"><th class="" colspan="2">
      <?php echo $this->tr('Popis (vyhledávač)');?>:
 <!--     <?php foreach (Locales::getAppLangsNames() as $lang => $desc) {?>
         <a href="<?php echo $this->link()->clear()->anchor('desc_'.$lang)?>" title="<?php echo $this->tr('Zobraz ').$desc?>" class=""><?php echo vve_tpl_lang_image($lang)?></a>
      <?php }?>-->
   </th></tr>
   
   <tr class="cubecms-row"><td colspan="2"><?php 
   echo (string)$this->catInfo->{Model_Category::COLUMN_DESCRIPTION} == null ? $this->tr('Není') : $this->catInfo->{Model_Category::COLUMN_DESCRIPTION};
   ?></td></tr>

   <tr class="cubecms-row"><th class="" colspan="2"><?php echo $this->tr('Klíčová slova (vyhledávač)');?>:</th></tr>
   <tr class=""><td colspan="2"><?php 
   echo (string)$this->catInfo->{Model_Category::COLUMN_KEYWORDS} == null ? $this->tr('Není') : $this->catInfo->{Model_Category::COLUMN_KEYWORDS};
   ?></td></tr>
</table>
<table class="cubecms-widget cubecms-table">
   <tr class="cubecms-row"><th class="" colspan="2"><?php echo $this->tr('Práva skupin');?>:</th></tr>
   <?php   foreach ($this->catRights as $right) {?>
   <tr class="single-row cubecms-row">
      <th scope="row" class=""><?php echo $right->{Model_Groups::COLUMN_NAME};?></th>
      <td class=""><?php echo tplCatTrRights($this->translator(), $right->{Model_Rights::COLUMN_RIGHT});?> </td>
   </tr>
   <?php }?>
   <tr class="single-row cubecms-row">
      <th scope="row" class=""><?php echo $this->tr('Ostatní');?></th>
      <td class=""><?php echo tplCatTrRights($this->translator(), $this->catInfo->{Model_Category::COLUMN_DEF_RIGHT});?></td>
   </tr>
</table>

