<?
// model s kategoriesmi
$model = new Model_Category();
$category = $model->getCategoryWoutRights($this->cat);
// model se skupinami
// TODO přepracovat
$this->setPageTitle($this->_('Uprava kategorie').' '.$category->{Model_Category::COLUMN_CAT_LABEL});
//var_dump($category);
?>

<div>
   <table>
      <tr>
         <th width="200"><?=$this->_('Název')?></th>
         <td>
            <?
            foreach (Locales::getAppLangsNames() as $langKey => $langName) {?>
            <strong><?=$langName?>:&nbsp;</strong>
               <?
               if($category[Model_Category::COLUMN_CAT_LABEL][$langKey] != null) {
                  print ($category[Model_Category::COLUMN_CAT_LABEL][$langKey].'<br />');
               } else {
                  print ('---<br />');
               }
            }?>
         </td>
      </tr>
      <tr>
         <th width="100"><?=$this->_('Url')?></th>
         <td>
            <?
            foreach (Locales::getAppLangsNames() as $langKey => $langName) {?>
            <strong><?=$langName?>:&nbsp;</strong>
               <?
               if($category[Model_Category::COLUMN_URLKEY][$langKey] != null) {
                  $link = new Url_Link(true);
                  $link->lang($langKey)->category($category[Model_Category::COLUMN_URLKEY][$langKey]);
                  print ('<a href="'.$link.'" title="'.$category[Model_Category::COLUMN_CAT_LABEL][$langKey]
                      .'">'.$link.'</a><br />');
               } else {
                  print ('---<br />');
               }
            }?>
         </td>
      </tr>
      <tr>
         <th width="100"><?=$this->_('Modul')?></th>
         <td>
            <?=$category[Model_Category::COLUMN_MODULE];?>
         </td>
      </tr>
      <tr>
         <th width="100"><?=$this->_('Priorita')?></th>
         <td>
            <?=$category[Model_Category::COLUMN_PRIORITY];?>
         </td>
      </tr>
     <tr>
         <th width="100"><?=$this->_('Klíčová slova')?></th>
         <td>
            <?
            foreach (Locales::getAppLangsNames() as $langKey => $langName) {?>
            <strong><?=$langName?>:&nbsp;</strong>
               <?
               if($category[Model_Category::COLUMN_KEYWORDS][$langKey] != null) {
                  print ($category[Model_Category::COLUMN_KEYWORDS][$langKey].'<br />');
               } else {
                  print ('---<br />');
               }
            }?>
         </td>
      </tr>
     <tr>
         <th width="100"><?=$this->_('Popis')?></th>
         <td>
            <?
            foreach (Locales::getAppLangsNames() as $langKey => $langName) {?>
            <strong><?=$langName?>:&nbsp;</strong>
               <?
               if($category[Model_Category::COLUMN_DESCRIPTION][$langKey] != null) {
                  print ($category[Model_Category::COLUMN_DESCRIPTION][$langKey].'<br />');
               } else {
                  print ('---<br />');
               }
            }?>
         </td>
      </tr>
      <?while ($group = $groups->fetch()) {?>
      <tr>
         <th width="100">
            <?=sprintf($this->_('Práva %s:'), $group[Model_Users::COLUMN_GROUP_NAME])?><br />
            <?=$group[Model_Users::COLUMN_GROUP_LABEL]?>
         </th>
         <td>
            <?=$category[Model_Category::COLUMN_GROUP_PREFIX.$group[Model_Users::COLUMN_GROUP_NAME]]?>
         </td>
      </tr>
      <?}?>

   </table>
   <?=$this->includeTpl('buttonback.phtml', true, array('link' => $this->link()->clear()))?>
<?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('edit_category', $this->_("Upravit kategorii"),
          $this->link()->route('edit', array('categoryid' => $category[Model_Category::COLUMN_CAT_ID])),
          $this->_("Upravit zobrazenou kategorii"), "text_edit.png");
      $toolbox->addTool('category_delete', $this->_("Smazat kategorii"),
          $this->link(), $this->_("Smazat zobrazenou kategorii"), "text_edit.png",
          'category_id', $category[Model_Category::COLUMN_CAT_ID],
          $this->_('Opravdu smazat kategorii? Všechna data budou odstraněna.'));
      $this->includeTplObj($toolbox);
   }
   ?>
</div>