<?
$this->addCssFile("style.less");
// do titulku
   if($this->edit) {
      if($this->adminMenu == true){
         $this->addPageTitle($this->tr('úprava administrační kategorie').' '.$this->catName);
         echo ('<h1>'.$this->tr('úprava administrační kategorie').' "'.$this->catName.'"</h1>');
      } else {
         $this->addPageTitle($this->tr('úprava kategorie').' '.$this->catName);
         echo ('<h1>'.$this->tr('úprava kategorie').' "'.$this->catName.'"</h1>');
      }
   } else {
      if($this->adminMenu == true){
         $this->addPageTitle($this->tr('přidání administrační kategorie'));
         echo ('<h1>'.$this->tr('přidání administrační kategorie').'</h1>');
      } else {
         $this->addPageTitle($this->tr('přidání kategorie'));
         echo ('<h1>'.$this->tr('přidání kategorie').'</h1>');
      }
   }

?>
<div class="main-content-detail main-content-form-edit">
   <?
// donastavení formuláře
   $this->form->urlkey->html()->setAttrib('data-idparent', $this->get('id'));
   
   $this->form->priority->html()->setAttrib('size', 4);
   $this->form->module->htmlSubLabel()->addContent('<div id="module-desc"><span class="desc">'.$this->tr('Popis').':</span><div class="content"></div></div>', true);
   $this->addJsPlugin(new JsPlugin_JQuery());
   echo $this->form;
   ?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         $('select[name=categorymodule]').after('<div id="module-desc"><strong><?=$this->tr('Popis')?>:</strong><div class="content"></div></div>');
         loadDoc();
         $('select[name=categoryparent_cat]').change(function(){
            if($('#categoryurlkey_1_<?=Locales::getDefaultLang()?>').val() !== '' && confirm('<?=$this->tr('Upravit také URL adresu?')?>')){
               $('.categoryurlkey_class').val(null);
            }
         });
         $('select[name=categorymodule]').change(function(){loadDoc();$('input[name=categorygotoSettings]').attr('checked',true);});
         
         $('.button_update_urlkey_for_categoryurlkey').after(
            $('<a></a>')
            .addClass('input-group-btn').addClass('button_update_urlkey_from_name')
            .prop('href', '<?=$this->link()?>#update-urlkey-by-name')
            .prop('title', '<?=$this->tr('Aktualizovat podle jména')?>')
            .html('<span class="icon icon-retweet"></span>')
            .on('click', function(e){
               e.preventDefault();
               // update by name
               var $eUrlKey = $(this).closest('div').find('.categoryurlkey_class');
               $eUrlKey.val($('.categoryname_class[lang="'+$eUrlKey.prop('lang')+'"]').val()).change();
               return false;
            })
         );
         <?
         // EDITACE
         if($this->edit) {?>
         <?} else {
            // PŘIDÁNÍ
            ?>
            $('.categoryname_class').change(function(){
               var $eUrlKey = $('.categoryurlkey_class[lang="'+$(this).prop('lang')+'"]');
               if(!$eUrlKey.data('userchanged')){
                  $('.categoryurlkey_class[lang="'+$(this).prop('lang')+'"]').val($(this).val()).change();
               }
            });
         <?}?>
         
         // pokud url klíž změnil uživatel
         $('.categoryurlkey_class').change(function(){
            $(this).data('userchanged', true);
         })
         .on('beforeCheck', function(event, data){
            var $eName = $('.categoryname_class[lang="'+$(this).prop('lang')+'"]');
            data.name = $eName.val();
            data.idparent = $('select[name="categoryparent_cat"]').val();
            if(data.key === ""){
               data.key = data.name;
            }
         });
            
      });
      
      function loadDoc(){
         var url = '<?=$this->link()->route('moduleDoc')?>';
         url.indexOf("?") >= 0 ? url += '&' : url += '?';
         url += 'module='+$('select[name=categorymodule]').val();
         $('#module-desc .content').load(url+' .moduleLabel');
      }
      /* ]]> */
   </script>
</div>
