<?
$this->addCssFile("style.css");
// do titulku
   if($this->edit) {
      if($this->adminMenu == true){
         $this->addPageTitle($this->_('úprava administrační kategorie').' '.$this->catName);
         echo ('<h1>'.$this->_('úprava administrační kategorie').' "'.$this->catName.'"</h1>');
      } else {
         $this->addPageTitle($this->_('úprava kategorie').' '.$this->catName);
         echo ('<h1>'.$this->_('úprava kategorie').' "'.$this->catName.'"</h1>');
      }
   } else {
      if($this->adminMenu == true){
         $this->addPageTitle($this->_('přidání administrační kategorie'));
         echo ('<h1>'.$this->_('přidání administrační kategorie').'</h1>');
      } else {
         $this->addPageTitle($this->_('přidání kategorie'));
         echo ('<h1>'.$this->_('přidání kategorie').'</h1>');
      }
   }

?>
<div class="main-content-detail main-content-form-edit">
   <?
// donastavení formuláře
   $this->form->priority->html()->setAttrib('size', 4);
   $this->form->module->htmlSubLabel()->addContent('<span style="font-weight:bold;">'.$this->_('Popis').':</span><div id="moduleNameDoc"></div>', true);
   $this->addJsPlugin(new JsPlugin_JQuery());
   echo $this->form;
   ?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){loadDoc();});
      $('#categorymodule').change(function(){loadDoc();});
      function loadDoc(){
         $('#moduleNameDoc').load('<?=$this->link()->route('moduleDoc')?>?module='+$('#categorymodule').val()+' .moduleLabel');
      }
      /* ]]> */
   </script>
</div>
<?=$this->includeTpl('buttonback.phtml', true, array('link' => $this->link()->clear()))?>
