<?
$this->addCssFile("style.css");
$this->addJsPlugin(new JsPlugin_JQuery());

define('SECTION_EDTI_LABEL', $this->_('Upravit'));
define('SECTION_REMOVE_LABEL', $this->_('Smazat'));
define('SECTION_SETTINGS_LABEL', $this->_('Upravit parametry'));
define('SECTION_MOVEUP_LABEL', $this->_('Nahoru'));
define('SECTION_MOVEDOWN_LABEL', $this->_('Dolu'));
define('SECTION_GOTO_CAT_LABEL', $this->_('Přejít na'));
define('SECTION_SHOW_DETAIL_LABEL', $this->_('Zobrazit detail'));
define('SECTION_MODULE_LABEL', $this->_('Modul'));
define('SECTION_LABEL_LABEL', $this->_('Popisek'));
define('SECTION_IND_PANELS_LABEL', $this->_('Individuální panely'));
define('SECTION_YES_LABEL', $this->_('Ano'));
define('SECTION_NO_LABEL', $this->_('Ne'));

// funkce pro render menu
function vveSectionsRenderFunc($menuArr, $link) {
   $link2 = clone $link;
   $link3 = clone $link;
   //   print ("<ul>\n");
   $first = true;
   $count = $menuArr->count();
   $cycle = 0;
   //   $level = $menuArr->getLevel();
   foreach ($menuArr as $key => $item) {$cycle++?>
<tr class="list-item"><td style="padding-left: <?=$item->getLevel()*30?>px;">
      <a href="<?=$link3->clear()->category($item->getCatObj()->getUrlKey())?>" title="<?=$item?>"><span class="sec"><?=$item?></span></a>
      <?
      if($item->getCatObj()->haveFeed()){?>
      <a href="<?=$link3->clear()->category($item->getCatObj()->getUrlKey())->file(Url_Request::URL_FILE_RSS);?>" title="rss feed"><img src="<?=Url_Request::getBaseWebDir()?>images/icons/rss-icon.png" alt="feed icon" height="12" />
      </a>
      <?}
      ?>&nbsp;ID:<?=$item->getId()?>
      <a href="<?=$link?>" class="button-show-detail" title="<?=SECTION_SHOW_DETAIL_LABEL?>">dateil</a>
      <div class="category-params">
         <table>
            <tr>
               <th><?=SECTION_MODULE_LABEL?>:</th>
               <td><?=$item->getCatObj()->getModule()->getName()?></td>
            </tr>
            <tr>
               <th><?=SECTION_IND_PANELS_LABEL?>:</th>
               <td><?
               echo $item->getCatObj()->isIndividualPanels() == true ? SECTION_YES_LABEL : SECTION_NO_LABEL;
                  ?></td>
            </tr>
         </table>
      </div>
   </td><td width="110">
      <form method="post" action="<?=$link2->route('settings',array('categoryid' => $item->getId()))?>" style="display:inline;">
         <input type="image" src="<?=vve_get_tpl_file('icons/cog_edit.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="category_settings" title="<?=SECTION_SETTINGS_LABEL?>" />
      </form>
      <form method="post" action="<?=$link2->route('edit',array('categoryid' => $item->getId()))?>" style="display:inline;">
         <input type="image" src="<?=vve_get_tpl_file('icons/application_edit.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="category_edit" title="<?=SECTION_EDTI_LABEL?>" />
      </form>
      <form method="post" action="<?=$link?>" style="display:inline;" onsubmit="return submitRemoveCat('<?=$item;?>')">
         <input type="hidden" value="<?=$item->getId()?>" name="category_id" />
         <input type="image" src="<?=vve_get_tpl_file('icons/application_delete.png', VVE_TPL_FILE_IMAGE)?>"
                value="remove" name="category_remove" title="<?=SECTION_REMOVE_LABEL?>" />
      </form>
            <?if(!$first) {?>
      <form method="post" action="<?=$link?>" style="display:inline;">
         <input type="hidden" value="<?=$item->getId()?>" name="item_id" />
         <input type="hidden" value="up" name="item_move_to" />
         <input type="image" src="<?=vve_get_tpl_file('icons/go-up.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="item_move" title="<?=SECTION_MOVEUP_LABEL?>" />
      </form>
            <?}
            if($cycle < $count) {?>
      <form method="post" action="<?=$link?>" style="display:inline;">
         <input type="hidden" value="<?=$item->getId()?>" name="item_id" />
         <input type="hidden" value="down" name="item_move_to" />
         <input type="image" src="<?=vve_get_tpl_file('icons/go-down.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="item_move" title="<?=SECTION_MOVEDOWN_LABEL?>" />
      </form>
            <?}?>
   </td>
</tr>
      <?
      if(!$item->isEmpty()) {
         vveSectionsRenderFunc($item, $link);
      }
      $first = false;
   }
}
?>
<h1><?=$this->_("Struktura stránek")?></h1>
<div class="main-content-detail">
   <?//sekce
   $typeClass = 'mainStruct';
   if($this->adminStructure == true) {$typeClass = 'adminStruct';}
   ?>
   <div id="sections" class="<?=$typeClass?>">
      <table style="width: 98%">
         <?if($this->structure != null){
            echo vveSectionsRenderFunc($this->structure, $this->link());
         }?>
      </table>
   </div>
   <br />
   <?$this->includeTpl('structtype.phtml');?><br />
   <br />
   <script type="text/javascript">
      /* <![CDATA[ */
      function submitRemoveCat(msg){
         return confirm('<?=$this->_('Opravdu smazat kategorii: ')?>'+msg+'?');
      }

      $('.button-show-detail').click(function(){
         $(this).next('div').toggle();
         return false;
      });
      /* ]]> */
   </script>
   <?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('add_category', $this->_("Přidat kategorii"),
          $this->link()->route('add'),
          $this->_("Přidat novou kategorii"), "application_add.png");
      $this->includeTplObj($toolbox);
   }
   ?>
</div>

