<?
$model = new Model_Category();
$cats = $model->getCategoryList();
$catArr = array();
foreach ($cats as $item) {
   $catArr[$item[Model_Category::COLUMN_CAT_ID]] = $item;
}

$menu = unserialize(VVE_CATEGORIES_STRUCTURE);

define('SECTION_EDTI_LABEL', $this->_('Upravit'));
define('SECTION_REMOVE_LABEL', $this->_('Smazat'));
define('SECTION_MOVEUP_LABEL', $this->_('Nahoru'));
define('SECTION_MOVEDOWN_LABEL', $this->_('Dolu'));

// funkce pro render menu
function vveSectionsRenderFunc($menuArr, $link, $cats, $catLabel) {
   $link2 = clone $link;
   //   print ("<ul>\n");
   $first = true;
   $count = $menuArr->count();
   $cycle = 0;
   $level = $menuArr->getLevel();
   foreach ($menuArr as $key => $item) {
      $cycle++;
      if($item instanceof Menu_Sections) {?>
<tr><td>
      <span class="sec"><?=str_repeat('&nbsp;', ($level)*6).$item->getLabel()?></span>
   </td><td>
      <form method="post" action="<?=$link2->route('editSec',array('secid' => $item->getId()))?>" style="display:inline;">
         <input type="image" src="<?=vve_get_tpl_file('toolbox/text_edit.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="section_edit" title="<?=SECTION_EDTI_LABEL?>" />
      </form>
      <form method="post" action="<?=$link?>" style="display:inline;" onsubmit="return submitRemoveSec('<?=$item->getLabel();?>')">
         <input type="hidden" value="<?=$item->getId()?>" name="section_id" />
         <input type="hidden" value="" name="section_cat_id" />
         <input type="image" src="<?=vve_get_tpl_file('toolbox/remove.png', VVE_TPL_FILE_IMAGE)?>"
                value="remove" name="section_remove" title="<?=SECTION_REMOVE_LABEL?>" />
      </form>
               <?if(!$first) {?>
      <form method="post" action="<?=$link?>" style="display:inline;">
         <input type="hidden" value="<?=$key?>" name="item_child_key" />
         <input type="hidden" value="<?=$menuArr->getId()?>" name="item_parent_id" />
         <input type="hidden" value="up" name="item_move_to" />
         <input type="image" src="<?=vve_get_tpl_file('toolbox/go-up.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="item_move" title="<?=SECTION_MOVEUP_LABEL?>" />
      </form>
               <?}
               if($cycle < $count) {?>
      <form method="post" action="<?=$link?>" style="display:inline;">
         <input type="hidden" value="<?=$key?>" name="item_child_key" />
         <input type="hidden" value="<?=$menuArr->getId()?>" name="item_parent_id" />
         <input type="hidden" value="down" name="item_move_to" />
         <input type="image" src="<?=vve_get_tpl_file('toolbox/go-down.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="item_move" title="<?=SECTION_MOVEDOWN_LABEL?>" />
      </form>
               <?}?>
   </td></tr>
         <?vveSectionsRenderFunc($item, $link, $cats, $catLabel);
      } else {?>
   <tr><td>
               <?if(isset($cats[$item])) {
                  print (str_repeat('&nbsp;', ($level)*6).$catLabel." id: ".$item." - ".$cats[$item][Model_Category::COLUMN_CAT_LABEL]);
               } else {
                  print (str_repeat('&nbsp;', ($level)*6).$catLabel." id: ".$item." - NOT EXIST");
               }?>
   </td><td>
      <form method="post" action="<?=$link?>" style="display:inline;" onsubmit="return submitRemoveCat('<?=$item?>')">
         <input type="hidden" value="<?=$menuArr->getId();?>" name="section_id" />
         <input type="hidden" value="<?=$key?>" name="section_cat_id" />
         <input type="image" src="<?=vve_get_tpl_file('toolbox/remove.png', VVE_TPL_FILE_IMAGE)?>" value="remove" name="section_remove" />
      </form>
               <?if(!$first) {?>
      <form method="post" action="<?=$link?>" style="display:inline;">
         <input type="hidden" value="<?=$key?>" name="item_child_key" />
         <input type="hidden" value="<?=$menuArr->getId()?>" name="item_parent_id" />
         <input type="hidden" value="up" name="item_move_to" />
         <input type="image" src="<?=vve_get_tpl_file('toolbox/go-up.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="item_move" title="<?=SECTION_MOVEUP_LABEL?>" />
      </form>
               <?}
               if($cycle < $count) {?>
      <form method="post" action="<?=$link?>" style="display:inline;">
         <input type="hidden" value="<?=$key?>" name="item_child_key" />
         <input type="hidden" value="<?=$menuArr->getId()?>" name="item_parent_id" />
         <input type="hidden" value="down" name="item_move_to" />
         <input type="image" src="<?=vve_get_tpl_file('toolbox/go-down.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="item_move" title="<?=SECTION_MOVEDOWN_LABEL?>" />
      </form>
               <?}?>
   </td></tr>
      <?}
      //      print ("</li>\n");
      $first = false;
   }
//   print ("</ul>\n");
}
?>
<div>
   <?//sekce?>
   <h2><?=$this->_("Sekce")?></h2>
   <div id="sections">
      <table>
      <?=vveSectionsRenderFunc($menu, $this->link(), $catArr, $this->_('Kategorie'))?>
      </table>
   </div>
   <br />
   <br />
   <?//kategorie?>
   <h2><?=$this->_("Kategorie")?></h2>
   <table>
      <tr>
         <th width="30"><?=$this->_('Id')?></th>
         <th><?=$this->_('Název')?></th>
         <th><?=$this->_('Url adresa')?></th>
         <th><?=$this->_('Detail')?></th>
      </tr>
      <?//while ($row = $cats->fetch()) {
      foreach ($cats as $row) { ?>
      <tr>
         <td><?=$row[Model_Category::COLUMN_CAT_ID]?></td>
         <td><?=$row[Model_Category::COLUMN_CAT_LABEL]?></td>
         <td><a href="<?=$this->link()->clear()->category($row[Model_Category::COLUMN_URLKEY]);?>"
                title="<?=$row[Model_Category::COLUMN_CAT_LABEL]?>"><?=$this->link()->clear()->category($row[Model_Category::COLUMN_URLKEY]);?></a></td>
         <td>
            <a href="<?=$this->link()->route('detail',array('categoryid' => $row[Model_Category::COLUMN_CAT_ID]))?>"
               title="<?=$this->_('detail kategorie').' '.$row[Model_Category::COLUMN_CAT_LABEL]?>"><?=$this->_('detail')?></a>
         </td>
      </tr>
      <?}?>
   </table>
   <script type="text/javascript">
      function submitRemoveCat(msg){
         if(confirm('<?=$this->_('Opravdu smazat kategorii s id:')?>'+msg+'?')){
            return true;
         }
         return false;
      }
      function submitRemoveSec(msg){
         return (confirm('<?=$this->_('Opravdu smazat sekci ')?>'+msg+'?'));
      }
   </script>

   <?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('add_category', $this->_("Přidat kategorii"),
          $this->link()->route('add'),
          $this->_("Přidat novou kategorii"), "text_add.png");
      $toolbox->addTool('add_section', $this->_("Přidat sekci"),
          $this->link()->route('addSection'),
          $this->_("Přidat novou sekci"), "text_add.png");
      $toolbox->addTool('connect_section_cat', $this->_("Provázat kategorii"),
          $this->link()->route('connectCat'),
          $this->_("provázat kategorií se sekcí"), "connect.png");
      $this->includeTplObj($toolbox);
   }
   ?>
</div>

