<?
$this->addCssFile("style.css");
$this->addJsPlugin(new JsPlugin_JQuery());
$this->addJsPlugin(new JsPlugin_JQueryCSS());
$this->addJsPlugin(new JsPlugin_TreeTable());

define('SECTION_EDTI_LABEL', $this->tr('Upravit'));
define('SECTION_REMOVE_LABEL', $this->tr('Smazat'));
define('SECTION_SETTINGS_LABEL', $this->tr('Upravit parametry'));
define('SECTION_MOVEUP_LABEL', $this->tr('Nahoru'));
define('SECTION_MOVEDOWN_LABEL', $this->tr('Dolu'));
define('SECTION_GOTO_CAT_LABEL', $this->tr('Přejít'));
define('SECTION_SHOW_DETAIL_LABEL', $this->tr('Zobrazit detail'));
define('SECTION_MODULE_LABEL', $this->tr('Modul'));
define('SECTION_LABEL_LABEL', $this->tr('Popisek'));
define('SECTION_IND_PANELS_LABEL', $this->tr('Individuální panely'));
define('SECTION_YES_LABEL', $this->tr('Ano'));
define('SECTION_NO_LABEL', $this->tr('Ne'));
define('SECTION_MODULE_DATADIR', $this->tr('Datový adresář'));
define('SECTION_RIGHTS', $this->tr('Výchozí práva'));
define('SECTION_TITLE', $this->tr('Popis'));
define('SECTION_DESC', $this->tr('Popis vyhledávače'));
define('SECTION_VISIBILITY', $this->tr('Viditelné'));
define('SECTION_VISIBILITY_ALL', $this->tr('Všem'));
define('SECTION_VISIBILITY_HIDDEN', $this->tr('Nikomu'));
define('SECTION_VISIBILITY_WHEN_LOG', $this->tr('Pouze přihlášeným'));
define('SECTION_VISIBILITY_WHEN_NOT_LOG', $this->tr('Pouze nepřihlášeným'));
define('SECTION_VISIBILITY_WHEN_ADMIN', $this->tr('Pouze administrátorům'));

// funkce pro render menu
function vveSectionsRenderFunc($menuArr, $link) {
   $link2 = clone $link;
   $link3 = clone $link;
   //   print ("<ul>\n");
   $first = true;
   $count = $menuArr->count();
   $cycle = 0;
   //   $level = $menuArr->getLevel();
   foreach ($menuArr as $key => $item) {
      $cycle++;
      $class = null;
      if($item->getParentId() != 0){// pokud není kořen
         $class = 'child-of-node-'.$item->getParentId();
      }
      ?><tr id="node-<?=$item->getId();?>" class="ui-widget-header list-item <?=$class;?>">
         <td class="cat-first-coll">
      <span class="sec"><?=$item?></span>
      <?
      echo langsImages($item->getCatObj()->getCatDataObj()->{Model_Category::COLUMN_URLKEY});
      if($item->getCatObj()->haveFeed()){?>
      <a href="<?=$link3->clear()->category($item->getCatObj()->getUrlKey())->file(Url_Request::URL_FILE_RSS);?>" title="rss feed"><img src="<?=Url_Request::getBaseWebDir()?>images/icons/rss-icon.png" alt="feed icon" height="12" /></a>
      <?}
      ?>&nbsp;ID:<?=$item->getId()?>
      <a href="" class="button-show-detail" title="<?=SECTION_SHOW_DETAIL_LABEL?>">detail</a>&nbsp;
      <a href="<?=$link3->clear()->lang()->category($item->getCatObj()->getUrlKey())?>" title="<?=SECTION_GOTO_CAT_LABEL?>"><?=SECTION_GOTO_CAT_LABEL?></a>

      <div class="category-params">
         <table>
            <tr>
               <th><?=SECTION_MODULE_LABEL?>:</th>
               <td><?=$item->getCatObj()->getModule()->getName()?></td>
            </tr>
            <tr>
               <th><?=SECTION_IND_PANELS_LABEL?>:</th>
               <td><?
               echo $item->getCatObj()->isIndividualPanels() == true ? SECTION_YES_LABEL : SECTION_NO_LABEL;
                  ?></td>
            </tr>
            <tr>
               <th><?=SECTION_VISIBILITY?>:</th>
               <td><?
               switch ($item->getCatObj()->getCatDataObj()->{Model_Category::COLUMN_VISIBILITY}) {
                  case Model_Category::VISIBILITY_HIDDEN:
                     echo SECTION_VISIBILITY_HIDDEN;
                     break;
                  case Model_Category::VISIBILITY_WHEN_ADMIN:
                     echo SECTION_VISIBILITY_WHEN_ADMIN;
                     break;
                  case Model_Category::VISIBILITY_WHEN_LOGIN:
                     echo SECTION_VISIBILITY_WHEN_LOG;
                     break;
                  case Model_Category::VISIBILITY_WHEN_NOT_LOGIN:
                     echo SECTION_VISIBILITY_WHEN_NOT_LOG;
                     break;
                  case Model_Category::VISIBILITY_ALL:
                  default:
                     echo SECTION_VISIBILITY_ALL;
                     break;
               }
                  ?></td>
            </tr>
            <tr>
               <th><?=SECTION_MODULE_DATADIR?>:</th>
               <td><?=$item->getCatObj()->getModule()->getDataDir(true)?></td>
            </tr>
            <tr>
               <th><?=SECTION_RIGHTS?>:</th>
               <td><?=$item->getCatObj()->getCatDataObj()->{Model_Category::COLUMN_DEF_RIGHT};?></td>
            </tr>
            <tr>
               <th><?=SECTION_TITLE?>:</th>
               <td><?=$item->getCatObj()->getCatDataObj()->{Model_Category::COLUMN_CAT_ALT};?></td>
            </tr>
            <tr>
               <th><?=SECTION_DESC?>:</th>
               <td><?=$item->getCatObj()->getCatDataObj()->{Model_Category::COLUMN_DESCRIPTION};?></td>
            </tr>
            <tr>
               <th>Url:</th>
               <td><?
                  foreach ($item->getCatObj()->getCatDataObj()->{Model_Category::COLUMN_URLKEY} as $lang => $urlkey){
                     if($urlkey == null) continue;
                     if($lang != Locales::getDefaultLang()) $link3->lang($lang); // default language needn't have definition in URL
                     $l = (string)$link3->clear()->category($urlkey);
                     echo '<a href="'.$l.'" title="'.SECTION_GOTO_CAT_LABEL.'">';
                     echo '<img src="images/langs/small/'.$lang.'.png" alt="'.$lang.'" class="lang-image" />&nbsp;';
                     echo $l;
                     echo '</a>';
                     echo '<br />';
                  }
               ?></td>
            </tr>
         </table>
      </div>
         </td><td width="110" valign="top">
      <form method="post" action="<?=$link2->route('settings',array('categoryid' => $item->getId()))?>" style="display:inline;">
         <input type="image" src="<?=vve_get_tpl_file('icons/cog_edit.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="category_settings" title="<?=SECTION_SETTINGS_LABEL?>" />
      </form>
      <form method="post" action="<?=$link2->route('edit',array('categoryid' => $item->getId()))?>" style="display:inline;">
         <input type="image" src="<?=vve_get_tpl_file('icons/application_edit.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="category_edit" title="<?=SECTION_EDTI_LABEL?>" />
      </form>
      <form method="post" action="<?=$link?>" style="display:inline;" onsubmit="return submitRemoveCat('<?=$item;?>')">
         <input type="hidden" value="<?=$item->getId()?>" name="category_id" />
         <input type="image" src="<?=vve_get_tpl_file('icons/application_delete.png', VVE_TPL_FILE_IMAGE)?>"
                value="remove" name="category_remove" title="<?=SECTION_REMOVE_LABEL?>" />
      </form>
            <?if(!$first) {?>
      <form method="post" action="<?=$link?>" style="display:inline;">
         <input type="hidden" value="<?=$item->getId()?>" name="item_id" />
         <input type="hidden" value="up" name="item_move_to" />
         <input type="image" src="<?=vve_get_tpl_file('icons/go-up.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="item_move" title="<?=SECTION_MOVEUP_LABEL?>" />
      </form>
            <?}
            if($cycle < $count) {?>
      <form method="post" action="<?=$link?>" style="display:inline;">
         <input type="hidden" value="<?=$item->getId()?>" name="item_id" />
         <input type="hidden" value="down" name="item_move_to" />
         <input type="image" src="<?=vve_get_tpl_file('icons/go-down.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="item_move" title="<?=SECTION_MOVEDOWN_LABEL?>" />
      </form>
            <?}?>
   </td>
</tr>
      <?
      if(!$item->isEmpty()) {
         vveSectionsRenderFunc($item, $link);
      }
      $first = false;
   }
}

echo $this->toolbox;
?>
<h1><?=$this->tr("Struktura stránek")?></h1>
<?=$this->includeTpl('navigation.phtml');?>
<div class="main-content-detail">
   <p><?=$this->tr('Ve struktuře jsou zobrazeny také zkryté položky.');?></p>
   <?//sekce
   $typeClass = 'mainStruct';
   $id = 'categories-table';
   if($this->isMainMenu != true) {
      $id = 'admin-categories-table';
      $typeClass = 'adminStruct';
      echo '<p><strong>'.$this->tr("Pozor úprava administračního menu může ovlivnit chování celých stránek!").'</strong></p>';
   }
   ?>
   <hr />
   <div id="sections" class="<?=$typeClass?>">
      <table id="<?=$id?>" style="width: 98%">
         <?if($this->structure != null){
            echo vveSectionsRenderFunc($this->structure, $this->link());
         }?>
      </table>
   </div>
   <br />
   <br />
   <?
   ?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $('#<?=$id?>').treeTable({
         clickableNodeNames : true,
         indent: 15
      });

      function submitRemoveCat(msg){
         return confirm('<?=$this->tr('Opravdu smazat kategorii: ')?>'+msg+'?');
      }

      $('a.button-show-detail').click(function(){
         var $div = $(this).parent('td').children('div.category-params');
         $div.toggle();
         if($div.is(':hidden')){
            $(this).parent('td').parent('tr').removeClass('ui-widget-content');
         } else {
            $(this).parent('td').parent('tr').addClass('ui-widget-content');
         }
//         $(this).parent('td').children('div.category-params').toggle(function(){
//         }, function(){
//            alert('hide');
//         });
         return false;
      });
      /* ]]> */
   </script>
</div>

