<?
$this->addPageTitle($this->_('úprava parametrů kategorie').' '.$this->catName);
?>
<h1><?=$this->_('Úprava parametrů kategorie').' "'.$this->catName.'"'?></h1>
<?
if($this->includeTpl != null){
   $this->includeTplObj($this->includeTpl);
} else if($this->form == null) {
   print ($this->_('Kategorie nemá žádné nastavení'));
} else {
   print ($this->form);
}

$this->includeTpl('buttonback.phtml', true, array('link' => $this->link()->clear()));

?>