<?
// funkce pro render menu
function vveMenuRenderFunc($menuArr, $link) {
   print ("<ul>\n");
   foreach ($menuArr as $key => $item) {
      print ("<li>");
      print ('<a href="'.$link->clear()->category($item->getCatObj()->{Model_Category::COLUMN_URLKEY}).'">'
             .$item->getCatObj()->{Model_Category::COLUMN_CAT_LABEL}.'</a>'."");
      if(!$item->isEmpty()){
         vveMenuRenderFunc($item, $link);
      }
      print ("</li>\n");
   }
   print ("</ul>\n");
}
?>

<!-- Halvni menu sekce v menu  -->
<div id="smoothmenu1" class="ddsmoothmenu">
   <?=vveMenuRenderFunc($this->menu, $this->link())?>
   <br style="clear: left" />
</div>
