<?
// funkce pro render menu
function vveMenuRenderFunc($menuArr, $link) {
   print ("<ul>\n");
   foreach ($menuArr as $key => $item) {
      print ("<li>");
      if($item instanceof Menu_Sections) {
         print ('<a href="#" title="'.$item->getLabel().'">'.$item->getLabel()."</a>\n");
         vveMenuRenderFunc($item, $link);
      } else {
         print ('<a href="'.$link->clear()->category($item[Model_Category::COLUMN_URLKEY]).'">'
             .$item[Model_Category::COLUMN_CAT_LABEL].'</a>'."");
      }
      print ("</li>\n");
   }
   print ("</ul>\n");
}
?>

<!-- Halvni menu sekce v menu  -->
<div id="smoothmenu1" class="ddsmoothmenu">
   <?=vveMenuRenderFunc($this->menu, $this->link())?>
   <br style="clear: left" />
</div>
