<h1>
   <a href="<?=$this->l()->clear();?>"><?=strtolower(Category::getMainCategory()->getLabel())?></a>
   <span>
      <?//if($this->catTitle())
        // echo ' &raquo; '.$this->catTitle();
//      if($this->articleName())
//         echo ' &raquo; '.$this->articleName();
//      if($this->actionName())
//         echo ' &raquo; '.$this->actionName();?>
   </span>
</h1>
<?// foreach ($this->modules as $module) {?>
<div>
      <?
      $this->includeTplObj($this->module);?>
</div>
<?//}?>
