<h1>
   <a href="<?=$this->l()->clear()->category(Category::getLabel(), Category::getId())?>"><?=strtolower(Category::getLabel())?></a>
   <span>
      <?//if($this->catTitle())
        // echo ' &raquo; '.$this->catTitle();
      if($this->articleName())
         echo ' &raquo; '.$this->articleName();
      if($this->actionName())
         echo ' &raquo; '.$this->actionName();?>
   </span>
</h1>
<? foreach ($this->modules as $module) {?>
<div>
      <? $module->includeTplObj($module);?>
</div>
<?}?>
