<div id="editContactForm" class="content">
   <ul class="langMenu">
      <? foreach ($this->pVar("appLangsNames") as $key => $lang) {?>
      <li>
         <a href="#contactLang<?=$key?>" class="selectedd">
            <img src="images/lang/<?=$key?>.png" alt="<?=$lang?>" />
               <?=$lang?>
         </a>
      </li>
      <?}?>
   </ul>

   <div class="tabsContent">
      <form method="post" action="<?=$this->l();?>" enctype="multipart/form-data">
         <? foreach ($this->pVar("appLangsNames") as $key => $lang) {?>
         <p id="contactLang<?=$key?>" class="tabcontent">
               <?=$this->_("Název kontaktu");?>*:<br />
            <input type="text" size="40" maxlength="50" name="contact_name[<?=$key?>]"
                   value="<?=$this->post("contact_name[$key]", $this->contact['name'][$key]);?>" /><br />
               <?=$this->_("Text kontaktu (adresa, telefon, ...)");?>*:<br />
            <textarea class="textarea_tinymce textarea" rows="25" cols="70"
                      name="contact_text[<?=$key;?>]"><?=$this->post("contact_text[$key]", $this->contact['text'][$key]);?></textarea>
         </p>
         <br />
            <?=$this->_("Obrázek kontaktu")." \"".$this->contact[Contacts_Model_Detail::COLUMN_CONTACT_FILE]?>":<br />
         <input name="contact_file" type="file" value="" /><br />
         <br />
         <?=$this->_("Priorita (celé číslo od 0 do 100, čím větší, tím bude kontakt výše)")?>:
         <input name="contact_priority" type="text" size="3" maxlength="4"
                value="<?=$this->post("contact_priority", $this->contact['priority']);?>"/>
         <br />
         <br />
            <?=$this->_("GPS pozice na Google Maps")?>:<br />
            <?=$this->_("Souřadnicce X")?>:
         <input name="contact_position_x" type="text" size="10" maxlength="10" 
                value="<?=$this->post("contact_position_x", $this->contact['position_x']);?>"/>
            <?=$this->_("Souřadnicce Y")?>:
         <input name="contact_position_y" type="text" size="10" maxlength="10" 
                value="<?=$this->post("contact_position_y", $this->contact['position_y']);?>"/>
         <br />
         <br />
            <?=$this->_("Typ kontaktu")?>:
         <select name="contact_id_type">
            <?foreach ($this->contactTypes as $contType) {?>
            <?if($this->post("contact_id_type", $this->contact['id_type']) == $contType['id_type']) {?>
            <option value="<?=$contType[Contacts_Model_Types::COLUMN_ID]?>" selected="sellected">
               <?=$contType[Contacts_Model_Types::COLUMN_NAME]?>
            </option>
               <?} else {?>
            <option value="<?=$contType[Contacts_Model_Types::COLUMN_ID]?>">
               <?=$contType[Contacts_Model_Types::COLUMN_NAME]?>
            </option>
            <?}?>
            <?}?>
         </select>
         <br />
         <?}?>
         <br />
         <input name="contact_reset" type="reset" value="<?=$this->_m("Obnovit")?>" />
         <input name="contact_send" type="submit" value="<?=$this->_m("Odeslat")?>" />
         <?if($this->edit) {?>
         <input name="contact_id" type="hidden" value="<?=$this->contact['id_contact']?>" />
         <?}?>

      </form>

   </div>
   <?$this->includeTpl("buttonback.phtml", true, array('link' => $this->l()->action()->article()));?>
   <script type="text/javascript">
      $(document).ready(function(){
         $("#editContactForm").tabs();
      });
   </script>
</div>
