<?
$this->addCssFile("style.css");
// do titulku
if($this->project != false) {
   $h = sprintf($this->tr('Úprava projektu "%s"'), $this->project->{Projects_Model_Projects::COLUMN_NAME});
   // donastavení formuláře
   if(isset($this->form->delimg)){
      $img = sprintf($this->tr('Titulní:').' <img src="%s" height="50" alt="%s" /> ', 
         $this->dataDir.$this->project->{Projects_Model_Projects::COLUMN_IMAGE}, $this->tr('Titulní obrázek'));
      $imgThumb = sprintf($this->tr('Miniatura:').' <img src="%s" height="50" alt="%s" /> ', 
         $this->dataDir.$this->project->{Projects_Model_Projects::COLUMN_THUMB}, $this->tr('Titulní obrázek - miniatura'));
      $this->form->delimg->setSubLabel($img.$imgThumb);
   }
   
} else {
   $h = $this->tr('Přidání projektu');
}
$this->addPageTitle($h);


?>
<h1><?=$h;?></h1>
<div class="main-content-form-edit" id="edit-form-project">
   <?echo($this->form);?>
   <script type="text/javascript">
      // generate url address
      $('input[name="edit_projectname"]').change(function(){
         var $url = $('input[name="edit_projecturl"]');
         $url.val(str2url($(this).val()));
      });
   </script>
</div>
