<?php 
$this->addFile("css://projects:style.less");
// do titulku
if($this->project != false) {
   $h = sprintf($this->tr('Úprava projektu "%s"'), $this->project->{Projects_Model_Projects::COLUMN_NAME});
   // donastavení formuláře
   $imagetag = '<img src="%s" height="50" alt="%s" /> ';
   if(isset($this->form->delimgtitle)){
      $img = sprintf($imagetag, 
         $this->dataDir.$this->project->{Projects_Model_Projects::COLUMN_IMAGE}, $this->tr('Titulní obrázek'));
      $this->form->delimgtitle->setSubLabel($img);
   }
   if(isset($this->form->delimgthumb)){
      $imgThumb = sprintf($imagetag, 
         $this->dataDir.$this->project->{Projects_Model_Projects::COLUMN_THUMB}, $this->tr('Titulní obrázek - miniatura'));
      $this->form->delimgthumb->setSubLabel($imgThumb);
   }
   
} else {
   $h = $this->tr('Přidání projektu');
}
$this->addPageTitle($h);


?>
<h1><?php echo $h;?></h1>
<div class="main-content-form-edit" id="edit-form-project">
   <?php echo($this->form);?>
</div>
