<?php 
// do titulku
$h = $this->tr('úprava pořadí projektů');
$this->addPageTitle($h);

$jq = new JsPlugin_JQuery();
$jq->addUISortable();
$this->addJsPlugin($jq);
$this->addFile('css://projects:style.less');
?>
<h1><?php ps($h)?></h1>
<div class="content-form-edit">
   <?php  echo $this->form->renderStart(); ?>
      <div class="cubecms-widget cubecms-widget-sorting">      
         <ul id="projects-sort-list" class="cubecms-widget cubecms-list">
            <?php 
            foreach ($this->projects as $pr) {?>
               <li class="cubecms-list-row cubecms-list-row-movable "><span class="icon icon-arrows-v icon-fw"></span><?php 
               echo $pr->{Projects_Model_Projects::COLUMN_NAME};
               $this->form->id->setValues($pr->getPK());
               echo $this->form->id;
               ?></li>
            <?php }?>
         </ul>
         <div class="cubecms-widget-footer">
            <div class="cubecms-widget-note"><?php ps($this->tr('Pro změnu pořadí stačí uchopit a přesunout.'))?></div>
            <div class="cubecms-widget-buttons">
               <?php echo $this->form->save->controllAll()?>
            </div>
         </div>
      </div>
   <?php  echo $this->form->renderEnd(); ?>
   <script>
	$(function() {
		$( "#projects-sort-list" ).sortable({
			placeholder: "ui-state-highlight",
         cursor: 'move'
		});
		$( "#projects-sort-list" ).disableSelection();
	});
	</script>
</div>
