<?
/**
 * Variables
 * $this->project - objekt projektu
 * $this->dataDir - adresář k obrázkům
 * $this->toolbox - nástroje k projektu
 * $this->toolboxImages - nástroje k obrázkům
 * $this->projectsRelated - relevantní projekty
 */

$h = $this->project->{Projects_Model_Projects::COLUMN_NAME};
$this->addPageTitle($h);
echo $this->toolbox;
?>

<h1><?$this->includeFile('tpl://engine:headline/icon.phtml'); echo htmlspecialchars($h);?></h1>
<div class="main-content-detail">
   <div class="main-content-text">
      <?if($this->project->{Projects_Model_Projects::COLUMN_THUMB} != null){?>
      <div class="main-content-image">
         <img src="<?=$this->dataDir.$this->project->{Projects_Model_Projects::COLUMN_THUMB}?>" />
      </div>
      <?}?>
      <?=$this->filter((string)$this->project->{Projects_Model_Projects::COLUMN_TEXT}, array('emoticons'));?>
      <?if($this->project->{Projects_Model_Projects::COLUMN_IMAGE} != null){?>
      <div class="main-content-image">
         <img src="<?=$this->dataDir.$this->project->{Projects_Model_Projects::COLUMN_IMAGE}?>" />
      </div>
      <?}?>
   </div>
   <hr class="reseter" />
   <?if(count($this->images > 0)){?>
   <h2><?=$this->tr('Náhledy')?></h2>
   <?}?>
   <? // images gallery
   $this->imagesBaseDir = $this->dataDir;
   $this->includeFile('tpl://engine:photogalery.phtml');
   ?>
   
   <?if($this->projectsRelated != null){?>
   <h2><?=$this->tr('Související projekty')?></h2>
   <div class="main-content-text">
      <ul>
         <?foreach ($this->projectsRelated as $project) {
         $link = $this->link()->route('project', array('prkey' => $project->{Projects_Model_Projects::COLUMN_URLKEY},
                                                               'seckey' => $project->{Projects_Model_Sections::COLUMN_URLKEY}));   
         ?>
         <li><a href="<?=$link?>" title="<?=$project->{Projects_Model_Projects::COLUMN_NAME}?>"><?=$project->{Projects_Model_Projects::COLUMN_NAME}?></a></li>            
         <?}?>
      </ul>
   </div>
   <?}?>
<!-- relevantní projekty-->
   <hr class="reseter" />
   <?$this->includeTpl('articletools.phtml', true, array('shares' => array('url' => $this->link(), 'title' => $h)));?>
</div>


