<?php 
/**
 * Variables
 * $this->project - objekt projektu
 * $this->dataDir - adresář k obrázkům
 * $this->toolbox - nástroje k projektu
 * $this->toolboxImages - nástroje k obrázkům
 * $this->projectsRelated - relevantní projekty
 */

$h = $this->project->{Projects_Model_Projects::COLUMN_NAME};
$this->addPageTitle($h);
echo $this->toolbox;
?>

<h1><?php $this->includeFile('tpl://engine:headline/icon.phtml'); echo htmlspecialchars($h);?></h1>
<div class="main-content-detail">
   <div class="main-content-text">
      <?php if($this->project->{Projects_Model_Projects::COLUMN_THUMB} != null){?>
      <div class="main-content-image">
         <img src="<?php echo $this->dataDir.$this->project->{Projects_Model_Projects::COLUMN_THUMB}?>" />
      </div>
      <?php }?>
      <?php echo $this->filter((string)$this->project->{Projects_Model_Projects::COLUMN_TEXT}, array('emoticons'));?>
      <?php if($this->project->{Projects_Model_Projects::COLUMN_IMAGE} != null){?>
      <div class="main-content-image">
         <img src="<?php echo $this->dataDir.$this->project->{Projects_Model_Projects::COLUMN_IMAGE}?>" />
      </div>
      <?php }?>
   </div>
   <hr class="reseter" />
   <?php if(count($this->images > 0)){?>
   <h2><?php echo $this->tr('Náhledy')?></h2>
   <?php }?>
   <?php  // images gallery
   $this->imagesBaseDir = $this->dataDir;
   $this->includeFile('tpl://engine:photogalery.phtml');
   ?>
   
   <?php if($this->projectsRelated != null){?>
   <h2><?php echo $this->tr('Související projekty')?></h2>
   <div class="main-content-text">
      <ul>
         <?php foreach ($this->projectsRelated as $project) {
         $link = $this->link()->route('project', array('prkey' => $project->{Projects_Model_Projects::COLUMN_URLKEY},
                                                               'seckey' => $project->{Projects_Model_Sections::COLUMN_URLKEY}));   
         ?>
         <li><a href="<?php echo $link?>" title="<?php echo $project->{Projects_Model_Projects::COLUMN_NAME}?>"><?php echo $project->{Projects_Model_Projects::COLUMN_NAME}?></a></li>            
         <?php }?>
      </ul>
   </div>
   <?php }?>
<!-- relevantní projekty-->
   <hr class="reseter" />
   <?php $this->includeTpl('articletools.phtml', true, array('shares' => array('url' => $this->link(), 'title' => $h)));?>
</div>


