<?php 
$h = $this->category()->getName();
$this->addFile("css://style.less");
echo $this->toolbox;
?>
<h1><?php $this->includeFile('tpl://engine:headline/icon.phtml'); echo $h;?></h1>
<div class="main-content">
   <?php if(!empty ($this->sections)) {
      foreach ($this->sections as $section) {
         $link = $this->link()->route('section', array('seckey' => $section->{Projects_Model_Sections::COLUMN_URLKEY}));
/*         <h2><a href="<?php echo $link?>" title="<?php echo $section->data->{Projects_Model_Sections::COLUMN_NAME}?>"><?php echo $section->data->{Projects_Model_Sections::COLUMN_NAME}?></a></h2>*/
         ?>
         <div class="main-content-text">
         <h2><?php echo $section->{Projects_Model_Sections::COLUMN_NAME}?></h2>
         <p><?php echo $section->{Projects_Model_Sections::COLUMN_TEXT}?></p>
         <?php  // projekty
         if(!empty ($section->projects)){
         ?>
         <p>
         <ul>
            <?php foreach ($section->projects as $project){
               $prlink = $this->link()->route('project', array('prkey' => $project->{Projects_Model_Projects::COLUMN_URLKEY},
                                                               'seckey' => $project->{Projects_Model_Sections::COLUMN_URLKEY}));
               ?>
            <li><a href="<?php echo $prlink?>" title="<?php echo $project->{Projects_Model_Projects::COLUMN_NAME}?>"><?php 
               echo $project->{Projects_Model_Projects::COLUMN_NAME_SHORT} != null 
                    ? $project->{Projects_Model_Projects::COLUMN_NAME_SHORT}
                    : $project->{Projects_Model_Projects::COLUMN_NAME};
               ?></a></li> 
            <?php }?>
         </ul>
         </p>
         <?php } else {
            echo '<p>'.$this->tr('Žádný projekt nebyl přiřazen').'</p>';
         }
         echo $section->toolbox;
         ?>
         </div>
         <hr class="reseter" />
      <?php }?>
   <?php 
      echo $this->scrollComp;
   } else {
      echo ($this->tr('Není vložena žádná sekce ani projekt'));
   }
   ?>
</div>
