<?php 
$this->addFile("css://style.less?original");
$this->addFile("js://engine:json2.js?original");
$this->addFile("js://form-edit.js?original");
// do titulku
if($this->edit) {
   $h = $this->tr('Úprava formuláře');
} else {
   $h = $this->tr('Vytvoření nového formuláře');
}
$jq = new JsPlugin_JQuery();
$jq->addUISortable();
$jq->addUIAccordion();
$this->addJsPlugin($jq);
?>
<h1><?php echo $h;?></h1>
<div class="form-edit" id="movie-form-edit">
   <div id="form-wrap" class="ui-widget">
      <div class="ui-widget-header">
         <h2 id="form-name">Název formuláře</h2>
      </div>
      <div class="message message-info">
         <p id="form-message">Formulář byl odeslán</p>
      </div>
      <div>
         <ul id="form" class="ui-widget-content">
         </ul>
      </div>
      <div class="ui-widget-header">
         <h2><?php ps($this->tr('Nastavení formuláře')) ?></h2>
      </div>
      <div id="form-settings" class="ui-widget-content clearfix">
         <?php 
         $this->form->html()->setAttrib('id','form-data');
         echo $this->form;
         ?>
         <button id="button-serialize">Serializovat</button>
      </div>
   </div>
   <div id="form-tools-wrap">
      <div class="ui-widget-header"><?php echo $this->tr('Nástroje')?></div>
      <div id="form-tools" class="ui-widget-content" >
         
         <h3 class="accordion ui-widget-header">Přidání elementu</h3>
         <div class="ui-widget-content" id="form-element-create">
            Nový element:
            <select name="create-element" onchange="FormEditor.createFormItem($(this).val());$(this).val('');">
               <optgroup label="<?php echo $this->tr('Základní')?>">
                  <option value=""><?php echo $this->tr('Vyberte element...')?></option>
                  <option value="text"><?php echo $this->tr('Textový řádek')?></option>
                  <option value="textarea"><?php echo $this->tr('Textové pole')?></option>
                  <option value="checkbox"><?php echo $this->tr('Checkbox')?></option>
                  <option value="select"><?php echo $this->tr('Výběr')?></option>
                  <option value="radio"><?php echo $this->tr('Výběr (radio)')?></option>
                  <option value="label"><?php echo $this->tr('Napis')?></option>
                  <option value="file"><?php echo $this->tr('Soubor')?></option>
               </optgroup>
               <optgroup label="<?php echo $this->tr('Pokročilé')?>">
                  <option value="selectcountry"><?php echo $this->tr('Výběr státu')?></option>
               </optgroup>
            </select>
         </div>
         
         <h3 class="accordion ui-widget-header">Nastavení elementu</h3>
         <div class="ui-widget-content" id="form-elem-setup">
            <form  id="form-elem-settings" onsubmit="return false;">
               <label>Název:</label><br />
               <input type="text" name="name" value="" onkeyup="FormEditor.$selectedItem.trigger('chengeLabel', $(this).val())" class="form-control" /><br />
               <label>Poznámka:</label><br />
               <input type="text" name="note" value="" onkeyup="FormEditor.$selectedItem.trigger('chengeNote', $(this).val())" class="form-control" />
               <div class="elem-optional" id="elem-optional-require-wrap">
                  <label>Povinný:</label>
                  <input type="checkbox" name="require" onchange="FormEditor.$selectedItem.trigger('chengeRequire', $(this).is(':checked'))"/>
               </div>
               <div class="elem-optional" id="elem-optional-options-wrap">
                  <label>Položky:</label><br />
                  <textarea name="optional-settings" onkeyup="FormEditor.$selectedItem.trigger('chengeOptions', $(this).val())" class="form-control"></textarea>
                  <p class="note">Nový řádek je nová položka</p>
               </div>
               <div class="elem-optional" id="elem-optional-validators-wrap">
                  <label>Validátor:</label><br />
                  <select name="validator" onchange="FormEditor.$selectedItem.trigger('chengeValidator', [this])" class="form-control">
                     <option value=""><?php echo $this->tr('Žádný')?></option>
                     <option value="mail"><?php echo $this->tr('E-Mail')?></option>
                     <option value="url"><?php echo $this->tr('URL adresa')?></option>
                     <option value="phone"><?php echo $this->tr('Telefon')?></option>
                  </select>
               </div>
               <div class="elem-optional" id="elem-optional-filetype-wrap">
                  <label>Typ souboru:</label><br />
                  <select name="filetype" onchange="FormEditor.$selectedItem.trigger('chengeFileType', $(this).val())" class="form-control">
                     <option value="imgonly"><?php echo $this->tr('Pouze obrázky')?></option>
                     <option value="doconly"><?php echo $this->tr('Pouze dokumenty')?></option>
                     <option value="extonly"><?php echo $this->tr('Dle přípony')?></option>
                  </select>
                  <label for="item-fileext"><?php ps($this->tr('Pouze soubory s příponou:'))?></label><br />
                  <input type="text" name="fileext" id="item-fileext" value="" onchange="FormEditor.$selectedItem.trigger('chengeFileType', $(this).val())" class="form-control" />
               </div>
               <div class="elem-optional" id="elem-optional-is-multiple-wrap">
                  <label>Více voleb:</label>
                  <input type="checkbox" name="ismultiple" onchange="FormEditor.$selectedItem.trigger('chengeIsMultiple', $(this).is(':checked'))"/>
               </div>
            </form>
         </div>
      </div>
   </div>
   <div id="form-tpls">
      <div class="element-tools">
         <a href="<?php echo $this->link()?>#" onclick="FormEditor.deleteFormItem(this);return false;"
                     title="<?php echo $this->tr('Smazat prvek')?>"><span class="ui-icon ui-icon-closethick"></span></a>
      </div>
   </div>
   <hr class="reseter" />
</div>
<script type="text/javascript">
   $(document).ready(function(){
      FormEditor.init({
         selectcountry : {label : '<?php echo $this->tr('Výběr země')?>', options : <?php echo json_encode(array_values( Form_Element_CountrySelect::getCountries()) ) ?>},
         defaultlabel : '<?php echo $this->tr('Název')?>'
      });
   });
</script>
