<?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('edit_photos', $this->_("Upravit akci"),
              $this->link()->route('edit'),
              $this->_("Upravit zobrazenou akci"), "page_edit.png");
      $toolbox->addTool('edit_ac_photos', $this->_("Upravit fotky"),
              $this->link()->route('editphotos'),
              $this->_("Upravit fotky akce"), "image_edit.png");
      $toolbox->addTool('article_delete', $this->_("Smazat akci"),
              $this->link(), $this->_("Smazat zobrazenou akci"), "page_delete.png",
              'article_id', (int)$this->action->{Articles_Model_Detail::COLUMN_ID},
              $this->_('Opravdu smazat akci?'));
      $this->includeTplObj($toolbox);
   }
   ?>