<? // načtení detailu
$this->addPageTitle($this->action->{Actions_Model_Detail::COLUMN_NAME});
$this->addPageHeadline($this->action->{Actions_Model_Detail::COLUMN_NAME});

$jQuery = new JsPlugin_JQuery();
$jQuery->addWidgentTabs();
$this->addJsPlugin($jQuery);
$this->addJsPlugin(new JsPlugin_PiroBox());

$photosModel = new PhotoGalery_Model_Images();
$countImages = $photosModel->getCountImages($this->category()->getId(), $this->action->{Actions_Model_Detail::COLUMN_ID});
?>

<div>
   <!--<h2><?=htmlspecialchars($this->action->{Actions_Model_Detail::COLUMN_NAME})?>&nbsp;-->
   <!--</h2>-->
   <p>
      <?
      $startDate = strftime("%x", $this->action->{Actions_Model_Detail::COLUMN_DATE_START});
      $stopDate = strftime("%x", $this->action->{Actions_Model_Detail::COLUMN_DATE_STOP});
      print ($startDate);
      if($startDate != $stopDate) {
         print ("&nbsp;&mdash;&nbsp;");
         print ($stopDate);
      }?>
      <br />
      <?=$this->_('Naposled upraveno:')?>&nbsp;<?=strftime("%x %X", $this->action->{Actions_Model_Detail::COLUMN_EDIT_TIME})?>
   </p>
   <!--<p>
      <a href="<?=$this->link()->route('detail')?>"><?=$this->_('Text')?></a>
      <a href="<?=$this->link()->route('detailPhotos')?>"><?=$this->_('Fotky')?></a>
   </p>-->

   <div id="actionTabs">
      <?if($countImages > 0) {?>
      <ul>
         <li><a href="#actionText"><?=$this->_('Text')?></a></li>
         <li><a href="#actionImages"><?=$this->_('Fotky')?></a></li>
      </ul>
         <?}?>
      <div id="actionText"><!-- SOF TEXT -->
         <?if($this->action->{Actions_Model_Detail::COLUMN_IMAGE} != null) {
            print (vve_tpl_image_tag($this->category()->getModule()->getDataDir().
                    $this->action->{Actions_Model_Detail::COLUMN_IMAGE}, 'image', null,null, 'actionImage'));
         }?>
         <?=$this->action->{Actions_Model_Detail::COLUMN_TEXT}?>
      </div> <!-- EOF TEXT -->
      <?if($countImages > 0) {?>
      <div id="actionImages"><!-- SOF IMAGES -->
            <?while ($image = $this->images->fetch()) {?>
         <a class="pirobox_gall" href="<?=$this->category()->getModule()->getDataDir(true)
                          .Photogalery_Controller::DIR_MEDIUM.URL_SEPARATOR.$image[PhotoGalery_Model_Images::COLUMN_FILE]?>"
            title="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>">
            <img src="<?=$this->category()->getModule()->getDataDir(true).Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                               .$image[PhotoGalery_Model_Images::COLUMN_FILE]?>" alt="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>" />
         </a>
               <?}?>
      </div>
         <?}?>
   </div>
   <?if($countImages > 0) {?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $("#actionTabs").tabs();

      $(document).ready(function(){
         $().piroBox({
            my_speed: 300, //animation speed
            bg_alpha: 0.8, //background opacity
            radius: 4, //caption rounded corner
            scrollImage : false, // true == image follows the page _|_ false == image remains in the same open position
            // in some cases of very large images or long description could be useful.
            slideShow : 'slideshow', // true == slideshow on, false == slideshow off
            slideSpeed : 3, //slideshow
            pirobox_next : 'piro_next', // Nav buttons -> piro_next == inside piroBox , piro_next_out == outside piroBox
            pirobox_prev : 'piro_prev', // Nav buttons -> piro_prev == inside piroBox , piro_prev_out == outside piroBox
            close_all : '.piro_close' // add class .piro_overlay(with comma)if you want overlay click close piroBox
         });
      });
      /* ]]> */
   </script>
      <?}?>
   <hr class="reseter" />

   <?$this->includeTpl('tools.phtml')?>
   <br />
   <?=$this->shares?>
</div>
<?$this->includeTpl("buttonback.phtml", true, array('link' => $this->link()->route()));?>
