<? // načtení detailu
$this->addPageTitle($this->action->{Actions_Model_Detail::COLUMN_NAME});

$jQuery = new JsPlugin_JQuery();
$this->addJsPlugin($jQuery);
$this->addJsPlugin(new JsPlugin_PiroBox());

$photosModel = new PhotoGalery_Model_Images();
$countImages = $photosModel->getCountImages($this->category()->getId(), $this->action->{Actions_Model_Detail::COLUMN_ID});
?>
<h1><?=$this->action->{Actions_Model_Detail::COLUMN_NAME};?></h1>
<div class="main-content-detail">
   <?if($this->action->{Actions_Model_Detail::COLUMN_IMAGE} != null) {?>
   <div class="main-content-image" id="actionText"><!-- SOF TEXT -->
      <?echo (vve_tpl_image_tag($this->category()->getModule()->getDataDir(true).$this->imagesDir.DIRECTORY_SEPARATOR
          .$this->action->{Actions_Model_Detail::COLUMN_IMAGE}, 'image', 300,null, 'actionImage'));?>
   </div>
   <?}?>

   <div class="main-content-annotation">
      <p class="main-content-dates">
               <?
               $startDate = vve_date("%x", new DateTime($this->action->{Actions_Model_Detail::COLUMN_DATE_START}));
               $stopDate = vve_date("%x", new DateTime($this->action->{Actions_Model_Detail::COLUMN_DATE_STOP}));
               print ($startDate);
               if($startDate != $stopDate AND $this->action->{Actions_Model_Detail::COLUMN_DATE_STOP} != null) {
                  print ("&nbsp;&mdash;&nbsp;");
                  print ($stopDate);
               }
               if($this->action->{Actions_Model_Detail::COLUMN_TIME} != null) {
                  $time = new DateTime($this->action->{Actions_Model_Detail::COLUMN_TIME});
                  print (",&nbsp;".$time->format("G:i"));
               }?>
            </p>
            <p class="main-content-other">
               <?
               if($this->action->{Actions_Model_Detail::COLUMN_PLACE} != null) {
                  print ',&nbsp;'.$this->action->{Actions_Model_Detail::COLUMN_PLACE};
               }
               if((int)$this->action->{Actions_Model_Detail::COLUMN_PRICE} != null|0) {
                  printf(',&nbsp;'.strtolower($this->_('Vstupné: %d Kč')),$this->action->{Actions_Model_Detail::COLUMN_PRICE});
               }
               if((int)$this->action->{Actions_Model_Detail::COLUMN_PREPRICE} != null|0) {
                  printf(',&nbsp;'.strtolower($this->_('V předprodeji: %d Kč')),$this->action->{Actions_Model_Detail::COLUMN_PREPRICE});
               }?>
            </p>
         <?if($this->action->{Actions_Model_Detail::COLUMN_NOTE} != null) {?>
         <p class="action-note"><?=$this->action->{Actions_Model_Detail::COLUMN_NOTE}?></p>
            <?}?>
         <br />
   </div>
   <div class="main-content-text">
         <?=$this->action->{Actions_Model_Detail::COLUMN_TEXT}?>
         <hr class="reseter" />
   </div>
      <?if($countImages > 0) {?>
   <div class="main-content-images" id="actionImages"><!-- SOF IMAGES -->
            <?while ($image = $this->images->fetch()) {?>
         <a class="pirobox_gall" href="<?=$this->category()->getModule()->getDataDir(true).$this->action[Actions_Model_Detail::COLUMN_URLKEY][Locales::getDefaultLang()]
                          .URL_SEPARATOR.Photogalery_Controller::DIR_MEDIUM.URL_SEPARATOR.$image[PhotoGalery_Model_Images::COLUMN_FILE]?>"
            title="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>">
            <img src="<?=$this->category()->getModule()->getDataDir(true).$this->action[Actions_Model_Detail::COLUMN_URLKEY][Locales::getDefaultLang()]
                               .URL_SEPARATOR.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR.$image[PhotoGalery_Model_Images::COLUMN_FILE]?>"
                 alt="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>" />
         </a>
               <?}?>
      </div>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){$().piroBox({slideShow : true,slideSpeed : 3});});
      /* ]]> */
   </script>
      <?}?>
   <hr class="reseter" />
   <?$this->includeTpl("buttonback.phtml", true);?>

   <?//$this->includeTpl('tools.phtml')?>
   <?$this->includeTpl('articletools.phtml', true, array(
           'lastEditTime' => $this->action->{Actions_Model_Detail::COLUMN_CHANGED},
           'lastEditUser' => $this->action->{Model_Users::COLUMN_USERNAME},
           'linkToPdf' => $this->link()->route('detailExport',array('output' => 'pdf')),
           'shares' => $this->shares));?>
   <?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('edit_action', $this->_("Upravit akci"),
              $this->link()->route('edit'),
              $this->_("Upravit zobrazenou akci"), "page_edit.png");
      $toolbox->addTool('edit_photos', $this->_("Upravit fotky"),
              $this->link()->route('editphotos'),
              $this->_("Upravit fotky zobrazené akce"), "image_edit.png");
      $toolbox->addTool('action_delete', $this->_("Smazat akci"),
              $this->link(), $this->_("Smazat zobrazenou akci"), "page_delete.png",
              'action_id', (int)$this->action->{Articles_Model_Detail::COLUMN_ID},
              $this->_('Opravdu smazat akci?'));
      $this->includeTplObj($toolbox);
   }
   ?>
</div>
