<? // načtení detailu
$this->addPageTitle($this->action->{Actions_Model::COLUMN_NAME});
$this->addPageHeadline($this->action->{Actions_Model::COLUMN_NAME});

$photosModel = new PhotoGalery_Model_Images();
$this->addJsPlugin(new JsPlugin_PiroBox());
?>

<div>
   <!--<h2><?=htmlspecialchars($this->action->{Actions_Model::COLUMN_NAME})?>&nbsp;-->
   <!--</h2>-->
   <p>
      <?
      $startDate = strftime("%x", $this->action->{Actions_Model::COLUMN_DATE_START});
      $stopDate = strftime("%x", $this->action->{Actions_Model::COLUMN_DATE_STOP});
      print ($startDate);
      if($startDate != $stopDate) {
         print ("&nbsp;&mdash;&nbsp;");
         print ($stopDate);
      }?>
      <br />
      <?=$this->_('Naposled upraveno:')?>&nbsp;<?=strftime("%x %X", $this->action->{Actions_Model::COLUMN_EDIT_TIME})?>
   </p>
   <p>
      <a href="<?=$this->link()->route('detail')?>"><?=$this->_('Text')?></a>
      <a href="<?=$this->link()->route('detailPhotos')?>"><?=$this->_('Fotky')?></a>
   </p>

   <div id="Action_Photos"><!-- SOF IMAGES -->
      <?while ($image = $this->images->fetch()) {?>
      <a class="pirobox_gall" href="<?=$this->category()->getModule()->getDataDir(true)
                    .Photogalery_Controller::DIR_MEDIUM.URL_SEPARATOR.$image[PhotoGalery_Model_Images::COLUMN_FILE]?>"
         title="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>">
         <img src="<?=$this->category()->getModule()->getDataDir(true).Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                         .$image[PhotoGalery_Model_Images::COLUMN_FILE]?>" alt="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>" />
      </a>
         <?}?>
      <script type="text/javascript">
         /* <![CDATA[ */
         $(document).ready(function(){
            $().piroBox({
               my_speed: 300, //animation speed
               bg_alpha: 0.8, //background opacity
               radius: 4, //caption rounded corner
               scrollImage : false, // true == image follows the page _|_ false == image remains in the same open position
               // in some cases of very large images or long description could be useful.
               slideShow : 'slideshow', // true == slideshow on, false == slideshow off
               slideSpeed : 3, //slideshow
               pirobox_next : 'piro_next', // Nav buttons -> piro_next == inside piroBox , piro_next_out == outside piroBox
               pirobox_prev : 'piro_prev', // Nav buttons -> piro_prev == inside piroBox , piro_prev_out == outside piroBox
               close_all : '.piro_close' // add class .piro_overlay(with comma)if you want overlay click close piroBox
            });
         });

         /* ]]> */
      </script><!-- EOF IMAGES -->
   </div>
   <hr class="reseter" />
   <?$this->includeTpl('tools.phtml')?>
   <br />
   <?=$this->shares?>
</div>
<?$this->includeTpl("buttonback.phtml", true);?>