<?
$icon = null;
if($this->panel->{Model_Panel::COLUMN_ICON} != null){
   $icon = '<img src="'.Panel::getIconDir().$this->panel->{Model_Panel::COLUMN_ICON}.'" alt="'.$this->panel->{Model_Panel::COLUMN_ICON}.'" />';
}
$backImg = null;
if($this->panel->{Model_Panel::COLUMN_BACK_IMAGE} != null){
   $backImg = 'background-image: url(\''.Panel::getBackImgDir().$this->panel->{Model_Panel::COLUMN_BACK_IMAGE}.'\');';
}
?>
<p class="panelLabel"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->category()->getLabel()?></a></p>
<div class="panelActions" style="<?=$backImg?>">
   <p><?=$this->_('Aktuální')?>:</p><br />
   <?while ($row = $this->actions->fetch()) {?>
   <a href="<?=$this->link()->route('detail', array('urlkey' => $row->{Actions_Model_Detail::COLUMN_URLKEY}))?>"
      title="<?=$row->{Actions_Model_Detail::COLUMN_NAME}?>"
      ><?=$row->{Actions_Model_Detail::COLUMN_NAME}?></a><br />
   <?}?>
</div>
<p class="panelLinkMore">
   <a href="<?=$this->link()?>"
      title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->_('Více')?></a>
</p>