<?php 

if(!isset($param) || !$param instanceof Model_ORM_Record){
   $param = Shop_Model_Product_ParamsValues::getNewRecord();
   $param->{Shop_Model_Product_ParamsValues::COLUMN_ID} = '{NEW}';
   $param->{Shop_Model_Product_ParamsValues::COLUMN_ID_PARAM} = 0;
   $pRowID = 'NEW';
} else {
   $pRowID = $param->getPK();
}

$this->formEdit->delete->setMultiple($param->getPK());
if(isset($this->formEdit->paramid)){
   $this->formEdit->paramid->setDimensional($param->getPK());
   $this->formEdit->paramid->setValues($param->{Shop_Model_Product_ParamsValues::COLUMN_ID_PARAM});
}
$this->formEdit->paramname->setMultiple($param->getPK());
$this->formEdit->value->setMultiple($param->getPK());
$this->formEdit->value->setValues($param->{Shop_Model_Product_ParamsValues::COLUMN_VALUE});
?>
<tr class="cubecms-row <?php echo isset($rowClasses) ? $rowClasses : null ?>" id="param-row-<?php echo $pRowID ?>">
   <td class="text-center">
      <div class="sorting-area">
         <span class="icon icon-arrows-v"></span><br />
      </div>
   </td>
   <td class="text-center">
      <?php echo $param->getPK() ?>
   </td>
   <td>
      <?php
      if(isset($this->formEdit->paramid)){
         echo $this->formEdit->paramid->setLabel('Použít parametr');
         echo $this->formEdit->paramid->label();
         echo $this->formEdit->paramid->controlAll();
      }
      ?>
      
      <?php
      $this->formEdit->paramname->setLabel('Vytvořit nový parametr');
      echo $this->formEdit->paramname->label().'<br />';
      $this->formEdit->paramname->html()->addClass('form-control');
      echo $this->formEdit->paramname->controlAll();
      ?>
   </td>
   <td>
      <div>
         <?php
         $this->formEdit->value->html()->addClass('form-control');
         echo $this->formEdit->value->controlAll();
         ?>
      </div>
   </td>
   <td>
      <?php echo $this->formEdit->delete->control(); ?>
      <a href="#" class="mark-param-delete text-danger"><span class="icon icon-remove"></span></a>
   </td>
</tr>