<?php
$this->addFile('css://engine:shop/style.less');
$this->addFile('js://engine:shop.js');
$jq = new JsPlugin_JQuery();
$jq->addUIButton();
$jq->addJQPlugin('cookie');
//$jq->addUITabs();
$this->addJsPlugin($jq);
// do titulku
$h = sprintf($this->tr('úprava variant produktu "%s"'), $this->product->{Shop_Model_Product::COLUMN_NAME});

$this->addPageTitle($h);
?>
<h1><?php echo $h; ?></h1>
<div class="main-content-form-edit">
   <?php
   if ($this->moduleActionButtons == null) {
      $this->moduleButtons = array(
          array(
              'link' => $this->linkBack == null ? $this->link()->route('detail') : $this->linkBack,
              'title' => $this->tr('Zavřít úpravu variant a přejít zpět na produkt'),
              'icon' => 'close',
              'name' => $this->tr('Zpět na produkt'),
          ),
      );
   } else {
      $this->moduleButtons = $this->moduleActionButtons;
   }
   $this->includeTpl('modules/buttons.phtml', true);
   ?>
</div>
<div class="main-content-form-edit" id="products-variants-edit-content">
   <div class="cubecms-tabs">

      <ul class="nav nav-tabs" id="pr-var-tabs">
         <li role="presentation" class="active"><a aria-controls="products-variants" role="tab" data-toggle="tab" href="<?php echo $this->link()->rmParam() ?>#products-variants"><?php echo $this->tr('Tvorba variant') ?></a></li>
         <li role="presentation"><a aria-controls="product-combinations" role="tab" data-toggle="tab" href="<?php echo $this->link()->rmParam() ?>#product-combinations"><?php echo $this->tr('Kombinace') ?></a></li>
         <li role="presentation"><a aria-controls="product-code-edit" role="tab" data-toggle="tab" href="<?php echo $this->link()->rmParam() ?>#product-code-edit"><?php echo $this->tr('Nastavení kódu produktu') ?></a></li>
      </ul>

      <div class="tab-content">
         <div id="products-variants" class="tab-pane active" role="presentation">
            <div class="">
               <p>
                  <?php
                  printf($this->tr('Základní cena produktu: <strong>%s</strong> bez daně, s daní: <strong>%s</strong>'), Shop_Tools::getPrice($this->product->{Shop_Model_Product::COLUMN_PRICE}), Shop_Tools::getPriceOfProduct($this->product));
                  ?>
               </p>
               <?php
               foreach ($this->formEditVariants as $element) {
                  if ($element instanceof Form_Element_Text || $element instanceof Form_Element_TextArea) {
                     $element->html()->addClass('form-control');
                  } else if ($element instanceof Form_Element_Submit || $element instanceof Form_Element_Button) {
                     $element->html()->addClass('btn btn-primary');
                  }
               }

               $this->formEditVariants->html()->setAttrib('id', 'form-create-combinations');
               echo($this->formEditVariants->renderStart());
               ?>
               <table id="products-variants-table" class="full-width variants-table cubecms-widget cubecms-table">
                  <thead class="cubecms-header">
                     <tr class="">
                        <th colspan="2"><?php echo $this->tr('Varianty') ?></th>
                        <th style="width: 40px;"><?php echo $this->tr('Výchozí') ?></th>
                        <th style="width: 300px;">
                           <?php echo $this->tr('Cena varianty') ?><br />
                           <span class="font-small"><?php echo $this->tr('bez ceny produktu') ?></span>
                        </th>
                        <th><?php echo $this->tr('Kód varianty') ?></th>
                        <th style="width: 120px;"><?php echo $this->tr('Váha varianty') ?></th>
                        <th></th>
                     </tr>
                  </thead>
                  <tfoot class="cubecms-footer">
                     <tr class="cubecms-row">
                        <td colspan="7" class="font-small">
                           * - <?php ps($this->tr('Pro tuto vlastnost nejsou vygenerovány kombinace. Nebude zobrazena ve výběru u produktu.')) ?>
                        </td>
                     </tr>
                     <?php if (!empty($this->productVarinats)) { ?>
                        <tr class="cubecms-row">
                           <td colspan="7">
                              <div class="controls">
                                 <?php
                                 echo $this->formEditVariants->generatePrice->control();
                                 echo $this->formEditVariants->generatePrice->label(null, true);
                                 echo $this->formEditVariants->save->control();
                                 ?>
                              </div>
                           </td>
                        </tr>
                     <?php } ?>
                  </tfoot>
                  <tbody class="cubecms-content">
                     <?php
                     if (!empty($this->productVarinats)) {
                        $prevGroupId = null;
                        foreach ($this->productVarinats as $variant) {
                           // kontrola nové varianty
                           if ($variant->{Shop_Model_Attributes::COLUMN_ID_GROUP} != $prevGroupId) {
                              $prevGroupId = $variant->{Shop_Model_Attributes::COLUMN_ID_GROUP};
                              ?>
                              <tr class="group-name cubecms-row cubecms-state-highlight">
                                 <td colspan="7">
                                    <?php ps($variant->{Shop_Model_AttributesGroups::COLUMN_NAME}) ?>
                                    ID: <?php echo $variant->{Shop_Model_Attributes::COLUMN_ID_GROUP} ?>
                                 </td>
                              </tr>
                              <?php
                           }
                           ?>
                           <tr id="variant-<?php echo $variant->getPK() ?>"
                               class="variant cubecms-row <?php if ($variant->{Shop_Model_Product_CombinationHasVariant::COLUMN_ID_COMBINATION} == null) echo ""; ?>">
                              <td></td>
                              <td>
                                 <?php
                                 ps($variant->{Shop_Model_Attributes::COLUMN_NAME});
                                 if ($variant->{Shop_Model_Product_CombinationHasVariant::COLUMN_ID_COMBINATION} == null) {
                                    echo " *";
                                 }
                                 if($variant->{Shop_Model_Attributes::COLUMN_CODE}){ ?>
                                       <em>(<?php echo $variant->{Shop_Model_Attributes::COLUMN_CODE}?>)</em>
                                 <?php } ?>
                              </td>
                              <td class="text-center">
                                 <?php
                                 $this->formEditVariants->default->setMultiple($variant->{Shop_Model_Attributes::COLUMN_ID_GROUP});
                                 $this->formEditVariants->default->setOptions(array($variant->{Shop_Model_Product_Variants::COLUMN_ID}));
                                 $this->formEditVariants->default->setRenderlabelInControl(false);
                                 echo $this->formEditVariants->default->control();
                                 ?>
                              </td>
                              <td>
                                 <table class="price-table full-width">
                                    <tr>
                                       <td><?php echo $this->tr('Bez daně:') ?></td>
                                       <td>
                                          <div class="input-group">
                                             <?php
                                             $this->formEditVariants->price->html()->addClass('price_without_tax');
                                             $this->formEditVariants->price->setMultiple($variant->{Shop_Model_Product_Variants::COLUMN_ID});
                                             $this->formEditVariants->price->setValues($variant->{Shop_Model_Product_Variants::COLUMN_PRICE_ADD});
                                             echo $this->formEditVariants->price->control();
                                             ?>
                                             <span class="input-group-addon"><?php echo CUBE_CMS_SHOP_CURRENCY_NAME ?></span>
                                          </div>
                                       </td>
                                    </tr>
                                    <tr>
                                       <td><?php echo $this->tr('S daní:') ?></td>
                                       <td>
                                          <div class="input-group">
                                             <input type="text" class="product_variants_price_class price_with_tax form-control"
                                                    value="<?php
                                                    echo Shop_Tools::getPrice(
                                                            $variant->{Shop_Model_Product_Variants::COLUMN_PRICE_ADD}, $this->product->{Shop_Model_Tax::COLUMN_VALUE}, false);
                                                    ?>">
                                             <span class="input-group-addon"><?php echo CUBE_CMS_SHOP_CURRENCY_NAME ?></span>
                                          </div>
                                       </td>
                                    </tr>
                                 </table>
                              </td>
                              <td><?php
                                 $this->formEditVariants->code->setMultiple($variant->{Shop_Model_Product_Variants::COLUMN_ID});
                                 $this->formEditVariants->code->setValues($variant->{Shop_Model_Product_Variants::COLUMN_CODE_ADD});
                                 echo $this->formEditVariants->code->control();
                                 ?></td>
                              <td>
                                 <div class="input-group">
                                    <?php
                                    $this->formEditVariants->weight->setMultiple($variant->{Shop_Model_Product_Variants::COLUMN_ID});
                                    $this->formEditVariants->weight->setValues($variant->{Shop_Model_Product_Variants::COLUMN_WEIGHT_ADD});
                                    echo $this->formEditVariants->weight->control();
                                    ?> 
                                    <span class="input-group-addon">Kg</span>
                                 </div>
                              </td>
                              <td>
                                 <a href="<?php echo $this->link()->param('deleteComb', $variant->{Shop_Model_Product_Variants::COLUMN_ID}) ?>"
                                    class="button-delete-variant" >
                                    <img src="/images/icons/delete.png" alt="del" />
                                 </a>

                              </td>
                           </tr>
                           <?php
                        }
                     } else {
                        ?>
                        <tr class="cubecms-row">
                           <td colspan="6"><?php echo $this->tr('Není přiřazena žádná varianta') ?></td>
                        </tr>
                     <?php } ?>
                  </tbody>
               </table>
               <?php echo($this->formEditVariants->renderEnd()); ?>
            </div>
            <div id="products-new-variant" class="">
               <h2 class=""><?php echo $this->tr('Přidání varianty') ?></h2>
               <div class="">
                  <?php
                  echo $this->formAddVariant->renderStart();
                  echo '<div class="controls">';
                  echo $this->formAddVariant->ids;
                  echo "</div>";
                  echo '<div id="form-selected-variants" class="font-small"></div>';
                  echo '<div class="buttons">';
                  echo '<span class="font-small">' . $this->tr('Více položek označíte podržením klávesy "Ctrl".') . '</span>   ';
                  echo $this->formAddVariant->save;
                  echo '<span class="form-return-msg"></span></div>';
                  echo $this->formAddVariant->renderEnd();
                  ?>
               </div>
            </div>
         </div>

         <div id="product-code-edit" class="tab-pane" role="presentation">
            <p class="">
               <?php ps($this->tr('Pro dynamické generování kódu stačí doplnit id atributu ve formátu "{id}".
            Tedy například z kódu PRODUCT-{5}-{3} se generuje PRODUCT-RED-A4.')); ?>
            </p>
            <div class="">
               <?php
               $this->formProductCode->html()->setAttrib('id', 'form-save-product-code')->addClass('form-horizontal');
               echo $this->formProductCode->renderStart();
               ?>
               <div class="row">
                  <div class="col-sm-4">
                     <div class="form-controls">
                        <?php
                        $this->formProductCode->code->html()->addClass('form-control');
                        echo $this->formProductCode->code;
                        ?>
                     </div>
                  </div>
                  <div class="col-sm-1">
                     <div class="form-controls">
                        <?php
                        $this->formProductCode->save->html()->addClass('btn')->addClass('btn-primary');
                        echo $this->formProductCode->save;
                        ?>
                     </div>
                  </div>
                  <div class="col-sm-4 form-return-msg" style="display: none;">
                     <div class="text-success" role="alert"></div>
                  </div>
               </div>
               <?php
               echo $this->formProductCode->renderEnd();
               ?>
            </div>
            <br />
            <h2><?php echo $this->tr('Skupiny přiřazené k produktu') ?></h2>
            <div>
               <table id="products-attributes-groups-table" class="full-width attributes-table cubecms-widget cubecms-table">
                  <thead class="cubecms-header">
                     <tr class="ui-widget-header">
                        <th><?php echo $this->tr('Název skupiny') ?></th>
                        <th></th>
                     </tr>
                  </thead>
                  <tbody class="cubecms-content">
                     <?php foreach ($this->variantsGroups as $group) { ?>
                        <tr class="cubecms-row">
                           <td>
                              <?php
                              ps($group->{Shop_Model_AttributesGroups::COLUMN_NAME} . " ");
                              ps('ID: ' . $group->{Shop_Model_AttributesGroups::COLUMN_ID} . '. ');
                              echo '<span class="font-small">';
                              ps(sprintf($this->tr('Do kódu vložte: "%s"'), "{" . $group->{Shop_Model_AttributesGroups::COLUMN_ID} . "}"));
                              echo '</span>';
                              ?>
                           </td>
                           <td class="variants-groups-buttons">
                              <button class="button-add-code btn btn-primary" type="button"
                                      data-codeadd="<?php echo $group->{Shop_Model_Attributes::COLUMN_ID_GROUP} ?>"
                                      ><span class="icon icon-plus"></span> <?php ps($this->tr('přidat do kódu')) ?></button>
                           </td>
                        </tr>
                     <?php } ?>
                  </tbody>
               </table>

            </div>
         </div>

         <div id="product-combinations" class="tab-pane" role="presentation">
            <?php
            echo $this->formComb->renderStart();
            $this->formComb->save->html()->addClass('btn')->addClass('btn-primary');
            ?>
            <table id="products-combinations-table" class="full-width combinations-table cubecms-widget cubecms-table">
               <thead class="">
                  <tr class="cubecms-header">
                     <th><?php echo $this->tr('Kombinace') ?></th>
                     <th><?php echo $this->tr('Kód') ?></th>
                     <th style="width: 100px;">
                        <?php
                        echo $this->tr('Váha');
                        $this->orderParam = 'word';
                        echo $this->includeFile('tpl://engine:modules/buttons-table-order.phtml');
                        ?></th>
                     <th style="width: 130px;">
                        <?php
                        echo $this->tr('Množství');
                        $this->orderParam = 'qord';
                        echo $this->includeFile('tpl://engine:modules/buttons-table-order.phtml');
                        ?>
                     </th>
                     <th colspan="3">
                        <?php
                        echo $this->tr('Cena bez dph');
                        $this->orderParam = 'pord';
                        echo $this->includeFile('tpl://engine:modules/buttons-table-order.phtml');
                        ?>
                     </th>
      <!--               <th></th>-->
                  </tr>
                  <tr class="cubecms-row">
                     <td colspan="7" class="combination-controll">
                        <?php echo $this->formComb->save ?>
                     </td>
                  </tr>
               </thead>
               <tfoot>
                  <tr class="cubecms-footer">
                     <td colspan="7" class="combination-controll">
                        <?php 
                        echo $this->formComb->save;
                        ?>
                     </td>
                  </tr>
               </tfoot>
               <tbody>
                  <?php
                  if (!empty($this->productCombinations)) {
                     $row = 1;
                     foreach ($this->productCombinations as $c) {
                        ?>
                        <tr class="cubecms-row combination-row <?php
                        if ($c->{Shop_Model_Product_Combinations::COLUMN_IS_DEFAULT}) {
                           echo ' cubecms-state-highlight';
                        }
                        if ($c->{Shop_Model_Product_Combinations::COLUMN_QTY} == 0 && $this->product->{Shop_Model_Product::COLUMN_STOCK}) {
                           echo " cubecms-state-error";
                        }
                        ?>">
                           <td class="combination-name">
                              <?php
                              if ($c->{Shop_Model_Product_Combinations::COLUMN_IS_DEFAULT}) {
                                 ?><img src="/images/icons/asterisk_yellow.png" alt="default" title="<?php echo $this->tr('Výchozí kombinace') ?>" /> <?php
                              }
                              ps($c->comb_name)
                              ?>
                           </td>
                           <td class="combination-code text-nowrap">
                              <?php
                              echo Shop_Tools::getProductCode(
                                      $this->product->{Shop_Model_Product::COLUMN_CODE}, json_decode($c->comb_codes_json), $c->comb_attr_codes_json
                              );
                              ?>
                           </td>
                           <td class="combination-weight">
                              <?php
                              ps(round($this->product->{Shop_Model_Product::COLUMN_WEIGHT} + $c->weight, 2) . " Kg");
                              ?>
                           </td>
                           <td class="combination-qty">
                              <div class="input-group">
                              <?php
                              $this->formComb->qty->html()->addClass('form-control')->addClass('text-right');
                              $this->formComb->qty->setMultiple($c->{Shop_Model_Product_Combinations::COLUMN_ID});
                              $this->formComb->qty->setValues($c->{Shop_Model_Product_Combinations::COLUMN_QTY});
                              echo $this->formComb->qty->control();
                              ?>
                                 <span class="input-group-addon"><?php echo $this->product->{Shop_Model_Product::COLUMN_UNIT}?></span>
                              </div>
                           </td>
                           <td class="combination-price inline-elements">
                              <?php
                              $this->formComb->price->html()->addClass('form-control form-control-autowidth')->addClass('text-right');
                              $this->formComb->price->setMultiple($c->{Shop_Model_Product_Combinations::COLUMN_ID});
                              $this->formComb->price->setValues($c->{Shop_Model_Product_Combinations::COLUMN_PRICE});
                              echo $this->formComb->price->control();
                              ?>
                           </td>
                           <td class="text-right text-nowrap">
                              <?php ps("+" . Shop_Tools::getFormatedPrice($this->product->{Shop_Model_Product::COLUMN_PRICE})); ?>
                           </td>
                           <td class="text-right text-nowrap">
                              = <span class="product-variant-total" data-baseprice="<?php echo $this->product->{Shop_Model_Product::COLUMN_PRICE} ?>"><span></span> <?php echo Shop_Tools::getCurrency() ?></span>
                           </td>
                        </tr>
                        <?php if ($row % 10 == 0) { ?>
                           <tr>
                              <td colspan="7" class="ui-widget-content combination-controll"><?php echo $this->formComb->save ?></td>
                           </tr>
                           <?php
                        }
                        $row++;
                     }
                  } else {
                     ?>
                     <tr class="cubecms-row cubecms-state-disable">
                        <td colspan="7"><?php echo $this->tr('Žádná kombinace není generována.') ?></td>
                     </tr>
                  <?php } ?>
               </tbody>
            </table>
            <?php
            echo $this->formComb->renderEnd();
            ?>
         </div>
      </div>
   </div>

   <script type="text/javascript">
      var tax = <?php echo number_format($this->product->{Shop_Model_Tax::COLUMN_VALUE} == 0 ? 0 : $this->product->{Shop_Model_Tax::COLUMN_VALUE} / 100, 2, '.', '') ?>;
      
      
      
      $(document).ready(function () {
         function updateContent()
         {
            $.get('<?php echo $this->link() ?>', function (data) {
               var $data = $(data);
               $('#products-variants-table').html($('#products-variants-table', $data).html());
               $('#products-attributes-groups-table').html($('#products-attributes-groups-table', $data).html());
               $('#products-combinations-table').html($('#products-combinations-table', $data).html());
               //                     $('#products-combinations-table').html($('products-combinations-table', $data).html());
            });
         }

         function updateTotalPrice()
         {
            $('.combination-row').each(function(){
            var $priceTotal = $('.product-variant-total span', this);
            $priceTotal.text(parseInt($('input.pr_comb_qty_price_class',this).val()) + parseInt($('.product-variant-total', this).data('baseprice')));
            });
         }
         updateTotalPrice();
         
         // base init
         CubeCMS.Tools.rememberTabSelection('#pr-var-tabs', !localStorage);
         
         $('input.pr_comb_qty_price_class').on('keyup',function(){
            updateTotalPrice();
         });
         
         // events
         $('#products-new-variant select').change(function () {
            var outHtml = "";
            var $opts = $(this).find('option:selected');
            var curLabel = null;
            $opts.each(function () {
               var label = $(this).parent().attr("label");
               if (label != curLabel) {
                  if (outHtml != "") {
                     outHtml += "<br/ >";
                  }
                  outHtml += "<strong>" + label + ":</strong> ";
                  curLabel = label;
               }
               outHtml += $(this).text() + ", ";
            });
            $('#form-selected-variants').html(/*"<strong><?php echo $this->tr('Vybráno') ?>:</strong><br />"+*/outHtml);
         });

         $('.price_without_tax, .price_with_tax').live('change', function () {
            if ($(this).hasClass('price_without_tax')) {
               $(this).parents('table.price-table').find('.price_with_tax').val(CubeCMS.Shop.getProductPrice(parseFloat($(this).val()), tax, <?php echo VVE_SHOP_PRICE_ROUND_DECIMAL ?>));
            } else {
               $(this).parents('table.price-table').find('.price_without_tax').val(CubeCMS.Shop.roundPrice(parseFloat($(this).val()) / (1 + tax), <?php echo VVE_SHOP_PRICE_ROUND_DECIMAL ?>));
            }
         });

         $('.button-delete-variant').live('click', function () {
            if (!confirm('<?php echo $this->tr('Smazat tuto varinatu?') ?>')) {
               return false;
            }
            var $this = $(this);
            var loadbox = CubeCMS.Loader.showLoadBox($this, '<?php echo $this->tr('Vymazávám') ?>');

            $.ajax({
               type: 'POST',
               url: '<?php echo $this->link()->route('editVariantsXHR') ?>',
               data: {deleteComb: (new RegExp('deleteComb=([0-9]+)')).exec($this.attr('href'))[1]},
               success: function (data) {
                  updateContent();
                  CubeCMS.Loader.hideLoadBox(loadbox);
                  CubeCMS.Msg.show(data);
               }
            });

            return false;
         });

         $('.button-add-code').live('click', function (e) {
            e.preventDefault();
            $('input[name="product_code_code"]').val($('input[name="product_code_code"]').val() + '{' +$(this).data('codeadd') + '}');
            return false;
         });

         $('#form-save-product-code').submit(function () {
            var loadbox = CubeCMS.Loader.showLoadBox(this, '<?php echo $this->tr('Ukládám') ?>');
            $.ajax({
               type: 'POST',
               url: '<?php echo $this->link()->route('editVariantsXHR') ?>',
               data: $(this).serialize(),
               success: function (data) {
                  updateContent();
                  CubeCMS.Loader.hideLoadBox(loadbox);
                  var $msgBox = $('.form-return-msg');
                  var $msgBoxText = $('.form-return-msg>div').text("").removeClass('text-error');
                  if (data.infomsg.length > 0) {
                     $msgBox.show();
                     $msgBoxText.text(data.infomsg[0]).addClass('text-success');
                     setTimeout(function () {
                        $msgBox.fadeOut(1000, function () {
                           $msgBoxText.text("");
                        });
                     }, 500);
                  } else if (data.errmsg.length > 0) {
                     $msgBox.show();
                     $msgBoxText.text(data.errmsg[0]).addClass('text-error');
                  }
               }
            });
            return false;
         });
         $('#form-create-combinations').submit(function () {
            var loadbox = CubeCMS.Loader.showLoadBox(this, '<?php echo $this->tr('Ukládám') ?>');
            $.ajax({
               type: 'POST',
               url: '<?php echo $this->link()->route('editVariantsXHR') ?>',
               data: $(this).serialize(),
               success: function (data) {
                  updateContent();
                  CubeCMS.Loader.hideLoadBox(loadbox);
                  CubeCMS.Msg.show(data);
               }
            });
            return false;
         });

         $('#products-variants-table>tbody>tr, #products-combinations-table>tbody>tr').live('mouseenter', function () {
            $(this).addClass('ui-state-hover');
         });
         $('#products-variants-table>tbody>tr, #products-combinations-table>tbody>tr').live('mouseleave', function () {
            $(this).removeClass('ui-state-hover');
         });
      });

   </script>
</div>
