<?php 
// třídy
$this->form->time->html()->addClass('prgItemTime')->setAttrib('size', 5);
$this->form->lenght->html()->addClass('prgItemLenght')->setAttrib('size', 5);
$this->form->bandid->html()->addClass('prgItemBand');
$this->form->textlong->html()->setAttrib('cols', 45)->setAttrib('rows',1);

switch ($this->type) {
   case 'band':?>
      <?php // BAND?>
      <li class="itemBand ui-state-default ui-corner-top ui-corner-bottom">
         <span class="ui-icon ui-icon-arrowthick-2-n-s move"></span>
         <span class="itemLabel">Skupina</span>
         od:&nbsp;<?php echo $this->form->time->setDimensional($this->itemIndex)->controll()?>&nbsp;
         délka:&nbsp;<?php echo $this->form->lenght->setDimensional($this->itemIndex)->controll()?>&nbsp;
         skupina:&nbsp;
         <?php echo $this->form->bandid->setDimensional($this->itemIndex)->controll()?>&nbsp;
         <span class="itemButtons">
            <a href="#" class="ui-icon ui-icon-closethick buttonRemove"></a>
         </span>
         <?php echo $this->form->type->setDimensional($this->itemIndex)->setValues('band')->controll()?>
         <hr class="reseter"/>
      </li>
      <?php 
      break;
   case "day":?>
      <?php // DAY?>
      <li  class="itemDay ui-widget-header ui-corner-top ui-corner-bottom">
         <span class="ui-icon ui-icon-arrowthick-2-n-s move"></span>
         <span class="itemLabel">Den</span>
         začátek:&nbsp;<?php echo $this->form->time->setDimensional($this->itemIndex)->controll()?>&nbsp;
         konec:&nbsp;<?php echo $this->form->lenght->setDimensional($this->itemIndex)->controll()?>&nbsp;
         název:&nbsp;<?php echo $this->form->text->setDimensional($this->itemIndex)->controll()?>&nbsp;
         <span class="itemButtons">
            <a href="#" class="ui-icon ui-icon-closethick buttonRemove"></a>
         </span>
         <?php echo $this->form->type->setDimensional($this->itemIndex)->setValues('day')->controll()?>
         <hr class="reseter"/>
      </li>
      <?php 
      break;
   case "note":?>
      <?php // NOTE?>
      <li class="itemNote ui-widget-content ui-corner-top ui-corner-bottom">
         <span class="ui-icon ui-icon-arrowthick-2-n-s move"></span>
         <span class="itemLabel">Poznámka</span>
         <?php echo $this->form->textlong->setDimensional($this->itemIndex)->controll()?>&nbsp;
         <span class="itemButtons">
            <a href="#" class="ui-icon ui-icon-closethick buttonRemove"></a>
         </span>
         <?php echo $this->form->type->setDimensional($this->itemIndex)->setValues('note')->controll()?>
         <hr class="reseter"/>
      </li>
      <?php 
      break;
   case "other":?>
      <?php // OTHER?>
      <li class="itemOther ui-state-default ui-corner-top ui-corner-bottom">
         <span class="ui-icon ui-icon-arrowthick-2-n-s move"></span>
         <span class="itemLabel">Jiné</span>
         od:&nbsp;<?php echo $this->form->time->setDimensional($this->itemIndex)->controll()?>&nbsp;
         délka:&nbsp;<?php echo $this->form->lenght->setDimensional($this->itemIndex)->controll()?>&nbsp;
         název:&nbsp;<?php echo $this->form->text->setDimensional($this->itemIndex)->controll()?>&nbsp;
         <span class="itemButtons">
            <a href="#" class="ui-icon ui-icon-closethick buttonRemove"></a>
         </span>
         <?php echo $this->form->type->setDimensional($this->itemIndex)->setValues('other')->controll()?>
         <hr class="reseter"/>
      </li>
      <?php 
      break;
   case "space":?>
      <?php // SPACE?>
      <li class="itemNote ui-widget-content ui-corner-top ui-corner-bottom">
         <span class="ui-icon ui-icon-arrowthick-2-n-s move"></span>
         <span class="itemLabel">Mezera</span>
         <span class="itemButtons">
            <a href="#" class="ui-icon ui-icon-closethick buttonRemove"></a>
         </span>
         <?php echo $this->form->type->setDimensional($this->itemIndex)->setValues('space')->controll()?>
         <hr class="reseter"/>
      </li>
      <?php 
      break;
   case "stage":?>
      <?php // STAGE?>
      <li class="itemStage ui-state-hover ui-corner-top ui-corner-bottom">
         <span class="ui-icon ui-icon-arrowthick-2-n-s move"></span>
         <span class="itemLabel">Stage</span>
         název:&nbsp;<?php echo $this->form->text->setDimensional($this->itemIndex)->controll()?>&nbsp;
         <span class="itemButtons">
            <a href="#" class="ui-icon ui-icon-closethick buttonRemove"></a>
         </span>
         <?php echo $this->form->type->setDimensional($this->itemIndex)->setValues('stage')->controll()?>
         <hr class="reseter"/>
      </li>
      <?php 
      break;
   default:?>
      <li class="ui-state-error">
         <strong><?php echo $this->_("Neplatný typ prvku programu!");?></strong>
      </li>
      <?php 
      break;
}
?>