<?php 
$this->addCssFile("style.less");
?>
<h1><?php ps($this->tr('Přehled podwebů')); ?></h1>
<div class="content content-admin">
   <?php
   $this->moduleButtons = array(
      array(
         'link' => $this->link()->route('add'),
         'title' => $this->tr('Vytvořit nový web'),
         'icon' => Template_Toolbox2::ICON_ADD,
         'name' => $this->tr('Nový web'),
      ),
   );
   $this->includeTpl('modules/buttons.phtml', true);
   ?>
   <?php 
   if(!empty($this->sites)){
      ?>
   <table class="cubecms-widget cubecms-table">
      <thead class="cubecms-header">
         <tr>
            <th><?php ps($this->tr('Adresa')); ?></th>
            <th><?php ps($this->tr('Složka')); ?></th>
            <th></th>
         </tr>
      </thead>
      <tbody>
      <?php foreach ($this->sites as $site) {?>
         <tr class="cubecms-row">
            <td><a href="http://<?php ps($site->getFullDomain()) ?>" class="link-external"><?php ps($site->getFullDomain()) ?></a></td>
            <td><?php ps($site->{Model_Sites::COLUMN_DIR}) ?></td>
            <td><?php echo $site->toolbox;?></td>
         </tr>
      <?php } ?>
      </tbody>
   </table>
      <?php
   } else {
      ?>
      <div class="admin-info-text"><?php ps($this->tr('Žádný podweb nebyl vytvořen')); ?></div>
      <?php
   }
   ?>
   <div class="admin-info-text"><?php ps($this->tr('Více domén může být přiřazeno jednomu adresáře.')); ?></div>
</div>