<?php 
$this->addCssFile("style.less");
?>
<h1><?php ps($this->tr('Přehled podwebů')); ?></h1>
<div class="content content-admin">
   <?php
   $this->moduleButtons = array(
      array(
         'link' => $this->link()->route('addSite'),
         'title' => $this->tr('Vytvořit nový web'),
         'icon' => Template_Toolbox2::ICON_ADD,
         'name' => $this->tr('Nový web'),
      ),
      array(
         'link' => $this->link()->route('addAlias'),
         'title' => $this->tr('Vytvořit nový alias'),
         'icon' => Template_Toolbox2::ICON_ADD,
         'name' => $this->tr('Nový alias'),
      ),
   );
   $this->includeTpl('modules/buttons.phtml', true);
   ?>
   <?php 
   if(!empty($this->sites)){
      $lastGroupId = 1;
      $groups = array();
      foreach ($this->sites as $site) {
         if(!isset($groups[$site->{Model_Sites::COLUMN_DIR}])){
            $groups[$site->{Model_Sites::COLUMN_DIR}] = $lastGroupId;
            $lastGroupId++;
         }
         $site->_grpID = $groups[$site->{Model_Sites::COLUMN_DIR}];
      }
      
      ?>
   <table class="cubecms-widget cubecms-table">
      <thead class="cubecms-header">
         <tr>
            <th><?php ps($this->tr('Adresa')); ?></th>
            <th><?php ps($this->tr('Složka')); ?></th>
            <th><?php ps($this->tr('Alias')); ?></th>
            <th></th>
         </tr>
      </thead>
      <tbody>
      <?php foreach ($this->sites as $site) {?>
         <tr class="cubecms-row">
            <td><a href="http://<?php ps($site->getFullDomain()) ?>" class="link-external"><?php ps($site->getFullDomain()) ?></a></td>
            <td>
               <?php ps($site->{Model_Sites::COLUMN_DIR}) ?>
               <span class="icon icon-circle site-group-color-<?php echo $site->_grpID?> "></span>
            </td>
            <td><?php ps($site->{Model_Sites::COLUMN_IS_ALIAS} ? $this->tr('Ano') : $this->tr('Ne')) ?></td>
            <td><?php echo $site->toolbox;?></td>
         </tr>
      <?php } ?>
      </tbody>
   </table>
      <?php
   } else {
      ?>
      <div class="admin-info-text"><?php ps($this->tr('Žádný podweb nebyl vytvořen')); ?></div>
      <?php
   }
   ?>
   <div class="admin-info-text"><?php 
   ps($this->tr('Více domén může být vytvořeno pomocí aliasu na jednu složku. Pro zprovoznění domén je také nutná úprava nastavení webhostingu či webserveru. Nutné je také upravit doménu, tak aby směřovala na webserver.'));
   ps(sprintf($this->tr('IP adresa serveru je %s'), $_SERVER['SERVER_ADDR'])); ?></div>
</div>