CREATE TABLE IF NOT EXISTS `{PREFIX}articles` (
  `id_article` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `id_cat` smallint(5) unsigned NOT NULL,
  `id_user` smallint(5) unsigned DEFAULT '1',
  `add_time` datetime NOT NULL,
  `edit_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_user_last_edit` smallint(6) DEFAULT NULL,
  `viewed` smallint(6) NOT NULL DEFAULT '0',
  `name_cs` varchar(400) DEFAULT NULL CHARACTER SET utf8 COLLATE utf8_czech_ci,
  `text_cs` text CHARACTER SET utf8 COLLATE utf8_czech_ci,
  `text_clear_cs` text CHARACTER SET utf8 COLLATE utf8_czech_ci,
  `urlkey_cs` varchar(100) DEFAULT NULL,
  `name_sk` varchar(400) CHARACTER SET utf8 COLLATE utf8_slovak_ci DEFAULT NULL,
  `text_sk` text CHARACTER SET utf8 COLLATE utf8_slovak_ci,
  `text_clear_sk` text CHARACTER SET utf8 COLLATE utf8_slovak_ci,
  `urlkey_sk` varchar(100) DEFAULT NULL,
  `name_en` varchar(400) DEFAULT NULL,
  `text_en` text,
  `text_clear_en` text,
  `urlkey_en` varchar(100) DEFAULT NULL,
  `name_de` varchar(400) DEFAULT NULL,
  `text_de` text,
  `text_clear_de` text,
  `urlkey_de` varchar(100) DEFAULT NULL,
  `public` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_article`),
  UNIQUE KEY `urlkey_cs` (`urlkey_cs`),
  UNIQUE KEY `urlkey_en` (`urlkey_en`),
  UNIQUE KEY `urlkey_de` (`urlkey_de`),
  FULLTEXT KEY `label_cs` (`name_cs`),
  FULLTEXT KEY `label_en` (`name_en`),
  FULLTEXT KEY `lebal_de` (`name_de`),
  FULLTEXT KEY `text_clear_cs` (`text_clear_cs`),
  FULLTEXT KEY `text_clear_en` (`text_clear_en`),
  FULLTEXT KEY `text_clear_de` (`text_clear_de`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;