<?if(isset($vars['lastEditTime'])) {
   if(($vars['lastEditTime'] instanceof DateTime) == false) {
      $vars['lastEditTime'] = new DateTime($vars['lastEditTime']);
   }?>
   <br />
   <p>
      <?=_('Naposled upraveno')?>&nbsp;<?=strftime("%x %X", $vars['lastEditTime']->format("U"))?>
<?if(isset($vars['lastEditUser'])) {?>
      &nbsp;<?=_('uživatelem')?>&nbsp;<span style="font-style: italic"><?=$vars['lastEditUser']?></span>
<?}?>
   </p>
<?}?>
<?if(isset($vars['linkToPdf']) OR isset($vars['linkToTxt'])) { ?>
   <br />
   <p>
<?if(isset($vars['linkToPdf'])) { ?>
   <?=_('Stáhnout')?>:&nbsp;<a href="<?=$vars['linkToPdf']?>" title="<?=_('Stáhnout')?> pdf">pdf</a>&nbsp;
<?}?>
<?if(isset($vars['linkToTxt'])) { ?>
   <?=_('Stáhnout')?>:&nbsp;<a href="<?=$vars['linkToTxt']?>" title="<?=_('Stáhnout')?> txt">txt</a>&nbsp;
<?}?>
   </p>
<?}?>

<?if(isset($vars['shares'])) {?>
   <br />
   <?=$vars['shares'] // sdílení?>
<?}?>
