<p>
<?=_('Sdílej')?>:
<?while ($service = $this->shares->fetch()) {?>
<a href="<?=str_replace($this->search, $this->replacement, $service->{Component_Share_Model::COLUM_LINK})?>"
   title="<?=$service->{Component_Share_Model::COLUM_NAME}?>">
         <?
         if(stripos($service->{Component_Share_Model::COLUM_ICON}, "http") !== false) {?>
   <img src="<?=$service->{Component_Share_Model::COLUM_ICON}?>" alt="<?=$service->{Component_Share_Model::COLUM_NAME}?> icon" width="16"/>
      <?} else {?>
   <img src="<?=vve_get_tpl_file($service->{Component_Share_Model::COLUM_ICON}, VVE_TPL_FILE_IMAGE)?>" alt="<?=$service->{Component_Share_Model::COLUM_NAME}?> icon" width="16" />
      <?}?>
</a>
<?}?>
</p>