<?
// do titulku
if($this->edit) {
   $h = sprintf($this->_('úprava osoby "%s"'),$this->person->{People_Model::COLUMN_NAME}.' '.$this->person->{People_Model::COLUMN_SURNAME});
} else {
   $h = $this->_('přidání osoby');
}
$this->addPageTitle($h);
// donastavení formuláře
$this->form->text->html()->setAttrib('cols', 80)->setAttrib('rows', 30);
$this->form->degree->html()->setAttrib('size', 5);

if(isset ($this->form->imgdel)){
   $this->form->imgdel->setSubLabel($this->_('Uložen portrét:').'<br /><img src="'.$this->category()->getModule()->getDataDir(true).$this->person->{People_Model::COLUMN_IMAGE}
   .'" alt="'.$this->person->{People_Model::COLUMN_IMAGE}.'" width="100" />');
}

?>
<h1><?=$h?></h1>
<div class="main-content-form-edit">
   <?
   echo($this->form);
   ?>
</div>
