<?
// do titulku
if($this->person) {
   $h = sprintf($this->tr('úprava osoby "%s"'),$this->person->{People_Model::COLUMN_NAME}.' '.$this->person->{People_Model::COLUMN_SURNAME});
} else {
   $h = $this->tr('přidání osoby');
}
$this->addPageTitle($h);
// donastavení formuláře
$this->form->text->html()->setAttrib('cols', 80)->setAttrib('rows', 30);
$this->form->degree->html()->setAttrib('size', 5);

if(isset ($this->form->imgdel)){
   $this->form->imgdel->setSubLabel($this->tr('Uložen portrét:').'<br /><img src="'.$this->category()->getModule()->getDataDir(true).$this->person->{People_Model::COLUMN_IMAGE}
   .'" alt="'.$this->person->{People_Model::COLUMN_IMAGE}.'" width="100" />');
}
?>
<h1><?=$h?></h1>
<div class="content-edit-form">
   <?
   echo($this->form);
   ?>
</div>
