<?php
echo $this->toolbox; // TOOLBOXY
//$this->addFile('css://style.less');
?>
<h1 class="text-center"><?php echo $this->category()->getName(true) ?></h1>
<div class="posts-list persons-list">
   <div class="row">
      <?php
      if (!empty($this->people)) {
         foreach ($this->people as $person) {
            ?>
            <div class="col-sm-6 autoheight">
               <div class="shortcut-hover shortcut-helper">
                  <?php if ($this->category()->getRights()->isWritable()) { ?>
                     <span class="shortcut shortcut-right"><?php ps('Kód pro vložení: ') ?><code>{PEOPLE:PERSON:<?php echo $person->getPK() ?>}</code></span>
                  <?php } 
                  
                  $this->includeFile('tpl://person.phtml', array('person' => $person));
                  ?>
               </div>
            </div>
            <?php
         }
      } else {
         echo ($this->tr('Není vložena žádná osoba'));
      }
      ?>
   </div>

   <?php
   if ($this->text instanceof Model_ORM_Record) {

      echo $this->filter($this->text);
   }
   ?>
</div>
<?php
echo $this->compScroll;
