<?php
/**
 * @template "Hlavní šablona"
 */
if($this->text != false AND (string)$this->text->{Text_Model::COLUMN_LABEL} != null) {
   $this->addPageTitle($this->text->{Text_Model::COLUMN_LABEL});
   $h1 = $this->text->{Text_Model::COLUMN_LABEL};
} else {
   $h1 = $this->category()->getName();
}
echo $this->toolbox;
?>
<h1><?php 
   echo $h1;
   echo $this->text ? Utils_CMS::getLangsImages($this->text->{Text_Model::COLUMN_TEXT}) : null;
   ?></h1>
<div class="content">
   <div class="text post">
      <?php 
      $this->includeFile('tpl://engine:components/titleimage.phtml'); 
      if($this->text && (string)$this->text->{Text_Model::COLUMN_TEXT_CLEAR} != null){
         echo ($this->filter($this->text->{Text_Model::COLUMN_TEXT},'emoticons'));
      } else if($this->category()->getRights()->isWritable()) {
         ?>
      <div class="admin-info-text"><?php printf($this->tr('Źádný text nebyl vyplněn. <a class="" href="%s">Upravit</a>.'), $this->link()->route('edit'));?></div>
         <?php
      }
      ?>
   </div>
   <?php if($this->textPrivate != false && (string)$this->textPrivate->{Text_Model::COLUMN_TEXT} != null){
      ?>
   <div class="main-content-text">
         <?php
            echo $this->textPrivate->{Text_Model::COLUMN_TEXT};
            echo $this->toolboxPrivate;
         ?>
      </div>
   <?php } ?>
</div>