<div class="productsList">
   <?
   if(!empty ($this->productsArray)){
   foreach ($this->productsArray as $product) {?>
   <div>
      <h2><a href="<?=$this->l()->article($product['label'], $product['id_product'])?>"
             title="<?=$product['label']?>"><?=$product['label']?>&nbsp;
          </a>
      </h2>
      <div class="imageBox">
         <?
//         var_dump($article);exit;
         if(isset($product['title_image'])){?>
            <?=imageTag($product['title_image'], "article title image", 80, 80);?>
         <?} else {?>
            <img src="images/icons/article_icon.png" alt="article title image" height="80" />
         <?}?>
      </div>
      <?//print (xhtml_cut(remove_tag('img', $article['text']), 650));?>
      <?print truncate(strip_tags($product['text']), 640);?>
      <p style="text-align:right;">
         <a href="<?=$this->l()->article($product['label'], $product['id_product'])?>"
         title="<?=$product['label']?>">[&nbsp;<?=$this->_m("více")?>&nbsp;]</a></p>
      <hr class="reseter" />
   </div>
   <?}}?>
   <br />
<?if($this->sys()->rights()->isWritable()){
   $this->includeTplObj($this->toolbox);
}?>
</div>
<?
$this->includeTplObj($this->EPLscroll);
?>