<?php 
$this->addPageTitle($this->tr('Chyba registrace'));
?>
<h1><?php echo $this->tr('Chyba registrace')?></h1>
<div class="main-content-text" id="userreg-reg-form">
   <?php 
   printf( $this->tr('Omlouvám se, ale Vaši registraci nelze dokončit. '
         .'Kontaktujte nás abychom sjednali nápravu, nebo se pokuste o novou <a href="%s">registraci</a>.'), 
         $this->link()->clear()->route() );
   ?>
</div>