<?
$jQ = new JsPlugin_JQuery();
$this->addJsPlugin($jQ);
echo $this->toolbox;
?>
<h1><?= $this->category()->getName() ?></h1>
<div class="main-content-text"><?
   if ($this->text != null) {
      echo $this->text;
   }
?></div>
<div class="main-content-form-edit" id="userreg-reg-form">
   <?
   echo $this->formReg;
   ?>
</div>
<script type="text/javascript">
   
   $(document).ready(function(){
	   
   function checkUserName() {
	   var $input = $('.regusername_class');
	   var userName = $input.val();
	   $loader.css('display' ,'inline');
	   $input.removeClass('form-error');
	   $.ajax({
		   type: "POST", url: "<?= $this->link()->route('checkUserName') ?>", cache: false,
		   data: {username: userName},
		   success: function(data){
            $status.html('&nbsp;');
            if(data.isFree == true){
               $status.append($('<img />').attr('src', 'images/icons/accept.png'));
            } else {
               $status.append($('<img />').attr('src', 'images/icons/exclamation.png'));
               $input.addClass('form-error');
            }
            $status.append('&nbsp;'+data.msg);
            $loader.css('display' ,'none');
         }
     });
  }
      var $loader = $('<span />').addClass('imput-loader').append('&nbsp;').css('display' ,'none');
      $loader.append($('<img />').attr('src', 'images/progress_small.gif'));
      var $status = $('<span />').addClass('username-status');
      $('.regusername_class').after($status).after($loader);

      $('.regusername_class').keyup(function(event){
    	  var userName = $(this).val();
         if(userName.length >= 5 && ((event.keyCode >= 48 && event.keyCode <= 90)
            || event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 116 || event.keyCode == 27 || event.keyCode == 16
            || event.keyCode == 37 || event.keyCode == 39 || event.keyCode == 109)
            || (event.keyCode < 48 || (event.keyCode > 90 && event.keyCode < 96) || event.keyCode > 105)){
            
        	   checkUserName();
         } else {
            return false;
         }
      });
      $('.regusername_class').change(function(){
    	   checkUserName();
    	   // pokud je e-mail přeřadit do mailu
    	   var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    	   var val = $('#regusername_1').val();
    	   if($('#regmail_1').val() == "" && re.test(val)){
    		   $('#regmail_1').val(val);
    	   }
      });

      if($('.regusername_class').val() != ""){
    	   checkUserName();
      }
      
   });
</script>