<?php
$this->addFile('css://style.less');
$this->addFile('js://engine:shop.js');
$piroBox = new JsPlugin_PrettyPhoto();
$this->addJsPlugin($piroBox);

$jQuery = new JsPlugin_JQuery();
$jQuery->addUISpinner();
$this->addJsPlugin($jQuery);

// do titulku
$this->addPageTitle($this->product->{Shop_Model_Product::COLUMN_NAME});
Template_Core::setPageKeywords($this->product->{Shop_Model_Product::COLUMN_KEYWORDS});
Template_Core::setPageDescription(strip_tags($this->product->{Shop_Model_Product::COLUMN_TEXT_SHORT}));
echo $this->toolbox;

// setup product
$this->includeFile('tpl://shopproductgeneral:detail_pre.phtml');
?>
<h1><?php
   echo $this->product->{Shop_Model_Product::COLUMN_NAME};
   echo strtotime($this->product->{Shop_Model_Product::COLUMN_IS_NEW_TO_DATE}) + (24 * 60 * 60) >= time() ? ' - ' . $this->tr('Novinka!') : null;
   echo!$this->product->{Shop_Model_Product::COLUMN_ACTIVE} ? ' - ' . $this->tr('neaktivní') : null;
   ?></h1>
<div class="row">
   <div class="col-sm-12">
      <div class="content">
         <div class="text">
            <?php echo $this->product->{Shop_Model_Product::COLUMN_TEXT_SHORT} ?>
         </div>
         <div class="row">
            <div class="col-sm-6">
               <?php if ($this->product->getTitleImage()) { ?>
                  <div class="title-image">
                     <?php
                     $imgSmall = Utils_Image::cache($this->product->getTitleImage()->getUrl(), 400);
                     ?>
                     <a href="<?php echo $this->product->getTitleImage()->getUrl() ?>"
                        rel="prettyPhoto[pr]" title="<?php ps($this->product->{Shop_Model_Product::COLUMN_NAME}) ?>">
                        <img class="img-responsive image" src="<?php echo $imgSmall ?>" alt="<?php echo $this->product->getTitleImage()->{Shop_Model_Product_Images::COLUMN_NAME} ?>"/>
                     </a>
                  </div>

                  <?php
               }

               $images = $this->product->getImages();
               foreach ($images as $img) {
                  $smallSrc = Utils_Image::cache($img->getUrl(), 80, 80, true);
                  ?>
                  <a href="<?php echo $img->getUrl() ?>" title="<?php ps($img->{Shop_Model_Product_Images::COLUMN_NAME}) ?>"
                     rel="prettyPhoto[pr]"
                     ><img src="<?php echo $smallSrc ?>" alt="<?php ps($img->{Shop_Model_Product_Images::COLUMN_NAME}) ?>" /></a>
                     <?php
                  }
                  ?>

            </div>
            <div class="col-sm-6">
               <div class="product-detail shop-product-attributes">
                  <?php if ($this->product->{Shop_Model_Product::COLUMN_CODE} != null) { ?>
                     <div class="attr-line clearfix">
                        <div class="left"><?php echo $this->tr('Kód') ?></div>
                        <div class="right product-code"><?php echo $this->productCode ?></div>
                     </div>
                  <?php } ?>
                  <div class="attr-line clearfix">
                     <div class="left"><?php echo $this->tr('Dostupnost') ?></div>
                     <div class="right product-qty"><?php
                        if ($this->productQty > 0 && $this->product->{Shop_Model_Product::COLUMN_STOCK}) {
                           printf($this->tr('Skladem %s %s'), $this->productQty, $this->product->{Shop_Model_Product::COLUMN_UNIT});
                        } else if ($this->productQty < 0 || !$this->product->{Shop_Model_Product::COLUMN_STOCK}) {
                           echo $this->tr('Skladem');
                        } else {
                           echo $this->tr('Vyprodáno (do 14 dní)');
                        }
                        ?>
                     </div>
                  </div>
                  <div class="attr-line clearfix">
                     <div class="left"><?php echo $this->tr('Váha') ?></div>
                     <div class="right product-weight"><?php
                        echo round($this->productWeight, 3) . " Kg";
                        ?></div>
                  </div>
                  <?php if ($this->product->{Shop_Model_Product::COLUMN_PERSONAL_PICKUP_ONLY} == true) { ?>
                     <div class="attr-line clearfix">
                        <div class="left"><?php echo $this->tr('Odběr') ?></div>
                        <div class="right"><?php echo $this->tr('Pouze osobní'); ?></div>
                     </div>
                  <?php } ?>
                  <?php
                  // render Combinations
                  ?>
                  <div class="attr-line clearfix">
                     <div class="left product-price-label"><?php echo $this->tr('Cena s daní') ?></div>
                     <div class="right product-price"><?php echo Shop_Tools::getFormatedPrice($this->productPrice, $this->product->{Shop_Model_Tax::COLUMN_VALUE}); ?></div>
                  </div>
                  <div class="attr-line clearfix">
                     <div class="left product-price-label"><?php echo $this->tr('Cena bez daně') ?></div>
                     <div class="right product-price-wout-tax"><?php echo Shop_Tools::getFormatedPrice($this->productPrice); ?></div>
                  </div>
                  <div id="product-buy-form">
                     <?php
                     if ($this->formAddToCart instanceof Form) {
                        echo $this->formAddToCart->renderStart();
                        $this->formAddToCart->productId->setValues($this->product->{Shop_Model_Product::COLUMN_ID});
                        $this->formAddToCart->qty->setValues($this->product->{Shop_Model_Product::COLUMN_UNIT_SIZE});
                        $this->formAddToCart->qty->html()->addClass('quantity');
                        // varianty
                        if ($this->productVariantsSelects) {
                           foreach ($this->productVariantsSelects as $name) {
                              echo '<div class="attr-line clearfix">';
                              $this->formAddToCart->$name->html()->addClass('select-variant');
                              echo $this->formAddToCart->$name->label() . "<br />";
                              echo $this->formAddToCart->$name->control();
                              echo '</div>';
                           }
                        }

                        echo '<div class="attr-line product-to-cart clearfix'
                        . (($this->productQty <= 0 && $this->product->{Shop_Model_Product::COLUMN_STOCK} && !VVE_SHOP_ALLOW_BUY_NOT_IN_STOCK) ? " hidden" : null) . '">';
                        echo '<div class="left">';
                        echo $this->formAddToCart->qty->label();
                        echo $this->formAddToCart->qty->control();
                        echo '&nbsp;' . $this->product->{Shop_Model_Product::COLUMN_UNIT} . '&nbsp;';
                        echo '</div><div class="right">';

                        echo $this->formAddToCart->productId->control();
                        echo $this->formAddToCart->add->control();
                        echo '</div>';
                        echo '</div>';
                        echo $this->formAddToCart->renderEnd();
                     }
                     ?>
                  </div>
               </div>
            </div>
         </div>
         <h2><?php echo $this->tr('Popis') ?></h2>
         <div class="main-content-text">
            <?php echo $this->product->{Shop_Model_Product::COLUMN_TEXT}; ?>
         </div>
         <?php
         // parametry
         $params = $this->product->getParams();
         if (!empty($params)) {
            ?>
            <h2><?php echo $this->tr('Parametry') ?></h2>
            <div class="product-params">
               <dl class="dl-horizontal">
                  <?php
                  foreach ($params as $param) {
                     ?>
                     <dt><?php ps($param->{Shop_Model_Product_Params::COLUMN_NAME}) ?><dt>
                     <dd><?php ps($param->{Shop_Model_Product_ParamsValues::COLUMN_VALUE}) ?></dd>
                     <?php
                  }
                  ?>
               </dl>
            </div>
            <?php
         }
         ?>
         <?php
         $this->includeTpl("buttonback.phtml", true, array('text' => $this->tr('Zpět na seznam zboží')));
         ?>
      </div>  
   </div>
</div>
<?php
$this->includeFile('tpl://shopproductgeneral:detail_scripts.phtml');
?>
<script type="text/javascript">
$(document).ready(function(){
   $("a[rel^='prettyPhoto']").prettyPhoto();
});
</script>