<?
//$jq = new JsPlugin_JQuery();
//$jq->addUIDatepicker();
//$this->addJsPlugin($jq);
// do titulku
if($this->edit) {
   $h = $this->tr('úprava produktu').' '.$this->product;
} else {
   $h = $this->tr('přidání produktu');
}
$this->addPageTitle($h);
// donastavení formuláře
$this->form->name->html()->setAttrib('size', 60)->addClass('form-element-long');
//$this->form->urlkey->html()->setAttrib('size', 60)->addClass('form-element-long');
//$this->form->metaKeywords->html()->setAttrib('size', 60)->addClass('form-element-long');
//$this->form->annotation->html()->setAttrib('cols', 58)->setAttrib('rows', 5);
//$this->form->metaDesc->html()->setAttrib('cols', 58)->setAttrib('rows', 3);
//$this->form->text->html()->setAttrib('cols', 58)->setAttrib('rows', 30);
// datepickery
//$this->form->created_date->html()->addClass('datepicker');
?>
<h1><?=$h;?></h1>
<div class="main-content-form-edit" id="article-edit-form">
   <?echo($this->form);?>
</div>
