<?php 
$this->addFile('css://style.css');
//$jQuery = new JsPlugin_JQuery();
//$jQuery->addUISpinner();
//$this->addJsPlugin($jQuery);

echo $this->toolbox;
?>
<h1><?php 
echo $this->category()->getName();
?></h1>
<div class="main-content-list">
   <?php 
   if(!empty($this->products)){
      $this->includeFile('tpl://shopproductgeneral:sorting.phtml');
      foreach ($this->products as $product) {
         $link = $this->link();
         if(isset($product->{Model_Category::COLUMN_URLKEY})){
            $link->category($product->{Model_Category::COLUMN_URLKEY});
         }
         $link->route('detail', array('urlkey' => $product->{Shop_Model_Product::COLUMN_URLKEY}))

         ?>
   <div class="main-content-list-record shop-product <?if(!$product->{Shop_Model_Product::COLUMN_ACTIVE}) echo "concept";?> clearfix">
      <h2><a href="<?php echo $link?>" title="<?php echo $this->tr('Přejít na ').$product->{Shop_Model_Product::COLUMN_NAME}?>"><?
             echo $product->{Shop_Model_Product::COLUMN_NAME};
             echo strtotime($product->{Shop_Model_Product::COLUMN_IS_NEW_TO_DATE})+(24*60*60) >= time() ? ' - '.$this->tr('Novinka!') : null;
             ?></a>
      <?php echo $product->{Shop_Model_Product::COLUMN_ACTIVE} ? null : ' - '.$this->tr('neaktivní')?>
      </h2>
      <?php if($product->{Shop_Model_Product::COLUMN_IMAGE} != null){?>
      <div class="main-content-list-record-image">
         <img src="<?php echo Shop_Product_Controller::getImagesDir(true).'small/'.$product->{Shop_Model_Product::COLUMN_IMAGE}?>" 
              alt="<?php echo $product->{Shop_Model_Product::COLUMN_NAME}?>" />
      </div>
      <?php }?>
      <div class="main-content-list-record-text">
         <?php echo $product->{Shop_Model_Product::COLUMN_TEXT_SHORT}?>
      </div>
      <div class="main-content-list-record-text shop-product-attributes">
         <div class="product-price">
            <?php 
            echo $this->tr('Cena').': ';
            echo Shop_Tools::getFormatedPrice($product->{Shop_Model_Product::COLUMN_PRICE}, $product->{Shop_Model_Tax::COLUMN_VALUE});
            ?>
         </div>
      <?php 
      $qty = $product->{Shop_Model_ProductCombinations::COLUMN_QTY} != null ?
         (int)$product->{Shop_Model_ProductCombinations::COLUMN_QTY} : (int)$product->{Shop_Model_Product::COLUMN_QUANTITY};
      if($this->formAddToCart instanceof Form
         && ( ($product->{Shop_Model_Product::COLUMN_STOCK} && $qty > 0)
               || (!$product->{Shop_Model_Product::COLUMN_STOCK})
               || VVE_SHOP_ALLOW_BUY_NOT_IN_STOCK)
      ){
         echo $this->formAddToCart->renderStart();
         $this->formAddToCart->productId->setValues($product->{Shop_Model_Product::COLUMN_ID});
         $this->formAddToCart->qty->setValues($product->{Shop_Model_Product::COLUMN_UNIT_SIZE});
         $this->formAddToCart->qty->html()->addClass('quantity');
         
         echo $this->formAddToCart->qty->label();
         echo $this->formAddToCart->qty->controll();
         echo '&nbsp;'.$product->{Shop_Model_Product::COLUMN_UNIT}.'&nbsp;';
         echo $this->formAddToCart->productId->controll();
         echo $this->formAddToCart->add->controll();
         
         echo $this->formAddToCart->renderEnd();
      } else if($product->{Shop_Model_ProductCombinations::COLUMN_ID} != null) {
         echo $this->tr('Zboží v této variantě je vyprodáno. Zkuste vybrat jinout variantu.');
      } else {
         echo $this->tr('Zboží je vyprodáno.');
      }
      ?>
      </div>
   </div>
   <script type="text/javascript">
   </script>
   <hr class="reseter" />
      <?php }
      echo $this->scrollComp;
   } else {?>
   <div class="main-content-text"><?php echo $this->tr('Žádné zboží nebylo nalezeno')?></div>
   <?php }?>
</div>
