<?php
$this->addFile('css://shopproductgeneral:style.less');
?>
<?php
if (!empty($this->products)) {
   $this->includeFile('tpl://shopproductgeneral:sorting.phtml');
   ?>
   <div class="row">
      <?php
      foreach ($this->products as $product) {
         $link = $this->link();
         if (isset($product->{Model_Category::COLUMN_URLKEY})) {
            $link->category($product->{Model_Category::COLUMN_URLKEY});
         }
         $link->route('detail', array('urlkey' => $product->{Shop_Model_Product::COLUMN_URLKEY}))
         ?>
         <div class="col-sm-4">
            <div class="main-content-list-record shop-product <?php if (!$product->{Shop_Model_Product::COLUMN_ACTIVE}) echo "concept"; ?> clearfix">
               <div class="aut-height">
                  <h2><a href="<?php echo $link ?>" title="<?php echo $this->tr('Přejít na ') . $product->{Shop_Model_Product::COLUMN_NAME} ?>"><?php
      echo $product->{Shop_Model_Product::COLUMN_NAME};
      echo strtotime($product->{Shop_Model_Product::COLUMN_IS_NEW_TO_DATE}) + (24 * 60 * 60) >= time() ? ' - ' . $this->tr('Novinka!') : null;
         ?></a>
                        <?php echo $product->{Shop_Model_Product::COLUMN_ACTIVE} ? null : ' - ' . $this->tr('neaktivní') ?>
                  </h2>
               </div>
               <?php
               if ($product->getTitleImage() != null) {
                  $src = Utils_Image::cache($product->getTitleImage()->getUrl(), 400, round(400 / 4 * 3), true);
                  ?>
                  <div class="main-content-list-record-image">
                     <img class="img-responsive" src="<?php echo $src ?>" 
                          alt="<?php echo $product->{Shop_Model_Product::COLUMN_NAME} ?>" />
                  </div>
               <?php } ?>
               <div class="main-content-list-record-text">
                  <?php echo Utils_String::truncate($product->{Shop_Model_Product::COLUMN_TEXT_SHORT}, 100) ?>
               </div>
               <div class="main-content-list-record-text shop-product-attributes">
                  <div class="product-price">
                     <?php
                     echo $this->tr('Cena') . ': ';
                     echo Shop_Tools::getFormatedPrice($product->{Shop_Model_Product::COLUMN_PRICE}, $product->{Shop_Model_Tax::COLUMN_VALUE});
                     ?>
                  </div>
                  <?php
                  $qty = $product->{Shop_Model_Product_Combinations::COLUMN_QTY} != null ?
                          (int) $product->{Shop_Model_Product_Combinations::COLUMN_QTY} : (int) $product->{Shop_Model_Product::COLUMN_QUANTITY};
                  if ($this->formAddToCart instanceof Form && ( ($product->{Shop_Model_Product::COLUMN_STOCK} && $qty > 0) || (!$product->{Shop_Model_Product::COLUMN_STOCK}) || VVE_SHOP_ALLOW_BUY_NOT_IN_STOCK)
                  ) {
                     echo $this->formAddToCart->renderStart();
                     $this->formAddToCart->productId->setValues($product->{Shop_Model_Product::COLUMN_ID});
                     $this->formAddToCart->qty->setValues($product->{Shop_Model_Product::COLUMN_UNIT_SIZE});
                     $this->formAddToCart->qty->html()->addClass('quantity');

                     echo $this->formAddToCart->qty->label();
                     echo $this->formAddToCart->qty->controll();
                     echo '&nbsp;' . $product->{Shop_Model_Product::COLUMN_UNIT} . '&nbsp;';
                     echo $this->formAddToCart->productId->controll();
                     echo '<div class="to-cart">';
                     echo $this->formAddToCart->add->controll();
                     echo '</div>';
                     echo $this->formAddToCart->renderEnd();
                  } else if ($product->{Shop_Model_Product_Combinations::COLUMN_ID} != null) {
                     echo $this->tr('Zboží v této variantě je vyprodáno. Zkuste vybrat jinout variantu.');
                  } else {
                     echo $this->tr('Zboží je vyprodáno.');
                  }
                  ?>
               </div>
            </div>
         </div>
         <?php
      }
      ?>
   </div>
   <?php
   echo $this->scrollComp;
} else {
   ?>
   <div class="main-content-text"><?php echo $this->tr('Žádné zboží nebylo nalezeno') ?></div>
<?php
} 
