<div>
<?
// do titulku
if($this->edit === true){
   $this->addPageTitle($this->_('úprava navigačního odkazu'));
   $this->addPageTitle($this->name);
   $this->addPageHeadline($this->_('úprava navigačního odkazu'));
   $this->addPageHeadline($this->name);
} else {
   $this->addPageTitle($this->_('přidání navigačního odkazu'));
   $this->addPageHeadline($this->_('přidání navigačního odkazu'));
}
?>

<?=$this->form?>

<script type="text/javascript">
   /* <![CDATA[ */
   /* ]]> */
</script>

<?=$this->includeTpl('buttonback.phtml', true, array('link' => $this->link()->clear()))?>
</div>