<?
$model = new NavigationMenu_Models_List();
$listSubdomains = $model->getSubdomainsList()->fetchAll();
$listProjects = $model->getProjectsList()->fetchAll();

?>
<div class="navigationMenu">
   <?if(!empty ($listSubdomains)){?>
   <ul id="subdomains">
      <?//while ($row = $listSubdomains->fetch()) {?>
      <?foreach ($listSubdomains as $row) {?>
      <li>
         <a href="<?=$row->{NavigationMenu_Models_List::COL_URL}?>"
            title="<?=$row->{NavigationMenu_Models_List::COL_NAME}?>">
            <?
            if($row->{NavigationMenu_Models_List::COL_ICON} != null) {?>
         <img src="<?=Url_Request::getBaseWebDir().VVE_DATA_DIR.URL_SEPARATOR.$this->getModuleName()
               .URL_SEPARATOR.$row->{NavigationMenu_Models_List::COL_ICON}?>"
              alt="<?=$row->{NavigationMenu_Models_List::COL_ICON}?> icon" />
                 <?}?>
         <?=$row->{NavigationMenu_Models_List::COL_NAME}?></a>
      </li>
      <?}?>
   </ul>
   <?}?>
   <?if(!empty ($listProjects)){?>
   <ul id="projects">
      <?foreach ($listProjects as $row) {?>
      <li>
         <a href="<?=$row->{NavigationMenu_Models_List::COL_URL}?>"
            title="<?=$row->{NavigationMenu_Models_List::COL_NAME}?>">
            <?
            if($row->{NavigationMenu_Models_List::COL_ICON} != null) {?>
         <img src="<?=Url_Request::getBaseWebDir().VVE_DATA_DIR.URL_SEPARATOR.$this->getModuleName()
               .URL_SEPARATOR.$row->{NavigationMenu_Models_List::COL_ICON}?>"
              alt="<?=$row->{NavigationMenu_Models_List::COL_ICON}?> icon" />
                 <?}?>
         <?=$row->{NavigationMenu_Models_List::COL_NAME}?></a>
      </li>
      <?}?>
   </ul>
   <?}?>
   <hr class="reseter" />
</div>