<?php 
$model = new NavigationMenu_Models_List();
$listSubdomains = $model->getSubdomainsList()->fetchAll();
$listProjects = $model->getProjectsList()->fetchAll();

?>
<div class="navigationMenu">
   <?php if(!empty ($listSubdomains)){?>
   <ul id="subdomains">
      <?php //while ($row = $listSubdomains->fetch()) {?>
      <?php foreach ($listSubdomains as $row) {?>
      <li>
         <a href="<?php echo $row->{NavigationMenu_Models_List::COL_URL}?>"
            title="<?php echo $row->{NavigationMenu_Models_List::COL_NAME}?>" <?php if($row->{NavigationMenu_Models_List::COL_FOLLOW} == false){echo 'rel="nofollow"';}?> 
            <?php if($row->{NavigationMenu_Models_List::COL_NEW_WIN} == true){echo 'class="link-external"';}?>>
            <?php 
            if($row->{NavigationMenu_Models_List::COL_ICON} != null) {?>
         <img src="<?php echo Url_Request::getBaseWebDir().VVE_DATA_DIR.URL_SEPARATOR.$this->getModuleName()
               .URL_SEPARATOR.$row->{NavigationMenu_Models_List::COL_ICON}?>"
              alt="<?php echo $row->{NavigationMenu_Models_List::COL_ICON}?> icon" />
                 <?php }?>
         <?php echo $row->{NavigationMenu_Models_List::COL_NAME}?></a>
      </li>
      <?php }?>
   </ul>
   <?php }?>
   <?php if(!empty ($listProjects)){?>
   <ul id="projects">
      <?php foreach ($listProjects as $row) {?>
      <li>
         <a href="<?php echo $row->{NavigationMenu_Models_List::COL_URL}?>"
            title="<?php echo $row->{NavigationMenu_Models_List::COL_NAME}?>" <?php if($row->{NavigationMenu_Models_List::COL_FOLLOW} == false){echo 'rel="nofollow"';}?> 
            <?php if($row->{NavigationMenu_Models_List::COL_NEW_WIN} == true){echo 'class="link-external"';}?>>
            <?php 
            if($row->{NavigationMenu_Models_List::COL_ICON} != null) {?>
         <img src="<?php echo Url_Request::getBaseWebDir().VVE_DATA_DIR.URL_SEPARATOR.$this->getModuleName()
               .URL_SEPARATOR.$row->{NavigationMenu_Models_List::COL_ICON}?>"
              alt="<?php echo $row->{NavigationMenu_Models_List::COL_ICON}?> icon" />
                 <?php }?>
         <?php echo $row->{NavigationMenu_Models_List::COL_NAME}?></a>
      </li>
      <?php }?>
   </ul>
   <?php }?>
   <hr class="reseter" />
</div>