<?php //<desc>Panel zobrazuje seznam podstránek</desc>
$icon = null;
if($this->panelObj()->getIcon() != null) {
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null) {
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
?>
<p class="panelLabel"><?php echo $icon?><a href="<?php echo $this->link()?>" title="<?php echo htmlspecialchars($this->panelObj()->getName())?>"><?php echo $this->panelObj()->getName()?></a></p>
<div style="<?php echo $backImg?>">
   <?php 
   $prev = null;
   foreach ($this->links as $link) {
      if($link->{NavigationMenu_Models_List::COL_TYPE} != $prev) {
         if($prev !== null) print "<br />";
         $prev = $link->{NavigationMenu_Models_List::COL_TYPE};
         switch ($prev) {
            case 'subdomain':
               print ("<span>".$this->_('Podstránky')."<span><br />");
               break;
            case 'project':
               print ("<span>".$this->_('Projekty')."<span><br />");
               break;
            case 'group':
               print ("<span>".$this->_('Skupiny')."<span><br />");
               break;
            case 'partner':
               print ("<span>".$this->_('Partneři')."<span><br />");
               break;
         }
      }
      $params = null;
      if($link->{NavigationMenu_Models_List::COL_URL} == true) $params = ' rel="nofollow"';
      if($link->{NavigationMenu_Models_List::COL_NEW_WIN} == true) $params .= ' class="linkNewWin" onclick="return ! window.open(this.href);"';
      ?>
   <a href="<?php echo $link->{NavigationMenu_Models_List::COL_URL}?>"
      title="<?php echo htmlspecialchars($link->{NavigationMenu_Models_List::COL_NAME})?>"<?php echo $params?>>
      <?php if($link->{NavigationMenu_Models_List::COL_ICON} != null){?>
      <img src="<?php echo Url_Request::getBaseWebDir().VVE_DATA_DIR.URL_SEPARATOR.NavigationMenu_Controller::ICONS_DIR
                      .URL_SEPARATOR.$link->{NavigationMenu_Models_List::COL_ICON}?>"
           alt="icon <?php echo htmlspecialchars($link->{NavigationMenu_Models_List::COL_NAME})?>" />
      <?php }?>
         <?php echo vve_tpl_truncate($link->{NavigationMenu_Models_List::COL_NAME},25)?></a>
   <br />
      <?php 
   }
   ?>
</div>
<p class="panelLinkMore">
   <a href="<?php echo $this->link()?>"
      title="<?php echo htmlspecialchars($this->category()->getLabel())?>"><?php echo $this->_('Více')?></a>
</p>