<?//<desc>Panel zobrazuje seznam projektů</desc>
$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
?>
<p class="panelLabel"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->panelObj()->getName())?>"><?=$this->panelObj()->getName()?></a></p>
<span class="panelSubLabel"><?=$this->_('Projekty')?></span>
<div style="<?=$backImg?>">
   <?foreach ($this->links as $link) {
      $params = null;
      if($link->{NavigationMenu_Models_List::COL_URL} == true) $params = ' rel="nofollow"';
      if($link->{NavigationMenu_Models_List::COL_NEW_WIN} == true) $params .= ' class="linkNewWin" onclick="return ! window.open(this.href);"';
      ?>
   <a href="<?=$link->{NavigationMenu_Models_List::COL_URL}?>"
      title="<?=htmlspecialchars($link->{NavigationMenu_Models_List::COL_NAME})?>"<?=$params?>>
   <?if($link->{NavigationMenu_Models_List::COL_ICON} != null){?>
      <img src="<?=Url_Request::getBaseWebDir().VVE_DATA_DIR.URL_SEPARATOR.NavigationMenu_Controller::ICONS_DIR
               .URL_SEPARATOR.$link->{NavigationMenu_Models_List::COL_ICON}?>"
           alt="icon <?=htmlspecialchars($link->{NavigationMenu_Models_List::COL_NAME})?>" />
      <?}?>
      <?=vve_tpl_truncate($link->{NavigationMenu_Models_List::COL_NAME},25)?></a>
   <br />
   <?
   }
   ?>
</div>
<p class="panelLinkMore">
   <a href="<?=$this->link()?>"
      title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->_('Více')?></a>
</p>