<h2><?=$this->_("Přidání emailu")?></h2>
<form action="<?=$this->l()?>" method="post">
   <input name="kontform_mail_mail" type="text" size="30" value="<?=$this->post($_POST["kontform_mail_mail"])?>" />
   <input name="kontform_mail_send" type="submit" value="<?=$this->_("Přidat")?>" />
</form>
<br />
<br />
<?if($this->mails->rowCount() > 0){?>
<h2><?=$this->_("Uložené emaily")?></h2>
<table>
   <tr>
      <th width="150"><?=$this->_("email")?></th>
      <th width="100"><?=$this->_("akce")?></th>
   </tr>
<?foreach ($this->mails as $mail) {?>
   <tr>
      <td><?=$mail[Kontform_Model_Mails::COLUMN_EMAIL]?></td>
      <td>
         <form method="post" action="<?=$this->l()?>" onsubmit="return (confirm('<?=$this->_("Opravdu smazat email?")?>'));">
            <input type="hidden" name="kontform_mail_id" value="<?=$mail[Kontform_Model_Mails::COLUMN_ID]?>" />
            <input type="submit" name="kontform_mail_delete" value="<?=$this->_("smazat")?>" />
         </form>
      </td>
   </tr>
<?}?>
</table>
<?}?>
<?$this->includeTpl("buttonback.phtml", true, array('link' => $this->l()->action()));?>