<?
// do titulku
if($this->edit) {
   $h = $this->tr('úprava ankety').' '.$this->name;
} else {
   $h = $this->tr('přidání ankety');
}
$this->addPageTitle($h);

?>
<h1><?=$h;?></h1>
<div class="main-content-form-edit" id="article-edit-form">
   <?=$this->form->renderStart()?>
      <fieldset>
         <table id="answerForm"  class="form-table">
            <tr>
               <th class="form-labels">
                  <?=$this->form->question->label();?>
               </th>
               <td class="form-controlls">
                  <?=$this->form->question->controllAll();?>
                  <span></span>
               </td>
            </tr>
            <tr>
               <th class="form-labels">
                  <?=$this->form->multianswer->label();?>
               </th>
               <td class="form-controlls">
                  <?=$this->form->multianswer->controllAll();?>
                  <span></span>
               </td>
            </tr>
            <tr>
               <th class="form-labels">
                  <?=$this->form->active->label();?>
               </th>
               <td class="form-controlls">
                  <?=$this->form->active->controllAll();?>
                  <span></span>
               </td>
            </tr>
            <?if(isset($this->form->clear)){?>
            <tr>
               <th class="form-labels">
                  <?=$this->form->clear->label();?>
               </th>
               <td class="form-controlls">
                  <?=$this->form->clear->controllAll();?>
                  <span></span>
               </td>
            </tr>
            <?}
            $vals = $this->form->answer->getValues();
            if(count($vals) == 0) {
               $vals = array(0,1);
            };
            foreach ($vals as $i => $val) {
               $this->form->answer->setDimensional($i);
               $this->form->answerCount->setDimensional($i);
               ?>
            <tr id="pollAnswer_<?=$i?>" class="pollAnswer">
               <th class="form-labels">
                  <?echo($this->form->answer->label())?>
               </th>
               <td class="form-controlls">
                     <?
                     $this->form->answer->html()->setAttrib('size', 20);
                     echo($this->form->answer->controll());
                     
                     echo($this->form->answerCount->label());
                     $this->form->answerCount->html()->setAttrib('size', 5)->addClass('mini');
                     echo($this->form->answerCount->controll());
                  ?>
                  <a href="<?=$this->link()?>#delete-row" onclick="return deleteAnswerRow(this);" title="<?=$this->tr('Odstranit řádek')?>"
                     class="form-row-action-icon"><img src="<?=vve_get_tpl_file('icons/delete.png', VVE_TPL_FILE_IMAGE)?>" alt="delete" /></a>
               </td>
            </tr>
            <?}?>
            <tr>
               <td></td>
               <td>
                  <a class="form-row-action-icon" href="<?=$this->link()?>#add-row" onclick="return addAnswerRow();" title="<?=$this->tr('Přidat odpověď')?>">
                     <img src="<?=vve_get_tpl_file('icons/add.png', VVE_TPL_FILE_IMAGE)?>" alt="add" />&nbsp;<?=$this->tr('Přidat odpověď')?>
                  </a>
               </td>
            </tr>
            <tr>
               <th class="form-labels"></th>
               <td class="form-controlls">
                  <?=$this->form->send->controllAll();?>
                  <span></span>
               </td>
            </tr>
         </table>
      </fieldset>
   <?=$this->form->renderEnd()?>
   <script type="text/javascript">
      /* <![CDATA[ */
      function addAnswerRow(){
         var row = $('#answerForm tr.pollAnswer:last').clone();
         row.show();
         var id = parseInt(row.attr('id').match(/pollAnswer_([0-9]+)/)[1])+1;
         row.attr('id', 'pollAnswer_'+id);
         
         row.find('input').each(function(){
            $(this).attr('name', $(this).attr('name').toString().replace(id-1, id) );
            $(this).attr('id', $(this).attr('id').toString().replace(id-1, id) );
            $(this).val("");
         });
         row.find('label').each(function(){
            $(this).attr('for', $(this).attr('for').toString().replace(id-1, id) );
         });
         $('#answerForm tr.pollAnswer:last').after(row);
         return false;
      }
      // odstranění položky
      function deleteAnswerRow(obj){
         if($('.pollAnswer').length == 1){//pokud je jeden nemažese
            return false;
         }
         // první nelze vymazat
         $(obj).parent().parent().remove();
         return false;
      }
      /* ]]> */
   </script>
</div>
