<div>
   <!--<form action="<?$this->form->getAction()?>" method="post">-->
   <?=$this->form->renderStart()?>
      <fieldset>
         <table id="answerForm" class="formTableGroup">
            <tr>
               <th class="formLabels">
                  <?=$this->form->question->label();?>
               </th>
               <td class="formControlls">
                  <?=$this->form->question->controllAll();?>
                  <span></span>
               </td>
            </tr>
            <tr>
               <th class="formLabels">
                  <?=$this->form->multianswer->label();?>
               </th>
               <td class="formControlls">
                  <?=$this->form->multianswer->controllAll();?>
                  <span></span>
               </td>
            </tr>
            <tr>
               <th class="formLabels">
                  <?=$this->form->active->label();?>
               </th>
               <td class="formControlls">
                  <?=$this->form->active->controllAll();?>
                  <span></span>
               </td>
            </tr>
            <?if(isset($this->form->clear)){?>
            <tr>
               <th class="formLabels">
                  <?=$this->form->clear->label();?>
               </th>
               <td class="formControlls">
                  <?=$this->form->clear->controllAll();?>
                  <span></span>
               </td>
            </tr>
            <?}
            $vals = $this->form->answer->getValues();
            if(count($vals) == 0) {
               $vals = array(0,1);
            };
            foreach ($vals as $i => $val) {
               $this->form->answer->setDimensional($i);?>
            <tr id="pollAnswer_<?=$i?>" class="pollAnswer">
               <th class="formLabels">
                  <?print($this->form->answer->label())?>
               </th>
               <td class="formControlls">
                     <?
                     $this->form->answer->html()->setAttrib('size', 20);
                     print($this->form->answer->controll());
                     // hidden
//                     $this->form->dateDeleted->setDimensional($i);
//                     $this->form->dateDeleted->setValues('false');
//                     print($this->form->dateDeleted->controll());
                  ?>
                  <a href="#" onclick="return deleteAnswerRow(this);" title="<?=$this->_('Odstranit řádek')?>">
                     <img src="<?=vve_get_tpl_file('icons/delete.png', VVE_TPL_FILE_IMAGE)?>" alt="delete" />
                  </a>
               </td>
            </tr>
            <?}?>
            <tr>
               <td colspan="2">
                  <a href="#" onclick="return addAnswerRow();" title="<?=$this->_('Přidat odpověď')?>"><?=$this->_('Přidat odpověď')?></a>
               </td>
            </tr>
            <tr>
               <th class="formLabels"></th>
               <td class="formControlls">
                  <?=$this->form->send->controllAll();?>
                  <span></span>
               </td>
            </tr>
         </table>
      </fieldset>
   <?=$this->form->renderEnd()?>
   <script type="text/javascript">
      /* <![CDATA[ */
      function addAnswerRow(){
         var row = $('#answerForm tr.pollAnswer:last').clone();
         row.show();
         var id = parseInt(row.find('input.poll_answer_class').attr('id').match(/poll_answer_([0-9]+)/)[1])+1;
         
         row.attr('id', 'pollAnswer_'+id);
         row.find('input.poll_answer_class').attr('name','poll_answer['+id+']');
         row.find('input.poll_answer_class').attr('id','poll_answer_'+id);
         row.find('label').removeClass('poll_answer_'+(id-1)+'_label_class').addClass('poll_answer_'+id+'_label_class').attr('for','poll_answer_'+id);
         $('#answerForm tr.pollAnswer:last').after(row);
         return false;
      }
      // odstranění položky
      function deleteAnswerRow(obj){
         if($('.pollAnswer').length == 1){//pokud je jeden nemažese
            return false;
         }
         // první nelze vymazat
         $(obj).parent().parent().remove();
         return false;
      }
      /* ]]> */
   </script>
   <?=$this->includeTpl('buttonback.phtml', true)?>
</div>
