<?
$icon = null;
if($this->panelObj()->getIcon() != null) {
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null) {
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
?>
<p class="panelLabel"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->panelObj()->getName())?>"><?=$this->panelObj()->getName()?></a></p>
<div class="panelText" style="<?=$backImg?>">
   <p>
      <?=$this->poll->{Polls_Model_Detail::COL_QUESTION}?>
   </p>
   <div>
      <?
      if ($this->formmulti != null) {
      // více možností
         $this->formmulti->html()->addClass('pollVoteForm');
         $pollTpl = new Template_Module($this->link(), $this->category());
         $pollTpl->addTplFile('poll_multi.phtml');
         $pollTpl->formmulti = $this->formmulti;
         $pollTpl->poll = $this->poll;
         echo ($pollTpl);
      } else if($this->formsingle != null) {
         // jedna možnost
         $this->formsingle->html()->addClass('pollVoteForm');
         $pollTpl = new Template_Module($this->link(), $this->category());
         $pollTpl->addTplFile('poll_single.phtml');
         $pollTpl->formsingle = $this->formsingle;
         $pollTpl->poll = $this->poll;
         echo ($pollTpl);
      } else {
         // jenom, zobrazení
         $pollTpl = new Template_Module($this->link(), $this->category());
         $pollTpl->addTplFile('poll_read.phtml');
         $pollTpl->poll = $this->poll;
         echo ($pollTpl);
      }?>
   </div>
</div>
<?
// vložení skriptu pro ajax
$this->includeTpl('voteScript.phtml');
?>
<p class="panelLinkMore">
   <a href="<?=$this->link()?>"
      title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->_('Více')?></a>
</p>