<?
$this->addFile("css://style.css");
$h1 = $this->category()->getName();
echo $this->toolbox;
?>
<h1><?$this->includeFile('tpl://engine:headline/icon.phtml'); echo $h1;?></h1>
<div class="main-content-list">
   <div class="main-content-list-records">
   <?
   if(!empty ($this->polls)){
   foreach ($this->polls as $poll) {
   ?>
   <div class="main-content-list-record">
   <h2><?=$poll->{Polls_Model::COLUMN_QUESTION}?></h2>
      <div style="position: relative" id="poll_<?=$poll->{Polls_Model::COLUMN_ID}?>">
         <?if($poll->{Polls_Model::COLUMN_ACTIVE} == true AND !isset ($this->votedPolls[$poll->{Polls_Model::COLUMN_ID}])) {
            // více možností
            if ($poll->{Polls_Model::COLUMN_IS_MULTI} == true) {
               $this->formmulti->html()->addClass('pollVoteForm');
               // více možností
               $pollTpl = new Template_Module($this->link(), $this->category());
               $pollTpl->addTplFile('poll_multi.phtml');
               $pollTpl->formmulti = $this->formmulti;
               $pollTpl->poll = $poll;
               echo ($pollTpl);
            } else {
               // jedna možnost
               $this->formsingle->html()->addClass('pollVoteForm');
               $pollTpl = new Template_Module($this->link(), $this->category());
               $pollTpl->addTplFile('poll_single.phtml');
               $pollTpl->formsingle = $this->formsingle;
               $pollTpl->poll = $poll;
               echo ($pollTpl);
            }
         } else {
            // jenom, zobrazení?>
            <?
            $pollTpl = new Template_Module($this->link(), $this->category());
            $pollTpl->addTplFile('poll_read.phtml');
            $pollTpl->poll = $poll;
            echo ($pollTpl);
         }
         ?>
      </div>
      <?
      if($this->toolboxPoll instanceof Template_Toolbox2){
         $this->toolboxPoll->poll_edit->setAction($this->link()->route('edit', array('id' => $poll->{Polls_Model::COLUMN_ID})));
         echo $this->toolboxPoll;
      }
      ?>
   </div>
      <?
   }
   echo $this->scrollComp; // skrolery
      $jQuery = new JsPlugin_JQuery();
      $this->addJsPlugin($jQuery);
      // vložení skriptu pro ajax
      $this->includeTpl('voteScript.phtml');
   } else {?>
   <p><?=$this->_('Žádná anketa není vložena')?></p>
   <?}?>
</div>
</div>
