<?// vypočty
$data = unserialize($this->poll->{Polls_Model_Detail::COL_DATA});
$maxVote = 0;
$allVotes = 0;
foreach ($data as $key => $vote) {
   if($vote['count'] > $maxVote) $maxVote = $vote['count'];
   $allVotes += $vote['count'];
}
print($this->formsingle->renderStart());// SOF form?>
<div>
   <?foreach ($data as $key => $answer) {
      $maxVote == 0 ? $prRender = 0 : $prRender = round(($answer['count']/($maxVote/100)*0.9));
      $percent = $allVotes/100;
      $percent == 0 ? $pr = 0 : $pr = round($answer['count']/$percent);
      ?>
   <input name="vote_answer" id="vote_answer_<?=$this->poll->{Polls_Model_Detail::COL_ID}."_".$key?>" value="<?=$key?>"
          type="radio" <?if($key == 0)print('checked="checked"')?> />
   <label for="vote_answer_<?=$this->poll->{Polls_Model_Detail::COL_ID}."_".$key?>"><?=$answer['answer']?></label>
   <br />
   <p class="pollGraph pollAnswer_<?=$key?>" style="width: <?=$prRender?>%;">
      <span class="pollNumbers"><?printf('%d %% (%d)',$pr ,$answer['count'])?></span>
   </p>
      <?}?>
   <?
   $this->formsingle->id_poll->setValues($this->poll->{Polls_Model_Detail::COL_ID});
   print ($this->formsingle->id_poll->controll());
   print ($this->formsingle->vote->controll());
   ?>
   <br />
   <span class="loader" style="display:none"><img src="images/progress.gif" alt="Loading..." width="16" /></span>
   <span class="pollNumVotes"><?printf($this->_('Celkem hlasovalo: %d osob'),$this->poll->{Polls_Model_Detail::COL_VOTES});?></span>
</div>
<?=$this->formsingle->renderEnd()// EOF form?>
