<div>
   <?
   $somePoll = false;
   while ($poll = $this->polls->fetch()) {
      $somePoll = true;?>
   <h2><?=$poll->{Polls_Model_Detail::COL_QUESTION}?></h2>
   <div style="position: relative">
         <?if($poll->{Polls_Model_Detail::COL_ACTIVE} == true AND !isset ($this->votedPolls[$poll->{Polls_Model_Detail::COL_ID}])) {
            // více možností
            if ($poll->{Polls_Model_Detail::COL_IS_MULTI} == true) {
               $this->formmulti->html()->addClass('pollVoteForm');
               // více možností
               $pollTpl = new Template_Module($this->link(), $this->category());
               $pollTpl->addTplFile('poll_multi.phtml');
               $pollTpl->formmulti = $this->formmulti;
               $pollTpl->poll = $poll;
               print ($pollTpl);
            } else {
               // jedna možnost
               $this->formsingle->html()->addClass('pollVoteForm');
               $pollTpl = new Template_Module($this->link(), $this->category());
               $pollTpl->addTplFile('poll_single.phtml');
               $pollTpl->formsingle = $this->formsingle;
               $pollTpl->poll = $poll;
               print ($pollTpl);
            }
         } else {
            // jenom, zobrazení?>
            <?
            $pollTpl = new Template_Module($this->link(), $this->category());
            $pollTpl->addTplFile('poll_read.phtml');
            $pollTpl->poll = $poll;
            print ($pollTpl);
         }
         if($this->category()->getRights()->isWritable()) {
            $toolbox = new Template_Toolbox();
            $toolbox->addTool('poll_edit', $this->_("Upravit anketu"),
                    $this->link()->route('edit',array('id' => (int)$poll->{Polls_Model_Detail::COL_ID})),
                    $this->_("Upravit anketu"), "film_edit.png");
            $toolbox->addTool('poll_delete', $this->_("Smazat anketu"),
                    $this->link(), $this->_("Smazat anketu"), "film_delete.png",
                    'poll_id', (int)$poll->{Polls_Model_Detail::COL_ID},
                    $this->_('Opravdu smazat anketu?'));
            $this->includeTplObj($toolbox);
         }?>
   </div>
   <br/>
      <?
   }
   print $this->scrollComp; // skrolery

   if($somePoll == true) {
      $jQuery = new JsPlugin_JQuery();
      $jQuery->addPluginAjaxForm();
      $this->addJsPlugin($jQuery);
      ?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $('form.pollVoteForm').submit(function(){
         var jform = $(this);
         showLoadBox(jform);
         $.ajax({
            type: "POST",
            cache: false,
            url: '<?=$this->link()->clear()->route('voteajax');?>',
            data: jform.serialize(),
            dataType: "json",
            success: function(data) {
               if(data.code == true){
                  hideLoadBox();
                  var pjform = jform.parent(); // zobrazení dat
                  jform.remove();
                  pjform.append($(data.data));
                  infoMsg(data.message);
               } else {
                  errMsg(data.message);
               }
            },
            error : function(){
               hideLoadBox();
            }
         });
         return false;
      });
      /* ]]> */
   </script>
      <?
   } else {?>
   <p><?=$this->_('Žádná anketa není vložena')?></p>
   <?}?>
</div>
<?
if($this->category()->getRights()->isWritable()) {
   $toolbox = new Template_Toolbox();
   $toolbox->addTool('add_poll', $this->_("Přidat anketu"),
           $this->link()->route('add'),
           $this->_("Přidat novou anketu"), "page_add.png");
   $this->includeTplObj($toolbox);
}?>
