<?// vypočty
$data = unserialize($this->poll->{Polls_Model::COLUMN_DATA});
$maxVote = 0;
$allVotes = 0;
foreach ($data as $key => $vote) {
   if($vote['count'] > $maxVote) $maxVote = $vote['count'];
   $allVotes += $vote['count'];
}?>
   <?foreach ($data as $key => $answer) {
      $maxVote == 0 ? $prRender = 0 : $prRender = round(($answer['count']/($maxVote/100)*0.9));
      $percent = $allVotes/100;
      $percent == 0 ? $pr = 0 : $pr = round($answer['count']/$percent);
      ?>
   <label><?=$answer['answer']?></label>
   <p class="pollGraph" style="width: <?=$prRender?>%;">
      <span class="pollNumbers"><?printf('%d %% (%d)',$pr ,$answer['count'])?></span>
   </p>
      <?}?>
   <span class="pollNumVotes"><?printf($this->_('Celkem hlasovalo: %d osob'),$this->poll->{Polls_Model::COLUMN_VOTES});?></span>