<?php 
if(!defined('VVE_MODULE_POOLS_SCRIPT')) {
   define('VVE_MODULE_POOLS_SCRIPT', true);
   ?>
<script type="text/javascript">
   /* <![CDATA[ */
   $('form.pollVoteForm').live('submit',function(){
      var $form = $(this);
      // kontrola alespoň jedné volby
      if($form.has('input[type=checkbox]').length > 0 && $('input[type=checkbox]:checked', $form).length == 0){
         errMsg('<?php echo $this->_('Musíte vybrat alespoň jednu možnost ankety')?>', true);
         return false;
      }
      showLoadBox($form);
      $.ajax({type: "POST", cache: false, url: '<?php echo $this->link()->clear()->route();?>',
         data: $form.serialize(),
         success: function(data) {
            vveShowMessages(data);
            $form.parent('div').load('<?php echo $this->link()->clear()->route('pollData');?>',{id : data.id});
         }
      });
      return false;
   });
   /* ]]> */
</script>
   <?php 
}
?>