<?php 
$t = $this->category()->getName().' - '. $this->tr('seznam dotazů');
Template::addPageTitle($t);

$jq = new JsPlugin_JQuery();
$this->addJsPlugin(new JsPlugin_JQuery());
$jsJqGrid = new Component_JqGrid_JsPlugin();
$this->addJsPlugin($jsJqGrid);
$this->addFile("css://style.css");

?>
<h1><?php echo $t;?></h1>
<div class="main-content-form-edit">
   <table id="table-questions"></table>
   <div id="table-questions-toolbar">
      <!--<label for="select-drug-id"><?php echo $this->tr('Drogy')?>:</label>
      <select id="select-drug-id" name="sel_drug">
         <?php 
         /*foreach ($this->groups as $grp) {
            $grpsArr[(int)$grp[Model_Groups::COLUMN_ID]] = $grp[Model_Groups::COLUMN_NAME];
            ?><option value="<?php echo $grp->{Model_Groups::COLUMN_ID}?>" title="<?php echo $grp->{Model_Groups::COLUMN_NAME}?>"><?php echo $grp->{Model_Groups::COLUMN_NAME}.' - '.$grp->{Model_Groups::COLUMN_LABEL}?></option><?php 
         }*/
         ?>
         <option value="0">kokain</option>
      </select>
      
      <label for="select-group-id"><?php echo $this->tr('Skupina')?>:</label>
      <select id="select-group-id" name="sel_group">
         <?php 
         /*foreach ($this->groups as $grp) {
            $grpsArr[(int)$grp[Model_Groups::COLUMN_ID]] = $grp[Model_Groups::COLUMN_NAME];
            ?><option value="<?php echo $grp->{Model_Groups::COLUMN_ID}?>" title="<?php echo $grp->{Model_Groups::COLUMN_NAME}?>"><?php echo $grp->{Model_Groups::COLUMN_NAME}.' - '.$grp->{Model_Groups::COLUMN_LABEL}?></option><?php 
         }*/
         ?>
         <option value="0">kokain</option>
      </select>-->
   </div>
   <div id="table-questions-pager"></div>
   <br />
   <p>
      <a href="<?php echo $this->link()->route()?>" title="<?php echo $this->tr('Přejít zpět na úvodní stranu poradny')?>">&Lt; <?php echo $this->tr('Zpět na úvodní stranu')?></a>
   </p>
   <div id="question-info">
      
   </div>
</div>

<script type="text/javascript">
   /* <![CDATA[ */
   // base vars
   var colors = <?php echo json_encode($this->answerColors)?>;
   
   /* JqGrid formaters */
   function answerFormatter( cellvalue) 
   {
      // format the cellvalue to new format
      
      if(cellvalue.length == 0){
         return '<span style="color: red; font-weight: bold;"><?php echo $this->tr('Ne')?></span>';
      }
      return '<span title="'+stripFormatter(cellvalue)+'"><?php echo $this->tr('Ano');?></span>';
   }
   
   function stripFormatter(html) 
   {
      var tmp = document.createElement("DIV");
      tmp.innerHTML = html;
      return tmp.textContent || tmp.innerText;
   }
   
   function colorFormatter(cellvalue, options, rowObject ) 
   {
      var html = '<div style="background-color: #'+cellvalue+'; padding: 3px; margin:0;">'
         +'<select name="row-color">';
      $.each(colors, function(index, value) { 
         html += '<option value="'+index+'"';
         if(index == cellvalue){
            html += 'selected="selected"';
         }
         html += '>'+value+'</option> ';
      });
      html += '</select></div>';
      return html;
   }
   
   function publicFormatter(cellvalue, options, rowObject ) 
   {
      var input = '<input type="checkbox" name="question_public" ';
      if(rowObject.<?php echo Advice_Model::COLUMN_IS_PUBLIC?> == true){
         input += 'checked="checked" '
      }
      if(rowObject.<?php echo Advice_Model::COLUMN_IS_PUBLIC_ALLOW?> != true){
         input += 'disabled="disabled" '
      }
      return input+'/>';
   }
   
   function detectColor(color){
      var d = 0;
      // Counting the perceptive luminance - human eye favors green color... 
      var a = 1 - ( 
         0.299 * parseInt((color).substring(0,2),16) 
         + 0.587 * parseInt((color).substring(2,4),16) 
         + 0.114 * parseInt((color).substring(4,6),16) )/255;
      if (a < 0.5){
         return "#000000"; // bright colors - black font
      } else{
         return "#ffffff"; // dark colors - white font
      }  
   }
   
   $(document).ready(function(){
      var questionsGrid = $("#table-questions").jqGrid({
            ajaxGridOptions : {type:"POST"},
            url: '<?php echo $this->link()->route('questionsList');?>?idgrp=0'/*+$('#select-group-id').val().toString()*/,
            datatype: "json",
            colNames:[
               'ID', 
               '<?php echo $this->tr('Dotaz')?>', 
               '<?php echo $this->tr('Veřejný')?>', 
               '<?php echo $this->tr('Odpověď')?>', 
               '<?php echo $this->tr('Vytvořeno')?>',
               '<?php echo $this->tr('Štítek')?>', 
               '<?php echo $this->tr('Akce')?>'
            ],
            colModel:[
               {name:'<?php echo Advice_Model::COLUMN_ID?>',index:'<?php echo Advice_Model::COLUMN_ID?>',
                  width:40,fixed: true, editable:false, searchtype:"integer"
               },
               
               {name:'<?php echo Advice_Model::COLUMN_QUESTION?>',index:'<?php echo Advice_Model::COLUMN_QUESTION?>',
                  formatter : stripFormatter
               },
               
               {name:'<?php echo Advice_Model::COLUMN_IS_PUBLIC?>',index:'<?php echo Advice_Model::COLUMN_IS_PUBLIC?>', 
                  width:33,fixed: true, formatter: publicFormatter 
               },

               {name:'<?php echo Advice_Model::COLUMN_ANSWER?>',index:'<?php echo Advice_Model::COLUMN_ANSWER?>',
                  width:33,fixed:true, formatter : answerFormatter, title : false
               },
               
               {name:'<?php echo Advice_Model::COLUMN_DATE_ADD?>', index:'<?php echo Advice_Model::COLUMN_DATE_ADD?>', 
                  width:80,fixed: true, formatter:'date', formatoptions:{srcformat: "Y-m-d H:i:s", newformat: 'd.m.Y'}
               },
               
               {name:'<?php echo Advice_Model::COLUMN_COLOR?>',index:'<?php echo Advice_Model::COLUMN_COLOR?>',
                  width:82,fixed:true, formatter : colorFormatter, title : false
               },
               
               {name:'actions',index:'actions', width:55, fixed: true,
                  formatter:'actions', formatoptions:{ keys:true, 
                     onEdit:function(rowid) {
                        alert("in onEdit: rowid="+rowid+"\nWe don't need return anything");
                     }
                     
                  }
               }
            ],
            rowNum:20,
            rowList:[10,20,40,100],
            pager: '#table-questions-pager',
            sortname: '<?php echo Advice_Model::COLUMN_DATE_ADD?>',
            sortorder: 'desc',
            caption:"<?php echo $this->tr('Dotazy poradny')?>",
            jsonReader: {
               repeatitems : false, root:"rows"
            },
            editurl : "<?php echo $this->link()->route("changeAttribute")?>",
            autowidth : true,
            height: '100%',
            toolbar: [true,"top"]
         });
         // toolbar - výběry
         $("#t_table-questions").append($('#table-questions-toolbar').html());
         $('#table-questions-toolbar').remove();
         
         /* změna barvy */
         $('select[name="row-color"]').live('change', function(){
            var $obj = $(this); var newColor = $obj.val(); var rowId = $obj.parents('tr').attr('id');
            $.ajax({
               url: "<?php echo $this->link()->route("changeAttribute")?>",
               type: "POST",
               data: {id : rowId, oper : 'color', v : newColor},
               success : function(){
                  $obj.parent('div').css('background-color', '#'+newColor);
               }
            });
         });
         
         /* změna public */
         $('input[name="question_public"]').live('change', function(){
            var $obj = $(this); var rowId = $obj.parents('tr').attr('id');
            var val = false;
            if($obj.is(':checked')){ val = true; }
            $.ajax({
               url: "<?php echo $this->link()->route("changeAttribute")?>",
               type: "POST", data: {id : rowId, oper : 'public', v : val}
            });
         });
         
         $('.ui-inline-edit').live('click', function(){
            window.location = ('<?php echo $this->link()->route('editQuestion')?>').replace('{id}', $(this).parents('tr').attr('id'));
         });
         
         $('.jqgrow').live('dblclick', function(){
            window.location = ('<?php echo $this->link()->route('editQuestion')?>').replace('{id}', $(this).attr('id'));
         });
         
         $('.jqgrow').live('click', function(){
            var $info = $('#question-info');
            var id = $(this).attr('id');
            $info
               .html("").css({ "background-color" : "transparent", color : "black" }) // reset colors
               .append($('<h2></h2>').text('<?php echo $this->tr('Informace o dotazu')?>'))
               .append($('<h3></h3>').text('<?php echo $this->tr('Dotaz')?>'))
               .append($('<p></p>').html( $('td:nth-child(2)',this).text()) );
             
            var color = $('td:nth-child(6) option:selected',this).val();
            if(color != "0"){
               $info.css({
                  "background-color" : "#"+color,
                  color : detectColor(color)
               });
            }
             
            if($('td:nth-child(4) span',this).attr("title") != null){
               $info.append($('<h3></h3>').text('<?php echo $this->tr('Odpověď')?>'))
               .append($('<p></p>').html( $('td:nth-child(4) span',this).attr("title")));
            }   
         });
         
         
         questionsGrid.jqGrid('navGrid','#table-questions-pager', 
            {edit:false,add:false,del:false}, 
            {}, {}, {}, 
            { // search opts
               multipleSearch: false, 
               multipleGroup:false, 
               closeAfterSearch: true,
               closeOnEscape:true,
               sopt : ['eq','ne','cn','nc']
            } 
         );
   });
   /* ]]> */
</script>
