<?
$t = $this->tr('Správa kateorií poradny');
Template::addPageTitle($this->tr('Správa kateorií'));
$this->addFile('css://style.css');

$this->formSortCats->delete->html()->addClass('checkbox-delete');
$this->formSortCats->save->setCancelConfirm(false);
$this->formSortCats->html()->addClass('form-set-sort');
if($this->formSortDrugs != null){
   $this->formSortDrugs->delete->html()->addClass('checkbox-delete');
   $this->formSortDrugs->save->setCancelConfirm(false);
   $this->formSortDrugs->html()->addClass('form-set-sort');
}
?>

<h1><?echo $t;?></h1>
<div class="main-content-detail">
   <h2><?=$this->tr('Kategorie')?></h2>
   <?
   echo $this->formSortCats->renderStart();?>
   <ul id="cats-sortable" class="cats-sortable">
   <?foreach ($this->cats as $cat) {?>
      <li class="ui-state-default ui-state-active">
         <span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
         <?
         $this->formSortCats->name->setDimensional($cat->{Advice_Model_Categories::COLUMN_ID});
         $this->formSortCats->name->setValues($cat->{Advice_Model_Categories::COLUMN_NAME});
         echo $this->formSortCats->name->controll();
         
         $this->formSortCats->delete->setDimensional($cat->{Advice_Model_Categories::COLUMN_ID});
         echo $this->formSortCats->delete->label();
         echo $this->formSortCats->delete->controll();
         ?>
      </li>
   <?}?>
   </ul>
   <div class="sort-tools ui-state-default">
         <?=$this->formSortCats->save->controll();?>
      <input type="button" name="add-cat" value="<?=$this->tr('Přidat kategorii')?>" />
   </div>
   <?=$this->formSortCats->renderEnd();?>
   <?if($this->formSortDrugs != null){?>
   <h2><?=$this->tr('Drogy')?></h2>
   <?=$this->formSortDrugs->renderStart();?>
   <ul id="drugs-sortable" class="cats-sortable">
   <?foreach ($this->drugs as $drug) {?>
      <li class="ui-state-default ui-state-active">
         <span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
         <?
         $this->formSortDrugs->name->setDimensional($drug->{Advice_Model_Categories::COLUMN_ID});
         $this->formSortDrugs->name->setValues($drug->{Advice_Model_Categories::COLUMN_NAME});
         echo $this->formSortDrugs->name->controll();
         
         $this->formSortDrugs->delete->setDimensional($drug->{Advice_Model_Categories::COLUMN_ID});
         echo $this->formSortDrugs->delete->label();
         echo $this->formSortDrugs->delete->controll();
         ?>
      </li>
   <?}?>
   </ul>
   <div class="sort-tools ui-state-default">
         <?=$this->formSortDrugs->save->controll();?>
      <input type="button" name="add-drug" value="<?=$this->tr('Přidat drogu')?>" />
   </div>
   <?=$this->formSortDrugs->renderEnd();?>
   <?}?>
   
</div>

<div id="add-cat-dialog" title="">
   <?
   $this->formAdd->save->setCancelConfirm(false);
   echo $this->formAdd;
   ?>
</div>

<div id="test"></div>
<?
$jq = new JsPlugin_JQuery();
$jq->addUISortable();
$jq->addUIDialog();
$this->addJsPlugin($jq);
?>
   <script type="text/javascript">
      /* <![CDATA[ */
      var someChanges = false;
      $(function() {
         // init sorting
         var sortOpts = {
            handle: 'span',
            forcePlaceholderSize: true,
            placeholder: 'ui-state-highlight',
            change: function() { someChanges = true; }
         };
         
         $( "#cats-sortable" ).sortable(sortOpts);
         $( "#drugs-sortable" ).sortable(sortOpts);
         // create dialog
         var addDialog = $( "#add-cat-dialog" ).dialog({ autoOpen: false, width: 400, modal: true});
         
         // button add cat
         $('input[name="add-cat"]').click(function(){
            addDialog.find('input[type="checkbox"]').removeAttr('checked');
            addDialog.dialog("option", 'title', '<?=$this->tr('Přidání kategorie')?>').dialog( "open" );
         });
         
         // button add drug
         $('input[name="add-drug"]').click(function(){
            addDialog.find('input[type="checkbox"]').attr('checked', 'checked');
            addDialog.dialog("option", "title", '<?=$this->tr('Přidání drogy')?>').dialog( "open" );
         });
         
         // zavření dialogu při zrušení
         $('input[name="add_cat_save_cancel"]').click(function(e){
            e.preventDefault();
            $( "#add-cat-dialog" ).dialog("close");
         });
         
         // změna stavu při smazání
         $('.checkbox-delete').live('change', function(){
            if($(this).is(':checked')){
               someChanges = true;
               $(this).parents('li').addClass('ui-state-disabled');
            } else {
               $(this).parents('li').removeClass('ui-state-disabled');
            }
         });
         
         $('.button-cancel').click(function(){
            if(someChanges == true){
               if(!confirm('<?=$this->tr('Zrušit neuložené změny?')?>')){return false;}
            }
         });
         
   	});
      /* ]]> */
</script>
