<?

$title = $this->question->{Advice_Model::COLUMN_NAME} != null 
   ? $this->question->{Advice_Model::COLUMN_NAME} 
   : $this->tr('Dotaz ID').':  '.$this->question->{Advice_Model::COLUMN_ID};
Template::addPageTitle($title);


$this->form->question->html()->setAttrib('rows', 10);
$this->form->answer->html()->setAttrib('rows', 10);
$this->form->allowPublic->html()->setAttrib('disabled', 'disabled');

$this->form->cats->html()->setAttrib('size', 8);
if (isset ($this->form->drugs)) {
   $this->form->drugs->html()->setAttrib('size', 8);
}

?>
<h1 style="<?if($this->question->{Advice_Model::COLUMN_COLOR} != ""){echo "border-bottom: 5px solid #".$this->question->{Advice_Model::COLUMN_COLOR}.";";}?>"><?ps($title);?></h1>
<div class="main-content-detail">
   <p class="text">
      <?=$this->tr("Vloženo").': '.vve_date("%x", new DateTime($this->question->{Advice_Model::COLUMN_DATE_ADD}))?>,<br />
      <strong><?echo $this->tr("Souhlas se zveřejněním").": ".($this->question->{Advice_Model::COLUMN_IS_PUBLIC_ALLOW} == true ? $this->tr('Ano') : $this->tr('Ne'));?></strong>
   </p>
   <?
   $this->form->html()->setAttrib('id', 'form-edit-question');
   echo $this->form;
   ?>
</div>
<?
$this->addJsPlugin(new JsPlugin_JQuery());
?>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         var origAnswer = $('textarea[name="question_answer"]').val();
         $('select[name="question_color"]').change(function(){
            if($(this).val() == "0"){
               $(this).parent().css("background-color", 'transparent');
            } else {
               $(this).parent().css("background-color", '#'+$(this).val());
            }
         });
         $('select[name="question_color"]').change();
         
         $('#form-edit-question').submit(function(){
            var answer = tinymce.get("question_answer_1").getContent() || $('textarea[name="question_answer"]').val();
            
            if($('input[name="question_sendAnswer"]').lenght != 0 &&
               !$('input[name="question_sendAnswer"]').is(":checked") &&
               answer != "" && answer != origAnswer ){
               if(confirm('<?=$this->tr('Odpověď byla vyplněna. Chcete ji odeslat emailem?')?>')){
                  $('input[name="question_sendAnswer"]').attr('checked', true);
               }
            }
         });
      });
      /* ]]> */
</script>
