<?
$this->addCssFile("style.css");

$model = new Text_Model_Detail();
$text = $model->getText(Category::getSelectedCategory()->getId());
$modelImages = new PhotoGalery_Model_Images();
$images = $modelImages->getImages($this->category()->getId());

// jquery galerka
$this->addJsPlugin(new JsPlugin_Galleriffic());

?>
<div class="imagesList">
   <?if($text != null) {?>
   <div>
         <?=$text->{Text_Model_Detail::COLUMN_TEXT}?>
   </div>
   <br />
   <?}?>

   <!-- Start Advanced Gallery Html Containers -->
   <div class="navigation-container">
      <div id="thumbs" class="navigation">
         <a class="pageLink prev" style="visibility: hidden;" href="#" title="Previous Page">&lt;</a>
         <ul class="thumbs noscript">
            <?while ($image = $images->fetch()) {
               ?>
            <li>
               <a class="thumb" name="leaf" href="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir
                         .Photogalery_Controller::DIR_MEDIUM.URL_SEPARATOR.$image[PhotoGalery_Model_Images::COLUMN_FILE]?>"
                  title="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>">
                  <img src="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir.Photogalery_Controller::DIR_SMALL.URL_SEPARATOR
                              .$image[PhotoGalery_Model_Images::COLUMN_FILE]?>" alt="<?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?>" />
               </a>
               <div class="caption">
                     <?if((string)$image->{PhotoGalery_Model_Images::COLUMN_NAME} != null) {?>
                  <div class="image-title"><?=$image->{PhotoGalery_Model_Images::COLUMN_NAME}?></div>
                     <?}?>
                     <?if((string)$image->{PhotoGalery_Model_Images::COLUMN_DESC} != null) {?>
                  <div class="image-desc"><?=$image->{PhotoGalery_Model_Images::COLUMN_DESC}?></div>
                     <?}?>
                  <div class="download">
                     <a href="<?=$this->category()->getModule()->getDataDir(true).$this->websubdir
                         .Photogalery_Controller::DIR_ORIGINAL.URL_SEPARATOR.$image[PhotoGalery_Model_Images::COLUMN_FILE]?>"><?=$this->_('Originál')?></a>
                  </div>
               </div>
            </li>
            <?}?>
         </ul>
         <a class="pageLink next" style="visibility: hidden;" href="#" title="Next Page">&gt;</a>

      </div>
   </div>

   <div class="content">
      <div class="slideshow-container">
         <div id="controls" class="controls"></div>
         <div id="loading" class="loader"></div>
         <div id="slideshow" class="slideshow"></div>
      </div>
      <div id="caption" class="caption-container">
      </div>
   <div style="position:relative; clear:both"></div>
   </div>
   <!-- End Gallery Html Containers -->
   <hr class="reseter" />

   <script type="text/javascript">
      /* <![CDATA[ */
      jQuery(document).ready(function($) {
         // We only want these styles applied when javascript is enabled
         $('div.content').css('display', 'block');

         // Initially set opacity on thumbs and add additional styling for hover effect on thumbs
         var onMouseOutOpacity = 0.67;
         $('#thumbs ul.thumbs li, div.navigation a.pageLink').opacityrollover({
            mouseOutOpacity:   onMouseOutOpacity,
            mouseOverOpacity:  1.0,
            fadeSpeed:         'fast',
            exemptionSelector: '.selected'
         });

         // Initialize Advanced Galleriffic Gallery
         var gallery = $('#thumbs').galleriffic({
            delay:                     2000,
            numThumbs:                 6,
            preloadAhead:              6,
            enableTopPager:            false,
            enableBottomPager:         false,
            imageContainerSel:         '#slideshow',
            controlsContainerSel:      '#controls',
            captionContainerSel:       '#caption',
            loadingContainerSel:       '#loading',
            renderSSControls:          true,
            renderNavControls:         true,
            playLinkText:              '<?=$this->_('Přehrát')?>',
            pauseLinkText:             '<?=$this->_('Pozastavit')?>',
            prevLinkText:              '&lsaquo; <?=$this->_('Předchozí fotka')?>',
            nextLinkText:              '<?=$this->_('Další fotka')?> &rsaquo;',
            nextPageLinkText:          '<?=$this->_('Další')?> &rsaquo;',
            prevPageLinkText:          '&lsaquo; <?=$this->_('Předchozí')?>',
            enableHistory:             false,
            autoStart:                 false,
            syncTransitions:           true,
            defaultTransitionDuration: 300,
            onSlideChange:             function(prevIndex, nextIndex) {
               // 'this' refers to the gallery, which is an extension of $('#thumbs')
               this.find('ul.thumbs').children()
               .eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
               .eq(nextIndex).fadeTo('fast', 1.0);

               // Update the photo index display
               this.$captionContainer.find('div.photo-index')
               .html('<?=$this->_('Fotka')?> '+ (nextIndex+1) +' <?=$this->_('z')?> '+ this.data.length);
            },
            onPageTransitionOut:       function(callback) {
               this.fadeTo('fast', 0.0, callback);
            },
            onPageTransitionIn:        function() {
               var prevPageLink = this.find('a.prev').css('visibility', 'hidden');
               var nextPageLink = this.find('a.next').css('visibility', 'hidden');

               // Show appropriate next / prev page links
               if (this.displayedPage > 0)
                  prevPageLink.css('visibility', 'visible');

               var lastPage = this.getNumPages() - 1;
               if (this.displayedPage < lastPage)
                  nextPageLink.css('visibility', 'visible');

               this.fadeTo('fast', 1.0);
            }
         });
         /**************** Event handlers for custom next / prev page links **********************/
         gallery.find('a.prev').click(function(e) {
            gallery.previousPage();
            e.preventDefault();
         });

         gallery.find('a.next').click(function(e) {
            gallery.nextPage();
            e.preventDefault();
         });
         /****************************************************************************************/
      });
      /* ]]> */
   </script>
   <?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('edit_text', $this->_("Upravit text"),
          $this->link()->route('edittext'),
          $this->_("Upravit text galerie"), "page_edit.png");
      $toolbox->addTool('edit_images', $this->_("Upravit obrázky"),
          $this->link()->route('editimages'),
          $this->_("Upravit text galerie"), "image_edit.png");
      $this->includeTplObj($toolbox);
   }?>
</div>
