<div class="order-buttons">
   <a href="<?php 
      if(isset($_GET[$this->orderParam]) && $_GET[$this->orderParam] == "a"){
         echo $this->link()->param($this->orderParam);
      } else {
         echo $this->link()->param($this->orderParam, 'a');
      }

   ?>" title="<?php echo $this->tr('Seřadit vzestupně')?>"
      class="button-order-up <?php if(isset($_GET[$this->orderParam]) && $_GET[$this->orderParam] == "a"){ echo "active";}?>"
           ><span class="icon icon-chevron-up"></span></a>
   <a href="<?php 
   if(isset($_GET[$this->orderParam]) && $_GET[$this->orderParam] == "d"){
      echo $this->link()->param($this->orderParam);
   } else {
      echo $this->link()->param($this->orderParam, 'd');
   }

   ?>" title="<?php echo $this->tr('Seřadit sestupně')?>"
      class="button-order-down <?php if(isset($_GET[$this->orderParam]) && $_GET[$this->orderParam] == "d"){ echo "active";}?>"
           ><span class="icon icon-chevron-down"></span></a>
</div>