<div class="order-buttons">
   <a href="<?php 
      if(isset($_GET[$this->orderParam]) && $_GET[$this->orderParam] == "a"){
         echo $this->link()->param($this->orderParam);
      } else {
         echo $this->link()->param($this->orderParam, 'a');
      }

   ?>" title="<?php echo $this->tr('Seřadit vzestupně')?>"
      class="button-order-up <?php if(isset($_GET[$this->orderParam]) && $_GET[$this->orderParam] == "a"){ echo "ui-state-highlight";}?>"
           ><span class="ui-icon ui-icon-triangle-1-n"></span></a>
   <a href="<?php 
   if(isset($_GET[$this->orderParam]) && $_GET[$this->orderParam] == "d"){
      echo $this->link()->param($this->orderParam);
   } else {
      echo $this->link()->param($this->orderParam, 'd');
   }

   ?>" title="<?php echo $this->tr('Seřadit sestupně')?>"
      class="button-order-down <?php if(isset($_GET[$this->orderParam]) && $_GET[$this->orderParam] == "d"){ echo "ui-state-highlight";}?>"
           ><span class="ui-icon ui-icon-triangle-1-s"></span></a>
</div>