<?
if( !empty($this->moduleButtons) ){
   $this->addFile('css://engine:style-admin.less');// need for buttons style
   ?>
   <ul class="module-tool-buttons clearfix">
   <?foreach ($this->moduleButtons as $id => $button) {
      if(is_array($button)){
         
         $button += array(
             'id' => null,
             'important' => false,
             'name' => null,
             'title' => null,
             'link' => null,
             'faicon' => null,
             'icon' => null,
             'type' => 'button',
             'state' => null, // warning, error, ok
             'options' => array(), // hodnoty pro rozbalovací seznam a podobně
             'attributes' => array(
                 'id' => isset($button['id']) ? $button['id'] : ( !is_int($id) ? $id : null ),
                 'onclick' => isset($button['confirm']) ? 'return confirm(\''.htmlspecialchars($button['confirm']).'\')' : null
             ),
         );
         strpos('.', $button['icon']) === false ? $button['faicon'] = $button['icon'] : '';

         $iconSrc = (strpos($button['icon'], 'http') !== false ? $button['icon'] : '/images/icons/'.$button['icon']);

         $cnt = null;
         switch ($button['type']){
            case 'text':
               $cnt .= '<div class="">';
               $cnt .= '<input type="text" ';
               foreach($button['attributes'] as $name => $value){
                  $cnt .= $name.'="'.$value.'" ';
               }
               $cnt .= '/>';
               $cnt .= '</div>';
               break;
            case 'select':
               $cnt .= '<div class="">';
               $cnt .= '<label>'.  htmlspecialchars($button['name']).'</label> ';
               $cnt .= '<select ';
               foreach($button['attributes'] as $name => $value){
                  $cnt .= $name.'="'.$value.'" ';
               }
               $cnt .= '>';
               foreach($button['options'] as $label => $value){
                  $cnt .= '<option value="'.$value.'">'.  htmlspecialchars( is_int($label) ? $value : $label ).'</option>';
               }
               $cnt .= '</select>';
               $cnt .= '</div>';
               break;
            case 'button':
            case 'default':
            default:
               $button['attributes']['href'] = $button['link'];
               $button['attributes']['title'] = $button['title'];

               $cnt = '<a class=" '.($button['name'] != null ? '' : '').'" ';
               foreach($button['attributes'] as $name => $value){
                  $cnt .= $value != null ? $name.'="'.$value.'" ' : null;
               }

               $cnt .= '>';
               if(isset($button['faicon'])){
                  $cnt .= '<span class="icon icon-'.$button['faicon'].'"></span>';
               } else if($button['icon']){
                  $cnt .= '<img src="'.$iconSrc.'" alt="'.$button['icon'].'" />';
               }
               $cnt .= htmlspecialchars($button['name']).'</a>';

               break;
         }
         ?>
         <li class="<?echo $button['important'] ? 'important' : ''?>"><?echo $cnt;?></li>
         <?
      } else if(is_string($button)) {
         ?>
         <li><div><?echo $button;?></div></li>
         <?
      }
   }?>
   </ul>
   <?
}
