<?
$this->addFile('css://engine:style-admin.less');// need for buttons style
?>
<div class="module-navigation-container">
<ul class="module-navigation">
<?
$curLink = new Url_Link();
$curLink = (string)$curLink;
foreach ($this->items as $name => $link) {
   $icon = null;
   $hidden = false;
   if(is_array($link)){
      $hidden = true;
      $icon = $link['icon'];
      $link = $link['link'];
   }
   
   $classes = array();
   $hidden ? $classes[] = "collapsible" : ''; 
   $curLink == (string)$link ? $classes[] = 'active' : '';
   
   ?>
   <li class="<?=implode(' ', $classes);?>"
       ><a href="<?=$link?>" title="<?=$this->tr('Přejít na').' '.$name?>"><?
   if($icon != null && strpos($icon, '.png') !== false){
      ?><img src="<?=vve_get_tpl_file('icons/'.$icon, VVE_TPL_FILE_IMAGE)?>" alt="icon <?=$icon?>" /><?
   } else if($icon != null){
      ?><span class="icon icon-<?=$icon?>"></span><?
   }
   ?><span class="name"><?=$name?></span></a></li>
<?
}
?>
</ul>
</div>