<?php 
   $h1 = $this->category()->getName();
   $this->addPageTitle($h1);
?>
<h1><?php ps($h1);?></h1>
<div class="main-content-detail">
   <?php 
   echo $this->text;
   ?>
   <ul id="links-list" class="">
      <?php 
      if(!empty($this->links)){
         foreach($this->links as $link) {
            $href = $link->{LinksList_Model_Links::COLUMN_TARGET};
            $name = $link->{LinksList_Model_Links::COLUMN_TITLE};
            if($link->{LinksList_Model_Links::COLUMN_CATEGORY} != 0){
               $ulr = new Url_Link(true);
               $href = $ulr->category($link->{Model_Category::COLUMN_URLKEY});
               $name = $link->{Model_Category::COLUMN_NAME};
            } else if(strpos($href, 'http') === false){
               $href = Url_Link::getMainWebDir().$href;
            }
            ?>
            <li id="link-<?php echo $link->getPK()?>" class="clearfix" data-id="<?php echo $link->getPK()?>">
               <span class="move"><span class="icon icon-arrows-v"></span></span>
               <?php if($link->imageSrc){?>
               <span class="image"><img src="<?php echo   vve_image_cacher($link->imageSrc, 100, 40)?>" alt="" />
               </span>
               <?php }?>
               <span class="info">
                  <span class="title"><?php echo $name?></span>
                  <a class="link" href="<?php echo $href?>"><?php ps($href)?></a>
               </span>
            </li>
            <?php 
         }
      } else {
         ?>
         <li>
            <?php   ps($this->tr('Není vložen žádný odkaz'))?>
         </li>
         <?php 
      }
      ?>
   </ul>
   <?php 
   echo $this->toolbox;
   ?>
</div>
