<?php 
$this->addCssFile("style.css");
// do titulku
if($this->edit) {
   $this->addPageTitle($this->tr('úprava novinky'));
   $this->addPageTitle($this->catName);
   $h1 = $this->tr('úprava novinky').' '.$this->catName;
} else {
   $h1 = $this->tr('přidání novinky');
   $this->addPageTitle($h1);
}
// donastavení formuláře
$this->form->name->html()->setAttrib('size', 72);
$this->form->urlkey->html()->setAttrib('size', 72);
$this->form->text->html()->setAttrib('cols', 60)->setAttrib('rows', 15)->addClass("mceEditor");
$this->form->metaKeywords->html()->setAttrib('size', 72);
$this->form->annotation->html()->setAttrib('cols', 80)->setAttrib('rows', 5)->addClass("mceEditor");
$this->form->metaDesc->html()->setAttrib('cols', 80)->setAttrib('rows', 3);
if($this->form->haveElement('textPrivate')){
   $this->form->textPrivate->html()->setAttrib('cols', 80)->setAttrib('rows', 30)->addClass("mceEditor");
}

$tinymce = new JsPlugin_TinyMce();
$tinymce->setCfgParam('theme', JsPlugin_TinyMce::TINY_THEME_ADVANCED_SIMPLE);
$this->addJsPlugin($tinymce);

?>
<h1><?php echo $h1;?></h1>
<div class="main-content-form-edit">
   <?php print($this->form);?>
</div>
