<div id="editNewForm">
   <ul class="langMenu">
      <? foreach ($this->pVar("appLangsNames") as $key => $lang) {?>
      <li>
         <a href="#newsLang<?=$key?>" class="selectedd">
            <img src="images/lang/<?$key?>.png" title="<?=$lang?>" />
            <?=$lang?>
         </a>
      </li>
      <?}?>
   </ul>

   <div class="tabsContent">
      <form method="post" action="<?=$this->l();?>">
         <? foreach ($this->pVar("appLangsNames") as $key => $lang) {?>
         <p id="newsLang<?=$key?>" class="tabcontent">
            <?=$this->_m("Název novinky");?>:<br />
            <input type="text" size="40" maxlength="50" name="news_label[<?=$key?>]"
                   value="<?=$this->post("news_label[$key]", $this->new['label'][$key]);?>" /><br />
            <?=$this->_m("Text");?>*:<br />
            <textarea class="textarea_tinymce textarea" rows="5" cols="70"
                      name="news_text[<?=$key;?>]"><?=$this->post("news_text[$key]", $this->new['text'][$key]);?></textarea>
         </p>

            <?}?>
         <br />
         <input name="news_reset" type="reset" value="<?=$this->_m("Obnovit")?>" />
         <input name="news_send" type="submit" value="<?=$this->_m("Odeslat")?>" />
         <?$this->includeTpl("help.phtml", true, array('file' => 'edit', 'module' => 'news'));?>
         <?if($this->edit){?>
         <input name="news_id" type="hidden" value="<?=$this->new['id_new']?>" />
         <?}?>

      </form>
   </div>
   <?$this->includeTpl("buttonback.phtml", true, array('link' => $this->l()->action()));?>
   <script>
      $(document).ready(function(){
         $("#editNewForm").tabs();
      });
   </script>
</div>
