<?
$this->addCssFile("style.css");
$this->includeTpl('sortLabel.phtml',false, null, 'articles');
$h1 = $this->category()->getName().$this->sortText;
echo $this->toolbox;
?>
<h1><?=$h1?></h1>
<div class="main-content-list">
   <?=$this->includeTpl('sort.phtml',false, null, 'articles')?>
   <div class="main-content-list-records">
   <?if(!empty ($this->articles)) {
      foreach ($this->articles as $article) {
         $showClass = $public = null;
         if($article->{Articles_Model_Detail::COLUMN_PUBLIC} == 0){
            $showClass = 'main-content-no-public';
            $public = $this->tr('Nezveřejněn');
         }
         ?>
   <div class="main-content-list-record <?=$showClass?>">
      <h2><a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
             title="<?=htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>"><?=htmlspecialchars($article->{Articles_Model_Detail::COLUMN_NAME})?>&nbsp;
            <span class="font-small">
             <?=  vve_date("%x %X", new DateTime($article->{Articles_Model_Detail::COLUMN_ADD_TIME}))?> - <?=$article->{Model_Users::COLUMN_USERNAME}?></span>
         </a><?='<span class="font-small">'.$public.'</span>'?>
      </h2>
      <?if((string)$article->{Articles_Model_Detail::COLUMN_ANNOTATION} != null){?>
         <div class="main-content-list-record-annotation"><?echo $article->{Articles_Model_Detail::COLUMN_ANNOTATION};?></div>
      <?} else {?>
         <div class="main-content-list-record-text"><?echo vve_tpl_truncate(strip_tags($article->{Articles_Model_Detail::COLUMN_TEXT}), 640);?></div>
      <?}?>
      <hr class="reseter" />
      <div class="main-content-showed"><?=$this->tr('Zobrazeno')?>:&nbsp;<?=$article->{Articles_Model_Detail::COLUMN_SHOWED}?>&times;</div>
      <div class="main-content-link-more">
         <a href="<?=$this->link()->route('detail', array('urlkey' => $article->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
            title="<?=$this->tr("více o").' '.$article->{Articles_Model_Detail::COLUMN_NAME}?>">[&nbsp;<?=$this->tr("Více")?>&nbsp;]</a>
      </div>
   </div>
     <?}
      echo $this->scrollComp;
   } else {
      echo ($this->tr('Není vložen žádný příspěvek'));
   }
   ?>
   </div>
   <?
      // rss ikony
   $feeds = new Component_Feed();
   $feeds->setConfig('feedLink', $this->link()->clear());
   $feeds->mainView();
   echo $feeds;
   ?>
</div>
