<div>
   <h2>
      <a href="<?=$this->l()->article($this->new['label'], $this->new['id_new'])?>" title="<?=$this->new['label']?>"><?=$this->new['label']?></a>
      <span class="smallFont"><?=strftime("%x %X", $this->new['time'])?> - <?=$this->new['username']?></span>
   </h2>
   <?=$this->new['text'];?>
   <?if(isset ($this->toolbox)){
      $this->includeTplObj($this->toolbox);
   }?>
   <?$this->includeTpl("buttonback.phtml", true, array('link' => $this->l()->article()));?>
</div>