<?php
$icon = null;
if ($this->panelObj()->getIcon() != null) {
    $icon = '<img src="' . Panel_Obj::getIconDir() . $this->panelObj()->getIcon() . '" alt="' . $this->panelObj()->getIcon() . '" />';
}
$backImg = null;
if ($this->panelObj()->getBackImage() != null) {
    $backImg = 'background-image: url(\'' . Panel_Obj::getBackImgDir() . $this->panelObj()->getBackImage() . '\');';
}
?>
<?php if ($this->rssLink != null) { ?>
    <a style="float: right" href="<?php echo $this->rssLink ?>" title="rss"><img src="<?php echo vve_get_tpl_file('icons/rss-icon.png', VVE_TPL_FILE_IMAGE) ?>" alt="rss" /></a>
<?php } ?>
<div class="panel-box-label"><?php echo $icon ?><a href="<?php echo $this->link() ?>" title="<?php echo htmlspecialchars($this->panelObj()->getName()) ?>"><?php echo $this->panelObj()->getName() ?></a></div>
<?php foreach ($this->articles as $new) { ?>
    <div class="panel-box-content">
        <div class="panel-box-label-article"><a href="<?php echo $this->link()->route('detail', array('urlkey' => $new->{Articles_Model_Detail::COLUMN_URLKEY})) ?>"
                                                title="<?php echo htmlspecialchars($new->{Articles_Model_Detail::COLUMN_NAME}) ?>"><?php echo vve_tpl_truncate($new->{Articles_Model_Detail::COLUMN_NAME}, 30) ?></a></div>
            <?php echo vve_tpl_truncate(strip_tags($new->{Articles_Model_Detail::COLUMN_TEXT}, VVE_SHORT_TEXT_TAGS), 150) ?>
        <div class="panel-box-link-more"><a href="<?php echo $this->link()->route('detail', array('urlkey' => $new->{Articles_Model_Detail::COLUMN_URLKEY})); ?>"
                                            title="<?php echo htmlspecialchars($new->{Articles_Model_Detail::COLUMN_NAME}) ?>"><?php echo $this->tr('Více') ?></a>
        </div>
    </div>
<?php } ?>
<div class="panel-box-link-more"><a href="<?php echo $this->link() ?>"
                                    title="<?php echo htmlspecialchars($this->category()->getLabel()) ?>"><?php echo $this->tr('Více novinek') ?></a></div>
