<?if($this->rssLink != null){?>
<a style="float: right" href="<?=$this->rssLink?>" title="rss"><img src="<?=vve_get_tpl_file('icons/rss-icon.png', VVE_TPL_FILE_IMAGE)?>" alt="rss" /></a>
<?}?>
<h3><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->category()
        ->getLabel())?>"><?=$this->category()->getLabel()?></a></h3>
<div>
   <?while ($new = $this->newArticles->fetch()) {?>
   <a href="<?=$this->link()->route('detail', array('urlkey'
                 => $new->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
      title="<?=htmlspecialchars($new->{Articles_Model_Detail::COLUMN_NAME})?>"
      ><?=vve_tpl_truncate($new->{Articles_Model_Detail::COLUMN_NAME},30)?></a><br />
   <div>
         <?=vve_tpl_truncate(strip_tags($new->{Articles_Model_Detail::COLUMN_TEXT}),150)?>
   </div>
   <p class="panelLinkMore">
      <a href="<?=$this->link()->route('detail', array('urlkey'
                 => $new->{Articles_Model_Detail::COLUMN_URLKEY}));?>"
         title="<?=htmlspecialchars($new->{Articles_Model_Detail::COLUMN_NAME})?>"><?=$this->_('Více')?></a>
   </p>

      <?}?>
</div>
   <p class="panelLinkMore">
      <a href="<?=$this->link()?>"
         title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->_('Více novinek')?></a>
   </p>
