<?
$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
?>
<?if($this->rssLink != null){?>
<a style="float: right" href="<?=$this->rssLink?>" title="rss"><img src="<?=vve_get_tpl_file('icons/rss-icon.png', VVE_TPL_FILE_IMAGE)?>" alt="rss" /></a>
<?}?>
<p class="panelLabel"><?=$icon?><a href="<?=$this->link()?>" title="<?=htmlspecialchars($this->panelObj()->getName())?>"><?=$this->panelObj()->getName()?></a></p>
<div style="<?=$backImg?>">
   <?while ($new = $this->newArticles->fetch()) {?>
   <a href="<?=$this->link()->route('detail', array('urlkey'
                 => $new->{Articles_Model_Detail::COLUMN_URLKEY}))?>"
      title="<?=htmlspecialchars($new->{Articles_Model_Detail::COLUMN_NAME})?>"
      ><?=vve_tpl_truncate($new->{Articles_Model_Detail::COLUMN_NAME},30)?></a><br />
   <div>
         <?=vve_tpl_truncate(strip_tags($new->{Articles_Model_Detail::COLUMN_TEXT}),150)?>
   </div>
   <p class="panelLinkMore">
      <a href="<?=$this->link()->route('detail', array('urlkey'
                 => $new->{Articles_Model_Detail::COLUMN_URLKEY}));?>"
         title="<?=htmlspecialchars($new->{Articles_Model_Detail::COLUMN_NAME})?>"><?=$this->_('Více')?></a>
   </p>

      <?}?>
</div>
   <p class="panelLinkMore">
      <a href="<?=$this->link()?>"
         title="<?=htmlspecialchars($this->category()->getLabel())?>"><?=$this->_('Více novinek')?></a>
   </p>
