<?
   $h1 = $this->category()->getName();
   $this->addPageTitle($h1);

?>
<h1><?$this->includeFile('tpl://engine:headline/icon.phtml'); echo $h1;?></h1>
<div class="main-content-list">
   <h2><?=$this->tr('Uložené nástroje')?></h2>
   <?if($this->tools != false){?>
   <table>
      <tr>
         <th scope="col" style="width: 5%;"><?=$this->tr('Ikona')?></th>
         <th scope="col" style="width: 5%;"><?=$this->tr('Název')?></th>
         <th scope="col" style="width: 40%;"><?=$this->tr('Adresa')?></th>
         <th scope="col" style="width: 5%;"><?=$this->tr('Pořadí')?></th>
         <th scope="col" style="width: 20%;"><?=$this->tr('Akce')?></th>
      </tr>
      <?foreach ($this->tools as $tool){?>
      <tr>
         <td><img src="<?=$this->iconsDir.$tool->{QuickTools_Model::COLUMN_ICON}?>" alt="<?=$tool->{QuickTools_Model::COLUMN_ICON}?>" /></td>
         <td><?=$tool->{QuickTools_Model::COLUMN_NAME}?></td>
         <td><?=$tool->{QuickTools_Model::COLUMN_URL}?></td>
         <td><?=$tool->{QuickTools_Model::COLUMN_ORDER}?></td>
         <td>edit/delete</td>
      </tr>
      <?}?>
   </table>
   <?} else {?>
      <p><?=$this->tr('Nejsou uloženy žádné nástroje.');?></p>
   <?}?>
   <?echo $this->toolbox;?>
</div>
