<?php 
   $h1 = $this->category()->getName();
   $this->addPageTitle($h1);

?>
<h1><?php $this->includeFile('tpl://engine:headline/icon.phtml'); echo $h1;?></h1>
<div class="main-content-list">
   <h2><?php echo $this->tr('Uložené nástroje')?></h2>
   <?php if($this->tools != false){?>
   <table>
      <tr>
         <th scope="col" style="width: 5%;"><?php echo $this->tr('Ikona')?></th>
         <th scope="col" style="width: 5%;"><?php echo $this->tr('Název')?></th>
         <th scope="col" style="width: 40%;"><?php echo $this->tr('Adresa')?></th>
         <th scope="col" style="width: 5%;"><?php echo $this->tr('Pořadí')?></th>
         <th scope="col" style="width: 20%;"><?php echo $this->tr('Akce')?></th>
      </tr>
      <?php foreach ($this->tools as $tool){?>
      <tr>
         <td><img src="<?php echo $this->iconsDir.$tool->{QuickTools_Model::COLUMN_ICON}?>" alt="<?php echo $tool->{QuickTools_Model::COLUMN_ICON}?>" /></td>
         <td><?php echo $tool->{QuickTools_Model::COLUMN_NAME}?></td>
         <td><?php echo $tool->{QuickTools_Model::COLUMN_URL}?></td>
         <td><?php echo $tool->{QuickTools_Model::COLUMN_ORDER}?></td>
         <td>edit/delete</td>
      </tr>
      <?php }?>
   </table>
   <?php } else {?>
      <p><?php echo $this->tr('Nejsou uloženy žádné nástroje.');?></p>
   <?php }?>
   <?php echo $this->toolbox;?>
</div>
