<?php 
if($this->tools != false){?>
<div id="quicktool-toolbox">
   <?php foreach ($this->tools as $tool) {
      ?><a href="<?php echo $tool->{QuickTools_Model::COLUMN_URL}?>" title="<?php echo $tool->{QuickTools_Model::COLUMN_NAME};?>"
         ><img src="<?php echo Url_Request::getBaseWebDir().$tool->{QuickTools_Model::COLUMN_ICON}?>" alt="<?php echo $tool->{QuickTools_Model::COLUMN_ICON}?>" 
            /></a><?php }?>
</div>
<?php }?>
