<?
$this->addPageTitle(strftime("%x", $this->dateFrom).' - '.strftime("%x", $this->dateTo));
$this->addPageHeadline(strftime("%x", $this->dateFrom).' - '.strftime("%x", $this->dateTo));

?>
<div>
   <p style="text-align: right">
      <a href="<?=$this->link()->route('archive')?>" title="<?=$this->_('Archiv')?>"><?=$this->_('Archiv')?></a>
   </p>

   <?while ($row = $this->actions->fetch()) {
      if($row->{Actions_Model_Detail::COLUMN_PUBLIC}) $class = "";
      else $class = 'nonPublicAction';
      ?>
   <div class="<?=$class?>">
      <h2><a href="<?=$this->link()->route('detail', array('urlkey' => $row->{Actions_Model_Detail::COLUMN_URLKEY}))?>"
             title="<?=$row->{Actions_Model_Detail::COLUMN_NAME}?>"
             ><?=$row->{Actions_Model_Detail::COLUMN_NAME}?></a></h2>
   <p>
      <?
      $startDate = strftime("%x", $row->{Actions_Model_Detail::COLUMN_DATE_START});
      $stopDate = strftime("%x", $row->{Actions_Model_Detail::COLUMN_DATE_STOP});
      print ($startDate);
      if($startDate != $stopDate) {
      print ("&nbsp;&mdash;&nbsp;");
         print ($stopDate);
      }
      if($row->{Actions_Model_Detail::COLUMN_TIME} != '00:00:00'|null){
         $time = new DateTime($row->{Actions_Model_Detail::COLUMN_TIME});
         print (",&nbsp;".$time->format("G:i"));
      }
      if($row->{Actions_Model_Detail::COLUMN_PLACE} != null){
         print ',&nbsp;'.$row->{Actions_Model_Detail::COLUMN_PLACE};
      }
      if((int)$row->{Actions_Model_Detail::COLUMN_PRICE} != null|0){
         printf(',&nbsp;'.strtolower($this->_('Vstupné: %d Kč')),$row->{Actions_Model_Detail::COLUMN_PRICE});
      }
      ?>
   </p>
   <p>
   <?
   if($row->{Actions_Model_Detail::COLUMN_IMAGE} != null){
      print (vve_tpl_image_tag($this->category()->getModule()->getDataDir()
              .$row[Actions_Model_Detail::COLUMN_URLKEY][Locale::getDefaultLang()].DIRECTORY_SEPARATOR
              .$row->{Actions_Model_Detail::COLUMN_IMAGE}, 'image', 50,50, 'actionImage'));
   }
   ?>
   <?=vve_tpl_xhtml_cut(strip_tags($row->{Actions_Model_Detail::COLUMN_TEXT},'<br><a><b><strong><em><i>'), 600);?>
   </p>
   <p style="text-align: right">
      <a href="<?=$this->link()->route('detail',
           array('urlkey' => $row->{Actions_Model_Detail::COLUMN_URLKEY}))?>"
           title="<?=$this->_('Více')?>"><?=$this->_('Více')?></a>
   </p>
   </div>

   <?}?>

   &laquo;<a href="<?=$this->linkBack?>" title="<?=$this->_('Vzad')?>"><?=$this->_('Vzad')?></a>&nbsp;&brvbar;&nbsp;
   <a href="<?=$this->linkNext?>" title="<?=$this->_('Vpřed')?>"><?=$this->_('Vpřed')?></a>&raquo;

   <?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('add_action', $this->_("Přidat akci"),
          $this->link()->route('add'),
          $this->_("Přidat novou akci"), "page_add.png");
      $this->includeTplObj($toolbox);
   }
   ?>
</div>