<?print ('<?xml version="1.0" encoding="utf-8"?>')?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?=Locale::getLang()?>" lang="<?=Locale::getLang()?>">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <meta name="author" content="Jakub Matas" />
      <meta name="keywords" content="<?=htmlspecialchars($this->pageKeywords)?>" />
      <meta name="description" content="<?=htmlspecialchars($this->pageDesc)?>" />
      <?if(Auth::isLoginStatic()) {?>
      <meta http-equiv="cache-control" content="no-cache" />
      <meta http-equiv="pragma" content="no-cache" />
      <meta http-equiv="pragma" content="-1" />
         <?}?>
      <meta name="Robots" content="index,follow" />

      <title><?print(VVE_WEB_NAME);?>{*-PAGE_TITLE-*}</title>

      <base href="<?=Url_Link::getMainWebDir()?>" />
      <link rel="stylesheet" type="text/css" href="<?=$this->style('style.css')?>" />
      <link rel="stylesheet" type="text/css" href="<?=$this->style('style-content.css')?>" />
      <link rel="stylesheet" href="<?=$this->style('style_opera.css')?>" type="text/nesmysl" />

      <!--[if lte IE 6]>
      <link rel="stylesheet" type="text/css" href="<?=$this->style('style_ie6.css')?>" />
      <script type="text/javascript" src="./jscripts/fix_eolas.js" defer="defer"></script>
      <![endif]-->

      {*-STYLESHEETS-*}
      {*-JAVASCRIPTS-*}
      <script type="text/javascript" src="jscripts/enginehelpers.js"></script>
   </head>
   <body id="pageTop">
      <div id="messages">
         <? $this->includeTpl("messages.phtml", true);?>
         <hr class="separator" />
      </div>
      <div id="moduleBox">
         <?if($this->pageNotFound) {
            $this->includeTpl("error404.phtml", true);
         } else {
            $this->includeTpl("modules.phtml", true);
         }
         ?>
         <hr class="separator" />
      </div><!-- col1pad -->
      <script type="text/javascript">
         $(document).ready(function(){
            $('form#ajaxForm').find('input[type=submit]').hide();
            window.parent.disableLoader();
         });
      </script>
   </body>
</html>
