<div class="article-tools">
   <?if(isset($vars['lastEditTime'])) {
      if(($vars['lastEditTime'] instanceof DateTime) == false) {
         $vars['lastEditTime'] = new DateTime($vars['lastEditTime']);
      }?>
   <div>
         <?=$this->tr('Naposled upraveno')?>&nbsp;<?=strftime("%x %X", $vars['lastEditTime']->format("U"))?>
         <?if(isset($vars['lastEditUser'])) {?>
      &nbsp;<?=$this->tr('uživatelem')?>&nbsp;<span style="font-style: italic"><?=$vars['lastEditUser']?></span>,
            <?}
         if(isset($vars['createdByUser'])) {
            printf($this->tr('Vytvořil: %s.'),$vars['createdByUser']);
         }
         if(isset($vars['showed'])) {
            echo ($this->tr('zobrazeno').":&nbsp;".$vars['showed']."&times;");
         }
         ?>

   </div>
   <br />
   <?}?>
   <?if(isset($vars['linkToPdf']) OR isset($vars['linkToTxt'])) { ?>
   <div class="donwload">
      <strong><?=$this->tr('Stáhnout')?>:</strong>
      <?if(isset($vars['linkToPdf'])) { ?>
   <a href="<?=$vars['linkToPdf']?>" title="<?=$this->tr('Stáhnout')?> pdf"><?=$this->tr('pdf (tisk)')?></a>&nbsp;
         <?}?>
      <?if(isset($vars['linkToTxt'])) { ?>
   <a href="<?=$vars['linkToTxt']?>" title="<?=$this->tr('Stáhnout')?> txt"><?=$this->tr('txt')?></a>&nbsp;
         <?}?>
      <?if(isset($vars['linkToHtml'])) { ?>
   <a href="<?=$vars['linkToHtml']?>" title="<?=$this->tr('Stáhnout')?> html"><?=$this->tr('html (tisk)')?></a>&nbsp;
         <?}?>
   </div>
   <br />
   <?}?>   
   
<div class="facebook-button">
   <?$this->addFile('https://connect.facebook.net/'.Locales::getLangLocale().'/all.js#xfbml=1');?>
   <fb:like href="" show_faces="false" layout="standard" width="380" action="recommend" font=""></fb:like>
</div>
<div class="share-button">
   <script type="text/javascript" src="https://apis.google.com/js/plusone.js">{lang: '<?=Locales::getLang()?>'}</script>
   <g:plusone size="small"></g:plusone>
<!-- AddThis Button BEGIN -->
   <div class="addthis_toolbox addthis_default_style">
      <a class="addthis_button_preferred_1"></a><a class="addthis_button_preferred_2"></a><a class="addthis_button_preferred_3"></a><a class="addthis_button_preferred_4"></a>
      <a class="addthis_button_compact"></a>
   </div>
   <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=xa-4cb6af65123b597d"></script>
</div>
<!-- AddThis Button END -->
<div class="nav-button">
   <a href="<?=$this->link()?>#pageTop" title="<?=$this->tr('Přejít na začátek')?>">
      &#94;&nbsp;<?=$this->tr('nahoru')?></a>
</div>
</div>
