<div class="article-tools">
   <?if(isset($vars['lastEditTime'])) {
      if(($vars['lastEditTime'] instanceof DateTime) == false) {
         $vars['lastEditTime'] = new DateTime($vars['lastEditTime']);
      }?>
   <div>
         <?=_('Naposled upraveno')?>&nbsp;<?=strftime("%x %X", $vars['lastEditTime']->format("U"))?>
         <?if(isset($vars['lastEditUser'])) {?>
      &nbsp;<?=_('uživatelem')?>&nbsp;<span style="font-style: italic"><?=$vars['lastEditUser']?></span>,
            <?}
         if(isset($vars['showed'])) {
            print (_('zobrazeno').":&nbsp;".$vars['showed']."&times;");
         }?>

   </div>
   <br />
   <?}?>
   <?if(isset($vars['linkToPdf']) OR isset($vars['linkToTxt'])) { ?>
   <div class="donwload">
      <strong><?=_('Stáhnout')?>:</strong>
      <?if(isset($vars['linkToPdf'])) { ?>
   <a href="<?=$vars['linkToPdf']?>" title="<?=_('Stáhnout')?> pdf">pdf (tisk)</a>&nbsp;
         <?}?>
      <?if(isset($vars['linkToTxt'])) { ?>
   <a href="<?=$vars['linkToTxt']?>" title="<?=_('Stáhnout')?> txt">txt</a>&nbsp;
         <?}?>
      <?if(isset($vars['linkToHtml'])) { ?>
   <a href="<?=$vars['linkToHtml']?>" title="<?=_('Stáhnout')?> html">html (tisk)</a>&nbsp;
         <?}?>
   </div>
   <br />
   <?}?>
<?
// sdílení
if(isset($this->shares)){$vars['shares'] = $this->shares;}
if(isset ($vars['shares']) AND $vars['shares'] instanceof Component_Share){
   echo $vars['shares'];
} else if(isset ($vars['shares']) AND is_array($vars['shares'])) {
   $shares = new Component_Share();
   $shares->setConfig('url', (string)$vars['shares']['url']);
   $shares->setConfig('title', (string)$vars['shares']['title']);
   echo $shares;
}
?>
   <br />
   <br />
   <iframe src="http://www.facebook.com/widgets/like.php?href=<?=urlencode($this->link());?>" scrolling="no" frameborder="0" style="border:none; width:450px; height:80px"></iframe>
</div>
