<?
if(isset ($vars['link'])){
   $link = (string)$vars['link'];
} else if(isset ($this->linkBack) AND $this->linkBack != null){
   $link = (string)$this->linkBack;
} else {
   $link = $this->l();
}

if(isset ($vars['text'])){
   $text = $vars['text'];
} else {
   $text = _("Zpět");
}
?>
<p class="buttonBack">
   <a href="<?=$link?>" title="<?=$text?>"><span>&laquo;</span>&nbsp;<?=$text?></a>
</p>
