<div class="message" id="coreErrMessage" style="background-image: url('<?=vve_get_tpl_file('icons/exclamation.png', VVE_TPL_FILE_IMAGE)?>')">
      <?
      $errors = CoreErrors::getErrors();
      foreach ($errors as $error) {?>
   <p>
            <?=$error["name"]?>: (<i><?=$error["code"]?></i>) <b><?=$error["message"]?></b>
            <?=_("soubor")?>: <?=$error["file"]?>, <?=_("řádek")?>: <?=$error["line"]?><br />
            <? if(VVE_DEBUG_ELEVE > 1) {
               foreach ($error["trace"] as $err) {?>
                  <?=$err["class"].$err["type"].$err["function"]."&nbsp;&nbsp;";
                  echo _("soubor").": <i>".$err["file"] ."</i>&nbsp;&nbsp;&nbsp;"._("řádek").": ".$err["line"];?>
      <br />
               <?}
            }?>
   </p>
      <?}?>
   <hr class="reseter" />
</div>
