<a href="javascript:popupHelp('<?php echo $this->pVar("mainWebDir");?>docs/modules/<?php echo $vars['module']?>/help/<?php echo $vars['file']?>.<?php echo $this->pVar("appLang")?>.xhtml');" title="help" onclick="">
   <img src="images/toolbox/help.png" alt="help" />&nbsp;<?php echo _("Nápověda")?>
</a>
<script type="text/javascript">
<!--
function popupHelp(file) {
   window.open( file, "Help","status = 1, height = 500, width = 300, resizable = 1, scrollbars = yes" )
}
//-->
</script>
