<?php  
$thin = (!isset($_COOKIE['cube_cms_helpbox']) || $_COOKIE['cube_cms_helpbox'] == 0) ? true : false;

?>
<div id="module-help-box" class="<?php echo $thin ? "thin" : null ?>">
<div class="headline"><span class="icon icon-help"></span> <?php echo $this->tr('Nápověda')?></div>
<a href="<?php echo $this->link()?>#hide-help" title="<?php  echo $thin ? $this->tr('Otevřít') : $this->tr('Schovat')?>" id="button-toggle-helpbox"
   ><span class="icon <?php echo $thin ? 'icon-info-circle' : 'icon-minus-square'?>"></span></a>
<div class="content"><?php echo $this->content?></div>
<?php  
$jq = new JsPlugin_JQuery();
$this->addJsPlugin($jq);
?>
<script type="text/javascript">
   $(document).ready(function(){
	   var $hbox = $('#module-help-box');
	   
	   $('#button-toggle-helpbox').click(function(e){
		   e.preventDefault();
		   if($hbox.hasClass('thin')){
			   $hbox.removeClass('thin');
			   $('.icon', this).removeClass('icon-info-circle').addClass('icon-minus-square');
            CubeCMS.Tools.setCookie("cube_cms_helpbox", 1);
		   } else {
			   $('.icon', this).removeClass('icon-minus-square').addClass('icon-info-circle');
			   $hbox.addClass('thin');
            CubeCMS.Tools.setCookie("cube_cms_helpbox", 0);
		   }
	   });
	});
</script>
</div>