<? // base metatags
Template_Core::setMetaTag('Robots', 'index,follow');
Template_Core::setMetaTag('generator', AppCore::ENGINE_NAME.' '.AppCore::ENGINE_VERSION.'.'.  AppCore::ENGINE_RELEASE);
// base styles
$this->addFile('css://style-handle.css');
?>
<!DOCTYPE html>
<html>
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1"> 
      {*-PAGE_META_TAGS-*}
      <title>{*-PAGE_TITLE-*}</title>
      <base href="<?=Url_Link::getMainWebDir()?>" />
      <link rel="canonical" href="<?=$this->link()->rmParam()?>" />
      <script type="text/javascript">
         /* <![CDATA[ */
         document.domain = '<?=Url_Request::getDomain();?>';
         document.lang = '<?=Locales::getLang()?>';
         /* ]]> */
      </script>
      {*-STYLESHEETS-*}
      {*-JAVASCRIPTS-*}
   </head>
   <body id="pageTop">
      <div data-role="page">
         <div data-role="header" data-theme="b"><?=VVE_WEB_NAME;?></div>
      
      <? $this->includeTpl("messages.phtml", true);?>
         <div class="content module-<?=  Category::getSelectedCategory()->getModule()->getName()?>">
            <? $this->includeTpl("modules.phtml", true); ?>
            <hr class="reseter" />
         </div>
      <div data-role="footer" data-theme="b">
         <? $this->includeTplObj($this->menuObj);?>
<!--         <a href="<?=$this->link()->clear(true);?>" title="<?=$this->tr("Domů")?>"><?=$this->tr("Domů")?></a>&nbsp;-->
      </div><!-- footwrap -->
      </div>
   </body>
</html>
