<?print ('<?xml version="1.0" encoding="utf-8"?>')?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?=Locale::getLang()?>" lang="<?=Locale::getLang()?>">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <?if(Auth::isLoginStatic()) {?>
      <meta http-equiv="cache-control" content="no-cache" />
      <meta http-equiv="pragma" content="no-cache" />
      <meta http-equiv="pragma" content="-1" />
      <?}?>
      <meta name="Robots" content="index,follow" />

      <title><?print(VVE_WEB_NAME);?>{*-PAGE_TITLE-*}</title>

      <base href="<?=Url_Link::getMainWebDir()?>" />

      <link rel="stylesheet" type="text/css" href="<?=$this->style('style.css')?>" />
      <link rel="stylesheet" type="text/css" href="<?=$this->style('style-content.css')?>" />
      <link rel="stylesheet" href="<?=$this->style('style_opera.css')?>" type="text/nesmysl" />

      <!--[if lte IE 6]>
      <link rel="stylesheet" type="text/css" href="<?=$this->style('style_ie6.css')?>" />
      <script type="text/javascript" src="./jscripts/fix_eolas.js" defer="defer"></script>
      <![endif]-->

      {*-STYLESHEETS-*}
      {*-JAVASCRIPTS-*}
      <?//Menu styly tady protože se přidává JsPlugin Jquery?>
      <link rel="stylesheet" type="text/css" href="<?=$this->style('ddsmoothmenu.css')?>" />
      <script type="text/javascript" src="jscripts/smoothmenu/ddsmoothmenu.js">
         /***********************************************
          * Smooth Navigational Menu- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
          * This notice MUST stay intact for legal use
          * Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
          ***********************************************/   
      </script>
      <script type="text/javascript">
         /* <![CDATA[ */
         ddsmoothmenu.init({
            mainmenuid: "smoothmenu1",
            orientation: "h",
            classname: "ddsmoothmenu",
            contentsource: "markup"});
         /* ]]> */
      </script>
   </head>
   <body id="pageTop">
      <? NavigationMenu_View::listView(); ?>
      <div id="bodywrap">

         <div id="headwrap">
            <a name="start_page"></a> <!-- PRESKAKOVANI POD FLASH-->
            <div id="menuBox">
               <div>
                  <form id="menuSearch" method="get" action="<?=$this->l()->clear(true);?>">
                     <p>
                        <input type="text" size="12" maxlength="50" name="search" value="<?=rawurldecode($this->get('search',null,false))?>" />
                        <input type="submit" value="<?=_("Hledej")?>" />
                     </p>
                  </form>
               </div>
               <div id="menuMain">
                  <? $this->includeTplObj($this->menuObj); ?> <!-- render menu-->
               </div>
               <hr class="separator" />
            </div>

            <div id="pageHeader">
            </div>

         </div><!-- headwrap -->
         <div id="colswrap">

            <div id="col1wrap" class="column">
               <div id="col1pad" class="<?if(!empty($this->panels['left'])) echo "col1pad_plusleft";?><?if(!empty($this->panels['left'])) echo " col1pad_plusright";?>">
                  <? $this->includeTpl("messages.phtml", true);
                  $this->includeTpl("navigation.phtml", true);?>
                  <h1>{*-PAGE_HEADLINE-*}</h1>
                  <?if($this->pageNotFound) {
                     $this->includeTpl("error404.phtml", true);
                  } else if($this->specialPage) {
                        $this->includeTplObj($this->specialPageTpl);
                     } else {
                        $this->includeTpl("modules.phtml", true);
                     }
                  ?>
                  <hr class="separator" />
               </div><!-- col1pad -->
            </div><!-- col1wrap -->

            <? // levy panel ?>
            <div id="col2wrap" class="column">
               <div id="col2pad">
                  <?
                  if(!empty($this->panels['left'])) {
                     foreach ($this->panels['left'] as $panelL) {?>
                  <div class="panel panelLeft">
                           <?$this->includeTplObj($panelL);?>
                  </div>
                     <?}
                  }?>
                  <hr class="separator" />
               </div><!-- col2pad -->
            </div><!-- col2wrap -->

            <? // pravy panel?>
            <div id="col3wrap" class="column">
               <div id="col3pad">
                  <?
                  if(!empty($this->panels['right'])) {
                     foreach ($this->panels['right'] as $panelR) {?>
                  <div class="panel panelRight">
                           <?$this->includeTplObj($panelR);?>
                  </div>
                     <?}
                  }?>
                  <hr class="separator" />
               </div><!-- col2pad -->
            </div><!-- col2wrap -->

            <div class="reseter">&nbsp;</div>
         </div><!-- colswrap -->

         <div class="reseter">&nbsp;</div>
         <div id="footwrap">
            <?
            if(!empty($this->panels['bottom'])) {
               foreach ($this->panels['bottom'] as $panelB) {?>
            <div class="panel" style="float:left; width: 200px;">
                     <?$this->includeTplObj($panelB);?>
            </div>
               <?}
            }?>
            <hr class="reseter" />
            <?//$this->includeTpl("login.phtml", true);//je v panelu?>
            <a href="<?=$this->link()->clear(true)->file('sitemap.html');?>" title="<?=_("mapa stránek")?>"><?=_("mapa stránek")?></a>
            <hr class="separator" />
         </div><!-- footwrap -->
      </div><!-- bodywrap /-->
      <div id="debug">
         <?
         if($this->showDebugConsole) {
            echo "<pre>";
            print_r($this);
            echo "</pre>";
         }

         if($this->debug == 2) {
            print ("Run functions: ".xdebug_get_function_count()."<br />");
            print ("Memory: ".xdebug_memory_usage()."<br />");
            print ("Memory PEAK: ".xdebug_peak_memory_usage()."<br />");
            print ("Index time: ".xdebug_time_index()."<br />");
         }
         ?>
      </div>
   </body>
</html>
