<?php
// base metatags
Template_Core::setMetaTag('Robots', 'noindex,nofollow');
Template_Core::setMetaTag('generator', AppCore::ENGINE_NAME . ' ' . AppCore::ENGINE_VERSION);
// base styles
$this->addFile('css://style.less');
$this->addFile('css://admin/admin.less');
// DEBUG
Template::addJsPlugin(new JsPlugin_JQuery());
if (VVE_DEBUG_LEVEL > 1) {
   $this->addFile('js://enginehelpers.js');
} else {
   $this->addFile('js://enginehelpers.min.js');
}

$this->addFile('js://base.js');
$this->addFile('js://bootstrap.min.js');
/* START PAGE */
?><!DOCTYPE html>
<html>
   <head>
      <?php $this->renderHeaderBase(); ?>
      <?php $this->renderHeaderRSS(); ?>
      <?php $this->renderHeaderCSSJS() ?>
      <script type="text/javascript">/* <![CDATA[ */<?php $this->renderHeaderScripts() ?>/* ]]> */</script>
   </head>
   <body id="pageTop" class="popup <?php echo $this->getBodyClasses(true); ?>" >
      <?php if (!Template_Core::isClosePopupWindow()) { ?>
         <header class="container">
            <span class="brand"><?php
               $title = Template_Core::getPageTitle();
               $last = array_pop($title);
               if (!empty($title)) {
                  ps($last . ' - ' . reset($title));
               } else {
                  ps($last);
               }
               ?></span>
            <?php if (isset($_GET['headerclose'])) { ?>
            <a href="#" class="button-cancel"><span class="icon icon-close"></span></a>
            <?php }?>
         </header>

         <section class="container">
            <div class="row">
               <div class="col-md-12">
                  <?php
                  $this->includeTpl("messages.phtml", true);
                  ?>
                  <div class="main-content module-<?php echo Category::getSelectedCategory()->getModule()->getName() ?> clearfix">
                     <?php 
                     $this->includeTpl("modules.phtml", true); 
                     ?>
                  </div>
                  <script type="text/javascript">
                        $(document).ready(function(){
                           $('form div[class^="col-md-"]').each(function(){
                              $(this).addClass( $(this).prop('class').replace('col-md-', 'col-xs-') );
                           });
                           $('.button-close-popup').on('click', function(){
                              
                           });
                        });
                     </script>
               </div>
            </div>
         </section>
         <?php if (isset($_GET['footerclose'])) { ?>
            <footer class="container">
               <button type="button" class="button-close-popup"><?php ps($this->tr('Zavřít')); ?></button>
            </footer>
            <?php
         }
         $this->renderBodyEnd();
         ?>
         <?php
      } else {
         ?>
         <script type="text/javascript">
            window.opener.<?php echo Url_Request::getPopupWindowCallback() ?>(<?php echo json_encode(Template_Core::getClosePopupWindowParams()) ?>);
            window.close();
         </script>
      <?php } ?>
   </body>
</html>
