<?
if(Template::browser()->isMobile() && ( !isset($_COOKIE['mobile'] ) || $_COOKIE['mobile'] == false ) ){
   $this->includeFile("tpl://index_handle.phtml");
   return;
}

// base metatags
Template_Core::setMetaTag('Robots', 'index,follow');
Template_Core::setMetaTag('generator', AppCore::ENGINE_NAME.' '.AppCore::ENGINE_VERSION.'.'.  AppCore::ENGINE_RELEASE);
if(VVE_FCB_APP_ID != null){
   Template_Core::setMetaTag('fb:app_id', VVE_FCB_APP_ID);
}
// detekce IE
Template::setPVar('IE',false);
$matches = array();
if(preg_match('/(?i)msie ([1-9])/i',$_SERVER['HTTP_USER_AGENT'], $matches)) {
   Template::setPVar('IE_WARN',false);
   if((int)$matches[1] < 7 AND !isset ($_COOKIE['show_ie_warning'])){
      Template::setPVar('IE_WARN',true);
   }
   Template::setPVar('IE',true);
}
// base styles
$this->addFile('css://style.less');
// DEBUG
if(VVE_DEBUG_LEVEL > 0){ $this->addFile('css://style-debug.css');}
Template::addJsPlugin(new JsPlugin_JQuery());
if(VVE_DEBUG_LEVEL > 1){ $this->addFile('js://enginehelpers.js');
} else { $this->addFile('js://enginehelpers.min.js');}

/* START PAGE */ 
?><!DOCTYPE html>
<html>
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <!-- {*-PAGE_META_TAGS-*}-->
      <title><!-- {*-PAGE_TITLE-*}--></title>
      <base href="<?=Url_Link::getMainWebDir()?>" />
      <link rel="canonical" href="<?=$this->link()->rmParam()?>" />
      <?//feedy RSS
      $model = new Model_Category();
      $model->setSelectAllLangs(false);
      $cats = $model->columns(array(Model_Category::COLUMN_NAME, Model_Category::COLUMN_URLKEY))
         ->where(Model_Category::COLUMN_FEEDS.' = 1', array())->records();
      $link = new Url_Link(true);
      foreach ($cats as $cat){
         $link->category($cat->{Model_Category::COLUMN_URLKEY})->file('rss.xml');
         ?><link rel="alternate" type="application/rss+xml" title="<?=VVE_WEB_NAME." - ".$cat->{Model_Category::COLUMN_CAT_LABEL}?>" href="<?=$link?>" />
      <?
      }?>
      <!--[if lte IE 6]>
      <link rel="stylesheet" type="text/css" href="<?=$this->style('style_ie6.css')?>" />
      <script type="text/javascript" src="./jscripts/fix_eolas.js" defer="defer"></script>
      <![endif]-->
      <!-- {*-STYLESHEETS-*} -->
      <!-- {*-JAVASCRIPTS-*} -->
      <? // admin nessesary files
      if(Category::getSelectedCategory()->getRights()->isWritable()){
         $this->addFile('css://style-admin.less');
         if(Auth::isAdmin()){ $this->addFile('js://admin/menu.js'); }
      }
      ?>
      <script type="text/javascript">
         /* <![CDATA[ */
         CubeCMS.init({
            domain : '<?=Url_Request::getDomain();?>',
            lang : '<?=Locales::getDefaultLang()?>',
            primaryLang : '<?=Locales::getDefaultLang()?>'
         });
         /* ]]> */
      </script>
   </head>
   <body id="pageTop" class="<?
         echo " module-".Category::getSelectedCategory()->getModule()->getName();
         echo " module-action-".$this->moduleAction;
         if(Auth::isAdmin()) echo ' with-admin-menu';
         ?>" >
      <? // admin menu
      if(Auth::isAdmin() AND $this->menuAdminObj != null AND !empty($this->menuAdminObj->menu)) $this->includeTplObj($this->menuAdminObj);
      ?>
      <? //NavigationMenu_View::listView(); ?>
      <div id="bodywrap" style="<?
                    $back = Category::getSelectedCategory()->getCatDataObj()->{Model_Category::COLUMN_BACKGROUND};
                    if($back != null){
                       echo "background-image: url('".Category::getImageDir(Category::DIR_BACKGROUND).$back."')"; }
                  ?>">
         <div id="headwrap">
            <a name="start_page"></a> <!-- PRESKAKOVANI POD FLASH-->
            <div id="menuBox">
               <div id="menuMain">
                  <? $this->includeTplObj($this->menuObj); ?> <!-- render menu-->
               </div>
               <hr class="separator" />
            </div>
            <div id="pageHeader">
            </div>
         </div><!-- headwrap -->
         <div id="colswrap">
            <div id="col1wrap" class="column">
               <div id="col1pad" class="<?if(!empty($this->panels['left'])) echo "col1pad_plusleft";?><?if(!Template::isFullWidth()) echo " col1pad_plusright";?>">
                  <?
                  $this->includeTpl("messages.phtml", true);
                  $navTpl = new Template_Navigation();
                  echo $navTpl;

                  if(Template::isTitlePage()){
                     echo HPSlideShow_View::getSlideshow();
                  }

                  if(VVE_DEBUG_LEVEL > 0){ echo "<pre>";Debug::printDebug(); echo "</pre>";Debug_Timer::printTimers(); }
                  ?>
                  <div class="main-content module-<?=  Category::getSelectedCategory()->getModule()->getName()?>">
                  <? $this->includeTpl("modules.phtml", true); ?>
                  <hr class="reseter" />
                  </div>
               </div><!-- col1pad -->
            </div><!-- col1wrap -->

            <? // levy panel ?>
            <div id="col2wrap" class="column">
               <div id="col2pad">
                  <div id="langs">
                     <?foreach (Template::pVar('appLangs') as $lang) {
                        $class = null;
                        if($lang['name'] == Locales::getLang()) $class = 'selected';
                        ?><a href="<?=$lang['link'];?>" title="<?=$lang['label'];?>" class="<?=$class?>"><?=$lang['name'];?></a>&nbsp;<?
                     }?>
                  </div>
                  <?echo CustomMenu_View::getMenu('left');?>
                  <?
                  if(!empty($this->panels['left'])) {
                     foreach ($this->panels['left'] as $panelL) {?>
                  <div class="panel panel-left panel-<?=$panelL->category()->getModule()->getName()?>">
                           <?$this->includeTplObj($panelL);?>
                  </div>
                     <?}
                  }?>
                  <hr class="reseter" />
               </div><!-- col2pad -->
            </div><!-- col2wrap -->

            <? // pravy panel
            if(!Template::isFullWidth()){?>
            <div id="col3wrap" class="column">
               <div id="col3pad">
                  <?echo Banners_View::getBanners('right')?>
                  <?
                  if(!empty($this->panels['right'])) {
                     foreach ($this->panels['right'] as $panelR) {?>
                  <div class="panel panel-right panel-<?=$panelR->category()->getModule()->getName()?>">
                           <?$this->includeTplObj($panelR);?>
                  </div>
                     <?}
                  }?>
                  <hr class="reseter" />
               </div><!-- col2pad -->
            </div><!-- col2wrap -->
            <?}?>

            <div class="reseter">&nbsp;</div>
         </div><!-- colswrap -->

         <div class="reseter">&nbsp;</div>
         <div>
            <?echo Banners_View::getBanners('bottom')?>
         </div>
         <div id="footwrap">
            <?
            if(!empty($this->panels['bottom'])) {
               foreach ($this->panels['bottom'] as $panelB) {?>
            <div class="panel" style="float:left; width: 200px;">
                     <?$this->includeTplObj($panelB);?>
            </div>
               <?}
            }?>
            <hr class="reseter" />
            <?echo CustomMenu_View::getMenu('bottom');?>
            <?//$this->includeTpl("login.phtml", true);//je v panelu?>
            <a href="<?=$this->link()->clear(true)->file('sitemap.html');?>" title="<?=$this->tr("Mapa stránek")?>"><?=$this->tr("Mapa stránek")?></a>&nbsp;
            <a href="<?=$this->link()->clear(true)->file('rss.html');?>" title="<?=$this->tr("Přehled rss zdrojů")?>"><?=$this->tr("Rss kanály")?></a>
            <hr class="reseter" />
         </div><!-- footwrap -->
      </div><!-- bodywrap /-->
      <hr class="reseter" />
      <div id="debug">
         <?
         if(VVE_DEBUG_LEVEL > 1) {
            if(function_exists('xdebug_get_function_count')){
               print ("Run functions: ".xdebug_get_function_count()."<br />");
               print ("Memory: ".xdebug_memory_usage()."<br />");
               print ("Memory PEAK: ".xdebug_peak_memory_usage()."<br />");
               print ("Index time: ".xdebug_time_index()."<br />");
            }
            print ("Exec time: ".$this->execTime."s<br />");
            print ("SQL Queries: ".Db_PDO::getCountQueries()."<br />");
            print ("Current user: ".Auth::getUserName()." - ".Auth::getUserId()."<br />");
         }
         ?>
      </div>
      <?if(defined('VVE_GOOGLE_ANALYTICS_CODE') && VVE_GOOGLE_ANALYTICS_CODE != null 
            && !in_array($_SERVER['REMOTE_ADDR'], explode(',', VVE_ANALYTICS_DISABLED_HOSTS))){?>
          <script type="text/javascript">
             /* <![CDATA[ */
             var _gaq = _gaq || [];
             _gaq.push(['_setAccount', '<?=VVE_GOOGLE_ANALYTICS_CODE?>']);
             _gaq.push(['_trackPageview']);

           (function() {
               var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
               ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
               var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
            /* ]]> */
         </script>
      <?}?>
      <?if(Category::getSelectedCategory()->getRights()->isWritable() || Template::pVar('showHelp') === true){
         $help = new Template_Help($this->moduleAction, Category::getSelectedCategory()->getModule());
         echo $help;      
      }?>
   </body>
</html>
