<!-- Sekce v menu  -->
<div class="chromestyle" id="chromemenu">
   <ul>
      <? foreach ($this->sectionsArray as $sec_key => $section) {?>
      <li>
         <? if($section["submenu"]){?>
         <a href="#" rel="dropmenu<?=$sec_key?>" title="<?=$section["slabel"]?>"><?=$section["slabel"]?></a>
         <? } else { ?>
         <a href="<?=$section["url"]?>" title="<?=$section["calt"]?>"><?=$section["clabel"]?></a>
         <? } ?>
      </li>
      <?}?>
   </ul>
</div>
<!-- Kategorie v podmenu -->
<? foreach ($this->categoryArray as $cat_key => $category) {?>
<div id="dropmenu<?=$cat_key?>" class="dropmenudiv">
   <? foreach ($category as $menuItem){?>
   <a href="<?=$menuItem["url"]?>" title="<?=$menuItem["calt"]?>"><?=$menuItem["clabel"]?></a>
   <? }?>
</div>
<? } ?>

<script type="text/javascript">
   cssdropdown.startchrome("chromemenu")
</script> 
