<?php

function CubeCMSAdminMenuReplaceIcon($icon)
{
   return str_replace(array(
       // png icons
       'page.png',
       'information.png',
       'cog.png',
       'pen.png',
           ), array(
       // fa icons
       'file-text-o',
       'info',
       'cog',
       'pen',
           ), $icon);
}

// funkce pro render menu
function CubeCMSAdminMenuRenderFunc($menuArr, $link, $ulParam, $renderHome = false)
{
//   $l = Locales::getUserLang();
   echo ("<ul " . $ulParam . ">\n");
   if($renderHome){
      echo '<li><a href="' . Url_Link::getBaseLink() . '"><span class="icon icon-fw icon-home"></span></a></li>';
   }
   foreach ($menuArr as $key => $item) {
      $class = 'menu_' . $key;
      if (sizeof($item['items']) > 1) {
         echo ('<li class="' . $class . '">');
         $label = $item['labels']['cs'];
         if (isset($item['labels'][Locales::getLang()])) {
            $label = $item['labels'][Locales::getLang()];
         }
         if (isset($item['labels'][Locales::getUserLang()])) {
            $label = $item['labels'][Locales::getUserLang()];
         }
         echo '<a href="#">';
         if ($item['icon'] != null) {
            $icon = CubeCMSAdminMenuReplaceIcon($item['icon']);
            if (strpos($icon, ".") !== false) { // je soubor?
               echo '<img src="' . (strpos($icon, "/") !== false ? $icon : '/images/icons/' . $icon) . '" alt="' . htmlspecialchars($label) . '" />';
            } else {
               echo '<span class="icon icon-fw icon-' . $icon . '"></span>';
            }
         }

         echo $label . '</a>';
         echo '<ul>';
         foreach ($item['items'] as $menuItem) {
            echo '<a href="' . $menuItem->getUrl() . '">';
            if ((string) $menuItem->getIcon() != null) {
               $icon = CubeCMSAdminMenuReplaceIcon($menuItem->getIcon());
               if (strpos($icon, ".") !== false) { // je soubor?
                  echo '<img src="' . (strpos($icon, "/") !== false ? $icon : '/images/icons/' . $icon) . '" alt="' . htmlspecialchars($menuItem->getName()) . '" />';
               } else {
                  echo '<span class="icon icon-fw icon-' . $icon . '"></span>';
               }
            }
            echo $menuItem->getName() . '</a>';
         }
         echo '</ul>';
//         echo $name.'</a>';
         echo ("</li>\n");
      } else if (sizeof($item['items']) == 1) {
         echo ('<li class="' . $class . '">');
         $menuItem = reset($item['items']);
         echo '<a href="' . $menuItem->getUrl() . '">';
         if ((string) $menuItem->getIcon() != null) {
            $icon = CubeCMSAdminMenuReplaceIcon($menuItem->getIcon());
            if (strpos($icon, ".") !== false) { // je soubor?
               echo '<img src="' . (strpos($icon, "/") !== false ? $icon : '/images/icons/' . $icon) . '" alt="' . htmlspecialchars($menuItem->getName()) . '" />';
            } else {
               echo '<span class="icon icon-fw icon-' . $icon . '"></span>';
            }
         }
         echo $menuItem->getName() . '</a>';
         echo ("</li>\n");
      } else {
         
      }
   }
   echo ("</ul>\n");
}
?>
<!-- Halvni menu sekce v menu  -->
<div id="adminMenuWrapper">
   <?php
   CubeCMSAdminMenuRenderFunc(Menu_Admin::getInstance()->getItems(Menu_Admin::POSITION_LEFT), $this->link(), 'class="dropdown"', true);
   if (class_exists("QuickTools_View")) {
//      QuickTools_View::renderTools();
   }
   CubeCMSAdminMenuRenderFunc(Menu_Admin::getInstance()->getItems(Menu_Admin::POSITION_RIGHT), $this->link(), 'class="dropdown right-menu"');
   ?>
</div>
