<?// Vypis hlasek
if(!empty ($this->messages)) { ?>
<div class="message infoMessage" id="messages">
   <img src="<?=Template::face(false)?>images/icons/accept.png" alt="message icon" width="16" />
      <? foreach ($this->messages as $message) {
         print ("<p>".$message . "</p>");
      }?>
   <hr class="reseter" />
   <script type="text/javascript">
      <!--
      setTimeout('document.getElementById("messages").style.display = "none"', 5000);
      -->
   </script>
</div>
<? }?>

{*-CORE_ERRORS-*}

<? // chyby modulu
if(!empty ($this->moduleErrors)) { ?>
<div class="message errorMessage">
   <img src="<?=Template::face(false)?>images/icons/error.png" alt="error icon" width="16" />
      <? foreach ($this->moduleErrors as $error) {
         print ("<p>"._("Chyba:")." ".$error ."</p>");
      }?>
   <hr class="reseter" />
</div>
<? }?>
