<?php 
if(empty($this->baseParts) && empty($this->extendedParts)){
   return;
}

$strArray = array( '<a href="'.$this->link(true)->clear(true).'">'.$this->tr('Domů').'</a>' );
foreach ($this->baseParts as $item) {
   $strArray[] = '<a href="'.$item['link'].'" title="'.htmlspecialchars($item['title']).'" class="'.($item['admin'] ? 'admin' : null).'">'.htmlspecialchars($item['name']).'</a>';
}
if(!empty($this->extendedParts)){
   foreach ($this->extendedParts as $item) {
      $strArray[] = '<a href="'.$item['link'].'" title="'.htmlspecialchars($item['title']).'" class="'.($item['admin'] ? 'admin' : null).'">'.htmlspecialchars($item['name']).'</a>';
   }
}
?>
<div id="breadcrumb">
   <?php  echo $this->tr('Právě se nacházíte:')?>
   <?php  echo implode(' > ', $strArray);?>
</div>
