<?php 
if(empty($this->baseParts) && empty($this->extendedParts)){
   return;
}

$strArray = array( '<li><a href="'.$this->link(true)->clear(true).'">'.$this->tr('Domů').'</a></li>' );
foreach ($this->baseParts as $item) {
   $strArray[] = '<li><a href="'.$item['link'].'" title="'.htmlspecialchars($item['title']).'" class="'.($item['admin'] ? 'text-danger' : null).'">'.htmlspecialchars($item['name']).'</a></li>';
}
if(!empty($this->extendedParts)){
   foreach ($this->extendedParts as $item) {
      $strArray[] = '<li><a href="'.$item['link'].'" title="'.htmlspecialchars($item['title']).'" class="'.($item['admin'] ? 'text-danger' : null).'">'.htmlspecialchars($item['name']).'</a></li>';
   }
}
?>
<ol id="breadcrumb" class="breadcrumb hidden-print">
   <?php  echo implode('', $strArray);?>
</ol>
