<?
/* 
 * Šablona pro fotogalerie
 */

// jquery galerka
$this->addJsPlugin(new JsPlugin_PiroBox());

$propName = $this->propName == null ? PhotoGalery_Model_Images::COLUMN_NAME : $this->propName;
$propAlt = $this->propAlt == null ? PhotoGalery_Model_Images::COLUMN_DESC : $this->propAlt;
$propFile = $this->propFile == null ? PhotoGalery_Model_Images::COLUMN_FILE : $this->propFile;

$dirBase = $this->imagesBaseDir != null ? $this->imagesBaseDir : $this->category()->getModule()->getDataDir(true).$this->websubdir;

$dirSmall = $this->imagesDirSmall != null ? $dirBase.$this->imagesDirSmall : $dirBase.Photogalery_Controller::DIR_SMALL.'/';
$dirMedium = $this->imagesDirMedium != null ? $dirBase.$this->imagesDirMedium : $dirBase.Photogalery_Controller::DIR_MEDIUM.'/';
$dirBig = $this->imagesDirBig != null ? $dirBase.$this->imagesDirBig : $dirBase.Photogalery_Controller::DIR_ORIGINAL.'/';


$images = $this->images;
$c = count($images);
if($c != 0){?>
   <div class="main-content-images">
      <?
      foreach ($images as $image) {
         $imgFile = isset($image->{$propFile}) ? $image->{$propFile} : $image[$propFile];
         ?>
         <a class="pirobox_gall image" rel="prettyPhoto[pp_gal]" href="<?=$dirMedium.$imgFile?>" title="<?=$image->{$propAlt}?>" >
            <img src="<?=$dirSmall.$imgFile?>" alt="<?=$image->{$propName}?>" />
         </a>
         <?
      }
      echo $this->toolboxImages;
      ?>
      <hr class="reseter" />
   </div>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){$().piroBox({slideShow : true,slideSpeed : 3});});
      /* ]]> */
   </script>
<?} else if($this->toolboxImages != null){?>
   <div class="admin-info-text">
      <?
      echo $this->tr('Galerie neobsahuje žádný obrázek.');
      echo $this->toolboxImages;
      ?>
   </div>
<?}?>