<h1><?php echo $this->tr('Seznam rss zdrojů');?></h1>
<div class="main-content-detail">
   <div class="main-content-text page-rsslist">
<?php if(count($this->sources) > 0){?>
<table>
   <?php 
   foreach ($this->sources as $source) {?>
   <tr>
      <th width="200"><?php echo $source['name']?></th>
      <td><a href="<?php echo $source['link']?>"
             title="<?php echo $this->tr('Zdroj k').' '.$source['name']?>"><?php echo $source['link']?></a></td>
   </tr>
   <?php }?>
   <tr>
      <td colspan="2"><br /></td>
   </tr>
   <tr>
      <th><?php echo $this->tr('Přehled všech kategorií')?></th>
      <td><a href="<?php echo $this->sourcesAll?>"
             title="<?php echo $this->tr('Zdroj ke všem kategoriím')?>"><?php echo $this->sourcesAll;?></a></td>
   </tr>
</table>

<?php } else {
   echo '<p>'.$this->tr('Stránka neobsahuje žádný rss zdroj.').'</p>';
}?>
   </div>
</div>
