<!--Sipky pro posun stranek-->
<?if($this->countAllPages > 1){?>
<div class="scroll_main">
<table>
<tr>
<td width="100" align="left">
<? //Sipka na zacatek
   if($this->activeButtonBegin){
      ?>
      <a href="<?=$this->pageLink()->rmParam('page')?>" title="<?=$this->tr("Začátek")?>">
      |&lt;
      </a>
   <?} else {?>
      |&lt;
   <?}?>
   &#032;&#032;

<? //Sipka na předchozí
   if($this->activeButtonPrevious){?>
      <a href="<?=$this->pageLink()->param('page', $this->selectedPage-1)?>" title="<?=$this->tr("Předchozí")?>">
         <span>&lt;&nbsp;<?=$this->tr("Předchozí")?></span>
      </a>
   <?} else {?>
      <span>&lt;&nbsp;<?=$this->tr("Předchozí")?></span>
   <?}?>
</td>
<td align="center">
   <? foreach ($this->pagesLeftSideArray as $number) {
      if($number == 1){
         $link = $this->pageLink()->rmParam('page');
      } else {
         $link = $this->pageLink()->param('page', $number);
      }
      ?>
      &nbsp;<a href="<?=$link;?>" title="<?=$number;?>"><?=$number;?></a>&nbsp;
   <?}?>
   [&nbsp;<?=$this->selectedPage.'/'.$this->countAllPages?>&nbsp;]
   <? foreach ($this->pagesRightSideArray as $number) {
      if($number == 1){
         $link = $this->pageLink()->rmParam('page');
      } else {
         $link = $this->pageLink()->param('page', $number);
      }
      ?>
      &nbsp;<a href="<?=$link;?>" title="<?=$number;?>"><?=$number;?></a>&nbsp;
   <?}?>
</td>
<td width="100" align="right">
<? //Sipka na další
   if($this->activeButtonNext){?>
      <a href="<?=$this->pageLink()->param('page', $this->selectedPage+1)?>" title="<?=$this->tr("Další")?>">
         <span><?=$this->tr("Další")?>&nbsp;&gt;</span>
      </a>
   <?} else {?>
      
      <span><?=$this->tr("Další")?>&nbsp;&gt;</span>
   <?}?>
   &#032;&#032;
<? //Sipka na konec
   if($this->activeButtonEnd){?>
      <a href="<?=$this->pageLink()->param('page', $this->countAllPages)?>" title="<?=$this->tr("Konec")?>">
      &gt;|
      </a>
   <?} else {?>
      &gt;|
   <?}?>
</td>
</tr>
</table>
<?/*
//if($this->ajaxBox != null){
$this->addJsPlugin(new JsPlugin_JQuery());
?>
<script type="text/javascript">
$('.scroll_main a').click(function(){
   $('.main-content').load(this.href+" .main-content", function(){
      alert('loaded');
   });
   return false;
});
</script>
<?
//}*/
?>
</div>
<?}?>