<!--Sipky pro posun stranek-->
<?php 
if($this->countAllPages > 1){?>
<div class="scroll_main">
<table>
<tr>
<td width="100" align="left">
<?php  //Sipka na zacatek
   if($this->activeButtonBegin){
      ?>
      <a href="<?php echo $this->pageLink()->rmParam($this->pageParam)?>" title="<?php echo $this->textStart?>">|&lt;</a>
   <?php } else {?>
      |&lt;
   <?php }?>
   &#032;&#032;

<?php  //Sipka na předchozí
   if($this->activeButtonPrevious){?>
      <a href="<?php echo $this->pageLink()->param($this->pageParam, $this->selectedPage-1)?>" title="<?php echo $this->textPrev?>">
         <span>&lt;&nbsp;<?php echo $this->textPrev?></span>
      </a>
   <?php } else {?>
      <span>&lt;&nbsp;<?php echo $this->textPrev?></span>
   <?php }?>
</td>
<td align="center">
   <?php  foreach ($this->pagesLeftSideArray as $number) {
      if($number == 1){
         $link = $this->pageLink()->rmParam($this->pageParam);
      } else {
         $link = $this->pageLink()->param($this->pageParam, $number);
      }
      ?>
      &nbsp;<a href="<?php echo $link;?>" title="<?php echo $number;?>"><?php echo $number;?></a>&nbsp;
   <?php }?>
   [&nbsp;<?php echo $this->selectedPage.'/'.$this->countAllPages?>&nbsp;]
   <?php  foreach ($this->pagesRightSideArray as $number) {
      if($number == 1){
         $link = $this->pageLink()->rmParam($this->pageParam);
      } else {
         $link = $this->pageLink()->param($this->pageParam, (int)$number);
      }
      ?>
      &nbsp;<a href="<?php echo $link;?>" title="<?php echo $number;?>"><?php echo $number;?></a>&nbsp;
   <?php }?>
</td>
<td width="100" align="right">
<?php  //Sipka na další
   if($this->activeButtonNext){?>
      <a href="<?php echo $this->pageLink()->param($this->pageParam, $this->selectedPage+1)?>" title="<?php echo $this->textNext?>">
         <span><?php echo $this->textNext?>&nbsp;&gt;</span>
      </a>
   <?php } else {?>
      
      <span><?php echo $this->textNext?>&nbsp;&gt;</span>
   <?php }?>
   &#032;&#032;
<?php  //Sipka na konec
   if($this->activeButtonEnd){?>
      <a href="<?php echo $this->pageLink()->param($this->pageParam, $this->countAllPages)?>" title="<?php echo $this->textEnd?>">&gt;|</a>
   <?php } else {?>
      &gt;|
   <?php }?>
</td>
</tr>
</table>
<?php /*
//if($this->ajaxBox != null){
$this->addJsPlugin(new JsPlugin_JQuery());
?>
<script type="text/javascript">
$('.scroll_main a').click(function(){
   $('.main-content').load(this.href+" .main-content", function(){
      alert('loaded');
   });
   return false;
});
</script>
<?php 
//}*/
?>
</div>
<?php }?>