<!--Sipky pro posun stranek-->
<?
if($this->countAllPages > 1){?>
<div class="scroll">
   <div class="left-box">
   <? //Sipka na předchozí
   if($this->activeButtonPrevious){?>
      <a href="<?=$this->pageLink()->param($this->pageParam, $this->selectedPage-1)?>" title="<?=$this->tr('Předchozí')?>">
         <?=$this->tr('Předchozí')?>
      </a>
   <?} else {?>
      <span><?=$this->tr('Předchozí')?></span>
   <?}?>
   </div>
   
   <div class="right-box">
      <? //Sipka na další
      if($this->activeButtonNext){?>
      <a href="<?=$this->pageLink()->param($this->pageParam, $this->selectedPage+1)?>" title="<?=$this->tr('Další')?>">
         <?=$this->tr('Další')?>
      </a>
   <?} else {?>
      <span><?=$this->tr('Další')?></span>
   <?}?>
   </div>
   
   <div class="numbers">
      <? 
      // left numbers
      foreach ($this->pagesLeftSideArray as $number) {
         if($number == 1){
            $link = $this->pageLink()->rmParam($this->pageParam);
         } else {
            $link = $this->pageLink()->param($this->pageParam, $number);
         }
         echo "&nbsp;<a href=\"$link\" title=\"$number\">$number</a>&nbsp;";
      }
      
      // center numbers
      echo "[{$this->selectedPage}/{$this->countAllPages}]";
   
      // right numbers
      foreach ($this->pagesRightSideArray as $number) {
         if($number == 1){
            $link = $this->pageLink()->rmParam($this->pageParam);
         } else {
            $link = $this->pageLink()->param($this->pageParam, (int)$number);
         }
         echo "&nbsp;<a href=\"$link\" title=\"$number\">$number</a>&nbsp;";
      }
      ?>
   </div>
</div>
<?}?>