<h1>
   <span><?php echo _("hledání výrazu").sprintf(' "%s"',$this->articleName())?></span>
</h1>
<div class="content">
   <h2>
      <?php 
      if($this->searchResultsCount == 0) {
         printf(_("Nebyl nalezen žádný výsledek. Zkontrolujte hledaný výraz."));
      } else if($this->searchResultsCount == 1) {
            printf(_("Byl nalezen %u výsledek"), $this->searchResultsCount);
         } else if($this->searchResultsCount > 1 AND $this->searchResultsCount < 5) {
               printf(_("Byly nalezeny %u výsledky"), $this->searchResultsCount);
            } else {
               printf(_("Bylo nalezeno %u výsledeků"), $this->searchResultsCount);
            }
      ?>
   </h2>
</div>
<div id="searchResults">
   <?php 
   if(!empty ($this->searchResults)) {
      foreach ($this->searchResults as $result) {?>
   <div class="searchResult content">
      <h2>
         <a href="<?php echo $result['category_url'];?>" title="<?php echo $result['category']?>"><?php echo $result['category']?></a>
               <?php if(!empty ($result['article'])) {?>
         &nbsp;&raquo;&nbsp;
         <a href="<?php echo $result['url']?>" title="<?php echo $result['category']?>"><?php echo $result['article']?></a>
               <?php }?>
      </h2>
      <div>
               <?php echo $result['text']?><br />
               <?php echo _("více")?>: <a href="<?php echo $result['url']?>" title="<?php echo $result['category']." ".$result['article']?>"><?php echo $result['url']?></a>
      </div>
   </div>
      <?php }?>
   <div class="contentLine"></div>
   <?php }?>
</div>
