<h1><?=_("Mapa stránek")?> <?=$this->pageTitle;?></h1>
<div class="moduleBox">
<?foreach ($this->sitemapPages as $section) {?>
   <ul>
      <li><?=$section['name']?>
         <ul>
            <?foreach ($section['categories'] as $category) {?>
            <li>
               <a href="<?=$category['url']?>" title="<?=$category['name']?>"><?=$category['name']?></a>
               <?if(!empty ($category['results'])){?>
               <ul>
               <?foreach ($category['results'] as $result) {?>
                  <li>
                     <a href="<?=$result['loc']?>" title="<?=$result['name']?>"><?=$result['name']?></a>
                  </li>
               <?}?>
               </ul>
               <?}?>
            </li>
            <?}?>
         </ul>
      </li>
   </ul>
<?}?>
</div>