<div class="userfiles_file"  id="userfiles_file<?=$this->file['id_file']?>">
   <div class="userfiles_file_header" onClick="showFileDetail(this);">
      <a style="float:right"><?=_("zobrazit detail")?></a>
      <img class="userfiles_file_header_exp_img" src="images/buttons/expand2.gif" alt="expand image" />
      <?if($this->file['type'] == 'image') {?>
         <?=imageTag($this->file['link_small'],"file ".$this->file['file'],false,15);?>
         <!--<img src="<?=$this->file['link_small']?>" alt="file <?=$this->file['file']?>" width="80" />-->
      <?} else if($this->file['type'] == 'flash') {?>
         <?=imageTag("images/icons/flashfile.png","file ".$this->file['file'],false,15);?>
         <!--<img src="images/icons/flashfile.png" alt="file <?=$this->file['file']?>" width="80" />-->
      <?} else {?>
         <!--<img src="images/icons/textfile.png" alt="file <?=$this->file['file']?>" width="80" />-->
         <?=imageTag("images/icons/textfile.png","file ".$this->file['file'],false,15);?>
      <?}?>
      &nbsp;<?=$this->file['file']?>&nbsp;(<?printf("%.2f KB", $this->file['size']/1024)?>)
      <?if($this->file['type'] == 'image' OR $this->file['type'] == 'flash') {
         echo "("._("rozměry").": ".$this->file['width']." x ".$this->file['height']." px)";
      }?>
   </div>
   <div class="userfiles_file_detail">
      <table>
         <tr>
            <td rowspan="3">
               <?if($this->file['type'] == 'image') {?>
               <a href="<?=$this->file['link_show']?>" rel="lightbox" title="<?=$this->file['file']?>" rel="lightbox">
               <?=imageTag($this->file['link_small'],"file ".$this->file['file'],120,120);?>
               </a>
               <?}?>
            </td>
            <td>
               <span class="smallFont">
                  <label><?=_("Odkaz pro zobrazení")?></label><br />
                  <a href="<?=$this->file['link_show']?>" title="<?=_("Odkaz pro zobrazení")
                     ." - ".$this->file['file']?>" target="_blank"><?=$this->file['link_show']?></a>
               </span>
            </td>
         </tr>
         <tr>
            <td>
               <label><?=_("Odkaz pro stažení")?></label><br />
               <span class="smallFont">
               <a href="<?=$this->file['link_download']?>" title="<?=_("Odkaz pro stažení")
                  ." - ".$this->file['file']?>"><?=$this->file['link_download']?></a>
               </span>
            </td>
         </tr>
         <tr>
            <td align="right">
               <?if($this->file['type'] == 'image') {?>
                  <form action="<?=$this->l()?>" method="post" onsubmit="return deleteUserFilesFile(
                     '<?=_("Opravdu smazat obrázek")?> - <?=$this->file['file']?>', <?=$this->file['id_file']?>);">
                     <input type="hidden" name="userfiles_file_id" value="<?=$this->file['id_file']?>" />
                     <input type="submit" name="userfiles_delete" value="<?=_("Smazat")?>" />
                  </form>
               <?} else {?>
                  <form action="<?=$this->l()?>" method="post" onsubmit="return deleteUserFilesFile(
                     '<?=_("Opravdu smazat soubor")?> - <?=$this->file['file']?>', <?=$this->file['id_file']?>);">
                     <input type="hidden" name="userfiles_file_id" value="<?=$this->file['id_file']?>" />
                     <input type="submit" name="userfiles_delete" value="<?=_("Smazat")?>" />
                  </form>
               <?}?>
            </td>
         </tr>
      </table>
   </div>
</div>