<div class="userFiles">
<div id="uploadUserFilesForm">
   <h5><?=_("Uživatelské soubory")?> (<span id="userFilesCount"><?=$this->numRows?></span>)</h5>
   <form action="<?=$this->ajaxLink->action('addFile')->param('idArticle', $this->idArticle)?>" method="post" enctype="multipart/form-data" target="upload_target" onsubmit="startUploadUserFile();" >
      <label><?=_("Soubor");?>*:</label>
      <input name="userfiles_new_file" type="file" />
      <input name="userfiles_idArticle" type="hidden" value="<?=$this->idArticle?>" />
      <input type="submit" name="userfiles_send_file" value="<?=_("Nahrát")?>" />
      <img id="upload_userfile_process" src="images/progress.gif" alt="loading" width="16" style="display:none"/>&nbsp;
      <span id="userfile_upload_result"></span>
   </form>
   <iframe id="upload_target" name="upload_target" src="#" style="width:0;height:0;border:0px solid #fff;"></iframe>

</div>

<?// výpis souborů?>
<div id="userfiles_fileslist">
   <?foreach ($this->filesArray as $file) {
      $this->fileTpl->file = $file;
      $this->includeTplObj($this->fileTpl);
   }?>
</div>


   <script language="javascript" type="text/javascript">
<!--
   $(document).ready(function() {
      setLightBox();
      $(".userfiles_file_detail").hide();
   });

   // zobrazení detailu
   function showFileDetail(obj){
      if(obj.opened == true){
         $(obj).next().slideUp(100);
         $(obj).children("img.userfiles_file_header_exp_img").attr("src", "images/buttons/expand2.gif");
         obj.opened = false;
      } else {
         $(obj).next().slideDown(100);
         $(obj).children("img.userfiles_file_header_exp_img").attr("src", "images/buttons/collapse2.gif");
         obj.opened = true;
      }
      return false;
   }

   // funkce pro nahrání obrázku
   function startUploadUserFile(){
      $("#upload_userfile_process").css("display", "inline");
      return true;
   }

   // funkce volaná po nahrání
   function stopUploadUserFile(successMessage, insertHtml, countFiles){
      $("#userfile_upload_result").text(successMessage);
      $("#upload_userfile_process").css("display", "none");
      var newObj = $(insertHtml);
      newObj.hide();
      newObj.children("div.userfiles_file_detail").hide();
      $("#userfiles_fileslist").prepend(newObj);
      newObj.slideDown("normal");
      $("#userFilesCount").text(countFiles);
      setLightBox();
      return true;
   }

   // funkce pro mazání obrázku
    function deleteUserFilesFile(qmsg, idF){
       if(confirm(qmsg)){
          $.ajax({
              type: "POST",
              url: "<?=$this->ajaxLink->action('deleteFile')?>",
              data: {
                  idFile : idF},
              success: function(msg){
                 if(msg != false){
                    $("#userfiles_file"+idF).slideUp("normal",
                      function callback() {
                          $(this).remove(); // dom element
                          setLightBox();
                      });
                  } else {
                     alert(msg+"<?=_("Soubor se nepodařilo smazat")?>");
                  }
            }
         });
      }
      return false;
   }

   // funkce znovu vatvoří lightbox
   function setLightBox(){
      $('a[rel*=lightbox]').lightBox();
   }
   -->
</script>
</div>