<li class="open" id="rootDir" rel="root" title="<?php echo VVE_DATA_DIR?>"><a href="#"><ins>&nbsp;</ins>data</a>
   <ul>
      <?php 
      function printDirs($dirList, $prefix, $writableDirs) {
         foreach ($dirList as $key => $dir) {
            $d = $prefix.URL_SEPARATOR.$key;
            $wr = 'readable';
            if(in_array($d, $writableDirs)) $wr = "editable";

            print ('<li rel="'.$wr.'" title="'.$d.'"><a href="#"><ins>&nbsp;</ins>'.$key.'</a>');
            if(!empty ($dir['childs'])) {
               print ('<ul>');
               printDirs($dir['childs'], $d, $writableDirs);
               print ('</ul>');
            }
            print('</li>');
         }
      }
      printDirs($this->dirs, VVE_DATA_DIR, $this->wrdirs);
      ?>
   </ul>
</li>
