<?php
header( 'Expires: Mon, 26 Jul 1997 05:00:00 GMT' );
header( 'Last-Modified: ' . gmdate( 'D, d M Y H:i:s' ) . ' GMT' );
header( 'Cache-Control: no-store, no-cache, must-revalidate' );
header( 'Cache-Control: post-check=0, pre-check=0', false );
header( 'Pragma: no-cache' );
// vatvoření základních url

$str = preg_replace("/jscripts(.*)$/", '', $_SERVER['SCRIPT_NAME']);
$pluginUrl = "http://".$_SERVER['SERVER_NAME'].$str."jsplugin/tinymce/cat-".$_GET['cat']."/";

?>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="pragma" content="-1" />
<script type="text/javascript" src="../tiny_mce_popup.js"></script>
<script type="text/javascript" src="../../jquery/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="../../jquery/jquery.cookie.js"></script>
<script type="text/javascript" src="../../jquery/jquery.hotkeys.js"></script>
<script type="text/javascript" src="../../jquery/jquery-ui-1.7.UICore.min.js"></script>
<script type="text/javascript" src="../../jquery/jquery-ui-1.7.Draggable.min.js"></script>
<script type="text/javascript" src="../../jquery/jquery-ui-1.7.Droppable.min.js"></script>
<script type="text/javascript" src="../../jquerytree/jquery.tree.min.js"></script>
<!--<script type="text/javascript" src="../../jquerytree/plugins/jquery.tree.contextmenu.js"></script>-->
<script type="text/javascript" src="../../jquerytree/plugins/jquery.tree.cookie.js"></script>
<script type="text/javascript" src="../../jquerytree/plugins/jquery.tree.hotkeys.js"></script>
<script type="text/javascript" src="tiny_mce_files_functions.js"></script>
<style type="text/css">
   #directoryList, #fileList {
      background:white none repeat scroll 0 0;
      border:1px solid gray;
      float:left;
      font-size:10px !important;
      height:245px;
      width: 100%;
      overflow:auto;
   }

   #directoryList {
      width:200px;
   }

   #mainTable th {
      text-align:left;
      font-size: 10pt !important;
   }

   a img {
      border:1px solid gray;
   }

   a.search {
      color:green !important;
   }

   /* styly textu */
   #fileList table th {
      font-size:10px !important;
      text-align:left;
   }

   tr.file td {
      border:1px solid transparent;
      border-top-color:gray;
      padding:3px;
      cursor:pointer;
   }

   tr.clicked{
      background:#BEEBFF none repeat scroll 0 0;
      -moz-background-clip:border;
      -moz-background-inline-policy:continuous;
      -moz-background-origin:padding;
   }

   span.fileLabel {
      color:gray;
   }

   .file div {
      height:75px;
   }

   input[type="image"], input[type="hidden"] {
      border:none;
      background-color:transparent;
   }

   #processing{
      visibility:hidden;
      text-align:center;
      margin:0px;
      padding:0px;
   }

   #operationResult {
      background-color: #d1e8ff;
   }
</style>
<script language="javascript" type="text/javascript">
   // počáteční nastavení
   tinyMCEPopup.onInit.add(FileBrowserDialogue.init, FileBrowserDialogue);
</script>
<table style="" id="mainTable">
   <tr>
      <th>Adresáře:</th>
      <th colspan="2">Soubory:</th>
   </tr>
   <tr valign="top">
      <td width="200">
         <input value="" type="text" size="10" />
         <input onclick="$.tree.focused().search($(this).prev().val())" value="Hledat" type="button" />
      </td>
      <td width="260">
         <span>Cesta:&nbsp;</span><span id="actualDir"></span>
      </td>
      <td width="270">
         <span>Soubor:&nbsp;</span><span id="actualFile"></span>
      </td>
   </tr>
   <tr valign="top">
      <td>
         <div id="directoryList"></div>
      </td>
      <td colspan="2">
         <div id="fileList"></div>
      </td>
   </tr>
   <tr valign="top">
      <td>
         <div>
            <span>Složku:</span>
            <input type="image" src="../../../images/icons/folder_add.png"
                   title="Vytvořit složku" onclick="FileBrowserDirsFunctions.createDir()" />
            <input type="image" src="../../../images/icons/folder_delete.png"
                   title="Smazat složku" onclick="FileBrowserDirsFunctions.removeDir()" />
            <input type="image" src="../../../images/icons/folder_edit.png"
                   title="Přejmenovat složku" onclick="FileBrowserDirsFunctions.renameDir()" />
            <input type="image" src="../../../images/icons/view-refresh.png"
                   title="Obnovit složky" onclick="FileBrowserDirsFunctions.loadDirs();" />
         </div>
      </td>
      <td></td>
      <td align="right">
         <span>Zaškrtnuté:</span>
         <input type="image" src="../../../images/icons/delete.png"
                title="Smazat označené soubory" onclick="FileBrowserFilesFunctions.removeCheckedFiles()" />
      </td>
   </tr>
   <tr>
      <td colspan="3">
         <div>
            <form id="uploadForm" action="<?=$pluginUrl?>uploadFile.html" method="post" enctype="multipart/form-data"
                  target="upload_target" onsubmit="FileBrowserFilesFunctions.startUpload();"
                  style="display:inline;">
               <label for="newfile">Nahrát soubor:</label>
               <input id="newfile" name="newf_File" type="file" />
               <input id="newfileDir" name="newf_Dir" type="hidden" value="" />
               <input id="newfileType" name="newf_ListType" type="hidden" value="" />
               <input type="submit" name="newf_Upload" value="Nahrát" />
            </form>
            <span id="processing"><img src="../../../images/progress.gif" alt="loading..." width="16"/></span>
            <iframe id="upload_target" name="upload_target"
                    style="position:absolute;width:0;height:0;border:0px solid #fff;visibility:hidden;display:none;"></iframe>
         </div>
      </td>
   </tr>
   <tr>
      <td colspan="2">
         <span id="operationResult"></span>
      </td>
      <td align="right">
         <form name="form">
            <input type="button" value="Vložit" onClick="FileBrowserDialogue.submitFile();" />
         </form>
      </td>
   </tr>
</table>