<div class="banners banners-in_articles">
<span class="title"><?=$this->tr('Reklama');?></span>
<?php
foreach ($this->banners as $banner) {
   $linkClick = (string)$this->linkClick->param('bid', $banner->{Banners_Model::COLUMN_ID});
   // co je to za soubor ?
   if(pathinfo($banner->{Banners_Model::COLUMN_FILE}, PATHINFO_EXTENSION) == 'swf'){
      $flashUrl = $this->dir.$banner->{Banners_Model::COLUMN_FILE}."?"
              .http_build_query( array( 'clickthru' => $linkClick, 'clickTAG' => $linkClick ));
      echo vve_tpl_flash($flashUrl, 200, 100);
   } else {
      ?>
   <a href="<?=$linkClick;?>" 
      title="<?ps($banner->{Banners_Model::COLUMN_NAME})?>"
      rel="nofollow" class="<?if($banner->{Banners_Model::COLUMN_NEW_WINDOW}){echo "link-external";}?>"
      ><img src="<?=$this->dir.$banner->{Banners_Model::COLUMN_FILE}?>" height="100"
           alt="<?ps($banner->{Banners_Model::COLUMN_NAME})?>" /></a>
   <?
   }
}
?>
</div>