<div class="banners banners-in_articles">
<span class="title"><?php echo $this->tr('Reklama');?></span>
<?php
foreach ($this->banners as $banner) {
   $linkClick = (string)$this->linkClick->param('bid', $banner->{Banners_Model::COLUMN_ID});
   // co je to za soubor ?
   if(pathinfo($banner->{Banners_Model::COLUMN_FILE}, PATHINFO_EXTENSION) == 'swf'){
      $flashUrl = $this->dir.$banner->{Banners_Model::COLUMN_FILE}."?"
              .http_build_query( array( 'clickthru' => $linkClick, 'clickTAG' => $linkClick ));
      echo vve_tpl_flash($flashUrl, 200, 100);
   } else {
      if($banner->{Banners_Model::COLUMN_URL} != null){?>
         <a href="<?php echo $linkClick;?>"
            title="<?php ps($banner->{Banners_Model::COLUMN_NAME})?>"
            rel="nofollow" class="<?php if($banner->{Banners_Model::COLUMN_NEW_WINDOW}){echo "link-external";}?>"><?php 
      }
      ?><img src="<?php echo $this->dir.$banner->{Banners_Model::COLUMN_FILE}?>" height="100"
           alt="<?php ps($banner->{Banners_Model::COLUMN_NAME})?>" /><?php 
      if($banner->{Banners_Model::COLUMN_URL} != null){?></a><?php }?>
   <?php 
   }
}
?>
</div>