<?php 
$this->addJsPlugin(new JsPlugin_JQueryCSS());
$this->addFile("css://maplocations:style.less");
$this->addPageTitle($this->tr('Seznam míst'));
echo $this->toolbox;
?>
<h1><?php echo $this->category()->getName().' - '.$this->tr('Seznam míst')?></h1>
<div class="main-content-list cubecms-widget cubecms-list-blocks">
   <?php if(!empty ($this->locations)) {
   foreach ($this->locations as $loc) {
      ?>
   <div class="main-content-list-record cubecms-list-block clearfix">
      <div class="header">
         <?php 
         if($loc->toolboxItem){
            $loc->toolboxItem->setTemplate(Template_Toolbox2::TEMPLATE_INLINE);
            echo $loc->toolboxItem;
         }
         ?>
         <h2><?php echo $loc->{MapLocations_Model::COLUMN_NAME}?></h2>
      </div>
      <div class="content">
            <div class="main-content-list-record-image">
               <img src="<?php echo $this->category()->getModule()->getDataDir(true).$loc->{MapLocations_Model::COLUMN_IMAGE}?>"
                    alt="<?php echo $loc->{MapLocations_Model::COLUMN_NAME}?>"/>
            </div>
         <?php 
         $cnt = null;
         $renderImagesAfter = strpos((string)$loc->{MapLocations_Model::COLUMN_TEXT}, '[images]') === false;
         $images = $loc->getImages();
         if(!empty($images)){
            ob_start();
            foreach ($images as $img) {
               ?> 
               <img src="<?php echo Utils_Image::cache($this->category()->getModule()->getDataDir().$loc->getDataDir().DIRECTORY_SEPARATOR.$img, 100, 100, true)?>" alt="" />
               <?php
            }
            $cnt = ob_get_clean();
         }
         echo str_replace('[images]', $cnt, $loc->{MapLocations_Model::COLUMN_TEXT});
         if($renderImagesAfter){
            echo $cnt;
         }
         ?>
      </div>
   </div>
   <?php }} else {?>   
   <div class="main-content-list-record ui-widget">
      <div class="ui-widget-content"><?php echo $this->tr('Źádné místo nebylo přidáno')?></div>
   </div>
   <?php }?>
   <div>
      <br />
      <a class="btn btn-default" href="<?php echo $this->link()->route()?>" 
         title="<?php echo $this->tr('Přejít zpět na mapu')?>"><?php echo $this->tr('Zpět na mapu')?></a>
   </div>
</div>
