<?
$this->addJsPlugin(new JsPlugin_JQueryCSS());
$this->addPageTitle($this->tr('Seznam míst'));
echo $this->toolbox;
?>
<h1><?=$this->category()->getName().' - '.$this->tr('Seznam míst')?></h1>
<div class="main-content-list">
   <?if(!empty ($this->locations)) {
   foreach ($this->locations as $loc) {?>
   <div class="main-content-list-record ui-widget">
      <div class="ui-widget-header ui-corner-top">
         <?
         $this->toolboxItem->setTemplate(Template_Toolbox2::TEMPLATE_INLINE);
         $this->toolboxItem->edit_location->setAction($this->link()->route('edit', array('id' => $loc->{MapLocations_Model::COLUMN_ID})));
         $this->toolboxItem->location_del->getForm()->id->setValues($loc->{MapLocations_Model::COLUMN_ID});
         echo $this->toolboxItem;
         ?>
         <h2><?=$loc->{MapLocations_Model::COLUMN_NAME}?></h2>
      </div>
      <div class="main-content-list-record-text ui-widget-content ui-corner-bottom">
         <?if($loc->{MapLocations_Model::COLUMN_IMAGE} != null){?>
            <div class="main-content-list-record-image">
               <img src="<?=$this->category()->getModule()->getDataDir(true).$loc->{MapLocations_Model::COLUMN_IMAGE}?>"
                    alt="<?=$loc->{MapLocations_Model::COLUMN_NAME}?>"/>
            </div>
         <?}?>
         <?
         echo $loc->{MapLocations_Model::COLUMN_TEXT};
         ?>
      <hr class="reseter" />
      </div>
   </div>
   <?}} else {?>   
   <div class="main-content-list-record ui-widget">
      <div class="ui-widget-content"><?=$this->tr('Źádné místo nebylo přidáno')?></div>
   </div>
   <?}?>
   <a href="<?=$this->link()->route()?>" title="<?=$this->tr('Přejít zpět na mapu')?>">&DoubleLeftArrow; <?=$this->tr('Zpět na mapu')?></a>
</div>
