<?
Template::addJS('http://maps.google.com/maps/api/js?sensor=false');
echo $this->toolbox;
?>
<h1><? echo $this->category()->getName(); ?></h1>
<div class="main-content-detail">
   <div id="map_canvas" style="width:100%; height:400px"></div>   
   <script type="text/javascript">
      var map = null;
      function initMap() {
         var latlng = new google.maps.LatLng(
<?=$this->category()->getParam(MapLocations_Controller::PARAM_MAP_X, '') /* X */?>, 
<?=$this->category()->getParam(MapLocations_Controller::PARAM_MAP_Y, '') /* Y */?>);
         var myOptions = {
            zoom: <?=$this->category()->getParam(MapLocations_Controller::PARAM_MAP_ZOOM, 8)?>,
            center: latlng,
            mapTypeId: google.maps.MapTypeId.<?=$this->category()->getParam(MapLocations_Controller::PARAM_MAP_TYPE, MapLocations_Controller::MAP_TYPE_NORMAL)?>
         };
         map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
      }
      initMap();
      // add markers
      <?if(!empty ($this->locations)) { foreach ($this->locations as $i => $loc) {
         // create content string
         $cnt = '<h2>'.$loc->{MapLocations_Model::COLUMN_NAME}."</h2>";
         if($loc->{MapLocations_Model::COLUMN_IMAGE} != null){
            $cnt .= '<img src="'.$this->category()->getModule()->getDataDir(true).$loc->{MapLocations_Model::COLUMN_IMAGE}.'" 
               alt="'.htmlspecialchars($loc->{MapLocations_Model::COLUMN_NAME}).'"
               class="image-left" />';
         }
         $cnt .= $loc->{MapLocations_Model::COLUMN_TEXT};
         
         echo "
         var point_$i = new google.maps.LatLng(
         {$loc->{MapLocations_Model::COLUMN_COORDINATE_X}},{$loc->{MapLocations_Model::COLUMN_COORDINATE_Y}});
         var infowindow_$i = new google.maps.InfoWindow({content: ".json_encode('<div style="width: 450px;">'.$cnt.'</div>').", maxWidth : 450});
         var marker_$i = new google.maps.Marker({
            position: point_$i, map: map, 
            title: ".json_encode($loc->{MapLocations_Model::COLUMN_NAME})."
         }); 
         google.maps.event.addListener(marker_$i, 'click', function() {infowindow_$i.open(map,marker_$i);});
         ";
      }}?>
      
   </script>
</div>
