<?php
// do titulku
$h = $this->tr('Úprava pořadí skupin položek');
$this->addPageTitle($h);

$jq = new JsPlugin_JQuery();
$jq->addUISortable();
$this->addJsPlugin($jq);
$this->addFile('css://style.css');
?>
<h1><?php echo $h ?></h1>
<div class="content-admin">
   <?php echo $this->form->renderStart(); ?>
   <div id="partners-groups-list-wrap" class="cubecms-widget cubecms-widget-sorting">
      <div class="cubecms-content">
         <ul  id="partners-groups-list" class="cubecms-widget cubecms-list">
            <?php
            foreach ($this->partnersGroups as $group) {
               ?>
               <li id="pgroup-<?php echo $group->getPK() ?>"
                   class="item cubecms-list-row clearfix"
                   data-id="<?php echo $group->getPK() ?>">
                  <div class="cubecms-sort sort-area">
                     <span class="icon icon-arrows"></span>
                  </div>
                  <span class="cubecms-name">
                     <?php
                     p_lang($group->{Partners_Model_Groups::COLUMN_NAME});
                     $this->form->id->setValues($group->{Partners_Model_Groups::COLUMN_ID});
                     echo $this->form->id;
                     ?>
                  </span>

      <!--            <span class="cubecms-tools">
                     <a href="<?php echo $this->link()->param('editv', $group->getPK()) ?>"
                        onclick="ShopVariants.editVariant(<?php echo $group->getPK() ?>); return false;"
                        class="button-edit-value"><span class="icon icon-pencil"></span></a>
                     <a href="<?php echo $this->link()->param('deletev', $group->getPK()) ?>"
                        onclick="ShopVariants.deleteVariant(<?php echo $group->getPK() ?>); return false;"
                        class="button-delete-value important"><span class="icon icon-remove"></span></a>
                  </span>-->
               </li>
               <?php
            }
            ?>
         </ul>
         <div id="pgroups-control" class="cubecms-footer">
            <?php echo $this->form->save->controllAll() ?>
         </div>
      </div>
   </div>
   <div class="alert alert-info">
      <?php echo $this->tr('Pro změnu pořadí stačí položku uchopit myší a přesunout.') ?>
   </div>
   <?php echo $this->form->renderEnd(); ?>
   <script>
      $(function () {
         $("#partners-groups-list").sortable({
            handle: ".sort-area",
            placeholder: "cubecms-list-row cubecms-state-highlight",
            forceHelperSize: true,
            forcePlaceholderSize: true
         });
//         $("#partners-groups-list").disableSelection();
      });
   </script>
</div>
