<?php 
$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
?>
<div class="label"><?php echo $icon?><a href="<?php echo $this->link()?>" title="<?php echo htmlspecialchars($this->panelObj()->getName())?>"><?php echo $this->panelObj()->getName()?></a></div>
   <?php foreach ($this->partners as $partner) {?>
   <div class="name">
      <?php 
      if($partner->{Partners_Model::COLUMN_URL} != null){
         echo '<a href="'.$partner->{Partners_Model::COLUMN_URL}.'" title="'.  htmlspecialchars($partner->{Partners_Model::COLUMN_NAME}).'" class="link-external">';
      }
      ps($partner->{Partners_Model::COLUMN_NAME});
      if($partner->{Partners_Model::COLUMN_URL} != null){
         echo "</a>";
      }
      ?>
   </div>
   <?php 
   if($partner->{Partners_Model::COLUMN_IMAGE} != null){
      $imgsrc = vve_image_cacher($this->imagesDir.$partner->{Partners_Model::COLUMN_IMAGE}, 150);?>
      <div class="image">
         <?php if($partner->{Partners_Model::COLUMN_URL} != null){
            echo '<a href="'.$partner->{Partners_Model::COLUMN_URL}.'" title="'.  htmlspecialchars($partner->{Partners_Model::COLUMN_NAME}).'" class="link-external">';
         }?>
         <img src="<?php echo $imgsrc ?>" alt="<?php ps($partner->{Partners_Model::COLUMN_NAME})?>" />
         <?php if($partner->{Partners_Model::COLUMN_URL} != null){
            echo '</a>';
         }?>
      </div>   
   <?php }?>
   <?php }?>
   <div class="link-more">
      <a href="<?php echo $this->link()?>"
         title="<?php echo htmlspecialchars($this->category()->getLabel())?>"><?php echo $this->tr('Více')?></a>
   </div>