<?php 
$this->addJsPlugin(new JsPlugin_JQueryCSS());
$this->addCssFile('style.css');
?>
<h2><?php echo $this->tr('Seznam instalovaných modulů')?></h2>
<table class="modules-list">
   <thead>
      <tr class="ui-widget-header">
         <th scope="col" class="modules-tb-name"><?php echo $this->tr('Název modulu')?></th>
         <th scope="col" class="modules-tb-version"><?php echo $this->tr('instalovaná verze')?></th>
      </tr>
   </thead>
   <tbody>
      <?php foreach ($this->modules as $module) {?>
      <tr class="ui-widget-content ui-state-default">
         <td><?php echo $module['name']?></td>
         <td><?php echo $module['version']?></td>
      </tr>
      <?php }?>
   </tbody>
</table>
<br />
<div>
</div>