<?
$this->addJsPlugin(new JsPlugin_JQueryCSS());
$this->addCssFile('style.css');
?>
<h2><?=$this->tr('Seznam instalovaných modulů')?></h2>
<table class="modules-list">
   <thead>
      <tr class="ui-widget-header">
         <th scope="col" class="modules-tb-name"><?=$this->tr('Název modulu')?></th>
         <th scope="col" class="modules-tb-version"><?=$this->tr('instalovaná verze')?></th>
      </tr>
   </thead>
   <tbody>
      <?foreach ($this->modules as $module) {?>
      <tr class="ui-widget-content ui-state-default">
         <td><?=$module['name']?></td>
         <td><?=$module['version']?></td>
      </tr>
      <?}?>
   </tbody>
</table>
<br />
<div>
</div>