<div class="comments-form-add" id="addComment">
   <strong><?=$this->tr('Přidání komentáře')?></strong>
   <p id="comment-reaction-label"></p>
   <?
   $this->formAdd->comment->html()->setAttrib('rows', 5)->setAttrib('cols', 70);
   $this->formAdd->comment->setSubLabel($this->tr('Povolené značky XHTML').': a, br, em, strong, sub, sup, ul, li, ol');
   $this->formAdd->add->html()->setAttrib('style', 'width: 70px;');
   echo $this->formAdd;
   ?>
</div>
<script type="text/javascript">
   /* <![CDATA[ */
   function selectParent(id, nick,text){
      document.getElementById('comment_new_parent_1').value = id;
      document.getElementById('comment-reaction-label').innerHTML = '<?=$this->tr('Reakce na: ')?>'+nick+' - '+text.toString();
   }
   // vypnutí submitu
   var ccTime = <?=$this->ctTime?>;
   document.getElementById('comment_new_add_1').disabled = 'disabled';
   document.getElementById('comment_new_add_1').value = ccTime+'s';

   function timedCount() {
      ccTime--;
      if(ccTime == 0){
         document.getElementById('comment_new_add_1').disabled = '';
         document.getElementById('comment_new_add_1').value = '<?=$this->tr('Uložit')?>';
      } else {
         document.getElementById('comment_new_add_1').value = ccTime+'s';
         t=setTimeout("timedCount()",1000);
      }
   }
   timedCount();
   /* ]]> */
</script>