<div class="comments-list">
   <?php 
   echo '<span class="comments-label"><strong>';
   printf($this->tr('Komentáře (%s), nové: (%s).'),$this->countComments, $this->unreaded);
   echo '</strong></span>';
   if(!empty ($this->comments)) {
      foreach ($this->comments as $comment) {
         $this->includeTpl('comments/item.phtml',true, array('comment' => $comment));
      }
   } else {
      echo $this->tr('<p>Není uložen žádný komentář</p>');
   }
   ?>
   <?php if($this->isClosed == true) {
      echo $this->tr('<p>Diskuze byla uzavřena</p>');
   }?>
</div>