<?php 
if(Template::browser()->isMobile()){ return; }
?>

<div class="article-tools">
   <?php if(isset($vars['lastEditTime'])) {
      if(($vars['lastEditTime'] instanceof DateTime) == false) {
         $vars['lastEditTime'] = new DateTime($vars['lastEditTime']);
      }?>
   <div>
         <?php echo $this->tr('Naposled upraveno')?>&nbsp;<?php echo strftime("%x %X", $vars['lastEditTime']->format("U"))?>
         <?php if(isset($vars['lastEditUser'])) {?>
      &nbsp;<?php echo $this->tr('uživatelem')?>&nbsp;<span style="font-style: italic"><?php echo $vars['lastEditUser']?></span>,
            <?php }
         if(isset($vars['createdByUser'])) {
            printf($this->tr('Vytvořil: %s.'),$vars['createdByUser']);
         }
         if(isset($vars['showed'])) {
            echo ($this->tr('zobrazeno').":&nbsp;".$vars['showed']."&times;");
         }
         ?>

   </div>
   <br />
   <?php }?>
   <?php if(isset($vars['linkToPdf']) OR isset($vars['linkToTxt'])) { ?>
   <div class="donwload">
      <strong><?php echo $this->tr('Stáhnout')?>:</strong>
      <?php if(isset($vars['linkToPdf'])) { ?>
   <a href="<?php echo $vars['linkToPdf']?>" title="<?php echo $this->tr('Stáhnout')?> pdf"><?php echo $this->tr('pdf (tisk)')?></a>&nbsp;
         <?php }?>
      <?php if(isset($vars['linkToTxt'])) { ?>
   <a href="<?php echo $vars['linkToTxt']?>" title="<?php echo $this->tr('Stáhnout')?> txt"><?php echo $this->tr('txt')?></a>&nbsp;
         <?php }?>
      <?php if(isset($vars['linkToHtml'])) { ?>
   <a href="<?php echo $vars['linkToHtml']?>" title="<?php echo $this->tr('Stáhnout')?> html"><?php echo $this->tr('html (tisk)')?></a>&nbsp;
         <?php }?>
   </div>
   <br />
   <?php }?>   
   
<div class="facebook-button">
   <?php $this->addFile('https://connect.facebook.net/'.Locales::getLangLocale().'/all.js#xfbml=1');?>
   <fb:like href="" show_faces="false" layout="standard" width="380" action="recommend" font=""></fb:like>
</div>
<div class="share-button">
   <script type="text/javascript" src="https://apis.google.com/js/plusone.js">{lang: '<?php echo Locales::getLang()?>'}</script>
   <g:plusone size="small"></g:plusone>
<!-- AddThis Button BEGIN -->
   <div class="addthis_toolbox addthis_default_style">
      <a class="addthis_button_preferred_1"></a><a class="addthis_button_preferred_2"></a><a class="addthis_button_preferred_3"></a><a class="addthis_button_preferred_4"></a>
      <a class="addthis_button_compact"></a>
   </div>
   <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=xa-4cb6af65123b597d"></script>
</div>
<!-- AddThis Button END -->
<div class="nav-button">
   <a href="<?php echo $this->link()?>#pageTop" title="<?php echo $this->tr('Přejít na začátek')?>">
      &#94;&nbsp;<?php echo $this->tr('nahoru')?></a>
</div>
</div>
