<?php
/*
 * vars:
 * $id
 * $close
 * $header
 * $content
 * $footer
 */
//var_dump(get_defined_vars());

$_id = Template::pVar('modal_id') == null ? 1 : Template::pVar('modal_id');
$id = isset($id) ? $id : 'modal-' . $_id;
$large = isset($large) ? $large : false;
$content = isset($content) ? $content : '';
$header = isset($header) ? $header : '';
$footer = isset($footer) ? $footer : '';
?>
<div id="<?php echo $id ?>" class="cubecms-modal <?=$large ? 'cubecms-modal-large' : ''?>">
   <div class="cubecms-modal-dialog">
      <div class="cubecms-modal-wrap">
         <?php if (isset($header)) { ?>
            <div class="cubecms-modal-header">
               <div class="cubecms-modal-title"><?php echo $header ?></div>
               <?php if (isset($close) && $close == true) { ?>
                  <a class="button-close close-modal" href="#close"><span class="icon icon-remove"></span></a>
               <?php } ?>
            </div>
         <?php } ?>
         <div class="cubecms-modal-body">
            <div class="cubecms-modal-errors errors"></div>
            <div class="cubecms-modal-content"><?php echo $content; ?></div>
         </div>
         <?php if (isset($footer)) { ?>
            <div class="cubecms-modal-footer">
               <?php echo $footer ?>
            </div>
         <?php } ?>
      </div>
   </div>
</div>