<?php 
$this->addPageTitle($this->movie->{CinemaProgram_Model_Detail::COL_NAME});
$this->setPageHeadline($this->movie->{CinemaProgram_Model_Detail::COL_NAME});
$m = $this->movie;
?>
<div>
   <?php if($m->{CinemaProgram_Model_Detail::COL_NAME_ORIG} != null) {?>
   <span style="font-style: italic">(<?php echo $m->{CinemaProgram_Model_Detail::COL_NAME_ORIG}?>)</span>
      <?php }?>
   <div>
      <?php if($m->{CinemaProgram_Model_Detail::COL_IMAGE} != null) {?>
      <p style="float: left; margin: 0 1em 0.5em 0">
            <?php echo vve_tpl_image_tag($this->category()->getModule()->getDataDir()
                    .$m->{CinemaProgram_Model_Detail::COL_IMAGE},null,200);?>
      </p>
            <?php }?>
      <p>
         <?php 
         if($m->{CinemaProgram_Model_Detail::COL_TYPE} != null) {
            echo ($this->_('Typ promítání').":&nbsp;".$m->{CinemaProgram_Model_Detail::COL_TYPE});
         }?>
         <br />
         <?php 
         print ($this->_('Mládeži').":&nbsp;");
         if($m->{CinemaProgram_Model_Detail::COL_ACCESS} != 0) {
            print $this->_('přístupno od')."&nbsp;".$m->{CinemaProgram_Model_Detail::COL_ACCESS}."&nbsp;".$this->_('let');
         } else {
            print $this->_('přístupno');
         }?>
         <br />
         <?php 
         print ($this->_('Znění').":&nbsp;");
         switch ($m->{CinemaProgram_Model_Detail::COL_VERSION}) {
            case 'origwsubtitles':
               print ($this->_('původní s titulky'));
               break;
            case 'original':
               print ($this->_('původní'));
               break;
            case 'slovakia':
               print ($this->_('slovensky'));
               break;
            case 'dabbing':
               print ($this->_('český dabbing'));
               break;
            case 'czech':
            default:
               print ($this->_('česky'));
               break;
         }?>
         <br />
         <?php echo $this->_('Stopáž')?>:&nbsp;<?php echo $m->{CinemaProgram_Model_Detail::COL_LENGTH}?>&nbsp;min<br />
         <?php echo $this->_('Cena')?>:&nbsp;<?php echo $m->{CinemaProgram_Model_Detail::COL_PRICE}?>&nbsp;Kč<br />

      </p>
      <hr class="reseter"/>
      <?php echo $m->{CinemaProgram_Model_Detail::COL_LABEL}?>
      <p>
         <?php if($m->{CinemaProgram_Model_Detail::COL_CSFDID} != 0) {?>
         <a href="http://www.csfd.cz/film/<?php echo $m->{CinemaProgram_Model_Detail::COL_CSFDID}
                       ."-".vve_cr_url_key($m->{CinemaProgram_Model_Detail::COL_NAME})?>"
            title="ČSFD" target="_blank"><img src="<?php echo vve_get_tpl_file('icons_logos/logo-csfd.png',
                                                      VVE_TPL_FILE_IMAGE)?>" alt="čsfd logo" /></a>
               <?php }?>
            <?php if($m->{CinemaProgram_Model_Detail::COL_IMDBID} != 0) {?>
         <a href="http://www.imdb.com/title/tt<?php echo $m->{CinemaProgram_Model_Detail::COL_IMDBID}
                       ."-".vve_cr_url_key($m->{CinemaProgram_Model_Detail::COL_NAME})?>"
            title="IMDB" target="_blank"><img src="<?php echo vve_get_tpl_file('icons_logos/logo-imdb.png',
                                                      VVE_TPL_FILE_IMAGE)?>" alt="imdb logo" /></a>
               <?php }?>
            <?php if($m->{CinemaProgram_Model_Detail::COL_CRITIQUE} != null) {?>
         <a href="<?php echo $m->{CinemaProgram_Model_Detail::COL_CRITIQUE}?>"
            title="<?php echo $this->_('Recenze')?>" target="_blank"><?php echo $this->_('Recenze')?></a>
               <?php }?>
      </p>
      <br />
      <h2><?php echo $this->_('Hrajeme')?>:</h2>
      <?php 
      $times = array();
      while ($row = $this->times->fetch()) {
         $date = new DateTime($row->{CinemaProgram_Model_Detail::COL_T_DATE});
         $time = new DateTime($row->{CinemaProgram_Model_Detail::COL_T_TIME});
         if(!isset ($times[$date->format("U")])) $times[$date->format("U")]=null;
         $times[$date->format("U")] .= strftime("%H:%M",$time->format("U")).', ';
      }?>
      <table>
         <?php foreach ($times as $date => $time) {?>
         <tr>
            <td style="width: 70px"><?php echo strftime('%A',$date)?></td>
            <td><a href="<?php echo $this->link()->route('normaldate', array('day' => date('d',$date), 'month' => date('m',$date),'year' => date('Y',$date)))?>"
                   title="<?php echo $this->_('přejít na program')?>"><?php echo strftime("%x", $date)?></a></td>
            <td>&nbsp;-&nbsp;<?php echo substr($time, 0, strlen($time)-2)?></td>
         </tr>
            <?php }?>
      </table>
      <?php 
      unset($times);
      ?>


   </div>
   <?php if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('edit_movie', $this->_("Upravit film"),
              $this->link()->route('edit',array('id' => (int)$m->{CinemaProgram_Model_Detail::COL_ID})),
              $this->_("Upravit film"), "film_edit.png");
      $toolbox->addTool('movie_delete', $this->_("Smazat film"),
              $this->link(), $this->_("Smazat film"), "film_delete.png",
              'movie_id', (int)$m->{CinemaProgram_Model_Detail::COL_ID},
              $this->_('Opravdu smazat film?'));
      $this->includeTplObj($toolbox);
   }?>
   <br />
   <?php echo $this->includeTpl('buttonback.phtml', true)?>
</div>
