<?
//print("locale");
//var_dump(setlocale(LC_ALL, "cs_CZ.UTF8"));
?>

<div>
   <?foreach ($this->movies as $movie) {?>
   <h2><?=$movie[CinemaProgram_Model_Detail::COL_NAME]?></h2>
   časy:<br />
   <?
   $times = $this->mmodel->getTimes($movie[CinemaProgram_Model_Detail::COL_ID]);
   foreach ($times as $time) {
      $tf = new DateTime((string)$time[CinemaProgram_Model_Detail::COL_T_TIME]);
      $dff = new DateTime((string)$time[CinemaProgram_Model_Detail::COL_T_DATEFROM]);
      $dtf = new DateTime((string)$time[CinemaProgram_Model_Detail::COL_T_DATETO]);

      if($dff != $dtf){
         print (strftime("%A",$dff->format("U"))." - ".strftime("%A",$dtf->format("U"))."<br />");
         print (strftime("%x",$dff->format("U"))." - ".strftime("%x",$dtf->format("U")));
      } else {
         print (strftime("%A",$dff->format("U"))."<br />". strftime("%x",$dff->format("U")));
      }
      print(" ");
      print ($this->_("čas: ").$tf->format("H:i"));
      print("<br />");
   }?>

   <hr />
   <?}?>
</div>


<?
   if($this->category()->getRights()->isWritable()) {
      $toolbox = new Template_Toolbox();
      $toolbox->addTool('add_movie', $this->_("Přidat film"),
          $this->link()->route('add'),
          $this->_("Přidat nový film"), "film_add.png");
      $this->includeTplObj($toolbox);
   }
   ?>