<?php 
// titulek
$range = strftime("%x", $this->curDate->format("U"))." - ".strftime("%x", $this->toDate->format("U"));
$this->addPageTitle($range);
$this->addPageHeadline($range);

$this->addJsPlugin(new JsPlugin_JQuery());

// načtení časů a převod do pole
$movies = array();
while ($time = $this->times->fetch()) {
   if(!isset ($movies[$time->{CinemaProgram_Model_Detail::COL_T_DATE}])) {
      $movies[$time->{CinemaProgram_Model_Detail::COL_T_DATE}] = array();
   }

   if(!isset ($movies[$time->{CinemaProgram_Model_Detail::COL_T_DATE}][$time->{CinemaProgram_Model_Detail::COL_ID}])) {
      $movies[$time->{CinemaProgram_Model_Detail::COL_T_DATE}]
              [$time->{CinemaProgram_Model_Detail::COL_ID}]
              = array('movie' => $time, 'times' => array());
   }
   array_push($movies[$time->{CinemaProgram_Model_Detail::COL_T_DATE}]
           [$time->{CinemaProgram_Model_Detail::COL_ID}]['times'], $time->{CinemaProgram_Model_Detail::COL_T_TIME});

}
?>
<style type="text/css" media="screen">
   .movieName:hover {
      background-color: #fff7b4;
   }
</style>
<div id="prMoviesList">
   <p style="text-align: right">
      <?php echo $this->_('Rozbalit')?>:&nbsp;
      <a href="#" id="showAllMovies" onclick="//return showAll()"><?php echo $this->_('Vše')?></a>
      <a href="#" id="hideAllMovies" onclick="//return hideAll()"><?php echo $this->_('Nic')?></a>
   </p>
   <?php 
   $cDay = clone $this->curDate;
   for ($day = 1; $day <= $this->deltaDay; $day++) {?>
   <div style="margin-bottom: 10px">
      <p style="font-weight: bold;background-color: yellow;"><?php echo strftime("%x", $cDay->format("U"))
                    ." - ".strftime("%A", $cDay->format("U"))?></p>
         <?php 
         if(isset ($movies[$cDay->format("Y-m-d")])) {?>
      <table style="width: 100%; border: 1px solid gray;">
               <?php 
               $prevMovieId = null;
               foreach ($movies[$cDay->format("Y-m-d")] as $movie) {
                  $m = $movie['movie'];?>
         <tr>
            <td style="width: 120px; padding: 2px; text-align: center" valign="middle">
               <p style="font-weight: bold;">
                           <?php 
                           $str = null;
                           foreach ($movie['times'] as $t) {
                              $time = new DateTime($t);
                              $str .= $time->format("H:i").", ";
                           }
                           print (substr($str, 0, strlen($str)-2));
                           ?>
               </p>
            </td>
            <td style="padding: 2px">
               <p class="movieName" onclick="showDetail(this)" style="cursor: pointer;">
                  <img class="expcolimg" src="images/buttons/expand.gif" alt="expand" />
                  <a href="#" title="<?php echo $this->_('Zobrazit detail')?>"
                     onclick="return false"><?php 
                                 if($m->{CinemaProgram_Model_Detail::COL_FC} == true) {
                                 ?><span style="color: red">FK</span>&nbsp;<?php 
                              }
                              print $m->{CinemaProgram_Model_Detail::COL_NAME};

                              if($m->{CinemaProgram_Model_Detail::COL_NAME_ORIG} != null) {?>
                     <span style="font-style: italic">(<?php echo $m->{CinemaProgram_Model_Detail::COL_NAME_ORIG}?>)</span>
                                 <?php }?>
                  </a>
                  <span style="float: right;"><?php echo $m->{CinemaProgram_Model_Detail::COL_LENGTH}?>&nbsp;min/<?php echo $m->{CinemaProgram_Model_Detail::COL_PRICE}?>&nbsp;Kč</span>
               </p>
               <div class="movieInfo" style="display: none;position: relative;">
                           <?php if($m->{CinemaProgram_Model_Detail::COL_IMAGE} != null) {?>
                  <p style="float: left; margin: 0 1em 0.5em 0">
                                 <?php echo vve_tpl_image_tag($this->category()->getModule()->getDataDir()
                                         .$m->{CinemaProgram_Model_Detail::COL_IMAGE},null,200);?>
                  </p>
                              <?php }?>
                  <p>
                     <?php 
                     echo ($this->_('Typ promítání').":&nbsp;");
                     if($m->{CinemaProgram_Model_Detail::COL_TYPE} != null) {
                        echo ($m->{CinemaProgram_Model_Detail::COL_TYPE});
                     } else {
                        echo ($this->_('Normální'));
                     }?>
                     <br />
                              <?php 
                              print ($this->_('Mládeži').":&nbsp;");
                              if($m->{CinemaProgram_Model_Detail::COL_ACCESS} != 0) {
                                 print $this->_('přístupno od')."&nbsp;".$m->{CinemaProgram_Model_Detail::COL_ACCESS}."&nbsp;".$this->_('let');
                              } else {
                                 print $this->_('přístupno');
                              }?>
                     <br />
                              <?php 
                              print ($this->_('Znění').":&nbsp;");
                              switch ($m->{CinemaProgram_Model_Detail::COL_VERSION}) {
                                 case 'origwsubtitles':
                                    print ($this->_('původní s titulky'));
                                    break;
                                 case 'original':
                                    print ($this->_('původní'));
                                    break;
                                 case 'slovakia':
                                    print ($this->_('slovensky'));
                                    break;
                                 case 'dabbing':
                                    print ($this->_('český dabbing'));
                                    break;
                                 case 'czech':
                                 default:
                                    print ($this->_('česky'));
                                    break;
                              }?>
                     <br />
                              <?php echo $this->_('Stopáž')?>:&nbsp;<?php echo $m->{CinemaProgram_Model_Detail::COL_LENGTH}?>&nbsp;min<br />
                              <?php echo $this->_('Cena')?>:&nbsp;<?php echo $m->{CinemaProgram_Model_Detail::COL_PRICE}?>&nbsp;Kč<br />

                  </p>
                  <hr class="reseter"/>
                           <?php echo $m->{CinemaProgram_Model_Detail::COL_LABEL}?>
                  <p>
                              <?php if($m->{CinemaProgram_Model_Detail::COL_CSFDID} != 0) {?>
                     <a href="http://www.csfd.cz/film/<?php echo $m->{CinemaProgram_Model_Detail::COL_CSFDID}
                                            ."-".vve_cr_url_key($m->{CinemaProgram_Model_Detail::COL_NAME})?>"
                        title="ČSFD" target="_blank"><img src="<?php echo vve_get_tpl_file('icons_logos/logo-csfd.png',
                                                                           VVE_TPL_FILE_IMAGE)?>" alt="čsfd logo" /></a>
                                    <?php }?>
                                 <?php if($m->{CinemaProgram_Model_Detail::COL_IMDBID} != 0) {?>
                     <a href="http://www.imdb.com/title/tt<?php echo $m->{CinemaProgram_Model_Detail::COL_IMDBID}
                                            ."-".vve_cr_url_key($m->{CinemaProgram_Model_Detail::COL_NAME})?>"
                        title="IMDB" target="_blank"><img src="<?php echo vve_get_tpl_file('icons_logos/logo-imdb.png',
                                                                           VVE_TPL_FILE_IMAGE)?>" alt="imdb logo" /></a>
                                    <?php }?>
                                 <?php if($m->{CinemaProgram_Model_Detail::COL_CRITIQUE} != null) {?>
                     <a href="<?php echo $m->{CinemaProgram_Model_Detail::COL_CRITIQUE}?>"
                        title="<?php echo $this->_('Recenze')?>" target="_blank"><?php echo $this->_('Recenze')?></a>
                                    <?php }?>
                     <a href="<?php echo $this->link()->route('detail', array('id' => $m->{CinemaProgram_Model_Detail::COL_ID}, 'name' => vve_cr_url_key($m->{CinemaProgram_Model_Detail::COL_NAME})))?>"
                        title="<?php echo $this->_('detail filmu')?>">detail</a>
                  </p>
                           <?php if($this->category()->getRights()->isWritable()) {
                              $toolbox = new Template_Toolbox();
                              $toolbox->addTool('edit_movie', $this->_("Upravit film"),
                                      $this->link()->route('edit',array('id' => (int)$m->{CinemaProgram_Model_Detail::COL_ID})),
                                      $this->_("Upravit film"), "film_edit.png");
                              $toolbox->addTool('movie_delete', $this->_("Smazat film"),
                                      $this->link(), $this->_("Smazat film"), "film_delete.png",
                                      'movie_id', (int)$m->{CinemaProgram_Model_Detail::COL_ID},
                                      $this->_('Opravdu smazat film?'));
                              $this->includeTplObj($toolbox);
                           }?>
               </div>
            </td>
         </tr>
         <tr>
            <td colspan="2" style="border-bottom: 1px solid gray"></td>
         </tr>
                  <?php }?>
      </table>
            <?php } else {
            print ($this->_('Nepromítá se'));
         }?>
   </div>
      <?php 
      $cDay->modify('+1 day');
   }
   ?>

   &laquo;<a href="<?php echo $this->linkBack?>" title="<?php echo $this->deltaDay."&nbsp;".$this->_('dní')?>"
             >-<?php echo $this->deltaDay."&nbsp;".$this->_('dní')?></a>&nbsp;&brvbar;&nbsp;
   <a href="<?php echo $this->linkNext?>" title="<?php echo $this->deltaDay."&nbsp;".$this->_('dní')?>"
      >+<?php echo $this->deltaDay."&nbsp;".$this->_('dní')?></a>&raquo;

   <script type="text/javascript">
      /* <![CDATA[ */
      function showDetail(linkObj){
         var $_l = $(linkObj);
         $(linkObj).parent().children('div.movieInfo').slideToggle(200, function(){
            if($(this).is(":hidden")){$_l.children("img").attr('src', 'images/buttons/expand.gif');
            } else {$_l.children("img").attr('src', 'images/buttons/collapse.gif');}
         });
         return false;
      }

      $(document).ready(function(){
         $('#showAllMovies').click(function(){
            $('div.movieInfo').show();
            $('div#prMoviesList img.expcolimg').attr('src', 'images/buttons/collapse.gif');
            return false;
         });
         $('#hideAllMovies').click(function(){
            $('div.movieInfo').hide();
            $('div#prMoviesList img.expcolimg').attr('src', 'images/buttons/expand.gif');
            return false;
         });
      });
      /* ]]> */
   </script>
</div>


<?php 
if($this->category()->getRights()->isWritable()) {
   $toolbox = new Template_Toolbox();
   $toolbox->addTool('add_movie', $this->_("Přidat film"),
           $this->link()->route('add'),
           $this->_("Přidat nový film"), "film_add.png");
   $this->includeTplObj($toolbox);
}
?>