
--
-- Struktura tabulky `{PREFIX}shop_products_general`
--

CREATE TABLE IF NOT EXISTS `{PREFIX}shop_products_general` (
  `id_product` int(11) NOT NULL AUTO_INCREMENT,
  `id_category` smallint(6) NOT NULL,
  `id_tax` int(11) NOT NULL,
  `code` varchar(100) DEFAULT NULL,
  `name_cs` varchar(200) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL,
  `urlkey_cs` varchar(200) DEFAULT NULL,
  `text_short_cs` text,
  `text_cs` text CHARACTER SET utf8 COLLATE utf8_czech_ci,
  `text_clear_cs` text,
  `keywords_cs` varchar(300) DEFAULT NULL,
  `name_en` varchar(200) DEFAULT NULL,
  `urlkey_en` varchar(200) DEFAULT NULL,
  `text_short_en` text,
  `text_en` text,
  `text_clear_en` text,
  `keywords_en` varchar(300) DEFAULT NULL,
  `name_de` varchar(200) DEFAULT NULL,
  `urlkey_de` varchar(200) DEFAULT NULL,
  `text_short_de` text,
  `text_de` text,
  `text_clear_de` text,
  `keywords_de` varchar(300) DEFAULT NULL,
  `name_sk` varchar(200) CHARACTER SET utf8 COLLATE utf8_slovak_ci DEFAULT NULL,
  `urlkey_sk` varchar(200) DEFAULT NULL,
  `text_short_sk` text,
  `text_sk` text CHARACTER SET utf8 COLLATE utf8_slovak_ci,
  `text_clear_sk` text,
  `keywords_sk` varchar(300) DEFAULT NULL,
  `price` float DEFAULT NULL,
  `unit` varchar(20) DEFAULT NULL,
  `unit_size` int(11) DEFAULT NULL,
  `quantity` smallint(6) DEFAULT '-1',
  `weight` float DEFAULT NULL,
  `discount` tinyint(4) DEFAULT '0',
  `deleted` tinyint(4) DEFAULT '0',
  `showed` int(11) NOT NULL DEFAULT '0',
  `active` tinyint(4) DEFAULT '1',
  `image` varchar(100) DEFAULT NULL,
  `date_add` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_new_to_date` date DEFAULT NULL,
  PRIMARY KEY (`id_product`),
  KEY `fk_id_category` (`id_category`),
  KEY `fk_id_tax` (`id_tax`),
  KEY `urlkey_cs` (`urlkey_cs`),
  KEY `urlkey_en` (`urlkey_en`),
  KEY `urlkey_de` (`urlkey_de`),
  KEY `urlkey_sk` (`urlkey_sk`),
  FULLTEXT KEY `text_cs_fulltext` (`text_clear_cs`),
  FULLTEXT KEY `text_en_fulltext` (`text_clear_en`),
  FULLTEXT KEY `text_sk_fulltext` (`text_clear_sk`),
  FULLTEXT KEY `text_de_fulltext` (`text_clear_de`),
  FULLTEXT KEY `name_cs_fulltext` (`name_cs`),
  FULLTEXT KEY `name_en_fulltext` (`name_en`),
  FULLTEXT KEY `name_sk_fulltext` (`name_sk`),
  FULLTEXT KEY `name_de_fulltext` (`name_de`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------
