<?php 
// do titulku
if($this->edit) {
   $this->addPageTitle(sprintf($this->_('úprava lektora "%s"'),$this->lecturer->{Lecturers_Model::COLUMN_NAME}.' '.$this->lecturer->{Lecturers_Model::COLUMN_SURNAME}));
   $this->addPageHeadline(sprintf($this->_('úprava lektora "%s"'),$this->lecturer->{Lecturers_Model::COLUMN_NAME}.' '.$this->lecturer->{Lecturers_Model::COLUMN_SURNAME}));
} else {
   $this->addPageTitle($this->_('přidání lektora'));
   $this->addPageHeadline($this->_('přidání lektora'));
}
// donastavení formuláře
$this->form->text->html()->setAttrib('cols', 80)->setAttrib('rows', 30);
$this->form->degree->html()->setAttrib('size', 5);

if(isset ($this->form->imgdel)){
   $this->form->imgdel->setSubLabel($this->_('Uložen portrét:').'<br /><img src="'.$this->imagePath.$this->lecturer->{Lecturers_Model::COLUMN_IMAGE}
   .'" alt="'.$this->lecturer->{Lecturers_Model::COLUMN_IMAGE}.'" width="100" />');
}
?>

<div class="article-form-edit">
   <?php 
   echo($this->form);
   ?>
</div>
