   <?php 
   function printDegree($degree) {
   if ($degree != null) {
      echo $degree;
      if ($degree[strlen($degree) - 1] != '.') {
         echo '.';
      }
      echo '&nbsp;';
   }
}
   if(!empty ($vars['lecturers'])) {
      foreach ($vars['lecturers'] as $lecturer) {
         ?>
   <div class="article-list-record module-lecturers-list-record" id="lecturer-<?php echo $lecturer->{Lecturers_Model::COLUMN_ID}?>">
      <<?php echo $vars['hE']?> class="<?php echo $vars['hEClass']?>" id="lecturer-<?php echo $lecturer->{Lecturers_Model::COLUMN_ID}?>">
         <?php 
         printDegree($lecturer->{Lecturers_Model::COLUMN_DEGREE});
         echo $lecturer->{Lecturers_Model::COLUMN_NAME}.'&nbsp;';
         echo $lecturer->{Lecturers_Model::COLUMN_SURNAME}.'&nbsp;';
         printDegree($lecturer->{Lecturers_Model::COLUMN_DEGREE_AFTER});
         ?>
      </<?php echo $vars['hE']?>>
      <div class="article-list-record-content">
         <?php if($lecturer->{Lecturers_Model::COLUMN_IMAGE} != null){?>
         <div class="article-list-record-box-image module-lecturers-list-record-box-image">
                  <?php echo vve_tpl_image_tag(AppCore::getAppDataDir().Lecturers_Controller::DATA_DIR.DIRECTORY_SEPARATOR
                          .$lecturer->{Lecturers_Model::COLUMN_IMAGE}, $lecturer->{Lecturers_Model::COLUMN_IMAGE}, 140);?>
         </div>
         <?php }?>
         <?php echo $lecturer->{Lecturers_Model::COLUMN_TEXT};?>
         <?php 
         if($this->toolboxEdit != null){
            $this->toolboxEdit->lecture_edit->setAction($this->link()->route('edit', array('id' => $lecturer->{Lecturers_Model::COLUMN_ID})));
            $this->toolboxEdit->lecture_del_->getForm()->id->setValues($lecturer->{Lecturers_Model::COLUMN_ID});
            echo $this->toolboxEdit;
         }
         ?>
      <hr class="reseter" />
      </div>
   </div>
         <?php }
   } else {
      echo ($this->_('Není vložen žádný lektor'));
   }?>