<?
if($this->edit == true){
      $h = $this->_('Úprava panelu');
   } else {
      $h = $this->_('Nový panel');
   }
?>
<h1><?=$h;?></h1>
<div class="main-content-form-edit" >
   <?
// donastavení formuláře
   $this->form->panel_order->html()->setAttrib('size', 4);
   $this->addJsPlugin(new JsPlugin_JQuery());

   if($this->form->haveElement('icon_delete')){
      $this->form->icon_delete->setSubLabel('<img src="'.Panel_Obj::getIconDir(true).$this->panelIcon.'" alt="panel icon" />&nbsp;'.$this->panelIcon);
   }
   if($this->form->haveElement('image_delete')){
      $this->form->image_delete->setSubLabel('<a href="'.Panel_Obj::getImgDir(true).$this->panelbackImg.'" title="'.$this->tr("Adresa obrázku").'">'.$this->panelbackImg.'</a>');
   }
   echo ($this->form);
   ?>
</div>