<div>
   <?
   $panelM = new Model_Panel();
   $panels = $panelM->getPanelsList(0,false);
   ?>
   <h2><?=$this->_('Seznam panelů');?></h2>

   <form action="<?=$this->link()?>" method="post">
   <table>
      <tr>
         <th width="200"><?=$this->_('kategorie')?></th>
         <th width="100"><?=$this->_('box')?></th>
         <th width="20"><?=$this->_('pořadí')?></th>
         <th width="20"><?=$this->_('smazat?')?></th>
      </tr>
      <?
      $previous = null;
      foreach ($panels as $key => $panel) {
         if($previous !== null AND $previous != $panel->{Model_Panel::COLUMN_POSITION}) {
            print ('<tr><td colspan="4"><hr /></td></tr>');
         }
         $this->editForm->panel_cat->setValues($panel->{Model_Category::COLUMN_CAT_ID})->setDimensional($key);
         $this->editForm->panel_box->setValues($panel->{Model_Panel::COLUMN_POSITION})->setDimensional($key);
         $this->editForm->panel_order->setValues($panel->{Model_Panel::COLUMN_ORDER})->setDimensional($key);
         $this->editForm->panel_id->setValues($panel->{Model_Panel::COLUMN_ID})->setDimensional($key);
         $this->editForm->panel_remove->setValues(false)->setDimensional($key);
         ?>
      <tr>
         <td><?=$this->editForm->panel_cat->controll()?></td>
         <td><?=$this->editForm->panel_box->controll()?></td>
         <td align="center"><?=$this->editForm->panel_order->controll()->setAttrib('size', 4)?></td>
         <td align="center">
            <?=$this->editForm->panel_id->controll()?>
            <?=$this->editForm->panel_remove->controll()->setAttrib('onclick', "if(this.checked == true)return confirm('Smazat?')")?>
         </td>
      </tr>
         <?
         $previous = $panel->{Model_Panel::COLUMN_POSITION};
      }
      ?>

      <tr>
         <td colspan="4" align="right">
            <?=$this->editForm->send->controll()?>
         </td>
      </tr>
   </table>
   </form>
   <?=$this->includeTpl('buttonback.phtml', true, array('link' => $this->link()->clear()))?>
   <br/>

</div>

