<?php 
echo $this->toolbox;
$this->addCssFile('style.less');
$this->addJsPlugin(new JsPlugin_JQuery());
$this->addJsPlugin(new JsPlugin_JQueryCSS());
?>
<h1><?php ps($this->category()->getName());?></h1>
<div class="content-admin">
   <?php 
   $linkajaxPanelInfo = new Url_Link_ModuleRequest();
   ?>
   <h2><?php echo $this->tr('Seznam globálních panelů');?></h2>
   <?php 
   $this->moduleButtons = array(
         array(
               'link' => $this->link()->route('add'),
               'title' => $this->tr('Přidat nový panel'),
               'icon' => Template_Toolbox2::ICON_ADD,
               'name' => $this->tr('Přidat nový panel'),
         ),
   );
   $this->includeTpl('modules/buttons.phtml', true);
   ?>
   <table class="panels-list cubecms-widget cubecms-table">
      <thead class="cubecms-header">
         <tr class="">
            <th scope="col" class="panel-tb-category"><?php echo $this->tr('kategorie')?></th>
            <th scope="col" class="panel-tb-box"><?php echo $this->tr('box')?></th>
            <th scope="col" class="panel-tb-order"><?php echo $this->tr('priorita')?></th>
            <th scope="col" class="panel-tb-actions"><?php echo $this->tr('akce')?></th>
         </tr>
      </thead>
      <tbody>
      <?php 
      $this->includeFile('tpl://listtpl.phtml');
      ?>
      </tbody>
   </table>
   <br />
   <br />
   <?php 
   // POKUD jsou individuální panely
   if(!empty ($this->individualPanelCats)) {?>
   <h2><?php echo $this->tr('Seznam individuálních panelů');?></h2>
   <?php 
   $this->moduleButtons = array(
         array(
               'link' => $this->link()->route('add')->rmParam(),
               'title' => $this->tr('Přidat nový individuální panel'),
               'icon' => Template_Toolbox2::ICON_ADD,
               'name' => $this->tr('Přidat nový individuální panel'),
               'id' => 'button-add-individual',
         ),
   );
   $this->includeTpl('modules/buttons.phtml', true);
   ?>
   <div class="ui-widget ui-widget-header category-selector" >
   <strong><?php echo $this->tr('Kategorie pro zobrazení')?>:</strong>
   <select id="catsList" name="catsList">
         <?php foreach ($this->individualPanelCats as $cat) {?>
      <option value="<?php echo $cat->{Model_Category::COLUMN_CAT_ID}?>"><?php echo $cat->{Model_Category::COLUMN_CAT_LABEL}." (".$cat->numPanels.")"?></option>
            <?php  }?>
   </select>
   <button name="selectCatPanels"><?php echo $this->tr('Vybrat')?></button>
   </div>
   <div><!-- kvuli loadboxu-->
      <table class="panels-list cubecms-widget cubecms-table" id="indCatPanelsList">
         <thead class="cubecms-header" id="indCatPanelsListHeader">
            <tr>
               <th scope="col" class="panel-tb-category"><?php echo $this->tr('kategorie')?></th>
               <th scope="col" class="panel-tb-box"><?php echo $this->tr('box')?></th>
               <th scope="col" class="panel-tb-order"><?php echo $this->tr('priorita')?></th>
               <th scope="col" class="panel-tb-actions"><?php echo $this->tr('akce')?></th>
            </tr>
         </thead>
         <tbody></tbody>
      </table>
   </div>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
    	   var idc = decodeURIComponent((new RegExp('[?|&]idc=([0-9]+)').exec(location.search)||[,""])[1].replace(/\+/g, '%20'))||null;
    	   if(idc != null){
    		   $('select#catsList').val(idc)
        	}
         loadPanels();
         $('button[name=selectCatPanels]').click(function(){loadPanels();return false;});
         $('select[name=catsList]').change(function(){loadPanels();return false;});
         $('#button-add-individual').click(function(){
             $(this).prop('href', $(this).prop('href')+"?idcto="+$('select[name=catsList]').val());
         });
      });
      function loadPanels(){
         showLoadBox($('table#indCatPanelsList'));
         $.ajax({
        	   url: '<?php echo $this->link()->route('getListPanels')?>',
            data: { idc : $('select#catsList').val()},
            success: function(data) {
               $('table#indCatPanelsList tbody').html(data);
               hideLoadBox();
            }
         });
      }
      /* ]]> */
   </script>
      <?php }?>
</div>

