<?php 
if(!empty ($this->panels)){
$previousPos = null;
foreach ($this->panels as $key => $panel) {
   if($previousPos != $panel->{Model_Panel::COLUMN_POSITION} AND $previousPos != null) {?>
<tr class="cubecms-row-separator">
   <td colspan="5"><span></span></td>
</tr>
      <?php }?>
<tr class="cubecms-row <?php echo !isset($this->facePanels[$panel->{Model_Panel::COLUMN_POSITION}]) ? 'state-disabled' : ''?>">
   <td>
         <?php 
         if((string)$panel->{Model_Panel::COLUMN_NAME} != null) {
            echo ($panel->{Model_Panel::COLUMN_NAME}.' (<span title="'.$this->tr('Kategorie').'">'.$panel->{Model_Category::COLUMN_NAME}.'</span>)');
         } else {
            echo ($panel->{Model_Category::COLUMN_NAME});
         }
         if($panel->{Model_Panel::COLUMN_FORCE_GLOBAL}){
            echo " (".$this->tr('vynucen globálně').")";
         }
         ?>
   </td>
   <td><?php 
      if(!empty($this->facePanels) && isset($this->facePanels[$panel->{Model_Panel::COLUMN_POSITION}])){
         ps($this->facePanels[$panel->{Model_Panel::COLUMN_POSITION}]);
      } else {
         ps($panel->{Model_Panel::COLUMN_POSITION});
      }
      ?></td>
   <td>
      <form method="post" action="<?php echo $this->link()->clear()?>" style="display:inline;">
         <input type="text" name="panel_position" value="<?php echo $panel->{Model_Panel::COLUMN_ORDER}?>" style="width: 30px" size="4" />
         <input type="hidden" name="panel_id" value="<?php echo $panel->{Model_Panel::COLUMN_ID}?>" />
         <input type="image" src="<?php echo vve_get_tpl_file('icons/accept.png', VVE_TPL_FILE_IMAGE)?>"
                value="edit" name="panel_changepos" title="<?php echo $this->tr('Uložit')?>" />
      </form>
   </td>
   <td>
      <?php 
      echo $panel->toolbox;
      ?>
   </td>
</tr>
   <?php 
   $previousPos = $panel->{Model_Panel::COLUMN_POSITION};
}
} else {?>
<tr class="cubecms-row">
   <td colspan="4"><?php echo $this->tr('Není uložen žádný panel');?></td>
</tr>
<?php }
