<?
echo $this->toolbox;
$this->addCssFile('style.css');
$this->addJsPlugin(new JsPlugin_JQuery());
$this->addJsPlugin(new JsPlugin_JQueryCSS());
?>
<h1><?=$this->category()->getName();?></h1>
<div class="main-content-detail">
   <?
   $linkajaxPanelInfo = new Url_Link_ModuleRequest();
   ?>
   <h2><?=$this->_('Seznam globálních panelů');?></h2>
   <br />
   <table class="panels-list">
      <thead>
         <tr class="ui-widget-header">
            <th scope="col" class="panel-tb-category"><?=$this->tr('kategorie')?></th>
            <th scope="col" class="panel-tb-box"><?=$this->tr('box')?></th>
            <th scope="col" class="panel-tb-order"><?=$this->tr('pořadí')?></th>
            <th scope="col" class="panel-tb-actions"><?=$this->tr('akce')?></th>
         </tr>
      </thead>
      <tbody>
      <?$this->panels = $this->gobalpanels;
      $this->includeTpl('listtpl.phtml', false, array('panels' => $this->gobalpanels));?>
      </tbody>
   </table>
   <br />
   <br />
   <?
   // POKUD jsou individuální panely
   if(!empty ($this->individualPanelCats)) {?>
   <h2><?=$this->_('Seznam individuálních panelů');?></h2>
   <br />
   <strong><?=$this->_('Kategorie pro zobrazení')?>:</strong>
   <select id="catsList" name="catsList">
         <?foreach ($this->individualPanelCats as $cat) {?>
      <option value="<?=$cat->{Model_Category::COLUMN_CAT_ID}?>"><?=$cat->{Model_Category::COLUMN_CAT_LABEL}?></option>
            <? }?>
   </select>
   <button name="selectCatPanels"><?=$this->_('Vybrat')?></button>
   <br />
   <div><!-- kvuli loadboxu-->
      <table class="panels-list" id="indCatPanelsList">
         <thead class="ui-widget-header" id="indCatPanelsListHeader">
            <tr>
               <th scope="col" class="panel-tb-category"><?=$this->tr('kategorie')?></th>
               <th scope="col" class="panel-tb-box"><?=$this->tr('box')?></th>
               <th scope="col" class="panel-tb-order"><?=$this->tr('pořadí')?></th>
               <th scope="col" class="panel-tb-actions"><?=$this->tr('akce')?></th>
            </tr>
         </thead>
         <tbody></tbody>
      </table>
   </div>
   <script type="text/javascript">
      /* <![CDATA[ */
      $(document).ready(function(){
         loadPanels();
         $('button[name=selectCatPanels]').click(function(){loadPanels();return false;});
         $('select[name=catsList]').change(function(){loadPanels();return false;});
      });
      function loadPanels(){
         showLoadBox($('table#indCatPanelsList'));
         $.ajax({
            url: '<?=$this->link()->route('getListPanels')?>?idc='+$('select#catsList').val(),
            success: function(data) {
               $('table#indCatPanelsList tbody').html(data);
               hideLoadBox();
            }
         });
      }
      /* ]]> */
   </script>
      <?}?>
</div>

