<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="pragma" content="-1" />
<script type="text/javascript" src="../tiny_mce_popup.js"></script>
<script type="text/javascript" src="../../jquery/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="../../jqueryjcrop/jquery.Jcrop.min.js"></script>
<script type="text/javascript" src="../../jquery/jquery-ui-1.7.UICore.min.js"></script>
<script type="text/javascript" src="../../jquery/jquery-ui-1.7.Resizable.min.js"></script>
<link rel="stylesheet" type="text/css" href="../../jqueryjcrop/jquery.Jcrop.css" type="text/javascript" />
<script type="text/javascript" src="tiny_mce_images_functions.js"></script>
<!--<script type="text/javascript" src="resizer.js"></script>-->
<link rel="stylesheet" type="text/css" href="../../jquery/ui/themes/base/ui.core.css" type="text/javascript" />
<link rel="stylesheet" type="text/css" href="../../jquery/ui/themes/base/ui.theme.css" type="text/javascript" />
<link rel="stylesheet" type="text/css" href="../../jquery/ui/themes/base/ui.resizable.css" type="text/javascript" />
<script type="text/javascript">
   $(document).ready(function(){
      FilePreviewDialogue.init();
      FilePreviewDialogue.loadImage();
   });
   //tinyMCEPopup.onInit.add(FilePreviewDialogue.init, FilePreviewDialogue);
</script>
<style type="text/css">
   #buttons {

   }
   #prevImgBoxCont {
      /*position: relative;*/
      width: 560px;
      height: 360px;
      overflow: scroll;
   }

   input[type="image"], input[type="hidden"] {
      border:none;
      background-color:transparent;
   }

   .boxToolEdit {
      display: none;
   }

   .tools input {
      border: 1px solid transparent;
   }

   .toolSelected {
      background-color: white !important;
      border: 1px solid gray !important;
   }

   #prevImgBoxCont {
      padding: 5px;
      position: relative;
   }

   #prevImgBox {
      margin: 0;
      padding: 0;
      /*position: absolute;*/
   }

   .ui-resizable-se {
      width: 8px;
      height: 8px;
      border: 1px solid black;
      background-color: white;
      bottom: 0;
      right: 0;
   }

   .flip-horizontal {
      -moz-transform: scaleX(-1);
      -webkit-transform: scaleX(-1);
      transform: scaleX(-1);
      filter: fliph; /*IE*/
   }
   .flip-vertical {
      -moz-transform: scaleY(-1);
      -webkit-transform: scaleY(-1);
      transform: scaleY(-1);
      filter: flipv; /*IE*/
   }

   .grayscale {
      filter: progid:DXImageTransform.Microsoft.BasicImage(grayscale=1); /*IE*/
      zoom: 1;
   }

</style>
<div>
   <table style="width: 100%; height: 98%">
      <tr>
         <td colspan="2">
            <div id="prevImgBoxCont">
               <div id="prevImgBox">
                  <img id="prevImg" src="" alt="" />
               </div>
            </div>
         </td>
      </tr>
      <tr>
         <td style="height: 50px" class="tools">
            <input type="image" src="../../../images/icons/magnify.png"
                   title="Změnit velikost"  onclick="FilePreviewImageFunctions.initTool(this, 'resize')" />
            <input type="image" src="../../../images/icons/crop.png"
                   title="Ořezat"  onclick="FilePreviewImageFunctions.initTool(this, 'crop')" />
            <input type="image" src="../../../images/icons/rotate.png"
                   title="Změnit rotaci" onclick="FilePreviewImageFunctions.initTool(this, 'rotate')" />
            <input type="image" src="../../../images/icons/flip.png"
                   title="Zrcadlit" onclick="FilePreviewImageFunctions.initTool(this, 'flip')" />
            <input type="image" src="../../../images/icons/gray.png"
                   title="Stupně šedi" onclick="FilePreviewImageFunctions.initTool(this, 'gray')" />
         </td>
         <td>
            <div id="box_rotate" class="boxToolEdit" >
               Otočit o: <input name="scale" type="text" value="" />°
               <input name="rotate" type="button" onclick="FilePreviewImageFunctions.rotateImage()" value="Uložit" />
               (není implementována)
            </div>
            <div id="box_resize" class="boxToolEdit">
               Zmenšit na:
               <input name="resize_w" type="text" value="" size="5" /> x
               <input name="resize_h" type="text" value="" size="5" /> px
               <input name="resize_ar" type="checkbox" checked="checked"/> Zachovat poměr
               <input name="resize" type="button" onclick="FilePreviewImageFunctions.resizeImage()" value="Uložit" />
               <br />
               (obrázek lze uchytit za pravý spodní roh nebo pravou a spodní stranu)
            </div>
            <div id="box_crop" class="boxToolEdit">
               Ořezat:
               X1: <input name="crop_x1" type="text" value="" size="4"/> px
               Y1: <input name="crop_y1" type="text" value="" size="4" /> px
               X2: <input name="crop_x2" type="text" value="" size="4" /> px
               Y2: <input name="crop_y2" type="text" value="" size="4" /> px<br />
               rozmeř: <input name="crop_w" type="text" value="" size="4" /> x
               výška <input name="crop_h" type="text" value="" size="4" /> px
               <input name="crop_ar" type="checkbox"/> Zachovat poměr
               <input name="crop" type="button" onclick="FilePreviewImageFunctions.cropImage()" value="Uložit" />
            </div>
            <div id="box_flip" class="boxToolEdit">
               Zrcadlit podle:
               X<input name="flip" value="x" type="radio" checked="checked" />
               Y<input name="flip" value="y" type="radio" />
               <input name="flip_img" type="button" onclick="FilePreviewImageFunctions.flipImage()" value="Uložit" />
            </div>
            <div id="box_gray" class="boxToolEdit">
               Odstíny šedi:
               <input name="gray" type="button" onclick="FilePreviewImageFunctions.grayImage()" value="Uložit" />
            </div>
         </td>
      </tr>
      <tr id="buttons">
         <td id="operationStatus"></td>
         <td valign="bottom" align="right">
            <input id="" name="close" type="button" onclick="FilePreviewDialogue.close()" value="Zavřít" />
         </td>
      </tr>
   </table>
</div>