<?
$this->addJsPlugin(new JsPlugin_SWFUpload());
$this->addJsPlugin(new JsPlugin_PiroBox());
$this->addFile("css://photogalery:style.css");
?>
<div id="datastorage-buttons">
   
   <div class="swfupload-control">
      <span id="swfUButtonPlaceholder"></span>
      <button type="button" name="upload" id="uplaod-button"><?=$this->tr('Nahrát');?></button>
   </div>
   <?
   // new dir
   echo $this->formCreateDir->html()->setAttrib('id', 'create-directory');
   echo $this->formCreateDir->renderStart();
   echo '<p>'.$this->formCreateDir->name;
   echo $this->formCreateDir->submit.'</p>';
   echo $this->formCreateDir->renderEnd();
   ?>
   <?
   // delete items
   echo $this->formDeleteItems->html()->setAttrib('id', 'delete-items');
   echo $this->formDeleteItems->renderStart();
   echo '<p>'.$this->formDeleteItems->names;
   $this->formDeleteItems->submit->html()->addClass('button-cancel');
   echo $this->formDeleteItems->submit.'</p>';
   echo $this->formDeleteItems->renderEnd();
   ?>
   <input type="submit" name="open-move-items" value="Přesunout"/>
   <div id="upload-queue" class="ui-widget action-details">
      <div class="ui-widget-header">
         <strong><?=$this->tr("Fronta odesílání")?>:</strong>&nbsp;
         <button onclick="clearUploadQueue();" title="<?=$this->tr('Vyčistit');?>" class="button-cancel"><?=$this->tr('Vyčistit');?></button>
      </div>
      <ul id="upload-list" class="ui-widget-content"></ul>
   </div>
   <div id="move-items" class="ui-widget action-details">
      <div class="ui-widget-header">
         <strong><?=$this->tr("Přesun položek")?>:</strong>&nbsp;
      </div>
      <?
      $this->formMoveItems->html()->setAttrib('id', 'move-items');
      echo $this->formMoveItems;
      ?>
      <hr class="reseter" />
   </div>
   <script type="text/javascript">
      var uploadUrl = '<?=$this->link()->route('uploadFile')?>';
      var sessionId = '<?=session_id();?>';
//      alert('doc ready');
   </script>
</div>