<table>
   <thead>
   <tr class="ui-widget-header ui-state-processing">
      <th colspan="<?=$this->controlls == true ? 4 : 3;?>" class="font-small">
         <?
      if(count($this->pathNav) > 1){
         echo $this->tr('Cesta:&nbsp;');
         foreach ($this->pathNav as $item) {
            ?><a href="<?=$item['link']?>" title="<?=$this->tr('Přejít do složky ').$item['name']?>" ><?=$item['name']?></a><?
         }
      }
      ?>
      </th>
   </tr>
   <tr class="ui-widget-header ui-state-processing">
      <?if($this->controlls == true){?><td class="file-selection"><input id="items-check-all" type="checkbox" /><?}?></td>
      <th scope="col" class="file-name">
         <a href="<?=$this->link()->param('sort', $this->curSort == 'name_a' ? 'name_d' : 'name_a')?>"
            title="<?=$this->tr('Řadit podle názvu')?>"class="<?if($this->curSort == 'name_a') echo "sort-label-asc"; else if($this->curSort == 'name_d') echo "sort-label-desc";?>"
            ><?=$this->tr('název')?></a>&nbsp;
         <label for="items-filter" class="font-small"><?=$this->tr('filtr')?>:</label>&nbsp;<input id="items-filter" name="itemsfilter" size="15" value="" />
         <span onclick="clrField();" class="font-small"><!--<img alt="clear" src="images/icons/cancel.png" />--></span></th>
      <th scope="col" class="file-mtime"><a href="<?=$this->link()->param('sort', $this->curSort == 'time_a' ? 'time_d' : 'time_a')?>"
                                            title="<?=$this->tr('Řadit podle času nahrání')?>"
                                            class="<?if($this->curSort == 'time_a') echo "sort-label-asc"; else if($this->curSort == 'time_d') echo "sort-label-desc";?>"
                                            ><?=$this->tr('nahráno')?><a/></th>
      <th scope="col" class="file-actions"><?=$this->tr('akce')?></th>
   </tr>
   </thead>
   <tbody>
   <?if($this->parentPath != null){?>
   <tr class="ui-widget-content ui-state-default">
      <?if($this->controlls == true){?><td></td><?}?>
      <td><?
         $link = new Html_Element('a', '...');
         $link->setAttrib('title', $this->tr('přejít výše'))
              ->setAttrib('href', $this->link()->param('path', $this->parentPath))
              ->addClass('dir-icon')->addClass('store-directory')->addClass('store-directory-up');
         echo $link;
      ?></td>
      <td></td>
      <td></td>
   </tr>
   <?}?>
   <?foreach ($this->items as $item) {?>
   <tr class="ui-widget-content ui-state-default">
      <?if($this->controlls == true){?><td><input type="checkbox" name="names[]" value="<?=$item['name']?>" class="item-select" /></td><?}?>
      <td><?
         if($item['isdir']){
            $link = new Html_Element('a', $item['name']);
            $link->setAttrib('title', $this->tr('Otevřít adresář').' '.$item['name'])
                 ->setAttrib('href', $this->link()->param('path', $item['path']))
                 ->addClass('dir-icon')->addClass('store-directory');
            echo $link;
         } else {
            $link = new Html_Element('a', $item['name'].'&nbsp;('.vve_create_size_str($item['size']).")");
            $link->setAttrib('title', $this->tr('Stáhnout').' '.$item['name'])
                 ->setAttrib('href', $item['url'])
                 ->addClass('file-icon')->addClass('file-'.$item['ext'])->addClass('store-file')->addClass('link-external');
            // doplnit ikony podle přípony
            echo $link;
            ?>
         <?}
         ?>
      </td>
      <td class="font-small"><?=vve_date("%x %X", $item['mtime']);?></td>
      <td>
         <input id="form-file-name" name="file-name" value="<?=$item['name']?>" type="hidden" />
         <?
         if($this->controlls == true){
            $this->formDeleteItem->html()->setAttrib('onSubmit', 'return confirm(\'Smazat položku '.$item['name'].' ?\')');
            echo $this->formDeleteItem->renderStart();
            $this->formDeleteItem->name->setValues($item['name']);
            echo $this->formDeleteItem->name;
            $this->formDeleteItem->submit->setImage('images/icons/cancel.png');
            echo $this->formDeleteItem->submit;
            echo $this->formDeleteItem->renderEnd();
         }
         if(!$item['isdir']){?>
         <a id="item-rename" href="<?=$this->link()->anchor('rename')?>" title="<?=$this->tr('Přejmenovat').' '.$item['name']?>"><img src="images/icons/pencil.png" alt="rename" /></a>
         <a href="<?=$item['dwurl']?>" title="<?=$this->tr('Stáhnout').' '.$item['name']?>"><img src="images/icons/download.png" alt="download" /></a>
         <?}?>
      </td>
   </tr>
   <?}?>
   </tbody>
</table>
