<h2>Struktura kategorií</h2>
<p>Na této stránce můžete upravovat strukturu stránek, přidávat resp. mazat jednotlivé kategorie, měnit jejich moduly nebo parametry.</p>

<h3>Zobrazení informací</h3>
<p>Při kliknutí na kategorii se v pravém sloupci objeví její podrobnější informace (modul, oprávnění, atd.).</p>
<h3>Přesun kategorií</h3>
<p>Jednotlivé kategorie lze přesouvat pouze myší. A to uchopením a přetažením na potřebné místo ve stromové struktuře. Při zapnutém políčku 
<strong>"Upravit URL adresy..."</strong> jsou u přesunovaných kategorií automaticky vytvořeny nové URL adresy kategorií podle jejícho nového zařazení.</p>
<p>Změny jsou automaticky ukládány na pozadí a v menu či mapě stránek se projeví až po znovunačtení stránky.</p>

<h3>Viditelnost kategorie</h3>
<p>Viditelnost kategorie určuje v jakém případě je daná kategorie a její potomci zobrazeni v menu a přidružených strukturách. 
<strong>POZOR! i když je kategorie neviditelná (není v menu), stále si ji uživatel (vyhledávač) může prohlížet!</strong></p>

<h3>Vlastník</h3>
<p>Položka vlastník definuje, kterému uživateli v systému daná kategorie patří. Vlastník, i když není administrátor si může tuto 
kategorii spravovat jak potřebuje a má k ní plné oprávnění.</p>