<h2>Úprava kategorie</h2>
<p>Na této stránce můžete upravovat parametry vybrané kategorie.</p>

<h3>Viditelnost kategorie</h3>
<p>Viditelnost kategorie určuje v jakém případě je daná kategorie a její potomci zobrazeni v menu a přidružených strukturách. 
<strong>POZOR! i když je kategorie neviditelná (není v menu), stále si ji uživatel (vyhledávač) může prohlížet!</strong></p>

<h3>Oprávnění</h3>
<p>Ke kategorii lze určit oprávnění jednotlivých skupin. Podle těchto oprávnění pak mohou uživatelé dané obsah upravovat, prohlížet nebo jim také zamezit přístup.</p>

<h3>Vlastník</h3>
<p>Položka vlastník definuje, kterému uživateli v systému daná kategorie patří. Vlastník, i když není administrátor si může tuto 
kategorii spravovat jak potřebuje a má k ní plné oprávnění.</p>