<?php 
if($this->file != null){
   $h = sprintf($this->tr('Úprava souboru "%s"'), $this->file->{DownloadFiles_Model::COLUMN_NAME});
} else {
   $h = sprintf($this->tr('Přidání souboru do kategorie "%s"'), $this->category()->getName());
}
Template_Core::setPageTitle($h);

?>
<h1><?php echo $h?></h1>
<div class="main-content-form-edit">
   <?php 
   // form
   $this->form->text->html()->setAttrib('rows', 7);
   echo $this->form;
   ?>
   <script type="text/javascript"></script>
</div>