/* UPDATE_MAIN_SITE */
ALTER TABLE `{PREFIX}sites` 
CHANGE COLUMN `domain` `domain` VARCHAR(50) NULL DEFAULT NULL ,
CHANGE COLUMN `dir` `dir` VARCHAR(50) NULL DEFAULT NULL ,
CHANGE COLUMN `table_prefix` `table_prefix` VARCHAR(50) NOT NULL ;
/* END_UPDATE */
