/* UPDATE_MAIN_SITE */
/* END_UPDATE */

ALTER TABLE `{PREFIX}sessions` 
CHANGE `created` `created` DATETIME NULL DEFAULT null,
CHANGE `updated` `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
