/* UPDATE_MAIN_SITE */
/* END_UPDATE */

ALTER TABLE `{PREFIX}sessions` 
CHANGE `created` `created` DATETIME NULL DEFAULT '1970-01-01 08:00:00',
CHANGE `updated` `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
