/* UPDATE_MAIN_SITE */
/* END_UPDATE */

ALTER TABLE `{PREFIX}sessions` 
CHANGE `created` `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
CHANGE `updated` `updated` DATETIME on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;