 
DROP TABLE IF EXISTS `{PREFIX}countries`;
CREATE TABLE IF NOT EXISTS `{PREFIX}countries` (
  `id_country` int(11) NOT NULL AUTO_INCREMENT,
  `country_numcode` int(11) NOT NULL,
  `country_iso` char(2) COLLATE utf8_unicode_ci NOT NULL,
  `country_iso3` char(3) COLLATE utf8_unicode_ci NOT NULL,
  `country_name_cs` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `country_name_en` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `country_name_de` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `country_namefull_cs` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `country_namefull_en` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `country_namefull_de` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id_country`),
  KEY `country_numcode` (`country_numcode`),
  KEY `country_iso` (`country_iso`),
  KEY `country_iso3` (`country_iso3`)
) ENGINE=InnoDB AUTO_INCREMENT=251 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Vyprázdnit tabulku před vkládáním `cube_cms_countries`
--

TRUNCATE TABLE `{PREFIX}countries`;
--
-- Vypisuji data pro tabulku `cube_cms_countries`
--

INSERT INTO `{PREFIX}countries` (`id_country`, `country_numcode`, `country_iso`, `country_iso3`, `country_name_cs`, `country_name_en`, `country_name_de`, `country_namefull_cs`, `country_namefull_en`, `country_namefull_de`) VALUES
(1, 4, 'AF', 'AFG', 'Afghánistán', 'Afghanistan', 'Afghanistan', 'Afghánská islámská republika', 'the Islamic Republic of Afghanistan', 'the Islamic Republic of Afghanistan'),
(2, 248, 'AX', 'ALA', 'Alandy', 'Åland Islands', 'Åland Islands', 'Provincie Alandy', 'Åland Islands', 'Åland Islands'),
(3, 8, 'AL', 'ALB', 'Albánie', 'Albania', 'Albania', 'Albánská republika', 'the Republic of Albania', 'the Republic of Albania'),
(4, 12, 'DZ', 'DZA', 'Alžírsko', 'Algeria', 'Algeria', 'Alžírská demokratická a lidová republika', 'the People\'s Democratic Republic of Algeria', 'the People\'s Democratic Republic of Algeria'),
(5, 16, 'AS', 'ASM', 'Americká Samoa', 'American Samoa', 'American Samoa', 'Území Americká Samoa', 'American Samoa', 'American Samoa'),
(6, 850, 'VI', 'VIR', 'Americké Panenské ostrovy', 'Virgin Islands (U.S.)', 'Virgin Islands (U.S.)', 'Americké Panenské ostrovy', 'the Virgin Islands of the United States', 'the Virgin Islands of the United States'),
(7, 20, 'AD', 'AND', 'Andorra', 'Andorra', 'Andorra', 'Andorrské knížectví', 'the Principality of Andorra', 'the Principality of Andorra'),
(8, 24, 'AO', 'AGO', 'Angola', 'Angola', 'Angola', 'Angolská republika', 'the Republic of Angola', 'the Republic of Angola'),
(9, 660, 'AI', 'AIA', 'Anguilla', 'Anguilla', 'Anguilla', 'Anguilla', 'Anguilla', 'Anguilla'),
(10, 10, 'AQ', 'ATA', 'Antarktida', 'Antarctica', 'Antarctica', 'Antarktida', 'Antarctica', 'Antarctica'),
(11, 28, 'AG', 'ATG', 'Antigua a Barbuda', 'Antigua and Barbuda', 'Antigua and Barbuda', 'Antigua a Barbuda', 'Antigua and Barbuda', 'Antigua and Barbuda'),
(12, 32, 'AR', 'ARG', 'Argentina', 'Argentina', 'Argentina', 'Argentinská republika', 'the Argentine Republic', 'the Argentine Republic'),
(13, 51, 'AM', 'ARM', 'Arménie', 'Armenia', 'Armenia', 'Arménská republika', 'the Republic of Armenia', 'the Republic of Armenia'),
(14, 533, 'AW', 'ABW', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Aruba'),
(15, 36, 'AU', 'AUS', 'Austrálie', 'Australia', 'Australia', 'Australské společenství', 'Australia', 'Australia'),
(16, 31, 'AZ', 'AZE', 'Ázerbájdžán', 'Azerbaijan', 'Azerbaijan', 'Ázerbájdžánská republika', 'the Republic of Azerbaijan', 'the Republic of Azerbaijan'),
(17, 44, 'BS', 'BHS', 'Bahamy', 'Bahamas (The)', 'Bahamas (The)', 'Bahamské společenství', 'the Commonwealth of The Bahamas', 'the Commonwealth of The Bahamas'),
(18, 48, 'BH', 'BHR', 'Bahrajn', 'Bahrain', 'Bahrain', 'Království Bahrajn', 'the Kingdom of Bahrain', 'the Kingdom of Bahrain'),
(19, 50, 'BD', 'BGD', 'Bangladéš', 'Bangladesh', 'Bangladesh', 'Bangladéšská lidová republika', 'the People\'s Republic of Bangladesh', 'the People\'s Republic of Bangladesh'),
(20, 52, 'BB', 'BRB', 'Barbados', 'Barbados', 'Barbados', 'Barbados', 'Barbados', 'Barbados'),
(21, 56, 'BE', 'BEL', 'Belgie', 'Belgium', 'Belgium', 'Belgické království', 'the Kingdom of Belgium', 'the Kingdom of Belgium'),
(22, 84, 'BZ', 'BLZ', 'Belize', 'Belize', 'Belize', 'Belize', 'Belize', 'Belize'),
(23, 112, 'BY', 'BLR', 'Bělorusko', 'Belarus', 'Belarus', 'Běloruská republika', 'the Republic of Belarus', 'the Republic of Belarus'),
(24, 204, 'BJ', 'BEN', 'Benin', 'Benin', 'Benin', 'Beninská republika', 'the Republic of Benin', 'the Republic of Benin'),
(25, 60, 'BM', 'BMU', 'Bermudy', 'Bermuda', 'Bermuda', 'Bermudy', 'Bermuda', 'Bermuda'),
(26, 64, 'BT', 'BTN', 'Bhútán', 'Bhutan', 'Bhutan', 'Bhútánské království', 'the Kingdom of Bhutan', 'the Kingdom of Bhutan'),
(27, 68, 'BO', 'BOL', 'Bolívie', 'Bolivia (Plurinational State of)', 'Bolivia (Plurinational State of)', 'Mnohonárodní stát Bolívie', 'the Plurinational State of Bolivia', 'the Plurinational State of Bolivia'),
(28, 535, 'BQ', 'BES', 'Bonaire, Svatý Eustach a Saba', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Svatý Eustach a Saba', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba'),
(29, 70, 'BA', 'BIH', 'Bosna a Hercegovina', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Bosna a Hercegovina', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina'),
(30, 72, 'BW', 'BWA', 'Botswana', 'Botswana', 'Botswana', 'Botswanská republika', 'the Republic of Botswana', 'the Republic of Botswana'),
(31, 74, 'BV', 'BVT', 'Bouvetův ostrov', 'Bouvet Island', 'Bouvet Island', 'Bouvetův ostrov', 'Bouvet Island', 'Bouvet Island'),
(32, 76, 'BR', 'BRA', 'Brazílie', 'Brazil', 'Brazil', 'Brazilská federativní republika', 'the Federative Republic of Brazil', 'the Federative Republic of Brazil'),
(33, 86, 'IO', 'IOT', 'Britské indickooceánské území', 'British Indian Ocean Territory (the)', 'British Indian Ocean Territory (the)', 'Britské území v Indickém oceánu', 'British Indian Ocean Territory (the)', 'British Indian Ocean Territory (the)'),
(34, 92, 'VG', 'VGB', 'Britské Panenské ostrovy', 'Virgin Islands (British)', 'Virgin Islands (British)', 'Britské Panenské ostrovy', 'British Virgin Islands (the)', 'British Virgin Islands (the)'),
(35, 96, 'BN', 'BRN', 'Brunej', 'Brunei Darussalam', 'Brunei Darussalam', 'Stát Brunej Darussalam', 'Brunei Darussalam', 'Brunei Darussalam'),
(36, 100, 'BG', 'BGR', 'Bulharsko', 'Bulgaria', 'Bulgaria', 'Bulharská republika', 'the Republic of Bulgaria', 'the Republic of Bulgaria'),
(37, 854, 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso'),
(38, 108, 'BI', 'BDI', 'Burundi', 'Burundi', 'Burundi', 'Burundská republika', 'the Republic of Burundi', 'the Republic of Burundi'),
(39, 184, 'CK', 'COK', 'Cookovy ostrovy', 'Cook Islands (the)', 'Cook Islands (the)', 'Cookovy ostrovy', 'Cook Islands (the)', 'Cook Islands (the)'),
(40, 531, 'CW', 'CUW', 'Curaçao', 'Curaçao', 'Curaçao', 'Curaçao', 'Curaçao', 'Curaçao'),
(41, 148, 'TD', 'TCD', 'Čad', 'Chad', 'Chad', 'Čadská republika', 'the Republic of Chad', 'the Republic of Chad'),
(42, 499, 'ME', 'MNE', 'Černá Hora', 'Montenegro', 'Montenegro', 'Černá Hora', 'Montenegro', 'Montenegro'),
(43, 203, 'CZ', 'CZE', 'Česko', 'Czechia', 'Czechia', 'Česká republika', 'the Czech Republic', 'the Czech Republic'),
(44, 156, 'CN', 'CHN', 'Čína', 'China', 'China', 'Čínská lidová republika', 'the People\'s Republic of China', 'the People\'s Republic of China'),
(45, 208, 'DK', 'DNK', 'Dánsko', 'Denmark', 'Denmark', 'Dánské království', 'the Kingdom of Denmark', 'the Kingdom of Denmark'),
(46, 180, 'CD', 'COD', 'Demokratická republika Kongo', 'Congo (the Democratic Republic of the)', 'Congo (the Democratic Republic of the)', 'Demokratická republika Kongo', 'the Democratic Republic of the Congo', 'the Democratic Republic of the Congo'),
(47, 212, 'DM', 'DMA', 'Dominika', 'Dominica', 'Dominica', 'Dominické společenství', 'the Commonwealth of Dominica', 'the Commonwealth of Dominica'),
(48, 214, 'DO', 'DOM', 'Dominikánská republika', 'Dominican Republic (the)', 'Dominican Republic (the)', 'Dominikánská republika', 'the Dominican Republic', 'the Dominican Republic'),
(49, 262, 'DJ', 'DJI', 'Džibutsko', 'Djibouti', 'Djibouti', 'Džibutská republika', 'the Republic of Djibouti', 'the Republic of Djibouti'),
(50, 818, 'EG', 'EGY', 'Egypt', 'Egypt', 'Egypt', 'Egyptská arabská republika', 'the Arab Republic of Egypt', 'the Arab Republic of Egypt'),
(51, 218, 'EC', 'ECU', 'Ekvádor', 'Ecuador', 'Ecuador', 'Ekvádorská republika', 'the Republic of Ecuador', 'the Republic of Ecuador'),
(52, 232, 'ER', 'ERI', 'Eritrea', 'Eritrea', 'Eritrea', 'Stát Eritrea', 'the State of Eritrea', 'the State of Eritrea'),
(53, 233, 'EE', 'EST', 'Estonsko', 'Estonia', 'Estonia', 'Estonská republika', 'the Republic of Estonia', 'the Republic of Estonia'),
(54, 231, 'ET', 'ETH', 'Etiopie', 'Ethiopia', 'Ethiopia', 'Etiopská federativní demokratická republika', 'the Federal Democratic Republic of Ethiopia', 'the Federal Democratic Republic of Ethiopia'),
(55, 234, 'FO', 'FRO', 'Faerské ostrovy', 'Faroe Islands (the)', 'Faroe Islands (the)', 'Faerské ostrovy', 'Faroe Islands (the)', 'Faroe Islands (the)'),
(56, 238, 'FK', 'FLK', 'Falklandy', 'Falkland Islands (the) (Malvinas)', 'Falkland Islands (the) (Malvinas)', 'Falklandské ostrovy', 'Falkland Islands (the) (Malvinas)', 'Falkland Islands (the) (Malvinas)'),
(57, 242, 'FJ', 'FJI', 'Fidži', 'Fiji', 'Fiji', 'Fidžijská republika', 'the Republic of Fiji', 'the Republic of Fiji'),
(58, 608, 'PH', 'PHL', 'Filipíny', 'Philippines (the)', 'Philippines (the)', 'Filipínská republika', 'the Republic of the Philippines', 'the Republic of the Philippines'),
(59, 246, 'FI', 'FIN', 'Finsko', 'Finland', 'Finland', 'Finská republika', 'the Republic of Finland', 'the Republic of Finland'),
(60, 250, 'FR', 'FRA', 'Francie', 'France', 'France', 'Francouzská republika', 'the French Republic', 'the French Republic'),
(61, 254, 'GF', 'GUF', 'Francouzská Guyana', 'French Guiana', 'French Guiana', 'Region Francouzská Guyana', 'French Guiana', 'French Guiana'),
(62, 260, 'TF', 'ATF', 'Francouzská jižní a antarktická území', 'French Southern Territories (the)', 'French Southern Territories (the)', 'Teritorium Francouzská jižní a antarktická území', 'French Southern Territories (the)', 'French Southern Territories (the)'),
(63, 258, 'PF', 'PYF', 'Francouzská Polynésie', 'French Polynesia', 'French Polynesia', 'Francouzská Polynésie', 'French Polynesia', 'French Polynesia'),
(64, 266, 'GA', 'GAB', 'Gabon', 'Gabon', 'Gabon', 'Gabonská republika', 'the Gabonese Republic', 'the Gabonese Republic'),
(65, 270, 'GM', 'GMB', 'Gambie', 'Gambia (the)', 'Gambia (the)', 'Gambijská republika', 'the Islamic Republic of the Gambia', 'the Islamic Republic of the Gambia'),
(66, 288, 'GH', 'GHA', 'Ghana', 'Ghana', 'Ghana', 'Ghanská republika', 'the Republic of Ghana', 'the Republic of Ghana'),
(67, 292, 'GI', 'GIB', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar'),
(68, 308, 'GD', 'GRD', 'Grenada', 'Grenada', 'Grenada', 'Grenadský stát', 'Grenada', 'Grenada'),
(69, 304, 'GL', 'GRL', 'Grónsko', 'Greenland', 'Greenland', 'Grónsko', 'Greenland', 'Greenland'),
(70, 268, 'GE', 'GEO', 'Gruzie', 'Georgia', 'Georgia', 'Gruzie', 'Georgia', 'Georgia'),
(71, 312, 'GP', 'GLP', 'Guadeloupe', 'Guadeloupe', 'Guadeloupe', 'Region Guadeloupe', 'Guadeloupe', 'Guadeloupe'),
(72, 316, 'GU', 'GUM', 'Guam', 'Guam', 'Guam', 'Teritorium Guam', 'Guam', 'Guam'),
(73, 320, 'GT', 'GTM', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemalská republika', 'the Republic of Guatemala', 'the Republic of Guatemala'),
(74, 831, 'GG', 'GGY', 'Guernsey', 'Guernsey', 'Guernsey', 'Bailiwick Guernsey', 'Guernsey', 'Guernsey'),
(75, 324, 'GN', 'GIN', 'Guinea', 'Guinea', 'Guinea', 'Guinejská republika', 'the Republic of Guinea', 'the Republic of Guinea'),
(76, 624, 'GW', 'GNB', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinea-Bissau', 'Republika Guinea-Bissau', 'the Republic of Guinea-Bissau', 'the Republic of Guinea-Bissau'),
(77, 328, 'GY', 'GUY', 'Guyana', 'Guyana', 'Guyana', 'Guyanská kooperativní republika', 'the Republic of Guyana', 'the Republic of Guyana'),
(78, 332, 'HT', 'HTI', 'Haiti', 'Haiti', 'Haiti', 'Republika Haiti', 'the Republic of Haiti', 'the Republic of Haiti'),
(79, 334, 'HM', 'HMD', 'Heardův ostrov a MacDonaldovy ostrovy', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'Heardův ostrov a MacDonaldovy ostrovy', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'),
(80, 340, 'HN', 'HND', 'Honduras', 'Honduras', 'Honduras', 'Honduraská republika', 'the Republic of Honduras', 'the Republic of Honduras'),
(81, 344, 'HK', 'HKG', 'Hongkong', 'Hong Kong', 'Hong Kong', 'Zvláštní administrativní oblast Čínské lidové republiky Hongkong', 'the Hong Kong Special Administrative Region of China', 'the Hong Kong Special Administrative Region of China'),
(82, 152, 'CL', 'CHL', 'Chile', 'Chile', 'Chile', 'Chilská republika', 'the Republic of Chile', 'the Republic of Chile'),
(83, 191, 'HR', 'HRV', 'Chorvatsko', 'Croatia', 'Croatia', 'Chorvatská republika', 'the Republic of Croatia', 'the Republic of Croatia'),
(84, 356, 'IN', 'IND', 'Indie', 'India', 'India', 'Indická republika', 'the Republic of India', 'the Republic of India'),
(85, 360, 'ID', 'IDN', 'Indonésie', 'Indonesia', 'Indonesia', 'Indonéská republika', 'the Republic of Indonesia', 'the Republic of Indonesia'),
(86, 368, 'IQ', 'IRQ', 'Irák', 'Iraq', 'Iraq', 'Irácká republika', 'the Republic of Iraq', 'the Republic of Iraq'),
(87, 364, 'IR', 'IRN', 'Írán', 'Iran (Islamic Republic of)', 'Iran (Islamic Republic of)', 'Íránská islámská republika', 'the Islamic Republic of Iran', 'the Islamic Republic of Iran'),
(88, 372, 'IE', 'IRL', 'Irsko', 'Ireland', 'Ireland', 'Irsko', 'Ireland', 'Ireland'),
(89, 352, 'IS', 'ISL', 'Island', 'Iceland', 'Iceland', 'Islandská republika', 'the Republic of Iceland', 'the Republic of Iceland'),
(90, 380, 'IT', 'ITA', 'Itálie', 'Italy', 'Italy', 'Italská republika', 'the Republic of Italy', 'the Republic of Italy'),
(91, 376, 'IL', 'ISR', 'Izrael', 'Israel', 'Israel', 'Stát Izrael', 'the State of Israel', 'the State of Israel'),
(92, 388, 'JM', 'JAM', 'Jamajka', 'Jamaica', 'Jamaica', 'Jamajka', 'Jamaica', 'Jamaica'),
(93, 392, 'JP', 'JPN', 'Japonsko', 'Japan', 'Japan', 'Japonsko', 'Japan', 'Japan'),
(94, 887, 'YE', 'YEM', 'Jemen', 'Yemen', 'Yemen', 'Jemenská republika', 'the Republic of Yemen', 'the Republic of Yemen'),
(95, 832, 'JE', 'JEY', 'Jersey', 'Jersey', 'Jersey', 'Bailiwick Jersey', 'Jersey', 'Jersey'),
(96, 710, 'ZA', 'ZAF', 'Jižní Afrika', 'South Africa', 'South Africa', 'Jihoafrická republika', 'the Republic of South Africa', 'the Republic of South Africa'),
(97, 239, 'GS', 'SGS', 'Jižní Georgie a Jižní Sandwichovy ostrovy', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'Jižní Georgie a Jižní Sandwichovy ostrovy', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands'),
(98, 728, 'SS', 'SSD', 'Jižní Súdán', 'South Sudan', 'South Sudan', 'Jihosúdánská republika', 'the Republic of South Sudan', 'the Republic of South Sudan'),
(99, 400, 'JO', 'JOR', 'Jordánsko', 'Jordan', 'Jordan', 'Jordánské hášimovské království', 'the Hashemite Kingdom of Jordan', 'the Hashemite Kingdom of Jordan'),
(100, 136, 'KY', 'CYM', 'Kajmanské ostrovy', 'Cayman Islands (the)', 'Cayman Islands (the)', 'Kajmanské ostrovy', 'Cayman Islands (the)', 'Cayman Islands (the)'),
(101, 116, 'KH', 'KHM', 'Kambodža', 'Cambodia', 'Cambodia', 'Kambodžské království', 'the Kingdom of Cambodia', 'the Kingdom of Cambodia'),
(102, 120, 'CM', 'CMR', 'Kamerun', 'Cameroon', 'Cameroon', 'Kamerunská republika', 'the Republic of Cameroon', 'the Republic of Cameroon'),
(103, 124, 'CA', 'CAN', 'Kanada', 'Canada', 'Canada', 'Kanada', 'Canada', 'Canada'),
(104, 132, 'CV', 'CPV', 'Kapverdy', 'Cape Verde', 'Cape Verde', 'Kapverdská republika', 'the Republic of Cape Verde', 'the Republic of Cape Verde'),
(105, 634, 'QA', 'QAT', 'Katar', 'Qatar', 'Qatar', 'Stát Katar', 'the State of Qatar', 'the State of Qatar'),
(106, 398, 'KZ', 'KAZ', 'Kazachstán', 'Kazakhstan', 'Kazakhstan', 'Republika Kazachstán', 'the Republic of Kazakhstan', 'the Republic of Kazakhstan'),
(107, 404, 'KE', 'KEN', 'Keňa', 'Kenya', 'Kenya', 'Keňská republika', 'the Republic of Kenya', 'the Republic of Kenya'),
(108, 296, 'KI', 'KIR', 'Kiribati', 'Kiribati', 'Kiribati', 'Republika Kiribati', 'the Republic of Kiribati', 'the Republic of Kiribati'),
(109, 166, 'CC', 'CCK', 'Kokosové (Keelingovy) ostrovy', 'Cocos (Keeling) Islands (the)', 'Cocos (Keeling) Islands (the)', 'Území Kokosové (Keelingovy) ostrovy', 'Cocos (Keeling) Islands (the)', 'Cocos (Keeling) Islands (the)'),
(110, 170, 'CO', 'COL', 'Kolumbie', 'Colombia', 'Colombia', 'Kolumbijská republika', 'the Republic of Colombia', 'the Republic of Colombia'),
(111, 174, 'KM', 'COM', 'Komory', 'Comoros (the)', 'Comoros (the)', 'Komorský svaz', 'the Union of the Comoros', 'the Union of the Comoros'),
(112, 178, 'CG', 'COG', 'Konžská republika', 'Congo (the)', 'Congo (the)', 'Konžská republika', 'the Republic of the Congo', 'the Republic of the Congo'),
(113, 408, 'KP', 'PRK', 'Korejská lidově demokratická republika', 'Korea (the Democratic People\'s Republic of)', 'Korea (the Democratic People\'s Republic of)', 'Korejská lidově demokratická republika', 'the Democratic People\'s Republic of Korea', 'the Democratic People\'s Republic of Korea'),
(114, 410, 'KR', 'KOR', 'Korejská republika', 'Korea (the Republic of)', 'Korea (the Republic of)', 'Korejská republika', 'the Republic of Korea', 'the Republic of Korea'),
(115, 95, 'XK', 'XXK', 'Kosovo', '', '', 'Kosovská republika', '', ''),
(116, 188, 'CR', 'CRI', 'Kostarika', 'Costa Rica', 'Costa Rica', 'Kostarická republika', 'the Republic of Costa Rica', 'the Republic of Costa Rica'),
(117, 192, 'CU', 'CUB', 'Kuba', 'Cuba', 'Cuba', 'Kubánská republika', 'the Republic of Cuba', 'the Republic of Cuba'),
(118, 414, 'KW', 'KWT', 'Kuvajt', 'Kuwait', 'Kuwait', 'Kuvajtský stát', 'the State of Kuwait', 'the State of Kuwait'),
(119, 196, 'CY', 'CYP', 'Kypr', 'Cyprus', 'Cyprus', 'Kyperská republika', 'the Republic of Cyprus', 'the Republic of Cyprus'),
(120, 417, 'KG', 'KGZ', 'Kyrgyzstán', 'Kyrgyzstan', 'Kyrgyzstan', 'Kyrgyzská republika', 'the Kyrgyz Republic', 'the Kyrgyz Republic'),
(121, 418, 'LA', 'LAO', 'Laos', 'Lao People\'s Democratic Republic (the)', 'Lao People\'s Democratic Republic (the)', 'Laoská lidově demokratická republika', 'the Lao People\'s Democratic Republic', 'the Lao People\'s Democratic Republic'),
(122, 426, 'LS', 'LSO', 'Lesotho', 'Lesotho', 'Lesotho', 'Lesothské království', 'the Kingdom of Lesotho', 'the Kingdom of Lesotho'),
(123, 422, 'LB', 'LBN', 'Libanon', 'Lebanon', 'Lebanon', 'Libanonská republika', 'the Lebanese Republic', 'the Lebanese Republic'),
(124, 430, 'LR', 'LBR', 'Libérie', 'Liberia', 'Liberia', 'Liberijská republika', 'the Republic of Liberia', 'the Republic of Liberia'),
(125, 434, 'LY', 'LBY', 'Libye', 'Libya', 'Libya', 'Libyjský stát', 'Libya', 'Libya'),
(126, 438, 'LI', 'LIE', 'Lichtenštejnsko', 'Liechtenstein', 'Liechtenstein', 'Lichtenštejnské knížectví', 'the Principality of Liechtenstein', 'the Principality of Liechtenstein'),
(127, 440, 'LT', 'LTU', 'Litva', 'Lithuania', 'Lithuania', 'Litevská republika', 'the Republic of Lithuania', 'the Republic of Lithuania'),
(128, 428, 'LV', 'LVA', 'Lotyšsko', 'Latvia', 'Latvia', 'Lotyšská republika', 'the Republic of Latvia', 'the Republic of Latvia'),
(129, 442, 'LU', 'LUX', 'Lucembursko', 'Luxembourg', 'Luxembourg', 'Lucemburské velkovévodství', 'the Grand Duchy of Luxembourg', 'the Grand Duchy of Luxembourg'),
(130, 446, 'MO', 'MAC', 'Macao', 'Macao', 'Macao', 'Zvláštní administrativní oblast Čínské lidové republiky Macao', 'Macao Special Administrative Region of China', 'Macao Special Administrative Region of China'),
(131, 450, 'MG', 'MDG', 'Madagaskar', 'Madagascar', 'Madagascar', 'Madagaskarská republika', 'the Republic of Madagascar', 'the Republic of Madagascar'),
(132, 348, 'HU', 'HUN', 'Maďarsko', 'Hungary', 'Hungary', 'Maďarsko', 'Hungary', 'Hungary'),
(133, 807, 'MK', 'MKD', 'Makedonie', 'Macedonia (the former Yugoslav Republic of)', 'Macedonia (the former Yugoslav Republic of)', 'Bývalá jugoslávská republika Makedonie', 'the former Yugoslav Republic of Macedonia', 'the former Yugoslav Republic of Macedonia'),
(134, 458, 'MY', 'MYS', 'Malajsie', 'Malaysia', 'Malaysia', 'Malajsie', 'Malaysia', 'Malaysia'),
(135, 454, 'MW', 'MWI', 'Malawi', 'Malawi', 'Malawi', 'Malawiská republika', 'the Republic of Malawi', 'the Republic of Malawi'),
(136, 462, 'MV', 'MDV', 'Maledivy', 'Maldives', 'Maldives', 'Maledivská republika', 'the Republic of Maldives', 'the Republic of Maldives'),
(137, 466, 'ML', 'MLI', 'Mali', 'Mali', 'Mali', 'Republika Mali', 'the Republic of Mali', 'the Republic of Mali'),
(138, 470, 'MT', 'MLT', 'Malta', 'Malta', 'Malta', 'Maltská republika', 'the Republic of Malta', 'the Republic of Malta'),
(139, 833, 'IM', 'IMN', 'Man', 'Isle of Man', 'Isle of Man', 'Ostrov Man', 'Isle of Man', 'Isle of Man'),
(140, 504, 'MA', 'MAR', 'Maroko', 'Morocco', 'Morocco', 'Marocké království', 'the Kingdom of Morocco', 'the Kingdom of Morocco'),
(141, 584, 'MH', 'MHL', 'Marshallovy ostrovy', 'Marshall Islands (the)', 'Marshall Islands (the)', 'Republika Marshallovy ostrovy', 'the Republic of the Marshall Islands', 'the Republic of the Marshall Islands'),
(142, 474, 'MQ', 'MTQ', 'Martinik', 'Martinique', 'Martinique', 'Region Martinik', 'Martinique', 'Martinique'),
(143, 480, 'MU', 'MUS', 'Mauricius', 'Mauritius', 'Mauritius', 'Mauricijská republika', 'the Republic of Mauritius', 'the Republic of Mauritius'),
(144, 478, 'MR', 'MRT', 'Mauritánie', 'Mauritania', 'Mauritania', 'Mauritánská islámská republika', 'the Islamic Republic of Mauritania', 'the Islamic Republic of Mauritania'),
(145, 175, 'YT', 'MYT', 'Mayotte', 'Mayotte', 'Mayotte', 'Departementní společenství Mayotte', 'Mayotte', 'Mayotte'),
(146, 581, 'UM', 'UMI', 'Menší odlehlé ostrovy USA', 'United States Minor Outlying Islands (the)', 'United States Minor Outlying Islands (the)', 'Menší odlehlé ostrovy USA', 'United States Minor Outlying Islands (the)', 'United States Minor Outlying Islands (the)'),
(147, 484, 'MX', 'MEX', 'Mexiko', 'Mexico', 'Mexico', 'Spojené státy mexické', 'the United Mexican States', 'the United Mexican States'),
(148, 583, 'FM', 'FSM', 'Mikronésie', 'Micronesia (Federated States of)', 'Micronesia (Federated States of)', 'Federativní státy Mikronésie', 'the Federated States of Micronesia', 'the Federated States of Micronesia'),
(149, 498, 'MD', 'MDA', 'Moldavsko', 'Moldova (the Republic of)', 'Moldova (the Republic of)', 'Moldavská republika', 'the Republic of Moldova', 'the Republic of Moldova'),
(150, 492, 'MC', 'MCO', 'Monako', 'Monaco', 'Monaco', 'Monacké knížectví', 'the Principality of Monaco', 'the Principality of Monaco'),
(151, 496, 'MN', 'MNG', 'Mongolsko', 'Mongolia', 'Mongolia', 'Mongolsko', 'Mongolia', 'Mongolia'),
(152, 500, 'MS', 'MSR', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat'),
(153, 508, 'MZ', 'MOZ', 'Mosambik', 'Mozambique', 'Mozambique', 'Mosambická republika', 'the Republic of Mozambique', 'the Republic of Mozambique'),
(154, 104, 'MM', 'MMR', 'Myanmar', 'Myanmar', 'Myanmar', 'Republika Myanmarský svaz', 'the Republic of the Union of Myanmar', 'the Republic of the Union of Myanmar'),
(155, 516, 'NA', 'NAM', 'Namibie', 'Namibia', 'Namibia', 'Namibijská republika', 'the Republic of Namibia', 'the Republic of Namibia'),
(156, 520, 'NR', 'NRU', 'Nauru', 'Nauru', 'Nauru', 'Republika Nauru', 'the Republic of Nauru', 'the Republic of Nauru'),
(157, 276, 'DE', 'DEU', 'Německo', 'Germany', 'Germany', 'Spolková republika Německo', 'the Federal Republic of Germany', 'the Federal Republic of Germany'),
(158, 524, 'NP', 'NPL', 'Nepál', 'Nepal', 'Nepal', 'Nepálská federativní demokratická republika', 'the Federal Democratic Republic of Nepal', 'the Federal Democratic Republic of Nepal'),
(159, 562, 'NE', 'NER', 'Niger', 'Niger (the)', 'Niger (the)', 'Nigerská republika', 'the Republic of the Niger', 'the Republic of the Niger'),
(160, 566, 'NG', 'NGA', 'Nigérie', 'Nigeria', 'Nigeria', 'Nigerijská federativní republika', 'the Federal Republic of Nigeria', 'the Federal Republic of Nigeria'),
(161, 558, 'NI', 'NIC', 'Nikaragua', 'Nicaragua', 'Nicaragua', 'Nikaragujská republika', 'the Republic of Nicaragua', 'the Republic of Nicaragua'),
(162, 570, 'NU', 'NIU', 'Niue', 'Niue', 'Niue', 'Niue', 'Niue', 'Niue'),
(163, 528, 'NL', 'NLD', 'Nizozemsko', 'Netherlands (the)', 'Netherlands (the)', 'Nizozemsko', 'the Kingdom of the Netherlands', 'the Kingdom of the Netherlands'),
(164, 574, 'NF', 'NFK', 'Norfolk', 'Norfolk Island', 'Norfolk Island', 'Území Norfolk', 'Norfolk Island', 'Norfolk Island'),
(165, 578, 'NO', 'NOR', 'Norsko', 'Norway', 'Norway', 'Norské království', 'the Kingdom of Norway', 'the Kingdom of Norway'),
(166, 540, 'NC', 'NCL', 'Nová Kaledonie', 'New Caledonia', 'New Caledonia', 'Nová Kaledonie', 'New Caledonia', 'New Caledonia'),
(167, 554, 'NZ', 'NZL', 'Nový Zéland', 'New Zealand', 'New Zealand', 'Nový Zéland', 'New Zealand', 'New Zealand'),
(168, 512, 'OM', 'OMN', 'Omán', 'Oman', 'Oman', 'Sultanát Omán', 'the Sultanate of Oman', 'the Sultanate of Oman'),
(169, 586, 'PK', 'PAK', 'Pákistán', 'Pakistan', 'Pakistan', 'Pákistánská islámská republika', 'the Islamic Republic of Pakistan', 'the Islamic Republic of Pakistan'),
(170, 585, 'PW', 'PLW', 'Palau', 'Palau', 'Palau', 'Republika Palau', 'the Republic of Palau', 'the Republic of Palau'),
(171, 275, 'PS', 'PSE', 'Palestina', 'Palestine, State of', 'Palestine, State of', 'Palestinská autonomní území', 'the State of Palestine', 'the State of Palestine'),
(172, 591, 'PA', 'PAN', 'Panama', 'Panama', 'Panama', 'Panamská republika', 'the Republic of Panama', 'the Republic of Panama'),
(173, 598, 'PG', 'PNG', 'Papua Nová Guinea', 'Papua New Guinea', 'Papua New Guinea', 'Nezávislý stát Papua Nová Guinea', 'the Independent State of Papua New Guinea', 'the Independent State of Papua New Guinea'),
(174, 600, 'PY', 'PRY', 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguayská republika', 'the Republic of Paraguay', 'the Republic of Paraguay'),
(175, 604, 'PE', 'PER', 'Peru', 'Peru', 'Peru', 'Peruánská republika', 'the Republic of Peru', 'the Republic of Peru'),
(176, 612, 'PN', 'PCN', 'Pitcairn', 'Pitcairn', 'Pitcairn', 'Pitcairnovy ostrovy', 'Pitcairn', 'Pitcairn'),
(177, 384, 'CI', 'CIV', 'Pobřeží slonoviny', 'Côte d\'Ivoire', 'Côte d\'Ivoire', 'Republika Pobřeží slonoviny', 'the Republic of Côte d\'Ivoire', 'the Republic of Côte d\'Ivoire'),
(178, 616, 'PL', 'POL', 'Polsko', 'Poland', 'Poland', 'Polská republika', 'the Republic of Poland', 'the Republic of Poland'),
(179, 630, 'PR', 'PRI', 'Portoriko', 'Puerto Rico', 'Puerto Rico', 'Portorické společenství', 'Puerto Rico', 'Puerto Rico'),
(180, 620, 'PT', 'PRT', 'Portugalsko', 'Portugal', 'Portugal', 'Portugalská republika', 'the Portuguese Republic', 'the Portuguese Republic'),
(181, 40, 'AT', 'AUT', 'Rakousko', 'Austria', 'Austria', 'Rakouská republika', 'the Republic of Austria', 'the Republic of Austria'),
(182, 638, 'RE', 'REU', 'Réunion', 'Réunion', 'Réunion', 'Region Réunion', 'Réunion', 'Réunion'),
(183, 226, 'GQ', 'GNQ', 'Rovníková Guinea', 'Equatorial Guinea', 'Equatorial Guinea', 'Republika Rovníková Guinea', 'the Republic of Equatorial Guinea', 'the Republic of Equatorial Guinea'),
(184, 642, 'RO', 'ROU', 'Rumunsko', 'Romania', 'Romania', 'Rumunsko', 'Romania', 'Romania'),
(185, 643, 'RU', 'RUS', 'Rusko', 'Russian Federation (the)', 'Russian Federation (the)', 'Ruská federace', 'the Russian Federation', 'the Russian Federation'),
(186, 646, 'RW', 'RWA', 'Rwanda', 'Rwanda', 'Rwanda', 'Rwandská republika', 'the Republic of Rwanda', 'the Republic of Rwanda'),
(187, 300, 'GR', 'GRC', 'Řecko', 'Greece', 'Greece', 'Řecká republika', 'the Hellenic Republic', 'the Hellenic Republic'),
(188, 666, 'PM', 'SPM', 'Saint Pierre a Miquelon', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'Územní společenství Saint Pierre a Miquelon', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'),
(189, 222, 'SV', 'SLV', 'Salvador', 'El Salvador', 'El Salvador', 'Salvadorská republika', 'the Republic of El Salvador', 'the Republic of El Salvador'),
(190, 882, 'WS', 'WSM', 'Samoa', 'Samoa', 'Samoa', 'Nezávislý stát Samoa', 'the Independent State of Samoa', 'the Independent State of Samoa'),
(191, 674, 'SM', 'SMR', 'San Marino', 'San Marino', 'San Marino', 'Republika San Marino', 'the Republic of San Marino', 'the Republic of San Marino'),
(192, 682, 'SA', 'SAU', 'Saúdská Arábie', 'Saudi Arabia', 'Saudi Arabia', 'Království Saúdská Arábie', 'the Kingdom of Saudi Arabia', 'the Kingdom of Saudi Arabia'),
(193, 686, 'SN', 'SEN', 'Senegal', 'Senegal', 'Senegal', 'Senegalská republika', 'the Republic of Senegal', 'the Republic of Senegal'),
(194, 580, 'MP', 'MNP', 'Severní Mariany', 'Northern Mariana Islands (the)', 'Northern Mariana Islands (the)', 'Společenství Severní Mariany', 'the Commonwealth of the Northern Mariana Islands', 'the Commonwealth of the Northern Mariana Islands'),
(195, 690, 'SC', 'SYC', 'Seychely', 'Seychelles', 'Seychelles', 'Seychelská republika', 'the Republic of Seychelles', 'the Republic of Seychelles'),
(196, 694, 'SL', 'SLE', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Republika Sierra Leone', 'the Republic of Sierra Leone', 'the Republic of Sierra Leone'),
(197, 702, 'SG', 'SGP', 'Singapur', 'Singapore', 'Singapore', 'Singapurská republika', 'the Republic of Singapore', 'the Republic of Singapore'),
(198, 703, 'SK', 'SVK', 'Slovensko', 'Slovakia', 'Slovakia', 'Slovenská republika', 'the Slovak Republic', 'the Slovak Republic'),
(199, 705, 'SI', 'SVN', 'Slovinsko', 'Slovenia', 'Slovenia', 'Slovinská republika', 'the Republic of Slovenia', 'the Republic of Slovenia'),
(200, 706, 'SO', 'SOM', 'Somálsko', 'Somalia', 'Somalia', 'Somálská federativní republika', 'the Federal Republic of Somalia', 'the Federal Republic of Somalia'),
(201, 784, 'AE', 'ARE', 'Spojené arabské emiráty', 'United Arab Emirates (the)', 'United Arab Emirates (the)', 'Stát Spojené arabské emiráty', 'the United Arab Emirates', 'the United Arab Emirates'),
(202, 840, 'US', 'USA', 'Spojené státy', 'United States of America (the)', 'United States of America (the)', 'Spojené státy americké', 'the United States of America', 'the United States of America'),
(203, 688, 'RS', 'SRB', 'Srbsko', 'Serbia', 'Serbia', 'Srbská republika', 'the Republic of Serbia', 'the Republic of Serbia'),
(204, 140, 'CF', 'CAF', 'Středoafrická republika', 'Central African Republic (the)', 'Central African Republic (the)', 'Středoafrická republika', 'the Central African Republic', 'the Central African Republic'),
(205, 729, 'SD', 'SDN', 'Súdán', 'Sudan (the)', 'Sudan (the)', 'Súdánská republika', 'the Republic of the Sudan', 'the Republic of the Sudan'),
(206, 740, 'SR', 'SUR', 'Surinam', 'Suriname', 'Suriname', 'Surinamská republika', 'the Republic of Suriname', 'the Republic of Suriname'),
(207, 654, 'SH', 'SHN', 'Svatá Helena', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'Svatá Helena, Ascension a Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'),
(208, 662, 'LC', 'LCA', 'Svatá Lucie', 'Saint Lucia', 'Saint Lucia', 'Svatá Lucie', 'Saint Lucia', 'Saint Lucia'),
(209, 652, 'BL', 'BLM', 'Svatý Bartoloměj', 'Saint Barthélemy', 'Saint Barthélemy', 'Společenství Svatý Bartoloměj', 'Saint Barthélemy', 'Saint Barthélemy'),
(210, 659, 'KN', 'KNA', 'Svatý Kryštof a Nevis', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'Federace Svatý Kryštof a Nevis', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis'),
(211, 663, 'MF', 'MAF', 'Svatý Martin (FR)', 'Saint Martin (French part)', 'Saint Martin (French part)', 'Společenství Svatý Martin', 'Saint Martin (French part)', 'Saint Martin (French part)'),
(212, 534, 'SX', 'SXM', 'Svatý Martin (NL)', 'Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)', 'Svatý Martin (NL)', 'Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)'),
(213, 678, 'ST', 'STP', 'Svatý Tomáš a Princův ostrov', 'Sao Tome and Principe', 'Sao Tome and Principe', 'Demokratická republika Svatý Tomáš a Princův ostrov', 'the Democratic Republic of Sao Tome and Principe', 'the Democratic Republic of Sao Tome and Principe'),
(214, 670, 'VC', 'VCT', 'Svatý Vincenc a Grenadiny', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'Svatý Vincenc a Grenadiny', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'),
(215, 748, 'SZ', 'SWZ', 'Svazijsko', 'Swaziland', 'Swaziland', 'Svazijské království', 'the Kingdom of Swaziland', 'the Kingdom of Swaziland'),
(216, 760, 'SY', 'SYR', 'Sýrie', 'Syrian Arab Republic', 'Syrian Arab Republic', 'Syrská arabská republika', 'the Syrian Arab Republic', 'the Syrian Arab Republic'),
(217, 90, 'SB', 'SLB', 'Šalomounovy ostrovy', 'Solomon Islands', 'Solomon Islands', 'Šalomounovy ostrovy', 'Solomon Islands (the)', 'Solomon Islands (the)'),
(218, 724, 'ES', 'ESP', 'Španělsko', 'Spain', 'Spain', 'Španělské království', 'the Kingdom of Spain', 'the Kingdom of Spain'),
(219, 744, 'SJ', 'SJM', 'Špicberky a Jan Mayen', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen', 'Špicberky a Jan Mayen', 'Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'),
(220, 144, 'LK', 'LKA', 'Šrí Lanka', 'Sri Lanka', 'Sri Lanka', 'Šrílanská demokratická socialistická republika', 'the Democratic Socialist Republic of Sri Lanka', 'the Democratic Socialist Republic of Sri Lanka'),
(221, 752, 'SE', 'SWE', 'Švédsko', 'Sweden', 'Sweden', 'Švédské království', 'the Kingdom of Sweden', 'the Kingdom of Sweden'),
(222, 756, 'CH', 'CHE', 'Švýcarsko', 'Switzerland', 'Switzerland', 'Švýcarská konfederace', 'the Swiss Confederation', 'the Swiss Confederation'),
(223, 762, 'TJ', 'TJK', 'Tádžikistán', 'Tajikistan', 'Tajikistan', 'Republika Tádžikistán', 'the Republic of Tajikistan', 'the Republic of Tajikistan'),
(224, 834, 'TZ', 'TZA', 'Tanzanie', 'Tanzania, United Republic of', 'Tanzania, United Republic of', 'Tanzanská sjednocená republika', 'the United Republic of Tanzania', 'the United Republic of Tanzania'),
(225, 764, 'TH', 'THA', 'Thajsko', 'Thailand', 'Thailand', 'Thajské království', 'the Kingdom of Thailand', 'the Kingdom of Thailand'),
(226, 158, 'TW', 'TWN', 'Tchaj-wan', 'Taiwan (Province of China)', 'Taiwan (Province of China)', 'Čínská republika (Tchaj-wan)', 'Taiwan (Province of China)', 'Taiwan (Province of China)'),
(227, 768, 'TG', 'TGO', 'Togo', 'Togo', 'Togo', 'Tožská republika', 'the Togolese Republic', 'the Togolese Republic'),
(228, 772, 'TK', 'TKL', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau'),
(229, 776, 'TO', 'TON', 'Tonga', 'Tonga', 'Tonga', 'Království Tonga', 'the Kingdom of Tonga', 'the Kingdom of Tonga'),
(230, 780, 'TT', 'TTO', 'Trinidad a Tobago', 'Trinidad and Tobago', 'Trinidad and Tobago', 'Republika Trinidad a Tobago', 'the Republic of Trinidad and Tobago', 'the Republic of Trinidad and Tobago'),
(231, 788, 'TN', 'TUN', 'Tunisko', 'Tunisia', 'Tunisia', 'Tuniská republika', 'the Republic of Tunisia', 'the Republic of Tunisia'),
(232, 792, 'TR', 'TUR', 'Turecko', 'Turkey', 'Turkey', 'Turecká republika', 'the Republic of Turkey', 'the Republic of Turkey'),
(233, 795, 'TM', 'TKM', 'Turkmenistán', 'Turkmenistan', 'Turkmenistan', 'Turkmenistán', 'Turkmenistan', 'Turkmenistan'),
(234, 796, 'TC', 'TCA', 'Turks a Caicos', 'Turks and Caicos Islands (the)', 'Turks and Caicos Islands (the)', 'Ostrovy Turks a Caicos', 'Turks and Caicos Islands (the)', 'Turks and Caicos Islands (the)'),
(235, 798, 'TV', 'TUV', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu'),
(236, 800, 'UG', 'UGA', 'Uganda', 'Uganda', 'Uganda', 'Ugandská republika', 'the Republic of Uganda', 'the Republic of Uganda'),
(237, 804, 'UA', 'UKR', 'Ukrajina', 'Ukraine', 'Ukraine', 'Ukrajina', 'Ukraine', 'Ukraine'),
(238, 858, 'UY', 'URY', 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguayská východní republika', 'the Eastern Republic of Uruguay', 'the Eastern Republic of Uruguay'),
(239, 860, 'UZ', 'UZB', 'Uzbekistán', 'Uzbekistan', 'Uzbekistan', 'Republika Uzbekistán', 'the Republic of Uzbekistan', 'the Republic of Uzbekistan'),
(240, 162, 'CX', 'CXR', 'Vánoční ostrov', 'Christmas Island', 'Christmas Island', 'Území Vánoční ostrov', 'Christmas Island', 'Christmas Island'),
(241, 548, 'VU', 'VUT', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Republika Vanuatu', 'the Republic of Vanuatu', 'the Republic of Vanuatu'),
(242, 336, 'VA', 'VAT', 'Vatikán', 'Holy See (the)', 'Holy See (the)', 'Vatikánský městský stát', 'Holy See (the) (Vatican City State)', 'Holy See (the) (Vatican City State)'),
(243, 826, 'GB', 'GBR', 'Velká Británie', 'United Kingdom of Great Britain and Northern Irela', 'United Kingdom of Great Britain and Northern Irela', 'Spojené království Velké Británie a Severního Irska', 'the United Kingdom of Great Britain and Northern Ireland', 'the United Kingdom of Great Britain and Northern Ireland'),
(244, 862, 'VE', 'VEN', 'Venezuela', 'Venezuela (Bolivarian Republic of)', 'Venezuela (Bolivarian Republic of)', 'Bolívarovská republika Venezuela', 'the Bolivarian Republic of Venezuela', 'the Bolivarian Republic of Venezuela'),
(245, 704, 'VN', 'VNM', 'Vietnam', 'Viet Nam', 'Viet Nam', 'Vietnamská socialistická republika', 'the Socialist Republic of Viet Nam', 'the Socialist Republic of Viet Nam'),
(246, 626, 'TL', 'TLS', 'Východní Timor', 'Timor-Leste', 'Timor-Leste', 'Demokratická republika Východní Timor', 'the Democratic Republic of Timor-Leste', 'the Democratic Republic of Timor-Leste'),
(247, 876, 'WF', 'WLF', 'Wallis a Futuna', 'Wallis and Futuna', 'Wallis and Futuna', 'Teritorium Wallisovy ostrovy a Futuna', 'Wallis and Futuna Islands', 'Wallis and Futuna Islands'),
(248, 894, 'ZM', 'ZMB', 'Zambie', 'Zambia', 'Zambia', 'Zambijská republika', 'the Republic of Zambia', 'the Republic of Zambia'),
(249, 732, 'EH', 'ESH', 'Západní Sahara', 'Western Sahara', 'Western Sahara', 'Saharská arabská demokratická republika', 'Western Sahara', 'Western Sahara'),
(250, 716, 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwe', 'Zimbabwe', 'Zimbabwská republika', 'the Republic of Zimbabwe', 'the Republic of Zimbabwe');
