<div id="userButtons">
   <form method="post" action="<?= $this->link(); ?>">
      <input id="login_submit" type="submit" name="logout_submit" value="<?= $this->tr('Odhlásit'); ?>" />
   </form>
   <form action="<?= $this->l()->route('changePasswd'); ?>" method="get">
      <input type="submit" value="<?= $this->tr('Změnit heslo'); ?>" />
   </form>
   <form action="<?= $this->l()->route('changeUser'); ?>" method="get">
      <input type="submit" value="<?= $this->tr('Změnit údaje'); ?>" />
   </form>
</div>