<div class="login_form_module">
   <div>
      <form method="post" action="<?=$this->l();?>">
         <p class="login_form_label">
            <img src="./images/icons/key.png" width="32" height="17" /><b><?=$this->_m('Přihlášení');?></b>
         </p>
         <table>
            <tr>
               <td><?=$this->_m('Jméno');?>:</td>
               <td align="right"><input class="login_input" type="text" name="login_username" maxlength="20" id="login_panel" size="22" value="<?=$this->post($_POST["login_username"]);?>" /></td>
            </tr>
            <tr>
               <td><?=$this->_m('Heslo');?>:</td>
               <td align="right"><input type="password" name="login_passwd" maxlength="20" id="passwd_panel" size="22" value="" /></td>
            </tr>
            <tr>
               <td colspan="2" align="right">
                  <input id="login_submit" type="submit" name="login_submit" value="<?=$this->_m('Přihlásit');?>" />
               </td>
            </tr>
         </table>
      </form>
   </div>
</div>