<h1><?php echo  $this->category()->getName(); ?></h1>
<div class="main-content-form-edit" id="login-form">
   <div class="clearfix">
      <?php
      $loginForm = Auth::getAuthenticator('internal')->getLoginForm();
      $loginForm->html()->addClass('clearfix')->addClass('form-vertical');
      echo $loginForm->renderStart();
      ?>
         <div class="login-form-label">
            <h2><?php echo  $this->tr('Přihlášení'); ?></h2>
         </div>
         <div class="form-group">
            <div class="form-labels">
               <?php echo $loginForm->{Auth_Provider_Internal::FORM_USERNAME}->label();?>
            </div>
            <div class="form-controls">
               <?php 
               $loginForm->{Auth_Provider_Internal::FORM_USERNAME}->html()->addClass('form-control');
               echo $loginForm->{Auth_Provider_Internal::FORM_USERNAME}->control();
               ?>
            </div>
         </div>
         <div class="form-group">
            <div class="form-labels">
               <?php echo $loginForm->{Auth_Provider_Internal::FORM_PASSWORD}->label();?>
            </div>
            <div class="form-controls">
               <?php 
               $loginForm->{Auth_Provider_Internal::FORM_PASSWORD}->html()->addClass('form-control');
               echo $loginForm->{Auth_Provider_Internal::FORM_PASSWORD}->control();
               ?>
            </div>
         </div>
         <div class="form-group login-permanent">
            <div class="form-controls">
               <?php echo $loginForm->{Auth_Provider_Internal::FORM_PERMANENT}->control()?>
               <label for="login-permanent"><?php echo $loginForm->{Auth_Provider_Internal::FORM_PERMANENT}->label(null, true)?></label>
            </div>
         </div>
         <div class="form-group">
            <div class="form-controls">
               <?php echo $loginForm->{Auth_Provider_Internal::FORM_SUBMIT}->control()?>
            </div>
         </div>
      <?php
      echo $loginForm->renderEnd();
      
      if($this->redirUrl != null){
         ?>
         <a href="<?php echo $this->redirUrl?>">Přihlášení přes kořenový web</a>
         <?php
      }
      
      ?>
      <p class="login-lost-password">
         <a href="<?php echo  $this->link()->route('newPassword') ?>" title="<?php echo  $this->tr('Obnovit zapomenuté heslo') ?>"><?php echo  $this->tr('Zapomenuté heslo') ?></a>
      </p>
      <?php if(Auth::isAuthenticator('google')){?>
      <div>
         <a href="<?php echo Auth::getAuthenticator('google')->getAuthUrl()?>"
            ><img width="200" src="https://developers.google.com/accounts/images/sign-in-with-google.png" alt="" /></a>
      </div>
      <?php }?>
      <?php if(Auth::isAuthenticator('openid')){?>
      <div>
         <form action="" method="post">
            <label for="">OpenID</label>
            <input type="text" name="<?php echo Auth_Provider_OpenID::FORM_ID_NAME?>" value="" />
            <button type="submit" name="<?php echo Auth_Provider_OpenID::FORM_SUBMIT_NAME?>">Přihlásit</button>
         </form>
      </div>
      <?php }?>
   </div>
</div>