<?
$icon = null;
if($this->panelObj()->getIcon() != null){
   $icon = '<img src="'.Panel_Obj::getIconDir().$this->panelObj()->getIcon().'" alt="'.$this->panelObj()->getIcon().'" />';
}
$backImg = null;
if($this->panelObj()->getBackImage() != null){
   $backImg = 'background-image: url(\''.Panel_Obj::getBackImgDir().$this->panelObj()->getBackImage().'\');';
}
?>
<p class="panel-box-label"><?=$icon?><a href="<?=$this->l();?>" title="<?=htmlspecialchars($this->panelObj()->getName())?>"><?=$this->panelObj()->getName()?></a></p>
<div class="panel-box-content" style="<?=$backImg?>">
<form method="post" action="<?=$this->currentLink;?>">
   <p>
      <? if(!Auth::isLoginStatic()){?>
      <label for="panel_login_username"><?=$this->_('Jméno')?></label><br />
      <input id="panel_login_username" class="login_input" type="text" 
             name="login_username" maxlength="20" size="15" value="_intranet_login"
             onclick="if (this.value == '_intranet_login') { this.value = ''; }"
             onblur="if (this.value == '') { this.value = '_intranet_login'; }"/><br />
      <label for="panel_login__passwd"><?=$this->_('Heslo')?></label><br />
      <input id="panel_login__passwd" type="password" name="login_passwd" maxlength="20" 
             size="15" value="Password" onclick="if (this.value == 'Password') { this.value = ''; }"
             onblur="if (this.value == '') { this.value = 'Password'; }"/><br />
      <input id="login_submit" type="submit" name="login_submit" value="<?=$this->_('přihlásit')?>" />
      <? } else { ?>
      <?=$this->_('Přihlášen')?>: <a href="<?=$this->l();?>" title="<?=htmlspecialchars($this->panelObj()->getName())?>"><?=Auth::getUserName()?></a><br />
      <input id="login_submit" type="submit" name="logout_submit" value="<?=$this->_('odhlásit')?>" />
      <? } ?>
   </p>
</form>
</div>