<?
$this->addCssFile("style.css");
?>
<h1><?=$this->_('Informace o účtu')?></h1>
<div class="main-content-detail">
   <table>
      <tr>
         <th width="100"><?=$this->_('Login')?></th>
         <td width="300"><?=$this->user->{Model_Users::COLUMN_USERNAME}?></td>
      </tr>
      <tr>
         <th><?=$this->_('Jméno')?></th>
         <td><?=$this->user->{Model_Users::COLUMN_NAME}?></td>
      </tr>
      <tr>
         <th><?=$this->_('Přijmení')?></th>
         <td><?=$this->user->{Model_Users::COLUMN_SURNAME}?></td>
      </tr>
      <tr>
         <th><?=$this->_('Skupina')?></th>
         <td><?=$this->user->{Model_Users::COLUMN_GROUP_NAME}?></td>
      </tr>
      <tr>
         <th><?=$this->_('E-maily')?></th>
         <td><?=$this->user->{Model_Users::COLUMN_MAIL}?></td>
      </tr>
      <tr>
         <th><?=$this->_('Poznámky')?></th>
         <td><?=$this->user->{Model_Users::COLUMN_NOTE}?></td>
      </tr>
   </table>
   <br />
   <div id="userButtons">
      <form method="post" action="<?=$this->link();?>">
         <input id="login_submit" type="submit" name="logout_submit" value="<?=$this->_('Odhlásit');?>" />
      </form>
      <form action="<?=$this->l()->route('changePasswd');?>" method="get">
         <input type="submit" value="<?=$this->_('Změnit heslo');?>" />
      </form>
      <form action="<?=$this->l()->route('changeUser');?>" method="get">
         <input type="submit" value="<?=$this->_('Změnit údaje');?>" />
      </form>
   </div>
</div>