<?
$this->addCssFile("style.css");
$this->addJsPlugin(new JsPlugin_JQueryCSS());
?>
<h1><?=$this->_('Informace o účtu')?></h1>
<div class="main-content-detail" id="user-dateil">
   <table>
      <tr>
         <th class="ui-widget-header" width="200"><?=$this->_('Uživatelké jméno')?></th>
         <td class="ui-widget-content" width="300"><?=$this->user->{Model_Users::COLUMN_USERNAME}?></td>
      </tr>
      <tr>
         <th class="ui-widget-header"><?=$this->_('Jméno')?></th>
         <td class="ui-widget-content"><?=$this->user->{Model_Users::COLUMN_NAME}?></td>
      </tr>
      <tr>
         <th class="ui-widget-header"><?=$this->_('Přijmení')?></th>
         <td class="ui-widget-content"><?=$this->user->{Model_Users::COLUMN_SURNAME}?></td>
      </tr>
      <tr>
         <th class="ui-widget-header"><?=$this->_('Skupina')?></th>
         <td class="ui-widget-content"><?=$this->user->{Model_Users::COLUMN_GROUP_NAME}?></td>
      </tr>
      <tr>
         <th class="ui-widget-header"><?=$this->_('E-maily')?></th>
         <td class="ui-widget-content"><?=$this->user->{Model_Users::COLUMN_MAIL}?></td>
      </tr>
      <tr>
         <th class="ui-widget-header"><?=$this->_('Poznámky')?></th>
         <td class="ui-widget-content"><?=$this->user->{Model_Users::COLUMN_NOTE}?></td>
      </tr>
   </table>
   <br />
   <?=$this->includeTpl('buttons.phtml')?>
</div>