<?
$this->addCssFile("style.css");
?>
<h1><?=$this->_('Informace o účtu')?></h1>
<div class="main-content-detail">
   <table>
      <tr>
         <th width="100"><?=$this->_('Login')?></th>
         <td width="300"><?=$this->user->{Model_Users::COLUMN_USERNAME}?></td>
      </tr>
      <tr>
         <th><?=$this->_('Jméno')?></th>
         <td><?=$this->user->{Model_Users::COLUMN_NAME}?></td>
      </tr>
      <tr>
         <th><?=$this->_('Přijmení')?></th>
         <td><?=$this->user->{Model_Users::COLUMN_SURNAME}?></td>
      </tr>
      <tr>
         <th><?=$this->_('Skupina')?></th>
         <td><?=$this->user->{Model_Users::COLUMN_GROUP_NAME}?></td>
      </tr>
      <tr>
         <th><?=$this->_('E-maily')?></th>
         <td><?=$this->user->{Model_Users::COLUMN_MAIL}?></td>
      </tr>
      <tr>
         <th><?=$this->_('Poznámky')?></th>
         <td><?=$this->user->{Model_Users::COLUMN_NOTE}?></td>
      </tr>
   </table>
   <br />
   <?=$this->includeTpl('buttons.phtml')?>
</div>