<h2>Sráva uživatelů</h2>
<p>Tato stránka slouží ke správě všech uživatelských účtů v systému. Vidíte zde všechny uživatele z dané skupiny.</p>
<h3>Přepnutí zobrazené skupiny</h3>
<p>V záhlaví tabulky s uživateli je přepínač pro výběr uživatelské skupiny, která se má zobrazit.</p>
<h3>Úpravy uživatelů</h3>
<p>Úpravy uživatelů se provadí pomocí tlačítek v zápatí tabulky (plus, upravit, koš).</p>
<h3>Blokace</h3>
<p>Pro zablokování uživatele slouží zaškrtávací tlačítko ve sloupci <em>Blokace</em>. po zablokování má uživatel zakázáno přihlášení a jekékoliv úpravy.</p>
