<h2>Vytvoření uživatele</h2>
<p>Na této stránce můžete vytvořit nový uživatelský účet. </p>
<h3>Odeslání informací</h3>
<p>Při zaškrtnutí <em>odeslání informací</em> se novému uživateli zadané informace zašlou na uvedený e-mail.</p>
<h3>Skupina uživatele</h3>
<p><strong>Zkontrolujte si</strong> předeším do jaké <strong>skupiny</strong> uživatele zařazujete! Nový uživatel tak může získat plný přístup k Vašim schránkám.</p>
<h3>Zpráva pro uživatele</h3>
<p>K odesílaným informacím o uživatelském účtu můžete připojit textovou zprávu.</p>
