<h2>Sráva skupin</h2>
<p>Tato stránka slouží ke správě všech skupin v systému. <em>Každá kategorie je vázána oprávněním na skupinu, nikoliv na uživatele.</em></p>
<h3>Úpravy skupin</h3>
<p>Úpravy skupin se provadí pomocí tlačítek v zápatí tabulky (plus, upravit, koš).</p>
<h3>Administrační skupina</h3>
<p>Administrační skupina označuje skupinu, která má vždy všechna práva ke všem stránkám a může upravovat strukturu srtánek, nastavovat jednotlivé stránku nebo jejich parametry.</p>
<h3>Omezení na domény</h3>
<p>U více doménových stránek se pomocí této volby nastavují domény, pro které je daná skupina určena.</p>
