<?
$this->addCssFile("style.css");
// do titulku
$h = $this->tr('Úprava pořadí prvků');
$this->addPageTitle($h);

$jQuery = new JsPlugin_JQuery();
$jQuery->addUISortable();

$this->addJsPlugin($jQuery);

echo $this->toolbox;?>
<h1><?=$h?></h1>
<div class="main-content-form-edit" id="items-editlist-form">
   <ul id="title-page-items">
      <?  foreach ($this->list as $item) {
         switch ($item['type']) {
                  case TitlePage_Controller::ITEM_TYPE_TEXT:
                     $tpl = 'item-text.phtml';
                     break;
                  case TitlePage_Controller::ITEM_TYPE_MENU:
                     $tpl = 'item-menu.phtml';
                     break;
                  case TitlePage_Controller::ITEM_TYPE_VIDEO:
                     $tpl = 'item-video.phtml';
                     break;
                  case TitlePage_Controller::ITEM_TYPE_ARTICLE:
                  case TitlePage_Controller::ITEM_TYPE_NEWS:
                  case TitlePage_Controller::ITEM_TYPE_ARTICLEWGAL:
                     $tpl = 'item-article.phtml';
                     break;
                  case TitlePage_Controller::ITEM_TYPE_ACTION:
                  case TitlePage_Controller::ITEM_TYPE_ACTIONWGAL:
                     $tpl = 'item-action.phtml';
                     break;
                  default:
                     break;
               }
         
         ?>
      <li id="item_<?=$item['id']?>" class="ui-widget columns-<?=$item['cols']?> item-type-<?=$item['type']?>">
         <div class="ui-widget-header title-bar">
            <div class="title-bar-right">
               <form method="post" name="form-delete-item" action="<?=$this->link()?>">
                  <input type="submit" class="ui-icon ui-icon-close" name="delete" value="" />
                  <input type="hidden" name="delete_id" value="<?=$item['id']?>" />
               </form>
               <a href="<?=$this->link()->route('editItem',array('id' => $item['id']));?>" title="<?=$this->tr('Upravit');?>" class="ui-icon ui-icon-pencil"></a>
            </div>
            <div class="title-bar-left">
               <?
               if($item['name'] != null){
                  echo $item['name'];
               } else {
                  echo '<em>'.$this->tr('Bez názvu').'</em>';
               }
               ?>
            </div>
            <hr class="reseter" />
         </div>
         <div class="ui-widget-content item-content">
            <?
            if((string)$item['nameCat'] != null){
               echo $this->tr('Kategorie').':&nbsp;'.'<a href="'.$item['linkCat'].'" title="'.$item['nameCat'].'">'.$item['nameCat'].'</a>';
            } else {
               echo $this->tr('Kategorie').':&nbsp;'.$this->category()->getName();
            }
            $this->item = $item;
            $this->includeTpl($tpl);
            ?>
         </div>
      </li>
      <?}?>
   </ul>
   <hr class="reseter" />
   <script type="text/javascript">
      $(function() {
         $("#title-page-items").sortable({
            handle: 'div.ui-widget-header',
            placeholder: 'ui-state-highlight',
            opacity: 0.6 ,
            start : function(event, ui){
               $("li.ui-state-highlight", this).height(ui.item.height());
               $("li.ui-state-highlight", this).width(ui.item.width());
            },
            update : function () {
               $.ajax({
                  type: "POST", url: "<?=$this->link()->route('changePosition')?>",
                  data: $('#title-page-items').sortable('serialize').toString()
               });
            }, 
            stop : function(event, ui){}
         });

         $('form[name=form-delete-item]').submit(function(){
            if(confirm('<?=$this->tr('Opravdu smazat?');?>') != true) return false
            var $form = $(this);
            var $li = $(this).parents('li');
            $.ajax({
               type: "POST", url: "<?=$this->link()->route('deleteItem')?>",
               data: $form.serialize(),
               success : function(data){
                  $li.animate({opacity:0}, 300, function(){
                     $(this).remove();
                  });
                  vveShowMessages(data);
               }
            });
            return false;
         });

      });
   </script>
</div>
