<h1><?=$this->_('Úprava položky se článkem')?></h1>
<?
$jQuery = new JsPlugin_JQuery();
$this->addJsPlugin($jQuery);

echo $this->form;
?>
<script type="text/javascript">
   $(document).ready(function(){
      $('select#article_item_category_id').change(function(){
         var idc = $(this).val();
         $.ajax({
            type: "POST", url: "<?=$this->link()->route('getList')?>",
               data: ({idc : idc, type : '<?=TitlePage_Controller::ITEM_TYPE_ARTICLE?>'}),
               success : function(msg){
                  $('select#article_item_article_id').html(null);
                  $.each(msg.list, function(key, value){
                     var opt = $('<option></option>').text(value.text).val(value.id);
                     $('select#article_item_article_id').append(opt);
                  });
               }
            });
      });
   });
</script>
<?$this->includeTpl("buttonback.phtml", true, array('link' => $this->link()->route('editList')));?>
