<h1><?php echo $this->tr('Úprava položky s akcí')?></h1>
<?php 
$jQuery = new JsPlugin_JQuery();
$this->addJsPlugin($jQuery);

echo $this->form;
?>
<script type="text/javascript">
   $(document).ready(function(){
      $('select[name=article_item_category_id]').change(function(){
         var idc = $(this).val();
         $.ajax({
            type: "POST", url: "<?php echo $this->link()->route('getList')?>",
               data: ({idc : idc, type : '<?php echo TitlePage_Controller::ITEM_TYPE_ACTION?>'}),
               success : function(msg){
                  $('select[name=article_item_article_id]').html(null);
                  $.each(msg.list, function(key, value){
                     var opt = $('<option></option>').text(value.text).val(value.id);
                     $('select[name=article_item_article_id]').append(opt);
                  });
               }
            });
      });
   });
</script>
