<?
$this->addCssFile("style.css");
// do titulku
$this->addPageTitle($this->_('Úprava pořadí prvků'));
$this->addPageHeadline($this->_('Úprava pořadí prvků'));

$jQuery = new JsPlugin_JQuery();
$jQuery->addUISortable();

$this->addJsPlugin($jQuery);

?>

<div id="items-editlist-form">
      <br />
      <br />
   <ul id="title-page-items">
      <?  foreach ($this->list as $item) {
         switch ($item['type']) {
                  case TitlePage_Controller::ITEM_TYPE_TEXT:
                     $tpl = 'item-text.phtml';
                     break;
                  case TitlePage_Controller::ITEM_TYPE_MENU:
                     $tpl = 'item-menu.phtml';
                     break;
                  case TitlePage_Controller::ITEM_TYPE_VIDEO:
                     $tpl = 'item-video.phtml';
                     break;
                  case TitlePage_Controller::ITEM_TYPE_ARTICLE:
                  case TitlePage_Controller::ITEM_TYPE_NEWS:
                  case TitlePage_Controller::ITEM_TYPE_ARTICLEWGAL:
                     $tpl = 'item-article.phtml';
                     break;
                  case TitlePage_Controller::ITEM_TYPE_ACTION:
                     $tpl = 'item-action.phtml';
                     break;
                  default:
                     break;
               }
         
         ?>
      <li id="item_<?=$item['id']?>" class="ui-widget columns-<?=$item['cols']?>">
         <div class="ui-widget-header title-bar">
            <div class="title-bar-right">
               <form method="post" name="form-delete-item" action="<?=$this->link()?>">
                  <input type="submit" class="ui-icon ui-icon-close" name="delete" value="" />
                  <input type="hidden" name="delete_id" value="<?=$item['id']?>" />
               </form>
               <a href="<?=$this->link()->route('editItem',array('id' => $item['id']));?>" title="<?=$this->_('Upravit');?>" class="ui-icon ui-icon-pencil"></a>
            </div>
            <div class="title-bar-left">
               <?
               if($item['name'] != null){
                  echo $item['name'];
               } else {
                  echo '<em>'.$this->_('Bez názvu').'</em>';
               }
               ?>
            </div>
            <hr class="reseter" />
         </div>
         <div class="ui-widget-content item-content">
            <?
            $this->item = $item;
            $this->includeTpl($tpl);
            ?>
         </div>
      </li>
      <?}?>
   </ul>
   <hr class="reseter" />
   <?echo $this->toolbox;?>
   <?$this->includeTpl("buttonback.phtml", true, array('link' => $this->link()->clear()));?>
   <script type="text/javascript">
      $(function() {
         $("#title-page-items").sortable({
            handle: 'div.ui-widget-header',
            placeholder: 'ui-state-highlight',
            start : function(event, ui){
               $("li.ui-state-highlight", this).height(ui.item.height());
               $("li.ui-state-highlight", this).width(ui.item.width());
            },
            update : function () {
               $.ajax({
                  type: "POST", url: "<?=$this->link()->route('changePosition')?>",
                  data: $('#title-page-items').sortable('serialize').toString()
               });
            }
         });

         $('form[name=form-delete-item]').submit(function(){
            if(confirm('<?=$this->_('Opravdu smazat?');?>') != true) return false
            var $form = $(this);
            var $li = $(this).parents('li');
            $.ajax({
               type: "POST", url: "<?=$this->link()->route('deleteItem')?>",
               data: $form.serialize(),
               success : function(){
                  $li.animate({opacity:0}, 300, function(){
                     $(this).remove();
                  });
               }
            });
            return false;
         });

      });
   </script>
</div>
