<?php 
if($this->item['name'] != null){?>
<h2><a href="<?php echo $this->item['link']?>" title="<?php echo $this->tr('Přejít na').' '.$this->item['name']?>"><?php echo $this->item['name'];?></a></h2>
<?php } else {?>
<h2><a href="<?php echo $this->item['link']?>" title="<?php echo $this->tr('Přejít na').' '.$this->item['title']?>"><?php echo vve_tpl_truncate($this->item['title'], 70);?></a></h2>
<?php }
if($this->item['image'] != null){?>
<img src="<?php echo $this->item['image']?>" alt="<?php echo $this->item['imageAlt']?>"/>
<?php }
echo $this->item['data'];
?>