<? // načtení detailu
$this->addCssFile("style.css");
echo $this->toolbox;
?>
<h1><?=$this->tr('Titulní strana');?></h1>
<div class="main-content-detail" id="items-list">
   <ul id="title-page-items">
      <?  foreach ($this->list as $item) {
         switch ($item['type']) {
                  case TitlePage_Controller::ITEM_TYPE_TEXT:
                     $tpl = 'item-text.phtml';
                     break;
                  case TitlePage_Controller::ITEM_TYPE_MENU:
                     $tpl = 'item-menu.phtml';
                     break;
                  case TitlePage_Controller::ITEM_TYPE_VIDEO:
                     $tpl = 'item-video.phtml';
                     break;
                  case TitlePage_Controller::ITEM_TYPE_ARTICLE:
                  case TitlePage_Controller::ITEM_TYPE_ARTICLEWGAL:
                  case TitlePage_Controller::ITEM_TYPE_NEWS:
                     $tpl = 'item-article.phtml';
                     break;
                  case TitlePage_Controller::ITEM_TYPE_ACTION:
                  case TitlePage_Controller::ITEM_TYPE_ACTIONWGAL:
                     $tpl = 'item-action.phtml';
                     break;
                  default:
                     break;
               }
         ?>
      <li id="item_<?=$item['id']?>" class="item columns-<?=$item['cols']?>">
         <div class="item-content">
            <?
            $this->item = $item;
            $this->includeTpl($tpl);
            ?>
         </div>
      </li>
      <?}?>
   </ul>
   <hr class="reseter" />
</div>

