<?
$this->addFile('css://style.less');
$this->addFile('js://cart.js');
$jQuery = new JsPlugin_JQuery();
$jQuery->addUISpinner();
$datepicker = false;
if(isset ($this->formNext->pickupDate)){
   $datepicker = true;
   $jQuery->addUIDatepicker();
}
$this->addJsPlugin($jQuery);
$this->step = 1;
?>
<h1><?=$this->category()->getName();?></h1>
<?if(!$this->cart->isEmpty()){
   $this->includeFile('tpl://navigation.phtml');
}
?>
<script type="text/javascript">
   $(document).ready(function(){
      <?if(!$this->cart->isEmpty()){?>
      Cart.init({
         shippings : <?=json_encode($this->shippings)?>,
         freeShipAndPayFrom : <?=(int)$this->freeShipAndPayFrom?>,
         payments : <?=json_encode($this->payments)?>,
         disallowPayments : <?=json_encode($this->disallowPayments)?>,
         priceCart : <?=str_replace(',', '.',$this->cart->getPrice())?>,
         priceShipping : <?=$this->shippingPrice?>,
         pricePayment : <?=$this->paymentPrice?>,
         updateUrl : '<?=$this->link()->route('cartUpdate')?>',
         currency : '<?=VVE_SHOP_CURRENCY_NAME?>',
         datepicker : <?echo $datepicker ? "true" : "false";?>,
         roundDecimals : <?=(int)VVE_SHOP_PRICE_ROUND_DECIMAL?>,
         decimals : <?=(int)VVE_SHOP_PRICE_DECIMALS?>,
         msg : {
            free : '<?=$this->tr('Zdarma')?>',
            deleteItem : '<?=$this->tr('Smazat tuto položku?')?>'
         }
      });
      <?}?>
   });
</script>

<div class="main-content-list" id="shop-cart">
   <?if(!$this->cart->isEmpty()){?>
   <h2><?=$this->tr('Obsah košíku');?></h2>
   <?
   $this->formItems->html()->setAttrib('id', 'form-items-qty');
   echo $this->formItems->renderStart();
   ?>
   <table class="full-width" id="table-cart-items">
      <thead>
         <tr>
            <th class="column-1"><?=$this->tr('Název')?></th>
            <th class="column-2"><?=$this->tr('Cena/ks')?></th>
            <th class="column-3"><?=$this->tr('Počet')?></th>
            <th class="column-4"><?=$this->tr('Cena')?></th>
            <th class="column-5"></th>
         </tr>
      </thead>
      <tbody>
      <?foreach ($this->cart as $item) {
         $this->formItems->qty->setMultiple($item->getId());
         $this->formItems->qty->html()->addClass('shop-cart-qty');
         $this->formItems->qty->setValues($item->getQty());
         ?>
         <tr id="cart-item-<?=$item->getId()?>" class="cart-item">
            <td class="column-1 product-name">
               <a href="<?=$item->getUrl()?>" title="<?=$item->getName()?>"><?=$item->getName()?></a>
               <?if($item->getNote() != null){
                  echo '<p class="font-small">';
                  ps($item->getNote());
                  echo '</p>';
               }?>
               <?if ($item->getCode() != null){?>
               <p><? ps($item->getCode())?></p>
               <?}?>
            </td>
            <td class="product-price-by-piece no-wrap"><?
               echo Shop_Tools::getFormatedPrice($item->getPrice(false));
               echo ' / '.$item->getUnitSize().' '.$item->getUnit();
               ?>
               <input class="unit-size" type="hidden" value="<?=$item->getUnitSize()?>" />
               <?if($item->getProductQty() >= 0 ){ // @todo kontrola jestli je pro zboží povolen sklad (z produktu)  ?>
               <input class="max-qty" type="hidden" value="<?=$item->getProductQty()?>" />
               <?}?>
            </td>
            <td><?
               echo $this->formItems->qty->controll().' '.$item->getUnit();
            ?></td>
            <td class="column-4 column-price">
               <span class="price product-price"><?=Shop_Tools::getFormatedPrice($item->getPrice())?></span>
               <input class="product-price-input" type="hidden" value="<?=str_replace(",", '.', $item->getPrice())?>" />
            </td>
            <td class="column-5">
               <a class="button-delete-item" href="<?=$this->link()->param('dp', $item->getId())?>" title="<?=$this->tr('Odtsranit z košíku')?>">
                  <img src="/images/icons/delete.png" alt="del" />
               </a>
            </td>
         </tr>
      <?}?>
      </tbody>
      <tfoot>
         <tr>
            <td><? echo $this->formItems->set->controll();?></td>
            <td colspan="2" class="price column-price"><?=$this->tr('Cena za zboží:')?></strong></td>
            <td colspan="" class="price column-price products-price">
               <?=Shop_Tools::getFormatedPrice($this->cart->getPrice())?> </strong>
            </td>
            <td></td>
         </tr>
      </tfoot>
   </table>
   <?echo $this->formItems->renderEnd();?>
   <?if(VVE_DEBUG_LEVEL > 1){?>
   <div style="float: right;">
      <?
      echo $this->formReset->renderStart();
      echo $this->formReset->reset->controll();
      echo $this->formReset->renderEnd();
      ?>
   </div>
   <?}?>
   
   <h2><?=$this->tr('Doprava a platba');?></h2>
   <?echo $this->formNext->renderStart();?>
   <table class="full-width">
      <tbody>
         <tr>
            <td><? echo $this->formNext->shipping->label();?></td>
            <td><? 
            echo $this->formNext->shipping->controll();
            if(isset ($this->formNext->pickupDate)){
               echo $this->formNext->pickupDate->label();
               echo $this->formNext->pickupDate->controll();
            }
            ?></td>
            <td class="column-4 column-price" >
               <span id="shipping-price"><?echo $this->shippingPrice > 0 ? Shop_Tools::getFormatedPrice($this->shippingPrice) : $this->tr('Zdarma')?></span>
            </td>
         </tr>
         <tr>
            <td><? echo $this->formNext->payment->label();?></td>
            <td><? echo $this->formNext->payment->controll();?></td>
            <td class="column-4 column-price" >
               <span id="payment-price"><?echo $this->paymentPrice > 0 ? Shop_Tools::getFormatedPrice($this->paymentPrice) : $this->tr('Zdarma')?></span>
            </td>
         </tr>
         <tr>
            <th><? echo $this->tr('Cena celkem');?></th>
            <td></td>
            <td class="price column-price">
               <span id="full-price">
                  <? echo Shop_Tools::getFormatedPrice($this->cart->getPrice()+$this->shippingPrice+$this->paymentPrice);?>
               </span>
            </td>
         </tr>
         <tr>
            <td colspan="3" class="align-right"><? echo $this->formNext->send->controll();?></td>
         </tr>
      </tbody>
   </table>
   <?echo $this->formNext->renderEnd();?>
   <?} else {?>
   <div class="text"><p><?=$this->tr('Košík neobsahuje žádnou položku.')?></p></div>
   <?}?>
</div>

