<?php 
$step = $this->step == null ? 1 : $this->step;
$steps = array(
   1 => $this->tr('Krok 1. Košík'),
   2 => $this->tr('Krok 2. Kontakt a potvrzení'),
   3 => $this->tr('Krok 3. Dokončení'),
);
?>
<div>
   <div class="row shop-step-list">
   <?php foreach ($steps as $stepNum => $s) {?>
      <div class="<?php if($stepNum == $step){ echo 'selected';} ?> col-sm-4"><?php echo $s?></div>
   <?php }?>
   </div>
</div>
           