<?php 
$this->addFile('css://style.css');
$h = $this->tr('Potvrzení objednávky');
Template_Core::addPageTitle($h);
$this->addJsPlugin(new JsPlugin_JQuery());
$this->step = 3;
?>
<h1><?php echo $h?></h1>
<?php $this->includeFile('tpl://navigation.phtml')?>
<div class="main-content-detail">
   <h2><?php echo $this->tr('Souhrn položek');?></h2>
   <table class="full-width">
      <thead>
         <tr>
            <th><?php echo $this->tr('Název')?></th>
            <th><?php echo $this->tr('Cena za položku')?></th>
            <th><?php echo $this->tr('Počet')?></th>
            <th><?php echo $this->tr('Cena celkem')?></th>
         </tr>
      </thead>
      <tbody>
      <?php foreach ($this->basket as $item){?>
         <tr>
            <td><a href="<?php echo $item->getUrl()?>" title="<?php echo $item->getName()?>"><?php echo $item->getName()?></a></td>
            <td><?php 
               echo $item->getPrice(false).' '.VVE_SHOP_CURRENCY_NAME;
               echo ' / '.$item->getUnitSize().' '.$item->getUnit();
               ?>
            </td>
            <td><?php  echo $item->getQty().' '.$item->getUnit(); ?></td>
            <td><?php echo $item->getPrice().' '.VVE_SHOP_CURRENCY_NAME?></td>
         </tr>
      <?php }?>
         <tr><td colspan="4" class="spacer">&nbsp;</td></tr>
         <tr>
            <td colspan="2"><?php echo $this->tr('Doprava')?></td>
            <td><?php ?></td>
            <td><?php 
            if($this->shipping == 0){
               echo '0 '.VVE_SHOP_CURRENCY_NAME.' ('.$this->tr('zdarma').')';
            }
            ?></td>
         </tr>
         <tr>
            <td colspan="2"><?php echo $this->tr('Platba')?></td>
            <td><?php ?></td>
            <td><?php 
            if($this->payment == 0){
               echo '0 '.VVE_SHOP_CURRENCY_NAME.' ('.$this->tr('zdarma').')';
            }
            ?></td>
         </tr>
         <tr><td colspan="4" class="spacer">&nbsp;</td></tr>
         <tr class="basket-full-price">
            <td colspan="3"><?php echo $this->tr('Cena celkem')?></td>
            <td><?php echo $this->basket->getPrice().' '.VVE_SHOP_CURRENCY_NAME?></td>
         </tr>
      </tbody>
   </table>
   <script type="text/javascript">
   </script>
</div>