<?php
$this->addFile('css://style.less');
$h = $this->tr('Platební a poštovní informace');
Template_Core::addPageTitle($h);
$this->addJsPlugin(new JsPlugin_JQuery());
$this->step = 2;
$this->stepAllowBack = true;


$classLabels = 'col-sm-3';
$classControls = 'col-sm-9';
?>
<h1><?php echo $h ?></h1>
<?php $this->includeFile('tpl://navigation.phtml') ?>
<div class="main-content-detail">
   <?php if ($this->formLogin) { ?>
      <div id="order-login-form">
         <h2><?php ps($this->tr('Přihlášení')) ?></h2>
         <?php
//         $this->formLogin->html()->addClass('form-horizontal');
         echo $this->formLogin->renderStart();
         ?>
         <div class="form-group">
            <?php
            $this->formLogin->{Auth_Provider_Internal::FORM_USERNAME}->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formLogin->{Auth_Provider_Internal::FORM_USERNAME}->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formLogin->{Auth_Provider_Internal::FORM_USERNAME}->html()->addClass('form-control');
               echo $this->formLogin->{Auth_Provider_Internal::FORM_USERNAME}->ControlAll();
               ?>
            </div>
         </div>
         <div class="form-group">
            <?php
            $this->formLogin->{Auth_Provider_Internal::FORM_PASSWORD}->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formLogin->{Auth_Provider_Internal::FORM_PASSWORD}->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formLogin->{Auth_Provider_Internal::FORM_PASSWORD}->html()->addClass('form-control');
               echo $this->formLogin->{Auth_Provider_Internal::FORM_PASSWORD}->ControlAll();
               ?>
            </div>
         </div>
         <div class="form-group">
            <div class="<?php echo $classControls ?>"></div>
            <div class="<?php echo $classLabels ?>">
               <?php
               $this->formLogin->{Auth_Provider_Internal::FORM_SUBMIT}->setSufixIcon('sign-in');
               $this->formLogin->{Auth_Provider_Internal::FORM_SUBMIT}->html()->addClass('form-control')->addClass('btn btn-success');
               echo $this->formLogin->{Auth_Provider_Internal::FORM_SUBMIT}->ControlAll();
               ?>
            </div>
         </div>
         <?php
         echo $this->formLogin->renderEnd();
         ?>
         <?php
//      var_dump($this->formLogin);
         ?>
      </div>
   <?php } ?>
   <div id="order-confirm-form">
      <h2><?php ps($this->tr('Objednávka')) ?></h2>
      <?php
      // echo $this->formItems->renderStart();
//      $this->formOrder->html()->addClass('form-horizontal');
      echo $this->formOrder->renderStart();
      ?>
      <fieldset class="fieldset-alt">
         <legend><span class="form-legend-name"><?php echo $this->tr('Informace o zákazníkovi') ?></span></legend>

         <div class="form-group">
            <?php
            $this->formOrder->customerName->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->customerName->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->customerName->html()->addClass('form-control');
               echo $this->formOrder->customerName->ControlAll();
               ?>
                <!--<input type="name" class="form-control" placeholder="">-->
            </div>
         </div>
         <div class="form-group">
            <?php
            $this->formOrder->customerSurname->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->customerSurname->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->customerSurname->html()->addClass('form-control');
               echo $this->formOrder->customerSurname->ControlAll();
               ?>        
            </div>
         </div>
         <div class="form-group">
            <?php
            $this->formOrder->customerEmail->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->customerEmail->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->customerEmail->html()->addClass('form-control');
               echo $this->formOrder->customerEmail->ControlAll();
               ?>       
            </div>
         </div>
         <div class="form-group">
            <?php
            $this->formOrder->customerPhone->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->customerPhone->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->customerPhone->html()->addClass('form-control');
               echo $this->formOrder->customerPhone->ControlAll();
               ?>         
            </div>
         </div>
         <?php if (isset($this->formOrder->createAcc)) { ?>
            <div class="form-group">
               <div class="<?php echo $classLabels ?>"></div>
               <div class="<?php echo $classControls ?>">
                  <div class="checkbox">
                     <?php
                     echo $this->formOrder->createAcc->Control();
                     echo $this->formOrder->createAcc->label(true);
                     ?>         
                  </div>
               </div>
            </div>
            <div class="form-group create-account-form-group">
               <?php
               $this->formOrder->createAccPassword->htmlLabel()->addClass($classLabels . ' control-label');
               echo $this->formOrder->createAccPassword->label();
               ?>
               <div class="<?php echo $classControls ?>">
                  <?php
                  $this->formOrder->createAccPassword->html()->addClass('form-control');
                  echo $this->formOrder->createAccPassword->ControlAll();
                  ?>         
               </div>
            </div>
            <div class="form-group create-account-form-group">
               <?php
               $this->formOrder->createAccPasswordC->htmlLabel()->addClass($classLabels . ' control-label');
               echo $this->formOrder->createAccPasswordC->label();
               ?>
               <div class="<?php echo $classControls ?>">
                  <?php
                  $this->formOrder->createAccPasswordC->html()->addClass('form-control');
                  echo $this->formOrder->createAccPasswordC->ControlAll();
                  ?>         
               </div>
            </div>

         <?php } ?>
         <?php if (isset($this->formOrder->newsletter)) { ?>
            <div class="form-group">
               <div class="<?php echo $classLabels ?>"></div>
               <div class="<?php echo $classControls ?>">
                  <div class="checkbox">
                     <?php
                     echo $this->formOrder->newsletter->Control();
                     echo $this->formOrder->newsletter->label(true);
                     ?>         
                  </div>
               </div>
            </div>
         <?php } ?>
      </fieldset>
      <fieldset class="fieldset-alt">
         <legend><span class="form-legend-name"><?php echo $this->tr('Fakturační adresa') ?></span></legend>

         <div class="form-group">
            <?php
            $this->formOrder->paymentStreet->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->paymentStreet->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->paymentStreet->html()->addClass('form-control');
               echo $this->formOrder->paymentStreet->ControlAll();
               ?>         
            </div>
         </div>
         <div class="form-group">
            <?php
            $this->formOrder->paymentCity->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->paymentCity->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->paymentCity->html()->addClass('form-control');
               echo $this->formOrder->paymentCity->ControlAll();
               ?>         
            </div>
         </div>
         <div class="form-group">
            <?php
            $this->formOrder->paymentPostCode->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->paymentPostCode->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->paymentPostCode->html()->addClass('form-control');
               echo $this->formOrder->paymentPostCode->ControlAll();
               ?>         
            </div>
         </div>
         <div class="form-group">
            <?php
            $this->formOrder->paymentCountry->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->paymentCountry->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->paymentCountry->html()->addClass('form-control');
               echo $this->formOrder->paymentCountry->ControlAll();
               ?>         
            </div>
         </div>
         <div class="form-group">
            <?php
            $this->formOrder->paymentCompanyName->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->paymentCompanyName->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->paymentCompanyName->html()->addClass('form-control');
               echo $this->formOrder->paymentCompanyName->ControlAll();
               ?>         
            </div>
         </div>
         <div class="form-group">
            <?php
            $this->formOrder->paymentCompanyIC->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->paymentCompanyIC->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->paymentCompanyIC->html()->addClass('form-control');
               echo $this->formOrder->paymentCompanyIC->ControlAll();
               ?>         
            </div>
         </div>
         <div class="form-group">
            <?php
            $this->formOrder->paymentCompanyDIC->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->paymentCompanyDIC->label();
            ?>
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->paymentCompanyDIC->html()->addClass('form-control');
               echo $this->formOrder->paymentCompanyDIC->ControlAll();
               ?>         
            </div>
         </div>
      </fieldset>
      <fieldset class="fieldset-alt">
         <legend><span class="form-legend-name"><?php echo $this->tr('Dodací adresa') ?></span></legend>

         <div class="form-group">
            <?php
            $this->formOrder->isDeliveryAddress->htmlLabel()->addClass($classLabels . ' control-label form-labels');
            echo $this->formOrder->isDeliveryAddress->label();
            ?>            
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->isDeliveryAddress->html()->addClass('form-controlls');
               echo $this->formOrder->isDeliveryAddress->ControlAll();
               ?>         
            </div>
         </div>
         <div class="form-group delivery-form-group">
            <?php
            $this->formOrder->deliveryName->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->deliveryName->label();
            ?>            
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->deliveryName->html()->addClass('form-control');
               echo $this->formOrder->deliveryName->ControlAll();
               ?>         
            </div>
         </div>
         <div class="form-group delivery-form-group">
            <?php
            $this->formOrder->deliveryStreet->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->deliveryStreet->label();
            ?>             
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->deliveryStreet->html()->addClass('form-control');
               echo $this->formOrder->deliveryStreet->ControlAll();
               ?>         
            </div>
         </div>
         <div class="form-group delivery-form-group">
            <?php
            $this->formOrder->deliveryCity->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->deliveryCity->label();
            ?>              
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->deliveryCity->html()->addClass('form-control');
               echo $this->formOrder->deliveryCity->ControlAll();
               ?>         
            </div>
         </div>
         <div class="form-group delivery-form-group">
            <?php
            $this->formOrder->deliveryPostCode->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->deliveryPostCode->label();
            ?>           
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->deliveryPostCode->html()->addClass('form-control');
               echo $this->formOrder->deliveryPostCode->ControlAll();
               ?>         
            </div>
         </div>
         <div class="form-group delivery-form-group">
            <?php
            $this->formOrder->deliveryCountry->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->deliveryCountry->label();
            ?>             
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->deliveryCountry->html()->addClass('form-control');
               echo $this->formOrder->deliveryCountry->ControlAll();
               ?>         
            </div>
         </div>
      </fieldset>
      <fieldset class="fieldset-alt not-hidden">
         <legend><span class="form-legend-name"><?php echo $this->tr('Rekapitulace objednávky') ?></span></legend>
         <div class="table-responsive">
            <table class="table table-striped">
               <thead>
                  <tr>
                     <th><?php echo $this->tr('Název') ?></th>
                     <th><?php echo $this->tr('Množství') ?></th>
                     <th><?php echo $this->tr('Cena') ?></th>
                  </tr>
               </thead>
               <tbody>
                  <?php foreach ($this->cart as $item) { ?>
                     <tr>
                        <td>
                           <a href="<?php echo $item->getUrl() ?>" title="<?php ps($item->getName()); ?>"><?php ps($item->getName()); ?></a>
                           <?php
                           if ($item->getNote() != null) {
                              echo "<br />";
                              ps($item->getNote());
                           }
                           ?>
                        </td>
                        <td class="column-unit">
                           <?php
                           ps($item->getQty() . " " . $item->getUnit());
                           ?>
                        </td>
                        <td class="column-price">
                           <?php
                           echo Shop_Tools::getFormatedPrice($item->getPrice(true));
                           ?>
                        </td>
                     </tr>
                  <?php } ?>
               </tbody>
               <tfoot>
                  <tr>
                     <td colspan="2">
                        <?php printf($this->tr('<strong>Doprava:</strong> %s'), $this->shipping->{Shop_Model_Shippings::COLUMN_NAME}) ?>
                        <?php
                        if ((string) $this->shipping->{Shop_Model_Shippings::COLUMN_TEXT} != null) {
                           ?>
                           <div class="shipping-note"><?php echo $this->shipping->{Shop_Model_Shippings::COLUMN_TEXT} ?></div>
                           <?php
                        }
                        ?>
                     </td>
                     <td class="column-price"><?php echo Shop_Tools::getFormatedPrice($this->shippingPrice) ?></td>
                  </tr>
                  <tr>
                     <td colspan="2">
                        <?php printf($this->tr('<strong>Platba:</strong> %s'), $this->payment->{Shop_Model_Payments::COLUMN_NAME}) ?>
                        <?php
                        if ((string) $this->payment->{Shop_Model_Payments::COLUMN_TEXT} != null) {
                           ?>
                           <div class="payment-note"><?php echo $this->payment->{Shop_Model_Payments::COLUMN_TEXT} ?></div>
                           <?php
                        }
                        ?>
                     </td>
                     <td class="column-price"><?php echo Shop_Tools::getFormatedPrice($this->paymentPrice) ?></td>
                  </tr>
                  <tr>
                     <th colspan="2">
                        <?php echo $this->tr('Cena celkem:') ?>
                     </th>
                     <th class="column-price">
                        <span class="price price-total">
                           <?php echo Shop_Tools::getFormatedPrice($this->priceTotal) ?>
                        </span>
                     </th>
                  </tr>
               </tfoot>
            </table>
         </div>
      </fieldset>

      <fieldset class="fieldset-alt">
         <legend><span class="form-legend-name"><?php echo $this->tr('Odeslání objednávky') ?></span></legend>

         <div class="form-group">
            <?php
            $this->formOrder->note->htmlLabel()->addClass($classLabels . ' control-label');
            echo $this->formOrder->note->label();
            ?>             
            <div class="<?php echo $classControls ?>">
               <?php
               $this->formOrder->note->html()->addClass('form-control');
               echo $this->formOrder->note->ControlAll();
               ?>         
            </div>
         </div>
         <?php if (isset($this->formOrder->terms)) { ?>
            <div class="form-group">
               <div class="<?php echo $classLabels ?>"></div>
               <div class="<?php echo $classControls ?>">
                  <div class="checkbox">
                     <?php
                     echo $this->formOrder->terms->Control();
                     echo $this->formOrder->terms->label(true);
                     ?>         
                  </div>
               </div>
            </div>
         <?php } ?>
      </fieldset>
      <div class="row">
         <div class="col-sm-12">
            <div class="pull-left">
               <?php
               $this->formOrder->back->setPrefixIcon('chevron-left');
               $this->formOrder->back->html()->addClass('form-control')->addClass('btn btn-danger');
               echo $this->formOrder->back->ControlAll();
               ?> 
            </div>
            <div class="pull-right">
               <?php
               $this->formOrder->send->setSufixIcon('check');
               $this->formOrder->send->html()->addClass('form-control')->addClass('btn btn-success');
               echo $this->formOrder->send->ControlAll();
               ?>         
            </div>
         </div>
      </div>
      <?php
      echo $this->formOrder->renderEnd();
      ?>
   </div>
</div>
<script type="text/javascript">
   $(document).ready(function () {
      // skrytí dodací adresy
      toggleAddress($('input[name="order_isDeliveryAddress"]'));
      $('input[name="order_isDeliveryAddress"]').change(function () {
         toggleAddress($(this));
      });

      togglePassword($('input[name="order_createAcc"]'));
      $('input[name="order_createAcc"]').change(function () {
         togglePassword($(this));
      });

   });
   function toggleAddress($this) {
      var items = $('.delivery-form-group');
      if ($this.is(':checked')) {
         items.show();
      } else {
         items.hide();
      }
   }
   function togglePassword($this) {
      var items = $('.create-account-form-group');
      if ($this.is(':checked')) {
         items.show();
      } else {
         items.hide();
      }
   }
</script>
</div>