<?
if(VVE_DEBUG_LEVEL > 1) {
   $this->addFile('css://debug.less');
   ?>
   <div id="debug">
      <div>
         <table>
            <caption><?ps($this->tr('Infomrace o jádře'))?></caption>
            <tr class="row">
               <td colspan="4">CORE</td>
            </tr>
            <tr>
               <th><?ps('Úroveň DEBUG režimu:')?></th>
               <td><?ps(VVE_DEBUG_LEVEL)?></td>
               <th><?ps('IP:')?></th>
               <td><?ps($_SERVER['REMOTE_ADDR']." (".$_SERVER['REMOTE_HOST'].")")?></td>
            </tr>
            <tr>
               <th><?ps('Exec time jádra:')?></th>
               <td><?ps($this->execTime)?></td>
               <th><?ps('SQL dotazů:')?></th>
               <td><?ps(Db_PDO::getCountQueries())?></td>
            </tr>
            <tr>
               <th><?ps('Aktuální uživatel:')?></th>
               <td><?ps(Auth::getUserName()." - ID:".Auth::getUserId())?></td>
               <th><?ps('Verze jádra:')?></th>
               <td><?ps(AppCore::ENGINE_VERSION.'.'.AppCore::ENGINE_RELEASE)?></td>
            </tr>
            <tr>
               <th><?ps('Název webu (VVE_WEB_NAME):')?></th>
               <td><span title="<?ps(VVE_WEB_NAME)?>"><?ps(vve_tpl_truncate(VVE_WEB_NAME, 30))?></span></td>
               <th><?ps('Název vzhledu (face):')?></th>
               <td><?ps(Face::getCurrent()->getName())?></td>
            </tr>
            <tr>
               <th><?ps('Modul:')?></th>
               <td><?ps(Category::getSelectedCategory()->getModule()->getName())?></td>
               <th><?ps('Akce:')?></th>
               <td><?ps($this->moduleAction)?></td>
            </tr>
            <?if(function_exists('xdebug_get_function_count')){?>
            <tr class="row">
               <td colspan="4">XDEBUG</td>
            </tr>
            <tr>
               <th><?ps('Paměť:')?></th>
               <td><?ps(number_format(xdebug_memory_usage(), 0, '.', ' ').' B')?></td>

               <th><?ps('Spuštěno funkcí:')?></th>
               <td><?ps(number_format(xdebug_get_function_count(), 0, '.', ' '))?></td>
            </tr>
            <tr>
               <th><?ps('Paměť (špička):')?></th>
               <td><?ps(number_format(xdebug_peak_memory_usage(), 0, '.', ' ').' B')?></td>

               <th><?ps('Index time (s kompilací css/js):')?></th>
               <td><?ps(xdebug_time_index())?></td>
            </tr>
            <?}?>
         </table>
      </div>
   </div>
<?}
if(Category::getSelectedCategory()->getRights()->isWritable() || Template::pVar('showHelp') === true){
   $help = new Template_Help($this->moduleAction, Category::getSelectedCategory()->getModule());
   echo $help;
}
?>
<?if(defined('VVE_GOOGLE_ANALYTICS_CODE') && VVE_GOOGLE_ANALYTICS_CODE != null
   && !in_array($_SERVER['REMOTE_ADDR'], explode(',', VVE_ANALYTICS_DISABLED_HOSTS))){?>
<script type="text/javascript">
   /* <![CDATA[ */
   var _gaq = _gaq || [];
   _gaq.push(['_setAccount', '<?=VVE_GOOGLE_ANALYTICS_CODE?>']);
   _gaq.push(['_trackPageview']);

   (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
   })();
   /* ]]> */
</script>
<?}?>