<?php
if(VVE_DEBUG_LEVEL > 1 && !Template::browser()->isMobile() || isset($_GET['debug'])) {
   $this->addFile('css://debug.less');
   ?>
   <div id="debug">
      <div>
         <table>
            <caption><?php ps($this->tr('Infomrace o jádře'))?></caption>
            <tr class="section-name">
               <td colspan="4">CORE</td>
            </tr>
            <tr>
               <th><?php ps('Úroveň DEBUG režimu:')?></th>
               <td><?php ps(VVE_DEBUG_LEVEL)?></td>
               <th><?php ps('IP:')?></th>
               <td><?php ps($_SERVER['REMOTE_ADDR']. (isset($_SERVER['REMOTE_HOST']) ? " (".$_SERVER['REMOTE_HOST'].")" : null) )?></td>
            </tr>
            <tr>
               <th><?php ps('Exec time jádra:')?></th>
               <td><?php ps($this->execTime)?></td>
               <th><?php ps('SQL dotazů:')?></th>
               <td><?php ps(Db_PDO::getCountQueries())?></td>
            </tr>
            <tr>
               <th><?php ps('Aktuální uživatel:')?></th>
               <td><?php ps(Auth::getUserName()." - ID:".Auth::getUserId())?></td>
               <th><?php ps('Verze jádra:')?></th>
               <td><?php ps(AppCore::ENGINE_VERSION)?></td>
            </tr>
            <tr>
               <th><?php ps('Název webu (VVE_WEB_NAME):')?></th>
               <td><span title="<?php ps(VVE_WEB_NAME)?>"><?php ps(vve_tpl_truncate(VVE_WEB_NAME, 30))?></span></td>
               <th><?php ps('Název vzhledu (face):')?></th>
               <td><?php ps(Face::getCurrent()->getName())?></td>
            </tr>
            <tr>
               <th><?php ps('Modul:')?></th>
               <td><?php ps(Category::getSelectedCategory()->getModule()->getName())?></td>
               <th><?php ps('Akce:')?></th>
               <td><?php ps($this->moduleAction)?></td>
            </tr>
            <tr>
               <th><?php ps('Kategorie:')?></th>
               <td><?php ps(Category::getSelectedCategory()->getName())?></td>
               <th><?php ps('ID kategorie:')?></th>
               <td><?php ps(Category::getSelectedCategory()->getId())?></td>
            </tr>
            <?php if(function_exists('xdebug_get_function_count')){?>
            <tr class="section-name">
               <td colspan="4">XDEBUG</td>
            </tr>
            <tr>
               <th><?php ps('Paměť:')?></th>
               <td><?php ps(number_format(xdebug_memory_usage(), 0, '.', ' ').' B')?></td>

               <th><?php ps('Spuštěno funkcí:')?></th>
               <td><?php ps(number_format(xdebug_get_function_count(), 0, '.', ' '))?></td>
            </tr>
            <tr>
               <th><?php ps('Paměť (špička):')?></th>
               <td><?php ps(number_format(xdebug_peak_memory_usage(), 0, '.', ' ').' B')?></td>

               <th><?php ps('Index time (s kompilací css/js):')?></th>
               <td><?php ps(xdebug_time_index())?></td>
            </tr>
            <?php }?>
            <tr class="section-name">
               <td colspan="4">Optimalizace</td>
            </tr>
            <tr>
               <th><?php ps('Používá se cache:')?></th>
               <td><?php ps(Cache::isEnabled() ? $this->tr('Ano') : $this->tr('Ne'))?></td>

               <th><?php ps('Typ cache:')?></th>
               <td><?php ps(get_class(Cache::getProvider()))?></td>
            </tr>
         </table>
      </div>
   </div>
<?php }

if(Category::getSelectedCategory()->getRights()->isWritable() || Template::pVar('showHelp') === true){
   $help = new Template_Help($this->moduleAction, Category::getSelectedCategory()->getModule());
   echo $help;
}

if($this->disableFooterGA !== true && defined('VVE_GOOGLE_ANALYTICS_CODE') && VVE_GOOGLE_ANALYTICS_CODE != null
   && !in_array($_SERVER['REMOTE_ADDR'], explode(',', VVE_ANALYTICS_DISABLED_HOSTS))){?>
<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?php echo VVE_GOOGLE_ANALYTICS_CODE?>', 'auto');
  ga('send', 'pageview');
</script>
<?php
}