Statistiky
<?php 
$page = '';
$GACode = '48157697';
?>

<div class="ga-page-stats clearfix">
   
   
</div>
<script type="text/javascript">
   var query = "https://www.googleapis.com/analytics/v3/data/ga?ids=ga%<?php echo $GACode?>&metrics=ga%3Apageviews%2Cga%3AavgTimeOnPage%2Cga%3AexitRate%2Cga%3Avisits%2Cga%3Avisitors%2Cga%3AnewVisits&filters=ga%3ApagePath%3D%3D%2Froznov-live%2Fmesto-chce-pritlacit-na-media-ktera-o-nem-pisou-negativne-najalo-pravnika%2F&start-date=2013-08-01&end-date=2013-09-23&max-results=50";
</script>