<?php 
if (isset($this->form->titleImage) && Template::pVar('DIALOG_TITLE_IMAGE') != true) {
   Template::setPVar('DIALOG_TITLE_IMAGE', true);
   $jq = new JsPlugin_JQuery();
   $jq->addUIResizable();
   $jq->addUIDialog();
   $this->addJsPlugin($jq);
   $baseDir = $this->titleImagesURL != null ? $this->titleImagesURL : vve_tpl_art_title_image('');
   ?>
   <div id="dialog-title-image" title="<?php echo  $this->tr('Výběr titulního obrázku') ?>">
   <?php 
   foreach ($this->form->titleImage->getOptions() as $key => $image) {
      if ($image == null) {
         echo '<a href="' . $this->link() . '#" class="button-select-title-image" data-file="" >' . $key . '</a>';
      } else {
         $imgSrc = vve_image_cacher($baseDir.$image, 100, 100, false );
         echo '<a href="' . $this->link() . '#' . $image . '" class="button-select-title-image" data-file="' . $image . '" title="' . $image . '">'
         . '<img src="'.$imgSrc.'" alt="'.htmlspecialchars($imgSrc).'" /></a>';
      }
   }
   ?>
   </div>
   <script type="text/javascript">
   /* <![CDATA[ */
   $(document).ready(function(){
      CubeCMS.Form.addButton($('select[name$="titleImage"]'), {
         elementClass : 'button-open-title-image-galery',
         title : '<?php ps($this->tr('Vybrat z již uložených obrázků'))?>',
         icon : 'folder-open'
      });
      
      var $select = null;
      
      // zobraz galerii
      $('.button-open-title-image-galery').click(function(e){
         e.preventDefault();
         $select = $(this).prev('select');
         $('#dialog-title-image a').removeClass('selected');
         $('#dialog-title-image a[data-file="'+$select.val()+'"]').addClass('selected');
         
         $( "#dialog-title-image" ).dialog({width: 580, height: 365, resizable : true});          
      });
      // výběr z galerie
      $('.button-select-title-image').click(function(e){
         e.preventDefault();
         $select.val($(this).data('file'));
         $( "#dialog-title-image" ).dialog('close');
      });
   });
   /* ]]> */
</script>
   <?php  } ?>
