<? 
if (isset($this->form->titleImage) && Template::pVar('DIALOG_TITLE_IMAGE') != true) { 
   Template::setPVar('DIALOG_TITLE_IMAGE', true);
   $jq = new JsPlugin_JQuery();
   $jq->addUIResizable();
   $jq->addUIDialog();
   $this->addJsPlugin($jq);
   ?>
   <div id="dialog-title-image" title="<?= $this->tr('Výběr titulního obrázku') ?>">
   <?
   foreach ($this->form->titleImage->getOptions() as $key => $image) {
      if ($image == null) {
         echo '<a href="' . $this->link() . '#" class="button-select-title-image" data-file="" >' . $key . '</a>';
      } else {
         $imgSrc = vve_image_cacher(vve_tpl_art_title_image($image), 100, 100, false );
         echo '<a href="' . $this->link() . '#' . $image . '" class="button-select-title-image" data-file="' . $image . '" title="' . $image . '">'
         . '<img src="'.$imgSrc.'" alt="'.htmlspecialchars($imgSrc).'" /></a>';
      }
   }
   ?>
   </div>
   <script type="text/javascript">
   /* <![CDATA[ */
   $(document).ready(function(){
      $('select[name$="titleImage"]')
         .after('<a href="<?=$this->link()?>#select-title-image" class="button-open-title-image-galery" title="<?ps($this->tr('Vybrat z již uložených obrázků'))?>"><?=$this->tr('Vybrat z galerie')?></a>');
      var $select = null;
      
      // zobraz galerii
      $('.button-open-title-image-galery').click(function(e){
         e.preventDefault();
         $select = $(this).prev('select');
         $('#dialog-title-image a').removeClass('selected');
         $('#dialog-title-image a[data-file="'+$select.val()+'"]').addClass('selected');
         
         $( "#dialog-title-image" ).dialog({width: 560, height: 365, resizable : true});          
      });
      // výběr z galerie
      $('.button-select-title-image').click(function(e){
         e.preventDefault();
         $select.val($(this).data('file'));
         $( "#dialog-title-image" ).dialog('close');
      });
   });
   /* ]]> */
</script>
   <? } ?>
