<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <title>Instalace Cube-CMS krok <?php echo $step;?></title>
        <link rel="stylesheet" type="text/css" href="tpls/style.css" />
    </head>
    <body>
       <form action="<?php echo $currentLink?>" method="post">
       <div id="main-contect">
          <div id="main-header">
             <p id="header-install-step">krok <?php echo $step;?></p>
             <p>Instalace systému Cube-CMS</p>
          </div>
          <div id="main-page-content">
             <?php if($errMsg != null){?>
             <div id="error-message-box">CHYBA: <?php echo $errMsg?></div>
             <?php }?>
             <?php  include './tpls/'.$tplFile;?>
          </div>
          <div id="main-page-buttons">
             <input type="button" name="reload" value="Obnovit" onclick="window.location.href='<?php echo $currentLink;?>'" />
             <input type="submit" name="next" value="<?php echo $buttonNextTitle?>" />
          </div>
          <div id="main-footer">
             <p>
                Prosíme, čtěte pozorně všechny instrukce. Za případné chyby neručíme. Cube-Studio.cz
             </p>
          </div>
       </div>
       </form>
    </body>
</html>
