<table id="php-status">
<?php foreach ($infoItems as $item) {
   if($item['status'] != 'group'){?>
   <tr>
      <td class="check-item-name"><?php echo $item['name'];?></td>
      <td class="check-item-status"><?php 
      switch ($item['status']) {
         case 'err':
            echo '<span class="status-err">CHYBA</span>';
            break;
         case 'warn':
            echo '<span class="status-warn">Warování</span>';
            break;
         case 'ok':
         default:
            echo '<span class="status-ok">OK</span>';
            break;
      }?>
      </td>
   </tr>
   <?php 
   } else {?>
   <tr>
      <th colspan="2" class="check-item-groupname"><?php echo $item['name'];?></th>
   </tr>
   <?php }?>

   <?php if($item['info'] != null){?>
   <tr>
      <td class="check-item-info" colspan="2"><?php echo $item['info'];?></td>
   </tr>
   <?php }?>
<?php }?>
</table>


