<?
//var_dump($phpMSGS);
?>
<h1>Instalace databáze</h1>
<h2>Nastavení konfigurace</h2>
<p>Upravte soubor <i><?echo CMS_DIR.'config'.DIRECTORY_SEPARATOR.'config.php';?></i> s nastavením připojení k db.</p>
<br />
<h2>Spuštění SQL dotazů</h2>
<p>
   Pro kontrolu přístupu zadejte heslo k databázi.<br />
   <label>Heslo:&nbsp;</label><input type="text" name="db_pass" value="" />
</p>
<br />
<h2>E-shop rozšíření</h2>
<label for="shop_install_check">Instalovat e-shop rozšíření?</label>
<input type="checkbox" name="shop_install" value="true" id="shop_install_check" />
