<?
//var_dump($phpMSGS);
?>
<h1>Dokončení</h1>
<p>Instalace proběhla úspěšně. Nyní můžete dokončit průvodce a přejít do systému. 
Po přihlášení lze systém v administraci nastavit dle vlastních potřeb.
</p>
<br />
<h2>Přihlašovací údaje</h2>
<p>
   Uživatelské jméno: <i>admin</i><br />
   Heslo: <i>admin</i><br />
</p>
<br />
<h2>DŮLEŽITÉ:</h2>
   <ul>
      <li>Změntě heslo u administrátora!!!</li>
      <li>Odstranění adresáře <i>install</i> z kořene webu.</li>
   </ul>
<br />
<br />
<p>
   Děkujem za použití Cube-CMS<br />
   <i>Tým Cube Studio</i><br />
   <i>cms@cube-studio.cz</i>
</p>
<br />

